### PR TITLE
tests/fuzzers/bls1381: add bls fuzzer

### PR DESCRIPTION
**Pull request by holiman**
It's not a full differential fuzzer, but it would be good to get this up on oss-fuzz cc @MariusVanDerWijden

### CODE REVIEW

**Comment by MariusVanDerWijden** [comment]
Yeah I agree that getting something BLS' onto oss-fuzz is a good idea. 
I'm not sure about the usefulness though, because basically we randomly search for data that matches the high strucutural requirements of BLS (points on the curve). Additionally we run all precompiles on the same data. They need vastly different lengths of data though so we will confuse the mutator even more.
But we also don't want to give the fuzzer to much structure so it can't find issues related to structural problems...

**Comment by holiman** [comment]
Yes, I agree about all those points. I wasn't sure which was the most up-to-date version of the fuzzer(s), so I just took one and simplified it. It won't do fancy differential fuzzing, but at least we might find a crasher.

One simple way to improve it would be to split it up into 8 fuzzers, each focusing on only one precompile. That would help the corpus evolution better.
Another would be to generate some good base corpus, but IIRC we already did that way back when.

**Comment by MariusVanDerWijden** [comment]
Yeah I would vote for splitting the fuzzer into 8 smaller ones (have 8 entrypoints)

**Comment by holiman** [comment]
@MariusVanDerWijden it's now split up. However, I need to do the whole docker thingy to verify that it works with oss basebuilder stuff. Also it would be good to generate some valid points for starting. 

Any of those tasks are up for grabs btw :)

**Comment by holiman** [comment]
This passes the local checks: 
```
python infra/helper.py build_image go-ethereum && \
python infra/helper.py build_fuzzers --sanitizer address go-ethereum
python infra/helper.py check_build go-ethereum
```

**Comment by MariusVanDerWijden** [comment]
@holiman I added some corpus here: https://github.com/holiman/go-ethereum/pull/21

**Comment by holiman** [comment]
Ok, corpus merged, it build locally, can I haz a thumb?

**Review by MariusVanDerWijden — APPROVED** [review]
SGTM

**Pull request merged**
