### PR TITLE
core: avoid write existing block again

### PR DESCRIPTION
**Pull request by markya0616**

### CODE REVIEW

**Comment by karalabe** [comment]
This to me just seems to paper over the bug, not fix it. We need to find why all of a sudden this started to happen.

**Comment by fjl** [comment]
I'm looking into it.

**Comment by holiman** [comment]
> This to me just seems to paper over the bug, not fix it. We need to find why all of a sudden this started to happen.

It does fix the false positives we're getting on network splits. I'd like this merged as soon as possible.

**Comment by karalabe** [comment]
@markya0616 Hey there! Apparently this PR managed to cause a lot of headaches for us. It created a bad block deadlock during fast sync to full sync transition https://github.com/ethereum/go-ethereum/issues/15204, due to using HasBlock instead of HasBlockAndState (details in https://github.com/ethereum/go-ethereum/pull/15234).

However, block and state presence is already verified in InsertChain https://github.com/ethereum/go-ethereum/blob/master/core/blockchain.go#L931, so adding it here is just duplicating code. As such, we're going to revert this change.

Could you describe the exact use case you saw and reason you thought this would be a necessary change? That way me might try to add it in a different way that plays nice with the remainder of the code.

**Pull request merged**
