### PR TITLE
Swarm

### PR DESCRIPTION
**Pull request by nishakant001**

### CODE REVIEW

**Comment by robotally** [comment]
:exclamation: Pull request against `master` :exclamation:

| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Tue Jun 7 12:09:10 UTC 2016_

**Comment by GitCop** [comment]
Your commits seem to not adhere to the repository coding standards

 * Commit: 03b9ae7cf654571c154eb767cab43cc0c5f0de6b
  * Your commit message body contains a line that is longer than 72 characters

 * Commit: 6de197108511b8fd81b1e15e2a68827db7837b27
  * Your commit message body contains a line that is longer than 72 characters

 * Commit: f7d5ce4985258d78b1d9913f75cbd81bfa7fd29d
  * Your commit message body contains a line that is longer than 72 characters

 * Commit: e267b56c3275ae9aa43443d0022e948f0c882878
  * Commit subjects should be kept under 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by karalabe** [comment]
Not sure what you wanted to do with this PR. I assume it was an accident.

**Comment by obscuren** [comment]
Suggestion maybe? ;-)

**Pull request closed without merging**
