### PR TITLE
eth/downloader: add optional id parameter to Downloader.Cancel

### PR DESCRIPTION
**Pull request by zhiqiangxu**
This PR also removes call to d.Cancel in d.spawnSync as d.synchronise has already ensured it.

### CODE REVIEW

**Review by Mitumaru — APPROVED** [review]

**Review by Mitumaru — APPROVED** [review]

**Review by karalabe — COMMENTED** [review]
What's the purpose of this PR?

The downloader is *extremely* brittle with an insane number of cornercases handled, so unless there's something that's demonstably broken, we prefer to minimize changes, especially around stuff that can potentially hang the network.

**Comment by zhiqiangxu** [comment]
> What's the purpose of this PR?
> 
> The downloader is _extremely_ brittle with an insane number of cornercases handled, so unless there's something that's demonstably broken, we prefer to minimize changes, especially around stuff that can potentially hang the network.

If there's two concurrent call to `synchronise`, the `Cancel` call may step on each other's foot by mistake. This kind of bug is taken care of inside `concurrentFetch`, but seems not the case in `synchronise`. So I add an optional `id` parameter to `Cancel` so that if you specify an `id` parameter (only specified in `synchronise` and `concurrentFetch`), then cancel will do nothing if `id` doesn't match `cancelPeer`.

**Comment by fjl** [comment]
I'm against this change because downloader cancellation is already very complex.

**Comment by holiman** [comment]
> Before we decide whether or not to merge this PR, can we first of all clarify whether this is the expected behaviour?

Sounds reasonable. However, I agree with @fjl and @karalabe that the added complexity does not seem worth it (increases the maintenance overhead)

**Pull request closed without merging**
