### PR TITLE
all: ensure subscription is not nil

### PR DESCRIPTION
**Pull request by rjl493456442**

### CODE REVIEW

**Comment by fjl** [comment]
I don't like this PR. It makes sense to check if there is any chance the subscription might fail, but all internal subscriptions should never fail.

**Comment by rjl493456442** [comment]
Yes, the internal subscription will never fail, but normally we will return a wrapper(`SubscriptionScope`) to outside. It can happen that the returned one is nil.

**Comment by fjl** [comment]
Hmm. When does that happen?

**Comment by rjl493456442** [comment]
@fjl Not sure, in some weird corner cases

like the panic happened yesterday

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xca5c59]
goroutine 3069977 [running]:
github.com/ethereum/go-ethereum/les.(*serverHandler).broadcastHeaders(0xc001515090)
    /home/travis/gopath/src/github.com/ethereum/go-ethereum/les/server_handler.go:901 +0xb9
created by github.com/ethereum/go-ethereum/les.(*serverHandler).start
    /home/travis/gopath/src/github.com/ethereum/go-ethereum/les/server_handler.go:93 +0x6c
FAIL    github.com/ethereum/go-ethereum/les    19.858s
```

We call the `Stop` of blockchain before we create the subscriptions

**Pull request closed without merging**
