### PR TITLE
Make CGO_ENABLED=0 build again

### PR DESCRIPTION
**Pull request by holiman**
This PR removes some direct imports into CGO-land. I found this when trying to solve https://github.com/dvyukov/go-fuzz/issues/171 . 
After this fix, it's possible to build with `CGO_ENABLED=0 go-fuzz-build`, at least in the `p2p` section. 

Two remaining offenders are in `scwallet/wallet.go`: 
```golang
// determinePublicKey uses a signature and the X component of a public key to
// recover the entire public key.
func determinePublicKey(sig, pubkeyX []byte) ([]byte, error) {
	for v := 0; v < 2; v++ {
		sig[64] = byte(v)
		pubkey, err := crypto.Ecrecover(DerivationSignatureHash[:], sig)
		if err == nil {
			if bytes.Equal(pubkey, pubkeyX) {
				return pubkey, nil
			}
		} else if v == 1 || err != secp256k1.ErrRecoverFailed {
			return nil, err
		}
	}
	return nil, ErrPubkeyMismatch
}

// makeRecoverableSignature uses a signature and an expected public key to
// recover the v value and produce a recoverable signature.
func makeRecoverableSignature(hash, sig, expectedPubkey []byte) ([]byte, error) {
	for v := 0; v < 2; v++ {
		sig[64] = byte(v)
		pubkey, err := crypto.Ecrecover(hash, sig)
		if err == nil {
			if bytes.Equal(pubkey, expectedPubkey) {
				return sig, nil
			}
		} else if v == 1 || err != secp256k1.ErrRecoverFailed {
			return nil, err
		}
	}
	return nil, ErrPubkeyMismatch
}
```
@gballet those `secp256k1.ErrRecoverFailed` are not as trivial to replace. Either we can hardcode the actual error message, or maybe define them in a nocgo library import? Are they really used -- what other types of errors would occur here to necessitate this?

### CODE REVIEW

**Comment by karalabe** [comment]
@holiman @gballet Yeah, this code is a bit funky, we can rework it to not use the error at all, rather try recovering with both `v == 0` and `v == 1` and if both fails, return the error. No need to explicitly match on the returned error. That would solve it.

**Comment by karalabe** [comment]
I.e. The code doesn't **need** the specific error, it's just used because the original author implemented the code this way.

**Comment by holiman** [comment]
@karalabe do you mean like this? 
```golang

func determinePublicKey(sig, pubkeyX []byte) ([]byte, error) {
	for v := 0; v < 2; v++ {
		sig[64] = byte(v)
		pubkey, err := crypto.Ecrecover(DerivationSignatureHash[:], sig)
		if err == nil && bytes.Equal(pubkey, pubkeyX) {
			return pubkey, nil
		}
	}
	return nil, ErrPubkeyMismatch
}
```

**Comment by holiman** [comment]
added fixes in the scwallet area and also in `ipc`, where a tiny import is used to check the size of the max length for a ipc path. Maybe that can be done more elegantly than copy-pasting an entire file

**Comment by holiman** [comment]
One remaining big chunk of C comes from `tracers` using duktape... :/

**Comment by holiman** [comment]
I now modified the rpc section so that only the actual constant is moved into a separate file, instead of duplicating the entre unix listener code

**Comment by karalabe** [comment]
@holiman Your fix is not fully correct though, as you are completely ignoring any returned error now and just assume it's a pubkey mismatch.

I think we need 3 cases:

 * Try to recover `v==0` and `v==1` and return either of them that succeeded.
 * If neither match but one returns an error, return that.
 * If neither batch but also neither error out, only then return ErrPubkeyMismatch.

At least this would be the same behavior as the original code.

**Comment by holiman** [comment]
@karalabe done. I also removed the copy-paste so that the little loop is only in one place. Unfortunately, there are no tests for these two functions...

**Pull request merged**
