### PR TITLE
Enable constantinople on Ropsten testnet

### PR DESCRIPTION
**Pull request by eosclassicteam**
To-do: Enable constantinople on rinkeby testnet also 

cc @karalabe @holiman

### CODE REVIEW

**Comment by eosclassicteam** [comment]
@holiman Question, do we need to purge node's database in order to make it work after the fork?

**Comment by karalabe** [comment]
@eosclassicteam No, fork rules can be changes and new ones are picked up automatically as long as the block hasn't passed yet. If it did, geth refuses to start.

**Comment by eosclassicteam** [comment]
@karalabe Is there any ETA date or block num for Rinkeby?

**Comment by karalabe** [comment]
Post devcon really. I don't see any reason to fork before that. Since it's a pure geth network, it won't find consensus issues either way, so there's no reason to break Rinkeby if something slips in and a fix is needed for Ropsten.

**Comment by ligi** [comment]
For future reference - here the meeting notes of the core devs call where the block-number was agreed on: https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%2047.md#constantinople

**Pull request merged**
