### PR TITLE
accounts/abi/bind/backends: fix AdjustTime to respect Fork

### LINKED ISSUE #25220: SimulatedBackend: Cannot use `AdjustTime` after `Fork`
#### System information

OS & Version: Linux
Commit hash : de1cecb22e2a18ad70d4cb92bee122f4549c5b79 (master)

#### Expected behaviour
When using `AdjustTime` directly after a `Fork`, the following `Commit` should still create a block in the side-chain, the same goes for all other `AdjustTime` and `Commit` calls afterwards.

#### Actual behaviour
`AdjustTime` uses the current head (`b.blockchain.CurrentBlock()`), which is the canonical head and thus not the block we just rolled back to when calling `Fork`. Thus the following call to `Commit` creates a block with parent `h3` instead of with parent `h1`, resulting in the same bahavior as if `Fork` was never called.

##### Fix
Use `b.blockchain.GetBlockByHash(b.pendingBlock.ParentHash)` instead of `b.blockchain.CurrentBlock()` in `SimulatedBackend.AdjustTime`.

#### Steps to reproduce the behaviour
```golang
// Create a new SimulatedBackend (should be possible without allocations)
sb := backends.NewSimulatedBackend(
		core.GenesisAlloc{},
		30_000_000,
	)
sb.Commit() // h1
h1 := sb.Blockchain().CurrentHeader().Hash()
sb.Commit() // h2
sb.Fork(context.Background(), h1)
sb.AdjustTime(1 * time.Second)
sb.Commit() // Should have h1 as parent but has h2
```

### PR DESCRIPTION
**Pull request by lightclient**
closes #25220

### CODE REVIEW

**Review by MariusVanDerWijden — APPROVED** [review]
SGTM

**Comment by MariusVanDerWijden** [comment]
`Rollback()` also ignores `Fork()`, but I think that is okay because it allows me to rollback the fork command if I need to

**Comment by DragonDev1906** [comment]
Interesting point, `Rollback()` ignoring `Fork()` does mean that you can undo the last `Fork` call by rolling back the entire side-chain (only keeping the canonical chain). However, it doesn't match the comment on `Rollback`:

> Rollback aborts all pending transactions, reverting to the last committed state.

Something like the following would, for example, revert the call to `Fork`, too, even though the last committed state is in the side-chain:
```golang
sb.Commit()
sb.Commit()
sb.Commit()
sb.Fork(...) // Back to the first Commit()
sb.Commit()
sb.SendTransaction(...)
sb.Rollback()
```

According to the comment on `Rollback` this should only remove the `SendTransaction` call, the current implementation goes back to the canonical chain and thus removes all calls after `Fork` unless that is the canonical chain (in this case `Fork`, the last `Commit` and `SendTransaction`). Additionally, the current implementation rolls back all Forks (since you could call `Fork` with a block that is already in a side-chain. Wouldn't it be more intuitive if `Rollback` either undoes the last `Fork` or doesn't bother with `Fork` at all (like the comment suggests). The latter would probably be easier to implement, since it could just use `b.pendingBlock.ParentHash`.

Another thing to consider is, that (with the current implementation) you'd have to use `Fork` (on the latest block of the side-chain) to undo pending transactions, because otherwise you'd roll back to the canonical chain. To undo a call to `Fork` (like rollback currently does) you could always call `sb.Fork(ctx, sb.Blockchain().CurrentHeader().Hash())`, which could also be a `RollbackToCanonicalChain` function.

(Just my 2ct, I'd be fine with both versions, though I'd suggest to change the rollback comment if it rolls back any Fork calls to go to the canonical chain)

**Comment by holiman** [comment]
@lightclient please rebase

**Review by holiman — APPROVED** [review]

**Pull request merged**
