### PR TITLE
p2p/nat: fix UPnP auto discovery

### LINKED ISSUE #890: UPnP not discovered
I built v0.9.18 from source on linux amd64.

I0509 13:47:01.427490   19131 nat.go:94] network port 30303 could not be mapped: no UPnP or NAT-PMP router discovered

However, I'm pretty sure my router has UPnP enabled, http://i.imgur.com/mf3xcD4.png

### PR DESCRIPTION
**Pull request by fjl**
This is supposed to fix #890. The SOAP communication was actually working, the bug was in the initialization.

### CODE REVIEW

**Comment by obscuren** [comment]
Please fix

**Comment by etherum** [comment]
Please revert this patch and reapply one that doesn't include 150,000 changes.

**Comment by fjl** [comment]
The additions are due to the goupnp bump pulling in `golang.org/x/net` and `golang.org/x/text`.

**Comment by obscuren** [comment]
@fjl Nothing. @etherum doesn't know what he's talking about.

**Pull request merged**
