### PR TITLE
eth: set networkID to chainID by default

### PR DESCRIPTION
**Pull request by fjl**
This improves the user experience when creating a private network
because the `--networkid` flag doesn't need to be specified anymore.

### CODE REVIEW

**Comment by karalabe** [comment]
Linter failed

**Comment by fjl** [comment]
cmd/geth tests are failing for the case where genesis.json doesn't contain chainID. Unsure what to do in that case, maybe default to networkID zero, or one?

**Comment by karalabe** [comment]
Perhaps it's better to just reject starting up altogether. Lets try and drop ancient modes of operation. (i.e. add chainid into the tests, leave behavior as is).

**Comment by karalabe** [comment]
Ok, leave behavior as is = fix the crash so it refuses to start, rejecting a non-set chainid.

**Comment by fjl** [comment]
Hmm, I'm not sure. If you configure a network without replay protection, the chainId is not needed.
Various bits of go-ethereum assume that chainID is zero when it's unset.

I think we need a better fix where we validate chainID when you initialize from genesis.json.

**Comment by holiman** [comment]
Requires a rebase

**Comment by holiman** [comment]
We probably discussed this at a couple of triage sessions, and for some reason never decided to merge it. But we also never clearly wrote down what the problem is. (Except the ` If you configure a network without replay protection,...` thing -- but is that it?)

**Comment by abebeos** [comment]
(You outperformed solana/polkadot in "milestone-hopping")

* Does this change break existent installations / documentations?
  * YES: => close
  * NO: => merge it

```
# Creating a private network

create-network-command --chainID=my-chain-id --networkID=my-network-id

# with this PR merged

create-network-command --chainID=my-chain-id
```

I like it! Should be merged (if not breaking)

**Comment by karalabe** [comment]
@abebeos Please stop spamming our PRs ro we'll ban your account. Thank you

**Comment by karalabe** [comment]
This definitely goes on Twitter :)

**Comment by nflaig** [comment]
sad to see this https://github.com/ethereum/go-ethereum/pull/20271#issuecomment-1476362144 on a ethereum project, and to be honest everything until this comment can not be considered spam, it is called feedback

@abebeos feel free to join us at [Lodestar](https://github.com/ChainSafe/lodestar) if you want to contribute to Ethereum. You don't need to be a maintainer, have experience or any other qualifications to participate. We appreciate everyones opinion/input and glad to provide guidance if needed 🙏

**Comment by abebeos** [comment]
> This definitely goes on Twitter :)

Nice, maybe add this:

The Ethereum project-lead @karalabe fails to comprehend that `go-ethereum` is an open project and about "decentralization" in its very core. Centralizing the development-process around some core-developers that keep insider-knowledge to themselves does no good. It blocks contributions. Even people with decades of IT experience cannot contribute easily if information is withheld (e.g. processing issues in meetings, without feeding results back to the issue-tracker).

As for "The PR is open because Felix wanted to leave it open." => This PR is "junio-dev" level. Estimated effort to analyse & merge or close: 2 to 4 hours.

Have you people no professional pride to keep it 3,5 years open?

---

(@nflaig , ty for the invite, will surely take a look in the next days)

**Comment by fjl** [comment]
If I may say something (it is my PR after all), the reason why this seemingly-trivial change did not get merged immediately is that caused some test failures at the time, which were not trivial to resolve. The technical issue here is that a `chainID` might not be defined, but the `networkID` *must* be defined. Some amount of refactoring would be needed to get a nice error message to the user in this case, or we could define a default. I just moved on to other more pressing things and kept this around because it is kind of a nice idea.

**Comment by abebeos** [comment]
@fjl , nothing I wrote was "against" you. I understand that trivial changes sometimes spawn follow-up issues (I did not count those into the "2 to 4" hours estimation).

>  I just moved on to other more pressing things and kept this around because it is kind of a nice idea.

I'd say that standard-procedure would be here to file an issue, summarize everything there and point to the old (and closed) PR.

Anyways, all good from my side!

No hard feelings.

**Comment by abebeos** [comment]
> Since it seems you care about this functionality to some extent, why not give this problem a try yourself?

I care mostly about "closing an old PR", though I found the described UX enhancement positive/rational.

Quick pass:

Problem: my intuition/gut-feeling tells me to avoid changing the underlying sources just to enable this PR (risk of follow-up work)

### Possible Solution

As this is about `user experience when creating a private network`

* leave existent cli parameter logic as-is (= do not risk to break something)
* introduce a new cli parameter dedicated to private networks
  * `--privateNetworkID` or  
  * `--privateChainID` or  
  * `--privateID` or
  * (whatever fits more)
* document that users have the option to start a private network with just this option.

**Comment by abebeos** [comment]
@fjl , going through the doc https://geth.ethereum.org/docs/fundamentals/private-network, it looks simple enough.

I now understand that the issue is about

* drop the need for `--networkid` for private network
  * use `chainid` from the config within `genesis.json`

So my possible solution within https://github.com/ethereum/go-ethereum/pull/20271#issuecomment-1476736476 is nonsense

Me got curious enough now, will look more at this those days.

**Comment by abebeos** [comment]
I filed an issue on my fork, 'cause I need more control over my writings:

https://github.com/abebeos/go-ethereum/issues/1

(this is additionally a showcase for "how to evolve/document an issue, instead of keeping the knowledge within comments or brains)

**Comment by abebeos** [comment]
> cmd/geth tests are failing for the case where genesis.json doesn't contain chainID - https://github.com/ethereum/go-ethereum/pull/20271#issuecomment-553370114

=> `chainID` should become mandatory

> Perhaps it's better to just reject starting up altogether. Lets try and drop ancient modes of operation. - https://github.com/ethereum/go-ethereum/pull/20271#issuecomment-553376401

=> drop 'ancient' modes of operation (use usual deprecation process)

> Hmm, I'm not sure. If you configure a network without replay protection, the chainId is not needed.
> Various bits of go-ethereum assume that chainID is zero when it's unset. - https://github.com/ethereum/go-ethereum/pull/20271#issuecomment-553385711

After reading a little bit, it has become clear to me that "chainID" should be a "must" configuration.

So (as hard as it may feel at this point to me...), agreeing with @karalabe (re `chainID`).

=> Issue: Make configuration of `chainID` mandatory

---

Still, there is the issue of changing the default-behaviour of `--networkID`. Not sure if this is so easy to deprecate.

=> Issue: Consider deprecation of `--networkID=1` default

---

Once those issues are resolved, this PR should be free to proceed.

**Comment by ansermino** [comment]
I would just like to clarify that the views expressed by @nflaig are not those of @ChainSafe or Lodestar. We believe respectful discourse is critical to a healthy community, and a cornerstone of Ethereum's values. Disagreements are natural, but never justify belittlement or harassment of anyone.

**Comment by abebeos** [comment]
> I would just like to clarify that the views expressed by @nflaig are not those of @ChainSafe or the Lodestar team. 

And who are you, Mr. "Dazed and confuzed, but trying to continue" who "Speaks for @ChainSave / the Lodestar Team"?

> We believe respectful discourse is critical to a healthy community, and a cornerstone of Ethereum's values. Disagreements are natural, but never justify belittlement or harassment of anyone.

You're late to the party, we're all friends here again and focus on technicals. "belittlement or harassment" exists only in your "dazed and confuzed" (as you self-assess) mind.

Me totally dazed and confused now!

Now go away, or stay in-topic.

(@nflaig , hope you do not get into trouble for your rational & friendly words)

**Comment by abebeos** [comment]
(@ansermino , you've literally dazed and confused me. I still struggle to understand your https://github.com/ethereum/go-ethereum/pull/20271#issuecomment-1478409189 - need more coffee & glycose, again...)

**Comment by abebeos** [comment]
@fjl , could you please trigger the ci run again? It looks you're not using github actions, so it's not trivial for me to do.

**Comment by abebeos** [comment]
> There is no point in triggering the run again. The result will not change.

The result is not visible anymore.

**Comment by fjl** [comment]
If you just want to see this patch fail the tests, you can run the tests locally.

**Comment by abebeos** [comment]
> If you just want to see this patch fail the tests, you can run the tests locally.

Naturally, but I am "off-code" for this issue.

**Comment by abebeos** [comment]
OT follow-up re chainsafe: 

- https://github.com/ChainSafe/lodestar/issues/5291

**Comment by abebeos** [comment]
Does this never end? @nflaig updated the comment:
> I am **NOT** in support of any of the harassment done by @abebeos,
https://github.com/ethereum/go-ethereum/pull/20271#issuecomment-1476544930

Nice, now I am the "harasser", because I reacted to an abusive project-lead within a core Ethereum project.

But the only thing that could be categorized as "harassment" is this:

> @abebeos Please stop spamming our PRs ro we'll ban your account. Thank you

Now @nflaig essentially confirms something, without knowing it:

> That being said, I specifically mentioned that the comments **BEFORE** [#20271 (comment)](https://github.com/ethereum/go-ethereum/pull/20271#issuecomment-1476362144) meaning this [#20271 (comment)](https://github.com/ethereum/go-ethereum/pull/20271#issuecomment-1475395475) and that [#20271 (comment)](https://github.com/ethereum/go-ethereum/pull/20271#issuecomment-1476232115) can not be considered spam (or at least not something people should be banned for) and I still have that **personal** opinion.
https://github.com/ethereum/go-ethereum/pull/20271#issuecomment-1476544930

@nflaig , the logical conclusion is that you assess this here:

> @abebeos Please stop spamming our PRs ro we'll ban your account. Thank you
https://github.com/ethereum/go-ethereum/pull/20271#issuecomment-1476362144

as harassment.

Of course you do not have the spine to write this clearly, similar to @ansermino

Now, I am used to spineless folks within the IT domain (especially crypto, and much more Ethereum).

I am, however, not used to people bringing me to the level of disgust.

You (@nflaig , @ansermino ) are close to it.

(archive title: the never ending circus of the spineless Ethereum Satellites)

P.S.: Yes, my reply getting the title of "spammer" and "harasser" is to hand out titles like "circus", "satellites", and "spineless". This is my ethical right.

P.S. 2: trying to finally go on with this non-updated PR that has no CI run.

**Comment by abebeos** [comment]
spawned issue:

- https://github.com/ethereum/go-ethereum/issues/26952

**Comment by karalabe** [comment]
@nflaig You're not used to toxic personalities and that's ok. I was harsh from the get go because I know the signs and saw where this is going. The guy is not interested in contributing, he is compiling a list of why every crypto project is bad and he will push the envelope on anyone willing until he finds a breaking point to report on. The guy is simply malicious and everybody's time is too valuable to spend on him. It doesn't even matter how good his contributions would be, you do not want to allow this level of toxicity to stay in your community, it would backfire badly long term.

I'm sorry if I came out as a bad person, but somebody needs to take a stance and I'm willing to be that one to keep our environment friendly (-er at least). Take care, Peter.

**Comment by holiman** [comment]
@abebeos I've put you on a 7-day block for now. You are welcome back in a week, if you still want to contribute, but for now, we want to keep the noise down.

**Comment by abebeos** [comment]
> @abebeos I've put you on a 7-day block for now. You are welcome back in a week, if you still want to contribute, but for now, we want to keep the noise down.

I can deal with an incompetent team-lead, some mediocre devs sticking together, weak personalities etc.

But can't deal with IT-fascists.

So, fuck off, fucking fascists.

**Comment by abebeos** [comment]
Note to readers: I deleted my comments in this PR and this repo myself.

**Pull request closed without merging**
