### PR TITLE
core, txpool: less allocations when handling transactions

### PR DESCRIPTION
**Pull request by MariusVanDerWijden**
```
BenchmarkPendingDemotion100-16       	 6804576	       173 ns/op	       0 B/op	       0 allocs/op
BenchmarkPendingDemotion1000-16      	 6309848	       174 ns/op	       0 B/op	       0 allocs/op
BenchmarkPendingDemotion10000-16     	 7006021	       176 ns/op	       0 B/op	       0 allocs/op
BenchmarkFuturePromotion100-16       	358416355	         3.38 ns/op	       0 B/op	       0 allocs/op
BenchmarkFuturePromotion1000-16      	365451259	         3.37 ns/op	       0 B/op	       0 allocs/op
BenchmarkFuturePromotion10000-16     	377171361	         3.33 ns/op	       0 B/op	       0 allocs/op
BenchmarkPoolBatchInsert100-16       	      38	  27382746 ns/op	  607269 B/op	    8177 allocs/op
BenchmarkPoolBatchInsert1000-16      	       5	 259864088 ns/op	 5861854 B/op	   83225 allocs/op
BenchmarkPoolBatchInsert10000-16     	       1	2085832352 ns/op	51360392 B/op	  690243 allocs/op
BenchmarkPoolBatchInsert100000-16    	       1	17361944530 ns/op	445913240 B/op	 5550197 allocs/op
```
Master
```
BenchmarkPendingDemotion100-16      	 5902473	       183 ns/op	       0 B/op	       0 allocs/op
BenchmarkPendingDemotion1000-16     	 6397833	       178 ns/op	       0 B/op	       0 allocs/op
BenchmarkPendingDemotion10000-16    	 6575794	       176 ns/op	       0 B/op	       0 allocs/op
BenchmarkFuturePromotion100-16      	389451097	         2.96 ns/op	       0 B/op	       0 allocs/op
BenchmarkFuturePromotion1000-16     	371748506	         2.96 ns/op	       0 B/op	       0 allocs/op
BenchmarkFuturePromotion10000-16    	404261654	         3.01 ns/op	       0 B/op	       0 allocs/op
BenchmarkPoolBatchInsert100-16      	      39	  27335098 ns/op	  633578 B/op	    9082 allocs/op
BenchmarkPoolBatchInsert1000-16     	       6	 216564796 ns/op	 6051392 B/op	   94093 allocs/op
BenchmarkPoolBatchInsert10000-16    	       1	2149670407 ns/op	53134952 B/op	  750930 allocs/op
```

### CODE REVIEW

**Comment by MariusVanDerWijden** [comment]
Using this test for master
```go
func BenchmarkTxListAdd(t *testing.B) {
	// Generate a list of transactions to insert
	key, _ := crypto.GenerateKey()

	txs := make(types.Transactions, 100000)
	for i := 0; i < len(txs); i++ {
		txs[i] = transaction(uint64(i), 0, key)
	}
	// Insert the transactions in a random order
	list := newTxList(true)
	priceLimit := big.NewInt(0).SetUint64(DefaultTxPoolConfig.PriceLimit)
	t.ResetTimer()
	for _, v := range rand.Perm(len(txs)) {
		list.Add(txs[v], DefaultTxPoolConfig.PriceBump)
		list.Filter(priceLimit, DefaultTxPoolConfig.PriceBump)
	}
}
```
and this for this branch
```go
func BenchmarkTxListAdd(t *testing.B) {
	// Generate a list of transactions to insert
	key, _ := crypto.GenerateKey()

	txs := make(types.Transactions, 100000)
	for i := 0; i < len(txs); i++ {
		txs[i] = transaction(uint64(i), 0, key)
	}
	// Insert the transactions in a random order
	list := newTxList(true)
	priceLimit := DefaultTxPoolConfig.PriceLimit
	t.ResetTimer()
	for _, v := range rand.Perm(len(txs)) {
		list.Add(txs[v], DefaultTxPoolConfig.PriceBump)
		list.Filter(priceLimit, DefaultTxPoolConfig.PriceBump)
	}
}
```
I got the following results:
```
master
BenchmarkTxListAdd-16    	1000000000	         0.0851 ns/op	       0 B/op	       0 allocs/op
tx_reduceallocsv2
BenchmarkTxListAdd-16    	1000000000	         0.0561 ns/op	       0 B/op	       0 allocs/op
```

**Comment by holiman** [comment]
I'm golfing away
```
BenchmarkPoolBatchInsert100-6                 67          19192397 ns/op          373139 B/op       5148 allocs/op
BenchmarkPoolBatchInsert1000-6                 6         190592352 ns/op         3704962 B/op      51542 allocs/op
BenchmarkPoolBatchInsert10000-6                1        2091724254 ns/op        33357816 B/op     498078 allocs/op
```

**Comment by MariusVanDerWijden** [comment]
Now down to
```
BenchmarkPoolBatchInsert100-16    	      37	  27332816 ns/op	  379164 B/op	    5002 allocs/op
BenchmarkPoolBatchInsert1000-16    	       6	 217340430 ns/op	 3701454 B/op	   50551 allocs/op
BenchmarkPoolBatchInsert10000-16    	       1	2080770716 ns/op	33212728 B/op	  478450 allocs/op
```

**Comment by MariusVanDerWijden** [comment]
With the new test cases we spot the big memory leak: 
```
BenchmarkPoolBatchInsert100-16                        43          27457989 ns/op          378687 B/op       5002 allocs/op
BenchmarkPoolBatchInsert1000-16                        6         203928329 ns/op         3698616 B/op      50541 allocs/op
BenchmarkPoolBatchInsert10000-16                       1        1967694228 ns/op        33202688 B/op     478333 allocs/op
BenchmarkPoolBatchLocalInsert100-16                   57          69215142 ns/op         2583880 B/op       5124 allocs/op
BenchmarkPoolBatchLocalInsert1000-16                   6         880639775 ns/op        35409178 B/op      51022 allocs/op
BenchmarkPoolBatchLocalInsert10000-16                  1        32001544662 ns/op       1465866464 B/op   554108 allocs/op
```
```
BenchmarkPoolBatchInsert100-16                        66          27111004 ns/op          614724 B/op       9222 allocs/op
BenchmarkPoolBatchInsert1000-16                        6         206998251 ns/op         6050997 B/op      94097 allocs/op
BenchmarkPoolBatchInsert10000-16                       1        2068979714 ns/op        53141072 B/op     750973 allocs/op
BenchmarkPoolBatchLocalInsert100-16                   52          42339111 ns/op         3612176 B/op     338515 allocs/op
BenchmarkPoolBatchLocalInsert1000-16                   5         200485642 ns/op         6020937 B/op      89963 allocs/op
BenchmarkPoolBatchLocalInsert10000-16                  1        109329517576 ns/op      14425409792 B/op        1617470241 allocs/op
```

**Comment by MariusVanDerWijden** [comment]
```
> benchcmp master tx_reduceallocsv2
benchcmp is deprecated in favor of benchstat: https://pkg.go.dev/golang.org/x/perf/cmd/benchstat
benchmark                                 old ns/op        new ns/op      delta
BenchmarkPoolBatchInsert100-16            26964301         27592412       +2.33%
BenchmarkPoolBatchInsert1000-16           218805225        224426000      +2.57%
BenchmarkPoolBatchInsert10000-16          2087232704       2088864320     +0.08%
BenchmarkPoolBatchLocalInsert100-16       21966964         24972428       +13.68%
BenchmarkPoolBatchLocalInsert1000-16      2551680926       239331292      -90.62%
BenchmarkPoolBatchLocalInsert10000-16     110797073688     3842275783     -96.53%

benchmark                                 old allocs     new allocs     delta
BenchmarkPoolBatchInsert100-16            9090           5003           -44.96%
BenchmarkPoolBatchInsert1000-16           94089          50540          -46.28%
BenchmarkPoolBatchInsert10000-16          750991         478352         -36.30%
BenchmarkPoolBatchLocalInsert100-16       9068           5000           -44.86%
BenchmarkPoolBatchLocalInsert1000-16      34290177       49235          -99.86%
BenchmarkPoolBatchLocalInsert10000-16     1617469794     491134         -99.97%

benchmark                                 old bytes       new bytes     delta
BenchmarkPoolBatchInsert100-16            633746          377866        -40.38%
BenchmarkPoolBatchInsert1000-16           6051782         3697901       -38.90%
BenchmarkPoolBatchInsert10000-16          53142120        33209024      -37.51%
BenchmarkPoolBatchLocalInsert100-16       644781          391006        -39.36%
BenchmarkPoolBatchLocalInsert1000-16      311539462       3580522       -98.85%
BenchmarkPoolBatchLocalInsert10000-16     14425394808     36389416      -99.75%
```
most additional bytes spent is due to the benchmark being dependent on `b.N` e.g. 
`BenchmarkPoolBatchLocalInsert100-16` runs on master with `b.N = 51` and on this branch with `b.N = 63` which means this branch inserts 1200 transactions more (12 * 100). 

The overhead of linearly searching the pool can be seen on the global batch insert benchmarks and should be around ~1-2%, since we reduce the allocations by ~50% this small regression should be negligible since we reduce the need for the garbage collector to kick in drastically.

**Comment by holiman** [comment]
Seems one of my commits wasn't go-formatted properly :)

**Comment by holiman** [comment]
This is now up for testing on prod: https://geth-bench.ethdevops.io/d/QC1Arp5Wk/single-geth?orgId=1&var-host=bootnode-aws-eu-west-1-001&var-percentile=50&from=1592490879131&to=now -- graph from 30 minutes before updating to this PR

**Comment by holiman** [comment]
Some comparisons with other bootnodes, 7 days. This PR (on `aws-eu-west`) was swapped in ~3 days ago, and is shown in green. This is the alloc-count
Screenshot_2020-06-21 Dual Geth - Grafana(1)
Screenshot_2020-06-21 Dual Geth - Grafana

This is the alloc-count for all bootnodes, last 12 hours, stacked. 
Screenshot_2020-06-21 Multi Geth - Grafana

This PR is the third from the bottom, light turqoise. 
And finally, the legends showing the average and current, last `12` hours: 

Screenshot_2020-06-21 Multi Geth - Grafana(1)
Same for 2 days: 

Screenshot_2020-06-21 Multi Geth - Grafana(2)

**Comment by karalabe** [comment]
Ooooh, this looks super nice :)

**Comment by holiman** [comment]
@MariusVanDerWijden do you have time to rebase this now that we merged the other one?

**Comment by MariusVanDerWijden** [comment]
@holiman yep, rebased it onto current master now

**Comment by fjl** [comment]
Reverted in https://github.com/ethereum/go-ethereum/commit/bcb308745010675671991522ad2a9e811938d7fb because this PR handles account balances as uint64, which is not OK without overflow checks.

**Pull request merged**
