### PR TITLE
Update ethtest default path for BlockTests

### LINKED ISSUE #1472: ethtest default path to BlockTests
please change ethtest default path to BlockTests
from test/BlockTests to test/BlockchainTests

### PR DESCRIPTION
**Pull request by tgerring**
Closes #1472

### CODE REVIEW

**Comment by tgerring** [comment]
@Gustav-Simonsson FYI

**Comment by Gustav-Simonsson** [comment]
IMO it's better to use the names / directories directly as they are in the tests repo. That way it's more similar across client implementations and a bit simpler when cross-checking between them.

**Comment by fjl** [comment]
What is the best resolution here? This is really hard to decide. We can't actually run the tests in the `BlockTests` directory, but it does add some confusion to support it as an alias for `BlockchainTests`.

@winsvega: how important is this to you?

**Comment by tgerring** [comment]
This PR add us basic flexibility for name conflicts for what is effectively a convenience function, perhaps used by no one? `go test` works equally as well and doesn't require building `ethtest` as a separate step. The output is different, obviously

**Pull request merged**
