### PR TITLE
Allow Zero Gas Price txns for certain chains

### PR DESCRIPTION
**Pull request by vdamle**
* Introduces a chain configuration to indicate zero gas price chain
  (does not require baseFee for transactions)
* Uses the config to check and handle transaction inclusion, state
  validation, header validation.

Ref: https://github.com/ethereum/go-ethereum/issues/24966

### CODE REVIEW

**Comment by karalabe** [comment]
This change set kind of highlights why we don't want to accept it. First up, it accidentally (?) disabled part of London that was not about the base fee, rather about refunds.

Secondly, it does a strange hack to ignore fee checks here and there, but still operate as if the base fee was in there. That could end up causing serious issues within the EVM where the tx thinks it paid a base fee, but in reality it did not because it was ignored. Such a network could have very nasty runtime bugs on the contract layer in the long term. Transactions still have the base fee and can set it arbitrarily, but it is just ignored. Tooling all around that would go haywire with conflicting information wrt submitted and executed transactions.

I'm sorry, but Ethereum took the design decision to go with 1559 and the concept of base fees and Geth will follow that design space. We don't have the capacity - nor willingness - to maintain code for non-Ethereum networks. Not out of any particular malice, rather because every consensus change is a risk for Ethereum that we don't want to take. You are obviously free to make arbitrary modifications to your fork of Geth, but we can't help maintaining it.

**Comment by vdamle** [comment]
> First up, it accidentally (?) disabled part of London that was not about the base fee, rather about refunds.

@karalabe Sorry that was an error which I overlooked. Thank you for the additional explanation, I understand your concerns around runtime bugs with the above change proposal.

The other route I explored and which you called out in your issue comment was setting `baseFee` to `0`. Would this be an acceptable path?

**Comment by Mouradif** [comment]
I would be very eager to know the answer to that last question as well.

**Comment by Ilaieri** [comment]
Hi @vdamle I've just seen this and was interested in using it, however the current version of geth has changed the tx_pool that you modified into legacypool. Is there any chance you could point me towards how to implement this in the latest release of geth?

**Pull request closed without merging**
