### PR TITLE
[core] use interface for ApplyTransaction to allow mocking in testing.

### PR DESCRIPTION
**Pull request by krasi-georgiev**
closes https://github.com/ethereum/go-ethereum/issues/26278

cc @holiman

### CODE REVIEW

**Comment by karalabe** [comment]
Ahm, hmm... :D 

So, I don't really understand what this helps with. I mean, sure, you can mock out statedb, but a statedb can be backed by a memory database, so there's no externality either way. I'm not really sure there's anything to gain by working around it. The downside is an extra redirection and interface, which is very annyoing. The upside is... unsure what... not performance, not really cleaner code... anything to balance the downside out?

**Comment by krasi-georgiev** [comment]
NewEVM already accepts an interface so the only redirection is in applyTransaction.
I will try using a memory db in the tests and will see if it will work.

Btw Why did you say that using an interface annoying? No other code requires any changes and you can still pass the same StateDb Struct. I imagine that even if can use a memory db to set some state it will require way too many lines of code than just mocking the interface.

**Comment by krasi-georgiev** [comment]
just had another look at the implementation of StateDb and its use in the EVM and I am even more convinced that without an interface it would be quite difficult if not impossible to set some predefined state vs a mock interface.

It looks like this is the exact reason why the EVM initialization accepts an interface and not the StateDB struct directly.

**Comment by krasi-georgiev** [comment]
will re-open if needed

**Pull request closed without merging**
