### PR TITLE
mobile: fix typo (Ethereun -> Ethereum)

### PR DESCRIPTION
**Pull request by ligi**

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 34e0e4c9b8c3a9a8087346d5f62022695d214053
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by fjl** [comment]
argh, didn't check the base branch

**Comment by fjl** [comment]
Please resubmit against the master branch.

**Comment by ligi** [comment]
ack

**Pull request merged**
