### PR TITLE
Light: GetTxStatus/TxStatus web3 api implementation

### PR DESCRIPTION
**Pull request by cocoahuke**
[-> Light Ethereum Subprotocol (LES) introduction](https://github.com/zsfelfoldi/go-ethereum/wiki/Light-Ethereum-Subprotocol-%28LES%29)

So now able to retrieve status of transaction by given hash, write into database after transaction verified status as "Included", you can query transaction corresponding block after that.
You need rebuild your **geth** to get it work.

I have reviewed contributing guidelines.

## New Web3 API definition
**GetTransactionStatus(ctx context.Context, hash common.Hash) (core.TxStatus, error)**
The value of core.TxStatus can refer to the following:
```
TxStatusUnknown                            //0
TxStatusQueued                             //1
TxStatusPending                            //2
TxStatusIncluded                           //3
```

##### Full Node - Generated a transaction hash
```
> web3.eth.sendTransaction({from.....
0x94d621916000a92db27c2a08dfe2950947a80e7d69c9eaa5ef5135ed977b1631
```
##### Light Client - Retrieve current state: Pending
```
> web3.eth.getTransactionStatus("0x94d621916000a92db27c2a08dfe2950947a80e7d69c9eaa5ef5135ed977b1631")
2
```
##### Full Node - Start mining work until transaction is finalised
```
> web3.miner.start()
...
```
##### Light Client - So now you should get status(3): Included
By the time, linking between this transaction hash and corresponding block would be verified and write into database, that means **web3.eth.getTransactionReceipt** or **web3.eth.getTransaction** etc api are worked again on Light client.
```
> web3.eth.getTransactionStatus("0x94d621916000a92db27c2a08dfe2950947a80e7d69c9eaa5ef5135ed977b1631")
3
> web3.eth.getTransaction("0x94d62191.....
{
  blockHash: "0x83a965c....
  blockNumber: ...
  from: ...
...
> web3.eth.getTransactionReceipt("0x94d62
{
  blockHash: "0x83a96....,
  blockNumber: ...
  contractAddress: ...
...
````
## Still need to improve

**GetTxStatus/TxStatus** retrieve transaction status, block hash and block index from a full node by a given transaction hash, these information retrieve from full node is lacking of relevant data to verify.

My current solution is simple (Code at odr_util.go):
Only start verification after it's been "included", to proof a transaction is valid:
  Retrieve BlockHash/BlockIndex -> Retrieve and verify BlockBody -> Verify given transaction hash whether included

Need support verify through pending transactions in order to be **Fast verification**
Require more test and share your ideas!

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 6bbf4b96c95c9598b9565c75062cac5a29ce4970
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 6bbf4b96c95c9598b9565c75062cac5a29ce4970
  * Commits must be prefixed with the package(s) they modify

 * Commit: ac159bc501be283ba1fb983e36ad6beb244b6bd6
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 6bbf4b96c95c9598b9565c75062cac5a29ce4970
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 9b8afba4bcf412eef4722b62e90c46a435ea15c1
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 9b8afba4bcf412eef4722b62e90c46a435ea15c1
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 9b8afba4bcf412eef4722b62e90c46a435ea15c1
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 9b8afba4bcf412eef4722b62e90c46a435ea15c1
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 9b8afba4bcf412eef4722b62e90c46a435ea15c1
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 9b8afba4bcf412eef4722b62e90c46a435ea15c1
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by holiman** [comment]
Sorry this has been left to become stale. @zsfelfoldi can you take a look at this if it's something we can include? If so, it probably needs to be rebased, and it might require a protocol update?

**Comment by fjl** [comment]
LESv2 has a message for querying transaction status. We couldn't come to consensus about adding this feature to the eth protocol and have decided not to add this new RPC API.

**Pull request closed without merging**
