### PR TITLE
internal/ethapi: Add method getBalanceFromJs for work with address as bytes

### PR DESCRIPTION
**Pull request by k1noman**
https://github.com/ethereum/go-ethereum/issues/3382

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 58bc91afcf9b051c73b2220b0acbc7546661ca5a
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by karalabe** [comment]
Seems to me that the single `getBalance` method shout "just work (TM)". Unsure where the type information gets lost between Go -> Js -> Go conversion. Perhaps getBalance should have been `[]byte` all along? @Arachnid ?

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 58bc91afcf9b051c73b2220b0acbc7546661ca5a
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by Arachnid** [comment]
See my update to the referenced issue.

**Comment by Arachnid** [comment]
All the methods that take `common.Address` need to be changed to take `[]byte` and call `common.BytesToAddress`. No new methods are needed. Can you update your PR?

**Comment by tet32** [comment]
Oh sure. I will do in the near future

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 58bc91afcf9b051c73b2220b0acbc7546661ca5a
  * Commits must be prefixed with the package(s) they modify

 * Commit: 9bebb9adefa6475c94b3f8e8901d26daa8fcf0fd
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by k1noman** [comment]
@Arachnid I corrected what you asked for
Please take a look

**Comment by k1noman** [comment]
@Arachnid I corrected what you asked for
Please take a look

**Pull request merged**
