### PR TITLE
rlp, trie, contracts, compression, consensus: improve readability

### PR DESCRIPTION
**Pull request by s-matthew-english**
improve readability: ameliorating comments, i.e. fixing typos, inter alia

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 453d126d1647b21f85cf7edc3d5881209cdb56ff
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by s-matthew-english** [comment]
Hello everyone- I'm new to this project, and of course I'm not yet familiar with the correct procedures to ensure that all the tests pass etc., but I'm enthusiastic about contributing- so, if someone would be interested in helping me improve the quality of this pull request I'd definitely be interested in that!

**Comment by karalabe** [comment]
Hey there, thanks for the PR!

The typo fixes are all ok, thanks for that. Regarding the RLP dead comment deletions, could you @fjl respond whether that should indeed be dropped or perhaps reinstated? Regarding the chequebook deletions, could you @zelig or @jmozah perhaps respond?

**Comment by fjl** [comment]
> Regarding the RLP dead comment deletions

If you mean the changes in compression/rle, I support removing tests that have been commented forever. Same for chequebook.

**Pull request merged**
