### PR TITLE
support 'optimize-runs' arg for solc

### PR DESCRIPTION
**Pull request by dyzz**
This would allow developers to compile smart contracts for the different purposes. Large optimize runs can reduce gas cost for frequently used functions.

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 947393fd882b9b8208d3d0cca241319e964ad3b1
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by karalabe** [comment]
I'm unsure about this. I don't think Geth should try to be a comprehensive wrapper around a Solidity compiler. The wrapped compiler is mostly used to create Go bindings for contracts, but if production performance tuning is needed, users should most definitely control and fine tune their compilation directly with solc, and not with geth.

**Comment by holiman** [comment]
I agree with @karalabe -- as it is, users are basically forced to move away from geth for anything other than simple experimentation. And that is how it should be.

**Comment by karalabe** [comment]
@fjl That's also a possibility yes, as long as we don't end up something that we have to constantly maintain, extend and rework ourselves. I don't mind having an ability to pass in custom flags. 

@dyzz I'll close this PR as it's not something that we'd accept like this, but if you'd be interested in making the generic flag approach, that would be welcome!

**Pull request closed without merging**
