### PR TITLE
event/filter: fix data race in the test

### PR DESCRIPTION
**Pull request by karalabe**
```
==================
WARNING: DATA RACE
Read by goroutine 6:
  github.com/ethereum/go-ethereum/event/filter.TestFilters()
      /work/src/github.com/ethereum/go-ethereum/event/filter/filter_test.go:48 +0x829
  testing.tRunner()
      /opt/google/go/src/testing/testing.go:456 +0xdc

Previous write by goroutine 7:
  github.com/ethereum/go-ethereum/event/filter.TestFilters.func1()
      /work/src/github.com/ethereum/go-ethereum/event/filter/filter_test.go:33 +0x6a
  github.com/ethereum/go-ethereum/event/filter.Generic.Trigger()
      /work/src/github.com/ethereum/go-ethereum/event/filter/generic_filter.go:47 +0x3d
  github.com/ethereum/go-ethereum/event/filter.(*Generic).Trigger()
      <autogenerated>:4 +0xce
  github.com/ethereum/go-ethereum/event/filter.(*Filters).loop()
      /work/src/github.com/ethereum/go-ethereum/event/filter/filter.go:81 +0x502

Goroutine 6 (running) created at:
  testing.RunTests()
      /opt/google/go/src/testing/testing.go:561 +0xaa3
  testing.(*M).Run()
      /opt/google/go/src/testing/testing.go:494 +0xe4
  main.main()
      github.com/ethereum/go-ethereum/event/filter/_test/_testmain.go:54 +0x20f

Goroutine 7 (finished) created at:
  github.com/ethereum/go-ethereum/event/filter.(*Filters).Start()
      /work/src/github.com/ethereum/go-ethereum/event/filter/filter.go:49 +0x42
  github.com/ethereum/go-ethereum/event/filter.TestFilters()
      /work/src/github.com/ethereum/go-ethereum/event/filter/filter_test.go:29 +0x23d
  testing.tRunner()
      /opt/google/go/src/testing/testing.go:456 +0xdc
==================
```

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Thu Nov 5 11:17:16 UTC 2015_

**Comment by fjl** [comment]
This test looks like it should use channels instead. :+1:

**Comment by karalabe** [comment]
@fjl PTAL. Kind of reworked the test a bit to make is cleaner.

**Comment by obscuren** [comment]
:+1:

**Pull request merged**
