### PR TITLE
p2p: throttle peers to prevent hammering

### PR DESCRIPTION
**Pull request by karalabe**
Maintain a list of recent failures to prevent constant redialing (i.e. have a cooldown of 30 seconds before reattempting a previously failed/dropped/disconnected peer).

### CODE REVIEW

**Comment by fjl** [comment]
@karalabe Is this still relevant?

**Comment by karalabe** [comment]
I've sorted out all the merge conflicts, so the patch should be mergable again. However, as far as I know the trusted/static peers won't get a free pass on the dial error (might not be a problem). Do check things out if they all still make sense please.

**Comment by karalabe** [comment]
All in all, this imho is a good thing to have, but if you're aiming to release something today, then I would suggest to hold this off. The network works fine without it, and if it's not tested properly, it might just screw it up. As I don't have the time to test it right now, I'm not vouching for it (although it did work properly when I wrote it originally).

**Comment by obscuren** [comment]
Can we close this PR?

**Comment by fjl** [comment]
yes. #1014 does that as well.

**Pull request closed without merging**
