### PR TITLE
cmd/disasm: fix array-out-of-bounds error

### PR DESCRIPTION
**Pull request by wuestholz**

### CODE REVIEW

**Comment by wuestholz** [comment]
@fjl Thank you very much for having a look and for pointing out these other procedures!

The main reason for using this "callback iterator" was to avoid storing the disassembled instructions in a separate data structure (e.g., list) that would need to be processed and iterated again by a client.

I will update the PR to only fix the out-of-bounds error as soon as possible.

However, I think it would be great to clean up all those procedures like you suggest. I would be happy to help with that. Should I just send a separate PR and mention you there?

About the license: from looking at the files under "core", it seems like they are also under GPL. What other license where you thinking of?

**Comment by fjl** [comment]
Files outside cmd/ ("the go-ethereum library") are LGPLv3.

**Comment by wuestholz** [comment]
@fjl I see. Sorry for not noticing and thanks for the clarification!

**Comment by wuestholz** [comment]
@fjl I have updated the PR to only fix the array-out-of-bounds error.

**Pull request merged**
