### PR TITLE
fix SetHead func to call repair func

### LINKED ISSUE #20224: Ask a question about the code in func SetHead
```
func (bc *BlockChain) SetHead(head uint64) error {
	log.Warn("Rewinding blockchain", "target", head)

	bc.chainmu.Lock()
	defer bc.chainmu.Unlock()

	updateFn := func(db ethdb.KeyValueWriter, header *types.Header) {
		// Rewind the block chain, ensuring we don't end up with a stateless head block
		if currentBlock := bc.CurrentBlock(); currentBlock != nil && header.Number.Uint64() < currentBlock.NumberU64() {
			newHeadBlock := bc.GetBlock(header.Hash(), header.Number.Uint64())
			if newHeadBlock == nil {
				newHeadBlock = bc.genesisBlock
			} else {
				if _, err := state.New(newHeadBlock.Root(), bc.stateCache); err != nil {
					// Rewound state missing, rolled back to before pivot, reset to genesis
					newHeadBlock = bc.genesisBlock
				}
			}
			rawdb.WriteHeadBlockHash(db, newHeadBlock.Hash())
			bc.currentBlock.Store(newHeadBlock)
			headBlockGauge.Update(int64(newHeadBlock.NumberU64()))
		}
...
```
I want to ask, why here not try to repair the chain (call the func repair)?. Just reset to genesisBlock?

### PR DESCRIPTION
**Pull request by james-ray**
fix #20224

### CODE REVIEW

**Comment by james-ray** [comment]
It is strange with the test, isn't it?

**Comment by rjl493456442** [comment]
@james-ray It's unrelative unit test failure, no worry.

**Comment by james-ray** [comment]
@rjl493456442  OK!   Is the code OK?

**Comment by karalabe** [comment]
Superseeded by https://github.com/ethereum/go-ethereum/pull/21409.

**Pull request closed without merging**
