### PR TITLE
Making precompile lookup function injectable into the block context

### PR DESCRIPTION
**Pull request by ramtinms**
Some L2 blockchains (e.g., Base) need to add their own precompiled contracts in the VM environment to facilitate L1<>L2 chain operations. 

In this PR, I added a new field to the block config (similar to CanTransfer) that could be injected when needed. To maintain the backward compatibility and minimize the code changes, the VM uses the default function if this new field is not set on the block context.

### CODE REVIEW

**Comment by holiman** [comment]
Can't you just override them in the method `func (evm *EVM) precompile(addr common.Address) (PrecompiledContract, bool) ` ?

**Comment by ramtinms** [comment]
@holiman you mean overriding global variables like PrecompiledAddressesByzantium? or adding a condition inside `precompile` method to check if block context has set a `HasPrecompileFunc` and if not falls back to the original behaviour?

**Comment by MariusVanDerWijden** [comment]
I think I would do something like this in order to add the base specific precompiles
```diff
diff --git a/core/vm/evm.go b/core/vm/evm.go
index 088b18aaa..48a5fbcac 100644
--- a/core/vm/evm.go
+++ b/core/vm/evm.go
@@ -51,6 +51,9 @@ func (evm *EVM) precompile(addr common.Address) (PrecompiledContract, bool) {
        default:
                precompiles = PrecompiledContractsHomestead
        }
+       if evm.chainConfig.IsBase() {
+               precompiles[common.Address{0xff}] = &bigModExp{}
+       }
        p, ok := precompiles[addr]
        return p, ok
 }
 ```

**Comment by tynes** [comment]
> Some L2 blockchains (e.g., Base) need to add their own precompiled contracts in the VM environment to facilitate L1<>L2 chain operations.

Hi i am a contributor to the op-stack and this isn't true, evm bytecode is used to facilitate L1<>L2 chain operations. There are no plans to add extra precompiles outside of the RIP process

**Comment by ramtinms** [comment]
Thanks @tynes for clarification, yeah seems I had wrong understanding of how addresses like`https://basescan.org/address/0x4200000000000000000000000000000000000016` works on the L2. 

Yet I still think its valuable to have the option to inject precompiles as an option.

**Pull request closed without merging**
