### PR TITLE
accounts/abi, mobile: use EIP155Signer for new txs (#16484)

### LINKED ISSUE #16484: Abi.bind should use EIP155Signer (not HomesteadSigner) for new transactions.
Currently, Abi.bind is [hardcoded to use HomesteadSigner](https://github.com/ethereum/go-ethereum/blob/2e247705cd27e919e806f29ff2adcd57c163b1ac/accounts/abi/bind/base.go#L237). Should not we use the newer EIP155Signer for new txs?

### PR DESCRIPTION
**Pull request by dinstein**
Fix #16484.

### CODE REVIEW

**Comment by karalabe** [comment]
I'm a bit uncertain about this change. If we have the `SignerFn` already supplied from the outside, why not add the EIP155 changes to that instead? This PR feels as if we're leaking out logic into the wrong place.

**Comment by dinstein** [comment]
I thought the `ChainId` may be an attribute of transaction (just like `Nonce`) after EIP155 hard fork, so I added it into `TransactOpts`. While if we treat it as an attribute of `SignFn`, indeed it should not be included in `TransactOpts`.

`SignFn` requires a `types.Signer` input parameter, but without `ChainId` we could not create an EIP155 Signer in `transact` function either pass it to `SignFn`, so shall we implement a `SignFn` that ignore the first parameter `types.Signer` and create EIP155 Signer inside instead?

**Comment by dinstein** [comment]
As shown in mobile/bind.go, the `SetSigner` create an `opts.Signer` which [ignores the input parameter](https://github.com/dinstein/go-ethereum/blob/master/mobile/bind.go#L93) `signer` and uses `mobile.Signer` to sign a txn. I think this may be a little confusing, if we want `SignFn` to handle all the signing actions, maybe we should remove its first parameter `types.Signer` and only pass address and unsigned txn to it.

**Comment by Dominator008** [comment]
What's the status of this?

**Comment by gballet** [comment]
@dinstein you are right, having the signer as the first parameter leads to a confusing situation. Removing the first parameter is a good idea. It will require a change in `NewKeyedTransactor` but it's easilty done with that `SetSigner` function.

**Comment by dinstein** [comment]
@gballet glad to see the progress :)

**Pull request closed without merging**
