### PR TITLE
Revert "cmd/utils: fix compilation issue on openbsd (#22511)"

### PR DESCRIPTION
**Pull request by gballet**
#22511 presented an incorrect fix and it was merged in haste. I am working on the correct fix in the background.

### CODE REVIEW

**Comment by karalabe** [comment]
We were discussing that we should drop our custom disk space tracker altogether and just use `gopsutils/disk`. Doesn't make sense to reimplement something, especially if it's a pain to port.

**Comment by gballet** [comment]
agreed, the fix to gopsutil is in progress

**Comment by gballet** [comment]
btw the "fix" that was hastily merged didn't fix anything on master:

```
# github.com/shirou/gopsutil/mem
../../../../pkg/mod/github.com/shirou/gopsutil@v2.20.5+incompatible/mem/mem_openbsd.go:21:17: undefined: CTLVm
../../../../pkg/mod/github.com/shirou/gopsutil@v2.20.5+incompatible/mem/mem_openbsd.go:21:24: undefined: VmUvmexp
../../../../pkg/mod/github.com/shirou/gopsutil@v2.20.5+incompatible/mem/mem_openbsd.go:26:14: undefined: sizeOfUvmexp
../../../../pkg/mod/github.com/shirou/gopsutil@v2.20.5+incompatible/mem/mem_openbsd.go:29:13: undefined: Uvmexp
../../../../pkg/mod/github.com/shirou/gopsutil@v2.20.5+incompatible/mem/mem_openbsd.go:43:17: undefined: CTLVm
../../../../pkg/mod/github.com/shirou/gopsutil@v2.20.5+incompatible/mem/mem_openbsd.go:43:24: undefined: VmUvmexp
../../../../pkg/mod/github.com/shirou/gopsutil@v2.20.5+incompatible/mem/mem_openbsd.go:48:14: undefined: sizeOfUvmexp
../../../../pkg/mod/github.com/shirou/gopsutil@v2.20.5+incompatible/mem/mem_openbsd.go:51:13: undefined: Uvmexp
../../../../pkg/mod/github.com/shirou/gopsutil@v2.20.5+incompatible/mem/mem_openbsd.go:72:16: undefined: CTLVfs
../../../../pkg/mod/github.com/shirou/gopsutil@v2.20.5+incompatible/mem/mem_openbsd.go:72:24: undefined: VfsGeneric
../../../../pkg/mod/github.com/shirou/gopsutil@v2.20.5+incompatible/mem/mem_openbsd.go:72:24: too many errors
```

**Comment by holiman** [comment]
> btw the "fix" that was hastily merged didn't fix anything on maste

Well, arguably it fixed an openbsd compilation error, but not all of them.

**Pull request closed without merging**
