### PR TITLE
ethdb, cmd/geth, eth: guerilla state pruning

### PR DESCRIPTION
**Pull request by obscuren**
This is by no means production ready code. This PR is up for debate and demonstrate and introduces an intermediate state pruning process.

This PR takes the following approach on pruning:
1. Take the state of the last 256 blocks
2. Copy them to another database
3. Remove all state data from database
4. Copy state data from step (2)

~~After running this you'll still, with a legacy, full state database, end up 12GB of data. I'm not sure where the exact bulk of the data is coming from and is most definitely worth investigating.~~

This PR does not contain any automated pruning process. Pruning is fully optionally and must be initiated manually using the `prune` sub command (i.e. `geth prune`).

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Mon Apr 25 09:06:56 UTC 2016_

**Comment by obscuren** [comment]
@fjl @karalabe PTAL

**Comment by obscuren** [comment]
The issue the 12GB remaining space was due to db compaction (i.e. it wasn't). A state database prunes to roughly 2.4GB total.

Output of a full state (`0...current`) with an approximate of 14.4GB being pruned:

```
I0428 15:05:08.730588 cmd/geth/chaincmd.go:120] Copying relevant state data
I0428 15:08:54.040286 cmd/geth/chaincmd.go:151] Pruning old state data
I0428 15:13:46.598544 cmd/geth/chaincmd.go:185] Compacting database
I0428 15:18:06.364725 cmd/geth/chaincmd.go:191] Moving new state data to database
I0428 15:18:17.769322 cmd/geth/chaincmd.go:205] Pruning process completed in: 13m9.041272193s
````

```
$ du -sh chaindata
2.5G	chaindata
```

The process is a relatively slow, this because of the 14GB it needs to crunch initially. All subsequent calls take roughly 3 minutes (depending on the size of the state). We could reduce this further by splitting up the database again and do the following:

1. Copy relevant state data to new database
2. Delete out state database
3. Move 1.

Most of the overhead comes from scanning the database of data we wish to delete. By simply moving the data over and deleting the old database this process can be reduces by another ~2 minutes.

All of the above times are done on an SSD. I've yet to perform a test on a full state stored on an HDD.

**Comment by obscuren** [comment]
@karalabe would you mind trying this PR on your old machine?

**Comment by karalabe** [comment]
Sure thang.

**Comment by fjl** [comment]
LGTM. please rebase

**Comment by karalabe** [comment]
It will break hard with the state trie changes... if I ever get to implement it :(

**Pull request closed without merging**
