### PR TITLE
graphql: add raw fields to block and tx

### PR DESCRIPTION
**Pull request by s1na**
Adds:

- Transaction.raw
- Block.rawHeader
- Block.raw

### CODE REVIEW

**Review by holiman — APPROVED** [review]
LGTM

**Comment by holiman** [comment]
Not sure how we treat graphql. Do we just merge away or do we need to update some standard somewhere?

**Comment by karalabe** [comment]
There's this document https://eips.ethereum.org/EIPS/eip-1767, unsure if an update is meant to change this or open a new EIP? Also unsure if EIPs are the correct thing for API specs.

**Comment by s1na** [comment]
There's now a living spec here: https://github.com/ethereum/execution-apis/blob/main/graphql.json
I'll open a PR to update that first then

**Comment by ligi** [comment]
context: https://github.com/ethereum/execution-apis/pull/220

**Pull request merged**
