### PR TITLE
ethereum: remove TODO comment about subscription

### PR DESCRIPTION
**Pull request by sbs2001**
Fixes TODO mentioned by @fjl   https://github.com/ethereum/go-ethereum/blob/2a2013014c46844728421a1acc5ad40ca823414b/interfaces.go#L32

### CODE REVIEW

**Comment by fjl** [comment]
It's too late for this TODO, this type and the methods returning it have existed for a long time and we would break code using it. So we need to remove the TODO instead.

**Comment by sbs2001** [comment]
@fjl  fixed. 

Though I was able to build geth with the previous commit.

**Comment by fjl** [comment]
Yeah, it's not about Geth and more about other projects which may depend on these interfaces.

**Comment by sbs2001** [comment]
@fjl thanks. I dropped that commit to just delete the TODO comment

**Pull request merged**
