### PR TITLE
eth: fix corner case in sync head determination

### PR DESCRIPTION
**Pull request by zouguangxian**
synchronisation failure when local header is ahead of local full block.

### CODE REVIEW

**Comment by holiman** [comment]
Could you give some more context here? In what scenarios would this happen, and why is the fix improving the situation?

**Comment by zouguangxian** [comment]
> Could you give some more context here? In what scenarios would this happen, and why is the fix improving the situation?

I integrate a BFT-based consensus into go-ethereum, and launch a 3 nodes network via docker-compose.yml. After shutdown and restart the cluster,  one node(A) still have the latest header and block, but the other two node(B,C) just have latest header and it's parent block. In such a situation, B and C can't sync to the latest block.

**Comment by holiman** [comment]
In your changes, did you change the rollback mechanism at sync failure? I don't understand how they can have the latest `head` but not have filled the header with a full block?

**Comment by holiman** [comment]
The thing about this change, is that it may possibly fix some cornercase you're experiencing with your modified version of the code, but we need to ensure that there's exactly no way that this change screws up with regular go-ethereum mainnet clients. And that's very hard to do, unless we spend a lot of time analyzing what the possible consequences are, and ensure that we have sufficient test coverage of every potential case. 

So it's very unlikely (imo) that we will accept this PR, unless it actually improves something or solves a problem relevant for ethereum mainnet clients.

**Comment by zouguangxian** [comment]
> In your changes, did you change the rollback mechanism at sync failure? I don't understand how they can have the latest `head` but not have filled the header with a full block?

No, I don't change rollback mechanism at sync failure.

**Review by holiman — APPROVED** [review]
lgtm

**Pull request merged**
