### PR TITLE
build: set the number of go testing process

### PR DESCRIPTION
**Pull request by jsvisa**
**What's this PR works for:**

run testing in concurrent mode.

### CODE REVIEW

**Comment by fjl** [comment]
The default value of `-p` is the number of CPUs available. Why does it need to be changed?

**Comment by jsvisa** [comment]
@fjl the default value is 1 from here https://github.com/ethereum/go-ethereum/blob/master/build/ci.go#L308, and where does process number was set?

**Comment by fjl** [comment]
Oh sorry, I missed that. I remember now: We added `-p 1` to reduce test failures caused by overload on TravisCI. The TravisCI VMs are slow and running many packages in parallel doesn't make it faster.

It should stay this way. If you want faster tests on your machine you can just use `go test`. `build/ci.go` is for CI.

**Comment by jsvisa** [comment]
@fjl Thanks for your reply, IMO, we run testing  with `make test`,  so I think make testing prallel as configable maybe a good choice, and the default 1 is not changed.

**Comment by fjl** [comment]
Closing because there is a good workaround (use `go test`) and we will probably
discontinue support for the Makefile when we switch to Go modules.

**Pull request closed without merging**
