### PR TITLE
mobile: Allows mobile clients to set verbosity of clients's logs

### PR DESCRIPTION
**Pull request by Nigui**

### CODE REVIEW

**Comment by Nigui** [comment]
Afterall, maybe Verbosity has to be a Geth method and not a Node method ? 
At usage : 
```java
Geth.verbosity(6);
```
**vs**
```java
Node node = Geth.newNode(...);
node.verbosity(6);
```
What do you think ?

**Comment by karalabe** [comment]
Indeed, it should be outside since it changes log levels for everything. Please place it inside a new file `mobile/logger.go`. (I know it's weird that there's only a single 1 liner in there, but we can add `vmodule` specs later so that will need its file anyway).

Also please call it `SetVerbosity` (opposed to plain `Verbosity`). Otherwise looks good!

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: f0d044d4e8b6dcff537e9603fa7630b478cf8f29
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: b7d7c99c1501eec33ea281b587a74267b2f4b80e
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: b7d7c99c1501eec33ea281b587a74267b2f4b80e
  * Commits must be prefixed with the package(s) they modify

 * Commit: b9e6390670086c1b5f4c8a07def506d9e3111d65
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
