### PR TITLE
ethclient: Changed TransactionByHash to only pass one argument to eth_getTransactionByHash

### LINKED ISSUE #3203: ethclient.TransactionByHash: "too many params, want 1 got 2"
#### System information

Geth version: develop branch
OS & Version: Arch Linux
Commit hash : 77560730099546b0a861754cf38abcb1140ecdc5

The method `ethclient.Client.TransactionByHash()` always responds with an error: "too many params, want 1 got 2".

The [RPC method](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactionbyhash) takes one, while `TransactionByHash` also [hands a boolean value](https://github.com/ethereum/go-ethereum/blob/5bb517355e292b50d81b4abf28cb741712c13a7e/ethclient/ethclient.go#L148).

### PR DESCRIPTION
**Pull request by stevenroose**
Fixes #3203

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 2f0a61982bfa77f9e0728de543791742bd0a1a60
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by karalabe** [comment]
@fjl PTAL

**Comment by stevenroose** [comment]
Also, any heads up on when the `ethclient` package might end up in master?

**Comment by karalabe** [comment]
@stevenroose It will be part of Geth 1.5. We're pushing very hard to get it out.

**Pull request merged**
