### PR TITLE
Fix build on OpenBSD

### PR DESCRIPTION
**Pull request by mrdomino**
I have no idea if I've used godep properly, but the effects appear to be as desired. The relevant changes are properly referencing OpenBSD's byte-swapping operations in ethash, and adding openbsd to the list of supported platforms in go-isatty.

### CODE REVIEW

**Comment by fjl** [comment]
Yes, you have used godep correctly. Please squash the commits. Thank you.

**Comment by mrdomino** [comment]
Done.

**Comment by fjl** [comment]
:+1:

**Comment by obscuren** [comment]
:+1:

**Pull request merged**
