### PR TITLE
ckeck account already exists or not When import keystore

### PR DESCRIPTION
**Pull request by JKinGH**

### CODE REVIEW

**Comment by holiman** [comment]
Hm, I think this might be too naive a solution. While the address might exist, it may be the case that the user has the same pkey stored in two separate keyfiles -- with different passwords. So let's say you have it on your computer, but forgot the password. And now you want to re-import it from a backup. In that case, it's not sufficient to just say "no you already have it". And it's not a good solution either to blindly overwrite it. 

So, for starters: what happens right _now_, before this PR?

**Comment by JKinGH** [comment]
> Hm, I think this might be too naive a solution. While the address might exist, it may be the case that the user has the same pkey stored in two separate keyfiles -- with different passwords. So let's say you have it on your computer, but forgot the password. And now you want to re-import it from a backup. In that case, it's not sufficient to just say "no you already have it". And it's not a good solution either to blindly overwrite it.
> 
> So, for starters: what happens right _now_, before this PR?

Thank you very much and you said it very well. However, when there are multiple keyfiles with the same address in a keydir, I will fail to Export t or Update the password,  prompted "multiple keys match address ...". So I think the same file based on the same address should not exist in the same directory. So let's say you have it on your computer, but forgot the password. And now you must delete/remove the old keyfile when you want to re-import it from a backup.

**Comment by holiman** [comment]
So, right now, we do allow importing it, but then the user needs to actively figure out and resolve the underlying problem, right?
If so, that sounds more like a correct approach, because this is not really a situation which geth/clef can handle on it's own, in some automated fashion.

**Comment by JKinGH** [comment]
> So, right now, we do allow importing it, but then the user needs to actively figure out and resolve the underlying problem, right?
> If so, that sounds more like a correct approach, because this is not really a situation which geth/clef can handle on it's own, in some automated fashion.

Okey, Maybe you are right.  I'll deal with the duplication of keystore myself.
Thank you and  have a good life.

**Pull request closed without merging**
