### PR TITLE
SWARM: prevent stack depth attack in checkbook.sol

### PR DESCRIPTION
**Pull request by colm**
Prevents [stack depth attack](https://blog.ethereum.org/2016/06/10/smart-contract-security/) in checkbook.sol

A malicious actor could cause a send to fail and the contract continues assumes the account wrote a bad check.

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Sat Jun 11 19:59:30 UTC 2016_

**Comment by obscuren** [comment]
@zelig  PTAL

**Comment by Arachnid** [comment]
👍 LGTM. Would you mind rebasing so we can merge?

**Comment by colm** [comment]
Sure I will do this in a little while.

**Comment by colm** [comment]
@Arachnid I coudl not rebase. It was super complicated and i didn't want to risk breaking things. So I made a new PR https://github.com/ethereum/go-ethereum/pull/2922

**Pull request closed without merging**
