### PR TITLE
params: add new bootnodes

### PR DESCRIPTION
**Pull request by holiman**
This PR adds new bootnodes. 
cc @skylenet please approve if you consider these finalized (will not be changing enode ids/ips at this time). 
cc @fjl could you verify conectivity with them using your cool toolz? 

One open question is if we should remove the old bootnodes in this PR, or let them live side by side in the client for a while (the actual nodes will be kept alive for a while longer either way)

### CODE REVIEW

**Comment by fjl** [comment]
I checked discovery connectivity for these nodes and `bootnode-aws-ap-southeast-1-001`, `bootnode-aws-eu-central-1-001`, `bootnode-azure-australiaeast-0013`, `bootnode-azure-brazilsouth-001`, `bootnode-azure-koreasouth-0013` are not responding to PING from my location.

You can check yourself using the devp2p command:

```text 
go build ./cmd/devp2p
/devp2p discv4 ping <node>
```

**Comment by fjl** [comment]
Old bootnodes should stay in the list. I will add some Parity nodes to the list as well.

**Comment by holiman** [comment]
Works for me: 
```
[user@work go-ethereum]$ go build ./cmd/devp2p/
[user@work go-ethereum]$ ./devp2p discv4 ping enode://d860a01f9722d78051619d1e2351aba3f43f943f6f00718d1b9baa4101932a1f5011f16bb2b1bb35db20d6fe28fa0bf09636d26a87d31de9ec6203eeedb1f666@18.138.108.67:30303
INFO [06-07|16:06:52.058] New local node record                    seq=1 id=ae828247e1b1ce63 ip=127.0.0.1 udp=50476 tcp=0
node responded to ping (RTT 437.451942ms).
```

**Comment by holiman** [comment]
All of them works for me
```
INFO [06-07|16:10:04.148] New local node record                    seq=1 id=e3916abdd78ab7ca ip=127.0.0.1 udp=51531 tcp=0
node responded to ping (RTT 299.788963ms).
INFO [06-07|16:10:04.477] New local node record                    seq=1 id=deced3ce5a872e59 ip=127.0.0.1 udp=55242 tcp=0
node responded to ping (RTT 352.697155ms).
INFO [06-07|16:10:04.864] New local node record                    seq=1 id=44aa7a8b77001861 ip=127.0.0.1 udp=60005 tcp=0
node responded to ping (RTT 51.606428ms).
INFO [06-07|16:10:04.950] New local node record                    seq=1 id=eff5e859fcd9fee3 ip=127.0.0.1 udp=59089 tcp=0
node responded to ping (RTT 28.563387ms).
INFO [06-07|16:10:05.015] New local node record                    seq=1 id=24ab260844d522e2 ip=127.0.0.1 udp=39090 tcp=0
node responded to ping (RTT 458.492442ms).
INFO [06-07|16:10:05.504] New local node record                    seq=1 id=472528233b77c7c2 ip=127.0.0.1 udp=60028 tcp=0
node responded to ping (RTT 276.265347ms).
INFO [06-07|16:10:05.816] New local node record                    seq=1 id=b7f51c28ef1ce889 ip=127.0.0.1 udp=40491 tcp=0
node responded to ping (RTT 257.619999ms).
INFO [06-07|16:10:06.103] New local node record                    seq=1 id=b6e71025c638ac1a ip=127.0.0.1 udp=52126 tcp=0
node responded to ping (RTT 396.367515ms).
```

**Comment by fjl** [comment]
Yeah, it's probably my bad connection.

**Comment by holiman** [comment]
We'll follow up with Parity bootnodes later, once https://github.com/paritytech/parity-ethereum/pull/10705 has been rolled out and they're responsive again

**Comment by holiman** [comment]
This is now merged, but somehow the PR didn't get closed.

**Pull request closed without merging**
