### PR TITLE
core: handle checkpoint sync corner case explicitly

### PR DESCRIPTION
**Pull request by zsfelfoldi**

### CODE REVIEW

**Comment by holiman** [comment]
I'm on mobile, so limited readability... Buy what's the point of the loop? Is it just to induce panic if the chain is broken?

**Comment by zsfelfoldi** [comment]
@holiman yes

**Comment by holiman** [comment]
If we introduce a `panic` where previously there was no panic, I think you should motivate the reason behind that. It's difficult to review and determine the possible causes that could lead to that happening.

**Comment by fjl** [comment]
The reason for this PR was adding a panic in case the header chain is broken. We have re-reviewed this and concluded that the check is unnecessary because a broken header chain will cause enough other problems already.

**Pull request closed without merging**
