### PR TITLE
miner: make independent header for each task

### PR DESCRIPTION
**Pull request by ucwong**

### CODE REVIEW

**Comment by karalabe** [comment]
Could you please detail why you made this change?

**Comment by ucwong** [comment]
@karalabe I find out it will make some wrong tasks when mine blocks in a short time, concurrently. It will be a wast of hashes

**Comment by ucwong** [comment]
@karalabe especially when including uncle blocks

**Comment by rjl493456442** [comment]
@ucwong `commit` function is single-threaded. So in theory no concurrency issue should suffer here.

**Comment by ucwong** [comment]
@rjl493456442 Thanks a lot for your reply. Yes, you are right, commit func is in single thread. But now using header as a pointer in a task, when I want to include an uncle by renewing a task, maybe it will change the current header pointer in pre-task. Is there some possible to mine a wrong task in some time?

**Comment by rjl493456442** [comment]
@ucwong Every time when we generate a new mining task, we will deep copy the header. Check out the code here https://github.com/ethereum/go-ethereum/blob/master/core/types/block.go#L184.

**Comment by ucwong** [comment]
OK, I think both commitNewWork and  case ev := <-w.chainSideCh: will call commit concurrently, w.current.header seems not be thread safe. There may be some problems when doing the deep copy

**Comment by rjl493456442** [comment]
@ucwong They are in the same `select` so only one will be called.

**Comment by ucwong** [comment]
image
@rjl493456442 I got u,  now 2 new tasks in a very exact same time , when receive a new segment. Whether it because of new block channel and regular routine timer ?

**Comment by rjl493456442** [comment]
@ucwong It more likes an issue. The strategy of miner is: Generate an empty task first and in the meantime apply all pending transactions into a full task. Once it finishes, switch the task with the full one.
But if there are no pending transactions at all, we SHOULDN'T push the second empty task.

**Comment by ucwong** [comment]
@rjl493456442 Yes,I have checked the code , it should run like you said above without pending txs, so  I think whether there are some problems in special situation about single thread

**Comment by CoreyLin** [comment]
> @ucwong They are in the same select so only one will be called.

Sorry I don't quite understand here. Indeed they are in the same `select`, but the `select `statement is inside a `for` loop. So is there any possibility of concurrency issue here?

**Comment by adamschmideg** [comment]
Opened an issue for this: #20267

**Pull request closed without merging**
