### PR TITLE
cmd, node, rpc: TLS support

### PR DESCRIPTION
**Pull request by farazdagi**
## What?

- This PR has basic support for transport layer security, and allows servicing RPC requests on HTTPS.
- Both server and console have been updated i.e. you can use `geth attach` to connect to TLS-enabled node
- Support for self-signed certificates (again both server and client side) has been added
- Extra utils to auto-generate self-signed certificate/key

## Why?
- the obvious solution whenever one needs to fix mixed content issues (when you load your Dapp on https and connect to node running on http directly), was to use intermediary relay server, as outlined in comments to https://github.com/ethereum/go-ethereum/issues/2121
- moreover, it has been stated that the RPC server functionality being targeted to developers probably doesn't need TLS support at all
- one possible use case [we](https://github.com/status-im) have discovered is when Dapps running on Status were communicating with underlying Geth node directly (**on mobile device**, we try to minimize number of intermediaries, so running the relay server is probably not the best idea)

## Details

**Server:**

```bash
# start node, enable TLS, use provided cert/key
geth --testnet --light --rpc --tls --tlscert cert.pem --tlskey key.pem console

# start node, enable TLS, auto-generate cert/key
geth --testnet --light --rpc --tls console
```

**Client:**

```bash
# connect to TLS-enabled node, use given certificate, treat certificate as its own CA
geth --tlscert tlscert.pem --tlskey tlskey.pem --tlscertca attach https://localhost:8545

# connect to TLS-enabled node, make sure that client accepts any key provided by server
# (including self-signed certificate)
geth --tlsnoverify attach https://localhost:8545

# connect to TLS-enabled node, which uses certificate signed by known CA
geth --tlsnoverify attach https://localhost:8545
```

## Roadmap
- as no prior discussion has been held, the purpose of this PR, at this stage, is more to gauge interest than anything else
- if there will be interest to merge the thingy, then tests will be provided, and overall polishing attempted (guided by recommendations/comments from the core team)
- if there will be no intent to merge, then this PR should be closed. Hopefully, someone looking for TLS-support will be able to locate the PR and, effectively, have a good starting point (thus, community can still benefit)

### CODE REVIEW

**Comment by obscuren** [comment]
Sorry for the late response and thank you for your PR. We're discussing this internally

**Comment by obscuren** [comment]
We've discussed internally and here's what we decided:

* We'd like to get TLS support for RPC in 1.6 (next version, ~2-4 weeks)
* We like to support TLS through configuration files (not yet supported)
* We do not want TLS to be configurable through CLI flags

Are you interested in doing the extra work once configuration files have been implemented?

**Comment by farazdagi** [comment]
- Yep, I am definitely interested in doing that extra work
- What tickets/PRs should I watch for config files implementation, I've found:
  - issue https://github.com/ethereum/go-ethereum/issues/3332
  - and corresponding (blocked) PR https://github.com/ethereum/go-ethereum/pull/3424

**Comment by obscuren** [comment]
@farazdagi: @fjl will reimplement the configuration PR. We've decided to take a different approach. #3424 maps CLI flags directly through configuration; instead we want to add a hierarchal configuration  options by mapping them directly to our internal config structs.

@fjl: please this PR.

**Comment by fjl** [comment]
We're postponing this this 1.6.1. The RPC server configuration mechanism will be reworked and I'll add support for TLS then.

**Comment by nwilson1412** [comment]
Hi any update on this, as 1.6.1 is out?

**Comment by karalabe** [comment]
I don't think anyone worked on TLS since then.

**Comment by jozanza** [comment]
Yeah I'd also love an update on this one if possible

**Comment by fjl** [comment]
We got distracted by other stuff and didn't implement new configuration for RPC endpoints. This is up for grabs if anyone wants to do it.

**Comment by pranavburnwal** [comment]
+1
Need this...

**Comment by tamama** [comment]
+1
https://github.com/ethereum/go-ethereum/issues/16554

**Comment by sanguohot** [comment]
+1
Need it···

**Comment by dylanpoe** [comment]
+1 Need it ...
This is my problem encountered during deploy nginx 

```

    upstream websocket {
	#ip_hash;
	server 127.0.0.1:9647;  
       }
    server {
#       listen       80 default_server;
#       listen       9648;
#       server_name  _;
        listen       443 ssl http2 default_server;
        listen       [::]:443 ssl http2 default_server;
        server_name  ssl.eash.io;
	ssl          on;
        root         /usr/share/nginx/html;
         ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA;
        ssl_prefer_server_ciphers on;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;	
	ssl_certificate      /etc/letsencrypt/live/ssl.eash.io/cert.pem; 
        ssl_certificate_key /etc/letsencrypt/live/ssl.eash.io/privkey.pem;
        include /etc/nginx/default.d/*.conf;
        location / {
 		proxy_set_header        Host $host;
    		proxy_http_version      1.1;
    		proxy_set_header        Upgrade $http_upgrade;
   		proxy_set_header        Connection "upgrade";
    		proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    		proxy_set_header        X-Real-IP $remote_addr;
    		proxy_set_header        X-Forwarded-Proto $scheme;
    		proxy_pass              http://127.0.0.1:9647;
        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }

```

my nginx conf
and when I try to connect the node in another VPS

image
How should I do this ,configure nginx for wss ?

**Pull request closed without merging**
