### PR TITLE
travis, Dockerfile, appveyor, build: bump to Go 1.11

### PR DESCRIPTION
**Pull request by karalabe**

### CODE REVIEW

**Comment by karalabe** [comment]
@SamuelMarks Fairly sure https://travis-ci.org/ethereum/go-ethereum/jobs/430439073#L509 :)

**Comment by karalabe** [comment]
Famous last words

**Comment by SamuelMarks** [comment]
@karalabe Oh, it was literally the lack of linted code that stopped it compiling? - Great, happy this is merging then 👍

**Comment by karalabe** [comment]
It wasn't stopping it from compiling, rather we have a linter CI step to prevent pushing badly formatted code into the repo.

**Pull request merged**
