### PR TITLE
eth/filters: annotate logs in a sub with block end markers

### PR DESCRIPTION
**Pull request by karalabe**
EDIT: Ugh, so this doesn't actually work, because the `*types.Log` embedding redefines JSON marshalling, which overrides it even for the wrapper. Ugh

Fixes https://github.com/ethereum/go-ethereum/issues/24787

When subscribing to logs, the user will get a never ending stream of them. It can be annoying to figure out whether the last log of a block arrived, or if there's some more in the pipeline. This PR adds a block end marker into logs.

### CODE REVIEW

**Comment by holiman** [comment]
From @fjl 

> We can add field Last in types.Log 
> With omitempty)
> Clients will also need it, and the type used in subscription is types.Log

**Comment by karalabe** [comment]
So, to make this work we should:

- Add the `Last` to `types.Log`
- Set it during loading from the db
- Set it whenever we refilter

**Comment by fjl** [comment]
Closing because https://github.com/ethereum/go-ethereum/pull/26109 is more up-to-date.

**Comment by holiman** [comment]
> Closing because https://github.com/ethereum/go-ethereum/pull/26109 is more up-to-date.

**Pull request closed without merging**
