### PR TITLE
core/state: maintain destruction flag by default

### PR DESCRIPTION
**Pull request by rjl493456442**
Originally the destructed flag in stateDB is only maintained when snapshot
is enabled and alive. But it turns out that this flag is also required in PBSS.

For example: 

The object was destructed then re-created. StateDB needs the signal
to cleanup the original storage which is unknown without this flag

This PR maintains this flag by default. The logic should not be changed.

### CODE REVIEW

**Review by holiman — APPROVED** [review]
LGTM

**Comment by rjl493456442** [comment]
This PR might be unnecessary. Please give me a bit more time to figure out if it's really required.

**Comment by rjl493456442** [comment]
Let's include it. It's still a required functionality

**Comment by holiman** [comment]
I think this will be beneficial for https://github.com/ethereum/go-ethereum/pull/24916 too. Because with this PR, one can just "pretend" that an account was deleted and recreated, by marking it in the `stateObjectsDestruct`, and thus implement full storage clearing that works for snap and trie-backed both.

**Pull request merged**
