### PR TITLE
vendor: remove leftover trace

### PR DESCRIPTION
**Pull request by gballet**
some trave was left out in the vendored go-libpcsclite. Remove it.

### CODE REVIEW

**Comment by karalabe** [comment]
You didn't update the vendor json.

**Comment by gballet** [comment]
that's because it's not in the original repo

**Comment by karalabe** [comment]
If I do a `govendor fetch github.com/gballet/go-libpcsclite` a whole lot of changes are pulled in. Any reason behind not using your latest card code?

**Comment by karalabe** [comment]
Btw, it **is** in the original repo https://github.com/gballet/go-libpcsclite/blob/95b81846253cd854b8bb8f2fd9cc6056d0681ac4/winscard.go#L238

**Comment by karalabe** [comment]
Govendor commit revision doesn't match the vendored in code by far. Please fix the vendor and try not to modify vendored code at all.

**Comment by gballet** [comment]
> Btw, it **is** in the original repo https://github.com/gballet/go-libpcsclite/blob/95b81846253cd854b8bb8f2fd9cc6056d0681ac4/winscard.go#L238

ok, it got removed in a later commit. The reason why the latest version hasn't been used is that the current version combination in master has been thoroughly tested, whereas the other one hasn't.

**Comment by karalabe** [comment]
Doesn't matter, vendor hash needs to be in sync with the vendored code.

**Pull request merged**
