### PR TITLE
ethapi: Optimise gas estimation for common case

### PR DESCRIPTION
**Pull request by piersy**
Rather than enter into a binary search on every call to estimate gas,
this change first sees if the sumbitted transaction can be executed with
the gas used value, and if so gas estimation can stop there. This reduces
the number of tx executions during estimation from about 24 to 2 for
transactions that are not calling SELFDESTRUCT or zeroing storage. My
hunch is that most transactions are not calling SELFDETRUCT or zeroing
storage so this would result in a performance imporovement of about 12x
for nodes serving calls to estimate gas.

### CODE REVIEW

**Comment by karalabe** [comment]
I don't think your examples are fully exhaustive. Calls have 1/64 stipends that require gas which won't be used. So txs doing calls at the end will not work in this case. Setting and reverting a storage slot again entails refunds. I don't really think going with a "hunch" is good enough rationale for this change, but perhaps if you can reestimate all the past X transactions (say 1 month) and see how many produce accurate results vs under/over-estimate, that would be a good way to back this proposal up.

**Comment by piersy** [comment]
Hi @karalabe thanks for filling me in, could you point me in the direction of some documentation describing the 1/64 stipends that require gas, I wasn't aware of this behaviour?

You mentioned setting and reverting a storage slot, could you explain how that is different to zeroing storage?

I'd be interested in performing the re-estimation, would you be able to provide access to an archive node for this purpose?

**Comment by tynes** [comment]
> Hi @karalabe thanks for filling me in, could you point me in the direction of some documentation describing the 1/64 stipends that require gas, I wasn't aware of this behaviour?
> 
> You mentioned setting and reverting a storage slot, could you explain how that is different to zeroing storage?
> 
> I'd be interested in performing the re-estimation, would you be able to provide access to an archive node for this purpose?

https://docs.soliditylang.org/en/v0.8.12/introduction-to-smart-contracts.html?highlight=63%2F64#message-calls

**Comment by antonydenyer** [comment]
It was my understanding that if you execute something though the evm the resulting `UsedGas` would always be the lowest theoretically possible `gasLimit` required? 

If that is the case then performing a second call with the `UsedGas` to see if it works seems logical. Then if it doesn't work continue to do a binary search. In addition, I think it makes sense to use that return value as the lower bound for the binary search.

**Pull request closed without merging**
