### PR TITLE
cmd/geth, jsre: improve the js command

### PR DESCRIPTION
**Pull request by fjl**
geth js stopped the JS runtime after running the first input file
and blocked for pending callbacks. This commit makes it process
all files and enables quitting with Ctrl-C regardless of callbacks.

Error reporting is also improved. If a script fails to load, the error
is printed and includes the backtrace. package jsre now ensures that
otto is aware of the filename, the backtrace will contain them.

Before:

```text
$ geth js bad.js; echo "exit $?"
... log messages ...
exit 0
```

After:
 
```
$ geth js bad.js; echo "exit $?"
... log messages ...
Fatal: JavaScript Error: Invalid number of input parameters
    at web3.js:3109:20
    at web3.js:4917:15
    at web3.js:4960:5
    at web3.js:4984:23
    at checkWork (bad.js:11:9)
    at bad.js:19:1

exit 1
```

@bas-vk please review

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Wed Apr 20 21:21:26 UTC 2016_

**Comment by obscuren** [comment]
👍

**Comment by bas-vk** [comment]
Code looks 👍 (since when do we have these ugly emojis?).

Since all scripts are executes within the same VM we should describe in the [wiki](https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options) that variables creates by one script can be read/changes in other scripts. This can bite a user who uses the same variable name in multiple scripts. Especially with timers set in one scripts that alter variables it can get tricky.

**Comment by fjl** [comment]
I think that's a feature actually. You can run `geth js my-library.js my-program.js`.

**Pull request merged**
