### PR TITLE
string version for build server

### PR DESCRIPTION
**Pull request by caktux**

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Fri Aug 7 18:16:05 UTC 2015_

**Comment by caktux** [comment]
I know it's redundant but the build server currently depends on that to get the version. It would add an extra two build steps just to get each part of the version, then concatenate the three different properties in every subsequent step also. This is just a hot fix until we resolve this properly.

My suggestion is to have a `VERSION` file at the root of the repo so we no longer depend on parsing the version from code.

**Comment by fjl** [comment]
I know we asked this before, but can't you run geth version instead?

**Comment by obscuren** [comment]
I'll merge this for now. @caktux lets try to find an optimal solution for this once and for all :-D

**Comment by caktux** [comment]
That was never asked specifically, and I'll have to parse that output anyway, which will no doubt change eventually also, and builds will break again... A static `VERSION` file is the way to go, for cpp it's now in the cmake file so that's already more stable and less bound to be changed.

**Comment by fjl** [comment]
I can't find the discussion right now because I'm on the phone‎.If we promised to keep geth version output stable forever, wouldyou use it instead?

**Comment by caktux** [comment]
Yep, that's a pretty good solution in that case :) making the changes to the build server

**Comment by caktux** [comment]
Wait... that solution introduces some problems, as the build first has to be successful to even be able to do `geth version`, hence why parsing from file is required... :(

**Comment by fjl** [comment]
But why is a version required if the build fails? We can't publish the resultif the build doesn't work.

**Comment by caktux** [comment]
The build results are, and it'd be quite inconsistent to have no version set in the build if it failed. Sure you have the commit hash and all, but the version should be set also.

**Pull request merged**
