### PR TITLE
core/vm: use uint256 in EVM implementation

### PR DESCRIPTION
**Pull request by chfast**
Continuation of #20601 by @holiman.

> This PR is another experiment at integrating the fixed-256 bit math library, instead of using the native go big.Int arbitrary precision big number library.
>
> Theoretically, it could make a difference, but historically we haven't seen any big differences. We have some more advanced metrics now, and both @gballet and @chfast has been curious about giving it another go, so let's do a benchmark when we have a couple of machines available.
>
> See #18191 for earlier numbers.

This one uses `uint256@v1.0.0` and removes intpool.

The git history is not perfect, let me know if I should work more on it.

### CODE REVIEW

**Comment by holiman** [comment]
I pushed a loop benchmark as the first commit. 
```
benchstat loop_v0.txt loop_v4.txt 
name          old time/op    new time/op    delta
SimpleLoop-6     198ms ± 5%     145ms ± 1%  -26.52%  (p=0.008 n=5+5)

name          old alloc/op   new alloc/op   delta
SimpleLoop-6    51.6kB ± 0%    76.1kB ± 0%  +47.35%  (p=0.008 n=5+5)

name          old allocs/op  new allocs/op  delta
SimpleLoop-6       110 ± 0%       109 ± 0%     ~     (p=0.079 n=4+5)
[user@work vm]$ 
```

**Comment by holiman** [comment]
This is a substantial change, on a loop which does not access state, but performs some rather common ops, like jump, jumpdest, sub, swap, dup, it shaves of 25%.

**Comment by holiman** [comment]
I pushed another commit, which improves the lookup of a jumpdest analysis and heavily improves the performance of `JUMP`/`JUMPI`. We might want to cherry-pick that to a separate pr. Here's the bench diff when applying the `core/vm: improve jumpdest lookup` commit

```
loop_v4.txt loop_v5.txt 
name          old time/op    new time/op    delta
SimpleLoop-6     145ms ± 1%     115ms ± 1%  -20.86%  (p=0.008 n=5+5)

name          old alloc/op   new alloc/op   delta
SimpleLoop-6    76.1kB ± 0%    76.1kB ± 0%     ~     (p=0.635 n=5+4)

name          old allocs/op  new allocs/op  delta
SimpleLoop-6       109 ± 0%       109 ± 0%     ~     (all equal)
```

**Comment by holiman** [comment]
Some charts. This PR is ahead by about 45 minutes, after a couple of days. 

Screenshot_2020-03-24 Dual Geth - Grafana

**Comment by holiman** [comment]
This PR has consistently lower allocation count 
Screenshot_2020-03-24 Dual Geth - Grafana(1)

**Comment by holiman** [comment]
Funky that travis got this on one of the builds:
```
--- FAIL: TestSingleSideRangeProof (0.05s)

    proof_test.go:426: Expected no error, got the fork point must be a fullnode

{op: 6, key: common.Hex2Bytes(""), value: common.Hex2Bytes("")}, // step 0

{op: 6, key: common.Hex2Bytes(""), value: common.Hex2Bytes("")}, // step 1

{op: 0, key: common.Hex2Bytes("d51b182b95d677e5f1c82508c0228de96b73092d78ce78b2230cd948674f66fd1483bd"), value: common.Hex2Bytes("0000000000000002")}, // step 2
```

..?

**Comment by holiman** [comment]
Might be a good idea to also pull in this one: https://github.com/ledgerwatch/turbo-geth/pull/556/commits/7f9557f35db532cab63054c33cadd1ccf920c69e

**Comment by chfast** [comment]
> Might be a good idea to also pull in this one: [ledgerwatch/turbo-geth@7f9557f](https://github.com/ledgerwatch/turbo-geth/commit/7f9557f35db532cab63054c33cadd1ccf920c69e)

I was considering doing the same change, but there is probably a way to eliminate the need for some parts of the `Safe` interface.

**Comment by chfast** [comment]
I can fix `uint256` build for Go 1.12 if that's desired.

**Comment by holiman** [comment]
> I can fix uint256 build for Go 1.12 if that's desired.

It's definitely not needed by geth -- due to the new error handling introduced in 1.13, we're going to deprecate 1.12 anyway. Both the new snapshot sync implementation and https://github.com/ethereum/go-ethereum/pull/21067 deprecates 1.13

**Comment by holiman** [comment]
The benchmark currently running on bench01/02 is almost done, this evening I can spin up a benchmark of this PR, to give it a final spin.

**Comment by holiman** [comment]
I rebased again to get most recent head-fixes in

**Comment by holiman** [comment]
Ok ,benchmark is started. https://geth-bench.ethdevops.io/d/Jpk-Be5Wk/dual-geth?orgId=1&var-exp=bench01&var-master=bench02&var-percentile=50&from=1590434109271&to=now . 

```
May 25 21:14:33 bench01.ethdevops.io geth INFO [05-25|19:14:33.545] Starting peer-to-peer node instance=Geth/v1.9.15-unstable-30b26f83-20200525/linux-amd64/go1.14.3
May 25 21:14:40 bench02.ethdevops.io geth INFO [05-25|19:14:40.123] Starting peer-to-peer node instance=Geth/v1.9.15-unstable-dbf6b8a7-20200525/linux-amd64/go1.14.3 
```
Both started at `5013683`. For some reason I set them both to use `--snapshot`, so it'll take a couple of hours or so for them to generate it and act 'normally' again. Doesn't hurt to do moar snapshot runs, I guess.

**Comment by holiman** [comment]
Here's from when the two were finished generating snapshot: https://geth-bench.ethdevops.io/d/Jpk-Be5Wk/dual-geth?orgId=1&var-exp=bench01&var-master=bench02&var-percentile=50&from=1590442980695&to=now . This PR is `bench01`, `master` is `bench02`

**Comment by holiman** [comment]
Oddly enough, in this portion, the `uint256` PR was ahead, but was overtaken by `master`. 
https://geth-bench.ethdevops.io/d/Jpk-Be5Wk/dual-geth?orgId=1&var-exp=bench01&var-master=bench02&var-percentile=50&from=1590538399305&to=1590591365741

**Comment by chfast** [comment]
Opsiee.

**Comment by holiman** [comment]
Pushed a change. I may have found how/why the uint256 branch regresses: and it's due to the overhead of mem usage calls are made. It "allocates" (not via malloc, but on the stack) 1024 *32-byte at every `call`, which was not the case for master, since it previously used pointers instead. 

The `capacity` of a slice is immediately allocated. From the docs:
```
//      For example, make([]int, 0, 10) allocates an underlying array
//    of size 10 and returns a slice of length 0 and capacity 10 that is
//    backed by this underlying array.
```

Rerunning the benchmark, now with `05e5643483b7db8adfe20d1a9ca66fb5ae6a6744` (this PR) on `bench01` against `a5eee8d1dc61352c29b9800eaf96609ba4184fd6` (`master`) on `bench02`.

**Comment by holiman** [comment]
With the last change, after 24 hours, this PR is about 45 minutes ahead of master.

**Comment by holiman** [comment]
Here's a segment taken 24 hours into the benchmark

Screenshot_2020-06-02 Dual Geth - Grafana

The average of `execution` is `28.4` vs `36.9`. 

Here are the last 6 hours: 

Screenshot_2020-06-02 Dual Geth - Grafana(1)

**Comment by holiman** [comment]
rebased

**Pull request merged**
