### PR TITLE
testing, please ignore

### PR DESCRIPTION
**Pull request by holiman**
Seems there's some new tool checking secrets being checked into repos. This is just a test of that thing.

### CODE REVIEW

**Comment by holiman** [comment]
oh noes all my secrets, best I close this so PR then so nobody can see them

**Comment by karalabe** [comment]
You need to hex encoded it so it's not visible, duh!

**Comment by holiman** [comment]
a no worries, it was already base64-encrypted, phew!

**Comment by karalabe** [comment]
You do know that unless we add that the above are obvious sarcasm, someone
will dig it up and put in on Twitter? ;P

**Pull request closed without merging**
