### PR TITLE
core/state: new state forking (reloaded)

### PR DESCRIPTION
**Pull request by obscuren**
**`core/state: added state copy benchmark`**

Adds a benchmark to measure the difference between the new state changes and the current

**`core/state: improved state API and copying mechanism`**

The old state copy mechanism made deep copy for every object in state, most of them not required by the new state and therefor wasting a ton of resources. The copy of a state can be made using the `state.Fork` function, which will allocate a new State and return it. This new object holds a refernce to it's parent which can be used to query for any information not currently available. When an object can not be found it will recusively call the parent for the object until it reached the root
state and checks the state trie. Objects are now copied on demand and will never be copied during the `state.Fork` function call.

State can also be flattened in to one single object, merging all the state from root to current, leaving a single state with all recent changes. State can be flattened using `state.Flatten`

In addition the following methods have changed to functions instead:

* state.Commit
* state.BatchCommit
* state.IntermediateRoot

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: fde7287250937f4abd60e26aa0b91286f0ce3587
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: a0edffd0ee5eda3c333832e2d9a950734aa7b318
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: a0edffd0ee5eda3c333832e2d9a950734aa7b318
  * Commits must be prefixed with the package(s) they modify

 * Commit: c66be719a809af4baf462d6ec035b42dc06aae35
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: ef29262ceb8b4e6e598aa4492fc0c3318db49220
  * Commits must be prefixed with the package(s) they modify

 * Commit: 372c4da9443ffed61c99a3080a4b01f3b790027d
  * Commits must be prefixed with the package(s) they modify

 * Commit: f5af33118ebf7cf1f79e40c8c2d4398518083b2e
  * Commits must be prefixed with the package(s) they modify

 * Commit: 80e9f40ef7741261d8920bee694c0b0ede8055a1
  * Commits must be prefixed with the package(s) they modify

 * Commit: dd341b6089dece266f29c63709d218ae6849a50a
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 4573773a91e18b28b50f4c0610344a806a8fbcb2
  * Commits must be prefixed with the package(s) they modify

 * Commit: ec9b582fe1fe5be1d196277f56f88163a61226d1
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by obscuren** [comment]
Closing in favour of https://github.com/ethereum/go-ethereum/pull/3092

**Pull request closed without merging**
