### PR TITLE
allow passing custom compiler args

### PR DESCRIPTION
**Pull request by krasi-georgiev**
Signed-off-by: Krasi Georgiev <8903888+krasi-georgiev@users.noreply.github.com>

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
still working out the details, just checking if you are willing to take such a PR?

**Comment by krasi-georgiev** [comment]
> provide geth with the artefacts.
did you mean to provide abigen with the artifacts for generating the bindings?

Removing the compilation part means removing the `./common/compiler` package, which is like 200-300lines of code. If you want to remove this extra maintenance, you can refactor abigen to require the artifacts folder.

I have built my own wrapper which adds downloading the contracts from etherscan directly, downloading the required compiler  and generating the bindings.
https://github.com/cryptoriums/contraget/blob/main/pkg/contraget/contraget.go

**Comment by holiman** [comment]
> > provide geth with the artefacts.

> did you mean to provide abigen with the artifacts for generating the bindings?

Yes, I meant that geth would only look at the compiler outputs, the abi definitions, but not try to orchestrate the compilers.

**Comment by krasi-georgiev** [comment]
that sounds reasonable, I can refactor the PR to do that and as an addition can move the `compile` package in a repo I maintain in case people prefer to still use this wrapper

https://github.com/cryptoriums/packages

**Comment by karalabe** [comment]
The compiler calls were removed on master, so this PR is not not relevant any more. Sorry for the wasted effort, though your PR did prompt cleaning up our code a bit, so I guess that's a plus :)

**Pull request closed without merging**
