### PR TITLE
use the SHA3-512 hash of pulic key is distance calculation

### PR DESCRIPTION
**Pull request by keks**
Disclaimer: please don't merge this yet; read on
This addresses #495. I have some comments to this:
- I used the sha3 library provided in your source code. Is there a reason you don't use `golang.org/x/crypto/sha3`?
- I didn't fix the tests. I am not familiar with ethereums structure yet so I wasn't sure how to fix them without just setting the values so that they pass; and honestly I didn't run them beforehand so I don't know if they had failed anyway. I can try to look into this tomorrow, but I'd like to know how you'd approach this.

### CODE REVIEW

**Comment by fjl** [comment]
First of all, thank you for your contribution. It doesn't happen very often that someone submits a contribution of such impact out of the blue. I was actually going to work on this issue right this weekend ;).

We use an earlier version of the keccak algorithm mostly because the rest of ethereum also uses it. Our `crypto/sha3` package is not compatible with `golang.org/x/crypto/sha3`. We actually never use the 512 bit variant, but always use Keccak256.

About the code: `distcmp` is not the only place that implements the distance metric. you would also need to adapt `logdist`. `logdist` determines the bucket in which the node is placed (buckets are a kind of index by distance). Your solution, while effective, will create a lot of computation overhead. A better way to approach this would be to store the hash in `Node` and then modifying the distance functions so they operate on hashes. 

Fixing the tests for this change will be a bit harder because the switch to `sha3` makes `randomID` impossible to implement (that's one of the reasons why we want to make this switch). The tests very much rely on it. A solution for that (similar to the suggestion above) would be to generate random hashes at a certain distance and ignoring the fact that IDs and hashes do not correspond. I don't know yet whether this is actually feasible for all the tests.

**Comment by fjl** [comment]
As a general comment, the tests of `p2p/discover` must pass before something can be merged.

**Comment by keks** [comment]
Oh, okay I figured the target already was in the correct format, but now that you mention it, that doesn't make much sense. I chose the 512bit-version because you have 512 bit NodeIDs. By the way, I implemented Kademlia in Go not too long ago and was amused to see that you have the same lookup table for the determining the correct bucket :).

I believe attaching the hash to the `Node` struct is not the way to go, because the distance functions operate on `NodeID`, not on `Node`. I suspect the callers often don't have a `Node` yet, only the `NodeID`, so changing that isn't possible either.

I still don't really know what to do about the test cases; I am afraid to break stuff, but I'll do my best and show you what I came up with.

Definitely, merging untested code would be madness.

**Comment by keks** [comment]
Also, I don't think optimizing for execution speed is the right thing to do right now. By the way: how about a distance type that has a `Less()` method attached? Changes would only need to take place in there if stuff changes again.

Also, isn't there some ethereum protocol that all implementations must meet? Changing the distance metric would break compatibility, or am I missing something?

**Comment by keks** [comment]
I looked at the code again and I'm pretty sure you need I need to use the 512bit hash. Suddenly changing the address length probably breaks more stuff.

**Comment by zelig** [comment]
it can safely be 256 bit. 

"I believe attaching the hash to the Node struct is not the way to go, because the distance functions operate on NodeID, not on Node"  well that's the point, they need to operate on NodeIDHash or whatever you call it. 

I had a stab at this earlier, but got killed :) 
https://github.com/ethersphere/go-ethereum/tree/p2p-cademlia/p2p

**Comment by fjl** [comment]
> I believe attaching the hash to the Node struct is not the way to go, because the distance functions operate on NodeID, not on Node.

The distance functions will take the hash as the argument, not `Node`. In fact, they don't need to change at all except for the parameter type.

>  I suspect the callers often don't have a Node yet, only the NodeID, so changing that isn't possible either.

I can assure you that callers (will) have a `Node` always. 

> Also, isn't there some ethereum protocol that all implementations must meet? Changing the distance metric would break compatibility, or am I missing something?

> I looked at the code again and I'm pretty sure you need I need to use the 512bit hash. Suddenly changing the address length probably breaks more stuff.

We have had long internal discussions about this change and all implementations are working on an update to the sha3 distance right now. Keccak256 will be used.

**Comment by fjl** [comment]
@zelig your stab was not merged because it renamed `NodeID`, among other reasons.

**Comment by keks** [comment]
I didn't know all implementations change to the sha3. I thought only the go implementation changed and that would have created incompatibilities.

My suggestion for this: create a cache for hashes. Instead of hashing, ask the cache and if that misses it just computes the hash, stores it and returns it to you. If you ask at a later point it just fetches the hash from the cache. The easiest implementation would be a map[NodeID][]byte guarded by a mutex.

I wouldn't introduce a new `NodeIDHash` type, because working with []byte saves you from allocation and copying memory all the time. I'll fix up a patch and show you, just tell me what you think. I can still change the type of `distcmp` and the others later.

**Comment by fjl** [comment]
How would you prevent the cache from growing too big?Storing the cache on the node has the advantage that it exists as long as the node is stored in the table. It wouldn't need a mutes either. I don't see why you want to avoid this solution.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ‎

**Comment by keks** [comment]
Okay, I guess you're right. However, I still don't think implementing a type for the hash is wise, otherwise a lot of copying would take place on function calls. What do you think?

**Comment by zelig** [comment]
I don't see any more copying. Its just one more field on `Node` as a result of a single hashing.

**Comment by keks** [comment]
That's not what I meant. Assume I use type `NodeIDHash` instead of `[]byte` to store the hash in, and the hash returns []byte, then every time a new address is encountered I need to copy the data from the `[]byte` returned by `hash.Sum()` to the `NodeIDHash`. Instead, I could operate on `[]byte` directly.

**Comment by fjl** [comment]
You can use `[]byte` if you want. Or make an array  type `hash‎` and pass `*hash` to avoid copying. Note however, that arrays can usually be allocated on the stack so the copying will usually not be a problem. Again, thank you for taking the time to work on this.

**Comment by fjl** [comment]
My preferred solution would have:

```go

type hash [32]byte

type Node struct {
    ...
    sha hash
}

func logdist(a, b hash) int 

```

**Comment by keks** [comment]
When using `[32]byte` oder `*[32]byte`, you still would need to copy the data from the `[]byte` returned from `hash.Sum()` to that type, that's what I meant by copying.

**Comment by keks** [comment]
I am currently in the process of fixing the tests. They already compile, but of cause fail. Especially the `randomID` function doesn't make sense anymore but I don't find a way to fix it without finding collisions in sha3 ;).

I can post my progress by now and you can just tell me what you think of it.

**Comment by keks** [comment]
One approach would be to rewrite all the tests to use `nodeIDHash` instead of `NodeID`. I don't know if that can be done everywhere though.

**Comment by keks** [comment]
Also, there still are 513 buckets. I guess this number should be reduced now that the addresses used for distance calculations are shorter?

**Comment by keks** [comment]
I don't know, I think `randomID` could be changed to work on the soon-to-be-exported (I'm working on it) NodeIDHash. BTW, I figured it should be unexported because Felix dubbed it `hash`, which is unexported as well.

**Comment by fjl** [comment]
My plan for the tests was to generate random hashes at a certain distance instead. That would basically mean renaming randomID to randomHash and changing the type. I think none of the tests will require generating a matching ID at a certain distance, so you can put anything in the ID. 

The number of buckets always corresponds to the length, so we'd need 257 buckets (actually 256 but there is something about logdist that makes 257 more convenient).

Please don't export the hash in any way. This is an implementation detail. 
We have discussed making the lookup target a hash, too. That would be the only place where it would surface. You can make that argument a byte slice for now. 
‎

**Comment by zelig** [comment]
by passing the hash instead of nodeid as arguments a few other places i think you can save hashing.
https://github.com/ethersphere/go-ethereum/commit/f5f69dff19824a853859a76f98c09645f10c16db
note its confusing in my branch hash was called node id and node id was public key!

**Comment by fjl** [comment]
The hash should not be exported. Dammit.

**Comment by zelig** [comment]
I take dammit as a kind request to consent: sure, let's export after conversion. its not crucial now.
FWIW my previous comment pointed to code internal to discover where changing arguments passed around can save a few calls to hash. 
thanks @keks @fjl for taking care of my pet peeve

**Comment by keks** [comment]
I've just gone into the [performance][benchmark] of hashing again and I came to the conclusion that saving at this part is completely misguided. It would be much easier not the change the distance computation function's types and just hashing every time in that function. On my good ol' Thinkpad X61 ([1.6GHz Core 2 Duo][cpu]) computing one of these hashes without reusing the hasher takes roughly 6.5 microseconds; reusing it brings it down to 4.5.

Considering the code complexity that would be added when introducing a second type and mixing and matching them all over the package, I would strongly suggest to either just change the two functions (distcmp and logdist) and throw out the tests that make the assumption that similar `NodeID`s must be close to each other or rename `NodeID` to `PubKey` and make the hash the new `NodeID`. Unfortunately, I currently don't have time for anything but the former.

[cpu]:http://ark.intel.com/products/29757/Intel-Core2-Duo-Processor-L7500-4M-Cache-1_60-GHz-800-MHz-FSB
[benchmark]:http://play.golang.org/p/pNdmalrDRb

**Comment by keks** [comment]
Let's take these numbers one step further. Assume you need to send receive 10000 packets per second for all the looking up and DHT bookkeeping. if, for each of these packets, you need to compute one hash, that would be 10000 hashes, on my CPU that are 0.065s of hashing per second, so the hashing would account for 6.5% my CPU time - alot.

However, consider what this means in bandwidth: assume that a packet contains at least one NodeID of 64 bytes, that would be 640kB/s. I think that if I send /that/ many packets, 6.5% CPU just for hashing is not all that bad.

**Comment by fjl** [comment]
Good calculations. Unfortunately, deleting the tests that need to generate values at a certain distance would reduce the test coverage a lot. At the moment, pretty much all the tests for the table logic rely on that so the nodes inserted for testing fall into certain buckets. I am not really looking forward to designing an entirely new test suite for the table that. Making node ID a hash is not possible because the ID has a very specific meaning: it is the public key of the node. We need the public key in order to encrypt certain packets in the TCP-based RLPx protocol. Do you have the time and energy to continue this effort, or should I just pick up your changes and continue?

**Comment by keks** [comment]
I currently am to busy to go through this, sorry. I'm writing my bachelor's thesis and thought "oh, this seems doable" when I was looking at the issue list. Sorry I kept you from getting this done this weekend, I didn't expect this to be that much work. I'd love to contribute later, though.

**Comment by fjl** [comment]
Please do! We are always looking for contribut‎ors. :)I will continue working on this next week.

**Comment by keks** [comment]
Great :). One idea I just had: don't call it `nodeIDHash` but `nodeKadID` or something like that. That way it will be much more clear what it does instead of how it is created.

**Pull request closed without merging**
