### PR TITLE
contracts/chequebook: add chequebook contract wrapper

### PR DESCRIPTION
**Pull request by fjl**
The wrapper code is adapted from the swarm/services/chequebook package
with the following mostly cosmetic changes:

* The code now uses the new Go API interfaces to query balances. Some
  minor functional changes were required to make this work.
* The package no longer depends on swarm/services/swap/swap. References
  to swap.Promise are replaced by interface{}, the base type of Promise.
  This is temporary.
* The contract wrapper has been regenerated with latest abigen
  and solc v0.3.6.
* There is a new generator that creates the 'deployed code' variable.
* Documentation comments now follow the recommended godoc style.
* [CHEQUEBOOK] log prefixes are gone.
* LGPL license headers have been added to all files.

I am committing this as @zelig because he wrote the swarm chequebook code. When reviewing, it might be useful to compare this to the originial code from the swarm branch. To do that, check out the swarm branch separately and run diff.

```text
cd $GOPATH/src/github.com/ethereum
git clone --branch swarm https://github.com/ethereum/go-ethereum go-ethereum-swarm
diff go-ethereum-swarm/swarm/services/chequebook/cheque.go go-ethereum/contracts/chequebook/cheque.go 
```

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Sun Aug 28 13:23:20 UTC 2016_

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 6dfd4257bc79a4597db9d50331c9d106e930d2ac
  * Your commit message body contains a line that is longer than 72 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 2aa824af764128884d03f088f179de47be65b2f8
  * Your commit message body contains a line that is longer than 72 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by zelig** [comment]
:+1:

**Comment by nagydani** [comment]
:+1:

**Pull request merged**
