### PR TITLE
cmd/bootnode, cmd/utils: add 'pmp:<IP>' to --nat flag description

### PR DESCRIPTION
**Pull request by dbadoy**
[https://github.com/ethereum/go-ethereum/blob/01808421e20ba9d19c029b64fcda841df77c9aff/p2p/nat/nat.go#L52-L62](https://github.com/ethereum/go-ethereum/blob/01808421e20ba9d19c029b64fcda841df77c9aff/p2p/nat/nat.go#L52-L62)

Wouldn't adding that mechanism help to configuration?

### CODE REVIEW

**Comment by holiman** [comment]
>	"pmp"                uses NAT-PMP with an auto-detected gateway address
>	"pmp:192.168.0.1"    uses NAT-PMP with the given gateway address

With this change, it might look like providing IP is mandatory -- but according to the docs, it seems like the default is probably safest, the auto-detected gateway address. So I think we should leave it as is. Because the alternative would be to show that it _can_ be supplied, but is optional... and that just seems too condensed and complex: 

```
    --nat value                    (default: "any")
          NAT port mapping mechanism (any|none|upnp|pmp:<IP (optional)>|extip:<IP>)
```

**Comment by holiman** [comment]
Possibly we could extend the description, like 
```diff 
diff --git a/cmd/utils/flags.go b/cmd/utils/flags.go
index cb7ff910d0..2ce8b62727 100644
--- a/cmd/utils/flags.go
+++ b/cmd/utils/flags.go
@@ -832,8 +832,19 @@ var (
 		Category: flags.NetworkingCategory,
 	}
 	NATFlag = &cli.StringFlag{
-		Name:     "nat",
-		Usage:    "NAT port mapping mechanism (any|none|upnp|pmp|extip:<IP>)",
+		Name: "nat",
+
+		Usage: `NAT port mapping mechanism (any|none|upnp|pmp|extip:<IP>)
+
+The available choices are 
+any: bla bla, 
+none: no nat used, 
+upnp: foo bar,
+pmp:  uses NAT-PMP with an auto-detected gateway address
+pmp:<IP> uses NAT-PMP with the given gateway address
+extip:<IP> uses the IP as the external IP
+`,
+
 		Value:    "any",
 		Category: flags.NetworkingCategory,
 	}
```
But I don't know, the formatting becomes a bit screwy:
```
[user@work go-ethereum]$ geth --dev -h   | grep nat -A 10
    --nat value                    (default: "any")
          NAT port mapping mechanism (any|none|upnp|pmp|extip:<IP>)
          
          The available choices
          are 
          any: bla bla, 
          none: no nat used, 
          upnp: foo bar,
          pmp:  uses NAT-PMP with
          an auto-detected gateway address
          pmp:<IP> uses NAT-PMP with the given gateway
          address
          extip:<IP> uses the IP as the external IP
```

**Comment by dbadoy** [comment]
How about splitting it into `pmp` and `pmp:<IP>`? I think these two are different mechanisms.

**Comment by dbadoy** [comment]
Auto-detection only considers x.x.x.1 as a gateway, so have to use `pmp:<IP>` otherwise, but I think it's hard for users to know this now, so I submitted this PR.

**Comment by holiman** [comment]
> How about splitting it into pmp and pmp:<IP>? 

Yeah that sounds like an ok compromise to me

**Review by fjl — APPROVED** [review]

**Pull request merged**
