### PR TITLE
fdtrack: hide message

### PR DESCRIPTION
**Pull request by obscuren**

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Wed Aug 19 19:19:39 UTC 2015_

**Comment by fjl** [comment]
Let's just remove the tracking instead. Nobody has reported anything regarding high usage since the fix was pushed last week.

You can remove it with `git revert 5c949d3b3ba81ea`.

**Comment by obscuren** [comment]
Done

**Comment by fjl** [comment]
:+1:

**Pull request merged**
