### PR TITLE
go.mod : goleveldb update

### PR DESCRIPTION
**Pull request by ucwong**
including cache and other optimizations from 2021-2022
https://github.com/syndtr/goleveldb/commit/4bbca4ea2470b1c244f502710f0cc52023ba0e44

https://github.com/syndtr/goleveldb/commit/678c1e822a17275fef61c4d39b468c794b718422

https://github.com/syndtr/goleveldb/commit/126854af5e6d8295ef8e8bee3040dd8380ae72e8
https://github.com/syndtr/goleveldb/commit/75fe51978d5f82f9b62d1025e1d061cb2008c38b
https://github.com/syndtr/goleveldb/commit/cc7a1bdbc7f20c75b15890cc2137eeef77cbce62
https://github.com/syndtr/goleveldb/commit/943eb65c10f0a3b289dcda08a6faffe068d4178a

### CODE REVIEW

**Comment by fjl** [comment]
We have already tried this upgrade for a while, and unfortunately had to downgrade again (PR #25413) because the newer version has some bugs.

**Comment by ucwong** [comment]
> We have already tried this upgrade for a while, and unfortunately had to downgrade again (PR #25413) because the newer version has some bugs.

https://github.com/syndtr/goleveldb/pull/409/files
I think this PR has been fix the issue above

**Comment by fjl** [comment]
We tried it, and still had issue reports from users.

**Comment by ucwong** [comment]
> We have already tried this upgrade for a while, and unfortunately had to downgrade again (PR #25413) because the newer version has some bugs.

OK, I have used this version for months, but it seems OK now.

**Pull request closed without merging**
