### PR TITLE
Fix path problem with Solidity compile with filepath.Glob on Windows

### LINKED ISSUE #2244: Error when using Solidity: "solc: no build results found"
Geth instance: Geth/v1.3.3/windows/go1.5.1
Solidity : Version: 0.2.2-d3bb5d01/Release-Windows/msvc/JIT linked to libethereum-
Error: 
solc: no build results found
    at InvalidResponse (<anonymous>:-81662:-44)
    at send (<anonymous>:-156322:-44)
    at solidity (<anonymous>:-133322:-44)
    at <anonymous>:1:12

Issue #1770 (https://github.com/ethereum/go-ethereum/issues/1770) is said to have been fixed but continue to see it in my latest windows installs for geth and solidity

### PR DESCRIPTION
**Pull request by remyroy**
Fixes #2244.

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Fri Mar 4 19:52:21 UTC 2016_

**Comment by karalabe** [comment]
LGTM :+1: 

Notes to reviewers:

 * Per the [Glob pattern syntax](https://golang.org/pkg/path/filepath/#Match), `.` doesn't have to be escaped as it's not a special character
 * *"On Windows, escaping is disabled. Instead, '\\' is treated as path separator."*

**Comment by fjl** [comment]
:+1: but please change commit message to say "common/compiler: fix ..."

**Comment by obscuren** [comment]
Per @fjl's suggestion, please fix the commit message and it will get merged.

**Comment by remyroy** [comment]
Done.

**Pull request merged**
