### PR TITLE
eth/gasestimator: allow slight estimation error in favor of less iterations

### PR DESCRIPTION
**Pull request by karalabe**
This PR adds three optimisations to gas estimation:

- A precise optimization is trying to return 21000 gas for plain transfers. It does it if there's no contract code at the receiver side and no input data. The call is still simulated before returning 21000 to catch any potential future unaccounted tx cost (like access lists currently). This results in a total iteration count of 1 for plain transfers.
- Introduces an error ratio (currently set to 1.5%) to allow short circuiting the binary search faster by returning a slight overestimate. This reduces the number of needed estimation calls from 18-20 to 7-8 at the cost of overshooting the perfect estimate by 1.5% gas max. Maybe this could be made configurable in the future, but I think it's useful to be more agressive by default than perfect.
- Introduces an optimization from @orenyomtov that tries to "guesstimate" the needed gas as `gasUsed + gasRefund` (I've added a call stipend on top + a 64/63 multiplier to account for gas forwarding rules). Most of the time this estimate will be enough to cover the execution. The original proposal did an early return, but that has a variance of 1-11% error ratio, which is a bit unpredictable, so this PR doens't do an early return, rather uses the result as a `lo` or `hi` cap for the binary search, cutting the iteration count in half most f the time whilst preserving the 1.5% precision.

FWIW, it would most definitely be possible to make the error ratio configurable, but I'm unsure if that's a desirable aspect. If it's configurable via a CLI flag, node operators are incentivised to bump it all the way up as it saves them CPU. This might get weird if different operators run with different limits. On the other hand, if it's configurable via a RPC param to eth_estimateGas, then callers could just yolo it down to 0 error, because why not, they are paying the same, so might as well max out precision. As such, this PR for now picks a percentage that seems small enough to be irrelevant as an overestimate, but forces it upon everyone equally.

### CODE REVIEW

**Review by holiman — APPROVED** [review]
LGTM

**Review by MariusVanDerWijden — APPROVED** [review]
LGTM

**Comment by wjmelements** [comment]
This wasted some of my time today. How do I workaround? There should have been a parameter or something but I don't see it in the code.

**Comment by Ashflower13** [comment]
Ok yes.    I got to get some things done over next free days.

**Comment by wjmelements** [comment]
> This wasted some of my time today. How do I workaround? There should have been a parameter or something but I don't see it in the code.

There should be a way to set estimateGasErrorRatio or ErrorRatio but there is not. As a result geth is returning incorrect estimateGas.

**Comment by Ashflower13** [comment]
Going To be free next free days info in couple

**Pull request merged**
