### PR TITLE
cmd, consensus: add option to disable mmap for DAG caches/datasets

### PR DESCRIPTION
**Pull request by de1acr0ix**
The block submission RPC in current geth takes some non-trivial time. It uses the full DAG datasets which is mmaped. It does not guarantee that whole datasets is going to be in the memory and I/O can cause pretty big delays. This PR added `--ethash.cacheslockmmap` and `--ethash.dagslockmmap` options to lock memory map contents in memory to address this issue.

### CODE REVIEW

**Comment by fjl** [comment]
Both @karalabe and me aren't very happy with the implementation in this PR, even though the idea is pretty good. There might be a simpler way to do this: just force the OS to load all of the mapped file after mmapping it. It might also be possible to pin the mmap'ed region into main memory using platform-specific mmap flags.

**Comment by de1acr0ix** [comment]
> Both @karalabe and me aren't very happy with the implementation in this PR, even though the idea is pretty good. There might be a simpler way to do this: just force the OS to load all of the mapped file after mmap'ing it. It might also be possible to pin the mmap'ed region into main memory using platform-specific mmap flags.

@fjl @karalabe Thanks for the hint. I have changed to use `Lock()` method provided by `go-mmap`. And I also changed option names to `--ethash.cacheslockmmap` and `--ethash.dagslockmmap`. Please review the change.

**Comment by adamschmideg** [comment]
We have to check the behaviour of `mlock` on Linux

**Comment by karalabe** [comment]
The PR look godo to me btw, we just need to sanity check that it runs as expected.

**Comment by de1acr0ix** [comment]
@adamschmideg @karalabe Sorry I didn't have much time for coding recently. I have added a simple benchmark `BenchmarkHashimotoFullMmap()` to showcase the difference. I also rebased the change to newest `master`.

**Comment by haihongS** [comment]
I am curious about the result of enabling cacheslockmmap and dagslockmmap. Seemingly it will accerelate the speed for submitting new mined block and may cost much more memory?

I guess it probably needs 4g+ extra memory if we keep only 1 cache in memory?

@de1acr0ix

**Comment by de1acr0ix** [comment]
> I am curious about the result of enabling cacheslockmmap and dagslockmmap. Seemingly it will accerelate the speed for submitting new mined block and may cost much more memory?
> 
> I guess it probably needs 4g+ extra memory if we keep only 1 cache in memory?
> 
> @de1acr0ix

Yes it would improve the speed for submitting mined block (from ~1s to negligible) at the cost of using more memory. The memory used is the DAG dataset sizes summed up, so it is ~3.62 GB as of now (epoch 335).

In fact you can further reduce the memory usage by forking Geth to use light verification of PoW (original PR #19899 actually uses that). The light verification still yields pretty good performance (<2ms PoW verification) but uses much less memory.

**Pull request merged**
