### PR TITLE
core, eth/filter: optimize log retrieval

### PR DESCRIPTION
**Pull request by bas-vk**
**WIP, currently integration receipts during fast sync is too slow.**

This PR includes:

- [X] optimizes (re)generation of mipmap bloom pre-images
- [ ] use db batches for inserting receipts during fast sync
- [X] optimizes mipmap bloom levels for logs searching
- [X] replaces custom bloom filter implementation with package github.com/tylertreat/BoomFilters

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: a05f80847bd5a49cbbc05b81a7ab9998f3f8f5c1
  * Your commit message body contains a line that is longer than 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: e9b7c1a67e19f8c43f84a25756b6b52f91cd7a24
  * Your commit message body contains a line that is longer than 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 18e67419db2f05e6e7d48ecd63934076e9d07447
  * Your commit message body contains a line that is longer than 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 9f60d9cf03e1af86fb7f99cc8de9527ae7ef0331
  * Your commit message body contains a line that is longer than 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 34445d22cf6b8da3f1f2721ca3a7a7c9740f8332
  * Your commit message body contains a line that is longer than 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by fjl** [comment]
We have decided to use the bloom-bits approach in #3749.

**Pull request closed without merging**
