### PR TITLE
vendor: introduces leveldb pick compaction optimization

### PR DESCRIPTION
**Pull request by rjl493456442**
The upstream PR is https://github.com/syndtr/goleveldb/pull/268

Open this PR for experiment.

### CODE REVIEW

**Comment by karalabe** [comment]
Running on mon07

**Comment by Matthalp** [comment]
Should this also update `vender/vendor.json`?

**Comment by rjl493456442** [comment]
@Matthalp Just experiment only. The upstream hasn't been merged :)

**Comment by rjl493456442** [comment]
Close it because of #19284

**Pull request closed without merging**
