### PR TITLE
accounts/abi: Fix the bug of mobile framework crashing

### PR DESCRIPTION
**Pull request by croath**
...in the situation of only one output interface.

Fix: https://github.com/ethereum/go-ethereum/issues/14832
Thanks @OrenZak for your great work at https://github.com/ethereum/go-ethereum/pull/15402

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 67b536887eab38b46d88ee8efa8162643ee00649
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by karalabe** [comment]
It's very hard to evaluate these changes in themselves. Could you please add a test case for which the current code fails? It's important to build up an exhaustive test suite to prevent future regressions.

**Comment by croath** [comment]
Hi @karalabe , I just added a test case for mobile only. Without the changes I made in this pull request, the testing code will generate an error like:

`failed: expected no err but got: abi: cannot unmarshal *big.Int in to []interface {}`

The reason is the `Call` function on mobile turn all `Interface` into `[]Interface{}`: https://github.com/ethereum/go-ethereum/blob/master/mobile/bind.go#L157

**Comment by OrenZak** [comment]
Hi @croath  and @karalabe , I'm glad I could help.
Thanks for updating a test case to that scenario.

**Comment by croath** [comment]
Can anyone review this pull request? @karalabe

**Comment by croath** [comment]
@karalabe can you review this pull request?

**Comment by holiman** [comment]
My take on this PR is that it adds a fix at the wrong level. For whatever reason, the mobile bindings does a []interface to place the output into, at https://github.com/ethereum/go-ethereum/blob/master/mobile/bind.go#L157  . This PR just 'randomly' returns the first element if it happens to be holding a list.. 

So it's kind of.. in quirk no 1, we add a level of 'list' going in, and this PR adds quirk no 2, not tightly coupled with quirk no 1, to offset the effects of quirk no 1. 

A better fix imo would be to make the fix in the mobile binding package, where quirk no 1 is introduced in th first place. I must admit I haven't studied the problem deep enough to know why the mobile bindings behave like this in the first place.

**Comment by croath** [comment]
Hi @holiman , thanks for your review. I agree with you about the workaround at quirk 2 is not that good, because we'll leave 2 bugs there if following that way.

Could you check my latest commit? It's been fixed at the very beginning.

**Comment by croath** [comment]
@karalabe Can you review the appending code?

**Pull request merged**
