### PR TITLE
cmd/geth,internal:  set cpu number when geth starting

### PR DESCRIPTION
**Pull request by jsvisa**

### CODE REVIEW

**Comment by karalabe** [comment]
I don't really see the point in this? Why would you want to artificially control the threading limit?

**Comment by jsvisa** [comment]
@karalabe I'm developing geth in local MacOS, if the threading number is not limited, and the geth in syncing process, then the entire system got stuck.  So I've to limit the geth threading number to reduce the cpu usage.

**Comment by fjl** [comment]
I think there is a simpler way: let's remove the call to `runtime.GOMAXPROCS`. Then you can set it in your shell environment. It's OK to remove this call because the runtime defaults to number of CPUs anyway.

**Comment by jsvisa** [comment]
@fjl thanks for your reply, LGTM, and @karalabe what's your opinion?

**Comment by karalabe** [comment]
We can do that too, yes. I didn't know they changed it.

**Comment by jsvisa** [comment]
@fjl  remove the call to `runtime.GOMAXPROCS()` , PTAL

**Comment by stvenyin** [comment]
I 'm know cmd/internal/browser communication tools

**Pull request merged**
