### PR TITLE
whisper: fixed broken partial topic filtering

### PR DESCRIPTION
**Pull request by evgen-povt**
The merged pull request #15811 broke the partial topic filtering. Here is a fix.

### CODE REVIEW

**Comment by gluk256** [comment]
@b00ris your change in #15811 broke partial topics. Do you remember what is the reason for this code:

```go
if len(bt) < TopicLength {
	return false
}
```

**Comment by evgen-povt** [comment]
@gluk256 his comment on the pull request left 2 month ago:

@gballet It's related to this check https://github.com/b00ris/go-ethereum/blob/6600165e27c0396ecf1aa472865cd0daccdb061e/whisper/whisperv5/filter.go#L223.
I've added this to avoid same bugs later.
TestVariableTopics used topics with smaller length. I thougth that it's not correct and i should rewrite it.
Correct me if I'm wrong.

**Comment by evgen-povt** [comment]
@gluk256 @gballet could you please approve the PR?

**Comment by gballet** [comment]
@evgen-povt  we won't merge until we have an agreement with @b00ris about #15811

**Comment by b00ris** [comment]
Bloom filters broke the partial topic filtering for whisperv6. 

```
func TestMatching(t *testing.T) {
	btFull := []byte("test")
	btShort := []byte("tes")
	topicFull := BytesToTopic(btFull)
	topicShort := BytesToTopic(btShort)

	blFull := TopicToBloom(topicFull)
	blShort := TopicToBloom(topicShort)

	aggregate := make([]byte, BloomFilterSize)
	aggregate = addBloom(aggregate, blShort)

	t.Log(BloomFilterMatch(aggregate, blFull))
}
```

So, `matchSingleTopic` is not used in whisperv6. I think it could be removed.

But the fix could be applied for whisperv5.
The check
`if len(bt) < TopicLength {
	return false
}`
don't allow matching to empty filter topic. If we remove this check then filter which has empty topic have to decrypt every whisper envelop. But we can change it to `len(bt) != 0`


CC @gballet @evgen-povt @gluk256

**Comment by b00ris** [comment]
@evgen-povt Thanks! Looks good to me.

**Pull request merged**
