### PR TITLE
Improvement: fix padding alignment to optimize memory usage

### PR DESCRIPTION
**Pull request by kehiy**
I changed order and padding alignment of some struct to optimize memory usage.

### CODE REVIEW

**Comment by kehiy** [comment]
@fjl @holiman can you have a review?

**Comment by fjl** [comment]
Please note: We are not happy to receive project-wide refactoring/cleanup PRs, because they can mess with in-progress work.

Regarding this change specifically, since it is a performance oriented thing, it needa to be backed up by numbers. There are also aot of structs in go-ethereum where the field order is dictated by serialization. So changes to field order need to be considered on a case-by-case basis.

**Comment by kehiy** [comment]
@fjl so, should we close it?

**Comment by fjl** [comment]
I wasn't trying to say the PR should be closed, just that it needs more justification and a narrower scope.

**Pull request closed without merging**
