### PR TITLE
accounts/abi/bind: fix duplicate field names in the generated go struct

### PR DESCRIPTION
**Pull request by lwhile**
This pr fixes the problem of duplicate field names in go struct generated by `abigen`. The fix is to add numbers after the duplicate field names.

Related issue: #24627

### CODE REVIEW

**Comment by rjl493456442** [comment]
@lwhile I have pushed one more commit on top, with a few more fixes and tests.

**Comment by rjl493456442** [comment]
@MariusVanDerWijden please take a look.

**Comment by lwhile** [comment]
@rjl493456442 Thanks for the optimization.  I have pushed one commit to fix CI failure.

```
build/cache/golangci-lint-1.45.2-linux-amd64.tar.gz is stale
downloading from https://github.com/golangci/golangci-lint/releases/download/v1.45.2/golangci-lint-1.45.2-linux-amd64.tar.gz
10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
>>> build/cache/golangci-lint-1.45.2-linux-amd64/golangci-lint run --config .golangci.yml ./...
accounts/abi/type.go:262:6: `overloadedArgName` is unused (deadcode)
func overloadedArgName(rawName string, names map[string]string) (string, error) {
     ^
util.go:47: exit status 1
exit status 1
Command exited with code 1
Build failed
```

**Review by MariusVanDerWijden — APPROVED** [review]
LGTM

**Pull request merged**
