### PR TITLE
typo error: keccack256 -> keccak256

### PR DESCRIPTION
**Pull request by LuozhuZhang**

### CODE REVIEW

**Review by jwasinger — CHANGES_REQUESTED** [review]
there's also two instances of `keccack` in `internal/ethapi/api.go`.  maybe wise to correct those in this PR as well.

**Comment by LuozhuZhang** [comment]
> keccack

Hi

I don't seem to have seen the usage of Keccack, you can refer to [Wikipedia](https://en.wikipedia.org/wiki/SHA-3)

I think it might be a typo. The [method name](https://github.com/ethereum/go-ethereum/blob/594e32166269eed4f5cb8270bba99fa234a41606/internal/ethapi/api.go#L679) is Keccak256, and [the annotation](https://github.com/ethereum/go-ethereum/blob/594e32166269eed4f5cb8270bba99fa234a41606/internal/ethapi/api.go#L537) is also

I've marked other typos [here](https://github.com/ethereum/go-ethereum/blob/594e32166269eed4f5cb8270bba99fa234a41606/internal/ethapi/api.go#L508) and [here](https://github.com/ethereum/go-ethereum/blob/594e32166269eed4f5cb8270bba99fa234a41606/internal/ethapi/api.go#L1744)

**Comment by LuozhuZhang** [comment]
> there's also two instances of `keccack` in `internal/ethapi/api.go`. maybe wise to correct those in this PR as well.

Fix the bug, submit a new pr, pls review [it](https://github.com/ethereum/go-ethereum/pull/25056) ~

**Review by LuozhuZhang — COMMENTED** [review]
refer to [this pr](https://github.com/ethereum/go-ethereum/pull/25056)

**Review by s1na — APPROVED** [review]
LGTM

**Pull request merged**
