### PR TITLE
eth, les: add error when accessing missing block state

### PR DESCRIPTION
**Pull request by holiman**
Supersedes https://github.com/ethereum/go-ethereum/pull/15762 . It was not properly goimport-formatted, so I fixed that and refactored it a bit more. Thanks @shbli for the PR! 

---------------------------

For release notes:

This change makes getBalance, getCode, getStorageAt, getProof, call, getTransactionCount return an error if the block number in the request doesn't exist. getHeaderByNumber still returns `null` for missing headers.

### CODE REVIEW

**Comment by karalabe** [comment]
This might break the RPC APIs. I did a similar refactor a while back and it borked a lot of higher level client libraries which relied on missing blocks returning `null`.

**Comment by ryanschneider** [comment]
BTW, there is more recent discussion at https://github.com/ethereum/go-ethereum/issues/18254 since #3483 had been marked deprecated.

@karalabe do you remember which client libraries were impacted?  We could look at them and see if a) they still make that assumption and b) any work-arounds that could be implemented.

Ideally we can come up with a clever way forward that allows for an explicit error without breaking these clients too badly.

**Comment by xiaods** [comment]
cloud you please add testing to stub the case. the project missing many testing , please don't miss it anymore.

**Comment by xiaods** [comment]
any update? i don't clear howto in process doing on this patch?

**Comment by fjl** [comment]
This impacts: getBalance, getCode, getStorageAt, getProof, call, getTransactionCount.

**Comment by holiman** [comment]
done, ptal @fjl

**Comment by holiman** [comment]
ping @fjl  to add tests to this one, and merge it in

**Comment by fjl** [comment]
rebased and tests added

**Pull request merged**
