### PR TITLE
im newbie. how work go-etherfact for ubuntu 

### PR DESCRIPTION
**Pull request by mdikmetas**
im newbie. how work go-etherfact for ubuntu 

help me pleaqse

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 86c61cdfa423483682da89f6478030670e5edc98
  * Commits must be prefixed with the package(s) they modify

 * Commit: dbf98d00f511968b643b085ac75fd1ca87b63081
  * Commits must be prefixed with the package(s) they modify

 * Commit: 18ca4522dad4cb893add7de919854c66c7adc528
  * Commits must be prefixed with the package(s) they modify

 * Commit: d69cfcc84e579d777aefa4b1f1bdcd91a893c5b1
  * Commits must be prefixed with the package(s) they modify

 * Commit: 654475de02eed45ab68aafae54ad9b776154c83c
  * Commits must be prefixed with the package(s) they modify

 * Commit: 3bd777e2a5f92addf52b3e671107b0759f55291e
  * Commits must be prefixed with the package(s) they modify

 * Commit: 12a5c130b11ba914edc9defe88ebb962e9b57fb3
  * Commits must be prefixed with the package(s) they modify

 * Commit: c960f5627a693eb9724e5250ba589fb1ce4782ac
  * Commits must be prefixed with the package(s) they modify

 * Commit: 1eaef29346ac581d34e30491cb06c42439fa0c29
  * Commits must be prefixed with the package(s) they modify

 * Commit: 857815d766db50a6e8899537afcba014b22acffa
  * Commits must be prefixed with the package(s) they modify

 * Commit: 3a4cbfdd0a7815d5bfdf13866a377144b23e1368
  * Commits must be prefixed with the package(s) they modify

 * Commit: 612b08dd34a89914ccfa466b7633a0b63c8ef902
  * Commits must be prefixed with the package(s) they modify

 * Commit: edf2b7f420fddd5f663e7c48eb96c5d8829d1c67
  * Commits must be prefixed with the package(s) they modify

 * Commit: 573d4f9a5d3f550e36794c39cb36f12f37827e2c
  * Commits must be prefixed with the package(s) they modify

 * Commit: 00aa98f4da0d3f68739e6c1a847a5f958299edd6
  * Commits must be prefixed with the package(s) they modify

 * Commit: c4a6356b62fa8985cdfa6ee0a3806768398079d7
  * Commits must be prefixed with the package(s) they modify

 * Commit: 7a44b4f0a82c1a636357524f868b77c8eb098fae
  * Commits must be prefixed with the package(s) they modify

 * Commit: 38aea9976063cd6d57f72f00398499903e3981ea
  * Commits must be prefixed with the package(s) they modify

 * Commit: d43f633690b69606b68da156234a21c0e8cab3f7
  * Commits must be prefixed with the package(s) they modify

 * Commit: 409f78d4789b80aa4ba1a5425a51b1ec36656c1b
  * Commits must be prefixed with the package(s) they modify

 * Commit: cf00b55babab36e38352694e7a7739c82f693a3e
  * Commits must be prefixed with the package(s) they modify

 * Commit: d949afdfab39b547acb3bcc1cce2f6685d1295e8
  * Commits must be prefixed with the package(s) they modify

 * Commit: e0c98f82dc9f1383c2651248c49abdf7d90305d4
  * Commits must be prefixed with the package(s) they modify

 * Commit: 92b6568e37488a2bc768c65f4bc64fedddb43501
  * Commits must be prefixed with the package(s) they modify

 * Commit: bf7e5b53704cbbd2b12afc72e3a7e54835c16f5c
  * Commits must be prefixed with the package(s) they modify

 * Commit: 08cb8358393869050db1f7213728ddf5a1b750ac
  * Commits must be prefixed with the package(s) they modify

 * Commit: 04d907fd1b0e9f66713844cd82a66f7c6072707f
  * Commits must be prefixed with the package(s) they modify

 * Commit: ad3445b6657256948b3478c9cc5d9d4edf246ee5
  * Commits must be prefixed with the package(s) they modify

 * Commit: 40dae5a76197076bd65e2a8badd75deb6e260ae0
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 86c61cdfa423483682da89f6478030670e5edc98
  * Commits must be prefixed with the package(s) they modify

 * Commit: dbf98d00f511968b643b085ac75fd1ca87b63081
  * Commits must be prefixed with the package(s) they modify

 * Commit: 18ca4522dad4cb893add7de919854c66c7adc528
  * Commits must be prefixed with the package(s) they modify

 * Commit: d69cfcc84e579d777aefa4b1f1bdcd91a893c5b1
  * Commits must be prefixed with the package(s) they modify

 * Commit: 654475de02eed45ab68aafae54ad9b776154c83c
  * Commits must be prefixed with the package(s) they modify

 * Commit: 3bd777e2a5f92addf52b3e671107b0759f55291e
  * Commits must be prefixed with the package(s) they modify

 * Commit: 12a5c130b11ba914edc9defe88ebb962e9b57fb3
  * Commits must be prefixed with the package(s) they modify

 * Commit: c960f5627a693eb9724e5250ba589fb1ce4782ac
  * Commits must be prefixed with the package(s) they modify

 * Commit: 1eaef29346ac581d34e30491cb06c42439fa0c29
  * Commits must be prefixed with the package(s) they modify

 * Commit: 857815d766db50a6e8899537afcba014b22acffa
  * Commits must be prefixed with the package(s) they modify

 * Commit: 3a4cbfdd0a7815d5bfdf13866a377144b23e1368
  * Commits must be prefixed with the package(s) they modify

 * Commit: 612b08dd34a89914ccfa466b7633a0b63c8ef902
  * Commits must be prefixed with the package(s) they modify

 * Commit: edf2b7f420fddd5f663e7c48eb96c5d8829d1c67
  * Commits must be prefixed with the package(s) they modify

 * Commit: 573d4f9a5d3f550e36794c39cb36f12f37827e2c
  * Commits must be prefixed with the package(s) they modify

 * Commit: 00aa98f4da0d3f68739e6c1a847a5f958299edd6
  * Commits must be prefixed with the package(s) they modify

 * Commit: c4a6356b62fa8985cdfa6ee0a3806768398079d7
  * Commits must be prefixed with the package(s) they modify

 * Commit: 7a44b4f0a82c1a636357524f868b77c8eb098fae
  * Commits must be prefixed with the package(s) they modify

 * Commit: 38aea9976063cd6d57f72f00398499903e3981ea
  * Commits must be prefixed with the package(s) they modify

 * Commit: d43f633690b69606b68da156234a21c0e8cab3f7
  * Commits must be prefixed with the package(s) they modify

 * Commit: 409f78d4789b80aa4ba1a5425a51b1ec36656c1b
  * Commits must be prefixed with the package(s) they modify

 * Commit: cf00b55babab36e38352694e7a7739c82f693a3e
  * Commits must be prefixed with the package(s) they modify

 * Commit: d949afdfab39b547acb3bcc1cce2f6685d1295e8
  * Commits must be prefixed with the package(s) they modify

 * Commit: e0c98f82dc9f1383c2651248c49abdf7d90305d4
  * Commits must be prefixed with the package(s) they modify

 * Commit: 92b6568e37488a2bc768c65f4bc64fedddb43501
  * Commits must be prefixed with the package(s) they modify

 * Commit: bf7e5b53704cbbd2b12afc72e3a7e54835c16f5c
  * Commits must be prefixed with the package(s) they modify

 * Commit: 08cb8358393869050db1f7213728ddf5a1b750ac
  * Commits must be prefixed with the package(s) they modify

 * Commit: 04d907fd1b0e9f66713844cd82a66f7c6072707f
  * Commits must be prefixed with the package(s) they modify

 * Commit: ad3445b6657256948b3478c9cc5d9d4edf246ee5
  * Commits must be prefixed with the package(s) they modify

 * Commit: 40dae5a76197076bd65e2a8badd75deb6e260ae0
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 86c61cdfa423483682da89f6478030670e5edc98
  * Commits must be prefixed with the package(s) they modify

 * Commit: dbf98d00f511968b643b085ac75fd1ca87b63081
  * Commits must be prefixed with the package(s) they modify

 * Commit: 18ca4522dad4cb893add7de919854c66c7adc528
  * Commits must be prefixed with the package(s) they modify

 * Commit: d69cfcc84e579d777aefa4b1f1bdcd91a893c5b1
  * Commits must be prefixed with the package(s) they modify

 * Commit: 654475de02eed45ab68aafae54ad9b776154c83c
  * Commits must be prefixed with the package(s) they modify

 * Commit: 3bd777e2a5f92addf52b3e671107b0759f55291e
  * Commits must be prefixed with the package(s) they modify

 * Commit: 12a5c130b11ba914edc9defe88ebb962e9b57fb3
  * Commits must be prefixed with the package(s) they modify

 * Commit: c960f5627a693eb9724e5250ba589fb1ce4782ac
  * Commits must be prefixed with the package(s) they modify

 * Commit: 1eaef29346ac581d34e30491cb06c42439fa0c29
  * Commits must be prefixed with the package(s) they modify

 * Commit: 857815d766db50a6e8899537afcba014b22acffa
  * Commits must be prefixed with the package(s) they modify

 * Commit: 3a4cbfdd0a7815d5bfdf13866a377144b23e1368
  * Commits must be prefixed with the package(s) they modify

 * Commit: 612b08dd34a89914ccfa466b7633a0b63c8ef902
  * Commits must be prefixed with the package(s) they modify

 * Commit: edf2b7f420fddd5f663e7c48eb96c5d8829d1c67
  * Commits must be prefixed with the package(s) they modify

 * Commit: 573d4f9a5d3f550e36794c39cb36f12f37827e2c
  * Commits must be prefixed with the package(s) they modify

 * Commit: 00aa98f4da0d3f68739e6c1a847a5f958299edd6
  * Commits must be prefixed with the package(s) they modify

 * Commit: c4a6356b62fa8985cdfa6ee0a3806768398079d7
  * Commits must be prefixed with the package(s) they modify

 * Commit: 7a44b4f0a82c1a636357524f868b77c8eb098fae
  * Commits must be prefixed with the package(s) they modify

 * Commit: 38aea9976063cd6d57f72f00398499903e3981ea
  * Commits must be prefixed with the package(s) they modify

 * Commit: d43f633690b69606b68da156234a21c0e8cab3f7
  * Commits must be prefixed with the package(s) they modify

 * Commit: 409f78d4789b80aa4ba1a5425a51b1ec36656c1b
  * Commits must be prefixed with the package(s) they modify

 * Commit: cf00b55babab36e38352694e7a7739c82f693a3e
  * Commits must be prefixed with the package(s) they modify

 * Commit: d949afdfab39b547acb3bcc1cce2f6685d1295e8
  * Commits must be prefixed with the package(s) they modify

 * Commit: e0c98f82dc9f1383c2651248c49abdf7d90305d4
  * Commits must be prefixed with the package(s) they modify

 * Commit: 92b6568e37488a2bc768c65f4bc64fedddb43501
  * Commits must be prefixed with the package(s) they modify

 * Commit: bf7e5b53704cbbd2b12afc72e3a7e54835c16f5c
  * Commits must be prefixed with the package(s) they modify

 * Commit: 08cb8358393869050db1f7213728ddf5a1b750ac
  * Commits must be prefixed with the package(s) they modify

 * Commit: 04d907fd1b0e9f66713844cd82a66f7c6072707f
  * Commits must be prefixed with the package(s) they modify

 * Commit: ad3445b6657256948b3478c9cc5d9d4edf246ee5
  * Commits must be prefixed with the package(s) they modify

 * Commit: 40dae5a76197076bd65e2a8badd75deb6e260ae0
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by etherfact** [comment]
pls contact me
i will support you 🗡

**Pull request closed without merging**
