### PR TITLE
eth/downloader: remove header rollback mechanism

### PR DESCRIPTION
**Pull request by rjl493456442**
This pull request removes the rollback mechanism in downloader. 

Originally, this mechanism is tailored for Proof-of-Work consensus engine, which does PoW verification randomly. Therefore, whenever sync process exits abnormally, a part of tip headers will be removed for safety consideration.

In terms of Proof-of-Stake(also for Proof-of-Authority), each header is verified one by one, there is no reason to rewind the written headers which are certainly valid.

And another big reason for removing this additional mechanism is: inside of Rollback, the genesis state may be committed. It results in a weird scenario that persistent state is both modified by the Rollback function and also the state syncer. The concurrent state write will result in a corrupted state eventually, should be avoided in the first place.

### CODE REVIEW

**Comment by rjl493456442** [comment]
Deployed on both 7/8, let's see what happpens

**Comment by rjl493456442** [comment]
Both 07 and 08 can finish snap sync correctly.

https://my.papertrailapp.com/systems/13274397401/events?focus=1640527569457709063&selected=1640527569457709063

https://my.papertrailapp.com/systems/13274397641/events?focus=1640531858481680386&selected=1640531858481680386

**Review by karalabe — APPROVED** [review]
SGTM

**Comment by fjl** [comment]
Need to delete the tests as well.

**Pull request merged**
