### PR TITLE
les: add trailing slash to metric namespace

### PR DESCRIPTION
**Pull request by holiman**
This _might_ solve https://github.com/ethereum/go-ethereum/issues/22458

### CODE REVIEW

**Comment by karalabe** [comment]
Please replace the `.` too with a `/`.

**Comment by karalabe** [comment]
Or can't we just avoid a `.` in the name altogether. This is a folder at the end of the day, why put a `.` in it?

**Comment by holiman** [comment]
Yeah let's just omit the `.`

**Review by rjl493456442 — APPROVED** [review]
lgtm.

It's ok to rename the database folder. But should we also consider wiping the legacy les folders? e.g. `les.client  lespay`.

**Comment by rjl493456442** [comment]
Oh sorry, only the metric name is changed. Then it's totally fine for me.

**Pull request merged**
