### PR TITLE
go.mod: update github.com/golang/snappy for encode_arm64 fix

### PR DESCRIPTION
**Pull request by ucwong**
https://github.com/golang/snappy/pull/56

### CODE REVIEW

**Comment by holiman** [comment]
Good catch, thanks for notifying us about it!

**Comment by karalabe** [comment]
This fix will only be needed for Go 1.16, should we merge it now, given that it had 13 hours of existence to back it?

**Comment by holiman** [comment]
Minimal change: 
```git diff
--- a/go.mod
+++ b/go.mod
@@ -27,7 +27,7 @@ require (
        github.com/go-sourcemap/sourcemap v2.1.2+incompatible // indirect
        github.com/go-stack/stack v1.8.0
        github.com/golang/protobuf v1.4.2
-       github.com/golang/snappy v0.0.2-0.20200707131729-196ae77b8a26
+       github.com/golang/snappy v0.0.3-0.20201103224600-674baa8c7fc3
        github.com/google/gofuzz v1.1.1-0.20200604201612-c04b05f3adfa
        github.com/gorilla/websocket v1.4.1-0.20190629185528-ae1634f6a989
        github.com/graph-gophers/graphql-go v0.0.0-20191115155744-f33e81362277
diff --git a/go.sum b/go.sum
index dedae7bc7a..2c5b164d95 100644
--- a/go.sum
```

**Comment by fjl** [comment]
@ucwong I merged https://github.com/ethereum/go-ethereum/pull/21934 instead because
it didn't mess with go.mod so much. Thanks again for the reminder to update this library.

**Pull request closed without merging**
