### PR TITLE
Update common test files

### PR DESCRIPTION
**Pull request by Gustav-Simonsson**
Confirms Go is correct in EC recover precompiled in terms of cpp and python bugs:
* https://github.com/ethereum/libethereum/pull/91

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Wed Nov 18 14:15:23 UTC 2015_

**Comment by obscuren** [comment]
Hmm, why did our coverage drop with this change?

**Comment by Gustav-Simonsson** [comment]
@obscuren hmm, this only changed the JSON files - so codecov must be including them in it's estimate.

**Comment by obscuren** [comment]
@Gustav-Simonsson but perhaps the json tests test less now?

**Pull request merged**
