### PR TITLE
miner: remove some block accessor method calls

### PR DESCRIPTION
**Pull request by lxex**

### CODE REVIEW

**Review by rjl493456442 — APPROVED** [review]
LGTM

**Review by MariusVanDerWijden — APPROVED** [review]
Generally LGTM
It's not a big improvement, since both `block.NumberU64()` and `block.Hash()` are cached anyway.
Only `block.Number()` creates a new big.Int.
Since the Blocknumber is copied anyway in L632, the other receipts don't share the same underlying big.Int so the code is valid.
But I think it's a valid readability improvement

**Comment by karalabe** [comment]
> Since the Blocknumber is copied anyway in L632, the other receipts don't share the same underlying big.Int so the code is valid.

@MariusVanDerWijden Whadayamean? The `BlockNumber` field is a pointer. The copy you refer to just copies the pointer value. All versions will still be pointing to the exact same data.

**Comment by MariusVanDerWijden** [comment]
> @MariusVanDerWijden Whadayamean? The `BlockNumber` field is a pointer. The copy you refer to just copies the pointer value. All versions will still be pointing to the exact same data.

Yeah that should be, however I did a small test where I changed the field in one of the receipts and it didn't change the other.
Ah I guess I only changed the pointer not the underlying data.
So this PR might break something after all, right?

**Comment by karalabe** [comment]
https://play.golang.org/p/NlcFuFwJuLQ

Well, although I don't expect it to break things, I think it's good practice to not share the same backing memory for independent stuff.

**Comment by lxex** [comment]
> Generally LGTM
> It's not a big improvement, since both `block.NumberU64()` and `block.Hash()` are cached anyway.
> Only `block.Number()` creates a new big.Int.
> Since the Blocknumber is copied anyway in L632, the other receipts don't share the same underlying big.Int so the code is valid.
> But I think it's a valid readability improvement

`WriteReceipts`  will encode all the field to bytes and write to db. Therefore, change one receipt obviously do not affect other receipts.

> https://play.golang.org/p/NlcFuFwJuLQ
> 
> Well, although I don't expect it to break things, I think it's good practice to not share the same backing memory for independent stuff.

Although receipt  is independent, but this is in independent thread, as the block capacity increases, it seems not necessary to open up memory here
otherwise,  this field should not a pointer  type.

**Comment by holiman** [comment]
Thanks for the PR. We've decided to not apply this change, since it adds more code but does not meaningfully improve the speed or the clarity what is happening.

**Pull request closed without merging**
