### PR TITLE
core: add unit tests for code with no coverage

### PR DESCRIPTION
**Pull request by Gustav-Simonsson**
Will gather some more unit tests here. Can be open for a bit in lieu of merging the other core (refactor) PRs.

- [x] ```ChainManager Export```

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Tue Sep 15 17:05:28 UTC 2015_

**Comment by tgerring** [comment]
Needs a rebase but did slightly increase coverage from 62.4 to 63.5% :+1:

**Comment by obscuren** [comment]
@Gustav-Simonsson are you going to pick up this PR?

**Comment by fjl** [comment]
@Gustav-Simonsson ping

**Comment by obscuren** [comment]
@Gustav-Simonsson !!!

**Comment by tgerring** [comment]
Is this still relevant post core refactor?

**Comment by karalabe** [comment]
Considered abandoned. Please reopen if you wish to pick it up again.

**Pull request closed without merging**
