### PR TITLE
deps: update influxdb

### PR DESCRIPTION
**Pull request by holiman**
While investigating https://github.com/ethereum/go-ethereum/pull/26926 , to see what it is that pulls in `golang.org/x/net@0.4.0`, I noticed that out influx dependency is very old, at `v1.8.3` when the latest is `v1.11.0`. 

Updates since

- https://github.com/influxdata/influxdb/releases/tag/v1.8.4
- https://github.com/influxdata/influxdb/releases/tag/v1.8.5rc0
- https://github.com/influxdata/influxdb/releases/tag/v1.8.6
- https://github.com/influxdata/influxdb/releases/tag/v1.8.7
- https://github.com/influxdata/influxdb/releases/tag/v1.8.9
- https://github.com/influxdata/influxdb/releases/tag/v1.8.10

It just continues. There's a lot of fixes. After a while, they stopped making big 'releases', and just did the "tag and done", e.g. v1.10.0 release: https://github.com/influxdata/influxdb/releases/tag/v1.10.0 and 11: https://github.com/influxdata/influxdb/releases/tag/v1.11.0 

And no, this PR still does not update `golang.org./x/net`

### CODE REVIEW

**Comment by karalabe** [comment]
Seems our old dependency pulled in the entire influxdb repo because back then the client was embedded inside. Since then the client is it's separate project and we should switch over to depending on that only. 

To make things more fun however, this is the client for Influx 2 (and maybe 1.8 and above) https://github.com/influxdata/influxdb-client-go and this is for below that https://github.com/influxdata/influxdb1-client

I'm unsure which we would need to use honestly. Nor whether we should use both and somehow dynamically switch (based on what?). It might also screw up the flags if authentication changes.

**Comment by holiman** [comment]
Ha, 
- `github.com/influxdata/influxdb1-client/v2` -- this is for Influx v1
- `github.com/influxdata/influxdb-client-go` -- this is for Influx v2

**Comment by holiman** [comment]
I'll close this and try a different attempt

**Comment by donatocayurin** [comment]
Thank you ❤️🙏

**Comment by donatocayurin** [comment]
❤️🙏

**Pull request closed without merging**
