### PR TITLE
p2p/discover: improve nodesByDistance.push

### PR DESCRIPTION
**Pull request by zhiqiangxu**
Spotted this days ago, today I was writing something similar and I decide to create a PR for this.

It just doesn't feel right to check `ix == len(h.entries)` after possibly appending an additional entry to `h.entries`.

@fjl correct me if there's something missed out:)

### CODE REVIEW

**Comment by fjl** [comment]
I don't get it. Is there a bug in the current version?

**Comment by zhiqiangxu** [comment]
> I don't get it. Is there a bug in the current version?

No bug here, but I think the comment is not accurate, multiple cases are coerced into one.

**Comment by holiman** [comment]
I think the change is harder to understand than before the change.

**Comment by zhiqiangxu** [comment]
> I think the change is harder to understand than before the change.

`sort.Search(N, )` will at most return `N` when no match, so `ix` should compare with `N`, not `N+1`. The current version sometimes compare `ix` with `N+1`. But in the end, the final result is the same...

**Pull request merged**
