### PR TITLE
accounts: disable file system watch on linux/arm64

### LINKED ISSUE #2488: Geth 1.4 will not start on ARM 64 (AArch64)
#### System information

Geth version: 

(compiled from source)
Geth
Version: 1.4.0-rc
Git Commit: 8241fa522772837f0d05511f20caa6da1d5a3209
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.6.2
OS: linux
GOPATH=
GOROOT=/usr/lib/go

(downloaded binary)
Geth
Version: 1.4.0-rc
Git Commit: 8241fa522772837f0d05511f20caa6da1d5a3209
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.6.1
OS: linux
GOPATH=
GOROOT=/usr/local/go

OS & Version: Linux - Arch Linux Arm on Odroid C2 (AArch64)

#### Expected behaviour

geth starts successfully

#### Actual behaviour

geth does not start successfully

#### Steps to reproduce the behaviour

try to start geth from command line

#### Error

```
$ geth
I0424 16:12:07.718054 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to /home/xxx/.ethereum/chaindata
I0424 16:12:08.134728 ethdb/database.go:169] closed db:/home/xxx/.ethereum/chaindata
I0424 16:12:08.138212 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to /home/xxx/.ethereum/chaindata
panic: notify: epoll_wait(2) error function not implemented

goroutine 66 [running]:
panic(0xc1e2c0, 0x48205d8010)
	/usr/lib/go/src/runtime/panic.go:481 +0x384
github.com/rjeczalik/notify.(*inotify).loop(0x48200b0000, 0x4820092120)
	/home/xxx/build/geth-git/src/geth-git/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/rjeczalik/notify/watcher_inotify.go:215 +0x568
created by github.com/rjeczalik/notify.(*inotify).lazyinit
	/home/xxx/build/geth-git/src/geth-git/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/rjeczalik/notify/watcher_inotify.go:133 +0x210
```

Geth worked fine as of version 1.3.6. Upgrade to 1.4 introduced inability to start.

### PR DESCRIPTION
**Pull request by fjl**
Fixes #2488

@obscuren PTAL
@eramseth please try

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Mon Apr 25 11:31:36 UTC 2016_

**Comment by karalabe** [comment]
I think we should disable for `android` rather than the entire `arm64`. It's a limitation of the mobile platform I believe, I wouldn't like to cripple the entire ARM64 Linux platform for it.

**Comment by karalabe** [comment]
Of course I may be wrong. Please enlighten me otherwise.

**Comment by fjl** [comment]
@karalabe see the linked issue

**Comment by fjl** [comment]
@karalabe see the linked issue. android is already disabled AFAIK.

**Comment by karalabe** [comment]
I still don't see how this is an arm64 bit issue.

**Comment by karalabe** [comment]
Ok https://go-review.googlesource.com/#/c/21971/

**Comment by fjl** [comment]
Cool, so can we merge this now?

**Pull request merged**
