### PR TITLE
[WIP] accounts/abi: Tag fields in structs

### PR DESCRIPTION
**Pull request by VoR0220**
This makes the code cleaner and more reusable by outside parties. I do however appear to be running into some problems wrt the decoder and am going to examine this more. 

This will be something of a breaking change. So please, if anyone has any objections to this, let me know now before I keep working on it. 

Signed-off-by: RJ Catalano <catalanor0220@gmail.com>

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 084b2093299dcddd1971e584be74528cdc580650
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by karalabe** [comment]
I don't see how this would work. The abi is just a flat list of items (methods, fields, events), that the existing code splits up into maps keyed by the entity names. Converting everything to json tags would mean the ABI representation itself would need to be changed.

**Comment by fjl** [comment]
We can't easily change ABI JSON format and changing it to objects is pointless because the existing format works.

**Comment by VoR0220** [comment]
got it. Will close.

**Pull request closed without merging**
