### PR TITLE
Use highest UsedGas possible in eth_estimateGas

### LINKED ISSUE #21746: eth_estimateGas fails to estimate create2 and others internal calls that does not revert on fail
When trying to use ERC-2470, the eth_estimateGas is not giving enough gas for the create2 call succeed. 

Test on ropsten: https://ropsten.etherscan.io/address/0xce0042B868300000d44A59004Da54A005ffdcf9f

See [discussion on ERC-2470](https://ethereum-magicians.org/t/erc-2470-singleton-factory/3933/37?u=3esmit)

This also happens on MulitisigWallet executeTransaction, because this wallet does not revert when the internal call fails, instead it send an event with this result, see https://github.com/gnosis/MultiSigWallet/blob/develop/contracts/MultiSigWallet.sol#L230-L239, so the estimate always fail when this transaction more than minimal gas. 

The estimateGas should start with the maximum gas (blockGasLimit) and return the usedGas of the simulated call, instead of starting from the less gas possible. Whenever a transaction can use more gas, this is the intended way to be called, not the opposite.

### PR DESCRIPTION
**Pull request by 3esmit**
Fixes #21746

This change will make use of the highest "result.UsedGas" coming from DoCall, this is important for calls that can have different outcomes depending on gas limit of the transaction, for example, contracts that do internal calls but do not revert when this internal call fails. 

When someone is doing a estimate on gas, obviously, they likely want the outcome where no internal transactions failed. 

This change will improve the estimation of gas.

I wonder if this binary search of hi/low gas is necessary at all, IMO a DoCall with latest block gas limit could just grab the UsedGas and return that instead of this binary search, this would improve the speed that a transaction can be estimated. After merging this change I can open another PR changing this as well.

### CODE REVIEW

**Comment by karalabe** [comment]
The amount of gas used is not the same as the amount of gas needed unfortunately. For example when you make a CALL, 1/64th of the gas is forwarded as a stipend. So you actually need 21000*65/64 gas to make a contract do a plain value transfer, even though only 21000 will be used and the 21000/64 stipend will be returned. That's the reason really to use binary search, because the gas schedule of the EVM is way too complicated.

Contracts that don't revert when an internal call fails mean they don't care if the internal call failed or not, so that should be fine. This is a known limitation of the algorithm and a known requirement, that  you can only properly estimate calls where the outer contract/transaction is willing to fail the call if something bad goes on internally.

**Comment by 3esmit** [comment]
With this change, calls that previously estimated wrong are now estimating correctly. I can do more tests with other scenarios, however this change is improving the current estimation.

> Contracts that don't revert when an internal call fails mean they don't care if the internal call failed or not

I am looking forwards the UX that makes sense. What is the use case where a user wants a estimation that causes internal calls to fail out-of-gas?

**Comment by karalabe** [comment]
Things get very murky if you go down the path of reacting to internal failures. E.g. what happens if an internal call will always fail? Should we deny running the transactions altogether? IMHO it's up to the outer transaction / contract developer to handle any errors it wants, and if there's no error from the outer call's perspective, then I don't see why we'd push upwards instead of down.

**Comment by 3esmit** [comment]
This is abstracted out by the block gas limit. If a transaction always fail, it will never be able to increase the gas:
> what happens if an internal call will always fail? 

The problem would be for infinite loops, or whatever function that always use all remaining gas and fail, such as assert "false". I'll create some contracts that do this condition to see how to detect this scenarios. 

Do you think that these scenarios are common in contracts users interact? 
Would be possible for DoEstimate analyze the use of internal calls and if they failed, to properly give the best estimate and warn user that an internal call would fail?

**Comment by 3esmit** [comment]
I will close this PR as it needs a different approach to fix #21746. I will look forwards a solution on returning internal transactions errors on DoCall, that can be forwarded to wallet UI. Once that's ready I'll submit another PR.

**Pull request closed without merging**
