### PR TITLE
rpc: use go-winio instead of vendoring a named pipe implementation

### PR DESCRIPTION
**Pull request by fjl**
It's probably better to use a library written by Microsoft rather than maintaining our own wrapper.
Maybe helps with #2177.

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Mon Apr 4 11:56:54 UTC 2016_

**Comment by karalabe** [comment]
LGTM :+1: 

Haven't tested it tbh, but I don't see many things that could fail in those 2 remaining lines of code :))

**Comment by fjl** [comment]
@bas-vk please also take a look

**Comment by bas-vk** [comment]
Did some testing and it seems stable :+1:

**Pull request merged**
