### PR TITLE
deps: update prometheus/prometheus/tsdb

### PR DESCRIPTION
**Pull request by willianpaixao**
Similar to #24751, `github.com/prometheus/tsdb` was moved to `github.com/prometheus/prometheus/tsdb` in [2019](https://github.com/prometheus/prometheus/pull/5805) and no updates on the original path are made since.

This PR simply replaces the path and bumps to the latest stable version.

### CODE REVIEW

**Comment by holiman** [comment]
The updates in this PR are a lot more than just prometheus.  I'll fix it up

**Comment by holiman** [comment]
Did a rebase (freezer had changed), but couldn't seem to get rid of the other dependency-changes.

**Review by holiman — APPROVED** [review]
LGTM

**Comment by willianpaixao** [comment]
@holiman could you please assign a reviewer?

**Comment by holiman** [comment]
We'll get to this -- it's not a high prio PR, since we only use a very small snippet of code from prometheus/tsdb.

**Comment by holiman** [comment]
rebased on master

**Comment by holiman** [comment]
Triage discussion: it really makes no sense to pull in the gigantic prometheus dependenciy for this one feature. We'll leave it be, and instead try to replace it with something standalone/small at some point in the future.

**Pull request closed without merging**
