### PR TITLE
core, miner: revert block gas counter in case of invalid transaction

### LINKED ISSUE #26791: in `worker.commitTransaction` should also revert the gas pool when err is not nil and the TX is not added to the state
https://github.com/ethereum/go-ethereum/blob/master/miner/worker.go#L863-L875

for example in this code the when `core.ApplyTransaction` returns an error the pool will be reduced where in fact the tx is not added to the state.

### PR DESCRIPTION
**Pull request by rjl493456442**
Fixes #26791

### CODE REVIEW

**Review by holiman — APPROVED** [review]
LGTM, but we need to peek around and see if there are any other places where we need to apply the same fix, I think

**Comment by rjl493456442** [comment]
These fields of environment will be mutated in commitTransaction
- gasPool
- stateDb
- header.GasUsed

For header.GasUsed, it will only be increased when transaction is successfully applied. So I think this fix is enough.

**Comment by holiman** [comment]
I meant like here: 
https://github.com/ethereum/go-ethereum/blob/master/cmd/evm/internal/t8ntool/execution.go#L186

**Comment by rjl493456442** [comment]
@holiman good points, I will fix them.

**Pull request merged**
