### PR TITLE
Update to reinstate logfile flag

### PR DESCRIPTION
**Pull request by Firescar96**
Fix log to stdout instead of stderr
Add a flag to toggle logging to temp files instead of stdout

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Fri Jun 3 21:09:26 UTC 2016_

**Comment by hermanjunge** [comment]
+1

**Comment by karalabe** [comment]
Why? :-1:

**Comment by karalabe** [comment]
Closing per the discussion in https://github.com/ethereum/go-ethereum/issues/2646

**Pull request closed without merging**
