### PR TITLE
core: added default genesis block

### PR DESCRIPTION
**Pull request by obscuren**
When a user runs a freshly setup geth w/o a database initialised the
default genesis block is decoded and inserted in to the database.

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Sat Aug 1 15:36:01 UTC 2015_

**Comment by fjl** [comment]
So where is the block?

**Comment by fjl** [comment]
OK, it is visible in raw view. Maybe add line breaks every 100 characters so editors don't freak out when opening the file.

**Comment by fjl** [comment]
Please add a newline between the license header and the package statement. Otherwise the license header shows up in godoc.

**Comment by obscuren** [comment]
> Maybe add line breaks every 100 characters so editors don't freak out when opening the file.

Pro-top: VIM :-P

**Comment by fjl** [comment]
> Pro-top: VIM :-P

I tested and it seems to open quickly with all editors I have access to.
Github doesn't display it properly though. It also breaks syntax
highlighting in some of the editors (emacs is fine :open_mouth:).

For your consideration, I am asking you to change it to something [like this](https://github.com/fjl/go-ethereum/blob/e5331edbfbdbee06df4d82dc02521ddaa6a2e5e6/core/default_genesis.go).
With emacs it takes 15 keystrokes to transform your version into this.
I am sure your favourite editor can do it with less than that.

**Comment by fjl** [comment]
Even if you don't want to wrap the data, please add the newline after the license header.

**Comment by obscuren** [comment]
You'll have to excuse me for not seeing your point for wrapping :-) I'll add the newline. I'll keep this in mind, thanks.

**Comment by fjl** [comment]
amazing, thanks. :+1:

**Comment by Gustav-Simonsson** [comment]
Will the genesis block string be LGPL licensed since it's in that file?

**Comment by obscuren** [comment]
@Gustav-Simonsson The genesis block isn't. The data is ;-)

**Comment by Gustav-Simonsson** [comment]
@obscuren Hah :P Fine with me, but since we're being diligent with licensing, should we maybe avoid LGPL licensing this encoding of it? @fjl what do you think?

**Comment by obscuren** [comment]
We could license it with MIT. Having it licensed at all serves us no real benefit

**Comment by tgerring** [comment]
Untested locally, but seems reasonable based on prior conversations :+1:

**Comment by fjl** [comment]
@Gustav-Simonsson we should not license this file separately. The block itself has no copyright or license. It is just a string constant. We are also not licensing integer constants
specially (e.g. the protocol params file).

**Comment by fjl** [comment]
@Gustav-Simonsson could phrase that even simpler: if you put a few digits of Pi in a file with a GPL header, it does not make Pi GPL-licensed.

**Pull request merged**
