### PR TITLE
common/math: rename variable name `int` to `in`

### PR DESCRIPTION
**Pull request by tianyeyouyou**
It's odd to use the keyword `int` as variable name, I think it's better to use `in`

### CODE REVIEW

**Comment by fjl** [comment]
`int` is not a keyword, it's just a built-in identifier, and can be shadowed.

**Comment by tianyeyouyou** [comment]
Ah, sorry for it.

But anyway, using built-in identifier `int` is odd too...

**Review by karalabe — CHANGES_REQUESTED** [review]
I could agree with replacing with with `n`, which is used across Go. But `in` seems arbitrary.

**Review by karalabe — APPROVED** [review]
LGTM

**Pull request merged**
