### PR TITLE
Integrate new ethash api

### PR DESCRIPTION
**Pull request by Gustav-Simonsson**
Do not merge!  Opened for travis builds & discussion.

Currently panics (see comment)

### CODE REVIEW

**Comment by Gustav-Simonsson** [comment]
@fjl @LefterisJP 
```go
19:28:51 ((detached from le/finalize_and_use_new_api)) ~/go/src/github.com/ethereum/ethash
> go test -v
=== RUN TestEthash
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x8 pc=0x405250]

runtime stack:
runtime.gothrow(0x6a47d0, 0x2a)
	/home/gs/golang/src/runtime/panic.go:503 +0x8e
runtime.sigpanic()
	/home/gs/golang/src/runtime/sigpanic_unix.go:14 +0x5e

goroutine 8 [syscall, locked to thread]:
runtime.cgocall_errno(0x405760, 0xc2080175b0, 0xc200000000)
	/home/gs/golang/src/runtime/cgocall.go:130 +0xf5 fp=0xc208017590 sp=0xc208017568
github.com/ethereum/ethash._Cfunc_ethash_full_compute(0xc208038c40, 0x0, 0xc2080175f0, 0x6bd4c249b84179ac, 0x0)
	/home/gs/go/src/github.com/ethereum/ethash/:36 +0x40 fp=0xc2080175b0 sp=0xc208017590
github.com/ethereum/ethash.(*Full).Search(0xc208010110, 0x7f32cd3fd098, 0xc20802e4e0, 0x0, 0x6bd4c249b84179ac, 0x0, 0x0, 0x0)
	/home/gs/go/src/github.com/ethereum/ethash/ethash.go:236 +0x3ef fp=0xc2080176e0 sp=0xc2080175b0
github.com/ethereum/ethash.TestEthash(0xc208076090)
	/home/gs/go/src/github.com/ethereum/ethash/ethash_test.go:31 +0x19b fp=0xc208017778 sp=0xc2080176e0
testing.tRunner(0xc208076090, 0x966580)
	/home/gs/golang/src/testing/testing.go:447 +0xbf fp=0xc2080177d0 sp=0xc208017778
runtime.goexit()
	/home/gs/golang/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080177d8 sp=0xc2080177d0
created by testing.RunTests
	/home/gs/golang/src/testing/testing.go:555 +0xa8b

goroutine 1 [chan receive]:
testing.RunTests(0x6bd990, 0x966580, 0x2, 0x2, 0xc20808df01)
	/home/gs/golang/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc20802c640, 0x98b2a0)
	/home/gs/golang/src/testing/testing.go:485 +0x6c
main.main()
	github.com/ethereum/ethash/_test/_testmain.go:54 +0x1d5

goroutine 5 [chan receive]:
github.com/ethereum/go-ethereum/logger/glog.(*loggingT).flushDaemon(0x983a40)
	/home/gs/go/src/github.com/ethereum/go-ethereum/logger/glog/glog.go:897 +0x78
created by github.com/ethereum/go-ethereum/logger/glog.init·1
	/home/gs/go/src/github.com/ethereum/go-ethereum/logger/glog/glog.go:428 +0x77

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/home/gs/golang/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [select]:
github.com/ethereum/go-ethereum/logger.dispatchLoop()
	/home/gs/go/src/github.com/ethereum/go-ethereum/logger/sys.go:65 +0x6d1
created by github.com/ethereum/go-ethereum/logger.init·1
	/home/gs/go/src/github.com/ethereum/go-ethereum/logger/sys.go:44 +0x25
exit status 2
FAIL	github.com/ethereum/ethash	0.028s

```

**Comment by LefterisJP** [comment]
You are also getting this when running `go test -v` in the ethash repository with the latest tip of the `finalize_and_use_new_api` branch?

**Comment by Gustav-Simonsson** [comment]
@LefterisJP Yes, I get this on commit
```
b60226e... makeDAG is also exported now due to system testing
```
with go1.4.2 linux/amd64

**Comment by Gustav-Simonsson** [comment]
@LefterisJP and I debugged it and found that it's due to ethash_full_new returning NULL for a variety of errors, including file IO errors. In this case it was due to the DAG file already existing with the wrong size (from previous experiments).

This adds a panic in ethash.go to fail earlier, if the full field is NULL: https://github.com/LefterisJP/ethash/pull/1

@LefterisJP will also look into improving file IO error handling in the C code

**Comment by fjl** [comment]
Would be nice if ethash provided an error code so we can print something.

**Comment by Gustav-Simonsson** [comment]
It now mines but on a new fresh private chain it gets nonce mismatch. Investigating.

**Comment by LefterisJP** [comment]
there is also something funny on your Windows Pull Request build.

https://build.ethdev.com/builders/Windows%20Go%20pull%20requests/builds/79/steps/install-geth/logs/stdio

Says can't find `sprintf_s()`

**Pull request closed without merging**
