### PR TITLE
feature(abigen): support parse transaction input bytes readable go struct in `abigen`

### PR DESCRIPTION
**Pull request by fenghaojiang**
feature: support parse transaction input bytes readable go struct `abigen`

It's easy to use `abigen` to generate code that help you parse the `event log` and call the payable method with the transactor.

But parsing the transaction call data is missing. You can only send a transaction with a transactor. This PR aims to generate codes that help developer parse transaction calldata.

`abigen` can generate code to parse the transaction call data.
example 
```go
package bin

import (
	"context"
	"fmt"
	"testing"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/ethclient"
)

func TestOnParse(t *testing.T) {
	cli, err := ethclient.Dial("https://rpc.ankr.com/polygon")
	if err != nil {
		t.Fatal(err)
	}

	collectTx, _, err := cli.TransactionByHash(context.Background(),
		common.HexToHash("0x741146cce64d873cfe82ade413651de355a6db92f992e5bfc4e1c58d92f5dd5b"))
	if err != nil {
		t.Fatal(err)
	}

	increaseLiquidityTx, _, err := cli.TransactionByHash(context.Background(),
		common.HexToHash("0x645ff650d7bfb9a74f573af474b9ebee48c3fadc7dac67257a8da6b55c71f338"))

	collectInfo, err := ParseCollect(collectTx.Data())
	if err != nil {
		t.Fatal(err)
	}

	increaseLiquidityInfo, err := ParseIncreaseLiquidity(increaseLiquidityTx.Data())
	if err != nil {
		t.Fatal(err)
	}

	fmt.Printf("%+v\n", collectInfo)
	fmt.Printf("%+v\n", increaseLiquidityInfo)
}
```

Method ParseRenew is generate by `abigen`.   

Here is the output of above codes: 
&{Param_params:{TokenId:+894123 Recipient:0x48B8e4ed457da9B64c33Ee50Fd5490614833A37D Amount0Max:+340282366920938463463374607431768211455 Amount1Max:+340282366920938463463374607431768211455}}
&{Param_params:{TokenId:+891904 Amount0Desired:+331092 Amount1Desired:+0 Amount0Min:+331092 Amount1Min:+0 Deadline:+1685112789}}

### CODE REVIEW

**Comment by s1na** [comment]
I'm working on a v2 of abigen #26782 and this feature is one of the building blocks.

**Comment by fenghaojiang** [comment]
> I'm working on a v2 of abigen #26782 and this feature is one of the building blocks.

Nice. Your code looks neat. Should I merge my commit into your branch? And what I should do next?

**Comment by fenghaojiang** [comment]
This PR is non-intrusive.

**Comment by fjl** [comment]
As discussed in Discord, we would prefer to ship abigen v2 (#26782) rather than adding more features into abigen v1.

**Pull request closed without merging**
