### PR TITLE
api/bind: Add CallOpts.BlockHash to allow calling contracts at a specific block hash

### PR DESCRIPTION
**Pull request by ajsutton**
Adds `BlockHash` to `CallOpts` so contract bindings can be used to call contracts at a specific block hash. Previously only block number or pending was supported.

Backwards compatibility is preserved by introducing a new `BlockHashContractCaller` interface with the `CallContractAtHash` and `CodeAtHash` methods required from the backend, following a similar pattern to `PendingContractCaller`.  Simulated backend is updated to support the new methods and `CodeAtHash` has been added to `ethclient.Client` - it already supported `CallContractAtHash`.

Fixes https://github.com/ethereum/go-ethereum/issues/28017

### CODE REVIEW

**Review by MariusVanDerWijden — APPROVED** [review]
LGTM

**Comment by ajsutton** [comment]
@MariusVanDerWijden Mind hitting merge for me? :)

**Comment by karalabe** [comment]
We've discussed this last week. Should be ok, but it creates a strange asymmetric API. Would be nice to add the "AtHash" methods for everything (code, balance, nonce, etc).

**Comment by ajsutton** [comment]
> We've discussed this last week. Should be ok, but it creates a strange asymmetric API. Would be nice to add the "AtHash" methods for everything (code, balance, nonce, etc).

@karalabe Added `BalanceAtHash`, `NonceAtHash` and `StorageAtHash` to complete the set.

**Review by holiman — APPROVED** [review]
LGTM

**Review by karalabe — APPROVED** [review]
SGTM!

**Pull request merged**
