### PR TITLE
swarm: ctx propagation; bmt fixes; pss generic notification framework

### PR DESCRIPTION
**Pull request by nonsense**
This PR includes the changes within Swarm over the last 2 weeks:
1. context.Context propagation within internal Swarm APIs (@nonsense)
2. BMT fixes (@zelig)
3. PSS Generic Notifications (@nolash)
4. A few additional counters within the metrics collection per process (@nonsense)
5. Various minor fixes.

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 0b65a9bd53d75deb49637d3668f8054ec65c3c53
  * Commits must be prefixed with the package(s) they modify

 * Commit: 9001a9c496474ebb61039801b1b540e4f540a6da
  * Commits must be prefixed with the package(s) they modify

 * Commit: 10ea10f7cf69209ba85894b1dc03232cea3297d1
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 77806decd4517b03e9c9ac6e8f876038a7dbf38b
  * Your commit message body contains a line that is longer than 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 0b65a9bd53d75deb49637d3668f8054ec65c3c53
  * Commits must be prefixed with the package(s) they modify

 * Commit: 9001a9c496474ebb61039801b1b540e4f540a6da
  * Commits must be prefixed with the package(s) they modify

 * Commit: 10ea10f7cf69209ba85894b1dc03232cea3297d1
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by gbalint** [comment]
Only swarm changes and two counters added to metrics

**Pull request merged**
