### PR TITLE
Statedb rem blockhash followup

### PR DESCRIPTION
**Pull request by MariusVanDerWijden**
depends on #23103

### CODE REVIEW

**Comment by holiman** [comment]
> depends on #23103 

Not if I merge this first :trollface:

**Review by holiman — APPROVED** [review]

**Comment by gzliudan** [comment]
I have a question: why header.Hash() is used as parameter blockHash in https://github.com/MariusVanDerWijden/go-ethereum/blob/b5e579c4872dc604379689ce26c1312a8a1c877b/core/state_processor.go#L152 ?

```go
func ApplyTransaction(config *params.ChainConfig, bc ChainContext, author *common.Address, gp *GasPool, statedb *state.StateDB, header *types.Header, tx *types.Transaction, usedGas *uint64, cfg vm.Config) (*types.Receipt, error) {
	msg, err := tx.AsMessage(types.MakeSigner(config, header.Number), header.BaseFee)
	if err != nil {
		return nil, err
	}
	// Create a new context to be used in the EVM environment
	blockContext := NewEVMBlockContext(header, bc, author)
	vmenv := vm.NewEVM(blockContext, vm.TxContext{}, statedb, config, cfg)
	return applyTransaction(msg, config, bc, author, gp, statedb, header.Number, header.Hash(), tx, usedGas, vmenv)
}
```

**Comment by MariusVanDerWijden** [comment]
We need the header hash for setting it in the receipts. Or do you mean why not pass the header itself only the header hash? It's quicker if you apply multiple transactions in a block (see `(p *StateProcessor) Process()`)

**Comment by gzliudan** [comment]
According to my understanding, it should pass block hash, not header hash ?

**Comment by MariusVanDerWijden** [comment]
Blockhash and header hash are one and the same thing see: https://github.com/ethereum/go-ethereum/blob/e1b98f49a5075694c5022f5ec74425e40da415dd/core/types/block.go#L431

**Comment by gzliudan** [comment]
Thanks.

**Pull request merged**
