### PR TITLE
eth/tracers/js: fix type inconsistencies

### PR DESCRIPTION
**Pull request by s1na**
As pointed out by @LukaszRozmej there are 2 type inconsistencies in the JS tracer:

- In most places we return byte arrays as a `Uint8Array` to the tracer. However it seems we missed doing the conversion for `ctx` fields which are passed to the tracer during `result`. They are passed as simple arrays. I think Uint8Arrays are more suitable and we should change this inconsistency. Note: this will be a breaking-change. But I believe the effect is small. If we look at our tracers we see that these fields (`ctx.from`, `ctx.to`, etc.) are used in 2 ways. Passed to `toHex` which takes both array or buffer. Or the length was measured which is the same for both types.
- The `slice` taking in `int, int` params versus `memory.slice` taking `int64, int64` params. I suggest changing `slice` types to `int64`. This should have no effect almost in any case.

### CODE REVIEW

**Comment by LukaszRozmej** [comment]
This might be a breaking change as it changes how those arrays get serialized.

**Review by holiman — APPROVED** [review]
LGTM

**Comment by LukaszRozmej** [comment]
One more problem found `isPush` for `PUSH0` returns `false`, should be `true`

**Comment by holiman** [comment]
Tagged for triage for discussion, since potentially backwards incompatible

**Review by fjl — APPROVED** [review]

**Comment by fjl** [comment]
About `isPush`: this accessor is supposed to tell you whether the opcode has a size of more than one byte. PUSH0 is a single-byte opcode and that's why it returns `false` for it.

**Comment by holiman** [comment]
Actually, @fjl, we fixed that, it returns true now... Ambiguous semantics. I would argue that it should return true, or be renamed to HasImmediate

**Comment by s1na** [comment]
> @LukaszRozmej About isPush: this accessor is supposed to tell you whether the opcode has a size of more than one byte. PUSH0 is a single-byte opcode and that's why it returns false for it.

I think any code that depends on number of operands will do `opcode - 0x60`. This will return 0 for PUSH0. Within geth we are only using `isPush` in the assembler (in the same way I described), and I added a testcase to make sure that still works.

**Pull request merged**
