### PR TITLE
tests: update common test wrappers and test files

### PR DESCRIPTION
**Pull request by Gustav-Simonsson**
- [x] Validate both RLP decoded and imported block headers against test file JSON
- [x] Validate all fields in test file ```postState```
- [ ] ~~Skip validation of imported block headers in lieu of test files containing information on expected outcome of reorgs (since this cannot be determined by test wrapper without making use of the very protocol logic it's testing)~~
- [x] Correctly validate the longest chain after importing all blocks, based on ```lastblockhash``` field
- [x] Do not skip nil post state objects in ```StateTests``` validation
- [x] Conform to Go convention in test validation printouts

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Wed Sep 16 21:34:33 UTC 2015_

**Comment by Gustav-Simonsson** [comment]
Please scroll down to the end to see the change to ```state_test_util.go```

**Comment by fjl** [comment]
:+1:

**Comment by fjl** [comment]
Isn't checking nil state objects going to panic?

**Comment by Gustav-Simonsson** [comment]
@fjl hmm, don't think so. no idea why the check was there, probably due to some past behaviour of ```StateDB```

**Comment by obscuren** [comment]
:+1:

**Pull request merged**
