### PR TITLE
swarm Add convenience script to run singleton with geth support

### PR DESCRIPTION
**Pull request by hermanjunge**
This shortens the steps we need to run a singleton instance of swarm, as specified in this guide:

http://swarm-guide.readthedocs.io/en/latest/runninganode.html

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: aca8c13670a8b71ccd7218a77649404499dbdf49
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 1d5c5855e04318143989eafc4f3e1ef67e7d139f
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by hermanjunge** [comment]
@zelig

**Comment by zelig** [comment]
@hermanjunge do you mind publishing this in the swarm guide itself. 
In the code, we do not want to support such shell scripts.

**Comment by fjl** [comment]
Sorry, I'm closing this for the reason given by Viktor above. Thank you for the effort nonetheless!

**Pull request closed without merging**
