### PR TITLE
CONTRIBUTING: Added a feature section

### PR DESCRIPTION
**Pull request by obscuren**

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Mon Feb 1 12:53:00 UTC 2016_

**Comment by zsfelfoldi** [comment]
:+1:

**Comment by karalabe** [comment]
Please update the link within :P

**Comment by karalabe** [comment]
LGTM :+1:

**Pull request merged**
