### PR TITLE
Add flag to allow unlocked accounts + RPC, disable combination otherwise

### PR DESCRIPTION
**Pull request by Gustav-Simonsson**
https://www.youtube.com/watch?v=yK0P1Bk8Cx4

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Mon Aug 31 12:59:55 UTC 2015_

**Comment by karalabe** [comment]
Like this? :fire:

**Comment by obscuren** [comment]
:-1: I like the warning on `0.0.0.0`. I don't like the `--dangerzone` flag. We should add a token on startup instead when `--rpc` is ran. The token will be displayed **once** during startup of the `HTTP-RPC` interface

**Comment by Gustav-Simonsson** [comment]
@obscuren what type of token?

**Comment by fjl** [comment]
I'm guessing he is talking about an auth token that is checked against when sending a transaction.

**Comment by fjl** [comment]
Given that @obscuren doesn't agree there isn't much of a chance this PR will ever make it.

**Pull request closed without merging**
