### PR TITLE
all: clean up the configs for pruner and snapshotter

### PR DESCRIPTION
**Pull request by rjl493456442**
This PR cleans up the configurations for pruner and snapshotter by passing a config struct.

And also, this PR disables the snapshot background generation if the chain is opened in "read-only" mode. The read-only mode is necessary in some cases. For example, we have a list of commands to open the etheruem node in "read-only" mode, like `export-chain`. In these cases, the snapshot background generation is non expected and should be banned explicitly.

### CODE REVIEW

**Comment by holiman** [comment]
Due to #22407, this needs a rebase if we still want it in

**Comment by rjl493456442** [comment]
Yes, I will rebase it and want it in.

**Comment by MariusVanDerWijden** [comment]
This looks like an interesting PR, needs a rebase but the idea seems good to me

**Comment by holiman** [comment]
Rebased

**Review by holiman — APPROVED** [review]
LGTM

**Pull request merged**
