### PR TITLE
[swarm] Use a more common command to get mimetype

### PR DESCRIPTION
**Pull request by uzyn**
`mimetype` is not natively available on Mac and Ubuntu, while `file` is and should be on most.

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Thu May 12 15:46:04 UTC 2016_

**Comment by karalabe** [comment]
@zelig @nagydani Please check this PR as it's against the swarm branch and I've no clue what to do with it.

**Comment by uzyn** [comment]
Looks like there has been major updates since the last PR.

I'll resubmit a fresh PR if this is still good.

Thanks.

**Comment by fjl** [comment]
@zelig I repeat my plea that cmd/bzzup should be written in Go instead. If you do so,
there are many libraries that implement mime type sniffing in a platform-independent manner. See http://godoc.org/?q=magic for all the wonderful options that you have.

**Comment by zelig** [comment]
superceded

**Pull request closed without merging**
