### PR TITLE
accounts/usbwallet: swap karalabe/gousb to karalabe/hid

### PR DESCRIPTION
**Pull request by karalabe**
Use `hidapi` instead of `libusb` directly. This way macOS and Windows can use their proprietary APIs and we don't have permission issues. Linux remains with libusb.

### CODE REVIEW

**Comment by arkpar** [comment]
You could also use hidraw backend instead of libusb on Linux. It requires a not too ancient kernel but adds support bluetooth devices. See https://github.com/signal11/hidapi/blob/master/linux/README.txt

**Comment by karalabe** [comment]
Hey @arkpar, thanks for the tips. Currently the PR indeed is based on `hidraw`, although it requires `libudev` for building. I'm not sure whether to keep this version or `libusb` as I did figure out proper compilation and wrapping for the latter but not for the former. Will look into it though.

**Comment by fjl** [comment]
Please fork hidapi to your account and add it as a dependency in vendor/

**Comment by karalabe** [comment]
Fork what? It's a brand new package.

**Comment by fjl** [comment]
I can confirm that this fixes #3677

**Comment by karalabe** [comment]
OSX seems to work correctly too based on an initial smoke test by @alexvandesande .

**Comment by karalabe** [comment]
OSX also confirmed by someone on the Ledger slack channel.

**Pull request merged**
