### PR TITLE
ethdb/pebble: remove a dependency

### PR DESCRIPTION
**Pull request by MariusVanDerWijden**
The dependency was not really used anyway, so we can get rid of it

### CODE REVIEW

**Review by holiman — DISMISSED** [review]
LGTM

**Comment by MariusVanDerWijden** [comment]
Hmm I pushed another commit that does slightly change something. Beforehand if we encountered something fatal in pebble we would also output a stack trace. Now we also print a stack trace (because we panic), but the traces might be slightly different

**Comment by holiman** [comment]
Seems like a regular `fmt.Errorf` should be sufficient. But please provide a sample, so we can compare the before and after

**Comment by MariusVanDerWijden** [comment]
Before
```
--- FAIL: TestPanic (0.00s)
panic: fatal: Test [recovered]
	panic: fatal: Test

goroutine 8 [running]:
testing.tRunner.func1.2({0xb64260, 0xc00022c498})
	/home/matematik/sdk/go1.20.1/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	/home/matematik/sdk/go1.20.1/src/testing/testing.go:1529 +0x39f
panic({0xb64260, 0xc00022c498})
	/home/matematik/sdk/go1.20.1/src/runtime/panic.go:884 +0x213
github.com/ethereum/go-ethereum/ethdb/pebble.panicLogger.Fatalf(...)
	/home/matematik/go/src/github.com/ethereum/go-ethereum/ethdb/pebble/pebble.go:134
github.com/ethereum/go-ethereum/ethdb/pebble.TestPanic(0x412199?)
	/home/matematik/go/src/github.com/ethereum/go-ethereum/ethdb/pebble/pebble_test.go:60 +0x5b
testing.tRunner(0xc000185860, 0xc09510)
	/home/matematik/sdk/go1.20.1/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/home/matematik/sdk/go1.20.1/src/testing/testing.go:1629 +0x3ea
FAIL	github.com/ethereum/go-ethereum/ethdb/pebble	0.006s
FAIL
```
After
```
--- FAIL: TestPanic (0.00s)
panic: fatal: Test [recovered]
	panic: fatal: Test

goroutine 23 [running]:
testing.tRunner.func1.2({0xafe860, 0xc000111cd0})
	/home/matematik/sdk/go1.20.1/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	/home/matematik/sdk/go1.20.1/src/testing/testing.go:1529 +0x39f
panic({0xafe860, 0xc000111cd0})
	/home/matematik/sdk/go1.20.1/src/runtime/panic.go:884 +0x213
github.com/ethereum/go-ethereum/ethdb/pebble.panicLogger.Fatalf(...)
	/home/matematik/go/src/github.com/ethereum/go-ethereum/ethdb/pebble/pebble.go:133
github.com/ethereum/go-ethereum/ethdb/pebble.TestPanic(0x412199?)
	/home/matematik/go/src/github.com/ethereum/go-ethereum/ethdb/pebble/pebble_test.go:60 +0x53
testing.tRunner(0xc000224820, 0xc09510)
	/home/matematik/sdk/go1.20.1/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/home/matematik/sdk/go1.20.1/src/testing/testing.go:1629 +0x3ea
FAIL	github.com/ethereum/go-ethereum/ethdb/pebble	0.006s
FAIL
```

It looks like nothing changes, there are some additional fields that they set, that you can retrieve via `errors.GetSafeDetails(error)` but we don't do that anyway, so its moot.
In our case, the error will always be the same

**Comment by fjl** [comment]
I added the call to Diff to help with debugging test failures. While it isnt strictly required, and I do feel the dependency is justified, especially since it is only for tests.

**Comment by holiman** [comment]
I agree about keeping `Diff`, after looking into it. The dependency is tiny, and doesn't bring any more dependencies in: https://github.com/kylelemons/godebug/blob/master/go.mod

**Review by holiman — CHANGES_REQUESTED** [review]
Please revert the `kylelemons/godebug/diff` change

**Review by fjl — APPROVED** [review]

**Pull request merged**
