### PR TITLE
core/rawdb: Freezer.writeBatch is only used when !readonly

### PR DESCRIPTION
**Pull request by zhiqiangxu**

### CODE REVIEW

**Comment by holiman** [comment]
I mean.. the old code is not wrong. I don't think merging this PR for such a tiny change is warranted. I don't oppose the new code per se, just prefer not to change stuff if we don't need to.

**Comment by zhiqiangxu** [comment]
> I mean.. the old code is not wrong. I don't think merging this PR for such a tiny change is warranted. I don't oppose the new code per se, just prefer not to change stuff if we don't need to.

But this PR doesn't have any side effect or risk, right? It's weird to instantiate something for `write` when it's `readonly` IMO.

**Comment by holiman** [comment]
> But this PR doesn't have any side effect or risk, right?

True, but neither does it improve anything. It adds two lines of code, and the gain is that there's a tiny amount less memory consumed, and a bit of cpu cycles gained, in cases where we're doing readonly. But readonly is only used in special cases, it's not the "production default". 

I personally don't see any point in merging this change. However, yeah, I agree the code is not harmful. I'll approve it, and leave it to someone else to merge if they think it is a change worth making.

**Review by holiman — APPROVED** [review]
Doesn't hurt :)

**Comment by rjl493456442** [comment]
Not sure if it's worthwhile. I would prefer to initialize the batch instead of keeping it as nil.

**Comment by holiman** [comment]
Sorry, that makes two of us that do not feel this change is worth it. But thanks for taking the time to help out!

**Pull request closed without merging**
