### PR TITLE
Typo in readme

### PR DESCRIPTION
**Pull request by TrySpace**

### CODE REVIEW

**Comment by robotally** [comment]
:exclamation: Pull request against `master` :exclamation:

| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Thu Jun 16 13:50:05 UTC 2016_

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: e271fd57132763f39c6993a35e6c063aac3af4f1
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by karalabe** [comment]
Thanks for noticing this. Please open the PR against the `develop` branch. We do all our development on that and then backport/release changes from there. Also please prefix your commit message with the packages the changes touch (i.e. in this case `README`).

**Comment by karalabe** [comment]
Superseeded by https://github.com/ethereum/go-ethereum/pull/2763.

**Pull request closed without merging**
