### PR TITLE
jsre: downgrade web3.js due to issues with printing BigNumbers

### PR DESCRIPTION
**Pull request by bas-vk**
This PR downlogrades web3.js to the previous version. The latest version gives problems with printing BigNumbers and I need @frozeman helps to determine the actual problem. The latest version of web3.js comes with the personal extensions which where removed on upgrade. These are restored.

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Tue Apr 12 14:49:16 UTC 2016_

**Comment by fjl** [comment]
We can also fix the printer instead.

**Comment by bas-vk** [comment]
I'm not really sure what the problem is. The printer seems fine to me.

**Comment by fjl** [comment]
[This check](https://github.com/ethereum/go-ethereum/blob/f460b0217fd8de6de90814e53e7ba4e2e86aff15/jsre/pretty.go#L229) is broken.

**Comment by fjl** [comment]
See https://github.com/ethereum/go-ethereum/pull/2448

**Pull request closed without merging**
