### PR TITLE
containers/vagrant: Adding support for CentOS

### PR DESCRIPTION
**Pull request by ksinkar**
1. CentOS has been added as a multi-machine option to the Vagrant script
2. Ubuntu is still the default option

Usage:

For starting the CentOS machine please do

```bash
$ vagrant up centos
```

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 99152d7f7ef277f7a985c6c9496abeb3d31d4fb3
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 99152d7f7ef277f7a985c6c9496abeb3d31d4fb3
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by karalabe** [comment]
Hmm, I think the Ubuntu vagrant image is way out of sync already. The script probably won't work properly, at least the PPAs inside are wrong. We'd need to look into that too. Thanks for this PR, I'll try to test it out somehow, alas I don't use vagrant.

**Comment by ksinkar** [comment]
I can make both the images work. Both the images shall install and compile go-ethereum from source, in a fashion similar to your docker scripts. Just let me know what is the litmus test to make sure that the geth is working properly on the VM.

**Comment by fjl** [comment]
We'd appreciate a fix for the Ubuntu image too ;). For testing, just run geth for a while and see if it prints "imported new XXX" messages.

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 99152d7f7ef277f7a985c6c9496abeb3d31d4fb3
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by karalabe** [comment]
@ksinkar Oops, you accidentally merged in master into this PR. Please rebase pending PRs, never merge to avoid having duplicate commits like here.

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 99152d7f7ef277f7a985c6c9496abeb3d31d4fb3
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 99152d7f7ef277f7a985c6c9496abeb3d31d4fb3
  * Commits must be prefixed with the package(s) they modify

 * Commit: 27e0fbc9e63588fef591760d1fa2b32d758f60c4
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by ksinkar** [comment]
@karalabe I have fixed the mergin/rebasing problem created earlier. I also have a pushed Debian script.
@fjl Ubuntu script for Vagrant now works. Please check and let me know.

I would like to make suggestion here. The *Vagrantfile* should probably be placed in the root of this project, while the provisioners directory can stay back here. Please let me know what you think. Also I would like to squash all the commits on this branch into one for better commit history. Please let me know before you decide to merge, so I can squash the commits into one commit.

**Pull request merged**
