### PR TITLE
accounts/abi: Implement Parsing for Struct Types

### PR DESCRIPTION
**Pull request by VoR0220**
This PR contains parsing for tuple types (aka Structs) in the ABI. This is a fairly new feature and figured I'd help ya'll get there at the least. This does not contain packing or unpacking. Those will come in a later PR when I have time to work on it.

### CODE REVIEW

**Comment by VoR0220** [comment]
Current build is passing for everything except an account_cache_test.go error. It appears to be unrelated. Also a weird golinting error saving that this isn't gofmt'd...but it is? Maybe you have a better preference of how to write the structs in the type_test but I that was the easiest way for me to read them.

**Comment by dshulyak** [comment]
@VoR0220 do you plan to finish this pr in near future?

I am asking, cause i was doing similar changes with abi packing and input generation for abigen.
I can rebase those changes, or finish my pr

**Comment by VoR0220** [comment]
Near future, no. This is just the type generation for now. If you have packing and unpacking implemented, go for it, rebase this on top of your changes, do whatever you need to do.

**Comment by gballet** [comment]
@VoR0220 do you still need this PR to be reviewed? If so, would you mind rebasing? It would make it easier for me to find out what its merits are.

**Comment by VoR0220** [comment]
@gballet here are the merits. I've implemented parsing the ABI type for structs from the JSON format. Now someone else needs to do the serialization and deserialization into the type and out of the bytecode data that needs to be sent off. I can implement this serialization/deserialization some time in the future but I'm busy atm. IIRC structs haven't been implemented just yet.

**Comment by gballet** [comment]
Closing this PR as it is unfinished, hasn't been updated in a long time and is partially redundant with PRs that got in since. Feel free to reopen if you want to work on this further.

**Pull request closed without merging**
