### PR TITLE
Fixed language inconsistency in docs

### PR DESCRIPTION
**Pull request by SebastianSupreme**
Removed parentheses in line 71 because line 80 doesn't have them either.

### CODE REVIEW

**Review by ligi — APPROVED** [review]

**Comment by SebastianSupreme** [comment]
@ligi Somehow the AppVeyor build failed although I only changed text in the docs. Is that a problem for merging this PR?
If so, do you have any suggestions how to fix this error?

**Comment by SebastianSupreme** [comment]
@ligi Thank you for approving my PR. Will you merge it today, too?

**Comment by SebastianSupreme** [comment]
@ligi Thank you for approving my PR. Could you please merge it today, too?

**Comment by SebastianSupreme** [comment]
@holiman Hey, could you please merge my PR as well? ligi already reviewed and approved it.

**Comment by holiman** [comment]
> mined at Aug-27-2021 12:50:07 PM +UTC

This is correct. "It was mined at **date**", where **date** is a full-fledged member of the sentence. 

Putting it in parenthesis means that it can be omitted when read aloud. In the context above, that would not work. 
Here's an example of when it _does_ work: 

> It was mined a long time ago (Aug-27-2021 12:50:07 PM +UTC), way before the byzantium hardfork ...

**Comment by holiman** [comment]
Oh my bad -- I read the diff  "in reverse" :)

**Comment by SebastianSupreme** [comment]
@fjl Thanks for merging. Quick question: Does this mean I'm eligible for a GitPOAP now?

**Comment by holiman** [comment]
Gitpoaps are not affiliated with go-ethereum, or endorsed in any 'official' way. Ask them.

**Pull request merged**
