### PR TITLE
p2p: don't use peer.Name in warn messages

### PR DESCRIPTION
**Pull request by MariusVanDerWijden**
We currently use the name (which can be freely set by the peer) in several log messages.
This enables malicious actors to write spam into your geth log.
This pr reduces the usage of peer.Name() to log messages which are not shown by default

rel: https://github.com/ethereum/go-ethereum/issues/21687

### CODE REVIEW

**Comment by karalabe** [comment]
You can't just nuke a function to work around a single log entry :P. If the log is problematic, we need to make a more surgical fix. This will most probably blow up throughout the code which uses the node names.

**Comment by MariusVanDerWijden** [comment]
You're right, it's getting pretty late around here^^ Will provide a proper fix tomorrow

**Comment by karalabe** [comment]
Yup, no need to rush it that much

**Comment by holiman** [comment]
Alternatively, we could jsut display the first 20 (or so) characters of the name

**Comment by fjl** [comment]
We already truncate the name in package p2p's own log messages: https://github.com/ethereum/go-ethereum/blob/master/p2p/server.go#L999

**Comment by fjl** [comment]
I think it would also be reasonable to define a max name size at the protocol level, maybe 140 characters?

**Review by holiman — APPROVED** [review]
LGTM. Not sure if this is to be preferred over a shortened name, it's useful to be able to see what the remote side is.

**Comment by karalabe** [comment]
I still don't like this change. The purpose we put the name in the log in the first place was to see if something implements the checkpoint challenge or whatnot badly. Seeing which IP does a bad thing is more or less useless, that's the same as if we just hav the peer id. We need the name to see if some version is borked. At least that was the original point of including it.

**Comment by holiman** [comment]
@karalabe how about this: https://github.com/ethereum/go-ethereum/compare/master...holiman:addback?expand=1 ?

**Comment by fjl** [comment]
Please change `Peer.Name` to return the name truncated to 20 characters and add a new method `FullName` which returns the complete string. The peer info API needs to be changed to use the `FullName`.

**Pull request closed without merging**
