### PR TITLE
swarm subcommands for manifest manipulation

### LINKED ISSUE #3498: Swarm: need tools to update/manipulate manifests
Swarm manifests are easily created using the `bzz.upload` and `swarm up` commands. 

They are however very difficult to update / manipulate. Currently, if I want to fix a typo on a swarm website, I will fix the typo, then re-upload the offending html file and all the javascript, css, images, videos, pdfs and other assets contained in the site. 

What we need is a tool that makes it easy to:

Update an entry in a manifest.
Add an entry to a manifest.
Remove an entry from a manifest.

Note also that this may require recursively changing sub-manifests.

### PR DESCRIPTION
**Pull request by jmozah**
fixes #3498

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 18bf7ba0238f069162b62e945065e9e6e7ef2fad
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 18bf7ba0238f069162b62e945065e9e6e7ef2fad
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 18bf7ba0238f069162b62e945065e9e6e7ef2fad
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 18bf7ba0238f069162b62e945065e9e6e7ef2fad
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by zelig** [comment]
obsoleted by https://github.com/ethereum/go-ethereum/pull/3645

**Pull request closed without merging**
