### PR TITLE
core: implement eip-7623: increase calldata cost

### PR DESCRIPTION
**Pull request by MariusVanDerWijden**
Draft implementation for discussion

### CODE REVIEW

**Comment by vbuterin** [comment]
The floor implementation looks like it's counting bytes rather than tokens?

```
dataLen := uint64(len(data))
```

What I think you want is something like:

```
TokensPerNonzeroByteFrontier uint64 = 17
TokensPerNonzeroByte uint64 = 4
TxTokenGas uint64 = 4
CostFloorPerToken7623 uint64 = 17

tokensPerNonzeroByte = params.TokensPerNonzeroByteFrontier

if isEIP2028 {
    tokensPerNonzeroByte = params.tokensPerNonzeroByte
}
dataTokens = z + nz * TokensPerNonzeroByte
gasForData = dataTokens * params.TxTokenGas
floor := params.CostFloorPerToken7623 * dataTokens
```

**Comment by MariusVanDerWijden** [comment]
Yep, you're right. We have not had the concept of tokens yet, so I got a bit confused.
It should be okay now

**Comment by ChanHongMing** [comment]
the current implementation doesn't seems to match the specification on https://github.com/ethereum/EIPs/blob/a7fb2260ae2ea39bdd31886832c9e45452d0e76a/EIPS/eip-7623.md

In the EIP, the new formula is 
```python
tx.gasUsed = {
    21000 \ 
    + 
    max (
        STANDARD_TOKEN_COST * tokens_in_calldata \
           + evm_gas_used \
           + isContractCreation * (32000 + InitCodeWordGas * words(calldata)),
        TOTAL_COST_FLOOR_PER_TOKEN * tokens_in_calldata
    )
}
```
This implementation looks like 
```python
tx.gasUsed = {
    21000 \ 
    + evm_gas_used \
    + isContractCreation * (32000 + InitCodeWordGas * words(calldata)) \
    max (
        STANDARD_TOKEN_COST * tokens_in_calldata ,
        TOTAL_COST_FLOOR_PER_TOKEN * tokens_in_calldata
    )
}
```

**Comment by MariusVanDerWijden** [comment]
closing this in favor of https://github.com/ethereum/go-ethereum/pull/30946

**Pull request closed without merging**
