### PR TITLE
accounts/abi: added ability for abi to keep note of the payable field

### PR DESCRIPTION
**Pull request by VoR0220**
Signed-off-by: VoR0220 <rj@erisindustries.com>

### CODE REVIEW

**Comment by karalabe** [comment]
Just out of curiosity, this PR only tracks the `payable` property, but does not act on it whatsoever, right? Would it (here or in a follow up PR) make sense to do some actual reaction to it? How would it play along with backward compatibility with contracts who did not have this feature?

**Comment by VoR0220** [comment]
@karalabe I figure that in terms of actual reaction, there could be ways of reaching the fallback function (which is useful for testing, and is also specified by the ABI) and determining how to interact with that. Personally have no clue where your interaction in terms of transaction data is held ( I imagine it's in the bind/backends package), but using this, if it's not payable, it can save on the cost of gas by asserting that a fee not be included in the transaction if the method is not payable. Something along these lines.

**Comment by VoR0220** [comment]
As for backwards compatibility...ehhhhhh....yea I don't have a good answer for that.

**Comment by VoR0220** [comment]
@karalabe I'm not sure how exactly it's converting atm but if we were to use field tags for the unmarshalling then the backwards compatibility would simply default to false.

**Comment by obscuren** [comment]
I'm unsure about the functionality this PR is supposed to add. What is the purpose?

**Comment by VoR0220** [comment]
@obscuren thanks for the comment. The purpose of this is to denote whether a method in a contract can receive ether or not. Its a useful distinction to be added in and a big reason why its a part of the current abi.

**Comment by VoR0220** [comment]
Adds general safety when transacting with a smart contract function. The usefulness of this is not made clear here but would likely be made clear with additions to the bindings and backend packages to construct native smart contracts in go or java.

**Comment by karalabe** [comment]
I kind of agree with Jeff here that the tracking the `payable` field doesn't feel quite right. As far as I understand it the purpose of the modifier is for the Solidity compiler to be able to generate throws for other methods that should not accept payments. In this case however it isn't so useful for the user really, the contract's API should document clearly which functions accept payment and which do not.

I don't think doing protective measures in generated bindings is a good idea, too many things can go wrong. My main concern being for example backward compatibility: if I add a `payable` restriction enforcement into the generated bindings, but I want to interact with an old contract, I'm out of luck because the binding will not let me do it due to believing it's non payable.

I'm not necessarily saying this feature cn't be made useful, but perhaps we should first figure out exactly how this might be used in a reliable way and only after that add it to the codebase.

**Comment by VoR0220** [comment]
@karalabe that's a fair point to be made in terms of backwards compatibility. Perhaps there is a way for payable to default to true unless it's found as otherwise in the ABI?

**Comment by fjl** [comment]
I'm closing this because two people have voiced concerns about this feature and there is no immediate use for it. We can revisit this in the future, but it doesn't fit right now.

**Comment by VoR0220** [comment]
When I have more time I'll clean it up for you to make it backwards compatible ;)

**Pull request closed without merging**
