### PR TITLE
Godeps: update github.com/rjeczalik/notify to f627deca7a51

### LINKED ISSUE #2829: panic: unhandled error: notify.FSEventsMustScanSubDirs|notify.FSEventsKernelDropped
#### System information
 
~ geth version
Geth
Version: 1.4.10-stable-5f55d95a
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.6.2
OS: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.6.2/libexec

#### Actual behaviour

Software crash

#### Steps to reproduce the behaviour
No steps found to reproduce

#### Backtrace

````
I0717 23:50:36.332543 core/blockchain.go:963] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 17.456699ms. #1903995 [5b577140 / 5b577140]
panic: unhandled error: notify.FSEventsMustScanSubDirs|notify.FSEventsKernelDropped

goroutine 37 [running]:
panic(0x48f1740, 0xc82a92f560)
	/usr/local/opt/go/libexec/src/runtime/panic.go:481 +0x3e6
github.com/rjeczalik/notify.(*watch).Dispatch(0xc820177700, 0xc82f032500, 0x1, 0x1)
	/private/tmp/ethereum-20160716-84588-1tmln98/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/rjeczalik/notify/watcher_fsevents.go:136 +0x54f
github.com/rjeczalik/notify.(*watch).Dispatch-fm(0xc82f032500, 0x1, 0x1)
	/private/tmp/ethereum-20160716-84588-1tmln98/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/rjeczalik/notify/watcher_fsevents.go:205 +0x3e
github.com/rjeczalik/notify.gostream(0x5e032d0, 0x1, 0x1, 0x7007550, 0x7007560, 0x7007570)
	/private/tmp/ethereum-20160716-84588-1tmln98/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:104 +0x11c
github.com/rjeczalik/notify._cgoexpwrap_b138320e5461_gostream(0x5e032d0, 0x1, 0x1, 0x7007550, 0x7007560, 0x7007570)
	??:0 +0x53
github.com/rjeczalik/notify._Cfunc_CFRunLoopRun()
	??:0 +0x36
github.com/rjeczalik/notify.init.1.func1()
	/private/tmp/ethereum-20160716-84588-1tmln98/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:68 +0x112
created by github.com/rjeczalik/notify.init.1
	/private/tmp/ethereum-20160716-84588-1tmln98/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:70 +0x48
````

### PR DESCRIPTION
**Pull request by fjl**
Fixes #2829

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Thu Aug 4 19:21:40 UTC 2016_

**Comment by bas-vk** [comment]
Since the notify package now basically ignores the error what are the consequences?
Do we still get a signal to refresh the account cache, or do we serve outdated records?

**Comment by fjl** [comment]
See https://github.com/rjeczalik/notify/issues/99 for some context

**Comment by bas-vk** [comment]
Ok, 👍

**Pull request merged**
