### PR TITLE
core/state/snapshot: cleanup generation logic

### PR DESCRIPTION
**Pull request by rjl493456442**
This PR cleans up the snapshot generation logic a bit by moving out the nested functions.
The main intention is to improve the code read-ability, the main logic shouldn't be changed.

### CODE REVIEW

**Review by holiman — APPROVED** [review]
I've been eyeing through it, found nothing that seems wrong. There are no intentional changes other than moving stuff around right? The only 'sematic' difference, afaict, is a bit how you handle the abort-chan by wrapping it inside an error, but that looks good to me. 

Did you test it on a live node?

**Comment by rjl493456442** [comment]
Thanks for the review!

> There are no intentional changes other than moving stuff around right? 

Yes. The main motivation is to get rid of the embedded functions which is unreadable.

> The only 'sematic' difference, afaict, is a bit how you handle the abort-chan by wrapping it inside an error, but that looks good to me

Yes.

> Did you test it on a live node? 

Not yet, I will spin up a node very soon and post the result here later

**Comment by rjl493456442** [comment]
截屏2022-03-10 下午11 15 08

After two days syncing and generation, it works out.

**Comment by holiman** [comment]
Let's merge this after the current release

**Comment by holiman** [comment]
milestone: 1.10.18

**Comment by rjl493456442** [comment]
Nothing changed, just squashed all the commits into a single one.

**Pull request merged**
