### PR TITLE
all: fix megacheck

### PR DESCRIPTION
**Pull request by zramsay**
- implements the low hanging fruit of running `make megacheck`; this tool includes each of `unused, staticcheck, gosimple`, [see here](https://github.com/dominikh/go-tools/tree/master/cmd/megacheck)
- the fixes are mostly self-explanatory; removed dead code & optimized use of the standard library.
- many of the recommendations that weren't addressed are large enough to be separate PRs; I focused on only the least controversial fixes

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 4d793513e2441f9c7882a0f052fbbb8f725eda7f
  * Commits must be prefixed with the package(s) they modify

 * Commit: 2b5fec3e68640d24fc37ba9c0fdcb4baaecdbc86
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by zramsay** [comment]
since this PR touches nearly every package, perhaps some lenience from gitcop is in order? (spirit of law and whatnot) ... lest we be left dozens of tiny commits

**Comment by fjl** [comment]
You can use "all: ..." prefix to remove gitcop complaint.

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 4d793513e2441f9c7882a0f052fbbb8f725eda7f
  * Commits must be prefixed with the package(s) they modify

 * Commit: 47cdf04e24dc0902e343516a983e977ce885318e
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by fjl** [comment]
I'm sorry to close this, but we didn't review in time and this change will continue to get broken as master moves forward. We'll look into fixing megacheck complaints, but it'll need to be an incremental process.

**Comment by karalabe** [comment]
The issue really is that a lot of code was removed which tools flag as dead, but in reality they are used by external tools. Similar with ledger protocol parameters, which aren't used, but aid in documentation and future extensions.

I'd really like to get te code cleaned up though, will maybe try to cherry pick pieces of it.

**Pull request closed without merging**
