### PR TITLE
ethdb, vendor: experiment suitable write buffer for leveldb

### PR DESCRIPTION
**Pull request by rjl493456442**

### CODE REVIEW

**Comment by rjl493456442** [comment]
**A few benchmark result**

image

From the database-wise, the total read/write amount is lower than master(Because 2/3 read operations are disabled to trigger seek compaction).

image

image

From the performance-wise, the exp branch is a little slower than the master branch(0.5 hour behind).

**Comment by karalabe** [comment]
This PR seems to drastically reduce disk IO. Performance wise it's hard to say because it hovers around the same numbers, but on a machine with less memory and slower ssd, it might make a lot bigger impact.

Screenshot from 2019-09-11 12-16-50
Screenshot from 2019-09-11 12-16-55

**Comment by karalabe** [comment]
For the record, this was the leveldb seek compact disable version for fast sync.

Screenshot from 2019-09-24 12-05-29

Essentially the PR cuts fast sync disk io in half.

Full sync still running.

**Comment by karalabe** [comment]
Sorry, didn't mean to close, pushed the wrong button.

**Comment by karalabe** [comment]
This is a fast sync with the adjusted write caches. As expected, compactions are more frequent, since we cache less data before doing the initial layer 0 write, so the data getting into layer 0 is "less sorted" than with a larger cache.

Screenshot from 2019-09-26 14-20-01

Here's a live link to the entire run https://geth-bench.ethdevops.io/d/Jpk-Be5Wk/dual-geth?orgId=1&from=1569410376230&to=1569437256230&var-exp=mon07&var-master=mon06&var-percentile=50

**Pull request closed without merging**
