### PR TITLE
contracts/chequebook: fix possible reentrancy bug in chequebook contract

### PR DESCRIPTION
**Pull request by nagydani**
A malicious beneficiary contract could recursively call back the chequebook contract's send method with the same cheque before the cashed amount has been updated and thus withdraw the amount several times.

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Mon Aug 29 19:56:33 UTC 2016_

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: c28923483ce8573f8aa2fda392a04274c4b24808
  * Commit subjects should be kept under 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by fjl** [comment]
Things to watch out for:

* The commit message should name the package that is modified. In this case it would be "contracts/chequebook/contract: fix possible reentrancy bug..."
* Please don't commit merges, rebase your branch on develop instead.
* Please use solc v0.3.6 to compile the contract.
* Please use abigen from develop branch

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 0435b33f44a5e8b90934ab253dff53360f8020e5
  * Commit subjects should be kept under 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by fjl** [comment]
Please make the following additional changes:

* remove "TODO: insert license header\n\n" in contracts/chequebook/genvalue.go and regenerate
* add entry for "contracts/chequebook/contract/" in build/update-license.go below the comment that says "don't license generated code"
* reformat commit message so the lines are wrapped at column 80 (what @GitCop I complaining about)

I will verify and merge tonight.

**Comment by fjl** [comment]
Sorry, I meant gencode.go, not genvalue.go

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 2c95389bacd3cd89d145721b7fc198c625e3c750
  * Commit subjects should be kept under 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by fjl** [comment]
Please commit the change to gencode.go as well. Looks good otherwise.

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 7b884e0075cba9033dadf2d8ed0bf092193d2ae5
  * Commit subjects should be kept under 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
