### PR TITLE
trie : use trie.NewStackTrie instead of new(trie.Trie)

### PR DESCRIPTION
**Pull request by ucwong**

### CODE REVIEW

**Comment by fjl** [comment]
@holiman @karalabe: I just noticed, through this PR, that we added the `hasher` parameter in https://github.com/ethereum/go-ethereum/commit/87c0ba92136a75db0ab2aba1046d4a9860375d6a. I think it would be better to remove this parameter again and let NewBlock handle this internally.

**Comment by ucwong** [comment]
> @holiman @karalabe: I just noticed, through this PR, that we added the `hasher` parameter in [87c0ba9](https://github.com/ethereum/go-ethereum/commit/87c0ba92136a75db0ab2aba1046d4a9860375d6a). I think it would be better to remove this parameter again and let NewBlock handle this internally.

It will cause ```import cycle``` for this ```stacktrie_test.go``` file
https://github.com/ethereum/go-ethereum/blob/master/trie/stacktrie_test.go#L12

**Review by holiman — APPROVED** [review]
Yes, makes definite sense to me

**Comment by holiman** [comment]
> @holiman @karalabe: I just noticed, through this PR, that we added the hasher parameter in 87c0ba9. I think it would be better to remove this parameter again and let NewBlock handle this internally.

I'd love to get rid of it, but if so we need to solve the import cycle problem. ISTR it's not just tests, but other things that are hard to solve

**Comment by karalabe** [comment]
Stack trie assume we insert sorted keys, right? Are we sure all these use cases do that?

**Comment by holiman** [comment]
> Stack trie assume we insert sorted keys, right? Are we sure all these use cases do that?

Yes, it does. However, all these usecases, unless I've missed something, is used (eventually) to feed into DeriveSha, which (nowadays) ensure that the keys are sorted.

If I missed something, then that would be bad :/

**Review by holiman — APPROVED** [review]
LGTM. This PR changes to use `stackTrie` in places that either directly call into `DeriveSha`, or `types.NewBlock`, where the hasher is _only_ used for call into `DeriveSha`.

**Pull request merged**
