### PR TITLE
cmd, eth: ulc options added

### LINKED ISSUE #15657: ULC: first step
The issue is from https://gist.github.com/zsfelfoldi/7da2b802824569d2d159d5d06eeda14c (@zsfelfoldi ). A part of Status.im and Ethereum collaboration.

I've done 4 out of 6 points. The rest 2 should be done by @b00ris.

Here:
- adding the ultra light client option
Add an extra option for light client mode where the user can specify a text/json ULC config file that contains a list of trusted server enodes and N out of M parameters (which may depend on how many servers we are connected to, there may be 5 servers listed but we can still accept 2 out of 3 connected).
Here are some pointers to implementing the ULC mode. Just take a look at the relevant code, then feel free to ping me whenever you have questions (I guess it will happen a few times, I tried to document the most important parts but some of the code is still a bit messy, which I apologize for in advance).

- requesting signed headers
Now the client will only accept signed announcements so we can accept the corresponding headers without PoW check.

- switching off header PoW validation:

- modifying the server pool to always try to connect to trusted nodes:

### PR DESCRIPTION
**Pull request by JekaMas**
closes #15657

### CODE REVIEW

**Comment by ligi** [comment]
Sounds interesting - thanks - but I think we also need an option for the android API to use this option. As far as I see this way you can only configure it via CLI - there is no CLI when using the AAR

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 23c8784ce09187cdb3f699138a4d5436445bd6a2
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by karalabe** [comment]
Why open a PR with flags for a non existent feature? I'm all in for progressively merging large features, but it feels a bit backward to do the "UI" before having any actual implementation done.

**Comment by JekaMas** [comment]
@karalabe Ok, i've got you point so we are going to implement all other steps from https://gist.github.com/zsfelfoldi/7da2b802824569d2d159d5d06eeda14c and this issue going to be last.

**Comment by fjl** [comment]
Great. Let's reopen this when the functionality is there.

**Comment by JekaMas** [comment]
@fjl Could you reopen the issue: it was good and long day and i've implemented 4 od 6 steps of ULC and really want to hear feedback :)

**Pull request closed without merging**
