### PR TITLE
Dockerfile: extended version with Go binaries and version control systems

### PR DESCRIPTION
**Pull request by pavel-kiselyov**
Modern cloud CI environments use containerized builds for better isolation. Sometimes, integration tests in Go packages depend on running Geth node in development mode. To achieve that, there are two ways:

* First, you can re-use `cmd/geth` codebase to start a development node directly in tests inside a separate goroutine. But you can't just import `cmd/geth`, because it is a `main` package, so you'll probably have to copypaste all necessary code that is required by `startNode()` function.
* Second (and slightly more simplistic) way is to launch another OS process directly inside tests, using `os/exec` package and then terminate it at the end of the test suite.

This extended image is implementation of the second way. It contains `geth`, all the binaries from `cmd` subpackage, Golang binaries & libraries from base builder image and version control systems supported by `go get`.

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 7c2b98f2f87fb5ef6f9d3dbfe33df485072042e9
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by pavel-kiselyov** [comment]
@GitCop fixed

**Comment by pavel-kiselyov** [comment]
Fixed the commit message

**Comment by pavel-kiselyov** [comment]
@jebek29 Re-using image from 1st build step to avoid repeating actions & speed-up builds

**Comment by fjl** [comment]
We have discussed this and have decided to not include this Dockerfile. You can always create a container based on ours by installing git, etc. in the normal geth container.

**Pull request closed without merging**
