### PR TITLE
fuzzers: fuzzers for keystore, rlp, trie, whisper 

### PR DESCRIPTION
**Pull request by holiman**
This PR includes fuzzers for [fuzzbuzz](https://app.fuzzbuzz.io), a SaaS fuzzer platform using go-fuzz under the hood. Currently implemented fuzzers are:

- keystore
- rlp
- trie
- whisper6

cred to @guidovranken who wrote most of these fuzzers once upon a time

### CODE REVIEW

**Comment by fjl** [comment]
Maybe better to move this code to "tests/fuzzers".

**Comment by holiman** [comment]
I suspect this may need some more work _after_ we've switched to modules, so I'll take a peek once that's done

**Comment by holiman** [comment]
Fuzzers have been moved now, but as I suspected the switch to modules seems to have broken the workflow. Investigating...

**Comment by holiman** [comment]
Nope, false alarm. After I updated to a more recent version of `go-fuzz`, the build problems disappeared. 
This should be good to go. Ptal @fjl

**Pull request merged**
