### PR TITLE
les/catalyst/api: add support for ExchangeTransitionConfigurationV1

### PR DESCRIPTION
**Pull request by pinkiebell**
This method is missing in light client mode and breaks consensus clients that require a valid response.

### CODE REVIEW

**Comment by sirnicolas21** [comment]
```
INFO [09-18|09:24:31.854] Starting peer-to-peer node               instance=Geth/v1.11.0-unstable-8e520155/linux-amd64/go1.18.6
INFO [09-18|09:24:31.930] New local node record                    seq=1,662,720,486,099 id=c87551627b3f6d9f ip=127.0.0.1 udp=30303 tcp=30303
INFO [09-18|09:24:31.932] Started P2P networking                   self=enode://3aafd8d23132f45198678359c0b45ab0dc1d67d128d139ed09010db4d1a5f1d534a90b00d95d9f04f6d91693135a263f79bd4a818352ff112b8dbae160c66928@127.0.0.1:30303
INFO [09-18|09:24:31.933] Generated JWT secret                     path=jwtsecret
INFO [09-18|09:24:31.934] HTTP server started                      endpoint=192.168.1.12:8545 auth=false prefix= cors=192.168.1.12 vhosts=localhost
INFO [09-18|09:24:31.934] WebSocket enabled                        url=ws://127.0.0.1:8546
INFO [09-18|09:24:31.934] WebSocket enabled                        url=ws://192.168.1.12:8551
INFO [09-18|09:24:31.934] HTTP server started                      endpoint=192.168.1.12:8551 auth=true  prefix= cors=localhost    vhosts=localhost
WARN [09-18|09:24:32.240] Served engine_newPayloadV1               conn=192.168.1.13:52438 reqid=1 duration="22.42µs" err="the method engine_newPayloadV1 does not exist/is not available"
WARN [09-18|09:24:34.144] Served engine_newPayloadV1               conn=192.168.1.13:52438 reqid=1 duration="19.486µs" err="the method engine_newPayloadV1 does not exist/is not available"
WARN [09-18|09:24:36.087] Served engine_newPayloadV1               conn=192.168.1.13:52438 reqid=1 duration="18.159µs" err="the method engine_newPayloadV1 does not exist/is not available"
WARN [09-18|09:24:36.777] Served engine_exchangeTransitionConfigurationV1 conn=192.168.1.13:52438 reqid=1 duration="45.817µs" err="the method engine_exchangeTransitionConfigurationV1 does not exist/is not available"
```
still a problem in 8e520155

**Comment by pinkiebell** [comment]
> still a problem in [8e52015](https://github.com/ethereum/go-ethereum/commit/8e5201551dab455eff7c8413dc682dad29dec0cd)

You have to use the authenticated endpoint `endpoint=192.168.1.12:8551` in your consensus client together with the jwt secret.

**Comment by sirnicolas21** [comment]
yea i had :8541 in that option, worked right away after fixing that, thanks a lot
maybe you want to change the message however on that error in something else maybe "the method engine_exchangeTransitionConfigurationV1 does not exist/is not available on that endpoint"

thanks again

**Comment by ekawibisono** [comment]
hello, i have a problem this, any solution for geth version latest ?

**Pull request merged**
