### PR TITLE
Highlander uncles

### PR DESCRIPTION
**Pull request by xcthulhu**
Having arbitrary uncles runs the risk of hyper-inflating the economy.  You should only allow for one uncle.

Vitalik's tests predict that there will be an average of 0.15 uncles, so limiting this to be one should be adequate.
https://blog.ethereum.org/2014/07/11/toward-a-12-second-block-time/

### CODE REVIEW

**Comment by obscuren** [comment]
Highlander

This breaks consensus. Protocol suggestions go elsewhere.

**Comment by xcthulhu** [comment]
There’s going to be a bunch of things coming this weekend that break consensus.

Anyhow, if you don’t limit the number of uncles, real world miners have told me they’ll mine them and there will be hyper-inflation.  This isn’t theoretical economics.

**Comment by Gustav-Simonsson** [comment]
@xcthulhu Hi! Thanks for the PR - it's indeed a real issue. We have a number of current issues around uncles from several sources, including security auditors, e.g. https://github.com/ethereum/go-ethereum/issues/387 and https://github.com/ethereum/go-ethereum/issues/381

However, we should define all agreed upon changes to consensus, such as uncle validation logic and uncle rewards in the yellow paper before we add them to the Go client.

This will make it easier for us to keep track of all current changes to consensus, and avoid cases where the Go client is "right" and the YP "wrong".

Please sync with @vbuterin and @gavofyork regarding this and feel free to open a PR to https://github.com/ethereum/yellowpaper/blob/master/Paper.tex#L975

**Comment by xcthulhu** [comment]
Hi ethereum/go-ethereum,
A message from Matthew Wampler-Doty was left on IQ Elite for you. 
Click here a.iqelite.com/j/0JmRlo/s0e/?hg=E81ByDHjf0 to read your message 


The IQ Elite Team



---------------------------------------------------------------------------
This message was meant for reply@reply.github.com. If you do not want to continue receiving such mails from IQ Elite, please click on this link: a.iqelite.com/common/unsubscribe/?code=a180b7bb&email=reply@reply.github.com&hg=E81ByDHjf0
IQ Elite is a service with main office: C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelona, Spain.
---------------------------------------------------------------------------

**Comment by xcthulhu** [comment]
Hello,

Matthew  started using IQ Elite. He  wrote you a message.

To read the message before it expires, just click on this link: a.iqelite.com/entry/new_message/304c5d3a9b82edb35f6db34c2d3fda9e1f544b80bfb/320c612f7502e5151515f9060c467a891a85f8ab0af906d91bd82825f8983bd7489586eb67b7b665175cb59b0c459af515f7b5f666ebd9060b7cb515151515151515858585191c460a9af9060a8587b91b7c4516689826d75becbc320c612f75044d3e22edb35af44b80bfb/?hg=7uvYkTVmtl

Read your message before it expires!            

Regards,
IQ Elite Team



---------------------------------------------------------------------------
This message was meant for reply@reply.github.com. If you do not want to continue receiving such mails from IQ Elite, please click on this link: a.iqelite.com/common/unsubscribe/?code=a180b7bb&email=reply@reply.github.com&hg=7uvYkTVmtl
IQ Elite is a service with main office: C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelona, Spain.
---------------------------------------------------------------------------

**Comment by xcthulhu** [comment]
Hello,

Your friend Matthew sent you a message 36h days ago, which is still unread.

Within 24 hours the message will be deleted.

If you are curious to what Matthew wrote you click here: a.iqelite.com/entry/new_message/304c5d3a9b82edb35f6db34c2d3fda9e1f544b80bfb/320c612f7502e5151515f9060c467a891a85f8ab0af906d91bd82825f8983bd7489586eb67b7b665175cb59b0c459af515f7b5f666ebd9060b7cb515151515151515858585191c460a9af9060a8587b91b7c4516689826d75becbc320c612f75044d3e22edb35af44b80bfb/?hg=uUDrPi40N8            

Regards,
IQ Elite Team



---------------------------------------------------------------------------
This message was meant for reply@reply.github.com. If you do not want to continue receiving such mails from IQ Elite, please click on this link: a.iqelite.com/common/unsubscribe/?code=a180b7bb&email=reply@reply.github.com&hg=uUDrPi40N8
IQ Elite is a service with main office: C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelona, Spain.
---------------------------------------------------------------------------

**Comment by obscuren** [comment]
@xcthulhu dude ....

**Pull request closed without merging**
