### PR TITLE
cmd/evm: Add `--single-test` option to blocktest

### PR DESCRIPTION
**Pull request by marioevz**
Adds `--single-test` option to `evm blocktest` to run a single test from a given json BlockchainTest file.

This allows [execution-spec-tests](https://github.com/ethereum/execution-spec-tests/) to verify each of the tests it produces individually, because at the moment we verify the entire json file and it's not simple to detect which one of the included tests was the one that failed.

### CODE REVIEW

**Comment by lightclient** [comment]
@marioevz I made a bit of a modification to follow the `go test --run {regexp}` style a little more closely. Let me know if this change looks okay to you.

**Comment by marioevz** [comment]
Thanks for the help @lightclient ! It looks fine to me but I'm tagging @danceratopz since he's working on the feature that uses this change.

**Review by lightclient — APPROVED** [review]
looks like 👍 from Dan too

**Comment by danceratopz** [comment]
> looks like 👍 from Dan too

Yup, works nicely on our side, thanks!

**Pull request merged**
