### PR TITLE
Add flag to not reinject stale txns after reorg

### PR DESCRIPTION
**Pull request by fxfactorial**
EDIT: Please see this twitter thread for context: https://twitter.com/eyalmarkov/status/1399740841921556485

### CODE REVIEW

**Comment by rjl493456442** [comment]
What's the specific reason for this feature?

**Comment by joehawary** [comment]
> What's the specific reason for this feature?

https://twitter.com/eyalmarkov/status/1399740841921556485

**Comment by rjl493456442** [comment]
Injecting the reorged transactions is necessary in lots of normal cases.

For the private transaction, whenever the specific miner mines this transaction in the block, it's not private anymore. We can't fix it.

**Comment by thegostep** [comment]
Uncles being reinserted into the txpool is expected behavior - I agree, the transactions are no longer private at that point.

My concern is that regular transactions which were not included in an uncle are also leaked to the txpool on a re-sync.

**Comment by joehawary** [comment]
> Injecting the reorged transactions is necessary in lots of normal cases.
> 
> For the private transaction, whenever the specific miner mines this transaction in the block and sends this block out, it's not private anymore.

I think you might be missing the edge case

**Comment by karalabe** [comment]
> My concern is that private transactions which were not included in an uncle are also leaked to the txpool on a re-sync.

What does that mean? What does a resync mean?

**Comment by karalabe** [comment]
As @rjl493456442 said, we only pull txs back into the pool from blocks that have been reorged (published, were canonical, became side forks). Those blocks are public for all and will be pulled back into everyone's pools.

**Comment by karalabe** [comment]
Note, there's no notion of private txs in Geth. We maintain a set of txs given to us either via P2P or RPC, and we will share that set with others in the network.

**Pull request closed without merging**
