### PR TITLE
ethclient: add GetProof method

### PR DESCRIPTION
**Pull request by p4u**
Exposes EIP 1186 eth_getProof method to ethclient https://github.com/ethereum/EIPs/issues/1186

### CODE REVIEW

**Comment by MariusVanDerWijden** [comment]
Rel: https://github.com/ethereum/go-ethereum/pull/21738
Imo instead of adding this to the ethclient we should create a seperate interface for all geth specific methods

**Comment by p4u** [comment]
Yeah, that makes sense. However it would require a refactor and a big effort. I'd suggest to incorporate mean-while this implementation or else we could return a byte array from `json.Marshal()` in order to keep the caller away from the internal `ethapi.AccountResult` type

**Comment by fjl** [comment]
I don't want to add a temp workaround. The refactoring is not that large, we just need someone to get this gethclient package started and add the one method they want. @fxfactorial already offered to do it in #21738 in order to get a wrapper for the eth_call with overrides. Once that's in, we can add GetProof as well.

**Comment by p4u** [comment]
fine, thanks.

**Pull request closed without merging**
