### PR TITLE
Micahaza ethereum light statistics

### PR DESCRIPTION
**Pull request by micahaza**
LES protocol measurements

Wiki: https://github.com/micahaza/go-ethereum/wiki/LES-protocol-measurements
Feel free to contact me if you have any questions.

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: fd4080aac2c421659630e8bbfe1fabd335924d0c
  * Commits must be prefixed with the package(s) they modify

 * Commit: 6c27e78ad9cbd05cfdebb76ca378293ab41bdf7c
  * Commits must be prefixed with the package(s) they modify

 * Commit: 3671bc4da5106c601e6da05a9a4399fbd7b4c95e
  * Commits must be prefixed with the package(s) they modify

 * Commit: 7d0976481d6c452cd98e14697b4663c282950c81
  * Commits must be prefixed with the package(s) they modify

 * Commit: c380878318aa3b24315f409355faa439e90c4e41
  * Commits must be prefixed with the package(s) they modify

 * Commit: f1f79e184dec2435cb0649fff9cc87ff58053ad2
  * Commits must be prefixed with the package(s) they modify

 * Commit: f0626d74b590224f89ca0b7548667af775794bba
  * Commits must be prefixed with the package(s) they modify

 * Commit: 1b05a87b2f4f5c33b2624b6d94ffe850c13856d6
  * Commits must be prefixed with the package(s) they modify

 * Commit: 4dd1d345b9078f3baa2eaf4db21e6ccf7b758e5f
  * Commits must be prefixed with the package(s) they modify

 * Commit: 195a5f291cfaad883e2fa7dac77ed261a7222a93
  * Commits must be prefixed with the package(s) they modify

 * Commit: 7074ad20ae48991c9b1374411ae85fdc19e2efa3
  * Commits must be prefixed with the package(s) they modify

 * Commit: 5597b61bb181a9e5db34c403d91edf7e01d85a82
  * Commits must be prefixed with the package(s) they modify

 * Commit: 6bc5e82df74ba5c790360c50c1a9e26e166bbdf8
  * Commits must be prefixed with the package(s) they modify

 * Commit: e94c73fb4906cf02a3682ad7bb634d4ce0475e65
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: fd4080aac2c421659630e8bbfe1fabd335924d0c
  * Commits must be prefixed with the package(s) they modify

 * Commit: 6c27e78ad9cbd05cfdebb76ca378293ab41bdf7c
  * Commits must be prefixed with the package(s) they modify

 * Commit: 3671bc4da5106c601e6da05a9a4399fbd7b4c95e
  * Commits must be prefixed with the package(s) they modify

 * Commit: 7d0976481d6c452cd98e14697b4663c282950c81
  * Commits must be prefixed with the package(s) they modify

 * Commit: c380878318aa3b24315f409355faa439e90c4e41
  * Commits must be prefixed with the package(s) they modify

 * Commit: f1f79e184dec2435cb0649fff9cc87ff58053ad2
  * Commits must be prefixed with the package(s) they modify

 * Commit: f0626d74b590224f89ca0b7548667af775794bba
  * Commits must be prefixed with the package(s) they modify

 * Commit: 1b05a87b2f4f5c33b2624b6d94ffe850c13856d6
  * Commits must be prefixed with the package(s) they modify

 * Commit: 4dd1d345b9078f3baa2eaf4db21e6ccf7b758e5f
  * Commits must be prefixed with the package(s) they modify

 * Commit: 195a5f291cfaad883e2fa7dac77ed261a7222a93
  * Commits must be prefixed with the package(s) they modify

 * Commit: 7074ad20ae48991c9b1374411ae85fdc19e2efa3
  * Commits must be prefixed with the package(s) they modify

 * Commit: 5597b61bb181a9e5db34c403d91edf7e01d85a82
  * Commits must be prefixed with the package(s) they modify

 * Commit: 6bc5e82df74ba5c790360c50c1a9e26e166bbdf8
  * Commits must be prefixed with the package(s) they modify

 * Commit: e94c73fb4906cf02a3682ad7bb634d4ce0475e65
  * Commits must be prefixed with the package(s) they modify

 * Commit: 7020530eb9fe6607563fc8407b6ac327c4a73d94
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by micahaza** [comment]
Documentation updated: https://github.com/micahaza/go-ethereum/wiki/LES-protocol-measurements

**Comment by karalabe** [comment]
Closing this as imho not the correct approach. The swarm team have been working a lot on metrics gathering and light clients could eventually be take towards that direction.

**Pull request closed without merging**
