### PR TITLE
whisperv6: this part return nil will be better clean

### PR DESCRIPTION
**Pull request by DavidYangNO1**

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 420c3ee70f2a55c2aa36f5afcbeb4de1ff8b3ac3
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 420c3ee70f2a55c2aa36f5afcbeb4de1ff8b3ac3
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by gballet** [comment]
@DavidYangNO1 does that come out of a given lint tool?

**Comment by gballet** [comment]
No response, closing this issue.

**Pull request closed without merging**
