### PR TITLE
eth/tracers: change revert reason to return data

### PR DESCRIPTION
**Pull request by libotony**
I would propose changing the tracer `revertReason` to `returnData` which includes reason, and it is also a way to supply the tx's returned data in the API.

### CODE REVIEW

**Comment by s1na** [comment]
But output and error are already returned as part of `callTracer`. If efficiency is a concern one option I can think of is to allow `callTracer` an option to process or not process the internal calls. Then we can add a `revertReason` field to it and remove the extra tracer.

**Comment by libotony** [comment]
> But output and error are already returned as part of `callTracer`. If efficiency is a concern one option I can think of is to allow `callTracer` an option to process or not process the internal calls. Then we can add a `revertReason` field to it and remove the extra tracer.

As stated in #25265, the only concern of this kind of tracer is efficiency. But I am going to vote this since it's simple to implement rather than adding options to call tracers. The options is already in the codebase but I thought it might be complicated to have multiple types of options.

BTW, I was having this idea for some time,but at that moment I changed to use call tracer. I would like hear your thoghts.

**Comment by libotony** [comment]
I also have a second option upon decoding the revert reason. It's better decoding outside of `geth`.

**Comment by s1na** [comment]
> The options is already in the codebase but I thought it might be complicated to have multiple types of options.

To be clear I'm not asking you to do this change. This is a change I've considered for a while to allow tracer-specific config. This would be a clear use-case for it. I'll go ahead and open a PR for that. Then we can compare the two approaches.

**Comment by s1na** [comment]
So, I have a patch which adds the revert reason to the call tracer: https://github.com/s1na/go-ethereum/tree/calltracer/revert. It builds on #25430 which adds a `onlyTopCall` option to call tracer. When this is set, the tracer doesn't process any of the sub-call, bringing the performance close to the tracer implemented in this PR. Please give it a try and see if it fits your needs. Here's an example of how to invoke:

```console
debug.traceTransaction("0xcaca", { tracer: "callTracer", tracerConfig: { onlyTopCall: true } })
```

**Comment by libotony** [comment]
> So, I have a patch which adds the revert reason to the call tracer: https://github.com/s1na/go-ethereum/tree/calltracer/revert. It builds on #25430 which adds a `onlyTopCall` option to call tracer. When this is set, the tracer doesn't process any of the sub-call, bringing the performance close to the tracer implemented in this PR. Please give it a try and see if it fits your needs. Here's an example of how to invoke:
> 
> ```
> debug.traceTransaction("0xcaca", { tracer: "callTracer", tracerConfig: { onlyTopCall: true } })
> ```
> 
> EdIt: also cc'ing @fanbsb who wrote the original `revertReasonTracer`.

Great, this meets my needs! I have taken a look at your implementation in your branch `calltracer/revert` and I have some suggestions:
+ strongly advice decode reason  outside
+ if reason needs to stay, the error from `abi.UnpackRevert` is recommended be omitted since someone can just `revert(bytes)` and it can not be unpacked by `string`
+ how about rename `tracerConfig` to `config`, since it's already inside the `tracer` context

**Comment by libotony** [comment]
BTW, feel free to close this once #25430 is merged

**Comment by fanbsb** [comment]
It's good to see the discussion here, I agree what the new PR https://github.com/ethereum/go-ethereum/pull/25430 does, because it doesn't break the exist function behavior.

Again in my PR https://github.com/ethereum/go-ethereum/pull/25265, the key point is not efficiency, it's the purpose of the tracer, call tracer return all the raw data to user while revertreason give the human readable string (either evm error or abi error) to user/developer.

**Pull request closed without merging**
