### PR TITLE
eth/tests: implement basic test for tracing

### PR DESCRIPTION
**Pull request by holiman**
Related to https://github.com/ethereum/go-ethereum/issues/20063 . This PR implements a testcase which would have found the issue, and can be extended to further verify our js-tracers if needed.

### CODE REVIEW

**Comment by holiman** [comment]
Move this file to core.vm instead

**Comment by holiman** [comment]
Todo: rebase and merge when green

**Comment by holiman** [comment]
Rebased. @fjl thumb up?

**Comment by fjl** [comment]
Closing because @rjl493456442 added much more comprehensive tracing tests in #22161

**Pull request closed without merging**
