### PR TITLE
p2p/enode: allow DNS names in enode URLs

### LINKED ISSUE #18340: Why does the enode nodeId information not support the domain name?
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

### PR DESCRIPTION
**Pull request by dipingxian2**
Add "net.LookupIP()" function to support hostname when we add enode by hostname:port

Fixes #18340

### CODE REVIEW

**Comment by fjl** [comment]
Non-support of DNS names in enode URLs is a design choice. Can you explain why you want this change?

**Comment by dipingxian2** [comment]
> Non-support of DNS names in enode URLs is a design choice. Can you explain why you want this change?

yes, I want to support DNS name because:
     1) The old version of geth  support FQDN,  when we update  geth to the latest version, we failed, admin.addPeer() return "invalid IP address". 
     2)In the kubernetes environment, you know the pod's ip is flexible(pod is a kind of docker container),  we only can use service name to find the the pod(geth run as docker container in the pod). the service is FQDN(hostname)
     3) In my opinion, my change is hurtless :)
BTW, I‘m also curious, why we design to Non-support of DNS 
thanks~

**Comment by dipingxian2** [comment]
who can help me to review this commit, or give me a reason if deny

**Comment by fjl** [comment]
We chose not to resolve host names in those URLs because DNS resolution is a privacy risk. I understand that DNS would be more convenient for cloud setups. 

> 1) The old version of geth support FQDN, when we update geth to the latest version, we failed, admin.addPeer() return "invalid IP address".

Which version was that?

**Comment by dipingxian2** [comment]
> We chose not to resolve host names in those URLs because DNS resolution is a privacy risk. I understand that DNS would be more convenient for cloud setups.
> 
> > 1. The old version of geth support FQDN, when we update geth to the latest version, we failed, admin.addPeer() return "invalid IP address".
> 
> Which version was that?

Sorry, it's my mistake, the quorum (which is fork from go-ethereum, I guess you know) added it since v2.11
BTW,  only support IP not FQDN for privacy risk is reasonable, but in my opinion, for static-nodes.json or add static node usually used in private or locally environment,  DNS server is safe normally.

**Comment by adamschmideg** [comment]
@fjl will write how we'd like to see this implemented instead to avoid security risks.

**Comment by holiman** [comment]
We discussed this today, and agree that we would accept a PR that, 

- Does lookup on static nodes during startup, and, 
- Does lookup of names at the time they enter via `admin.addPeer`. 

The drawback will be that peers added through `addPeer` will 'stick' on ip, and if the ip changes, the user will have to call `addPeer` with the dns name again. Which is ok. 

I'm not sure if this one fullfills these.... ? Assigning to felix

**Comment by salanfe** [comment]
thx ! this feature makes it easier for us to use geth in Kubernetes 👍

**Comment by Roninchen** [comment]
thx! but what's the  version fix this?

**Comment by fjl** [comment]
v1.9.3

**Comment by MANOJKUMARCH** [comment]
This is a great feature to use DNS names in place of IP addresses. 
But is the connection execting any ssl or just a DNS with http is accepted for the connection of peers?

**Pull request merged**
