### PR TITLE
p2p/protocols: devp2p protocol abstraction

### PR DESCRIPTION
**Pull request by zelig**
Package protocols is an extension to p2p. It offers a user friendly simple way to define
devp2p subprotocols by abstracting away code that implementations would typically use.

The package provides a standard protocol peer object of type protocols.Peer initialised from
a p2p.Peer, a p2p.MsgReadWriter (the arguments passed to p2p.Protocol#Run
and a protocols.CodeMap.

Allowing the p2p.Protocol#Run function to construct this peer allows passing it to arbitrary
service instances sitting on peer connections. These service instances can encapsulate vertical slices
of business logic without duplicating code related to protocol communication.

```
*    registering multiple handler callbacks for incoming messages
*    automate assigments of code indexes to messages
*    automate RLP decoding/encoding based on reflecting
*    provide the forever loop to read incoming messages
*    standardise error handling related to communication
*    TODO: automatic generation of wire protocol specification for peers
```

  see the possibly obsolete #2254 for the peer management/connectivity related aspect)

The PR includes `p2p/testing` subpackage that provides a powerful framework to test
fairly complex subprotocol message exchanges in a multipeer session
The test for `p2p/protocols` demonstrates how to use this subpackage.

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Mon Aug 29 14:25:28 UTC 2016_

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: f29201b7660ad4d6cd1f8b3945987b77b6c95a24
  * Your commit message body contains a line that is longer than 72 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by zelig** [comment]
@fjl I implemented pretty much everything you suggested  and more

* does not depend on errs package which can now be removed (noone uses it)
* std protocol and Node-like service constructor eliminated
* peerPool eliminated
* composition-based use via the Peer#Run function
* CopeMap-based calculation 
* added Handshake call beside Register for much nicer handling of Handshakes
* major improvement of p2p/testing supporting mulltipeer sessions with parallel messages
* Disconnect terminates the read loop directly in testing so easy to implement Expect or Disconnect
* ...

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: ed6a4c64aab842f62e02dc3dc9a6341c854a3b39
  * Your commit message body contains a line that is longer than 72 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 23973c994d262ced846bd9c6fda9f1dd2cc60cc4
  * Your commit message body contains a line that is longer than 72 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Pull request closed without merging**
