### PR TITLE
rpc: add receiptRoot to getBlock* responses

### PR DESCRIPTION
**Pull request by fjl**
As requested by @PhiStr90 in #1679, this PR adds the receipt root to block responses.

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Sat Aug 29 09:15:55 UTC 2015_

**Comment by obscuren** [comment]
:+1: funny enough I had already made those changes but never submitted the PR 🌊🌞

**Comment by karalabe** [comment]
LGTM :+1: , but can't we somehow flatten that gigantic MarshalJSON method. It is extreme code duplication just for swapping the type of a single field. Maybe we could add a custom marshaller to the UncleRes field and have the transactions field a custom type containing the flag whether full is needed or not and a custom marshaller on that too. It would be a lot less shorter. @bas-vk ?

**Comment by fjl** [comment]
@karalabe we'll address that later

**Comment by karalabe** [comment]
@fjl Sure, it was just a memo.

**Pull request merged**
