### PR TITLE
accounts/abi: estimate gas before send transaction

### PR DESCRIPTION
**Pull request by nkbai**
for  abigen generated code,
when start a new transaction,it usually do the follows:
1)  call BoundContract.Transact
2) call bind.WaitMined to wait success of this transaction

if the first step sends an invalid transaction,for example a contract call that  always fails. then the second step will be waiting forever.
for example: 
registry is a abigen wraper, addtoken is a contract transaction call.
```go
      tx, err := this.registry.AddToken(TransactOpts, tokenAddress)
	if err != nil {
		return
	}
	receipt, err := bind.WaitMined(GetCallContext(), ethClient, tx)
	if err != nil {
		return
	}
```

### CODE REVIEW

**Comment by nkbai** [comment]
sorry ,i don't know how to cancel my preview pull request.

**Comment by Magicking** [comment]
AFAIK GasLimit is lazy calculated and you just need to nil TransactOpts.Nonce to reset it !

Also, a normal processing for a transaction imply to be picked-up and mined so you could theoretically wait for ever.

**Comment by nkbai** [comment]
when contract tx call,if it give a ver large gaslimit, it's problaly  a error.
if i call this function from remix,it gives a error:
transact to Registry.addToken errored: Gas required exceeds limit: 3000000.  An important gas estimation might also be the sign of a problem in the contract code. Please check loops and be sure you did not sent value to a non payable function (that's also the reason of strong gas estimation)

I test that:
if i set  nil TransactOpt.GasLimit, it will calculate a very large gaslimit. and it's a error, but EstimateGas don't think it's a error,

for example ,
if I call addtoken,and it failed because of a revert(),
then EstimateGas  will calculate a very large gaslimit,  but it's not an error, and the user will not detect it , and have to wait forever.
but if the user EstimateGas  before,and get  a very large gas, he will relealize that it's an error

what i want is ,if EstimateGas   is too large ,reports an error.

I use the code generated from abigen, if I want to avoid this trap, I have to estimateGas myself,before call the generated function

**Comment by nkbai** [comment]
and there is another question, if i send this tx ,and get a tx hash,
but if i call WaitMined for this tx, it will report error  "Receipt retrieval failed , hash not exists"
this tx is an invalid tx,but user cannot get an error response. and will wait a not exist tx forever.

**Comment by nkbai** [comment]
what i want to express is :
i specify  TransactOpts.GasLimit=300000,
if transactor.EstimateGas gets a too large gaslimit(for example 22177093129), BoundContract'transact should tell the caller there is an error. because there must be an error.

**Comment by nkbai** [comment]
waitmined print the following informations:
```
TRACE[12-28|13:20:23]                                          msg="sending {\"jsonrpc\":\"2.0\",\"id\":12,\"method\":\"eth_getTransactionReceipt\",\"params\":[\"0x1cc3ef3f561caadedcf1d0ac423312da63dfdc59adfd5abac134dbd193401def\"]}"
TRACE[12-28|13:20:23]                                          msg="<-readResp: response {\"jsonrpc\":\"2.0\",\"id\":12,\"result\":null}"
TRACE[12-28|13:20:23] Receipt retrieval failed                 hash=1cc3ef…401def err="not found"
```

**Comment by karalabe** [comment]
On current master (not sure about 1.7.3, but should be the same) gas estimation returns an error if the transaction will always fail. So even code generated by `abigen` should faile when calling `this.registry.AddToken(TransactOpts, tokenAddress)` if the transaction is invalid. As such, I don't think the bug you are reporting is still present.

Now, if you explicitly specify that you want the transaction to run with gas X, why do you think Geth should override and run with Y?

**Comment by nkbai** [comment]
my geth version 1.7.3-unstable

sendTransaction does't report an error for a failed contract call, and return a valid tx hash.
but when i call WaitMined with this tx hash, it prints this  hash not found in the console repeatly forever.

this is an invalid tx,but sendTransaction  doesn't return an error.
my problem is  how to detect this error.

**Comment by nkbai** [comment]
this.registry.AddToken(TransactOpts, tokenAddress) 
this call doesn't return an error  whenever TransactOpts.GasLimit is nil or not

**Comment by karalabe** [comment]
Please try with latest master on how it behaves. It really should fail estimation if the transaction always fails (and you don't explicitly specify a gas limit).

**Comment by nkbai** [comment]
@karalabe  
thanks  for your advice,
i update my geth to the lastest version.
this.registry.AddToken , this call failed . but  this tx can be found on blockchain. 
for example ,  use 
 eth.getTransaction("0x1df4a3686072c15d95722f5b21ba75b508268d7061f0a3b856ba9d71859fe2e9")
will get :
```
{                                                                                                
  blockHash: "0x41c959ead445f20401f2b1637fcca9a19e7ff28116305d6eadf4c362629d3496",               
  blockNumber: 16642,                                                                            
  from: "0x1a9ec3b0b807464e6d3398a59d6b0a369bf422fa",                                            
  gas: 3141592,                                                                                  
  gasPrice: 20000000000,                                                                         
  hash: "0x1df4a3686072c15d95722f5b21ba75b508268d7061f0a3b856ba9d71859fe2e9",                    
  input: "0x11da60b4",                                                                           
  nonce: 76,                                                                                     
  r: "0x7f2f10f825b512648f5a9507f0cba70db736c84421e780bbfe0dde3f487e415e",                       
  s: "0x766276cbcf455aed55deff12e1e2d84f39a20130ddaff33d145f293f46a5b8a6",                       
  to: "0x7ceb981180232322e608381629ec2f65f64700ce",                                              
  transactionIndex: 0,                                                                           
  v: "0x1c",                                                                                     
  value: 0                                                                                       
}                                                                                                
```
of course ,this is right  and should fail. 
but why not  make this tx fail before send? it saves  gas  for a ealier failure.

**Comment by nkbai** [comment]
after  search the usage of  "(c *BoundContract) transact" , i found it usally appear at code that is generated by abigen.
this is my usage too.

**Comment by karalabe** [comment]
But I'm assuming you explicitly specified a gas value (PI seems awfully not random ;) ), in which case Geth will not run the gas estimation and will not see that the transaction always fails.

I.e. Instead of mucking around with gas estimation, maybe the real issue here is that Geth should deny the transaction altogether if it would fail. That's a valid request, but it opens up an interesting issue that if you have an offline machine, you won't be able to create transactions with it because Geth will think they always fail (due to not being synced at all).

**Comment by nkbai** [comment]
i'm using a private chain to develop , tx willnot fail if i don't start mining.
this tx will be put into pending tx groups.

these two questions are different, for a must fail tx, the generated code should let me known and give me a choice.

**Comment by nkbai** [comment]
maybe a pr for generating code for golang bind  seems better for this question

**Comment by gballet** [comment]
@nkbai do you still want us to take a look at this PR and are you still interested in finishing up?

**Comment by nkbai** [comment]
@gballet  sorry, I have fixed my problem using vendor.

**Comment by gballet** [comment]
Ok thanks. We'll be closing it then, re-open it if it turns out you need it after all.

**Pull request closed without merging**
