### PR TITLE
resolve bzzr GET requests from ens/path to manifest

### LINKED ISSUE #3476: swarm: bzzr: doesn't properly parse GET requests
#### Expected behaviour
When you call up a swarm asset with bzzr you expect to get it served straight to you. 
For example, here is the swarm landing page manifest:
http://swarm-gateways.net/bzzr:/theswarm.test/?content_type=text/plain

#### Actual behaviour

When you call a submanifest however (like the 'i' submanifest of theswarm.test) we get an error:
http://swarm-gateways.net/bzzr:/theswarm.test/i?content_type=text/plain
no contract code at given address

#### Steps to reproduce the behaviour

Load any swarm asset with bzzr: that is specified by more than just a name or hash i.e. bzzr:/HASH/path/to/something

Example http://swarm-gateways.net/bzzr:/theswarm.test/i?content_type=text/plain

#### Note

Either bzzr should give a proper error message explaining how it only accepts a hash or name and nothing else, or (better) it should server whatever swarm asset is being referenced.

### PR DESCRIPTION
**Pull request by nolash**
fixes #3476

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: b520d7caa5f8a3307559db245974f0243b7908fd
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by zelig** [comment]
great @nolash. Yes this is a good way. 
Just edit the title and description to reflect the issue.
you can simply put "fixes #3476" in the description
then we get better cross-references between issue and PR 
plus also achieve that the issue is auto-closed once your PR is merged.

**Comment by nolash** [comment]
@zelig Cool. However, I can only find a title, no description. Do you with description mean where it now says "Would like to fix issue #3476"? Or do you mean the comment I had to add when adding the PR?

**Comment by zelig** [comment]
yes the main comment when you add the PR

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: b520d7caa5f8a3307559db245974f0243b7908fd
  * Commits must be prefixed with the package(s) they modify

 * Commit: 922f1055a4843443b3be2b392a6588033b1f5581
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: b520d7caa5f8a3307559db245974f0243b7908fd
  * Commits must be prefixed with the package(s) they modify

 * Commit: 922f1055a4843443b3be2b392a6588033b1f5581
  * Commits must be prefixed with the package(s) they modify

 * Commit: 90daa7a68b0568ddf8a65fb644cdaddd8254a7b6
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: b520d7caa5f8a3307559db245974f0243b7908fd
  * Commits must be prefixed with the package(s) they modify

 * Commit: 922f1055a4843443b3be2b392a6588033b1f5581
  * Commits must be prefixed with the package(s) they modify

 * Commit: 90daa7a68b0568ddf8a65fb644cdaddd8254a7b6
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by nolash** [comment]
@zelig I'm getting a lot of complaints from the bots policing commit formats etc, not sure how I can resolve it.

Anyway, the server_test.go seems to work, and running the updated server locally by me successfully resolves http://127.0.0.1:8500/bzzr:/theswarm.eth/images?content_type=text/plain

Changes are:
1. cleaned up the "path-or-no-path" condition in the GET case in **swarm/api/http/server.go**
2. removed the `nil` assignment of entry when last path index was reached in the `loadSubtrie` recursion in `*manifestTrie.findPrefixOf`(swarm/api/manifest.go), which was causing the not found error.

Caveat: I don't know what the `nil` in 2 was supposed to do/prevent in the first place. Do you?

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: b520d7caa5f8a3307559db245974f0243b7908fd
  * Commits must be prefixed with the package(s) they modify

 * Commit: 922f1055a4843443b3be2b392a6588033b1f5581
  * Commits must be prefixed with the package(s) they modify

 * Commit: 90daa7a68b0568ddf8a65fb644cdaddd8254a7b6
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: b520d7caa5f8a3307559db245974f0243b7908fd
  * Commits must be prefixed with the package(s) they modify

 * Commit: 922f1055a4843443b3be2b392a6588033b1f5581
  * Commits must be prefixed with the package(s) they modify

 * Commit: 90daa7a68b0568ddf8a65fb644cdaddd8254a7b6
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by nolash** [comment]
I'd forgotten that I'd added public access to the parsing method in **swarm/api/api.go** before. Dunno if that's too impertinent?

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: b520d7caa5f8a3307559db245974f0243b7908fd
  * Commits must be prefixed with the package(s) they modify

 * Commit: 922f1055a4843443b3be2b392a6588033b1f5581
  * Commits must be prefixed with the package(s) they modify

 * Commit: 90daa7a68b0568ddf8a65fb644cdaddd8254a7b6
  * Commits must be prefixed with the package(s) they modify

 * Commit: ea88565fad275cc9520f6d6fb0a3c5f4b3f654df
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: b520d7caa5f8a3307559db245974f0243b7908fd
  * Commits must be prefixed with the package(s) they modify

 * Commit: 922f1055a4843443b3be2b392a6588033b1f5581
  * Commits must be prefixed with the package(s) they modify

 * Commit: 90daa7a68b0568ddf8a65fb644cdaddd8254a7b6
  * Commits must be prefixed with the package(s) they modify

 * Commit: ea88565fad275cc9520f6d6fb0a3c5f4b3f654df
  * Commits must be prefixed with the package(s) they modify

 * Commit: 8a96f1e8807cfbd8c8e798a311a30a8c1d1b4f1f
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: b520d7caa5f8a3307559db245974f0243b7908fd
  * Commits must be prefixed with the package(s) they modify

 * Commit: 922f1055a4843443b3be2b392a6588033b1f5581
  * Commits must be prefixed with the package(s) they modify

 * Commit: 90daa7a68b0568ddf8a65fb644cdaddd8254a7b6
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: b520d7caa5f8a3307559db245974f0243b7908fd
  * Commits must be prefixed with the package(s) they modify

 * Commit: 922f1055a4843443b3be2b392a6588033b1f5581
  * Commits must be prefixed with the package(s) they modify

 * Commit: 90daa7a68b0568ddf8a65fb644cdaddd8254a7b6
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: b520d7caa5f8a3307559db245974f0243b7908fd
  * Commits must be prefixed with the package(s) they modify

 * Commit: 922f1055a4843443b3be2b392a6588033b1f5581
  * Commits must be prefixed with the package(s) they modify

 * Commit: 90daa7a68b0568ddf8a65fb644cdaddd8254a7b6
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by zelig** [comment]
obsoleted by #3615

**Review by Hsenaai — COMMENTED** [review]
🙏

**Review by Hsenaai — COMMENTED** [review]
🌹

**Pull request closed without merging**
