### PR TITLE
log: using maps.Clone

### PR DESCRIPTION
**Pull request by cuiweixie**

### CODE REVIEW

**Review by rjl493456442 — COMMENTED** [review]
Can you estimate how many pull requests like this will be submitted?

Personally I think the change is good, but it's really annoying to review this kind of changes a few times a day.

**Comment by cuiweixie** [comment]
> Can you estimate how many pull requests like this will be submitted?
> 
> Personally I think the change is good, but it's really annoying to review this kind of changes a few times a day. 

I am still reading the code. may be I can send others in one pr, if I can find more.

**Comment by rjl493456442** [comment]
You can probably submit a pull request per package or so. Multiple pull requests are fine if the package is huge!

**Comment by cuiweixie** [comment]
actually, I am thinking about using static analyzer to find all this cause one time, but I has not time to work in static analyzer in workdays. May be do it in weekends.

**Comment by rjl493456442** [comment]
You don't have to put all the changes in a single pull request, as it will touch too many files. Usually we prefer to have a granularity of one PR per package.

**Review by MariusVanDerWijden — APPROVED** [review]

**Pull request merged**
