### PR TITLE
p2p/simulations: replace reflect.DeepEqual with maps.Equal

### PR DESCRIPTION
**Pull request by cuiweixie**

### CODE REVIEW

**Comment by rjl493456442** [comment]
Personally I think it's fine to keep using `reflect`, otherwise there are too many changes required.

**Comment by cuiweixie** [comment]
> Personally I think it's fine to keep using `reflect`, otherwise there are too many changes required.

It can improve a bit performance.  we can change it one by one.

**Comment by rjl493456442** [comment]
For sure it might have some performance benefits. But i am not sure it's worthwhile since it's testing anyway.

**Comment by cuiweixie** [comment]
It's easy to write a static analyzer to find out all the case. if we do it that way it may be ok. What do you think about that? run all unittest is slow enough now.

**Comment by fjl** [comment]
We don't have the capacity to review a lot of these changes. There is no benefit for us since the tests have OK performance and improving the performance is a non-goal. @cuiweixie Please do not submit more changes like this unless it's in non-test code and the performance difference can be shown to matter *in practice*.

**Pull request closed without merging**
