### PR TITLE
[swarm] Fix possible reentrancy bug in chequebook contract

### PR DESCRIPTION
**Pull request by nagydani**
A malicious beneficiary contract could recursively call back the chequebook contract's send method with the same cheque before the cashed amount has been updated and thus withdraw the amount several times.

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Mon Aug 29 14:08:20 UTC 2016_

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 3c6cdf882151317f181c1789738a600a40ca41cf
  * Commit subjects should be kept under 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by fjl** [comment]
Please submit this to develop instead.

**Comment by fjl** [comment]
you also need to regenerate the contract binding by running go generate ./contracts/chequebook

**Pull request closed without merging**
