### PR TITLE
cmd/geth, eth: (typo) change whitelist terms to enforcelist

### PR DESCRIPTION
**Pull request by baptiste-b-pegasys**
split of #23290
thanks to @karalabe for the prior review

### CODE REVIEW

**Review by gballet — CHANGES_REQUESTED** [review]
Again, you can't use an infinitive as an adjective. EnforcementList would work (at a grammatical level).

Except Whitelist and Enforcement lists do not have the same meaning: one of them implies force, while the other implies authorization. AuthorizationList has the correct meaning.

And PR like these should not be merged: it doesn't add any technical value and clobbers the git history. When someone opens a PR to add technical value, we'll ask them to use these inclusive terms then.

**Comment by baptiste-b-pegasys** [comment]
Hello, how do you think this work can be validated? As typo or should it be closed?

**Comment by MariusVanDerWijden** [comment]
Authorization list does not convey the same meaning as whitelist.
I think EnforcedBlocks or something similar (RequiredBlocks, MandatoryBlocks, ... ) might be better.
Also this PR is outdated and needs to be rebased

**Comment by karalabe** [comment]
There's another PR being discussed that does something along eth.requiredBlocks. That was deemed goon enough so it supersedes this PR.

**Pull request closed without merging**
