### PR TITLE
Bigcook12345

### PR DESCRIPTION
**Pull request by bigcook12345**
I'm hoping, with what ever I have been missing? The changes made that have been and were necessary to be applied in the correct format. Skipping steps was not intended, just doing my best to cross all of my "t's",  & dot all of my ""i's" nothing more and or less...

This process surely was not easy by any means. But putting in the work as recommended...

### CODE REVIEW

**Comment by MariusVanDerWijden** [comment]
I'm not sure what you are trying to archive here

**Comment by bigcook12345** [comment]
So you close the request before even asking 🤔🤔🤔

**Comment by bigcook12345** [comment]
Also a valid reason for it..?

**Comment by MariusVanDerWijden** [comment]
Sorry I may have been to quick to close this. 
We do get a lot of spam pr's during hacktoberfest.
What are you trying to achieve with this PR?

**Comment by bigcook12345** [comment]
Marius

My sincere apologies for the late response to your request. 

Honestly, to try and understand what I do not yet understand...

"Hacktoberfest..?" I've never heard of the actual term..?

I have been navigating the site, for a bit longer than a year, & I am trying to actually learn how everything works step by step...

**Pull request closed without merging**
