### PR TITLE
eth/filters: subscribe ChainReorg events

### PR DESCRIPTION
**Pull request by jsvisa**
A simple implementation of https://github.com/ethereum/go-ethereum/issues/26953

And here is a simple client example:

```go
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"os"

	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/ethclient"
	"github.com/ethereum/go-ethereum/log"
)

var (
	provider = flag.String("rpc", "ws://127.0.0.1:8546", "rpc provider")
)

func main() {
	flag.Parse()
	log.Root().SetHandler(log.LvlFilterHandler(log.LvlInfo, log.StreamHandler(os.Stdout, log.TerminalFormat(true))))

	client, err := ethclient.Dial(*provider)
	if err != nil {
		log.Crit("error creating client", "err", err)
	}
	defer client.Close()

	ctx := context.Background()
	ch := make(chan *types.Header)
	sub, err := client.SubscribeChainReorg(ctx, ch)
	if err != nil {
		log.Crit("failed to subscribe chainside event", "err", err)
	}
	defer sub.Unsubscribe()

	log.Info("Success subscribe ChainReorg")
LOOP:
	for {
		select {
		case err := <-sub.Err():
			log.Error("subscribe error", "err", err)
			break LOOP

		case e := <-ch:
			ef, _ := json.MarshalIndent(e, "", "  ")
			log.Info("reorg -->")
			fmt.Println(string(ef))
		case err := <-ctx.Done():
			log.Error("context error", "err", err)
			break LOOP
		}
	}
	close(ch)
}
```

> Subscribe with 

```bash
go run reorg.go -rpc xxx
```

> Some example output:

```bash
INFO [05-16|23:35:54.737] Success subscribe ChainReorg


INFO [05-17|00:35:02.198] reorg -->
{
  "parentHash": "0xf4a6cf72480f4f84a0be2db64b1480ec1022172f652ffafdabdc8482eec1821e",
  "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  "miner": "0x690b9a9e9aa1c9db991c7721a92d351db4fac990",
  "stateRoot": "0x43c89b7a6b65328c56fc47911dde4ff00705f668d7745f9dbe00712ef6c9eeab",
  "transactionsRoot": "0x6162b6db65a3e60bb00a9f550f0c14d7b5644fc9a2dae5ecb393f0abd2ba5399",
  "receiptsRoot": "0xb846ad0702fdf2b74c9569fa49bfed05bf64c53acaedc858fc525fef7e0a582d",
  "logsBloom": "0x1ba10482081c10d87918571a8f08894b9027230138921052020163555dc4754241365de0c136207084205a3a0b10a11532070003da0138c85064e00c152d980b800aba9a20711c282b0660cbc014677f29428046bc475ce04e901c7088682c217f21092d0340a90381c41680832098830010e0a0a9c16e68c884c4f48b78be72c020425144888b5a81cf01305f53040620080281cb4c0b8a4d25006ec01003d1ffcc51ca1a0ef1632a0900c0dc89448e05c0a282e5a34b695d48a68835302a414b2c02b20a479053a04210980041265bc17d038282122c74f452518a08006200a535e80eb9110868166428e1a6551a04845a02d03000147445a9125287287f44",
  "difficulty": "0x0",
  "number": "0x1079bc4",
  "gasLimit": "0x1c9c380",
  "gasUsed": "0xa24b5a",
  "timestamp": "0x64642127",
  "extraData": "0x627920406275696c64657230783639",
  "mixHash": "0x7c6a7a16af8749719f5bfdee24a1f91efa2386fb923e29aaa14a80c21fb3a374",
  "nonce": "0x0000000000000000",
  "baseFeePerGas": "0x931606255",
  "withdrawalsRoot": "0xfc8557f98bcd013b833c686683cf0780c193379feb29d27e064e3c732d4a0c8a",
  "excessDataGas": null,
  "hash": "0xafdf26616fe59929b1ac85733b525eaaceb7b94822d9058b922a64a691ee909c"
}
INFO [05-17|00:42:21.005] reorg -->
{
  "parentHash": "0x3d58851135b811edfbc26c82b8343f6919a76709fc1c077499e2499884da0290",
  "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  "miner": "0xebec795c9c8bbd61ffc14a6662944748f299cacf",
  "stateRoot": "0xfced68db87020b4f510c55a0963266b0201ee74b3a176f6610fde41aae6a15f5",
  "transactionsRoot": "0x2770e1899b04ebaa05ce366fd99e2de89e24edd3fb404d51dff21c674c9c604c",
  "receiptsRoot": "0xfe41971da8a78646254d0ee53f8437ca8818a6a5a438e300e7e297202462630c",
  "logsBloom": "0x2f250248482e40c90248122080411a61322ec58202028c414003a041b0a001565808a240e4619161c21203063120a5840a89ca5ca880a8c0261c8e6712a931b0118a8a1804182cadec2443ca8a5008a0101a0602005d2c051090f57f984a5803a2022230120210cfa148540419c4186da0129080481b04b0020164f20439680ca911a04e16404222164e004ca26a01422caa2c09a908401ca411024344107003ba09e1d6091a6802d10a42e59014054854402841c000494a4444860211b1000742b26842401014d45400e425042a146c5740bd07432e20141826d5a3a0052463041a200c898008847f844da0ab2849c0845487ba510800ee90c81817d4190c9c",
  "difficulty": "0x0",
  "number": "0x1079be6",
  "gasLimit": "0x1c9c380",
  "gasUsed": "0xfd1b5e",
  "timestamp": "0x646422d7",
  "extraData": "0xd883010b06846765746888676f312e31392e38856c696e7578",
  "mixHash": "0xf48ad139fde09d2b9bec8bec4d33bbbe8e5058c0e8c56bf91a9284b18a498888",
  "nonce": "0x0000000000000000",
  "baseFeePerGas": "0x94f0dd366",
  "withdrawalsRoot": "0x3c3ea92e5fd9732b648d319f59d97cbc2c8cc959d3b5650c47b4e686bf0459f3",
  "excessDataGas": null,
  "hash": "0xa3526448bdbb58f8f3ebc69a2020e41861e21a93a20f079d8bc53cfd6e751881"
}

```

### CODE REVIEW

**Review by holiman — COMMENTED** [review]
I'd prefer not to add this complexity unless there's a strong signal from users that this is indeed a desired feature.

**Comment by jsvisa** [comment]
> I'd prefer not to add this complexity 

Firstly, I don't understand why this is considered a complex logic. Could you please explain in more detail, or is there any information I'm missing, Thank you.

In my view, subscribing to the channel and passing the results to the client is all that needs to be done. 

**The current way to check reorg**

Currently, we can subscribe to `newHeads` channel to get the first new block, then lag X blocks and use an `eth_getBlockByNumber` RPC call to check if the block has undergone re-orged. To ensure that this is the longest block, we may need to query two or three times with intervals of 2X or 3X. This means we need to re-query N times for each block, which is quite complicated to implement and introduces additional RPC queries (according to our statistics, currently only about 0.4% of blocks undergo reorg).

**Why not wait for X blocks and then query?**

This approach might work for accounting transactions in exchanges (for example, waiting for 20 blocks), but it is too slow and too late for security companies that need to detect the latest data on the blockchain.

**Comment by dkatzan** [comment]
@jsvisa @holiman 
will be happy to use this feature as well
it will be super useful as a wallet-provider in order to properly track transactions being mined and forked

**Comment by fjl** [comment]
We still believe this API is unnecessary. If you want to detect reorg, you can simply check whether the new head event's parentHash matches the previous block. If it doesn't, there was a reorg. If you need access to the reorged blocks without requesting them, you should maintain a client-side cache of headers.

**Pull request closed without merging**
