### PR TITLE
all: define and enable the Berlin hard fork on all networks

### PR DESCRIPTION
**Pull request by karalabe**
Block number decisions: https://github.com/ethereum/pm/issues/248#issuecomment-782106181
Berlin hard fork details: https://github.com/ethereum/eth1.0-specs/blob/master/network-upgrades/berlin.md

### CODE REVIEW

**Comment by holiman** [comment]
LGTM, maybe with one little diff suggestion - would be good to remove as much yolov3 stuff as possible
```diff
diff --git a/eth/tracers/api.go b/eth/tracers/api.go
index 013f5d52dd..cfb41a7ec3 100644
--- a/eth/tracers/api.go
+++ b/eth/tracers/api.go
@@ -585,8 +585,8 @@ func (api *API) standardTraceBlockToFile(ctx context.Context, block *types.Block
 			chainConfig.BerlinBlock = berlin
 			canon = false
 		}
-		if yolov3 := config.LogConfig.Overrides.YoloV3Block; yolov3 != nil {
-			chainConfig.YoloV3Block = yolov3
+		if berlin := config.LogConfig.Overrides.BerlinBlock; berlin != nil {
+			chainConfig.BerlinBlock = berlin
 			canon = false
 		}
 	}
```

**Comment by karalabe** [comment]
I did add Berlin too there just the lines above :P Not sure if I can nuke it given that it accesses Yolo directly. I'm happy to remove support for Yolo. Should we also drop it for Berlin? Any particular reason to have this override?

**Comment by holiman** [comment]
Oops. 
Anyway, the reason to have it is to enable folks to pre-check, before Berlin, how a particular block would behave with the upcoming rules, and perform analysis. So far, I estimate that I'm the only one who's ever done so (which is why I'm not concerned about dropping yolov3), but it might be good to leave it in there if others wants to analyze things, as berlin draws closer.

**Comment by karalabe** [comment]
Removed Yolov3 from there. PTAL

**Review by Platinumwrist — COMMENTED** [review]
cmd/geth/config.go

**Pull request merged**
