### PR TITLE
Gas price fix

### LINKED ISSUE #23915: Transaction.GasPrice() is  error .  if transaction  is from  latest block .
```   
hash := "0x4923bf8bef127a0a988d598667560f2f334e48b84997dad1d89f07f49c486f42"
	txHash  := common.HexToHash(hash)
	tx,_,_ := client.TransactionByHash(context.Background(),txHash)
	log.Println(tx.GasPrice().String() , tx.Hash().String())
	//  tx.GasPrice()  IS  95657255940   NOT  66232681164

```

TXT

### PR DESCRIPTION
**Pull request by sbrajchuk**
Fixes #23915

### CODE REVIEW

**Comment by holiman** [comment]
I think the root problem is that it's inherently impossible to know the actual gasprice unless in the context of an actual block. The actual gas price is not an aspect of the tx. 

So if we put it into the tx as some sort of cache, it will maybe/probably work in most contexts, depending on what accessor you used to create/fetch the transaction. I am very unsure if this will improve the UX, or if it will just make it more quirky.

**Comment by karalabe** [comment]
Also the `gasPrice` method is used internally at various locations, so redefining it seems like a can of worms that will have unexpected breakages.

**Comment by fomotrader** [comment]
Maybe a dumb question on my part but would it not be better to use the last block or 2 to calculate the gasPrice? Etherscan displays `Base Fee Per Gas` that would be fairly accurate no?

**Comment by fjl** [comment]
I'm against this change. The meaning of `GasPrice` is not well-defined for EIP-1559 transactions, and this change makes it even shakier because the value returned now depends on where the transaction comes from.

We need to look into creating a new core/types function to compute the effective gas price of a tx in a block instead.

**Pull request closed without merging**
