### PR TITLE
core: fix TxPool crash when reorg head is not found in database

### PR DESCRIPTION
**Pull request by ucwong**

### CODE REVIEW

**Comment by ucwong** [comment]
image
It will be crashed when add is nil

**Comment by karalabe** [comment]
Can this case actually happen? How?

**Comment by ucwong** [comment]
image
Thank you for your reply, It is possible this method return nil value, if there is no block in rawdb with exact hash and number

**Comment by holiman** [comment]
I also don't think this can happen -- or if it does, it is evidence of a severe malfunction: we have reorged to a new head, but that head is not available in the database. 
I don't think we should silently ignore that, and if it actually does happen, we need to investigate the mechanics behind it.

**Pull request closed without merging**
