### PR TITLE
swarm/api: url scheme bzzh for getting hashes of swarm content

### PR DESCRIPTION
**Pull request by janos**
This PR implements bzzh scheme as described in issue ethereum#15238.

More discussion on this subject is on a related PR https://github.com/ethersphere/go-ethereum/pull/141.

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: d82ecbac22c4ffdbf29193d03fde87776886e84e
  * Commits must be prefixed with the package(s) they modify

 * Commit: b18003d99a382ead6d165ceb0419ba8329ea7e66
  * Commits must be prefixed with the package(s) they modify

 * Commit: 379040e22d31e8a23a4b568e3e194b1a741a21f2
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by homotopycolimit** [comment]
Did we agree on calling it bzzh instead of bzz-hash?
I forget. There was a suggestion to use bzz-hash instead of bzzh, bzz-raw instead of bzzr.

**Comment by janos** [comment]
@homotopycolimit yes, there was a suggestion, but I am not aware that it was decided. If there will be more url schemas in the future, a an approach with more descriptive ones can be used to avoid conflicts in naming them.

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: d82ecbac22c4ffdbf29193d03fde87776886e84e
  * Commits must be prefixed with the package(s) they modify

 * Commit: b18003d99a382ead6d165ceb0419ba8329ea7e66
  * Commits must be prefixed with the package(s) they modify

 * Commit: 379040e22d31e8a23a4b568e3e194b1a741a21f2
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by janos** [comment]
Closing this PR as new changes need to be approved here https://github.com/ethersphere/go-ethereum/pull/163.

**Pull request closed without merging**
