### PR TITLE
core/vm: make contract creation failed if address collisions

### PR DESCRIPTION
**Pull request by rjl493456442**
Implements [ethereum EIP689](https://github.com/ethereum/EIPs/pull/689/files)

### CODE REVIEW

**Comment by karalabe** [comment]
Please ping us before you start working on something, especially on metropolis stuff with deadlines. I already have this implemented locally, just debating consensus issues between different implementations.

**Comment by karalabe** [comment]
Otherwise the code is ok :)

**Comment by karalabe** [comment]
Actually, not fully ok. Anyway, there's a cornercase that needs to be figured out before we can finalize this. https://github.com/ethereum/pm/issues/21#issuecomment-324863680

**Comment by rjl493456442** [comment]
It is fine. I will close it.

**Pull request closed without merging**
