### PR TITLE
WIP: Faster blocks

### PR DESCRIPTION
**Pull request by holiman**
This is a work in progress. Is __not__ ready for merging.

The benchmarks below are based on the following cases:

1. `BlockChain_1x1000ValueTransferToNonexisting` : importing one block, filled with `1000` transactions that each send a wei to a non-existing recipient. No data. 
2. `BlockChain_1x1000ValueTransferToExisting` : importing one block, filled with `1000` transactions that each send a wei to an _existing_ recipient. No data. 
3. `BlockChain_1x1000Executions`:  importing one block, filled with `1000` transactions that each invoke an existing contract which has code to do a `push` and a `pop`. No data. 

### Not allocating 1024 for intpool every tx

```
[user@work core]$ benchstat oldtimes.txt zerosizetimes.txt 
name                                           old time/op  new time/op  delta
BlockChain_1x1000ValueTransferToNonexisting-2  90.6ms ± 2%  85.5ms ± 5%   -5.54%  (p=0.032 n=5+5)
BlockChain_1x1000ValueTransferToExisting-2     62.8ms ± 6%  56.4ms ± 7%  -10.30%  (p=0.016 n=5+5)
BlockChain_1x1000Executions-2                  64.7ms ± 4%  60.7ms ± 4%   -6.08%  (p=0.008 n=5+5)
```
### Using a block-specific context

A per-block struct is used for things that does not change between transactions. This also hosts an intpool and the `precompile` list, among other things. Quite a large change. It has some benefits, but not extreme:
```
# Use block-context, which is not created anew each time
[user@work core]$ benchstat oldtimes.txt newtimes.txt 
name                                           old time/op  new time/op  delta
BlockChain_1x1000ValueTransferToNonexisting-2  90.6ms ± 2%  82.6ms ± 8%   -8.82%  (p=0.016 n=5+5)
BlockChain_1x1000ValueTransferToExisting-2     62.8ms ± 6%  56.0ms ± 7%  -10.81%  (p=0.008 n=5+5)
BlockChain_1x1000Executions-2                  64.7ms ± 4%  58.1ms ± 5%  -10.12%  (p=0.008 n=5+5)
```
### Pointers instead of objects

The last optimization is to replace large objects in the call chain for executing transactions, and using pointers instead. This change resulted in significant improvements. We need to ensure that at no point can anything mess with the data, though. 
```
# using pointers instead of passing around large structs
[user@work core]$ benchstat oldtimes.txt morepointertimes.txt 
name                                           old time/op  new time/op  delta
BlockChain_1x1000ValueTransferToNonexisting-2  90.6ms ± 2%  67.5ms ± 4%  -25.44%  (p=0.008 n=5+5)
BlockChain_1x1000ValueTransferToExisting-2     62.8ms ± 6%  42.1ms ± 4%  -33.02%  (p=0.008 n=5+5)
BlockChain_1x1000Executions-2                  64.7ms ± 4%  44.7ms ±12%  -30.89%  (p=0.008 n=5+5)
```

I'll post some graphs once I've run it on the aws cluster.

### CODE REVIEW

**Comment by holiman** [comment]
Experimental PR
Start:

```
Apr 12 11:37:24 18.130.0.187 geth-experimental: INFO [04-12|09:37:24] Block synchronisation started  
...

Apr 16 20:56:11 18.130.0.187 geth-experimental: INFO [04-16|18:56:11] Imported new chain segment               blocks=1    txs=91    mgas=5.239    elapsed=290.217ms mgasps=18.052  number=5452454 hash=720c1f…0f6496 cache=188.68mB 
```

From `0` to `5452454`: 105h 20m

Master:

```
Apr 12 11:37:51 35.177.24.226 geth-master: INFO [04-12|09:37:50] Block synchronisation started 
...

Apr 16 23:05:41 35.177.24.226 geth-master: INFO [04-16|21:05:41] Imported new chain segment               blocks=23   txs=2579  mgas=153.137 elapsed=8.036s    mgasps=19.056  number=5452460 hash=dbc5b1…be4f71 cache=207.04mB 
....
Apr 16 23:09:19 35.177.24.226 geth-master: INFO [04-16|21:09:19] Imported new chain segment               blocks=1    txs=31    mgas=3.046   elapsed=44.742ms  mgasps=68.079  number=5453015 hash=c8b164…65e97e cache=149.03mB 
```

From `0` to `5452460`: 107h 30m

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: dd8653ac50cecde6662b16ad2e26b494ed3ff812
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by holiman** [comment]
memstat_faster_blocks
This graphs shows two nodes running, fast-synched and up to date. In the middle of the graph, one of the nodes was switched over to this PR. Although there was no immediate effect on block processing time, there was a drastic effect on the number of allocations performed, from ca 1M to 250K.

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 874ca182e3a8c61766529caaba8e0e669869d54c
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 874ca182e3a8c61766529caaba8e0e669869d54c
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 874ca182e3a8c61766529caaba8e0e669869d54c
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by holiman** [comment]
I have now re-enabled some stuff which I hack-disabled while testing out the PR. If travis turns green, it would be good to

1. Run this on a full import again
2. Verify that transaction tracing still works, as well as estimateGas
3. Verify that LES odr-stuff still works

**Pull request closed without merging**
