### PR TITLE
cmd/geth: extradata is correcly initialized with console

### PR DESCRIPTION
**Pull request by kobigurk**

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Wed Sep 16 18:01:59 UTC 2015_

**Comment by Phistr90** [comment]
:+1: 

Thanks Kobi

**Comment by obscuren** [comment]
:+1:

**Comment by fjl** [comment]
:+1:

**Pull request merged**
