### PR TITLE
core: stop chain when tests are finished

### PR DESCRIPTION
**Pull request by darioush**
Adds calls for chain.Stop() to tests that call NewBlockChain

### CODE REVIEW

**Review by lightclient — COMMENTED** [review]
It isn't really necessary. The goroutines will be cleaned up by the runtime when the test exits and journaling isn't relavant because the tests use in-memory databases (and don't reopen them).

**Comment by darioush** [comment]
I ran the tests before and after the change, not a notable difference in execution time. The reason for the PR is as you note, the goroutines hang out while other tests are running and it seems better to clean-up resources in tests when not too difficult. Also most other tests call blockchain.Stop.

**Comment by 09306677806** [comment]
Ethereum should not be in the master, it should be in the wallet address and it should be OK with the IP of any program and the code of each system should be correct, the system will work better.

**Review by lightclient — APPROVED** [review]
Makes sense, appears it is more of an omission to not stop the chain. Thanks for this.

**Review by Georgezhang714 — COMMENTED** [review]
georgezhang714

**Pull request merged**
