### PR TITLE
core: fix temp memory blowup caused by defers holding on to state

### PR DESCRIPTION
**Pull request by karalabe**
When adding the background trie prefetcher, I've used defers to make sure the prefetchers are stopped irrelevant what error path the importer exits on. Learnt once again that defer in a loop is a horrible idea, because it kept references to old state imported in the same batch. On the Shanghai attack range, this caused a temporary memory blowup, which if enough blocks were imported in a single batch could cause a significant RAM spike.

Shoutout to [Michael](https://twitter.com/michael1011at/status/1359817492873568262) for finding this issue.

### CODE REVIEW

**Review by holiman — APPROVED** [review]
LGTM!

**Comment by holiman** [comment]
Screenshot_2021-02-12 Dual Geth - Grafana
Looks good!

**Comment by karalabe** [comment]
I think you didn't select this PR run on the charts, I only see the reference which blew :)

**Comment by karalabe** [comment]
Ah, you compared vs previous runs.

**Comment by karalabe** [comment]
Blue-green = master
Orange-red = PR

Screenshot from 2021-02-12 14-09-09

**Pull request merged**
