### PR TITLE
ethclient: reuse the common code 

### PR DESCRIPTION
**Pull request by jsvisa**

### CODE REVIEW

**Review by holiman — APPROVED** [review]
Sure, lgtm!

**Comment by holiman** [comment]
Hm, yeah, I agree with @fjl

**Comment by jsvisa** [comment]
@holiman just another quick question, in rpc.go we define block tag as below:

https://github.com/ethereum/go-ethereum/blob/8990c92aea01ca07801597b00c0d83d4e2d9b811/rpc/types.go#L65-L71

- `-1` stands for latest block
- `-2` stands for pending block

But in https://github.com/ethereum/go-ethereum/blob/8990c92aea01ca07801597b00c0d83d4e2d9b811/ethclient/ethclient.go#L570-L587 

We mapping `-1` to pending block, it's inconsistency, is it by design or tech debt?

**Comment by fjl** [comment]
I can explain that. The -1 thing was added earlier than the other two cases. The canonical way to get the latest block is with `number == nil`, so there was no confusion initially.

Now, with "safe" and "finalized" added, things looks a bit silly, I agree.

**Pull request closed without merging**
