### PR TITLE
Ignore this PR: cmd/faucet: more info in facebook failure

### PR DESCRIPTION
**Pull request by holiman**
This PR is just an attempt to catch the facebook auth error happening on travis from time to time, I want to find out what gets delivered from the server.

### CODE REVIEW

**Comment by holiman** [comment]
Failure: https://travis-ci.com/github/ethereum/go-ethereum/jobs/510372539#L345 -- the request needs auth, for some reason. 

If I do `curl https://m.facebook.com/fooz.gazonk/posts/2837228539847129` from my local machine (sweden) it works, but doing it from one of our aws-machines, located in london, I get a `302` redirect to 
```
location: https://m.facebook.com/login.php?next=https%3A%2F%2Fm.facebook.com%2Ffooz.gazonk%2Fposts%2F2837228539847129&refsrc=https%3A%2F%2Fm.facebook.com%2Ffooz.gazonk%2Fposts%2F2837228539847129&_rdr
```

**Comment by fjl** [comment]
Can we avoid hitting facebook.com in this test? It's also annoying on my machine because I need to authorize this connection in Little Snitch every time I run all tests.

**Comment by holiman** [comment]
I suspect fb did something, perhaps after brexit or whatever, but obviously certain regions cannot access things this way. So we probably need to remove this test and remove the fb auth feature.

**Comment by hari0806** [comment]
This is issue can be another valid reason along with #22624 to use Facebook API instead of page scraping which has inconsistent behavior. But the weird thing is that Facebook Graph API requires userAccessToken to get even public posts in the page of an user.

**Comment by holiman** [comment]
>  But the weird thing is that Facebook Graph API requires userAccessToken to get even public posts in the page of an user

Yes, I looked into it a bit yesterday, I reached the same conclusion :(

**Pull request closed without merging**
