### PR TITLE
all: don't use me, this, self as receiver names

### PR DESCRIPTION
**Pull request by jsvisa**
**What's this PR works for:**

Get ride of golint's warning: "don't use me, this, self as receiver names"

### CODE REVIEW

**Comment by karalabe** [comment]
There are a lot of PRs already open by @kielbarry that address exactly these issues. Those are pending review/merge. Does your PR bring anything new compared to those?

**Comment by jsvisa** [comment]
@karalabe  Thanks for your reply, and @kielbarry Have you adjusted this issue?(use `self` as receiver name)

**Comment by kielbarry** [comment]
@jsvisa I've purged all of the "use self as receiver name" from the codebase, pending review (10 outstanding PRs, 24 merged or something like that, a couple modules notwithstanding that I have locally). Apologies for your duplicate work. I believe the developer contribution docs mention creating PRs before starting work to prevent duping work - I would recommend that in the future. The vast majority of remaining golint warnings are for exported functions lacking documentation...

**Comment by jsvisa** [comment]
@karalabe @kielbarry It's my mistake to duping work, and this PR just convert self to anything else, nothing new, so I've to close this PR.

**Pull request closed without merging**
