### PR TITLE
rpc: check that "version" is "2.0" in request objects

### PR DESCRIPTION
**Pull request by dbadoy**
According to https://www.jsonrpc.org/specification,
`jsonrpc` in JSON-RPC 2.0 Request object  must be exactly "2.0".

In now, 
```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"net_version","params":[],"id":1.11}' http://localhost:8545
<-- {"jsonrpc":"2.0","id":1.11,"result":"2757"}

curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"geth","method":"net_version","params":[],"id":1.11}' http://localhost:8545
<-- {"jsonrpc":"2.0","id":1.11,"result":"2757"}

curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2411.0","method":"net_version","params":[],"id":1.11}' http://localhost:8545
<-- {"jsonrpc":"2.0","id":1.11,"result":"2757"}

curl -X POST -H "Content-Type: application/json" --data '{"method":"net_version","params":[], "id":12}' http://localhost:8545
<-- {"jsonrpc":"2.0","id":12,"result":"2757"}
```

Expect
```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2411.0","method":"net_version","params":[],"id":1.11}' http://localhost:8545
<-- {"jsonrpc":"2.0","id":1.11,"error":{"code":-32600,"message":"invalid request"}}
```

### CODE REVIEW

**Comment by dbadoy** [comment]
If allow that regardless JSON RPC 2.0 spec, I think it need to add comments like below
```
type jsonrpcMessage struct {
	Version string          `json:"jsonrpc,omitempty"` // Allow all values regardless of JSON-RPC 2.0 spec
	ID      json.RawMessage `json:"id,omitempty"`      // Allow floating point numbers regardless of JSON-RPC 2.0 spec
	Method  string          `json:"method,omitempty"`
	Params  json.RawMessage `json:"params,omitempty"`
	Error   *jsonError      `json:"error,omitempty"`
	Result  json.RawMessage `json:"result,omitempty"`
}
```

**Review by lightclient — APPROVED** [review]
This looks good to me. Maybe someone else can chime in if there are historical reasons for not requiring the version to be valid?

**Comment by fjl** [comment]
I agree that we could fix this, but it needs to be handled in a different place. This check should not be a part of `isNotification`, `isCall` etc. We should just assert that `version == "2.0"` in the `handler` code.

**Comment by dbadoy** [comment]
I thought `isNotification`, `isCall` are checks that `Does the received request satisfy JSON-RPC 2.0 Request object condition?` And `Version == "2.0"` is another condition in JSON-RPC Request object. So I added`hasValidVersion` there.
Am I misunderstood?

**Comment by fjl** [comment]
Sorry for delaying this, I was pretty sure there is a better way and wanted to try it. Having looked into it more, I now think the way you added the check is fine.

**Review by fjl — APPROVED** [review]

**Pull request merged**
