### PR TITLE
accounts/abi: return toGoType error immediately

### PR DESCRIPTION
**Pull request by ceyonur**
Returns the non-nil error before calculating next virtualArgs

### CODE REVIEW

**Review by gballet — CHANGES_REQUESTED** [review]
SGTM. Could you please add a test for this use case? Just a simplified version of the code that you used to run into this error would be enough.

**Comment by ceyonur** [comment]
Changes in this PR does not change any observable behavior. It just skips some additional calculation overhead before returning the error. Would you like me to add a test that actually returns an error for these methods? @gballet

**Review by rjl493456442 — APPROVED** [review]

**Review by holiman — APPROVED** [review]
LGTM

**Review by gballet — APPROVED** [review]
makes sense, LGTM

**Pull request merged**
