### PR TITLE
abi: fix checks when all fields are indexed

### PR DESCRIPTION
**Pull request by RachelFranks**
This PR fixes abi checks in the edge case where all arguments are indexed

### CODE REVIEW

**Comment by MariusVanDerWijden** [comment]
Looks good, could you add a small unit test for this, so we don't regress in the future?

**Comment by FreshKhalifa347** [comment]
Oh yeah I can for sure

As long as you ready to participate in the new Volume offering 5.0 airdrop
Tokens in 24hrs to all depositors.

**Comment by RachelFranks** [comment]
I've updated the unpacking test to include 3 more checks so that it includes scenarios with indexed arguments

**Review by MariusVanDerWijden — APPROVED** [review]
LGTM

**Comment by RachelFranks** [comment]
Looks like CI hit a fluke
```
--- FAIL: TestSkeletonSyncRetrievals (2.46s)
    skeleton_test.go:832: test 7, mid state: dropped peers mismatch: have 0, want 1
 ```

**Pull request merged**
