### PR TITLE
cmd: fix command help messages in modules

### PR DESCRIPTION
**Pull request by zacscoding**
solved errors if help flag is provided in some modules such as ethkey

### CODE REVIEW

**Comment by holiman** [comment]
```
[user@work go-ethereum]$ build/bin/evm run  -h
panic: template: help:1:6: executing "help" at <.cmd.Name>: can't evaluate field cmd in type cli.Command

goroutine 1 [running]:
github.com/ethereum/go-ethereum/cmd/utils.printHelp(0xdac720, 0xc0000c8008, 0xc945bb, 0x1d7, 0xc58540, 0xc0000e8a00)
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/flags.go:116 +0x359
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.ShowCommandHelp(0xc00021cf20, 0xc649dd, 0x3, 0x1, 0xc00021cf20)
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/help.go:185 +0x4c5
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.checkCommandHelp(0xc00021cf20, 0xc649dd, 0x3, 0xc00058bf80)
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/help.go:283 +0x7d
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0xc649dd, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc76d12, 0x18, 0x0, ...)
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/command.go:179 +0x930
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc00024c340, 0xc0000ae150, 0x3, 0x3, 0x0, 0x0)
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:255 +0x6ab
main.main()
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/evm/main.go:158 +0x55

```
I suppose this is what this PR fixes?

**Comment by holiman** [comment]
Yep, with this PR I get
```
[user@work go-ethereum]$ build/bin/evm run  -h
run [arguments...]
The run command runs arbitrary EVM code.
```

**Comment by holiman** [comment]
Still not perfect. Works: `devp2p enrdump -h`, `ethkey inspect -h`, `abigen`, `checkpoint-admin`, `faucet`, `p2psim`, `puppeth`, `rlpdump`, `wnode`
Doesn't work: 
```ib
[user@work go-ethereum]$ build/bin/clef init -h
panic: template: help:1:6: executing "help" at <.cmd.Name>: can't evaluate field cmd in type cli.Command

goroutine 1 [running]:
github.com/ethereum/go-ethereum/cmd/utils.printHelp(0xf96520, 0xc000010018, 0xe3c83a, 0x1d7, 0xdf6da0, 0xc000194a00)
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/flags.go:128 +0x359
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.ShowCommandHelp(0xc00021ac60, 0xe05b36, 0x4, 0x1, 0xc00021ac60)
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/help.go:185 +0x4c5
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.checkCommandHelp(0xc00021ac60, 0xe05b36, 0x4, 0xc000272120)
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/help.go:283 +0x7d
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0xe05b36, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe2e4bd, 0x2e, 0x0, ...)
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/command.go:179 +0x930
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0001c6b60, 0xc0000321b0, 0x3, 0x3, 0x0, 0x0)
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:255 +0x6ab
main.main()
	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/clef/main.go:229 +0x55
```

**Comment by zacscoding** [comment]
> Still not perfect. Works: `devp2p enrdump -h`, `ethkey inspect -h`, `abigen`, `checkpoint-admin`, `faucet`, `p2psim`, `puppeth`, `rlpdump`, `wnode`
> Doesn't work:
> 
> ```
> [user@work go-ethereum]$ build/bin/clef init -h
> panic: template: help:1:6: executing "help" at <.cmd.Name>: can't evaluate field cmd in type cli.Command
> 
> goroutine 1 [running]:
> github.com/ethereum/go-ethereum/cmd/utils.printHelp(0xf96520, 0xc000010018, 0xe3c83a, 0x1d7, 0xdf6da0, 0xc000194a00)
> 	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/flags.go:128 +0x359
> github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.ShowCommandHelp(0xc00021ac60, 0xe05b36, 0x4, 0x1, 0xc00021ac60)
> 	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/help.go:185 +0x4c5
> github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.checkCommandHelp(0xc00021ac60, 0xe05b36, 0x4, 0xc000272120)
> 	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/help.go:283 +0x7d
> github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0xe05b36, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe2e4bd, 0x2e, 0x0, ...)
> 	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/command.go:179 +0x930
> github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0001c6b60, 0xc0000321b0, 0x3, 0x3, 0x0, 0x0)
> 	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1/app.go:255 +0x6ab
> main.main()
> 	/home/user/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/clef/main.go:229 +0x55
> ```

addes also help template clef module

**Comment by holiman** [comment]
perfect, thanks!

**Comment by zacscoding** [comment]
> perfect, thanks!

thx for missing fixes :)

**Pull request merged**
