### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by obscuren**

### CODE REVIEW

**Comment by robotally** [comment]
:exclamation: Pull request against `master` :exclamation:

| Vote | Count | Users |
| :---: | :---: | :--- |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Thu Jul 30 13:31:16 UTC 2015_

**Comment by obscuren** [comment]
<3

**Comment by obscuren** [comment]
:heart:

**Comment by maran** [comment]
:+1: :8ball:

**Comment by obscuren** [comment]
:+1: :shipit:

**Comment by karalabe** [comment]
:sparkles:

**Pull request closed without merging**
