### PR TITLE
cademlia changed to use hash of public key as address/nodeID

### PR DESCRIPTION
**Pull request by zelig**
- rename NodeID, ID -> PublicKey
- add NodeID as 256 bit hash field to structs
- use NodeID in cademlia calculations and lookup target
- use PublicKey elsewhere
- add exportedd accessors for own and remote PublicKey and NodeID

### CODE REVIEW

**Comment by fjl** [comment]
I do not want to change the definition of NodeID. Will submit PR with a different approach later.

**Comment by fjl** [comment]
Sorry, maybe that sounded a bit rude. I think this approach its a bit too intrusive because it changes the definition of `NodeID`. The node identifier is the public key, that shouldn't change. 

The switch to hashes should only change the (**internal**) distance calculation. The API of package discover does not need to change. If required, we can introduce 

    func (*Table) LookupHash([]byte) ([]*Node, error)

I agree that the target for the findnode RPC should also be a 256 bit value.

**Comment by zelig** [comment]
synopsis of our discussion re p2p/discovery cademlia
both p2p server as well as swarm require:

1. need hash of public key as address so that address space satisfies independent bits assumption (this is needed by everyone for security, and will be done)
2. need address of peer exported as public field/func (minor)
3. need p2p server to actually use cademlia to drive peer selection so that the emerging network satifies the connectivity properties needed by dht routing/search
4. need all connected  peers included in the lookup table 
5. need functionality to lookup target -> bucket nodes
6. need a way to know which peers are connected and which are just 'potential peers' = 'nodes'

6 can be done by separately registering peer connect/disconnect within the protocol (already in code)

1 and 2 was done by current PR but rejected 

however as it turns out 3, 4, 5 are also not satisfied which leaves me wondering ...
5 can easily be done if 1-4 is done
but 4 does not stand since incoming peers are left out.
and therefore by definition 3 can only be incorrect.
Actually right now the p2p has no real strategy regarding who to connect to.

**Comment by subtly** [comment]
Why does everyone keep spelling kademlia wrong???

@zelig Until swarm specs are drafted in a form which can be understood and implemented by others it's not really appropriate to bring changes into the other protocols. Can you separate out the requests into specific changes which aren't already specified in rlpx.md on devp2p repos?

Right now the strategy is as-is specified in kademlia which is to connect to nodes which are nearest by xor distance. This is simple to do, and notably, tcp connectivity is somewhat of an orthogonal implementation detail for network shaping.

**Comment by nagydani** [comment]
Kademlia is being spelt wrong because of a misspelling that probably originates from me. My apologies.

**Pull request closed without merging**
