### PR TITLE
signer: enable typed data signing from signer rpc

### PR DESCRIPTION
**Pull request by nasdf**
Hello,

This PR should make it easier to sign EIP-712 typed data from the `accounts.Wallet` API.

```go
var wallet accounts.Wallet
var account accounts.Account
var typedData signer.TypedData

data, _ := json.Marshal(typedData)

wallet.SignData(account, accounts.MimetypeTypedData, data)
```

### CODE REVIEW

**Comment by holiman** [comment]
Not sure I follow. Why can't you use this existing method?  
```
func (api *SignerAPI) SignTypedData(ctx context.Context, addr common.MixedcaseAddress, typedData TypedData) (hexutil.Bytes, error) {
	signature, _, err := api.signTypedData(ctx, addr, typedData, nil)
	return signature, err
}
```

**Comment by holiman** [comment]
Ah, ok, it's not available on the interface. So then I think you could still avoid all the copy-paste code, and just call that method from inside the switch... ?

**Comment by nasdf** [comment]
> Ah, ok, it's not available on the interface. So then I think you could still avoid all the copy-paste code, and just call that method from inside the switch... ?

That would be a much better approach but `determineSignatureFormat` is expecting a `SignDataRequest` return value.
If you think a better approach is to add it to the wallet interface I'd be happy to try that route instead.

**Comment by holiman** [comment]
We already have `SignGnosisSafeTx`, isn't that basically the same thing?

**Comment by holiman** [comment]
Superseded by #26241

**Pull request closed without merging**
