### PR TITLE
web3: regression. Fixes #1613

### LINKED ISSUE #1613: geth console: eth.getBlock by hash not returning anything
with `geth 1.0.1`

via web3.js:
`web3.eth.getBlock(web3.eth.getBlock('latest').hash)` returns a block okay.

via `geth console`:

`web3.eth.getBlock(web3.eth.getBlock('latest').hash)` returns nothing
`web3.eth.getBlock(web3.eth.getBlock('latest').number)` works as expected.

expected is that the `console` also returns a block by hash.

### PR DESCRIPTION
**Pull request by obscuren**

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Fri Aug 7 10:33:34 UTC 2015_

**Comment by frozeman** [comment]
:+1: 

But why is it there? web3 has that fixed since a while

**Comment by frozeman** [comment]
btw i just checked web3.js latest...

**Comment by obscuren** [comment]
I know, I was just lazy :)

**Pull request merged**
