### PR TITLE
cmd, les, tests: remove light client code

### PR DESCRIPTION
**Pull request by MariusVanDerWijden**
This commit removes the light client (LES) code.
Since the merge the light client has been broken and it is hard to maintain it alongside the normal client. We decided it would be best to remove it for now and maybe rework and reintroduce it in the future.

This PR also removes the faucet, which has also been broken since the merge. There are great new faucet implementations out there which can be used to set up faucets on testnets

I've decided not to remove the light mode from the downloader as this will require a bigger refactor of the downloader and the tests for it.

The user is being warned about the deprecated flags now:
```
 ./build/bin/geth --light.serve 10 --light.ingress 3 --light.egress 10 --light.maxpeers 10 --light.nopruning 
--light.nosyncserve console
INFO [11-23|11:48:50.365] Starting Geth on Ethereum mainnet... 
INFO [11-23|11:48:50.365] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [11-23|11:48:50.366] Maximum peer count                       ETH=50 total=50
INFO [11-23|11:48:50.367] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [11-23|11:48:50.368] The light server has been deprecated, please remove this flag flag=light.serve
WARN [11-23|11:48:50.368] The light server has been deprecated, please remove this flag flag=light.ingress
WARN [11-23|11:48:50.368] The light server has been deprecated, please remove this flag flag=light.egress
WARN [11-23|11:48:50.368] The light server has been deprecated, please remove this flag flag=light.maxpeers
WARN [11-23|11:48:50.368] The light server has been deprecated, please remove this flag flag=light.nopruning
WARN [11-23|11:48:50.368] The light server has been deprecated, please remove this flag flag=light.nosyncserve
INFO [11-23|11:48:50.369] Set global gas cap                       cap=50,000,000
INFO [11-23|11:48:50.369] Initializing the KZG library             backend=gokzg
INFO [11-23|11:48:50.385] Allocated trie memory caches             clean=614.00MiB dirty=1024.00MiB
INFO [11-23|11:48:50.479] Using pebble as the backing database 
INFO [11-23|11:48:50.479] Allocated cache and file handles         database=/home/matematik/.ethereum/geth/chaindata cache=2.00GiB handles=262,144
INFO [11-23|11:48:51.619] Found legacy ancient chain path          location=/home/matematik/.ethereum/geth/chaindata/ancient
INFO [11-23|11:48:51.682] Opened ancient database                  database=/home/matematik/.ethereum/geth/chaindata/ancient readonly=false
```
and errors if the syncmode is set to light
```
./build/bin/geth --syncmode light console
INFO [11-23|11:52:27.010] Starting Geth on Ethereum mainnet... 
INFO [11-23|11:52:27.010] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [11-23|11:52:27.011] Maximum peer count                       ETH=50 total=50
INFO [11-23|11:52:27.012] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [11-23|11:52:27.014] Set global gas cap                       cap=50,000,000
INFO [11-23|11:52:27.014] Initializing the KZG library             backend=gokzg
Fatal: Failed to register the Ethereum service: can't run eth.Ethereum in light sync mode, light mode has been deprecated
```

Fixes https://github.com/ethereum/go-ethereum/issues/28591

### CODE REVIEW

**Comment by holiman** [comment]
I _think_ you just nuked the flags -- we should probably deprecate them and make them no-ops for now?

**Comment by zsfelfoldi** [comment]
> I _think_ you just nuked the flags -- we should probably deprecate them and make them no-ops for now?

The light mode has been dysfunctional for more than a year now, I think we can consider this as a deprecation period. Also, suddenly changing the behavior so that it just goes into full sync mode is not necessarily an improvement, just in case someone still attempts to run geth with the light flags (which is quite improbable). Failing properly in this case (as the current PR does) might be better. So I'd accept this PR as it is.

**Review by zsfelfoldi — APPROVED** [review]
LGTM :)

**Comment by namiloh** [comment]
I was thinking of flags like --light.serve for example.

**Comment by MariusVanDerWijden** [comment]
@holiman I readded the flags and added some deprecation warnings, PTAL

**Review by holiman — APPROVED** [review]
LGTM

**Comment by karalabe** [comment]
Fixes https://github.com/ethereum/go-ethereum/issues/28591 (playing with projects, hence the spam :P)

**Comment by ryanorendorff** [comment]
@MariusVanDerWijden 

For you comment

> This PR also removes the faucet, which has also been broken since the merge. There are great new faucet implementations out there which can be used to set up faucets on testnets

do you have any suggestions for which faucet implementations to use?

**Comment by MariusVanDerWijden** [comment]
@ryanorendorff 
https://github.com/pk910/PoWFaucet for a pow faucet
https://github.com/komputing/FaucETH for a non-pow faucet

**Pull request merged**
