### PR TITLE
eth: enable bad block reports

### PR DESCRIPTION
**Pull request by fjl**
We used to have reporting of bad blocks, but it was disabled before the
Frontier release. We need it back because users are usually unable to provide
the full RLP data of a bad block when it occurs.

One shortcoming of this particular implementation is that the origin peer
is not tracked for blocks received during eth/63 sync. No origin peer
info is still better than no report at all though.

Please review: @karalabe, @obscuren

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Tue May 24 21:49:25 UTC 2016_

**Comment by obscuren** [comment]
> One shortcoming of this particular implementation is that the origin peer is not tracked for blocks received during eth/63 sync.

@karalabe is there any way we could get this information anyway? Knowing which peer send you the block could be very valuable.

**Comment by obscuren** [comment]
Besides the peer ID 👍

**Comment by karalabe** [comment]
@obscuren Hmmm, well, during sync we always have a master peer which "defines" the entire chain being sent to us. Pre-concurrent headers it was the peer who sent the chain of headers, and post-concurrent headers it's the peer sending the header skeleton. Everything else is mapped on to the headerchain defined by this peer. So even though we piece the block together from multiple possible peers, we can always assume that the master peer can be a valid origin as it was the one who sent the header/hash.

During propagation I haven't looked at the code but I'm sure we have the information available, just need to surface it.

**Comment by obscuren** [comment]
Now that I think about it, it doesn't actually matter who gave you the block anyway. The information is pretty meaningless if you think about on what condition we do propagation (i.e. *only* the header must be valid). So even if you deem the block unworthy after processing it, you'll already have sent it around.

**Comment by fjl** [comment]
Just to be clear: the origin peer **is included** for relayed blocks. I just couldn't make it work for synced blocks because the body is downloaded separately and combined with the header in eth/downloader.

**Pull request merged**
