### PR TITLE
accounts/abi: support unpacking of transaction log to event parameters

### PR DESCRIPTION
**Pull request by kenmazsyma**
I’m using `accounts/abi/abi.go` for packing/unpacking data in my project.
Currently, this module doesn’t have functionality for unpacking transaction log to event parameters, because `abi.Unpack` function uses only `Outputs` part of ABI.
I added this functionality to this module.
If it is possible, please pull it.

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Sat Jun 4 07:56:06 UTC 2016_

**Comment by obscuren** [comment]
Reviewers: @obscuren

**Comment by karalabe** [comment]
@obscuren Pling?

**Comment by obscuren** [comment]
I'd still like to get this PR in. I'll recreate the PR and cherry pick this commit and fix up some go syntax.

**Pull request closed without merging**
