### PR TITLE
cmd/geth, cmd/utils: removed legalese

### LINKED ISSUE #1992: skip CheckLegalese via environment variable
Feature Request: Allow legalese to be skipped by correct value in environment variable.

up-side: more semantic means of skipping the legalese. ~~also official docker image works as-is.~~
down-side: ?

I understand that you can achieve this by creating the data directory first~~, but unfortunately there doesn't seem to be a way to do this with `docker-compose` when using the official image ( need to create a silly wrapper image ).~~

sorry for overly specific use-case concerns. :smile_cat:

### PR DESCRIPTION
**Pull request by obscuren**
Removed the legalese confirmation dialog. This closes #1992

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Thu Nov 19 10:56:57 UTC 2015_

**Comment by fjl** [comment]
`git rm cmd/utils/legalese.go`

**Comment by obscuren** [comment]
@fjl cheers

**Comment by karalabe** [comment]
LGTM :+1:

**Comment by Gustav-Simonsson** [comment]
:+1:

**Pull request merged**
