### PR TITLE
core: log optimisations

### PR DESCRIPTION
**Pull request by obscuren**
Optimised logs and stored receipts for faster iterations

### CODE REVIEW

**Comment by obscuren** [comment]
This has been tested on a fresh chain using the `coin.html` with the following filter:

```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_newFilter","params":[{"address":"<INSERT CONTRACT ADDRESS>","fromBlock":"0x0","toBlock":"latest"}],"id":8}' http://127.0.0.1:8545

curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getFilterLogs","params":["0x0"],"id":1}' http://127.0.0.1:8545
```

**Comment by frozeman** [comment]
I will try it once i get time, please don't merge yet.

**Comment by obscuren** [comment]
It will be merged in 2 hours

**Comment by frozeman** [comment]
I re-imported the whole chain of 400 000+ blocks and run the logs of my old address, which has a lot.
And it still takes over 20+ secs and 160% CPU usage to get those logs.

**Comment by frozeman** [comment]
You can try for yourself, address is `0xbd999ac9af99055bdbc8b0fe564b64381513fa99 `

**Comment by obscuren** [comment]
You are checking 400.000 blocks. Of course it takes time

**Comment by frozeman** [comment]
Sure, but we should think about how we can optimise that, because of one filter like that kills already my computer and a simple dapp can have many like that (e.g. the wallet needs 4 per account) and you have multiple dapps, than you computer will be unresponsive for a long time...

I already optimise it and only need to check all the past blocks, when the local storage is cleared, but other dapps might not do that.

We should index this logs by address or other means so that you can fast find them without running through all of them.

**Comment by obscuren** [comment]
You clearly don't understand the internals (which is understandable). This is getting merged now though since it's a big win over the previous implementation.

**Pull request merged**
