### PR TITLE
cmd/abigen, accounts/abi: add support for log subscriptions

### PR DESCRIPTION
**Pull request by bas-vk**
**WIP**: need to regenerate the contracts included in the `contracts` package but solc is not accepting them during the generation step. Need to figure out why not.

This PR adds supports for subscribing to log events on the generated source code.

E.g.:

```
pragma solidity ^0.4.15;

// generate go bindings with
// abigen -pkg main -sol test.sol -out test.go

contract Test {
  event Ev0(address);
  event Ev1(address indexed);
  event Ev2(uint indexed intArg, bytes32) anonymous;

  function raiseEvents() {
      Ev0(msg.sender);
      Ev1(msg.sender);
      Ev2(1234, "0x00112233445566778899");
  }
}
```
Generates the following bindings:

```
func (_Test *TestCaller) SubscribeEv0(opts *bind.CallOpts, ch chan<- types.Log, topics ...[]common.Hash) (ethereum.Subscription, error)
func (_Test *TestCaller) SubscribeEv1(opts *bind.CallOpts, ch chan<- types.Log, topics ...[]common.Hash) (ethereum.Subscription, error) {
func (_Test *TestCaller) SubscribeEv2(opts *bind.CallOpts, ch chan<- types.Log, topics ...[]common.Hash) (ethereum.Subscription, error) {
```

Note: I don't have a java environment set up so could not test generated java code. Therefore this PR currently only has go bindings in scope. But that probably leads to problems with the java bindings.

### CODE REVIEW

**Comment by chatchay** [comment]
pragma solidity ^0.4.15;

// generate go bindings with
// abigen -pkg main -sol test.sol -out test.go

contract Test {
  event Ev0(address);
  event Ev1(address indexed);
  event Ev2(uint indexed intArg, bytes32) anonymous;

  function raiseEvents() {
      Ev0(msg.sender);
      Ev1(msg.sender);
      Ev2(1234, "0x00112233445566778899");
  }
}

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: c064b1d94d29bebbe6d81419435590aa26daf67f
  * Your commit message body contains a line that is longer than 80 characters
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: c064b1d94d29bebbe6d81419435590aa26daf67f
  * Your commit message body contains a line that is longer than 80 characters
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by markya0616** [comment]
Any news on this?

**Comment by fjl** [comment]
@bas-vk ping

**Comment by karalabe** [comment]
Superseded by https://github.com/ethereum/go-ethereum/pull/15832.

**Pull request closed without merging**
