### PR TITLE
Update flags.go

### PR DESCRIPTION
**Pull request by larspensjo**
Improved warning for --rpcaddr

### CODE REVIEW

**Comment by robotally** [comment]
:exclamation: Pull request against `master` :exclamation:

| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Sat Aug 29 13:57:02 UTC 2015_

**Comment by maran** [comment]
Thanks for the PR! :) 

Could you re-open this against develop? The team doesn't merge changes into master (stable).

**Comment by obscuren** [comment]
:-1: your intentions are good but I don't believe this is the right solution.

Instead a warning should be given when changing it.

**Comment by larspensjo** [comment]
Agreed, this is not the complete solution but it should be compatible with most other solutions. My thinking was to immediately get a warning into the source code, for those that build directly from source. The change is trivial, please reject it if it doesn't fit into the planning.

**Comment by karalabe** [comment]
I think I agree that modifying the flag description isn't the best thing. Most people won't read it, or probably once in their life and not afterwards, so it's not really a good place to put warnings. I'll close this PR as it's opened against master and doesn't really solve the issue.

@Gustav-Simonsson I think wanted to issue a warning already if this is enabled, don't know if he has done it already/worked on it, maybe he can update this thread whether such a PR should be worked on or if he has it covered already.

**Pull request closed without merging**
