### PR TITLE
Adding avl tree to txpool.

### PR DESCRIPTION
**Pull request by SipengXie**
The AVL tree is a data structure used to determine whether inserting or replacing a new transaction will result in a balance exceeding the corresponding account. 
In the current design, all transactions, including those with larger nonces than the current transaction (tx0), are considered. 
However, a more reasonable approach would be to use the AVL tree to query the total cost of all transactions with smaller nonces than tx0, providing a more accurate assessment of the account balance.

### CODE REVIEW

**Comment by holiman** [comment]
Well, an account's `balance` goes up, and it goes down. It fluctuates, depending on external factors. Unless we want to resort every AVL-tree on every block, the trees will not represent the latest state, rather the state at some random earlier point in time. 

An account nonce, however, goes only up. Once a nonce is passed, all transactions below that nonce is `invalid`. It's not a a case of "there are others which are better", it's invalid. 

There is a difference between "invalid from now and forever after" and "invalid now, because the accounts lacks funds right now". And seen from that perspective, I'm not sure your proposal is more reasonable. 

Caveat: I haven't looked in depth at the actual code-changes, just read your description and skimmed the actual changes. Maybe I have misunderstood your proposal.

**Comment by SipengXie** [comment]
In my opinion,  the field `list[addr].totalcost` in the legacypool sums up the cost of all txs belonging to the very `addr`.
Suppose `balance[addr]=300`, and `list[addr] = {tx0, tx1, tx2}`, each of which costs 100, and thus `list[addr].totalcost = 300`;
Now if `tx1' `(having the same nonce of `tx1`) comes, and it costs 200, the current ValidationWithState function may say: `list[addr].totalcost` - `tx1.Cost` + `tx1'.Cost` > `balance[addr]`, so `tx1'` cannot replace `tx1`;
However, `balance[addr]` can afford to execute `tx0` and `tx1'`, the owner of `addr` may want to use `tx1'` to block `tx2`, so he does want the replacement to happen.
So I think it's crucial to know the totalcost **before** a transaction, not only the whole txlist, and that's why I integrate AVL-tree into txpool. (The AVL-tree only records the transaction costs of a txlist)

**Comment by MariusVanDerWijden** [comment]
I think adding this is huge overkill for a very small use case, it only helps in the case a user wants to replace a transaction after sending a bunch of follow-up transactions. Enabling this use case will also enable an attack where an attacker can invalidate a lot of their transactions by sending a self-transfer.

**Comment by holiman** [comment]
Closing this, as far as we can tell this is not a desired feature, since it would tend to increase the transaction churn.

**Pull request closed without merging**
