### PR TITLE
internal/ethapi: don't set sender-balance to maxuint, fixes #16999

### LINKED ISSUE #16999: return address.balance returns strange value
Originally opened [at remix](https://github.com/ethereum/solidity/issues/2325)
Then [at MetaMask](https://github.com/MetaMask/metamask-extension/issues/2999#issuecomment-397395577)
Then [here at Geth](https://github.com/ethereum/go-ethereum/issues/14989) (but I think mis-represented, so prematurely closed).

Solidity:
```
pragma solidity ^0.4.11;

contract Test {
  function balanceOfEther(address user) public constant returns (uint256) { return user.balance; } 
}
```

Returns unusual balances when requested from Geth via an eth_call.

For any address, returns:

```
{"jsonrpc":"2.0","id":570283474,"result":"0xfffffffffffffffffffffffffffffffffffffffffffffffffdeb17cb73b0ffff"}
```

### PR DESCRIPTION
**Pull request by holiman**
This fixes #16999 , but it may cause problem in other areas. Not sure what do do here...

### CODE REVIEW

**Comment by karalabe** [comment]
The fix seems reasonable, we just need to make sure it doesn't touch some strange code path. Btw, can't we get rid of that `dafultGasPrice` constant? Is that used anywhere?

**Comment by fjl** [comment]
Please fix the lint error.

**Comment by fjl** [comment]
This change makes eth_call semantics a lot less surprising. I'm pretty something will break, but let's merge anyway.

**Comment by wjmelements** [comment]
Thank you

**Pull request merged**
