### PR TITLE
core: add missing lock in TxPool.GetTransaction

### LINKED ISSUE #2650: fatal error: concurrent map read and map write
#### System information

Geth version: tested on `1.4.5-stable` & `1.4.5-stable-a269a713`
OS & Version: Arch Linux 4.5.4-1

#### Expected behaviour
I'm using a web3/nodejs script to deploy millions of contracts to a private blockchain. Expected run time is ~2 days to deploy ~50,000000 contracts.

#### Actual behaviour
After approximately 30 mins geth crashes & reviewing geth logs in journalctl I find this:

```
Jun 02 13:28:09 mario geth[9833]: fatal error: concurrent map read and map write

Jun 02 13:28:09 mario geth[9833]: goroutine 62878 [running]:

Jun 02 13:28:09 mario geth[9833]: runtime.throw(0x1121760, 0x21)

Jun 02 13:28:09 mario geth[9833]:         /usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc82217cda8 sp=0xc82217cd90

Jun 02 13:28:09 mario geth[9833]: runtime.mapaccess2(0xcdd980, 0xc8201eafc0, 0xc82217ce18, 0x0, 0x0)

Jun 02 13:28:09 mario geth[9833]:         /usr/local/go/src/runtime/hashmap.go:343 +0x5a fp=0xc82217cdf0 sp=0xc82217cda8

Jun 02 13:28:09 mario geth[9833]: github.com/ethereum/go-ethereum/core.(*TxPool).GetTransaction(0xc8203d65a0, 0xbcd8ed0ca7b3b1f9, 0x852636080acee85c, 0xbe98dd39aa40b0c8, 0x5e76045a7e09d46c, 0x0)

Jun 02 13:28:09 mario geth[9833]:         /go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/tx_pool.go:372 +0x5c fp=0xc82217cea0 sp=0xc82217cdf0

Jun 02 13:28:09 mario geth[9833]: github.com/ethereum/go-ethereum/eth.getTransaction(0x7f86ac256f50, 0xc820430000, 0xc8203d65a0, 0xbcd8ed0ca7b3b1f9, 0x852636080acee85c, 0xbe98dd39aa40b0c8, 0x5e76045a7e09d46c, 0x0, 0xe0e920, 0x0, ...)
```

#### Steps to reproduce the behaviour
Using javascript/web3 and nodejs to deploy contract to a private 1 node network. Single geth instance is receiving the transactions and mining the blocks (difficulty in genesis.json set to 0x4). The contract definition doesn't seem to effect the bug either.

```
var numContracts = 50000000;
var MyContract = web3.eth.contract(contractAbi);

for(var i = 0; i < numContracts; i++)
{
    var contractInstance = MyContract.new({data: '0x12345...', from: myAccount, gas: 1000000});
    //optional thread.sleep to spread out transactions, doesn't seem to effect outcome.
}
```

### PR DESCRIPTION
**Pull request by fjl**
Fixes #2650 
Please review: @obscuren

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Thu Jun 2 18:36:38 UTC 2016_

**Comment by obscuren** [comment]
👍

**Comment by karalabe** [comment]
Doesn't this also need locking? https://github.com/ethereum/go-ethereum/blob/develop/core/tx_pool.go#L428

**Comment by karalabe** [comment]
Hmm, seems that we use this in the version which removes multiple transactions. The we should either make this private, or make a private version non-locking and lock in this one too. It's non obvious that this isn't meant to be called publicly.

**Comment by fjl** [comment]
@karalabe @obscuren PTAL

**Comment by obscuren** [comment]
@karalabe it's meant to be called publicly. It's currently utilised in `eth/api.go` as well as tx pool it self. I suspect the latter was added later and exposed the method.

LGTM

**Comment by karalabe** [comment]
LGTM :+1:

**Pull request merged**
