### PR TITLE
simplify nested complexity and if blocks ending with a return statement

### PR DESCRIPTION
**Pull request by alexprut**
**Changes:**
* Simplify nested complexity
* If an `if` blocks ends with a `return` statement then remove the `else` nesting.

Most of the changes has also been reported in `golint` https://goreportcard.com/report/github.com/ethereum/go-ethereum#golint

### CODE REVIEW

**Review by karalabe — APPROVED** [review]
Thanks! LGTM

**Review by karalabe — DISMISSED** [review]
Whoops, `les` fails to compile. Please check travis lint errors and fix.

**Comment by alexprut** [comment]
thanks for the feedback @karalabe , I've fixed `Travis` reported errors, it still fail though on `AppVeyor`, it is possible that there is something wrong with `AppVeyor`, or there is non-deterministic behaviour? am I missing something more trivial? It says it fails:
```
--- FAIL: TestTinyTrie (0.06s)
    trie_test.go:601: 1: got bbfd0d22135cee7f53a18d9fa31b835b4936d717ce949fe932f5ee5a7b5f1242, exp 4fa6efd292cffa2db0083b8bedd23add2798ae73802442f52486e95c3df7111c
--- FAIL: TestCommitAfterHash (0.02s)
    trie_test.go:635: got 58a7d09221d881fea2e713786b8fae6b9eeaa6d201ff1a309c64dbba3d0f79d3, exp e5e9c29bb50446a4081e6d1d748d2892c6101c1e883a1f77cf21d4094b697822
    trie_test.go:639: got 58a7d09221d881fea2e713786b8fae6b9eeaa6d201ff1a309c64dbba3d0f79d3, exp e5e9c29bb50446a4081e6d1d748d2892c6101c1e883a1f77cf21d4094b697822
--- FAIL: TestCommitSequence (0.00s)
    trie_test.go:743: test 0, disk write sequence wrong:
        got fd72e26d8f67efc7c1eafc9d9033ef516c738561c097eeb4e9fd1b38f6caa494 exp 68c495e45209e243eb7e4f4e8ca8f9f7be71003bd9cafb8061b4534373740193
root: 76427641802cfe6cbf39101179e6e6cdbdde686aea3c422e34cb6ff41d674388
FAIL
coverage: 74.9% of statements
FAIL	github.com/ethereum/go-ethereum/trie	161.047s
```
I was able to run the tests and build successfully.

**Comment by holiman** [comment]
Yeah, you can ignore appveyor (although, I just fixed them, so a rebase should make it green -- but it doesn't matter)

**Review by holiman — APPROVED** [review]
Changes LGTM, but retesteth was recently removed, so it needs a rebase again :)

**Comment by alexprut** [comment]
@holiman @karalabe all green now, fixed and rebased :)

**Pull request merged**
