### PR TITLE
eth/tracers: fix unigram tracer's return value

### LINKED ISSUE #22208: Can't call internal tracer in `traceBlockByNumber`
#### System information

Geth version: `1.9.25`
OS & Version: Ubuntu

#### Expected behaviour
Run internal tracers.

#### Actual behaviour
```
Error: json: error calling MarshalJSON for type json.RawMessage: unexpected end of JSON input
        at web3.js:6347:37(47)
        at web3.js:5081:62(37)
        at <eval>:1:25(7)
```

#### Steps to reproduce the behaviour
From JS console:
```
> debug.traceBlockByNumber(11701516, {tracer: 'unigramTracer'})
```

### PR DESCRIPTION
**Pull request by s1na**
Fixes #22208. The issue is that the tracer doesn't return a value (i.e. in js-land it returns `undefined`) if a tx was transfer-only, and one transfer tx in the block was enough to make the whole call fail.

I'm not sure what's wrong with my go-bindata. I run `go generate eth/tracers/internal/tracers/tracers.go` but it changes the generated code by a bit.

### CODE REVIEW

**Review by holiman — COMMENTED** [review]
LGTM, except from the bindata. We use https://github.com/kevinburke/go-bindata, afaik

**Comment by holiman** [comment]
Yes, if you do `make devtools`, it downloads 
```
go: downloading github.com/kevinburke/go-bindata v3.22.0+incompatible

```
So that's what's used on e.g. travis-builds.

**Comment by s1na** [comment]
Ah hadn't seen `make devtools`. I'm facing an error though, will have to investigate:

```
accounts/abi/bind/backend.go:24:2: import "github.com/ethereum/go-ethereum" is a program, not an importable package
make: *** [Makefile:53: devtools] Error 1
```

But for now I manually got the other go-bindata version and updated the PR.

**Review by holiman — APPROVED** [review]
LGTM

**Pull request merged**
