### PR TITLE
core: avoid reflect.DeepEqual to compare errors in genesis test

### PR DESCRIPTION
**Pull request by gurza**
Rewrote error comparison in tests to not depend on the inner structure of errors.

### CODE REVIEW

**Comment by fjl** [comment]
Can you please let me know why you want to make this change? The test use DeepEqual and pass, there is no immediate need to change it from our perspective.

**Comment by gurza** [comment]
> Can you please let me know why you want to make this change? The test use DeepEqual and pass, there is no immediate need to change it from our perspective.

You are right. Now the genesis tests work correctly when using DeepEqual. However using reflect.DeepEqual on errors in tests is a common antipattern, which results in brittle tests. Even just adding more diagnostic information (I mean additional fields) to the error can break the test. Golang lint (https://github.com/golang/lint) returns a warning for this case.

**Comment by anton-yakovlev-mr** [comment]
@gurza Golint is deprecated and frozen, https://github.com/golang/go/issues/38968

**Comment by gurza** [comment]
@anton-yakovlev-mr thanks for your comment. I use staticcheck linter, https://staticcheck.io. It also returns a warning for this case.

**Comment by fjl** [comment]
> Even just adding more diagnostic information (I mean additional fields) to the error can break the test.

If we would change the error to add more information, we'd rather update the test and check that the additional information is also correct. So, I still think reflect.DeepEqual is better here.

**Pull request closed without merging**
