### PR TITLE
all: clean up various error handling in core and the miner

### PR DESCRIPTION
**Pull request by karalabe**
**Please don't squash on merge, the individual commits are standalone and fix different issues, one depending on another.**

---

##### Commit `miner: don't verify our own blocks, trust the engine`

The miner in the current code did a full verification of a mined header before inserting it into the database.

This is really suboptimal, since we ourselves minted this block. Given that the seal is valid (which we either calculate ourselves or explicitly verify for remote miners), there's really no way for the block to become invalid apart from a programming error.

Apart from being suboptimal, the header check has a more significant consequence, namely that the miner does allow (previously 4, currently 1) second future blocks, which **will cause** the header check to fail. Our old code simply ignored this particular error, which is arguably the worse possible solution, since a "future error" doesn't mean there aren't other errors, just that this was the first (and it actually is one of the first things checked in VerifyHeader).

All in all validating the header in the miner seems both suboptimal and the current requirements of ignoring future errors makes the validation essentially useless, so the PR just flat out drops validating the freshly mined headers. (Emphasis again, the seal **is** validated for remote miners).

PS: This also fixes a bug the plugable consensus PR introduced when dropping the weird future error ignoring clause, which caused the miner to hang for extremely low difficulty networks where block mining was faster than 1 second, causing future errors to appear, dropping the current work but not getting new ones.

##### Commit `cmd/geth, eth: drop bad block reporting, its offline anyway`

This commit drops the bad block reporting code. The `badblocks.ethdev.com` service had been killed a long time ago (heck, even `ethdev.com` is dead for a long time now). It was just legacy messy code that we tried to hack around. (Btw, it's needed in this PR because it did some funky error checks that the PR cleans up).

##### Commit `all: drop all the legacy custom core error types`

With the consensus engine moves into their own package, the error types in `core` became superfluous. Some code accidentally kept using the old errors vs. some the new. Looking through the error types, half of them was dead code, half of them had funky constructs not really used at all, and 2-3 were actually errors that external packages cared about.

This commit deleted **all** the strange error types and added just the three ones interesting to the outside that `core` can meaningfully generate. I'm guessing the reason we had all these types it so differentiate between consensus breaking errors vs. other types of errors in some legacy form of the code.

Our current code clearly requires that any error returned from a consensus critical check (e.g. tx exec, block import) to mean that the entity is invalid. We do not rely on the "type" of the failure to decide whether it's invalid or not. Hence we can remove all the custom errors that add no value, just a lot of extra complexity.

### CODE REVIEW

**Comment by bas-vk** [comment]
If we trust the engine and don't do any verification could this cause issues with other nodes trying to import blocks?

Currently if the miner is able to create blocks in such a fast way due to very low difficulty it rejects blocks due to the `ErrFutureBlock` that is raised when validating the header. If this check in the miner is removed  the block will be included in its local blockchain. If another node on the network receives this block it will do a full header verification and hits the same `ErrFutureBlock` and drops the block and stops syncing until it founds a block that passes all checks.

**Comment by karalabe** [comment]
Similarly the miner will pause if it goes too far into the future (https://github.com/ethereum/go-ethereum/blob/master/miner/worker.go#L420), which would avoid us minting a long chain of future blocks locally.

**Comment by bas-vk** [comment]
Just tried it out. This seems to happen on a private network with 2 nodes and one of them mining with a low difficulty. The miner keeps on generating blocks while the other nodes stops syncing and drops the peer because it sent invalid blocks.

```
DEBUG[04-06|12:41:41] Queued propagated block                  peer=9fc4cfc7042de7a7 number=8 hash=07da10…21f660 queued=1
DEBUG[04-06|12:41:41] Importing propagated block               peer=9fc4cfc7042de7a7 number=8 hash=07da10…21f660
DEBUG[04-06|12:41:41] Propagated block verification failed     peer=9fc4cfc7042de7a7 number=8 hash=07da10…21f660 err="block in the future"
DEBUG[04-06|12:41:41] Removing Ethereum peer                   peer=9fc4cfc7042de7a7
TRACE[04-06|12:41:41] Unregistering sync peer                  peer=9fc4cfc7042de7a7
DEBUG[04-06|12:41:41] Ethereum message handling failed         id=9fc4cfc7042de7a7 conn=staticdial err=EOF
DEBUG[04-06|12:41:41] Removing p2p peer                        id=9fc4cfc7042de7a7 conn=staticdial duration=3.711s    peers=0 req=false err="useless peer"
```

**Comment by karalabe** [comment]
Sigh... https://github.com/ethereum/go-ethereum/blob/09777952ee476ff80d4b6e63b5041ff5ca0e441b/eth/fetcher/fetcher.go#L657

https://github.com/ethereum/go-ethereum/blob/master/consensus/ethash/consensus.go#L47

The consensus engine is returning it's own error type for future blocks, not the core type.

**Comment by karalabe** [comment]
I'll go through the errors and check which are duplicated and move them into the `consensus` package.

**Comment by fjl** [comment]
See, that's what I mean. It's no longer clear where the error should live because "consensus" and "core" are equally good places.

**Comment by karalabe** [comment]
Imho consensus is still better because it aggregates stuff only from the consensus engines and not from other components in core. Imho code got too big already.

**Comment by karalabe** [comment]
@bas-vk Could you try the current code? I cleaned up all the error handling so that `core` doesn't do all that weird useless error wrapping any more.

@fjl PTAL whether it makes sense, notably the last commit is of interest.

**Comment by bas-vk** [comment]
@karalabe it seems to work now that the errors match.

**Pull request merged**
