### PR TITLE
Sync free accountscan 2

### PR DESCRIPTION
**Pull request by holiman**
This PR supersedes https://github.com/ethereum/go-ethereum/pull/14974. 
This PR contains the following changes: 

- The accountCache contains a file cache, and remembers from scan to scan what files were present earlier. Thus, whenever there's a change, the scan phase only bothers processing new and removed files. 
- The scan phase previously used ` ioutil.ReadDir(ac.keydir)`, which both gets the directory listing, but also performs `lstat` on each file. That operation takes qutie some time on a large mass of files, so has been rewritten to only fetch the filenames. 

In general, no locks are held during long periods; each time an account is added or removed as a consequence of a scan, a lock is temporarily acquired. All fs-scanning and file-reading is lock-free.

### CODE REVIEW

**Comment by holiman** [comment]
Ok, failure now is 
```
ok  	github.com/ethereum/go-ethereum/eth	3.546s	coverage: 32.0% of statements
--- FAIL: TestFastCriticalRestartsFail63 (4.29s)
	downloader_test.go:1781: pivot block not locked in after critical section failure
FAIL
coverage: 82.2% of statements
```
Which is not related to this PR

**Comment by holiman** [comment]
Modified watch.go, after conversation with @fjl. I mistakenly thought that events needed to take concurrentcy into account, but since there's only one loop, that's not the case.

**Comment by holiman** [comment]
Oh, one more comment... 

Since we're now not `lstat`:ing all the flles, there are two cases where the behaviour is modified: 

* `isDir` is not checked. So directories will be `open` ed, which will fail. This is not a problem, but was previously checked earlier. 
* Whether a file is a symlinks is now not checked. Earlier, we explicitly ignored symlinks, which this PR does not do. If we want that, we need to add back a check if a file is a symlink before we start reading it.

**Comment by holiman** [comment]
I've now changed the behaviour, so that modifications to files are detected. 

* The latest seen `mtime` is remembered, 
* If a file has a more recent `mtime` (but is not a new file), the file is re-processed (deleted and added). 
* Since we're not `lstat`:ing files again, we now block symlinks again.

**Comment by vxnxn** [comment]
Hi I'm not a coder, can someone help me transfer eth from etherscan.io?

**Comment by fjl** [comment]
This should be OK to merge now if tests pass on Travis.

**Pull request merged**
