### PR TITLE
eth/protocols/eth: remove Requests in block body

### PR DESCRIPTION
**Pull request by islishude**
Block no longer has Requests.

It wasn't removed in #30425

### CODE REVIEW

**Review by fjl — APPROVED** [review]

**Comment by MariusVanDerWijden** [comment]
I think we also need to remove the `requestHashes` in `eth/downloader/downloader_test.go:233`

**Comment by MariusVanDerWijden** [comment]
I think we also need to remove the `emptyRequests` check from `EmptyBody` in `core/types/block.go`.
Otherwise we might try to fetch a block that should not be fetched otherwise, but I'm not 100% sure here cc @lightclient @fjl

**Comment by islishude** [comment]
> I think we also need to remove the `emptyRequests` check from `EmptyBody` in `core/types/block.go`.

It was removed in https://github.com/ethereum/go-ethereum/pull/30425

**Comment by MariusVanDerWijden** [comment]
Ah perfect, looks like I was on a wrong branch

**Review by MariusVanDerWijden — APPROVED** [review]
LGTM

**Pull request merged**
