### PR TITLE
ethdb/pebble: upgrade pebble

### PR DESCRIPTION
**Pull request by rjl493456442**
This PR upgrades the pebble dependencies with two features merged:

- https://github.com/cockroachdb/pebble/pull/2846
- https://github.com/cockroachdb/pebble/pull/2828

The intention is not to merge this pull request immediately, but wait a bit more for a stable release from pebble.

### CODE REVIEW

**Comment by rjl493456442** [comment]
Run a snap sync on bench05/06, 05 is the experimental branch.

There is no big difference of the overall system resource comsumption.

截屏2023-09-08 上午11 30 10

##

Database read/write wise, master is "slightly" higher. But we can treat them as identical.

截屏2023-09-08 上午11 33 51

##

05 finishes sync a half hour ahead (9 hours in total), not too much difference.

截屏2023-09-08 上午11 35 26


All in all, I don't think pebble changes has a big impact on the snap sync performance. Let's switch to full sync then.

**Comment by rjl493456442** [comment]
https://geth-bench.ethdevops.io/d/Jpk-Be5Wk/dual-geth?var-exp=bench05&var-master=bench06&var-percentile=50&from=now-15m&to=now&refresh=1m

Start another round of benchmark, run full sync on bench05/06, 05 is PR.

**Review by MariusVanDerWijden — APPROVED** [review]
LGTM

**Comment by rjl493456442** [comment]
Switch to full sync for a few days, dump some metrics here

## Overall system metrics

Not too much difference

截屏2023-09-12 下午7 45 06

## Database

This pull request has ~10% disk read, otherwise pretty much same(bench05 is 4 hours ahead) 

截屏2023-09-12 下午7 46 39

## Sync performance

This pull request is ~3hours a head after running 3 or 4 days. A little faster, but not too much

截屏2023-09-12 下午7 48 18


The conclusion is, with the change of https://github.com/cockroachdb/pebble/pull/2846, a few
unnecessary disk reads are avoid.

**Comment by karalabe** [comment]
Given the strange IO issues on Pebble 23.1, this branch got a priority merge 🙃

**Pull request merged**
