### PR TITLE
graphql: upgrade UI to v2

### PR DESCRIPTION
**Pull request by s1na**
Upgrades graphiql to v2.4.4. The interface has become much nicer. There are extra features like tabs, history, dark mode etc.

Also now instead of sourcing the JS and CSS files from CDN they are embedded in the binary. That makes offline usage of the UI possible.

It works fine. Only there is a slight issue: sometimes white spaces are displayed weird
Screenshot 2023-05-17 at 13 53 31

I realized that when in `index.html` I replace this line:

```js
<script src="/graphql/ui/graphiql.min.js" type="application/javascript"></script>
```

with:

```js
<script src="https://unpkg.com/graphiql/graphiql.min.js" type="application/javascript"></script>
```

the issue goes away. Even tho they are the same file!

### CODE REVIEW

**Comment by s1na** [comment]
Turns out adding: `<meta charset="UTF-8">` fixes the issue. Read for review.

**Comment by holiman** [comment]
This PR loads the data into memory, 
```
WARN [05-19|09:10:55.730] Loaded graphiql asset                    asset=index.html size=1144
WARN [05-19|09:10:55.735] Loaded graphiql asset                    asset=graphiql.min.css size=411,956
WARN [05-19|09:10:55.744] Loaded graphiql asset                    asset=graphiql.min.js  size=980,555
WARN [05-19|09:10:55.744] Loaded graphiql asset                    asset=react.production.min.js size=11440
WARN [05-19|09:10:55.744] Loaded graphiql asset                    asset=react-dom.production.min.js size=120,585
```
Is it worth it? Browsers should only fetch it once, and then cache it for the future. But even if that is not the case, I tested fetching the heaviest file 100 times 
```
real	0m1.122s
user	0m0.395s
sys	0m0.626s
```
With on-the-fly loading: 
```
real	0m1.487s
user	0m0.368s
sys	0m0.631s
```
I'd say it's about same same. If anyone wants to make a public graphql server able to handle high demands, they should add a caching nginx or something in front. I'll push some changes...

**Comment by holiman** [comment]
PTAL. I changed it so it now loads on demand. Also, I undid the charset-fix, so we can keep the asset identical to the upstream version. The proper fix is to set the charset in the http header instead.

**Review by holiman — APPROVED** [review]
LGTM

**Comment by s1na** [comment]
> PTAL. I changed it so it now loads on demand. Also, I undid the charset-fix, so we can keep the asset identical to the upstream version. The proper fix is to set the charset in the http header instead.

Good point. We don't need to impose the initial loading on every user even if they don't want to use graphiql. Your changes LGTM

**Pull request merged**
