### PR TITLE
eth/gasprice: add query limit for FeeHistory to defend DDOS attack

### PR DESCRIPTION
**Pull request by NathanBSC**
Add query limit to defend DDoS attack. Max allow 100 different percentiles in rewardPercentiles.

this PR is ported from bsc [2423](https://github.com/bnb-chain/bsc/pull/2423)

### CODE REVIEW

**Comment by NathanBSC** [comment]
I checked the failed golangci-lint, It's strange
and on my mac, it's ok
image

**Comment by AaronChen0** [comment]
Please rebase your commit. Your branch is 236 commits behind the master branch. And the return values of function `FeeHistory` is changed in this commit https://github.com/ethereum/go-ethereum/commit/1ec7af261223d6dad9370ee8263f86347b190bab

**Comment by fjl** [comment]
This new limit is not necessary because it is already covered by other limits. The percentiles have to be in increasing order, and < 100. It is therefore impossible to submit more than 100.

There *was* a bug in the validation until recently, but it got fixed in https://github.com/ethereum/go-ethereum/pull/28954

**Comment by buddh0** [comment]
> This new limit is not necessary because it is already covered by other limits. The percentiles have to be in increasing order, and < 100. It is therefore impossible to submit more than 100.

the element of rewardPercentiles is type float now, not integer, so is it impossible to submit more than 100? @fjl

**Review by karalabe — APPROVED** [review]
LGTM

**Review by holiman — APPROVED** [review]
LGTM

**Pull request merged**
