### PR TITLE
accounts/abi/bind: replace contract backend with ethclient interfaces

### PR DESCRIPTION
**Pull request by awishformore**
@fjl is working on a stable Go API for Ethereum; this PR uses this API and the connected interfaces to replace the backends of the bound contract for native Go contract bindings. You then have the possibility to use `ethclient` which uses the new RPC client, or the full node / light node as a backend for your contracts. It does not yet implement a simulated backend; I assume that would be better done as a simulated implementation of the API instead.

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Sun Aug 21 12:24:48 UTC 2016_

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 30372b7f96faf91f1e82b8e57d43afb1a06ce7f0
  * Commit subjects should be kept under 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by masonforest** [comment]
When I built `abigen` on this branch and compiled a test file I got:

    ./token.go:121: too many arguments in call to bind.NewBoundContract

([Gist](https://gist.github.com/masonforest/cabd2a16e9fbd27b2a726181ee35369c))

The [template](https://github.com/awishformore/go-ethereum/blob/master/accounts/abi/bind/template.go#L161) probably just needs updating.

I'm new to the project and have been loving it so far. I'm eager to try subscription bindings! Let me know if there's anything I can do to help that along! I'm in the gitter room if anyone wants to say hi

**Comment by awishformore** [comment]
There have been too many back and forth changes, I missed that one. Thanks, it's fixed now.

**Comment by fjl** [comment]
People who like this PR also like #2930

**Comment by fjl** [comment]
We have merged #2930 which includes these changes with some slight modifications.

**Pull request closed without merging**
