### PR TITLE
core, params: update Holesky testnet to relaunched spec

### PR DESCRIPTION
**Pull request by karalabe**
Updates the Holesky genesis specs to the relaunched testnet.

### CODE REVIEW

**Review by parithosh — APPROVED** [review]

**Comment by MariusVanDerWijden** [comment]
LGTM, spec: https://github.com/eth-clients/holesky/blob/main/custom_config_data/genesis.json

**Comment by MariusVanDerWijden** [comment]
Ah you guys we're quicker already

**Comment by jakubgs** [comment]
We are about 28 hours away from genesis. How about a release?

**Comment by karalabe** [comment]
We need to fix other stuff that actually matter. We'll release when that gets in.

**Comment by karalabe** [comment]
Also, maybe if next time **anyone** told us the testnet didn't launch properly, we could have done something earlier. We were told last minute that btw, new testnet (actually, we weren't even told, I saw a tweet about it). Well, if nobody bothers to ping us that they need a hotfix, then I will sure as hell won't bother prioritizing it last minute.

**Comment by jakubgs** [comment]
Wow, that's hilarious. As per usual the Ethereum foundation is amazing at communication.

I would have gladly told you :D. How could I have done it?

**Comment by jakubgs** [comment]
>We need to fix other stuff that actually matter.

I was not aware you did. Other EL clients just made hotfix releases that changed only the Holesky parameters.

**Comment by karalabe** [comment]
Yes, but other clients are not in the middle of a major release "fallout" :)

**Pull request merged**
