### PR TITLE
graphql: use embed for graphql ui html

### PR DESCRIPTION
**Pull request by islishude**
I also downgrade fetch to v2 due to https://github.com/github/fetch/issues/656

image

image

### CODE REVIEW

**Comment by holiman** [comment]
> I also downgrade fetch to v2 due to https://github.com/github/fetch/issues/656

That is an old ticket from 2018, from what I can tell it has something to do with IE11. Is it still relevant? Is it a problem that you encountered while using the graphql page? 
Curious, since as far as I know, nobody has filed a ticket about it at go-ethereum.

**Comment by islishude** [comment]
> Curious, since as far as I know, nobody has filed a ticket about it at go-ethereum.

because the fetch library is just a polyfill. and since 2017 all mainstream browsers have supported fetch. so even if the library has an error, it does not affect normal use. 

imo, it can be removed now.

fyi, https://caniuse.com/?search=fetch

**Comment by s1na** [comment]
Can you please try this #27294 and see if you get the error there also?

**Comment by holiman** [comment]
Closing in favour of https://github.com/ethereum/go-ethereum/pull/27294

**Pull request closed without merging**
