### PR TITLE
core: many golint fixes

### PR DESCRIPTION
**Pull request by kielbarry**
I have taken care of most receiver messages in this module, as well warnings like 'comments should be in the form of...". I've removed some one-off errors as a well

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 48404fe6691026a116a0aed533fd06c8492dedb2
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 48404fe6691026a116a0aed533fd06c8492dedb2
  * Commits must be prefixed with the package(s) they modify

 * Commit: c12621d09ebe300024beb8047bba453901b05912
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 48404fe6691026a116a0aed533fd06c8492dedb2
  * Commits must be prefixed with the package(s) they modify

 * Commit: c12621d09ebe300024beb8047bba453901b05912
  * Commits must be prefixed with the package(s) they modify

 * Commit: f3b6ca3ec3501a7a61fec0d5e85c5dac9001f014
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 48404fe6691026a116a0aed533fd06c8492dedb2
  * Commits must be prefixed with the package(s) they modify

 * Commit: c12621d09ebe300024beb8047bba453901b05912
  * Commits must be prefixed with the package(s) they modify

 * Commit: f3b6ca3ec3501a7a61fec0d5e85c5dac9001f014
  * Commits must be prefixed with the package(s) they modify

 * Commit: 780eba4a1164e256b8ff7d10aa0bc18522c17ef0
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 48404fe6691026a116a0aed533fd06c8492dedb2
  * Commits must be prefixed with the package(s) they modify

 * Commit: c12621d09ebe300024beb8047bba453901b05912
  * Commits must be prefixed with the package(s) they modify

 * Commit: f3b6ca3ec3501a7a61fec0d5e85c5dac9001f014
  * Commits must be prefixed with the package(s) they modify

 * Commit: 780eba4a1164e256b8ff7d10aa0bc18522c17ef0
  * Commits must be prefixed with the package(s) they modify

 * Commit: d55d9fa815aa2502f523e235870fbaafa95575b3
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 48404fe6691026a116a0aed533fd06c8492dedb2
  * Commits must be prefixed with the package(s) they modify

 * Commit: c12621d09ebe300024beb8047bba453901b05912
  * Commits must be prefixed with the package(s) they modify

 * Commit: f3b6ca3ec3501a7a61fec0d5e85c5dac9001f014
  * Commits must be prefixed with the package(s) they modify

 * Commit: 780eba4a1164e256b8ff7d10aa0bc18522c17ef0
  * Commits must be prefixed with the package(s) they modify

 * Commit: d55d9fa815aa2502f523e235870fbaafa95575b3
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 48404fe6691026a116a0aed533fd06c8492dedb2
  * Commits must be prefixed with the package(s) they modify

 * Commit: c12621d09ebe300024beb8047bba453901b05912
  * Commits must be prefixed with the package(s) they modify

 * Commit: f3b6ca3ec3501a7a61fec0d5e85c5dac9001f014
  * Commits must be prefixed with the package(s) they modify

 * Commit: 780eba4a1164e256b8ff7d10aa0bc18522c17ef0
  * Commits must be prefixed with the package(s) they modify

 * Commit: d55d9fa815aa2502f523e235870fbaafa95575b3
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 48404fe6691026a116a0aed533fd06c8492dedb2
  * Commits must be prefixed with the package(s) they modify

 * Commit: c12621d09ebe300024beb8047bba453901b05912
  * Commits must be prefixed with the package(s) they modify

 * Commit: f3b6ca3ec3501a7a61fec0d5e85c5dac9001f014
  * Commits must be prefixed with the package(s) they modify

 * Commit: 780eba4a1164e256b8ff7d10aa0bc18522c17ef0
  * Commits must be prefixed with the package(s) they modify

 * Commit: d55d9fa815aa2502f523e235870fbaafa95575b3
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by fjl** [comment]
Sorry, we didn't review this change in time and it is now out of date.

**Pull request closed without merging**
