### PR TITLE
Delete .mailmap

### PR DESCRIPTION
**Pull request by Nkased**

### CODE REVIEW

**Comment by holiman** [comment]
@fjl do you know the history behind this .mailmap file?

**Comment by s1na** [comment]
AFAIK this holds the list of all contributors to go-ethereum with their emails. In some theoretical cases like a change of license, they all have to be notified.

**Comment by holiman** [comment]
> the list of all contributors to go-ethereum with their emails 

Seems to me that it holds some kind of subset, definitely not all by a stretch

**Comment by holiman** [comment]
This is a lot more comprehensive: https://github.com/ethereum/go-ethereum/blob/master/AUTHORS  -- but I don't know why we have two of them

**Comment by s1na** [comment]
It seems to be mostly for sanitizing and cleaning the list, to display a consistent name and email even when the same person uses multiple names + emails.

**Comment by fjl** [comment]
The .mailmap file is used by git to de-duplicate committer names. We also use it when generating AUTHORS.

**Comment by fjl** [comment]
See git documentation about mailmap for more info: https://git-scm.com/docs/gitmailmap

**Pull request closed without merging**
