### PR TITLE
eth/tracers: fix callTracer fault handling

### LINKED ISSUE #23660: Rinkeby network. Error: cannot read property 'calls' of undefined in server-side tracer function 'fault'
#### System information

Geth version: `"Geth/v1.10.9-stable-eae3b194/linux-amd64/go1.17.1`
OS & Version: Linux

Params: --rinkeby --syncmode full --gcmode=archive --snapshot=true

#### Actual behaviour

When i try to call the method debug_traceTransaction on Rinkeby network:

````
сurl -X POST -H "Content-Type: application/json" --data '{"method": "debug_traceTransaction","params": ["0xdf8f0fc660ccc30c7d41f2fffa4b582c629d59597fb981019f0415a82ea9d7cd",{ "tracer": "callTracer","timeout": "100s" }],"jsonrpc": "2.0","id": 1}' http://ip:port
````
i get the error - 
````
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"TypeError: cannot read property 'calls' of undefined    in server-side tracer function 'fault'"}}
````
#### Expected behaviour
Correct traced response from node

### PR DESCRIPTION
**Pull request by s1na**
Fixes #23660

The idea for this fix is that we don't need to handle `fault` at all. Errors will be caught by `EVM` and passed to `exit` anyway. Only problem was that `exit` wasn't being invoked after a `fault` happened.

Edit: I'll also fix the indentation issues before the PR is merged.

### CODE REVIEW

**Comment by s1na** [comment]
When comparing new vs legacy results for this PR I noticed a difference in output value. The following is a diff for tx https://etherscan.io/tx/0xae924257680a3ac49c18532a12c6bcf396cf6ba8cb89c76b10b64b0bf647dc10

https://gist.github.com/s1na/984bead325e2066c2885f9fbbaf029bf

**Comment by s1na** [comment]
My best guess re the output difference is that the specified `retSize` for the `CALL` opcode is smaller than the byte array that interpreter returns.

**Comment by holiman** [comment]
> My best guess re the output difference is that the specified retSize for the CALL opcode is smaller than the byte array that interpreter returns.

This is correct

**Comment by holiman** [comment]
The calls in diff 1 uses an `out offset, out size` of `0,0`, but the call/delegatecalls actually return data. So it's correct behaviour by the tracer to show that data. 
In these traces, the contract actually checks `RETURNDATASIZE` immediately after the call, and _does_ use the output data. It's simply a more modern way of doing calls, and the new tracer correctly provides output where the old tracer did not.

**Review by holiman — APPROVED** [review]
LGTM

**Comment by s1na** [comment]
Fixed the indentation too.

**Pull request merged**
