### PR TITLE
core,eth: fixed TrieTimeLimit

### PR DESCRIPTION
**Pull request by hackmod**
**this is a bug report PR.**

fixed `TrieTimeLimit` to flush triedb roughly every ~~30 min~~ ~5 hours, ~1250 blocks

currently, the default `TrieTimeLimit` value is 60 min. but it seems too big.

- about ~8ms consumed per block and it means 30 minutes required per ~120 blocks
- for `TrieTimeLimit: 60 * time.Minute` case. it means `triedb.Commit()` executed after ~460,800 blocks (~80 days)

this PR reduce the default `TrieTimeLimit` value to ~~1 sec~~ 10 sec to flush triedb roughly every ~~30 min~~ ~5 hours
or we can fix `TrieTimeLimit` to 2 sec(~1 hour) or some more acceptable value to fit a realistic situation.

### CODE REVIEW

**Comment by holiman** [comment]
Question: are these time limits configurable via TOML? If so, I don't think we need to change this (at least not as drastically), since 
1. Long times here means that the pruning get's a lot better (I think)
2. For most users, it's preferrable to keep the disk size down as far as possible
3. The trie is committed anyway when the user exits, so on normal exit there's no need to rerun that 1 hour worth of block processing anyway. 

If it's not configurable, I think a better approach would be to expose them for external configuration.

**Comment by hackmod** [comment]
> The trie is committed anyway when the user exits, so on normal exit there's no need to rerun that 1 hour worth of block processing anyway.

yes and no. for normal use case, this fix worth nothing.
but under Windows + mist with fullsync use cases, close window action do not fire kill signal correctly, triedb will not be committed, and geth try to rewind almost all blocks after rerun mist or geth again. it's not a big issue but normal users confused on it.
(similar symptom also arise under linux, by `kill -9` geth process.)

> If it's not configurable, I think a better approach would be to expose them for external configuration.
oh... let me see...
https://github.com/ethereum/go-ethereum/blob/master/cmd/utils/flags.go#L1396-L1398
currently, `TrieTimeout` config option is not supported.

**Comment by karalabe** [comment]
This change would entail a huge performance and disk storage hit. Flushing every 10 seconds means we don't do any in-memory garbage collection, and would mostly revert us back into an archive node.

The 1 hour was just a sanity to cover node crashes gracefully. In all honesty, we shouldn't even be doing that, rather expect the user to cleanly terminate their node.

The 8ms per block value is also off by 1+ orders of magnitude. Mainnet head needs 100-200ms/block.

**Comment by karalabe** [comment]
We can play around with reducing the flush time after disk pruning is done. Then it's a better tradeoff. Currently however the price is too high imho.

**Comment by hackmod** [comment]
@karalabe // this is a bug report PR. I didn't try to fix any of related issues.
the point is that while `--syncmode=fast` it is work as expected but after sync completed, we have to reduce `TrieTimeout` value to fix some issue like as #18521

**Comment by hackmod** [comment]
`gcreal` added to check both `gcproc` and `gcreal` real time to flush triedb. (remove old fix, rebased)

**Comment by karalabe** [comment]
I am closing this PR as it's a quick hack for a non-issue. We expect people to gracefully shut their nodes down. We do have some ideas to make this better: instead of wiring out the trie itself to disk, just dump the dirty cache and load it back up. That solution would allow reducing the timer to whatever the user is comfortable with. Until then, this cannot go in and will just bitrot.

**Pull request closed without merging**
