### PR TITLE
console: don't exit on ctrl-c, only on ctrl-d

### PR DESCRIPTION
**Pull request by renaynay**
This PR adds an interrupt counter to the local console so that one `^C` will cause the console to be cleared, but two `^C`s in a row will cause console termination.

### CODE REVIEW

**Comment by karalabe** [comment]
I don't think this is a natural behavior. A console should IMHO only be terminated by Ctrl+D. It should not matter how many Ctrl+C I press, as long as the console is live, it should not terminate. My 2c

**Comment by renaynay** [comment]
I think the idea here was to copy the way nodejs does it, which is 2 ^Cs in a row = console terminated. Regardless, ctrl D also works to terminate the console immediately. Does this influence your opinion? 

I could also just allow ^C to clear the command line only and never terminate (and leave it to ctrl D for termination).

**Comment by holiman** [comment]
> I could also just allow ^C to clear the command line only and never terminate (and leave it to ctrl D for termination).

That's what the python repl does. That has my vote

**Review by holiman — APPROVED** [review]
LGTM. However, previously we exited on `ctrl-c`, and now we don't, so some users may be caught unawares. Should we maybe print out ("Press ctrl-d to exit") in a startup message?

**Comment by renaynay** [comment]
> LGTM. However, previously we exited on `ctrl-c`, and now we don't, so some users may be caught unawares. Should we maybe print out ("Press ctrl-d to exit") in a startup message?

Good call :)

**Comment by holiman** [comment]
LGTM!

**Pull request merged**
