### PR TITLE
 Fix commitNewWork with old time

### PR DESCRIPTION
**Pull request by lxex**
List some possible situations: 
    a. could be blocked by txsCh.
    b. timer.C in newWorkLoop.
    c. commitNewWork may be failed and commit next cycle.

### CODE REVIEW

**Comment by rjl493456442** [comment]
It's wrong. The timestamp should be kept unchanged in the same round. Otherwise a lower mining difficulty will be assigned and the block will become uncle block with high chance.

**Comment by lxex** [comment]
so, the `round = lastBlockReceivedTime + (some uncertain time) + miningTime`
and the `currentHeaderTime = lastBlockReceivedTime `, which causes the contract to read the old time
for example: some Dapp mining token every day, When user mined token at 0:00 a.m., the blockchain  headerTime was just yesterday , which lead to transaction failure.

 In the long run, changing the position of timestamp does not affect the difficulty, but changing the cycle will affect the difficulty.

**Comment by lxex** [comment]
> It's wrong. The timestamp should be kept unchanged in the same round. Otherwise a lower mining difficulty will be assigned and the block will become uncle block with high chance.

so, the round = lastBlockReceivedTime + (some uncertain time) + miningTime
and the currentHeaderTime = lastBlockReceivedTime , which causes the contract to read the old time
for example: some Dapp mining token every day, When user sent the tx to mine token at 0:00 a.m., the blockchain headerTime was just yesterday , which lead to transaction failure.

In the long run, changing the position of timestamp does not affect the difficulty, but changing the cycle will affect the difficulty.

**Comment by rjl493456442** [comment]
Unfortunately we can't avoid this. The block time is not accurate. And even more miners can assign the block time by their own strategies. So please don't rely on the block time for some "accurate things".

**Pull request closed without merging**
