### PR TITLE
Prevent re-entrancy, fix balance check logic

### PR DESCRIPTION
**Pull request by lastperson**

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: ee24dffae2f31f38c3b1a48314f4bf25a92820c7
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by lastperson** [comment]
@nagydani please review.

**Comment by obscuren** [comment]
Why was this closed?

**Comment by lastperson** [comment]
@obscuren due to a #3210 (or it's predecessor) has been opened earlier, it was only lacking one change from this one, which I've outlined in a comment/review.

**Comment by obscuren** [comment]
Cheers. I see now 👍

**Pull request closed without merging**
