### PR TITLE
les: light client protocol and API

### PR DESCRIPTION
**Pull request by zsfelfoldi**
Note: this PR is being regularly updated, forking it in its current state is not recommended. Don't be fooled by the old commit date, it's just because squashing commits always leaves the oldest date.

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Fri Jan 1 17:56:54 UTC 2016_

**Comment by immesys** [comment]
@zsfelfoldi This looks awesome. Thanks for working on this.

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 73e27bd865c07003c851ef37a55448d35294e20b
  * Commits must be prefixed with the package(s) they modify

 * Commit: d1e0fd4d5f80504f176aed1e206ba48648b7cf37
  * Commits must be prefixed with the package(s) they modify

 * Commit: c390528d66c31550295adbcaf8dc9793e183b35c
  * Commits must be prefixed with the package(s) they modify

 * Commit: 15f40a56501f3ca37a7040e53eebcec599561ed7
  * Commits must be prefixed with the package(s) they modify

 * Commit: 9252d63c9e7e930136b202812fca65f096d60a48
  * Commits must be prefixed with the package(s) they modify

 * Commit: 13c4d240d43cfc5b561710607f17c46de4715156
  * Commits must be prefixed with the package(s) they modify

 * Commit: be65a31edc9e2f9f90ff8be326e8431ed50e609e
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 73e27bd865c07003c851ef37a55448d35294e20b
  * Commits must be prefixed with the package(s) they modify

 * Commit: d1e0fd4d5f80504f176aed1e206ba48648b7cf37
  * Commits must be prefixed with the package(s) they modify

 * Commit: c390528d66c31550295adbcaf8dc9793e183b35c
  * Commits must be prefixed with the package(s) they modify

 * Commit: 15f40a56501f3ca37a7040e53eebcec599561ed7
  * Commits must be prefixed with the package(s) they modify

 * Commit: 9252d63c9e7e930136b202812fca65f096d60a48
  * Commits must be prefixed with the package(s) they modify

 * Commit: 13c4d240d43cfc5b561710607f17c46de4715156
  * Commits must be prefixed with the package(s) they modify

 * Commit: be65a31edc9e2f9f90ff8be326e8431ed50e609e
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: f62fd849d5d5037ba533ab9896691aa7b38c24c8
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: f62fd849d5d5037ba533ab9896691aa7b38c24c8
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: f62fd849d5d5037ba533ab9896691aa7b38c24c8
  * Commits must be prefixed with the package(s) they modify

 * Commit: 8a2044789add03de9cfc7078e7f0c89b20491a3a
  * Commits must be prefixed with the package(s) they modify

 * Commit: 9db355154575bd7a7d38f0ee9ac4c410a7e31b40
  * Commits must be prefixed with the package(s) they modify

 * Commit: 0eef51948148db33b5b2f31c78b948edd2be4bbf
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: f62fd849d5d5037ba533ab9896691aa7b38c24c8
  * Commits must be prefixed with the package(s) they modify

 * Commit: 8a2044789add03de9cfc7078e7f0c89b20491a3a
  * Commits must be prefixed with the package(s) they modify

 * Commit: 9db355154575bd7a7d38f0ee9ac4c410a7e31b40
  * Commits must be prefixed with the package(s) they modify

 * Commit: 0eef51948148db33b5b2f31c78b948edd2be4bbf
  * Commits must be prefixed with the package(s) they modify

 * Commit: 4d6c54dbf6d609a1a9ce0dea69472fb96727b4a2
  * Commits must be prefixed with the package(s) they modify

 * Commit: 6e3dc9806dac8d2c71603d3a56ab33dae7549775
  * Commits must be prefixed with the package(s) they modify

 * Commit: 12d25262e954c99a69228a72488517ec98e0205e
  * Commits must be prefixed with the package(s) they modify

 * Commit: ba39d7bab73d2e9c2d1c2cb40085390e7bf921c1
  * Commits must be prefixed with the package(s) they modify

 * Commit: ce438acb08c60f41921751efb7a3817fe177a06a
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: f62fd849d5d5037ba533ab9896691aa7b38c24c8
  * Commits must be prefixed with the package(s) they modify

 * Commit: 8a2044789add03de9cfc7078e7f0c89b20491a3a
  * Commits must be prefixed with the package(s) they modify

 * Commit: 9db355154575bd7a7d38f0ee9ac4c410a7e31b40
  * Commits must be prefixed with the package(s) they modify

 * Commit: 0eef51948148db33b5b2f31c78b948edd2be4bbf
  * Commits must be prefixed with the package(s) they modify

 * Commit: 4d6c54dbf6d609a1a9ce0dea69472fb96727b4a2
  * Commits must be prefixed with the package(s) they modify

 * Commit: 6e3dc9806dac8d2c71603d3a56ab33dae7549775
  * Commits must be prefixed with the package(s) they modify

 * Commit: 12d25262e954c99a69228a72488517ec98e0205e
  * Commits must be prefixed with the package(s) they modify

 * Commit: ba39d7bab73d2e9c2d1c2cb40085390e7bf921c1
  * Commits must be prefixed with the package(s) they modify

 * Commit: ce438acb08c60f41921751efb7a3817fe177a06a
  * Commits must be prefixed with the package(s) they modify

 * Commit: 785439d088ee48c74b5bb70c69ce66d031274c3f
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: f62fd849d5d5037ba533ab9896691aa7b38c24c8
  * Commits must be prefixed with the package(s) they modify

 * Commit: 8a2044789add03de9cfc7078e7f0c89b20491a3a
  * Commits must be prefixed with the package(s) they modify

 * Commit: 9db355154575bd7a7d38f0ee9ac4c410a7e31b40
  * Commits must be prefixed with the package(s) they modify

 * Commit: 0eef51948148db33b5b2f31c78b948edd2be4bbf
  * Commits must be prefixed with the package(s) they modify

 * Commit: 4d6c54dbf6d609a1a9ce0dea69472fb96727b4a2
  * Commits must be prefixed with the package(s) they modify

 * Commit: 6e3dc9806dac8d2c71603d3a56ab33dae7549775
  * Commits must be prefixed with the package(s) they modify

 * Commit: 12d25262e954c99a69228a72488517ec98e0205e
  * Commits must be prefixed with the package(s) they modify

 * Commit: ba39d7bab73d2e9c2d1c2cb40085390e7bf921c1
  * Commits must be prefixed with the package(s) they modify

 * Commit: ce438acb08c60f41921751efb7a3817fe177a06a
  * Commits must be prefixed with the package(s) they modify

 * Commit: 785439d088ee48c74b5bb70c69ce66d031274c3f
  * Commits must be prefixed with the package(s) they modify

 * Commit: c48b7caf6a1928a522a4b705f28a7e48438cb183
  * Commits must be prefixed with the package(s) they modify

 * Commit: 64b136b9961c45bd5f10d23fa3b26d3ba36602fe
  * Commits must be prefixed with the package(s) they modify

 * Commit: a09e88d4bfee6e147246cd5f4eef5340eaadd360
  * Commits must be prefixed with the package(s) they modify

 * Commit: 78a077372c432e8d6c626f3851dae7ee4ec45b55
  * Commits must be prefixed with the package(s) they modify

 * Commit: 74009742739649695c0fafd1e6ea37d73d225e36
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: f62fd849d5d5037ba533ab9896691aa7b38c24c8
  * Commits must be prefixed with the package(s) they modify

 * Commit: 8a2044789add03de9cfc7078e7f0c89b20491a3a
  * Commits must be prefixed with the package(s) they modify

 * Commit: 9db355154575bd7a7d38f0ee9ac4c410a7e31b40
  * Commits must be prefixed with the package(s) they modify

 * Commit: 0eef51948148db33b5b2f31c78b948edd2be4bbf
  * Commits must be prefixed with the package(s) they modify

 * Commit: 4d6c54dbf6d609a1a9ce0dea69472fb96727b4a2
  * Commits must be prefixed with the package(s) they modify

 * Commit: 6e3dc9806dac8d2c71603d3a56ab33dae7549775
  * Commits must be prefixed with the package(s) they modify

 * Commit: 12d25262e954c99a69228a72488517ec98e0205e
  * Commits must be prefixed with the package(s) they modify

 * Commit: ba39d7bab73d2e9c2d1c2cb40085390e7bf921c1
  * Commits must be prefixed with the package(s) they modify

 * Commit: ce438acb08c60f41921751efb7a3817fe177a06a
  * Commits must be prefixed with the package(s) they modify

 * Commit: 785439d088ee48c74b5bb70c69ce66d031274c3f
  * Commits must be prefixed with the package(s) they modify

 * Commit: c48b7caf6a1928a522a4b705f28a7e48438cb183
  * Commits must be prefixed with the package(s) they modify

 * Commit: 64b136b9961c45bd5f10d23fa3b26d3ba36602fe
  * Commits must be prefixed with the package(s) they modify

 * Commit: a09e88d4bfee6e147246cd5f4eef5340eaadd360
  * Commits must be prefixed with the package(s) they modify

 * Commit: 78a077372c432e8d6c626f3851dae7ee4ec45b55
  * Commits must be prefixed with the package(s) they modify

 * Commit: 74009742739649695c0fafd1e6ea37d73d225e36
  * Commits must be prefixed with the package(s) they modify

 * Commit: 02d4975edf95d86c973e7178c02080bdda886bc1
  * Commits must be prefixed with the package(s) they modify

 * Commit: 4ad808f4dcf1077acf712457c64874e344c87f54
  * Commits must be prefixed with the package(s) they modify

 * Commit: 658292f93431898d628a5149cb58d129c4798be8
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: f62fd849d5d5037ba533ab9896691aa7b38c24c8
  * Commits must be prefixed with the package(s) they modify

 * Commit: 8a2044789add03de9cfc7078e7f0c89b20491a3a
  * Commits must be prefixed with the package(s) they modify

 * Commit: 9db355154575bd7a7d38f0ee9ac4c410a7e31b40
  * Commits must be prefixed with the package(s) they modify

 * Commit: 0eef51948148db33b5b2f31c78b948edd2be4bbf
  * Commits must be prefixed with the package(s) they modify

 * Commit: 4d6c54dbf6d609a1a9ce0dea69472fb96727b4a2
  * Commits must be prefixed with the package(s) they modify

 * Commit: 6e3dc9806dac8d2c71603d3a56ab33dae7549775
  * Commits must be prefixed with the package(s) they modify

 * Commit: 12d25262e954c99a69228a72488517ec98e0205e
  * Commits must be prefixed with the package(s) they modify

 * Commit: ba39d7bab73d2e9c2d1c2cb40085390e7bf921c1
  * Commits must be prefixed with the package(s) they modify

 * Commit: ce438acb08c60f41921751efb7a3817fe177a06a
  * Commits must be prefixed with the package(s) they modify

 * Commit: 785439d088ee48c74b5bb70c69ce66d031274c3f
  * Commits must be prefixed with the package(s) they modify

 * Commit: c48b7caf6a1928a522a4b705f28a7e48438cb183
  * Commits must be prefixed with the package(s) they modify

 * Commit: 64b136b9961c45bd5f10d23fa3b26d3ba36602fe
  * Commits must be prefixed with the package(s) they modify

 * Commit: a09e88d4bfee6e147246cd5f4eef5340eaadd360
  * Commits must be prefixed with the package(s) they modify

 * Commit: 78a077372c432e8d6c626f3851dae7ee4ec45b55
  * Commits must be prefixed with the package(s) they modify

 * Commit: 74009742739649695c0fafd1e6ea37d73d225e36
  * Commits must be prefixed with the package(s) they modify

 * Commit: 02d4975edf95d86c973e7178c02080bdda886bc1
  * Commits must be prefixed with the package(s) they modify

 * Commit: 4ad808f4dcf1077acf712457c64874e344c87f54
  * Commits must be prefixed with the package(s) they modify

 * Commit: 658292f93431898d628a5149cb58d129c4798be8
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: f62fd849d5d5037ba533ab9896691aa7b38c24c8
  * Commits must be prefixed with the package(s) they modify

 * Commit: 8a2044789add03de9cfc7078e7f0c89b20491a3a
  * Commits must be prefixed with the package(s) they modify

 * Commit: 9db355154575bd7a7d38f0ee9ac4c410a7e31b40
  * Commits must be prefixed with the package(s) they modify

 * Commit: 0eef51948148db33b5b2f31c78b948edd2be4bbf
  * Commits must be prefixed with the package(s) they modify

 * Commit: 4d6c54dbf6d609a1a9ce0dea69472fb96727b4a2
  * Commits must be prefixed with the package(s) they modify

 * Commit: 6e3dc9806dac8d2c71603d3a56ab33dae7549775
  * Commits must be prefixed with the package(s) they modify

 * Commit: 12d25262e954c99a69228a72488517ec98e0205e
  * Commits must be prefixed with the package(s) they modify

 * Commit: ba39d7bab73d2e9c2d1c2cb40085390e7bf921c1
  * Commits must be prefixed with the package(s) they modify

 * Commit: ce438acb08c60f41921751efb7a3817fe177a06a
  * Commits must be prefixed with the package(s) they modify

 * Commit: 785439d088ee48c74b5bb70c69ce66d031274c3f
  * Commits must be prefixed with the package(s) they modify

 * Commit: c48b7caf6a1928a522a4b705f28a7e48438cb183
  * Commits must be prefixed with the package(s) they modify

 * Commit: 64b136b9961c45bd5f10d23fa3b26d3ba36602fe
  * Commits must be prefixed with the package(s) they modify

 * Commit: a09e88d4bfee6e147246cd5f4eef5340eaadd360
  * Commits must be prefixed with the package(s) they modify

 * Commit: 78a077372c432e8d6c626f3851dae7ee4ec45b55
  * Commits must be prefixed with the package(s) they modify

 * Commit: 74009742739649695c0fafd1e6ea37d73d225e36
  * Commits must be prefixed with the package(s) they modify

 * Commit: 02d4975edf95d86c973e7178c02080bdda886bc1
  * Commits must be prefixed with the package(s) they modify

 * Commit: 4ad808f4dcf1077acf712457c64874e344c87f54
  * Commits must be prefixed with the package(s) they modify

 * Commit: 658292f93431898d628a5149cb58d129c4798be8
  * Commits must be prefixed with the package(s) they modify

 * Commit: 827737b0f6fac90f5047eca5fb81a4bc3e738067
  * Commits must be prefixed with the package(s) they modify

 * Commit: 31e9f2f650e266a7b83af208e6797f01b4cab044
  * Commits must be prefixed with the package(s) they modify

 * Commit: 947d69621081a9187059abe07393be54f2eca804
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: f62fd849d5d5037ba533ab9896691aa7b38c24c8
  * Commits must be prefixed with the package(s) they modify

 * Commit: 8a2044789add03de9cfc7078e7f0c89b20491a3a
  * Commits must be prefixed with the package(s) they modify

 * Commit: 9db355154575bd7a7d38f0ee9ac4c410a7e31b40
  * Commits must be prefixed with the package(s) they modify

 * Commit: 0eef51948148db33b5b2f31c78b948edd2be4bbf
  * Commits must be prefixed with the package(s) they modify

 * Commit: 4d6c54dbf6d609a1a9ce0dea69472fb96727b4a2
  * Commits must be prefixed with the package(s) they modify

 * Commit: 6e3dc9806dac8d2c71603d3a56ab33dae7549775
  * Commits must be prefixed with the package(s) they modify

 * Commit: 12d25262e954c99a69228a72488517ec98e0205e
  * Commits must be prefixed with the package(s) they modify

 * Commit: ba39d7bab73d2e9c2d1c2cb40085390e7bf921c1
  * Commits must be prefixed with the package(s) they modify

 * Commit: ce438acb08c60f41921751efb7a3817fe177a06a
  * Commits must be prefixed with the package(s) they modify

 * Commit: 785439d088ee48c74b5bb70c69ce66d031274c3f
  * Commits must be prefixed with the package(s) they modify

 * Commit: c48b7caf6a1928a522a4b705f28a7e48438cb183
  * Commits must be prefixed with the package(s) they modify

 * Commit: 64b136b9961c45bd5f10d23fa3b26d3ba36602fe
  * Commits must be prefixed with the package(s) they modify

 * Commit: a09e88d4bfee6e147246cd5f4eef5340eaadd360
  * Commits must be prefixed with the package(s) they modify

 * Commit: 78a077372c432e8d6c626f3851dae7ee4ec45b55
  * Commits must be prefixed with the package(s) they modify

 * Commit: 74009742739649695c0fafd1e6ea37d73d225e36
  * Commits must be prefixed with the package(s) they modify

 * Commit: 02d4975edf95d86c973e7178c02080bdda886bc1
  * Commits must be prefixed with the package(s) they modify

 * Commit: 4ad808f4dcf1077acf712457c64874e344c87f54
  * Commits must be prefixed with the package(s) they modify

 * Commit: 658292f93431898d628a5149cb58d129c4798be8
  * Commits must be prefixed with the package(s) they modify

 * Commit: 827737b0f6fac90f5047eca5fb81a4bc3e738067
  * Commits must be prefixed with the package(s) they modify

 * Commit: 31e9f2f650e266a7b83af208e6797f01b4cab044
  * Commits must be prefixed with the package(s) they modify

 * Commit: 947d69621081a9187059abe07393be54f2eca804
  * Commits must be prefixed with the package(s) they modify

 * Commit: 8c3701c7c50a6344e7ceb24c2f357bd605184d49
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: f62fd849d5d5037ba533ab9896691aa7b38c24c8
  * Commits must be prefixed with the package(s) they modify

 * Commit: 8a2044789add03de9cfc7078e7f0c89b20491a3a
  * Commits must be prefixed with the package(s) they modify

 * Commit: 9db355154575bd7a7d38f0ee9ac4c410a7e31b40
  * Commits must be prefixed with the package(s) they modify

 * Commit: 0eef51948148db33b5b2f31c78b948edd2be4bbf
  * Commits must be prefixed with the package(s) they modify

 * Commit: 4d6c54dbf6d609a1a9ce0dea69472fb96727b4a2
  * Commits must be prefixed with the package(s) they modify

 * Commit: 6e3dc9806dac8d2c71603d3a56ab33dae7549775
  * Commits must be prefixed with the package(s) they modify

 * Commit: 12d25262e954c99a69228a72488517ec98e0205e
  * Commits must be prefixed with the package(s) they modify

 * Commit: ba39d7bab73d2e9c2d1c2cb40085390e7bf921c1
  * Commits must be prefixed with the package(s) they modify

 * Commit: ce438acb08c60f41921751efb7a3817fe177a06a
  * Commits must be prefixed with the package(s) they modify

 * Commit: 785439d088ee48c74b5bb70c69ce66d031274c3f
  * Commits must be prefixed with the package(s) they modify

 * Commit: c48b7caf6a1928a522a4b705f28a7e48438cb183
  * Commits must be prefixed with the package(s) they modify

 * Commit: 64b136b9961c45bd5f10d23fa3b26d3ba36602fe
  * Commits must be prefixed with the package(s) they modify

 * Commit: a09e88d4bfee6e147246cd5f4eef5340eaadd360
  * Commits must be prefixed with the package(s) they modify

 * Commit: 78a077372c432e8d6c626f3851dae7ee4ec45b55
  * Commits must be prefixed with the package(s) they modify

 * Commit: 74009742739649695c0fafd1e6ea37d73d225e36
  * Commits must be prefixed with the package(s) they modify

 * Commit: 02d4975edf95d86c973e7178c02080bdda886bc1
  * Commits must be prefixed with the package(s) they modify

 * Commit: 4ad808f4dcf1077acf712457c64874e344c87f54
  * Commits must be prefixed with the package(s) they modify

 * Commit: 658292f93431898d628a5149cb58d129c4798be8
  * Commits must be prefixed with the package(s) they modify

 * Commit: 827737b0f6fac90f5047eca5fb81a4bc3e738067
  * Commits must be prefixed with the package(s) they modify

 * Commit: 31e9f2f650e266a7b83af208e6797f01b4cab044
  * Commits must be prefixed with the package(s) they modify

 * Commit: 947d69621081a9187059abe07393be54f2eca804
  * Commits must be prefixed with the package(s) they modify

 * Commit: 8c3701c7c50a6344e7ceb24c2f357bd605184d49
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by fjl** [comment]
Superseded by #3145

**Pull request closed without merging**
