### PR TITLE
internal/ethapi: remove td field from block

### PR DESCRIPTION
**Pull request by s1na**
Implements https://github.com/ethereum/execution-apis/pull/570

### CODE REVIEW

**Comment by s1na** [comment]
If we remove GetTd usage from ethstats then the method could be dropped from the EthAPIBackend completely.

**Comment by rjl493456442** [comment]
> If we remove GetTd usage from ethstats

Why not?

**Comment by lightclient** [comment]
Looks like there are still some references to `"totalDifficulty"` in a few places that should also be cleaned up:

* `eth/tracers/internal/tracetest/testdata/`
* `internal/jsre/deps/web3.js`
* `ethstats`

**Comment by s1na** [comment]
> Looks like there are still some references to "totalDifficulty" in a few places

Yep I fixed the ones in `eth/tracers/internal/tracetest`. Those were filled via API and had those fields. The totalDifficulty was also unused even before this because it decodes into `*core.Genesis`.

> internal/jsre/deps/web3.js

Hm this one makes it so that when I do `eth.getBlock` in the console it shows `"totalDifficulty": 0`. Which is confusing. I am mindful that this is an external dependency and we shouldn't change it often. But since we haven't really updated web3.js or plan to do that I will go ahead and remove the offending line.

> ethstats

I'd like to keep this out of this PR.

**Comment by s1na** [comment]
Fixed last standing issue. PTAL

**Pull request merged**
