### PR TITLE
honors datadir when attaching

### PR DESCRIPTION
**Pull request by kobigurk**

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Thu Sep 3 06:25:24 UTC 2015_

**Comment by fjl** [comment]
:+1:

**Comment by karalabe** [comment]
:+1: 

Could you rename your commit message to `cmd/geth: honor datadir when attaching`? Thanks!

**Comment by kobigurk** [comment]
done

**Pull request merged**
