### PR TITLE
core/vm/runtime: invoke tx-end hook

### PR DESCRIPTION
**Pull request by holiman**
While updating goevmlab, I noticed that the way I invoked the executions, using the `core/vm/runtime` helpers, I didn't get any callbacks on the tx end. This PR fixes it by invoking them.

### CODE REVIEW

**Review by MariusVanDerWijden — APPROVED** [review]
LGTM, we could set more fields in the receipt than just the gasUsed e.g. `Type`, `PostState`,  `Status`, ... but I don't know if thats really important. The only thing that might be is PostState imo, but that would require us to call Commit() on the passed statedb. That is something that I don't think we should do

**Comment by holiman** [comment]
> LGTM, we could set more fields in the receipt than just the gasUsed e.g. `Type`, `PostState`, `Status`, ... but I don't know if thats really important.

It is not important. It's IMO a bit annoying that we need to even create this pretend-receipt. I'd rather just pass in nil, but it turns out that some tracers crash on nil-receipts.

**Comment by karalabe** [comment]
In general IMO it's not the best idea to pass too much, too high level data to callbacks directly. It expands our API surface a lot and also locks them in, since all of a sudden all the types are API with guarantees; and it also makes optimizations harder because you cannot avoid computing something that a tracer depends on later.

**Comment by holiman** [comment]
Yep, I agree

**Pull request merged**
