### PR TITLE
eth/downloader:add header request to cancel wait group

### PR DESCRIPTION
**Pull request by ucwong**

### CODE REVIEW

**Comment by holiman** [comment]
I don't see the point of this, tbh. The methods are very quick network sends -- and if we're closing down, it makes no sense to wait for them to complete. Either we send a packet or we don't, but it doesn't matter which, at that point. 

It makes more sense if the spun off thread actually does something important, and needs to be given time to finish before being torn down by the system. 

Please clarify in case I missed something.

**Comment by ucwong** [comment]
@holiman Thank you for your comment, You are right requests are very quick. But I think it will reduce some EOF error to others peers connected or some timeout waitings by system, if waiting for them finished. It is only a point of myself

**Comment by holiman** [comment]
I would prefer to close this, as it makes the code more complex to read. I don't think we should waitgroup things that don't require watiing for. 

Regarding EOF errors, we do see EOFs sometimes during peering, but I think that's unrelated to these mechanisms

**Comment by ucwong** [comment]
@holiman OK , I agree with u, thanks for that, I will close this pr

**Pull request closed without merging**
