### PR TITLE
core: flush in-memory trie with user-friendly time interval

### PR DESCRIPTION
**Pull request by rjl493456442**
This PR adjusts the in-memory trie flush strategy.
The original strategy is: flush the `head-128` trie if the accumulated block processing time beyond the `TrieTimeLimit`.
While it is not friendly for users. Since most of the users have no idea what's the **average block processing time**. And the default `TrieTimeLimit` is 1hour. Usually, if the geth node is crashed or is killed, it will lose all block states for the past day(AFAIK, the average block processing time is 100ms or 200ms, 1 hour is more than 18000 blocks).

Now the strategy here is: Refresh `head-128` trie every `TrieTimeLimit` time. It is easier for users to control the trie interval since the **average** block time is obvious.

### CODE REVIEW

**Comment by holiman** [comment]
I don't think we can repurpose and existing flag with a different behaviour. That screws documentation up a lot, and leads to severe confusion

**Comment by holiman** [comment]
But I agree that a user-exposed flag should be based user-centric, that is, the time experienced by the user, not the internal processing time of blocks, which is very difficult for a user to have any knowledge about

**Comment by karalabe** [comment]
This will explode the database size in the long run. Currently we are doing these periodic flushes only to recover from unforeseen issues(ie. machine crashes). If we flush more frequently, the database will grow at a lot higher rate.

This PR imho fixes a symptom, not the underlying issue. If the issue is that Geth crashes, then we need to fix that, not make it less painful that it regularly crashes.

**Comment by karalabe** [comment]
@holiman The flag **is** user centric. The flag means that if Geth crashes, you'll need to wait **this** much for it to recover.

**Comment by karalabe** [comment]
@rjl493456442 

> Since most of the users have no idea what's the average block processing time. 

And they shouldn't. They are specifying how much time to lose if they don't terminate Geth gracefully.

**Comment by holiman** [comment]
> @holiman The flag **is** user centric. The flag means that if Geth crashes, you'll need to wait **this** much for it to recover.

Yes, you're right

**Pull request closed without merging**
