### PR TITLE
make updates forked repository 

### PR DESCRIPTION
**Pull request by trustfarm-dev**
make updates forked repository

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 8ea3c88e444d774bc5921b51e30715494c52f713
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by fjl** [comment]
What are you trying to do in those PRs?

**Comment by fjl** [comment]
Please don't submit 1.4.x commits to the master branch.

**Comment by trustfarm-dev** [comment]
@fjl no it is mistakes, i am sorry that. ignore previous things.
I want to PR reverse direction, [ethereum latest to merge to forked repos.]

**Pull request closed without merging**
