### PR TITLE
miner: immediately include uncles in pending block

### PR DESCRIPTION
**Pull request by cdetrio**
This fixes https://github.com/ethereum/go-ethereum/issues/2902

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: e2e9a50cd00e6e3d7e7c37b5cd5ac5e01e3ced68
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by karalabe** [comment]
We need to rework the miner fist to permit multiple work blocks at the same time. Otherwise this would bump up the invalid share count on pools quite heavily since this invalidates the current works and starts  new one. The solution seems ok btw.

**Comment by chfast** [comment]
@karalabe, do you mean to rework the ethminer?

**Comment by chfast** [comment]
Check out this ethminer build: https://github.com/ethereum-mining/ethminer/pull/217.

**Comment by cdetrio** [comment]
What @karalabe might mean by "rework the miner" is to make sure the `SubmitWork` handler in [remote_agent.go](https://github.com/cdetrio/go-ethereum/blob/e2e9a50cd00e6e3d7e7c37b5cd5ac5e01e3ced68/miner/remote_agent.go#L141-L155) holds onto previously constructed pending blocks. I think it does, the only edge case I'm aware of is when two or more blocks are found at the same height (i.e. one mainchain block and then an uncle block), this [delete(a.work, hash)](https://github.com/cdetrio/go-ethereum/blob/e2e9a50cd00e6e3d7e7c37b5cd5ac5e01e3ced68/miner/remote_agent.go#L160) will prevent the second submission (a found uncle block) from being accepted.

**Comment by karalabe** [comment]
Closing this being the wrong approach, but I'll get it addressed in Gary's rework :)

**Pull request closed without merging**
