### PR TITLE
docker: don't remove executables in Docker image

### PR DESCRIPTION
**Pull request by robert-zaremba**
Let's keep all executables in the Docker image (objectives).

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 0759a7cf7b874e98bcbd4dbb87ba6c1aaa56a267
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by karalabe** [comment]
`make geth` inside the Dockerfile only builds Geth, nothing else, so you wouldn't have any other executable available.

That being said, I don't think it's a good idea to leave all the development tools in there as it would blow up the docker image size with stuff most people don't need. Which executable do you need and why is it better to ship it to everyone opposed to building it yourself?

**Comment by karalabe** [comment]
Doing a quick rough calculation, keeping all tools around would increase the size of the docker images by 130MB.

**Comment by robert-zaremba** [comment]
Thank you for the comments.
I see your point. Though now there is no official Dockrized build of full go-ethereum. If somebody would like to use it only `geth` then he can always remove those binaries in the Dockerfile. On the other hand bringing is currently not possible (unless doing own build)

**Comment by karalabe** [comment]
Removing binaries in a higher layer won't make the image smaller, all previous layers are still contained within.

**Comment by robert-zaremba** [comment]
OK, I see.

**Pull request closed without merging**
