### PR TITLE
cmd/geth: remove spaces in client identifier

### PR DESCRIPTION
**Pull request by fjl**

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Wed Aug 12 11:34:25 UTC 2015_

**Comment by Gustav-Simonsson** [comment]
:+1:

**Comment by maran** [comment]
Noticed this as well, very annoying. :+1:

**Comment by karalabe** [comment]
:+1: magical :tophat:

**Pull request merged**
