### PR TITLE
go.mod: bump goja

### PR DESCRIPTION
**Pull request by s1na**
bump goja to v0.0.0-20230119130012-17fd568758fe. It comes with async/await support!

### CODE REVIEW

**Comment by holiman** [comment]
tests fail :(

**Comment by holiman** [comment]
I recall we tried this a few months ago, and @fjl found some deep flaw inside Goja.

**Comment by s1na** [comment]
It *seems* to have been fixed. I played around the console and tracers a bit and things are working.

**Comment by holiman** [comment]
That time, we had to do this: https://github.com/ethereum/go-ethereum/pull/25974/files#diff-4a0bcee085dc713f036ab891045239b2289da01bb715bdbc50cab92dc97d3c11R100  -- and eventually we reverted it. @fjl did you repro the root issue somewhere?

**Review by holiman — APPROVED** [review]
Seems to work, so LGTM

**Review by Lost4urluv7 — APPROVED** [review]

**Comment by fjl** [comment]
The issue I discovered last time is fixed in goja upstream, I think.

**Review by fjl — APPROVED** [review]

**Pull request merged**
