### PR TITLE
p2p/discover/v5wire: reset buffer including cap reset

### PR DESCRIPTION
**Pull request by dbadoy**
/go-ethereum/p2p/discover/v5wire
```go
func (c *Codec) writeHeaders(head *Header) {
	c.buf.Reset()
	c.buf.Write(head.IV[:])
	binary.Write(&c.buf, binary.BigEndian, &head.StaticHeader)
	c.buf.Write(head.AuthData)
}
```
In the original codes, bytes.Buffer.Reset is used. There is no capacity reset. 
Of course, the capacity will not grow indefinitely, but in the worst case capacity will continue to maintain the maximum possible buffer size.

(+) Example test code  I used
```go
func (c *Codec) writeHeaders(head *Header) {
	fmt.Println("writeHeaders")
	c.buf.Reset()
	fmt.Printf("[Before] len: %d cap: %d\n", c.buf.Len(), c.buf.Cap())
	c.buf.Write(head.IV[:])
	binary.Write(&c.buf, binary.BigEndian, &head.StaticHeader)
	c.buf.Write(head.AuthData)
	fmt.Printf("[After] len: %d cap: %d\n", c.buf.Len(), c.buf.Cap())
}
```
<br>

Original codes
```
# /go-ethereum/p2p/discover/v5wire
go test -run TestHandshake_timeout
encodeRandom
[Before] len: 0 cap: 0
[After] len: 32 cap: 64
writeHeaders
[Before] len: 0 cap: 0
[After] len: 71 cap: 160
writeHeaders
[Before] len: 0 cap: 160
[After] len: 71 cap: 160
encodeWhoareyou
[Before] len: 0 cap: 0
[After] len: 24 cap: 64
writeHeaders
[Before] len: 0 cap: 0
[After] len: 63 cap: 64
writeHeaders
[Before] len: 0 cap: 64
[After] len: 63 cap: 64
encodeHandshakeHeader
[Before] len: 0 cap: 64
[After] len: 264 cap: 517
writeHeaders
[Before] len: 0 cap: 160
[After] len: 303 cap: 584
writeHeaders
[Before] len: 0 cap: 584
[After] len: 303 cap: 584
```

PR test results.
```
# /go-ethereum/p2p/discover/v5wire
go test -run TestHandshake_timeout
encodeRandom
[Before] len: 0 cap: 32
[After] len: 32 cap: 32
writeHeaders
[Before] len: 0 cap: 71
[After] len: 71 cap: 71
writeHeaders
[Before] len: 0 cap: 71
[After] len: 71 cap: 71
encodeWhoareyou
[Before] len: 0 cap: 24
[After] len: 24 cap: 24
writeHeaders
[Before] len: 0 cap: 63
[After] len: 63 cap: 63
writeHeaders
[Before] len: 0 cap: 63
[After] len: 63 cap: 63
encodeHandshakeHeader
[Before] len: 0 cap: 264
[After] len: 264 cap: 264
writeHeaders
[Before] len: 0 cap: 303
[After] len: 303 cap: 303
writeHeaders
[Before] len: 0 cap: 303
[After] len: 303 cap: 303
```

### CODE REVIEW

**Comment by dbadoy** [comment]
(+) Test code example I used
```go
func (c *Codec) writeHeaders(head *Header) {
	fmt.Println("writeHeaders")
	c.buf.Reset()
	fmt.Printf("[Before] len: %d cap: %d\n", c.buf.Len(), c.buf.Cap())
	c.buf.Write(head.IV[:])
	binary.Write(&c.buf, binary.BigEndian, &head.StaticHeader)
	c.buf.Write(head.AuthData)
	fmt.Printf("[After] len: %d cap: %d\n", c.buf.Len(), c.buf.Cap())
}
```

**Comment by dbadoy** [comment]
OR it seems OK without preallocate.
```go
func resetBuffer(buf *bytes.Buffer) {
	*buf = *bytes.NewBuffer([]byte{})
}
```

**Comment by fjl** [comment]
I think it's not necessary to worry about the buffer size here. discv5 packets are at most 1280 bytes, so that's the maximum size.

**Comment by dbadoy** [comment]
I see. But without pre-allocation, the capacity will be exceed 1280 bytes. 
My concern is a micro optimization? 😅

**Comment by fjl** [comment]
Sorry, didn't have time to reply here for a while.

I think this PR defeats the purpose of re-using the buffer in the first place. We are using the same buffer instance over and over so that it doesn't need to be allocated anew every time. The buffer manages its own capacity, and yes it may at some point exceed 1280 bytes, but it will surely not grow much further than that. We're not talking about a multi-megabyte buffer here.

**Pull request closed without merging**
