### PR TITLE
miner : fix exit channel goroutine leak

### PR DESCRIPTION
**Pull request by ucwong**

### CODE REVIEW

**Comment by karalabe** [comment]
Please write a description to all these PRs as to why they are needed. It's non obvious to me.

**Comment by ucwong** [comment]
The channel to receive quit signal to stop the object, only the first quit signal is useful, so length = 1 is enough for quit miner.

**Comment by karalabe** [comment]
But the question is why does making it buffered vs blocking help?

**Comment by ucwong** [comment]
The miner.exitCh is only called by close(miner.exitCh), I think it will not cause any blocking.

**Comment by fjl** [comment]
Adding a 1-element buffer to these `exitCh` channels is not useful because the channels are close-only. There is no send operation for these channels and `close(exitCh)` does not use the channel buffer.

**Pull request closed without merging**
