### PR TITLE
Preview of EVMJIT integration

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: aee839e4bb1a435dc4103fdcdff9bb83de2545cb
  * Commits must be prefixed with the package(s) they modify

 * Commit: 7d176e5301f574924d5d724a173da957e104892f
  * Commits must be prefixed with the package(s) they modify

 * Commit: ea83c20198298f65c1bf74588f22fd17b8f22016
  * Commits must be prefixed with the package(s) they modify

 * Commit: 5c3125a6f8b532b77230ea0259b3023c7799333e
  * Commits must be prefixed with the package(s) they modify

 * Commit: 564226db6ba9a3acef5c9567171b6f1b2489030b
  * Commits must be prefixed with the package(s) they modify

 * Commit: a9c30ac789815631483ea43fe28c9f95eaffa32c
  * Commits must be prefixed with the package(s) they modify

 * Commit: bcd50cc1824a5a1ba7364908e1e478aefacd36bd
  * Commits must be prefixed with the package(s) they modify

 * Commit: 0a893c0ce9cfc183b0960951e1bfb37267038e3a
  * Commits must be prefixed with the package(s) they modify

 * Commit: e032b56513b794f7f6df8f635e61eb299915b601
  * Commits must be prefixed with the package(s) they modify

 * Commit: b159bbeafbb8046a2d32e346a151b910f404edab
  * Commits must be prefixed with the package(s) they modify

 * Commit: c19bd35544b41565a03506b144a6ee2a3585a792
  * Commits must be prefixed with the package(s) they modify

 * Commit: d381b360bb838ec8dc7b3be2743dc63c8d71e105
  * Commits must be prefixed with the package(s) they modify

 * Commit: 7ccf06f2bd5dadfe978f31c61b1d27a30714512b
  * Commits must be prefixed with the package(s) they modify

 * Commit: 9bfce2d99ebda6301fbb487e6021bef0e5b910ff
  * Commits must be prefixed with the package(s) they modify

 * Commit: 20b314d92f98a09e6fed41200e36f9fe76a7e06e
  * Commits must be prefixed with the package(s) they modify

 * Commit: ba6648c0f23255f41ca02f0cd4a729db592d6044
  * Commits must be prefixed with the package(s) they modify

 * Commit: 605dcdf6d11e06ee683e17297b47f4ed15e38fc9
  * Commits must be prefixed with the package(s) they modify

 * Commit: 871893e50a19a004d7478fcea88a1742a265a0d9
  * Commits must be prefixed with the package(s) they modify

 * Commit: 1a1b7107e032158b7973d2c78931ca7b4894c188
  * Commits must be prefixed with the package(s) they modify

 * Commit: fb654f1479f03f5c75764d96d517922fb9471913
  * Commits must be prefixed with the package(s) they modify

 * Commit: a079f532e98639394702edf550f89fd9865eedcd
  * Commits must be prefixed with the package(s) they modify

 * Commit: 4af41c9106043aeefd9e119904a7a053e1781507
  * Commits must be prefixed with the package(s) they modify

 * Commit: d8db8e8e5e166054f2c127bb21f5a49ce3105727
  * Commits must be prefixed with the package(s) they modify

 * Commit: f2095d990636a0c80a4163dc6d0874fb328b3320
  * Commits must be prefixed with the package(s) they modify

 * Commit: 7fbf41d2dc686e734ba63258da026a173fe3d45f
  * Commits must be prefixed with the package(s) they modify

 * Commit: 646eb80a340a728df6d9a96d6709240eb831bcea
  * Commits must be prefixed with the package(s) they modify

 * Commit: 9193f241b1719fd24f7559d67fe0e610ecc136e7
  * Commits must be prefixed with the package(s) they modify

 * Commit: 2e5c0a02788c31485a5c125e59fdf298e4ad48c1
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: aee839e4bb1a435dc4103fdcdff9bb83de2545cb
  * Commits must be prefixed with the package(s) they modify

 * Commit: 7d176e5301f574924d5d724a173da957e104892f
  * Commits must be prefixed with the package(s) they modify

 * Commit: ea83c20198298f65c1bf74588f22fd17b8f22016
  * Commits must be prefixed with the package(s) they modify

 * Commit: 5c3125a6f8b532b77230ea0259b3023c7799333e
  * Commits must be prefixed with the package(s) they modify

 * Commit: 564226db6ba9a3acef5c9567171b6f1b2489030b
  * Commits must be prefixed with the package(s) they modify

 * Commit: a9c30ac789815631483ea43fe28c9f95eaffa32c
  * Commits must be prefixed with the package(s) they modify

 * Commit: bcd50cc1824a5a1ba7364908e1e478aefacd36bd
  * Commits must be prefixed with the package(s) they modify

 * Commit: 0a893c0ce9cfc183b0960951e1bfb37267038e3a
  * Commits must be prefixed with the package(s) they modify

 * Commit: e032b56513b794f7f6df8f635e61eb299915b601
  * Commits must be prefixed with the package(s) they modify

 * Commit: b159bbeafbb8046a2d32e346a151b910f404edab
  * Commits must be prefixed with the package(s) they modify

 * Commit: c19bd35544b41565a03506b144a6ee2a3585a792
  * Commits must be prefixed with the package(s) they modify

 * Commit: d381b360bb838ec8dc7b3be2743dc63c8d71e105
  * Commits must be prefixed with the package(s) they modify

 * Commit: 7ccf06f2bd5dadfe978f31c61b1d27a30714512b
  * Commits must be prefixed with the package(s) they modify

 * Commit: 9bfce2d99ebda6301fbb487e6021bef0e5b910ff
  * Commits must be prefixed with the package(s) they modify

 * Commit: 20b314d92f98a09e6fed41200e36f9fe76a7e06e
  * Commits must be prefixed with the package(s) they modify

 * Commit: ba6648c0f23255f41ca02f0cd4a729db592d6044
  * Commits must be prefixed with the package(s) they modify

 * Commit: 605dcdf6d11e06ee683e17297b47f4ed15e38fc9
  * Commits must be prefixed with the package(s) they modify

 * Commit: 871893e50a19a004d7478fcea88a1742a265a0d9
  * Commits must be prefixed with the package(s) they modify

 * Commit: 1a1b7107e032158b7973d2c78931ca7b4894c188
  * Commits must be prefixed with the package(s) they modify

 * Commit: fb654f1479f03f5c75764d96d517922fb9471913
  * Commits must be prefixed with the package(s) they modify

 * Commit: a079f532e98639394702edf550f89fd9865eedcd
  * Commits must be prefixed with the package(s) they modify

 * Commit: 4af41c9106043aeefd9e119904a7a053e1781507
  * Commits must be prefixed with the package(s) they modify

 * Commit: d8db8e8e5e166054f2c127bb21f5a49ce3105727
  * Commits must be prefixed with the package(s) they modify

 * Commit: f2095d990636a0c80a4163dc6d0874fb328b3320
  * Commits must be prefixed with the package(s) they modify

 * Commit: 7fbf41d2dc686e734ba63258da026a173fe3d45f
  * Commits must be prefixed with the package(s) they modify

 * Commit: 646eb80a340a728df6d9a96d6709240eb831bcea
  * Commits must be prefixed with the package(s) they modify

 * Commit: 9193f241b1719fd24f7559d67fe0e610ecc136e7
  * Commits must be prefixed with the package(s) they modify

 * Commit: 2e5c0a02788c31485a5c125e59fdf298e4ad48c1
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 5e48dee7631553df8a68433dad53102a152eb526
  * Commits must be prefixed with the package(s) they modify

 * Commit: 5ccf8a1785541d194ac680409fe015cd0e24af70
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 947fbebeb5f399abd83d515f0ea123a886b6cdb3
  * Commits must be prefixed with the package(s) they modify

 * Commit: 12564e366364991b8c0b350e423f7b15ee1aaf1b
  * Commits must be prefixed with the package(s) they modify

 * Commit: c25eb4794e7bb8eb7a0d08e40cff244e0e4cdf7f
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 947fbebeb5f399abd83d515f0ea123a886b6cdb3
  * Commits must be prefixed with the package(s) they modify

 * Commit: 12564e366364991b8c0b350e423f7b15ee1aaf1b
  * Commits must be prefixed with the package(s) they modify

 * Commit: 38b48fc8ddf049f4fff5902dee4aee628ff04b5c
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 947fbebeb5f399abd83d515f0ea123a886b6cdb3
  * Commits must be prefixed with the package(s) they modify

 * Commit: 12564e366364991b8c0b350e423f7b15ee1aaf1b
  * Commits must be prefixed with the package(s) they modify

 * Commit: 38b48fc8ddf049f4fff5902dee4aee628ff04b5c
  * Commits must be prefixed with the package(s) they modify

 * Commit: 651f1b01ac9f32abca2c0b6c8d22be9a8be4684e
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 947fbebeb5f399abd83d515f0ea123a886b6cdb3
  * Commits must be prefixed with the package(s) they modify

 * Commit: 12564e366364991b8c0b350e423f7b15ee1aaf1b
  * Commits must be prefixed with the package(s) they modify

 * Commit: 38b48fc8ddf049f4fff5902dee4aee628ff04b5c
  * Commits must be prefixed with the package(s) they modify

 * Commit: 651f1b01ac9f32abca2c0b6c8d22be9a8be4684e
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 947fbebeb5f399abd83d515f0ea123a886b6cdb3
  * Commits must be prefixed with the package(s) they modify

 * Commit: 12564e366364991b8c0b350e423f7b15ee1aaf1b
  * Commits must be prefixed with the package(s) they modify

 * Commit: 38b48fc8ddf049f4fff5902dee4aee628ff04b5c
  * Commits must be prefixed with the package(s) they modify

 * Commit: 651f1b01ac9f32abca2c0b6c8d22be9a8be4684e
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by chfast** [comment]
Replaced by https://github.com/ethereum/go-ethereum/pull/17050.

**Pull request closed without merging**
