### PR TITLE
eth,internal: add eth_chainId method to PublicEthereumApi JSONRPC

### PR DESCRIPTION
**Pull request by whilei**
I'm stealing @sorpaas words from [his congruent Parity client PR](https://github.com/paritytech/parity/pull/6329):
> Currently although we can use net_version RPC call to get the
current network ID, there's no RPC for querying the chain ID. This
makes it impossible to determine the current actual blockchain using
the RPC. An ETH/ETC client can accidentally connect to an ETC/ETH RPC
endpoint without knowing it unless it tries to sign a transaction or
it fetch a transaction that is known to have signed with a chain
ID. This has since caused trouble for application developers, such as
MetaMask, to add multi-chain support. 

Recently merged the same endpoint to ETC's go-ethereum: https://github.com/ethereumproject/go-ethereum/pull/336

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: dc0641c96ee4368b8df740a869a76310b26a8682
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by karalabe** [comment]
Would be nice to have an EIP for it before adding methods to the standardized `eth_` namespace.

**Comment by tcz001** [comment]
Good to see this, just created a EIP #694

**Comment by whilei** [comment]
Please find an EIP PR here: https://github.com/ethereum/EIPs/pull/695

**Comment by bas-vk** [comment]
The proper way to retrieve the chainID is:
```
if config := api.e.chainConfig; config.IsEIP155(api.e.blockchain.CurrentBlock().Number()) {
		chainID = config.ChainId
}
```

Although the EIP is not finalized it is likely that a `QUANTITY` is returned. You can return one the of integer types in the `hexutil` package for that. They will take care of the appropiate encoding that is used for quantity types.

**Comment by whilei** [comment]
It will `return hexutil.Uint(new(big.Int))`, ie. `0x0`, which does not conflict with any existing chainId in [EIP155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md).

**Comment by frankiebee** [comment]
whats the status on this? seems like a stale PR. did chainId make it in somewhere else?

**Comment by fjl** [comment]
Closing in favor of #17617

**Pull request closed without merging**
