### PR TITLE
Geth 1.4.8 "DAO Wars"

### PR DESCRIPTION
**Pull request by karalabe**

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Fri Jun 24 10:20:17 UTC 2016_

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: a9c94cbf48fefe39104ee3495df139ff374dd219
  * Commit subjects should be kept under 80 characters

 * Commit: f31a3a251afad1d4c7169bc530fe60471df36122
  * Commit subjects should be kept under 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by fjl** [comment]
👍

**Comment by Gustav-Simonsson** [comment]
Would recommend to either remove the `DAOSoftFork` flag and enable voting by default in this version, or if keeping it make sure to document clearly that a miner running this version WILL mine soft-fork blocks even if they do not set `DAOSoftFork` - if the voting threshold passes.

**Comment by ChirpChirp** [comment]
How are you planning to prevent the griefing problem? To quote Gavin from the Parity repo:

> it is mainly a problem for transactions that would have miners do significant computation prior to discovery that they're invalid (transactors can already grief miners to some degree by spamming transactions with too little ether in the 'from' account). ultimately if this became a problem, miners could include additional logic to automatically drop or deprioritize transactions whose gas is substantial.

https://github.com/ethcore/parity/pull/1309

The countermeasures he described are not implemented yet, so the network would be at risk of griefing. 

Can you clarify whether this version might be vulnerable to the same type of issues?

**Comment by karalabe** [comment]
There aren't any plans to do that currently. Transactions are almost instantaneous compared to POW verification so I don't think there's a realistic need for further complicating code. If need arises, we can consider exactly how to solve the issues at hand.

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: a9c94cbf48fefe39104ee3495df139ff374dd219
  * Commit subjects should be kept under 80 characters

 * Commit: f31a3a251afad1d4c7169bc530fe60471df36122
  * Commit subjects should be kept under 80 characters

 * Commit: b170a80cdcb380765c711017588b2d148eb1601e
  * Commit subjects should be kept under 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
