### PR TITLE
migrate to nextjs14

### PR DESCRIPTION
**Pull request by corwintines**
Upgrade project to Nextjs 14. Part of investigating https://github.com/ethereum/go-ethereum/issues/30309

More context on migration and its impact on ISR: https://docs.netlify.com/frameworks/next-js/runtime-v4/incremental-static-regeneration/

### CODE REVIEW

**Comment by corwintines** [comment]
https://app.netlify.com/sites/geth-website/deploys/66cfe39602ed16728a16380b working build here after updating to node v18

**Comment by holiman** [comment]
Is this something to worry about? (from the deploy log)

https://app.netlify.com/sites/geth-website/deploys/66cfe39602ed16728a16380b#L166

```
4:59:25 AM: Serving and scanning site from directory .next
4:59:31 AM: ERRORED_DOCUMENT_REQUEST
4:59:31 AM: Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 404)
```

**Comment by holiman** [comment]
The checks seems to have failed. Do you want this merged, or is this work in progress?

**Comment by corwintines** [comment]
Hey @holiman 

I switched the node version over in Netlify so while the checks haven't passed in here because I didnt add a new commit, this should be good to go.

**Review by minimalsm — APPROVED** [review]
LGTM

**Review by wackerow — APPROVED** [review]

**Comment by wackerow** [comment]
Going to pull this in and we can see how it does.

**Pull request merged**
