### PR TITLE
miner, core: sort txs by price, nonce

### PR DESCRIPTION
**Pull request by obscuren**

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Mon Aug 3 19:58:06 UTC 2015_

**Comment by Gustav-Simonsson** [comment]
Discussed with @obscuren a few ideas around this. One is:

txsToInclude := append(SortByGasPrice(UniqueAddressTxs), SortByAccountNonce(RemainingTxs)...)

Basically, split the available-txs-to-mine into two sets:
1. Pending txs for which there is no other pending tx from the same sender.
2. Txs where for each tx there is atleast one more tx from the same sender.

Sort (1) by gasPrice, (2) by account nonce. Then append (2) after (1).

This will allow users to always outbid other pending txs in case of congestion by increasing the gas price. It also forces an attacker that wants to fill up blocks with spam to create new accounts if he wants to out-compete other pending txs.

**Comment by obscuren** [comment]
I think it also makes sense to move these type of sorting strategies in their own functions and be configurable

**Comment by Gustav-Simonsson** [comment]
:+1:  though builds seems a bit fucked

**Comment by obscuren** [comment]
This PR has moved back to `sort by price & nonce`. Approaches have been left it for future reference.

**Pull request merged**
