### PR TITLE
eth: client setup

### PR DESCRIPTION
**Pull request by obscuren**
### This PR is specifically about the second commit (**setup made easy**).

Opened up this PR to start conversation regarding the difficulty of setting up a new client. The current approach is to use a few utility functions from the `cmd/util` package to setup a basic node using `MakeEthConfig`. `MakeEthConfig` heavily depends on package `cli` and isn't always suitable nor required.

This PR simplifies the setup process using default values for `eth.Config`.

**Note**: This PR isn't opened for reviewing purposes. This PR is opened up to engage in conversation regarding setup. Grammer nazi comments and comments that comments are missing are simply ignored and might result in deduction of salary and or contracting fees :fu:

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Wed Nov 4 11:13:59 UTC 2015_

**Comment by obscuren** [comment]
Setup would like:

```go
package main

import (
	"log"
	"os"
	"os/signal"

	"github.com/ethereum/go-ethereum/eth"
)

func main() {
	// create node
	ethereum, err := eth.New(&eth.Config{
		Verbosity: 3,
		DataDir:   "/tmp/testme",
	})
	if err != nil {
		log.Fatalln(err)
	}
	// start services
	ethereum.Start()

	// wait for ctrl-c
	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt, os.Kill)
	<-c
	ethereum.Stop()
}
```

**Comment by karalabe** [comment]
Btw, just mentioning that this PR is kind of conflicting with the protocol stack separation stuff I started engaging in. Note, that simplifying Ethereum setup is something still desired, but many of the stuff currently in there will move out into a `node` package. I'll try to open a PR as soon as I have something stable enough to be worthy of discussion.

**Comment by obscuren** [comment]
@karalabe when you open up a PR we'll move discussion to that PR instead of this one. Consider this one closed.

**Comment by karalabe** [comment]
Opened it, but it's not yet in a discussable state, just working my way through all the boilerplate. Will ping you when it's readier. Of course, prying eyes are always welcome :) https://github.com/ethereum/go-ethereum/pull/1970

**Comment by obscuren** [comment]
Closing this in favour of #1970

**Pull request closed without merging**
