### PR TITLE
params: settle the Pi vs Tau dispute

### PR DESCRIPTION
**Pull request by obscuren**
This commit increases the artificial gas floor to 4712388

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Fri Feb 26 15:19:05 UTC 2016_

**Comment by karalabe** [comment]
:+1:

**Comment by rebroad** [comment]
I have no idea what this means - it is explained anywhere?

**Comment by karalabe** [comment]
https://xkcd.com/1292/ :D

**Pull request merged**
