### PR TITLE
makefile: built in cross compilation targets

### PR DESCRIPTION
**Pull request by karalabe**
:sparkles: 

```
$ make geth-cross
[...]
Full cross compilation done:
-rwxr-xr-x 1 root root 23280432 Sep 21 21:33 build/bin/geth-android-16-arm
-rwxr-xr-x 1 root root 23280432 Sep 21 21:34 build/bin/geth-android-21-arm
-rwxr-xr-x 1 root root 14427264 Sep 21 21:31 build/bin/geth-darwin-386
-rwxr-xr-x 1 root root 17435156 Sep 21 21:30 build/bin/geth-darwin-amd64
-rwxr-xr-x 1 root root 21158117 Sep 21 21:28 build/bin/geth-linux-386
-rwxr-xr-x 1 root root 25118808 Sep 21 21:28 build/bin/geth-linux-amd64
-rwxr-xr-x 1 root root 20637198 Sep 21 21:29 build/bin/geth-linux-arm
-rwxr-xr-x 1 root root 16405858 Sep 21 21:32 build/bin/geth-windows-386.exe
-rwxr-xr-x 1 root root 19479325 Sep 21 21:31 build/bin/geth-windows-amd64.exe
```

```
real   7m12.292s
user   0m0.840s
sys    0m0.692s
```

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Mon Sep 21 18:40:23 UTC 2015_

**Comment by karalabe** [comment]
@fjl  ;)

**Comment by fjl** [comment]
Nice. Go idea. Can't try it because I don't have docker but it looks reasonable.

**Comment by obscuren** [comment]
:rainbow: I like

**Pull request merged**
