### PR TITLE
cmd, core, ethdb: enable Pebble on 32 bits and OpenBSD too

### PR DESCRIPTION
**Pull request by karalabe**
Supposedly upstream supports both now.

### CODE REVIEW

**Comment by holiman** [comment]
```
ethdb\pebble\pebble.go:150:21: cannot use 4 << 30 - 1 (untyped int constant 4294967295) as int value in assignment (overflows)
```

**Comment by holiman** [comment]
It's a constant we took from pebble, and have updated it upstream now: https://github.com/cockroachdb/pebble/blob/master/open.go#L57C44-L57C44 
```golang
	// The max memtable size is limited by the uint32 offsets stored in
	// internal/arenaskl.node, DeferredBatchOp, and flushableBatchEntry.
	//
	// We limit the size to MaxUint32 (just short of 4GB) so that the exclusive
	// end of an allocation fits in uint32.
	//
	// On 32-bit systems, slices are naturally limited to MaxInt (just short of
	// 2GB).
	maxMemTableSize = constants.MaxUint32OrInt
```
```golang
const (
	// oneIf64Bit is 1 on 64-bit platforms and 0 on 32-bit platforms.
	oneIf64Bit = ^uint(0) >> 63

	// MaxUint32OrInt returns min(MaxUint32, MaxInt), i.e
	// - MaxUint32 on 64-bit platforms;
	// - MaxInt on 32-bit platforms.
	// It is used when slices are limited to Uint32 on 64-bit platforms (the
	// length limit for slices is naturally MaxInt on 32-bit platforms).
	MaxUint32OrInt = (1<<31)<<oneIf64Bit - 1
)
```

**Review by gballet — APPROVED** [review]
Tried with `--dev` and `--synctarget` on 64bit OpenBSD, geth compiles, starts and starts syncing

**Comment by karalabe** [comment]
@holiman Thanks. Updated the constant to be in line with Pebble. PTAL

**Comment by karalabe** [comment]
@gballet TY!

**Review by holiman — APPROVED** [review]
LGTM

**Pull request merged**
