### PR TITLE
crypto/ecies: correct IV and MAC

### PR DESCRIPTION
**Pull request by Gustav-Simonsson**

### CODE REVIEW

**Comment by obscuren** [comment]
What's the status of this PR?

**Comment by Gustav-Simonsson** [comment]
@obscuren It's not urgent as it's not impacting security or performance, but after discussing it with Alex he agreed to these changes to make it compliant with the SEC1 standard which is the ECIES standard our impl is closest to.

This will make it easier for other clients to be compliant with Go and cpp (in particular the Java one, which raised this issue).

 So I'd recommend we coordinate the same changes in cpp and release updated versions at the same time, as the changes break compatibility with old version.

**Comment by subtly** [comment]
@Gustav-Simonsson This is accurate and requires coordination with c++ client. I'll clarify this in the spec and get a PR ready for C++. This breaks backwards compatibility must not be deployed without a backwards-compatible upgrade of the network.

cc @gavofyork

**Comment by subtly** [comment]
@all Just noting that this has been noted. Going to aggregate this change and IV issue w/review from Gustav after audit.

**Comment by fjl** [comment]
We'll make this change later, and when it's time to do that there will be a new PR.

**Comment by enuoCM** [comment]
@Gustav-Simonsson Hi, thanks for your commits . But even I merged your pull commits, it still cann't coordinate with ethereumj client.  I test it with https://www.programcreek.com/java-api-examples/index.php?source_dir=ethereumj-master/ethereumj-core/src/test/java/org/ethereum/crypto/CryptoTest.java#test14().

**Comment by Gustav-Simonsson** [comment]
@enuoCM Please note this PR was quite some time ago and so I wouldn't base anything on these old commits. Please check the up-to-date implementation at
https://github.com/ethereum/go-ethereum/tree/master/crypto/ecies
and https://github.com/ethereum/go-ethereum/blob/master/p2p/rlpx.go
I can't seem to find the most up-to-date spec for the encrypted handshake - there's quite a few old wiki pages from 2015 - I remember @fjl at some point wrote up a new up-to-date spec

**Comment by enuoCM** [comment]
@Gustav-Simonsson Thanks for your reply. The up-to-date implementation seems to be no change. In fact I tested it with the nearly newest go-ethereum(v1.6.7). I'm a litte curious, how could other ethereum nodes, such as ethereumj, make successful handshake with go-ethereum nodes?

**Comment by enuoCM** [comment]
@Gustav-Simonsson Thanks for your reply. Finally I find ECIESCoder of ethereumj works well with the go-ethereum ecies.

**Pull request closed without merging**
