### PR TITLE
cmd, core, eth: added official testnet

### PR DESCRIPTION
**Pull request by obscuren**

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Thu Oct 8 20:02:34 UTC 2015_

**Comment by alexvandesande** [comment]
👌🏻

**Comment by zsfelfoldi** [comment]
:+1:

**Comment by bas-vk** [comment]
Code looks fine :+1: 

One usability remark, the other clients all use the `--morden` flag/option. Maybe its convenient that geth uses the same instead of `--testnet`, or at least mention morden in the help description for the new testnet flag.

**Pull request merged**
