### PR TITLE
cmd: cap cache size if exceeds reasonable range

### PR DESCRIPTION
**Pull request by rjl493456442**

### CODE REVIEW

**Comment by rjl493456442** [comment]
@karalabe Just copy your implementation and update

**Comment by karalabe** [comment]
We'll probably need to run a fast sync and a full sync benchmark too with this. Seems good to me, but it's not something we want to merge last minute into a release. We can get it in after the next release and have a week or so to test it.

**Comment by karalabe** [comment]
Benchmarks seem completely uninteresting. Merging.

**Comment by JEJodesty** [comment]
Hi everyone,
can some explain why a certain cache size is within an un-reasonable range?

**Comment by JEJodesty** [comment]
Thanks @karalabe !

**Pull request merged**
