### PR TITLE
JSON Log Events

### PR DESCRIPTION
**Pull request by tgerring**
New functionality to satisfy [Log Events](https://github.com/ethereum/system-testing/wiki/Log-Events) specification.

* New LogSystem to output from the logger without log.LstdFlags
* New LogFormat flag to control which log system is used
* New JsonLogger type for logging maps as JSON

Invoke JSON-only logging with `ethereum -loglevel=1000 -logformat=raw`

### CODE REVIEW

**Comment by tgerring** [comment]
This needs more logging, but the structure should be in place. Implementation can be along-side existing logging by initializing the new logger: `var jsonlogger = ethlogger.NewJsonLogger()` then logging:
```
	evd := map[string]interface{}{
		"version_string": s.ClientIdentity().String(),
		"guid":           ethutil.Bytes2Hex(s.ClientIdentity().Pubkey()),
		"level":          "debug",
		"coinbase":       ethutil.Bytes2Hex(s.KeyManager().Address()),
		"eth_version":    ProtocolVersion,
	}
	jsonlogger.LogJson("starting", evd)
```

**Comment by tgerring** [comment]
This PR needs more implementation discussion due to required context building, however it is intended to satisfy #222

**Comment by sveneh** [comment]
What is the status of this PR? What needs to be decided to merge this? I know it does not support the full spec, but as @tgerring said, enough to get us started including it into system-testing. So if this could be merged, we can already use is and see how usable it is already.

**Comment by tgerring** [comment]
It's on the agenda to discuss this week while the whole Go team is together

**Comment by sveneh** [comment]
cool, please keep me and @heikoheiko updated.

**Comment by obscuren** [comment]
@sveneh Do we need that "debugging" field? There doesn't seem to be a lot of reason to have this

**Comment by obscuren** [comment]
@sveneh Please update your Time zone formatting according to **RFC3339Nano**
 
```
RFC3339Nano = "2006-01-02T15:04:05.999999999Z07:00"
              "YYYY-MM-DDTHH:MM:SS.SSSSSSZ"

```

Please correct me if I'm wrong but I don't think what you specified for TZ formatting is according to any RFC.

**Comment by heikoheiko** [comment]
Timstamps for Kibana must be formatted according to ISO8601.
e.g. 2015-02-02T14:55:10.029235Z

Actually you don't need to provide a timestamp as it can be added by the external log forwarder.

**Comment by tgerring** [comment]
Last commit updates the package so structured objects are available for each of the log types. For example:

```
jsonlogger.LogJson("starting", &ethlogger.LogStarting{
	ClientString:    s.ClientIdentity().String(),
	Guid:            ethutil.Bytes2Hex(s.ClientIdentity().Pubkey()),
	Coinbase:        ethutil.Bytes2Hex(s.KeyManager().Address()),
	ProtocolVersion: ProtocolVersion,
})
```

Additionally, the timestamp field will be auto-generated on output of all log types in the requested ISO 8601 format.

**Comment by tgerring** [comment]
Events have been made aware of their own name, so the signature is updated to only require a valid LogEvent defined in logger/types.go, instead of also having to supply the JSON name inline. This should make it easy to integrate into packages currently under active development once the new types have been merged into develop.

For example:
```
var jsonlogger = logger.NewJsonLogger()
jsonlogger.LogJson(&logger.LogStarting{field: value, ...})
```

**Pull request merged**
