### PR TITLE
p2p/discover: deflake TestUDP_successfulPing

### PR DESCRIPTION
**Pull request by fjl**
This should fix the Travis build failures.

### CODE REVIEW

**Comment by obscuren** [comment]
You've got some of my PR in your PR (look at the ARM build fail)

**Comment by fjl** [comment]
I think this is a problem with the build server.

**Comment by karalabe** [comment]
LGTM

@obscuren Could you ping someone regarding the ARM build server? That failure really does point to some stale code.

**Comment by obscuren** [comment]
@caktux :)

**Comment by caktux** [comment]
No build server error that I can see there, it's doing what it's supposed to...

**Comment by karalabe** [comment]
@caktux There's no such file in the commit that the build server is failing on:

`../go/src/github.com/ethereum/go-ethereum/core/vm_logger.go:12: undefined: vm.StructLog`

https://github.com/fjl/go-ethereum/tree/a8e4cb6dfe9dbaf3f5bf19807406577ee116cc2a/core

**Comment by caktux** [comment]
I see, added the missing cleanup step :) I'll trigger a rebuild in a minute

**Comment by karalabe** [comment]
LGTM :D

**Pull request merged**
