### PR TITLE
core/types: reimplement log.EncodeRLP

### PR DESCRIPTION
**Pull request by jsvisa**
fix https://github.com/ethereum/go-ethereum/issues/28008

### CODE REVIEW

**Comment by fjl** [comment]
It's nice you're submitting this, but I really think it should be handled in rlpgen instead. The method is there, so it should recognize that. The only reason why it does complain, is because type-checking is turned on in the package loader.

**Comment by jsvisa** [comment]
Or we should use `rlp.Encode` instead of `log.EncodeRLP` in https://github.com/ethereum/go-ethereum/blob/6aa88ccdd28a8f01ad371453df88cc61865ea1c8/core/types/receipt.go#L272-L275

**Comment by fjl** [comment]
I changed it because it's way faster to call the method directly. The reason why rlpgen fails, is because it applies the build tag `norlpgen` during code generation.

**Comment by jsvisa** [comment]
@fjl thanks for the information, I changed the behavior in rlpgen, please take another look, thanks.

**Comment by fjl** [comment]
I decided to just always remove the build tag for now: https://github.com/ethereum/go-ethereum/pull/28106

**Pull request closed without merging**
