### PR TITLE
Use uint256 instead of big.Int

### PR DESCRIPTION
**Pull request by holiman**
This is a successor to https://github.com/ethereum/go-ethereum/pull/20787 

- [x] Rebase
- [ ] Use `1.0` of uint256
- [ ] Benchmark + verify via full sync

### CODE REVIEW

**Comment by holiman** [comment]
It seems that go 1.11 becomes unsupported, due to the use of `bits.Add64` et al. 
Also, for some reason go 1.12 errors out: 
```
# github.com/holiman/uint256

../../../../pkg/mod/github.com/holiman/uint256@v0.0.0-20200319132535-a4d16d7dba8d/uint256.go:465:11: invalid operation: d[i] << shift (shift count type int, must be unsigned integer)

../../../../pkg/mod/github.com/holiman/uint256@v0.0.0-20200319132535-a4d16d7dba8d/uint256.go:465:29: invalid operation: d[i - 1] >> (64 - shift) (shift count type int, must be unsigned integer)

../../../../pkg/mod/github.com/holiman/uint256@v0.0.0-20200319132535-a4d16d7dba8d/uint256.go:467:15: invalid operation: d[0] << shift (shift count type int, must be unsigned integer)

../../../../pkg/mod/github.com/holiman/uint256@v0.0.0-20200319132535-a4d16d7dba8d/uint256.go:479:23: invalid operation: u[uLen - 1] >> (64 - shift) (shift count type int, must be unsigned integer)

../../../../pkg/mod/github.com/holiman/uint256@v0.0.0-20200319132535-a4d16d7dba8d/uint256.go:481:11: invalid operation: u[i] << shift (shift count type int, must be unsigned integer)

../../../../pkg/mod/github.com/holiman/uint256@v0.0.0-20200319132535-a4d16d7dba8d/uint256.go:481:29: invalid operation: u[i - 1] >> (64 - shift) (shift count type int, must be unsigned integer)

../../../../pkg/mod/github.com/holiman/uint256@v0.0.0-20200319132535-a4d16d7dba8d/uint256.go:483:15: invalid operation: u[0] << shift (shift count type int, must be unsigned integer)

../../../../pkg/mod/github.com/holiman/uint256@v0.0.0-20200319132535-a4d16d7dba8d/uint256.go:489:19: invalid operation: r >> shift (shift count type int, must be unsigned integer)

../../../../pkg/mod/github.com/holiman/uint256@v0.0.0-20200319132535-a4d16d7dba8d/uint256.go:496:12: invalid operation: un[i] >> shift (shift count type int, must be unsigned integer)

../../../../pkg/mod/github.com/holiman/uint256@v0.0.0-20200319132535-a4d16d7dba8d/uint256.go:496:31: invalid operation: un[i + 1] << (64 - shift) (shift count type int, must be unsigned integer)
```

**Comment by karalabe** [comment]
Myeah, but we're dropping 1.11 and 1.12 anyway due to the new errors, so seems that we shouldn't stress too much. The shift is interesting though, because that doesn't feel like a change Go would ship across versions. Wonder why Go 1.13 and 1.14 don't complain.

**Comment by chfast** [comment]
> The shift is interesting though, because that doesn't feel like a change Go would ship across versions. Wonder why Go 1.13 and 1.14 don't complain.

It's a soft fork :) something not allowed in 1.12 is allowed in 1.13.

**Comment by holiman** [comment]
Closing in favour of https://github.com/ethereum/go-ethereum/pull/20787

**Pull request closed without merging**
