### PR TITLE
core/types: remove support for legacy receipt/log storage encoding

### PR DESCRIPTION
**Pull request by fjl**
This removes the database upgrade path for receipts and logs stored before April 2019.

### CODE REVIEW

**Review by holiman — APPROVED** [review]
LGTM, but let's hear what karalabe thinks too

**Review by karalabe — APPROVED** [review]
Safe to delete as we introduced the freezer at the same time as the new format and the freezer moved everything reencoding, so nobody should have any old format stuff any more.

**Comment by shoenseiwaso** [comment]
_Note that this comment is intended only to help others who have the same problem, we are not expecting a fix._

For anyone who sees the following in their geth console logs with v1.10.4 or later:
```
ERROR[06-22|15:02:49.899] Invalid receipt array RLP                hash=28c41d..6bb895 err="rlp: expected input list for []*types.LogForStorage, decoding into ([]*types.ReceiptForStorage)[0](types.storedReceiptRLP).Logs"
ERROR[06-22|15:02:49.899] Invalid receipt array RLP                hash=506213..15eea1 err="rlp: expected input list for []*types.LogForStorage, decoding into ([]*types.ReceiptForStorage)[0](types.storedReceiptRLP).Logs"
ERROR[06-22|15:02:49.899] Invalid receipt array RLP                hash=fb8a03..3e976e err="rlp: expected input list for []*types.LogForStorage, decoding into ([]*types.ReceiptForStorage)[0](types.storedReceiptRLP).Logs"
ERROR[06-22|15:02:49.901] Invalid receipt array RLP                hash=506213..15eea1 err="rlp: expected input list for []*types.LogForStorage, decoding into ([]*types.ReceiptForStorage)[0](types.storedReceiptRLP).Logs"
```

Or sees the following error when they attempt to export their chaindata:
```
retrieved hash chain is invalid: invalid gas used (remote: 1884897 local: 1542885)
```

What probably happened is that at some point in the past, your geth database (chaindata) got silently corrupted and failed to automatically upgrade to the modern receipt/log storage encoding. With this change (#22852) go-ethereum removes the capability to read these legacy logs.

Possible solutions include:
(1) Recreate your geth database (chaindata) from scratch
(2) Postpone the upgrade to v1.10.4 or build a custom geth without this PR and run it until you can do (1)

**Comment by rjl493456442** [comment]
@shoenseiwaso not sure you are still around. Are you willing to recompile the geth with these diffs? I am curious why it's failed. Since we have the freezer to re-encode the legacy receipts. No legacy format receipts should be left. 

```go
diff --git a/core/rawdb/accessors_chain.go b/core/rawdb/accessors_chain.go
index 76132bf37..871ab0b64 100644
--- a/core/rawdb/accessors_chain.go
+++ b/core/rawdb/accessors_chain.go
@@ -572,7 +572,7 @@ func ReadRawReceipts(db ethdb.Reader, hash common.Hash, number uint64) types.Rec
        // Convert the receipts from their storage form to their internal representation
        storageReceipts := []*types.ReceiptForStorage{}
        if err := rlp.DecodeBytes(data, &storageReceipts); err != nil {
-               log.Error("Invalid receipt array RLP", "hash", hash, "err", err)
+               log.Error("Invalid receipt array RLP", "number", number, "hash", hash.Hex(), "err", err)
                return nil
        }
        receipts := make(types.Receipts, len(storageReceipts))

```

**Comment by rjl493456442** [comment]
Let's discuss at #23245

**Pull request merged**
