### PR TITLE
rlp: remove a meaningless todo

### PR DESCRIPTION
**Pull request by buddh0**
NewListIterator is used now

### CODE REVIEW

**Comment by karalabe** [comment]
@fjl Was this supposed to be deprecated and we accidentally started using it somewhere?

**Comment by fjl** [comment]
I actually don't know. @holiman added this for something.

**Comment by holiman** [comment]
I added the method to be able to iterate faster when we were populating leveldb from ancients, something. Then it got unused because new tx types forced us to actually soup the txs in full to figure out the hash, not just take the blob and hash it. 

And now it's used once again. so yeah the comment can be dropped

**Comment by holiman** [comment]
Sorry, clicked wrong!

**Review by holiman — APPROVED** [review]

**Pull request merged**
