### PR TITLE
cmd/evm: add state transition tool for testing

### PR DESCRIPTION
**Pull request by holiman**
This PR implements the state transition tool that can be a replacement for our retesteth client implementation.

A lot more documentation is present in the readme.md file in this PR. 
cc @winsvega

### CODE REVIEW

**Comment by winsvega** [comment]
Transaction creation: 
```
ERROR(10): Failed unmarshaling txs-file: hex string has length 0, want 40 for common.Address
```

a tx with empty destination is contract creation. not recognized

**Comment by holiman** [comment]
Did you test with simply omitting the 'to'-field?

**Comment by winsvega** [comment]
ommiting the field worked.
next issue 
```
Alloc:
{
    "0x095e7baea6a6c7c4c2dfeb977efac326af552d87" : {
        "balance" : "0x0de0b6b3a7640000",
        "code" : "0x6001600053600160006001f0ff00",
        "nonce" : "0x00",
        "storage" : {
        }
    },
    "0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b" : {
        "balance" : "0x0de0b6b3a7640000",
        "code" : "0x",
        "nonce" : "0x00",
        "storage" : {
        }
    }
}
Txs:
[
    {
        "input" : "0x",
        "gas" : "0x5f5e100",
        "gasPrice" : "0x1",
        "nonce" : "0x0",
        "to" : "0x095e7baea6a6c7c4c2dfeb977efac326af552d87",
        "value" : "0x186a0",
        "v" : "0x1b",
        "r" : "0x88544c93a564b4c28d2ffac2074a0c55fdd4658fe0d215596ed2e32e3ef7f56b",
        "s" : "0x7fb4075d54190f825d7c47bb820284757b34fd6293904a93cddb1d3aa961ac28",
        "hash" : "0x72fadbef39cd251a437eea619cfeda752271a5faaaa2147df012e112159ffb81"
    }
]
Env:
{
    "currentCoinbase" : "0x2adc25665018aa1fe0e6bc666dac8fc2697ff9ba",
    "currentDifficulty" : "0x020000",
    "currentGasLimit" : "0x3b9aca00",
    "currentNumber" : "0x01",
    "currentTimestamp" : "0x03e8",
    "previousHash" : "0xdac58aa524e50956d0c0bae7f3f8bb9d35381365d07804dd5b48a5a297c06af4"
}
```
when evm exception occur I have the log: 
```WARN [05-01|15:01:20.605] Dump incomplete due to missing preimages missing=1
```

**Comment by winsvega** [comment]
```
panic: getHash(0) invoked
```
need to figure out what to do with blockchain-specific opcodes.

**Comment by holiman** [comment]
From the README:

> Right now, a missing BLOCKHASH lead to panic, and does not exit with the right exit code
> It's not possible to provide blockhashes yet (not even specified how)

So we just need to add another input, list of hashes or (probably better), map[int]->hash of historic hashes

**Comment by holiman** [comment]
In the particular case you just reported, you have: 
```json
Env:
{
    "currentCoinbase" : "0x2adc25665018aa1fe0e6bc666dac8fc2697ff9ba",
    "currentDifficulty" : "0x020000",
    "currentGasLimit" : "0x3b9aca00",
    "currentNumber" : "0x01",
    "currentTimestamp" : "0x03e8",
    "previousHash" : "0xdac58aa524e50956d0c0bae7f3f8bb9d35381365d07804dd5b48a5a297c06af4"
}
```
A `previousHash`, which I think the tool ignores. In this case, since it's block `1` and it's asking about hash of block `0`, it would work, but a contract may ask up to `256` earlier hashes, so we need a more extensive mechanism.

**Comment by winsvega** [comment]
maybe we can extend env section file with blockhash map. as a test creator I know which numbers will be accessed so it can be a map. [0] - > hash  [5] -> hash.  
current tests ask only previous block or up to 10 numbers. there might be one test to check 256+\-1 if not we need to create one.

**Comment by holiman** [comment]
> maybe we can extend env section file with blockhash map. as a test creator I know which numbers will be accessed

Yep, that sounds like what I was thinking. Some notes, though: 

- I suggest that we make the map _optional_, 
- I suggest that we make the map key `blocknumber`, not `ancestor-number`. The latter would require the caller to `inc` every key with `1` every block. 
- I suggest that the tool shouldn't care if the caller sends along "future" numbers, or more than 256 numbers (the evm will only ever allow historic lookback up to 256 according to the evm spec anyway)

**Comment by holiman** [comment]
This: 
```
WARN [05-01|15:01:20.605] Dump incomplete due to missing preimages missing=1
```
Seems to be that in your example, there's a `SELFDESTRUCT` to `0x00..00`, which makes the dumper mistakenly believe that it's missing the preimage for, since it's all zeroes.

**Comment by holiman** [comment]
> Seems to be that in your example, there's a SELFDESTRUCT to 0x00..00, which makes the dumper mistakenly believe that it's missing the preimage for, since it's all zeroes.

Should now be fixed. Do you have example inputs that trigger the `panic`?

**Comment by holiman** [comment]
Added blockhash lookup, and example files

**Comment by holiman** [comment]
Todos: 

- [ ] Output traces to separate files (`1.jsonl`, `2.jsonl`...) or maybe `<blocknum>-1.jsonl`... 
- [ ] Include receiptroot in output

**Comment by winsvega** [comment]
can you please include logs hash in transaction receipt ?

**Comment by winsvega** [comment]
>  Output traces to separate files (1.jsonl, 2.jsonl...) 
about the trace I thought that we need  a vmtrace info about 
1) particular tx 2) in particular block 3) starting from particular step
although if I have full trace I can do this selection aside. or launch vmtrace debug tool that you showed.

**Comment by holiman** [comment]
> although if I have full trace I can do this selection aside. or launch vmtrace debug tool that you showed.

Yep, `go install github.com/holiman/cmd/traceview` then `traceview trace-1.json`

**Comment by holiman** [comment]
Done. I also renamed the poststate json fields,  to make it more obvious what they are. `postState`->`stateRoot`, `txHash`->`txRoot`.

**Comment by holiman** [comment]
@winsvega I've implemented ommer rewards now, see the updated information in the readme

**Comment by holiman** [comment]
From @winsvega :

> yay. now I was able to run all state tests and all blockchain tests using t8ntool 

So, as far as I'm concerned, this is ready for review, cc @fjl @karalabe

**Comment by winsvega** [comment]
```
Alloc:
{
    "0x49ec3a96efcc4f9e2e741ea2af622b91f74a2bcc" : {
        "balance" : "0x02540be400",
        "code" : "0x",
        "nonce" : "0x03",
        "storage" : {
        }
    },
    "0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b" : {
        "balance" : "0x02540be400",
        "code" : "0x",
        "nonce" : "0x00",
        "storage" : {
        }
    },
    "0xe4ccfc7cc4a70f5efd0b87867f20acbf68842ef8" : {
        "balance" : "0x02540be400",
        "code" : "0x",
        "nonce" : "0x00",
        "storage" : {
        }
    }
}
Txs:
[
    {
        "nonce" : "0x0",
        "gasPrice" : "0xa",
        "gas" : "0xc350",
        "to" : "0x095e7baea6a6c7c4c2dfeb977efac326af552d87",
        "value" : "0xa",
        "input" : "0x",
        "v" : "0x1b",
        "r" : "0xf3266921c93d600c43f6fa4724b7abae079b35b9e95df592f95f9f3445e94c88",
        "s" : "0x12f977552ebdb7a492cf35f3106df16ccb4576ebad4113056ee1f52cbe4978c1",
        "hash" : "0x8cb8a30c1c8170e33e2317466a982e591e3b55aa02e353e185841bbeac0cf063"
    },
    {
        "nonce" : "0x0",
        "gasPrice" : "0x1",
        "gas" : "0x5208",
        "to" : "0x000000000000000000000000000b9331677e6ebf",
        "value" : "0x14",
        "input" : "0x",
        "v" : "0x1c",
        "r" : "0x98ff921201554726367d2be8c804a7ff89ccf285ebc57dff8ae4c44b9c19ac4a",
        "s" : "0x8887321be575c8095f789dd4c743dfe42c1820f9231f98a962b210e3ac2452a3",
        "hash" : "0x2a4d7b6d2914ec7907b5f0246c8c993fabfe99658ac819f7422aa021b5b37c8f"
    },
    {
        "nonce" : "0x3",
        "gasPrice" : "0x1",
        "gas" : "0x5208",
        "to" : "0xb94f5374fce5edbc8e2a8697c15331677e6ebf0b",
        "value" : "0x1e",
        "input" : "0x",
        "v" : "0x1c",
        "r" : "0x98ff921201554726367d2be8c804a7ff89ccf285ebc57dff8ae4c44b9c19ac4a",
        "s" : "0x8887321be575c8095f789dd4c743dfe42c1820f9231f98a962b210e3ac2452a3",
        "hash" : "0x5114cd45ed63ff36303306fa9ba2123c6a64ca253b3620f02c2ea8a612fa0299"
    }
]
Env:
{
    "currentCoinbase" : "0x8888f1f195afa192cfee860698584c030f4c9db1",
    "currentDifficulty" : "0x020000",
    "currentGasLimit" : "0x2fefba",
    "currentNumber" : "0x01",
    "currentTimestamp" : "0x5db6fb75",
    "previousHash" : "0x701327478e9e63cff9633717a6bb288db43cd4027b5b3e9afe76bfec0eac1c8e",
    "blockHashes" : {
        "0" : "0x701327478e9e63cff9633717a6bb288db43cd4027b5b3e9afe76bfec0eac1c8e"
    }
}

```

**Comment by adria0** [comment]
@holiman, how this tests will be filled? afaik the current way is using retesteth json-rpc api, isn't it?

**Comment by holiman** [comment]
Yeah, so retesteth would invoke this binary instead of making a couple of rpc-calls. Retesteth would then have to seal the blocks, of it's doing blockchain-tests.

**Comment by holiman** [comment]
Rebased on master, now supports `YOLOv1` as forkname, and `2315` as activateable: 
```
                                      Available forknames: 
...
                                        Istanbul
                                        YOLOv1
                                      Available extra eips: 
                                        1344,1884,2200,2315

```

**Comment by winsvega** [comment]
Issues: 
* as the tool execute only one transition this forks are not needed:
```
                                        ByzantiumToConstantinopleAt5
                                        ByzantiumToConstantinopleFixAt5
                                        ConstantinopleFixToIstanbulAt5
                                        EIP158ToByzantiumAt5
                                        FrontierToHomesteadAt5
                                        HomesteadToDaoAt5
                                        HomesteadToEIP150At5
```
* need DaoFork  support that would perform balance movement from dao accounts
* the rule limiting transaction signature s value should not be applied on all forks (there are some test transactions with high s value)

**Comment by holiman** [comment]
- "as the tool execute only one transition this forks are not needed" --- I'll just leave it in, statet8n uses the same forks that the statetests use. It's up to you if you want to use the combo-chains or switch manually from the outside. 
- [x] the rule limiting transaction signature - fixed, 
- [ ] Daosupport -- I'll look into it

**Comment by holiman** [comment]
Re dao -- we do have `HomesteadToDaoAt5` -- isn't that sufficient?

**Comment by winsvega** [comment]
HomesteadToDaoAt5 was more of a test name. I can decode it on my side into Homestead if block <5 and to Dao if block >= 5

The logic I need to verify the tests is a state hash after initial dao fork execution. (state has dao accounts and it's balances moved to dao contract address)

**Comment by holiman** [comment]
> The logic I need to verify the tests is a state hash after initial dao fork execution. (state has dao accounts and it's balances moved to dao contract address)

I don't understand the problem -- why don't you just activate the dao-fork by feeding in block `5`? That must be how the rpc-retesteth did it previously?

**Comment by winsvega** [comment]
that does not seem to work

**Comment by holiman** [comment]
Ah ok, I know what the problem is. So as it's currently implemented, the DAO-changes are not part of an individual state transition rule, it's activated in `func (p *StateProcessor) Process(block *types.Block`. And `statet8n` does not handle blocks. It previously worked only if you handled blocks -- so either retesteth or blockchain-tests. 

I can make a fix to support it though

**Comment by holiman** [comment]
Ok, this is now fixed:
```
./statet8n --input.alloc=./testdata/7/alloc.json  --input.txs=./testdata/7/txs.json --input.env=./testdata/7/env.json --output.alloc=stdout --state.fork=HomesteadToDaoAt5 | head
{
 "alloc": {
  "0x005f5cee7a43331d5a3d3eec71305925a62f34b6": {
   "balance": "0x0"
  },
  "0x0101f3be8ebb4bbd39a2e3b9a3639d4259832fd9": {
   "balance": "0x0"
  },
  "0x057b56736d32b86616a10f619859c6cd6f59092a": {
   "balance": "0x0"
```

**Pull request merged**
