### PR TITLE
RPC updates

### PR DESCRIPTION
**Pull request by tgerring**
Conversion to RPC over HTTP

### CODE REVIEW

**Comment by tgerring** [comment]
Before merging, we should consider rolling in websocket functionality into the rpc package, since the messages and responses should be the same and only the transport is different.

**Comment by kumavis** [comment]
@tgerring yes this is what we're doing in node-ethereum, http + websocket protocol adapters to a generic rpc handler

**Comment by tgerring** [comment]
Both traditional HTTP and Websockets should be supported via the updated rpc package. Both transport methods can be started separately as so: `ethereum -rpc=true -rpcport=8080 -ws=true -wsport=40404`

**Comment by kumavis** [comment]
Does the rpc via http handle CORS?

**Comment by tgerring** [comment]
Is there a specific requirement in terms of enforcing or ignoring CORS? In the linked PR, neither HTTP nor Websocket respect the Origin header. Public-facing integrations will likely want to use a robust proxy such as Apache or Nginx to enforce rate-limiting, etc.

**Comment by kumavis** [comment]
@tgerring the browser requires some additional headers for CORS `Access-Control-Allow-Origin=*`

**Comment by tgerring** [comment]
@kumavis HTTP transport was updated by @obscuren at 7f638f0b2d8d989be25e660178d79df3278e4c84 setting "Access-Control-Allow-Origin" to "*"

**Comment by kumavis** [comment]
this is an awesome feature, but I suggest that it should be configurable and off by default,  as it exposes the rpc to any website you visit.

**Comment by obscuren** [comment]
The browser **requires** it. The browser is useless without. You can configure it (on/off, port). We could add a feature to (dis)allow CORS. Please open new issue.

**Pull request merged**
