### PR TITLE
p2p: validate recovered ephemeral pubkey

### PR DESCRIPTION
**Pull request by ebuchman**
Validate recovered ephemeral pubkey against checksum in decodeAuthMsg

Initiator sends an `authMsg` containing a signature produced by the ephemeral private key, and a sha3 checksum of the ephemeral public key. However the receiver was not validating the recovered pubkey against the checksum.

The other change is to check the validity of a remote peer right away, so we don't first waste entropy/time on a nonce and private key.

### CODE REVIEW

**Comment by Gustav-Simonsson** [comment]
Looks good.

**Comment by ebuchman** [comment]
1.0.2 ?

**Comment by obscuren** [comment]
@fjl PTAL

**Comment by fjl** [comment]
Sorry, I didn't have time to look into this until now. We are reworking the handshake crypto
and will remove the checksum. If the wrong key is recovered, secret derivation won't work
anyway so the error is always detected.

I'll try this PR and we can merge it for 1.0.2 if it doesn't break anything.

**Comment by fjl** [comment]
:+1:

**Comment by ebuchman** [comment]
Cool, I've been running it live for a few days now with no problem. And I don't think there's actually any vulnerability here, just found it weird to send a checksum and not check it. Reworking the handshake to use GCM or what?

**Comment by fjl** [comment]
More or less.

**Comment by obscuren** [comment]
@fjl merge at your discretion

**Pull request merged**
