### PR TITLE
eth/tracers/logger: remove redundant pointer references

### PR DESCRIPTION
**Pull request by mask-pp**
- Remove redundant pointer references.
- Avoid using `fmt.Sprintf` when doing encoding work.
- Prealloc capacity for map.

### CODE REVIEW

**Review by holiman — APPROVED** [review]
LGTM

**Comment by holiman** [comment]
This PR has many test-failures: https://ci.appveyor.com/project/ethereum/go-ethereum/builds/50504814/job/049bap204j85al2o#L1006

**Comment by mask-pp** [comment]
> This PR has many test-failures: https://ci.appveyor.com/project/ethereum/go-ethereum/builds/50504814/job/049bap204j85al2o#L1006

Get it, I will fix it later.

**Comment by mask-pp** [comment]
> This PR has many test-failures: https://ci.appveyor.com/project/ethereum/go-ethereum/builds/50504814/job/049bap204j85al2o#L1006

fixed.

**Comment by holiman** [comment]
You only "fixed" one testcase, there are more. For example

```
--- FAIL: TestTraceCall (0.02s)
    api_test.go:401: test 9: result mismatch, want  {"gas":53018,"failed":false,"returnValue":"","structLogs":[{"pc":0,"op":"NUMBER","gas":24946984,"gasCost":2,"depth":1,"stack":[]},
        		{"pc":1,"op":"STOP","gas":24946982,"gasCost":0,"depth":1,"stack":["0x1337"]}]}, got {"gas":53018,"failed":false,"returnValue":"","structLogs":[{"pc":0,"op":"NUMBER","gas":24946984,"gasCost":2,"depth":1},{"pc":1,"op":"STOP","gas":24946982,"gasCost":0,"depth":1,"stack":["0x1337"
```

want 
```
...{"pc":0,"op":"NUMBER","gas":24946984,"gasCost":2,"depth":1,"stack":[]},...
```
have 
```
...{"pc":0,"op":"NUMBER","gas":24946984,"gasCost":2,"depth":1}...
```

So, again, the problem is that you are _changing_ an existing format. This is what I wanted to highlight with the added test, and when I wrote "fixed" with quotes, I meant that you should change it back so the test passes, not change the test. I see no reason to modify our RPC responses, it'll upset users if we spuriously do those kinds of changes. 

I don't really think this change is warranted. It gives no tangible benefit at all, as far as I can see. Sorry, but I'm closing this.

**Pull request closed without merging**
