### PR TITLE
core/txpool/legacypool: simplify Pop function in nonceHeap

### PR DESCRIPTION
**Pull request by mask-pp**

### CODE REVIEW

**Review by jwasinger — COMMENTED** [review]
Condensing this into a one-liner makes it harder to read IMO.

**Comment by mask-pp** [comment]
> Condensing this into a one-liner makes it harder to read IMO.

However, this is the typical usage of golang!

**Comment by karalabe** [comment]
The reason I wrote it like that messy way originally was to avoid so many pointer dereferencings and len retrievals. Though no idea how much the compiler optimises your call.

**Comment by karalabe** [comment]
Also, FWIW, you removed setting the last item to 0, though it's questionable whether that made any sense or not.

**Comment by mask-pp** [comment]
> Also, FWIW, you removed setting the last item to 0, though it's questionable whether that made any sense or not.

`
func TestCC(t *testing.T) {
	var pp = []int{1, 2, 3}
	n := len(pp)
	x := pp[n-1]
	//pp[n-1] = 0
	pp = pp[:n-1]
	t.Log(x, pp)
	pp = append(pp, 4)
	t.Log(pp)
}
`
This test show that `pp[n-1] = 0` is not necessary.

**Comment by mask-pp** [comment]
> The reason I wrote it like that messy way originally was to avoid so many pointer dereferencings and len retrievals. Though no idea how much the compiler optimises your call.

Good question, I also don't know whether this frequent (*h) operation will cause performance degradation, but I can write a test make comparetion.

**Comment by jwasinger** [comment]
fyi, there's a pretty good web tool to view the assembly output of a given piece of code.

For [this code](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:go,selection:(endColumn:1,endLineNumber:21,positionColumn:1,positionLineNumber:21,selectionStartColumn:1,selectionStartLineNumber:21,startColumn:1,startLineNumber:21),source:'//+Type+your+code+here,+or+load+an+example.%0A//+Your+function+name+should+start+with+a+capital+letter.%0Apackage+main%0A%0Atype+nonceHeap+%5B%5Duint64%0A%0Afunc+(h+*nonceHeap)+PopOld()+interface%7B%7D+%7B%0A%09old+:%3D+*h%0A%09n+:%3D+len(old)%0A%09x+:%3D+old%5Bn-1%5D%0A%09old%5Bn-1%5D+%3D+0%0A%09*h+%3D+old%5B0+:+n-1%5D%0A%09return+x%0A%7D%0A%0Afunc+(h+*nonceHeap)+PopNew()+interface%7B%7D+%7B%0A%09var+x+interface%7B%7D%0A%09x,+*h+%3D+(*h)%5Blen(*h)-1%5D,+(*h)%5B:len(*h)-1%5D%0A%09return+x%0A%7D%0A%0Afunc+main()+%7B%0A++++var+n+nonceHeap%0A++++n.PopOld()%0A+++//+n.PopNew()%0A%7D%0A'),l:'5',n:'1',o:'Go+source+%231',t:'0')),k:33.333333333333336,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:gl1221,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1',verboseDemangling:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:go,libs:!(),options:'',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+gc+1.22.1+(Editor+%231)',t:'0')),k:33.333333333333336,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x86-64+gc+1.22.1',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x86-64+gc+1.22.1+(Compiler+%231)',t:'0')),k:33.33333333333333,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4), 

The generated asm looks somewhat similar from a glance.

**Comment by fjl** [comment]
It's OK to just leave the function as-is. As stated repeatedly in other PRs, we are not interested in refactoring/style changes with no clear benefit or justification.

**Pull request closed without merging**
