### PR TITLE
core/asm: optimize code

### PR DESCRIPTION
**Pull request by zgfzgf**

### CODE REVIEW

**Comment by fjl** [comment]
Could you explain this change a bit more? It seems to be a purely aesthetic change with no performance impact whatsoever.

**Comment by zgfzgf** [comment]
yes.  a purely aesthetic change
but easier to view and understand code

**Comment by fjl** [comment]
Thanks, that clears it up. I was just curious because you said 'optimize' in PR title, but now it's clear you mean 'optimize readability'.

**Comment by misamoo** [comment]
d

**Pull request merged**
