### PR TITLE
swarm: modify context key

### PR DESCRIPTION
**Pull request by KimMachineGun**
I think that define type with struct{} and using it as a context key is more go-ish.

And, actually golang/go project has been using it.

### CODE REVIEW

**Comment by KimMachineGun** [comment]
**Prev code can occur error by conflict context key inside the package.**

Although, It won't occur the error outside the package by `contextKey` type, it can still occur error inside the package.

If we define the new type with `struct{}` that to use context key, we can avoid the error by conflict context key both inside and outside the package. And `struct{}` has little benefit of memory allocation. 😂

I will solve that submodule issue ASAP.

_Sorry, I'm not good at English._ 😢

**Comment by KimMachineGun** [comment]
@justelad 
I solve that submodule issue and answer to your question. 😄

**Comment by justelad** [comment]
@KimMachineGun I am kind of neutral on this. 

The conflicting context keys would happen just if someone would introduce a key, inside that package, that isn't a part of the `iota` declaration and deliberately defines a key of an existing key; This is borderline malicious in intention (and then we might have bigger problem on our hands).

**Comment by KimMachineGun** [comment]
@zelig Sorry, I'm late. I will resolve that and push it ASAP.

**Comment by KimMachineGun** [comment]
@zelig Done!

**Pull request merged**
