### PR TITLE
graphql: add query timeout to prevent dos attack

### PR DESCRIPTION
**Pull request by ahmetavc**
https://github.com/ethereum/go-ethereum/issues/26026 as its proposed in this issue, I added the timeout

### CODE REVIEW

**Review by holiman — APPROVED** [review]
LGTM, but I wonder if 60s isn't a bit too lenient.

**Comment by Shiti** [comment]
We use graphql queries to fetch block and transaction data in bulk. The range of blocks we are able to fetch is between 100-1000. But the response time varies on the data size. Would it be possible to make this configurable ?

**Comment by ahmetavc** [comment]
> We use graphql queries to fetch block and transaction data in bulk. The range of blocks we are able to fetch is between 100-1000. But the response time varies on the data size. Would it be possible to make this configurable ?

**Comment by ahmetavc** [comment]
> We use graphql queries to fetch block and transaction data in bulk. The range of blocks we are able to fetch is between 100-1000. But the response time varies on the data size. Would it be possible to make this configurable ?

If the number of connections are not creating any problems, instead of making it configurable and failing fast, setting the limit according to max range would work fine imo.

**Comment by orangeagain** [comment]
make this configurable/ add a start parameter? like geth --querytimeout=2000ms

**Comment by fjl** [comment]
Scaling the timeout with request size is not possible in the general case. It's also not what this timeout is for. We mainly want to prevent totally stuck queries with this timeout, so it can be long.

**Review by s1na — APPROVED** [review]
LGTM. Error example:

```json
{
  "errors": [
    {
      "message": "context deadline exceeded"
    }
  ]
}
```

**Comment by s1na** [comment]
Actually this also interacts with the RPC WriteTimeout. The error I posted above will never be returned to the user because connection will be severed at the 30 seconds mark (See https://github.com/ethereum/go-ethereum/issues/21430 and https://github.com/ethereum/go-ethereum/pull/25457). I still don't think there's a harm in adding a timeout to graphql, but the original issue was actually a non-issue and the timeout set here is too long.

**Comment by ahmetavc** [comment]
> 
So something between 20-30 sec should be good? @s1na

**Comment by s1na** [comment]
@ahmetavc Yes let's shoot for a bit under 30 sec.

**Comment by fjl** [comment]
Wait, so we apply the RPC WriteTimeout to GraphQL connections as well?

**Comment by Doc-Pixel** [comment]
Question regarding the timeout: Can I disable this? I'm running large queries and get error messages like this:

```
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(1197 bytes read, 851 more expected)', IncompleteRead(1197 bytes read, 851 more expected))
```

I tried several approaches with requests, httpx to talk to the graphql on geth. 
Connected straight to the port as well as routing it through nginx. Seems geth is just chopping off data transfer.

Ideally you'd want to run a setup with a proper firewall config, and nginx or another webserver handling and limiting the traffic and timeouts for connections instead of exposing geth RPC / WSS directly to the internet. Hoping there's a parameter, read a through the issues here and the docs. Can't really figure out how to disable this.

**Comment by Doc-Pixel** [comment]
It's still giving the errors, gut feeling is that it is a little bit better.
I'm reducing the amount of blocks per call for now.

**Pull request merged**
