### PR TITLE
build: rename swarm deb package to ethereum-swarm; change swarm deb version from 1.8.x to 0.3.x

### PR DESCRIPTION
**Pull request by nonsense**
This PR makes it possible to package `ethereum-swarm`, but keep the binary name `swarm`.

According to `build/ci-notes.md`, I've run:
1. `go run build/ci.go debsrc -workdir dist`
2. `dpkg-buildpackage`
3. `dpkg-deb`, resulting in:

```
dpkg-deb -c geth-unstable_1.8.12+trusty_amd64.deb
drwxr-xr-x root/root         0 2018-06-14 14:11 ./
drwxr-xr-x root/root         0 2018-06-14 14:10 ./usr/
drwxr-xr-x root/root         0 2018-06-14 14:11 ./usr/bin/
-rwxr-xr-x root/root  21982224 2018-06-14 14:11 ./usr/bin/geth
drwxr-xr-x root/root         0 2018-06-14 14:10 ./usr/share/
drwxr-xr-x root/root         0 2018-06-14 14:10 ./usr/share/doc/
drwxr-xr-x root/root         0 2018-06-14 14:10 ./usr/share/doc/geth-unstable/
-rw-r--r-- root/root      3043 2018-06-14 13:56 ./usr/share/doc/geth-unstable/AUTHORS.gz
-rw-r--r-- root/root       172 2018-06-14 13:56 ./usr/share/doc/geth-unstable/changelog.gz
-rw-r--r-- root/root       647 2018-06-14 13:56 ./usr/share/doc/geth-unstable/copyright
```

```
dpkg-deb -c ethereum-swarm-unstable_1.8.12+trusty_amd64.deb
drwxr-xr-x root/root         0 2018-06-14 14:11 ./
drwxr-xr-x root/root         0 2018-06-14 14:10 ./usr/
drwxr-xr-x root/root         0 2018-06-14 14:11 ./usr/bin/
-rwxr-xr-x root/root  20353360 2018-06-14 14:11 ./usr/bin/swarm
drwxr-xr-x root/root         0 2018-06-14 14:10 ./usr/share/
drwxr-xr-x root/root         0 2018-06-14 14:10 ./usr/share/doc/
drwxr-xr-x root/root         0 2018-06-14 14:10 ./usr/share/doc/ethereum-swarm-unstable/
-rw-r--r-- root/root      3043 2018-06-14 13:56 ./usr/share/doc/ethereum-swarm-unstable/AUTHORS.gz
-rw-r--r-- root/root       172 2018-06-14 13:56 ./usr/share/doc/ethereum-swarm-unstable/changelog.gz
-rw-r--r-- root/root       647 2018-06-14 13:56 ./usr/share/doc/ethereum-swarm-unstable/copyright
```

Related discussion on naming: https://github.com/ethersphere/go-ethereum/issues/191

### CODE REVIEW

**Comment by nonsense** [comment]
@karalabe shall we also add `ubuntu/cosmic` to distros? It looks like newer docker images are already using it.

**Comment by nonsense** [comment]
cc @gbalint @lmars FYI

**Comment by lmars** [comment]
Personally I feel like geth and Swarm have very different release schedules and versions, so having them in the same debian package with the same release schedule and version probably doesn't make sense.

**Comment by gbalint** [comment]
@nonsense I agree with delaying this merge until we figure this out properly

**Comment by homotopycolimit** [comment]
Or (let me just say it) the go-ethereum version should not be the same thing as the geth version.
So installing go-ethereum-2018-06-28 would install geth 1.8.11 and swarm 0.3 and the other tools with their own versions...

**Comment by nonsense** [comment]
@homotopycolimit this makes sense, I can see `geth`, `swarm` and `wnode` at the very least having different release schedules and versions.

**Comment by nonsense** [comment]
I have refactored further the code, in order to be able to configure multiple Debian Meta packages, in order to have a different version for `ethereum-swarm` and not use the `ethereum` or `geth` version for it.

I have also hacked `ethereum-swarm` as a dependency in the `ethereum` meta Debian package, so that we continue to have it installed in case people install `ethereum`.

I have also included swarm as part of the archives we push to the Azure Blobstore - I still haven't verified if this will have an effect on https://geth.ethereum.org/downloads/ , will report on that. Ideally it should not have an effect, and we should also use a similar page on swarm side to distribute prebuilt binaries of releases.

All this assumes that we release `geth`, `swarm` and everything else at the same time, which we are fine with. I think it is good to have small incremental releases every 2-3 weeks for all projects, so for now we don't want to split the actual release process, but only fix the debian package conflict and use a meaningful version.

cc @karalabe @fjl let me know what you think.

I have tested this locally and this is how the resulting packages look:

```
ethereum-unstable

root@af8bfdb6926a:/go/src/github.com/ethereum/go-ethereum/dist# dpkg -I ethereum-unstable_1.8.12+xenial_amd64.deb
 new debian package, version 2.0.
 size 1544 bytes: control archive=492 bytes.
     468 bytes,    11 lines      control
     155 bytes,     2 lines      md5sums
 Package: ethereum-unstable
 Version: 1.8.12+xenial
 Architecture: amd64
 Maintainer: Ethereum Builds <fjl@ethereum.org>
 Installed-Size: 8
 Depends: ethereum-swarm-unstable, abigen-unstable, bootnode-unstable, evm-unstable, geth-unstable, puppeth-unstable, rlpdump-unstable, wnode-unstable
 Section: science
 Priority: extra
 Homepage: https://ethereum.org
 Description: Meta-package to install geth, swarm, and other tools
  Meta-package to install geth, swarm and other tools

root@af8bfdb6926a:/go/src/github.com/ethereum/go-ethereum/dist# dpkg-deb -c ethereum-unstable_1.8.12+xenial_amd64.deb
drwxr-xr-x root/root         0 2018-07-19 14:32 ./
drwxr-xr-x root/root         0 2018-07-19 14:32 ./usr/
drwxr-xr-x root/root         0 2018-07-19 14:32 ./usr/share/
drwxr-xr-x root/root         0 2018-07-19 14:32 ./usr/share/doc/
drwxr-xr-x root/root         0 2018-07-19 14:32 ./usr/share/doc/ethereum-unstable/
-rw-r--r-- root/root       170 2018-07-19 14:30 ./usr/share/doc/ethereum-unstable/changelog.gz
-rw-r--r-- root/root       647 2018-07-19 14:30 ./usr/share/doc/ethereum-unstable/copyright
```

```
swarm unstable

root@af8bfdb6926a:/go/src/github.com/ethereum/go-ethereum/dist# dpkg -I ethereum-swarm-unstable_0.3.1+xenial_amd64.deb
 new debian package, version 2.0.
 size 5186448 bytes: control archive=528 bytes.
     347 bytes,    12 lines      control
     298 bytes,     4 lines      md5sums
 Package: ethereum-swarm-unstable
 Version: 0.3.1+xenial
 Architecture: amd64
 Maintainer: Ethereum Builds <fjl@ethereum.org>
 Installed-Size: 19893
 Depends: libc6 (>= 2.14)
 Conflicts: ethereum, ethereum-swarm
 Section: science
 Priority: extra
 Homepage: https://ethereum.org
 Description: Ethereum Swarm daemon and tools
  Ethereum Swarm daemon and tools

root@af8bfdb6926a:/go/src/github.com/ethereum/go-ethereum/dist# dpkg-deb -c ethereum-swarm-unstable_0.3.1+xenial_amd64.deb
drwxr-xr-x root/root         0 2018-07-19 14:35 ./
drwxr-xr-x root/root         0 2018-07-19 14:35 ./usr/
drwxr-xr-x root/root         0 2018-07-19 14:35 ./usr/bin/
-rwxr-xr-x root/root  20357456 2018-07-19 14:35 ./usr/bin/swarm
drwxr-xr-x root/root         0 2018-07-19 14:35 ./usr/share/
drwxr-xr-x root/root         0 2018-07-19 14:35 ./usr/share/doc/
drwxr-xr-x root/root         0 2018-07-19 14:35 ./usr/share/doc/ethereum-swarm-unstable/
-rw-r--r-- root/root      3043 2018-07-19 14:29 ./usr/share/doc/ethereum-swarm-unstable/AUTHORS.gz
-rw-r--r-- root/root       174 2018-07-19 14:29 ./usr/share/doc/ethereum-swarm-unstable/changelog.gz
-rw-r--r-- root/root       647 2018-07-19 14:29 ./usr/share/doc/ethereum-swarm-unstable/copyright
```

```
geth stable

root@af8bfdb6926a:/go/src/github.com/ethereum/go-ethereum/dist# dpkg -I geth_1.8.12+xenial_amd64.deb
 new debian package, version 2.0.
 size 5715752 bytes: control archive=504 bytes.
     288 bytes,    12 lines      control
     240 bytes,     4 lines      md5sums
 Package: geth
 Source: ethereum
 Version: 1.8.12+xenial
 Architecture: amd64
 Maintainer: Ethereum Builds <fjl@ethereum.org>
 Installed-Size: 21472
 Depends: libc6 (>= 2.14)
 Section: science
 Priority: extra
 Homepage: https://ethereum.org
 Description: Ethereum CLI client.
  Ethereum CLI client.
```

```
swarm stable

root@af8bfdb6926a:/go/src/github.com/ethereum/go-ethereum/dist# dpkg -I ethereum-swarm_0.3.1+xenial_amd64.deb
 new debian package, version 2.0.
 size 5188546 bytes: control archive=502 bytes.
     302 bytes,    11 lines      control
     271 bytes,     4 lines      md5sums
 Package: ethereum-swarm
 Version: 0.3.1+xenial
 Architecture: amd64
 Maintainer: Ethereum Builds <fjl@ethereum.org>
 Installed-Size: 19885
 Depends: libc6 (>= 2.14)
 Section: science
 Priority: extra
 Homepage: https://ethereum.org
 Description: Ethereum Swarm daemon and tools
  Ethereum Swarm daemon and tools
```

```
ethereum stable

root@af8bfdb6926a:/go/src/github.com/ethereum/go-ethereum/dist# dpkg -I ethereum_1.8.12+xenial_amd64.deb
 new debian package, version 2.0.
 size 1524 bytes: control archive=480 bytes.
     387 bytes,    11 lines      control
     137 bytes,     2 lines      md5sums
 Package: ethereum
 Version: 1.8.12+xenial
 Architecture: amd64
 Maintainer: Ethereum Builds <fjl@ethereum.org>
 Installed-Size: 8
 Depends: ethereum-swarm, abigen, bootnode, evm, geth, puppeth, rlpdump, wnode
 Section: science
 Priority: extra
 Homepage: https://ethereum.org
 Description: Meta-package to install geth, swarm, and other tools
  Meta-package to install geth, swarm and other tools
```

**Comment by nonsense** [comment]
@karalabe @fjl this also means that alongside updating the `params` and tagging the release, we would also have to update the `params` for Swarm and bump up versions there, when we make a patch release. I hope this is not too much trouble.

**Comment by fjl** [comment]
I don't really agree with separating out the swarm version.

**Comment by nonsense** [comment]
I think we should separate the versions, because Swarm is not production-ready yet, and 1.8.12 (or similar) conveys an opposite meaning.

I think we should at least push binaries to Azure and to Ubuntu PPA with a more meaningful Swarm version, such as 0.3.1, for the foreseeable future.

Regarding tagging - I was thinking for now to keep only the geth/go-ethereum tag/version - v1.8.11 and not tag Swarm at all, just make sure we distribute it alongside Geth with the correct version. People would then be getting the correct versions from our website and from Ubuntu, and if they want to build from source, they would have to have the knowledge that we are tight to the Geth releases.

This proposal does not mean splitting the release process though! We should not have a Swarm-only or Geth-only release in the github release pages - the release process stays as it is.

**Comment by nonsense** [comment]
Rebased to master to resolve conflicts.

@fjl In `5f84441`, I removed the `VERSION` file, by:
1. Rename `params.Version` to `params.VersionWithMeta`
2. Introduced `params.Version`, which is identical to the VERSION file.
3. Introduced `params.ArchiveVersion(gitCommit string)` which is identical to `archiveVersion(env build.Environment, versionFilePath string)` which is now removed.

Therefore I think the code is equivalent, but we no longer need the VERSION files.

**Comment by nonsense** [comment]
@lmars you can review again as well, as the PR has changed considerably since your review.
cc @gbalint

**Pull request merged**
