### PR TITLE
core/types: convert status type from uint to uint64

### LINKED ISSUE #16750: Do not use `uint` in consensus datastructures.
https://github.com/ethereum/go-ethereum/blob/master/core/types/receipt.go#L49

https://golang.org/pkg/builtin/#uint

> uint is an unsigned integer type that is at least 32 bits in size. It is a distinct type, however, and not an alias for, say, uint32. 

`uint` in golang isn't guaranteed to be exactly 32-bits, so it should not be used in a datastructure that needs to be serialized or hashed since future compilers may use uint64 under the hood.

### PR DESCRIPTION
**Pull request by rjl493456442**
Fix #16750 
This PR is not a bugfix, just eliminate some misleading stuff.

### CODE REVIEW

**Comment by karalabe** [comment]
Why `uint32` and not `uint64`? Also you still use `hextuil.Uint` for the conversions, so that might still lead through `uint` anyway.

**Comment by rjl493456442** [comment]
@karalabe Updated

**Comment by karalabe** [comment]
It was more of a question than a change request.

**Comment by rjl493456442** [comment]
Actually there is no difference we convert uint to uint32 or uint64. All of these will not affect the correctness. 
For the `hexutil.Uint`, it will finally marshaled as a `hexutil.Uint64`. But maybe the `uint64` and `hexutil.Uint64` will make definition more clear.

**Pull request merged**
