### PR TITLE
Geth 1.4.11

### PR DESCRIPTION
**Pull request by obscuren**

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Thu Aug 18 12:58:26 UTC 2016_

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 6bd3bd4405b9488ece6038c07e8006345d1473f4
  * Commit subjects should be kept under 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 626604e86d9a47900e6da5fc003f7009bb239940
  * Commit subjects should be kept under 80 characters

 * Commit: 6c672a55c0622dfb133b67280fc593a0212eae76
  * Commit subjects should be kept under 80 characters

 * Commit: 86493f91032bd56831d6d6e6e63b23e17f24dcd2
  * Commit subjects should be kept under 80 characters

 * Commit: c4e4baf6682a32e129b19dd16258e6b693c2ba43
  * Commit subjects should be kept under 80 characters

 * Commit: bdbfe572f1fb51710256b78065a0a330a3970a89
  * Commit subjects should be kept under 80 characters

 * Commit: f4d7cdad483ab6e477633ceb074460f9ec520bf9
  * Commit subjects should be kept under 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by fjl** [comment]
:+1:

**Comment by karalabe** [comment]
Please add ethereum/go-ethereum#2685, otherwise the MIPS PR breaks xgo.

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 626604e86d9a47900e6da5fc003f7009bb239940
  * Commit subjects should be kept under 80 characters

 * Commit: 6c672a55c0622dfb133b67280fc593a0212eae76
  * Commit subjects should be kept under 80 characters

 * Commit: 86493f91032bd56831d6d6e6e63b23e17f24dcd2
  * Commit subjects should be kept under 80 characters

 * Commit: c4e4baf6682a32e129b19dd16258e6b693c2ba43
  * Commit subjects should be kept under 80 characters

 * Commit: bdbfe572f1fb51710256b78065a0a330a3970a89
  * Commit subjects should be kept under 80 characters

 * Commit: c4ed34f008ae508549c03ec286467f48b188272f
  * Commit subjects should be kept under 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
