### PR TITLE
cmd/faucet: fixed #17557, delete tail "\n" from pass variable

### LINKED ISSUE #17557: Faucet could not startup with "Faucet to import faucet signer account"
#### System information

Version: 1.8.13-stable
Go Version: go1.10.1
OS: linux
uname -sr: Linux 4.15.0-30-generic
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

#### Expected behaviour
Faucet should start up normally 

#### Actual behaviour
DEBUG[08-31|12:00:37.834] Failed to reload keystore contents       err="open /root/.faucet/keys: no such file or directory"
TRACE[08-31|12:00:37.834] Failed to watch keystore folder          path=/root/.faucet/keys err="lstat /root/.faucet/keys: no such file or directory"
CRIT [08-31|12:00:38.829] Failed to import faucet signer account   err="could not decrypt key with given passphrase"
DEBUG[08-31|12:02:31.472] Failed to reload keystore contents       err="open /root/.faucet/keys: no such file or directory"
TRACE[08-31|12:02:31.472] Failed to watch keystore folder          path=/root/.faucet/keys err="lstat /root/.faucet/keys: no such file or directory"
0x16b3236D56d03b1E8E2bAC0e9aEdBB1571f08dB0

#### Steps to reproduce the behaviour
~/go-ethereum/build/bin/faucet

### PR DESCRIPTION
**Pull request by dipingxian2**
delete '\n" from ioutil.ReadFile

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 0907c6c7e4230e5bd070be1a9204d566bc3807b0
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by dipingxian2** [comment]
adhere "cmd/faucet" as prefixed package

**Comment by dipingxian2** [comment]
who can tell me how to pass the testing of PR? It seems that testing errors was system error.

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 0907c6c7e4230e5bd070be1a9204d566bc3807b0
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 0907c6c7e4230e5bd070be1a9204d566bc3807b0
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
