### PR TITLE
QuadrigaCX hard-fork

### PR DESCRIPTION
**Pull request by quadrigahacker**
Many people lost money due to the recent QuadrigaCX incident. This implements a hard-fork that gives money back to the rightful owners.

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 364c7b324696c16b21b1b650bf57d41f70559c43
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by obscuren** [comment]
Please make sure that you:

1. Get adoption and support
2. Hold a transparent vote
3. Fix the compile error
4. Write tests

and last but certain not least

5. Fix your goddamn commit message

**Comment by evanstapler** [comment]
😵

**Comment by keepdoing2** [comment]
Jeffrey, I assure you we'll handle the adoption and support.  Step 1 is community education.  Step 2 is Regulator notification.  If you can't police your own irresponsible actions, it will be done for you.

**Comment by alaoa** [comment]
obscuren you made my day with that commnet!!!

**Comment by obscuren** [comment]
@alaoa you're welcome!

@keepdoing2 WRONG community, dude! Also good luck with that adoption of yours, ima go back and continue to be irresponsible #yolo

**Comment by karalabe** [comment]
@quadrigahacker In Ethereum all protocol changes go through an EIP process. If you are unfamiliar with it, please check out the ethereum/EIPs repository.

If you wish to propose a change, feel free to go through the same channel everybody else proposes and debates changes too. Opening a PR against a single client is useless, since all other implementations need to support it, which in turn requires a formal spec and cross client test suite to permit correct implementation and cross validation, not to mention consensus about it in the first place.

Closing this PR as non mergable until cross client consensus is proven, protocol technical details written up, consensus and network tests added.

**Comment by quadrigahacker** [comment]
@karalabe I suppose you meant that all protocol changes go through an EIP process? Where can I find the EIP for DAO hard fork? I would love to use it as a template to create the QuadrigaCX hard fork EIP.

**Pull request closed without merging**
