### PR TITLE
core: fix log order in "Imported new chain segment"

### PR DESCRIPTION
**Pull request by fjl**

### CODE REVIEW

**Review by lightclient — APPROVED** [review]
LGTM

**Comment by holiman** [comment]
"fix" ? You mean change?

**Comment by karalabe** [comment]
Funky

**Comment by fjl** [comment]
I can explain. This changes the logs to look like this

```
INFO [09-15|15:43:12.807] Imported new potential chain segment     number=15,539,464 hash=cbe511..2a7490 blocks=1  txs=145  mgas=7.354  elapsed=25.708ms 
INFO [09-15|15:43:12.890] Chain head was updated                   number=15,539,464 hash=cbe511..2a7490 root=48b1be..5409df elapsed=2.668276ms
```

i.e. the block number and hash will be shown in the same column for both log lines.

**Comment by holiman** [comment]
Yes that's fine. I originally mistook it to be the other way around :)

**Pull request merged**
