### PR TITLE
README, core, rpc: Fix typos

### PR DESCRIPTION
**Pull request by fabioberger**
- Modified `as an gateway` to `as a gateway` in README
- Fixed 3 typos in core
- Fixed 4 typos in rpc

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Tue Jun 21 05:06:47 UTC 2016_

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: a765751d732152d19115309939b08d381d8b6c79
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by karalabe** [comment]
Hey, thanks for fixing these. Could you please squash your commits into a single one (`git rebase -i HEAD~2`, change the second to `fixup`) and please also amend the commit message to include the packages modified: e.g. "README, core, rpc: fix various typos" (`git commit --amend`). These are needed to be consistent with our repository's coding standards.

After making these changes just force push them (`git push -f`) and this PR will be updated appropriately and we can merge in the changes.

**Comment by fabioberger** [comment]
Hey @karalabe, I made the changes you requested, will be sure to rebase instead of merge from now on, sorry about that!

**Comment by karalabe** [comment]
Thanks for these changes :) LTGM :+1:

**Pull request merged**
