### PR TITLE
accounts/abi/bind: generate java structs

### PR DESCRIPTION
**Pull request by MariusVanDerWijden**
This commit enables struct generation for contracts on java.
It will generate for the TUPLE contract the following:
```
// TupleP is an auto generated low-level Java binding around an user-defined struct.
	public class TupleP {
		public BigInt x;
		public BigInt y;
	}

	// TupleQ is an auto generated low-level Java binding around an user-defined struct.
	public class TupleQ {
		public BigInt x;
		public BigInt y;
	}

	// TupleS is an auto generated low-level Java binding around an user-defined struct.
	public class TupleS {
		public BigInt a;
		public BigInts b;
		public TupleT[] c;
	}

	// TupleT is an auto generated low-level Java binding around an user-defined struct.
	public class TupleT {
		public BigInt x;
		public BigInt y;
	}

	// Func1Results is the output of a call to func1.
	public class Func1Results {
		public TupleS Return0;
		public TupleT[][] Return1;
		public TupleT[][] Return2;
		public TupleS[] Return3;
		public BigInts Return4;
	}
```

### CODE REVIEW

**Comment by rjl493456442** [comment]
Hi marius, the struct java-binding is not easy. I tried to resolve it maybe 1 year ago. I'm not sure I still remember the detail.

The hard part is: *we only have a few in-built structures* to pass from Java-Go for `mobile/bind-Call` invocation.

The in-built types include some primitive types like `BigInt`, `BigInts`, `Strings`, `Bools`, etc. And we also support two generic types `Interface` and `Interfaces`. So that you can pass a batch of Java parameters (e.g. [Strings, Bools, BigInts]) as the `Interfaces` to the Go side for `bind-Call` invocation.

For tuple type parameter, we can generate the java-binding easily. However it's not easy to pass them to the Go side. One trick I used before is to transition them as the `Interfaces` format.

E.g.

```java
public class TupleT {
	public BigInt x;
	public BigInt y;
}
```

can be converted as

```go
Interfaces args = Geth.newInterfaces(2);
Interface arg0 = Geth.newInterface();arg0.setBigInt(t.x);args.set(0,arg0);
Interface arg1 = Geth.newInterface();arg1.setBigInt(t.y);args.set(1,arg1);
```

Only in this way we can pass the struct to Go.

And the tuple can include some nested tuple, nested tuple array, etc.. 

So my recommendation is: try to use the android package generated by `go-mobile` and write some simple test in Java. Then you will find the issues.

**Comment by rjl493456442** [comment]
See https://godoc.org/golang.org/x/mobile/cmd/gobind for supported types in `gomobile`

**Comment by rjl493456442** [comment]
You can check some my old hacks https://github.com/rjl493456442/go-ethereum/tree/java-tuple-hack. 

I just find it in my stash list. Maybe it can't be compiled :P

**Comment by MariusVanDerWijden** [comment]
closing, needs more work

**Pull request closed without merging**
