### PR TITLE
node: stop p2p.Server before stopping services

### PR DESCRIPTION
**Pull request by fjl**
This prevents printing of a gazillion error messages which
result from connections trying to interact with stopped core
services. In particular, stopping the eth also closes its databases,
but peer connections still receive transactions while they stop.

```text
I0129 11:17:34.845276 cmd/utils/cmd.go:122] Got interrupt, shutting down...
I0129 11:17:34.894570 core/blockchain.go:1251] imported 219 block(s) (0 queued 0 ignored) including 340 txs in 2.770893391s. #692742 [74f3c6dd / dca9ccef]
I0129 11:17:34.907584 core/blockchain.go:686] Chain manager stopped
I0129 11:17:34.907607 eth/handler.go:192] Stopping ethereum protocol handler...
I0129 11:17:34.907640 eth/handler.go:202] Ethereum protocol handler stopped
I0129 11:17:34.907670 core/transaction_pool.go:151] Transaction pool stopped
I0129 11:17:34.908438 eth/backend.go:461] Automatic pregeneration of ethash DAG OFF (ethash dir: /home/fjl/.ethash)
============= eth service is stopped at this point, peer goroutines are still running ===========
E0129 11:17:34.908809 trie/secure_trie.go:70] Unhandled trie error: Missing trie node fb40fd1e25dba210a565741e66babf5019b77572d3d8403f5f873de6b23c9920
E0129 11:17:34.908846 trie/secure_trie.go:70] Unhandled trie error: Missing trie node fb40fd1e25dba210a565741e66babf5019b77572d3d8403f5f873de6b23c9920
E0129 11:17:34.909144 core/transaction_pool.go:421] could not get current state: Missing trie node 1225e08bdb598abb2cee7d0eed3416726834832bf3d7073461a451414c226ea7
E0129 11:17:34.909168 trie/secure_trie.go:70] Unhandled trie error: Missing trie node bc0131241a3b5b98889308f7094ca875fff1764292d7710f22be93cbd88b4a49
E0129 11:17:34.909195 trie/secure_trie.go:70] Unhandled trie error: Missing trie node bc0131241a3b5b98889308f7094ca875fff1764292d7710f22be93cbd88b4a49
E0129 11:17:34.909445 core/transaction_pool.go:421] could not get current state: Missing trie node 1225e08bdb598abb2cee7d0eed3416726834832bf3d7073461a451414c226ea7
E0129 11:17:34.909482 trie/secure_trie.go:70] Unhandled trie error: Missing trie node 13046e6f0922d0b4be2dee026b3f6e8edf7194905b9ea58eac60ef02bd1968ca
............................. a billion more messages like this ..............
```

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Fri Jan 29 10:33:37 UTC 2016_

**Comment by fjl** [comment]
Damn, I did some more testing and it doesn't seem to resolve the issue completely. Will look a bit further.

**Comment by karalabe** [comment]
Is this PR still up for review, or should I put it back in progress state?

**Comment by fjl** [comment]
Will put back to in progress.

**Comment by fjl** [comment]
Closing this because it doesn't fix the issue at all.

**Pull request closed without merging**
