### PR TITLE
Typo fixed

### PR DESCRIPTION
**Pull request by 6londe**
README typo fixed

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Thu May 12 08:29:13 UTC 2016_

**Comment by karalabe** [comment]
Thanks :+1:

**Comment by karalabe** [comment]
Ah, please rename the commit to `README: fix typos`. We require out commits to be tagged with the packages/files they changes, otherwise it's very hard to track changes.

**Comment by 6londe** [comment]
@karalabe Thanks for your kindness :)

**Pull request closed without merging**
