### PR TITLE
snapshot: merge loops for better performance

### PR DESCRIPTION
**Pull request by ehnuje**
- data size check loop can be merged with sanity check routine.

### CODE REVIEW

**Comment by holiman** [comment]
I suspect that the intent was to eventually remove the panicky loops, hence why they're not already merged

**Comment by karalabe** [comment]
Perhaps, but I do think we should leave the panics in. If we mess up something, we should really blow up as soon as possible. Without the panics, we could end up with a consensus split, which arguably is worse.

**Comment by ehnuje** [comment]
I agree with the point that @karalabe mentioned, since data corruption here is the worst case we don't want in snapshot and panic here helps revealing the underlying problem, if exists.

**Review by holiman — APPROVED** [review]
LGTM

**Pull request merged**
