### PR TITLE
[Ignore] : pogreb test

### PR DESCRIPTION
**Pull request by holiman**
The barest minimal pogreb implementation

### CODE REVIEW

**Comment by holiman** [comment]
After running for half a day, the pogreb db size is `100G`, and the leveldb size is about `21G`, a factor of five difference (on the chart, 50G stems from some other data that resides on the same disk, so that should be ignored). 
Screenshot_2019-09-04 Enterprise Benchmark Dashboard Pro+ Datadog

Additionally, we did disable freezer, since some testing indicated that things became _really_ slow when we started deleting things from pogreb. Also, although the two are still roughly head-to-head, the `master` has `2G` extra memory usage, due to the leveldb caches, which we didn't give `pogreb`, which is a bit unfair.

**Comment by holiman** [comment]
After a couple of days, they're both roughly head-to-head
Screenshot_2019-09-05 Enterprise Benchmark Dashboard Pro+ Datadog
But the size of the pogreb database is really balooning out of control:
Screenshot_2019-09-05 Enterprise Benchmark Dashboard Pro+ Datadog(1)

**Comment by karalabe** [comment]
Yeah, benchmarks nuked. Pogreb seems to be wasting a 5x disk space on empty bucket slots. We might want to reach out to the upstream project for some guidance, but I see little hope.

**Comment by akrylysov** [comment]
Thanks for running the benchmarks. The issue will be addressed in Pogreb 0.9 https://github.com/akrylysov/pogreb/issues/24.

**Pull request closed without merging**
