### PR TITLE
`discv5` wormhole

### PR DESCRIPTION
**Pull request by lightclient**
wip

### CODE REVIEW

**Comment by holiman** [comment]
@fjl why did you close this??

**Comment by fjl** [comment]
I closed it because it was an experiment! I don't think we intend to ship it as a feature in cmd/devp2p?

**Comment by holiman** [comment]
I actually wanted this... :cry:

**Comment by fjl** [comment]
We can always develop this further as a standalone tool! The prototype doesn't depend on any go-ethereum internals. It can also be added as a subcommand of cmd/devp2p, but I'd want to do some further development before that.

Either way, to get this in, we'd need to submit the fixes for `Unhandled` to master.

**Pull request closed without merging**
