### PR TITLE
crypto/bn256: eliminate dead store

### PR DESCRIPTION
**Pull request by cuiweixie**

### CODE REVIEW

**Review by holiman — APPROVED** [review]
LGTM

**Comment by cuiweixie** [comment]
the check have failed. it seems not cause by change of this pr.

**Comment by cuiweixie** [comment]
> LGTM

@holiman  should we fix the check and then merge the pr. or we just merge the pr.

**Comment by holiman** [comment]
Yeah don't worry about unrelated CI failures

**Comment by fjl** [comment]
Please note that crypto/bn256/cloudflare is vendored from https://github.com/cloudflare/bn256. You should probably submit this change upstream, otherwise it will get lost if we ever pull changes from upstream again.

**Comment by cuiweixie** [comment]
> https://github.com/cloudflare/bn256

see https://github.com/cloudflare/bn256/pull/37

**Pull request merged**
