### PR TITLE
tests: update for London 

### PR DESCRIPTION
**Pull request by holiman**
This is a bit work in progress

- [x] update the tests
- [x]  fix statetests
- [x] fix blockchain tests

### CODE REVIEW

**Comment by holiman** [comment]
Rebased!

**Comment by holiman** [comment]
Depends on https://github.com/ethereum/tests/issues/865#issuecomment-852849898

**Comment by winsvega** [comment]
in rejected transactions: 
```
"rejected": [
  {
   "index": 0,
   "error": "insufficient funds for gas * price + value: address 0xa94f5374Fce5edBC8E2a8697C15331677e6EbF0B have 132000 want 23679000"
  }

```

would be good to have trHash to be sure which transaction are we talking about

**Comment by winsvega** [comment]
good

**Comment by holiman** [comment]
The tests now seem to be working (but we'll see what travis says). I think this PR is needed in order to get them working on hive aswell, because we need to have `baseFee` support in genesis specification there, which this PR provides. cc @renaynay

**Pull request merged**
