### PR TITLE
Ethash reloaded

### PR DESCRIPTION
**Pull request by Gustav-Simonsson**
* Update Godeps with ethash master branch
* Integrate new ethash API & new makeDAG cmd
* Unskip blocktests as they are much faster with ethash cache reusage

### CODE REVIEW

**Comment by Gustav-Simonsson** [comment]
One TODO: make DAG progress reporting work with geth makeDAG. @LefterisJP @fjl any idea why it's working when DAG is generated in Search call but not when MakeDAG is called?

**Comment by fjl** [comment]
The makedag command doesn't set the right log level.

**Comment by obscuren** [comment]
Builds on windows and linux are broken.

**Comment by Gustav-Simonsson** [comment]
@obscuren @fjl https://github.com/ethereum/ethash/pull/52  Please review - all builds seems to work

**Comment by LefterisJP** [comment]
For some strange reason it does not show the diff I commented on.

**Pull request merged**
