### PR TITLE
rpc/json.go : add response status

### PR DESCRIPTION
**Pull request by af913337456**
make it easier for the client to handle the request results

### CODE REVIEW

**Comment by karalabe** [comment]
A status field is not part of the JSON RPC spec https://www.jsonrpc.org/specification#response_object.

**Comment by af913337456** [comment]
@karalabe Yes, but without state, the client will have a hard time handling the returned results, and more work needs to be done to distinguish between success and failure.

**Comment by jsvisa** [comment]
maybe you can check the `Error`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by karalabe** [comment]
I don't really see why. If there's an error field, something failed. If there's no error field, everything is happy. Any modern JSON parser should be able to handle optionally present fields. You can set both the `error` and `result` as optional, and see which was sent.

**Pull request closed without merging**
