### PR TITLE
p2p: logs peer statistics in seperate goroutine

### PR DESCRIPTION
**Pull request by iyume**
## Reason

The dialer main loop blocks this line of code: https://github.com/ethereum/go-ethereum/blob/a14301823ea4da3004f05584ca1093d1d626819d/p2p/dial.go#L240

When no bootnode and staticnode are configured, logStat will not execute.

The code may not be written very well, looking forward to improvement.

## Reproduce

```
geth --datadir data --bootnodes "" --netrestrict "10.0.0.0/8"
```

`netrestrict` can be any fake CIDR masks.

### CODE REVIEW

**Comment by karalabe** [comment]
This is a loop spinning like crazy calling logging non stop. Why is this needed in the first place?

**Comment by iyume** [comment]
@karalabe As I said in PR comment: "When no bootnode and staticnode are configured, logStat will not execute."

The missing logs of "Looking peer" sometime confused people. We don't know whether the peer has reached the maximum number of connections or is not connected at all. If it is proper, then just ignored this PR.

**Comment by iyume** [comment]
It can be implemented using Timer for performance. I will push the updates later.

**Comment by holiman** [comment]
> When no bootnode and staticnode are configured, logStat will not execute.

Why is that?

**Comment by iyume** [comment]
> Why is that?

@holiman 

https://github.com/ethereum/go-ethereum/blob/a14301823ea4da3004f05584ca1093d1d626819d/p2p/dial.go#L242

`select` waits for signal and blocks the code.

**Comment by iyume** [comment]
I have committed the implementation. Help me review it 👌

**Comment by fjl** [comment]
It's not possible to just put the logging to a different goroutine because they are modified by the main loop (data race).
My thinking with these messages was: the node will log "Looking for peers" when it is actually looking for peers. If the dialer is not running for lack of nodes from discovery, certainly it is not looking for peers.

It would be better to print a warning message when no peers were discovered for a long time.

**Comment by iyume** [comment]
I'm sorry for my naive knowledge of go-ethereum.

> It would be better to print a warning message when no peers were discovered for a long time.

I pushed a similar implementation, can u help check it?

**Comment by holiman** [comment]
> My thinking with these messages was: the node will log "Looking for peers" when it is actually looking for peers. If the dialer is not running for lack of nodes from discovery, certainly it is not looking for peers.

This makes sense to me: if we are not actually looking for peers, I don't think we should say "Looking for peers" every `10` seconds. Which I think is what this PR currently does?

**Comment by fjl** [comment]
I don't get it either. Sorry @iyume, we're closing this.

**Pull request closed without merging**
