### PR TITLE
core: allow rewinding to block 0

### PR DESCRIPTION
**Pull request by zhiqiangxu**
`0` is a possible value for block number, but impossible for block time.

This PR tries to allow explicitly rewinding to block `0` by adding `ConfigCompatError.RewindByBlock` field.

Previously there's no way to explicitly rewind to block `0` according to [this condition](https://github.com/ethereum/go-ethereum/blob/cc22e0cdf0468947265883921b0c29119ca0327a/core/genesis.go#L357).

### CODE REVIEW

**Comment by lightclient** [comment]
If you're going to rewind to block 0, why override the config at all? Why not initialize with the config you desire?

**Comment by zhiqiangxu** [comment]
> If you're going to rewind to block 0, why override the config at all? Why not initialize with the config you desire?

They should do the same thing, right?

**Review by holiman — COMMENTED** [review]
Instead of adding a `RewindByBlock`, we could turn `RewindToBlock` into an `int64`, and make `-1` denote the "not used" value.

**Comment by zhiqiangxu** [comment]
> Instead of adding a `RewindByBlock`, we could turn `RewindToBlock` into an `int64`, and make `-1` denote the "not used" value.

Good idea, done!

**Pull request closed without merging**
