### PR TITLE
les, light: LES/2 protocol version

### PR DESCRIPTION
**Pull request by zsfelfoldi**
This PR implements the new LES protocol version extensions:

- new and more efficient Merkle proofs reply format (when replying to a multiple Merkle proofs request, we just send a single set of trie nodes containing all necessary nodes)
- BBT (BloomBitsTrie) works similarly to the existing CHT and contains the bloombits search data to speed up log searches
- GetTxStatusMsg returns the inclusion position or the pending/queued/unknown state of a transaction referenced by hash
- an optional signature of new block data (number/hash/td) can be included in AnnounceMsg to provide an option for "very light clients" (mobile/embedded devices) to skip expensive Ethash check and accept multiple signatures of somewhat trusted servers (still a lot better than trusting a single server completely and retrieving everything through RPC). The new client mode is not implemented in this PR, just the protocol extension.

Updated protocol documentation:
https://github.com/zsfelfoldi/go-ethereum/wiki/Light-Ethereum-Subprotocol-(LES)
https://github.com/zsfelfoldi/go-ethereum/wiki/BloomBits-Trie

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 30fe2431930c5b4f4da619f921132b184c3869c3
  * Commits must be prefixed with the package(s) they modify

 * Commit: 771eccad5cc5d386c34875b7e83e6c3f6ac70787
  * Commits must be prefixed with the package(s) they modify

 * Commit: 1d5e142f2ec8ec12901ee8c24a3fbbeb160a335c
  * Commits must be prefixed with the package(s) they modify

 * Commit: 0bc5a7b11ffb0ccb8f3e7977177ba493b8daa216
  * Commits must be prefixed with the package(s) they modify

 * Commit: ef1868909d1c5acbd173999e74bd1b4c653ce535
  * Commits must be prefixed with the package(s) they modify

 * Commit: ad32b1c18375b1391afe199717cc053e955e653d
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 30fe2431930c5b4f4da619f921132b184c3869c3
  * Commits must be prefixed with the package(s) they modify

 * Commit: 771eccad5cc5d386c34875b7e83e6c3f6ac70787
  * Commits must be prefixed with the package(s) they modify

 * Commit: 1d5e142f2ec8ec12901ee8c24a3fbbeb160a335c
  * Commits must be prefixed with the package(s) they modify

 * Commit: 0bc5a7b11ffb0ccb8f3e7977177ba493b8daa216
  * Commits must be prefixed with the package(s) they modify

 * Commit: ef1868909d1c5acbd173999e74bd1b4c653ce535
  * Commits must be prefixed with the package(s) they modify

 * Commit: e845d777a4e635b0a1604b9056ca64d68464bc91
  * Commits must be prefixed with the package(s) they modify

 * Commit: afd61a2558a812d5e54c64bd54342076a16c662b
  * Commits must be prefixed with the package(s) they modify

 * Commit: 107340e841a4725c73fb747b4bd739fa50cab2f3
  * Commits must be prefixed with the package(s) they modify

 * Commit: 4663d58648a6327f7f22db84a112d0f439c837b1
  * Commits must be prefixed with the package(s) they modify

 * Commit: 6720ae4657e8abec8fb31e73e9ceec2023e3bc79
  * Commits must be prefixed with the package(s) they modify

 * Commit: e8ced953f1615b304cdc86d70342a4e17b515da4
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 30fe2431930c5b4f4da619f921132b184c3869c3
  * Commits must be prefixed with the package(s) they modify

 * Commit: 771eccad5cc5d386c34875b7e83e6c3f6ac70787
  * Commits must be prefixed with the package(s) they modify

 * Commit: 1d5e142f2ec8ec12901ee8c24a3fbbeb160a335c
  * Commits must be prefixed with the package(s) they modify

 * Commit: 0bc5a7b11ffb0ccb8f3e7977177ba493b8daa216
  * Commits must be prefixed with the package(s) they modify

 * Commit: ef1868909d1c5acbd173999e74bd1b4c653ce535
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: d36c66e50899c0c3b8731a8ad365cd97d8b4adff
  * Commits must be prefixed with the package(s) they modify

 * Commit: b8ac0597bf6d37e0fbbfa370bce865d9b742294a
  * Commits must be prefixed with the package(s) they modify

 * Commit: 79357836661075907b1856b0974bf32b49f5f6c6
  * Commits must be prefixed with the package(s) they modify

 * Commit: 0575a1c92307caaf4b28463cc8cb819b52afc46d
  * Commits must be prefixed with the package(s) they modify

 * Commit: 40f2a403756a63d3789e77cabd9158b5fd085aa8
  * Commits must be prefixed with the package(s) they modify

 * Commit: 07864c0d5dd27b9707ec0ec3fa4e69cb50e1ff3c
  * Commits must be prefixed with the package(s) they modify

 * Commit: 313a0d5802c8dfc12b35ff179e31d30735aace03
  * Commits must be prefixed with the package(s) they modify

 * Commit: dcdbedb343c9f37e251cb4ae207ae515b828a9aa
  * Commits must be prefixed with the package(s) they modify

 * Commit: a84c303b2c6e58fd810aa8bda03e99a0cbccc968
  * Commits must be prefixed with the package(s) they modify

 * Commit: b56f30b38d0557ff8f59104c815f4eb659c24a76
  * Commits must be prefixed with the package(s) they modify

 * Commit: 89f5c8cec15ce97664b869024b208d2e26d1d602
  * Commits must be prefixed with the package(s) they modify

 * Commit: 8aca7103c0c1d11701bbcdbdbcd974529b9f1978
  * Commits must be prefixed with the package(s) they modify

 * Commit: 99affe7d30fffae11a07a0f50d2d81487d7311f9
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 5b228372138e3ce7a5faca26524257e0ae296238
  * Commits must be prefixed with the package(s) they modify

 * Commit: b490f7e9b4b7da4b618d59c445995ea03299d056
  * Commits must be prefixed with the package(s) they modify

 * Commit: c64c4d1c96c86ba901198f9b8963798096922b75
  * Commits must be prefixed with the package(s) they modify

 * Commit: 86ea571a7e836732ba94f0d2457619bf8e49fc4e
  * Commits must be prefixed with the package(s) they modify

 * Commit: aa5ed3cacd55f115f3b11222d6585c4382a837f5
  * Commits must be prefixed with the package(s) they modify

 * Commit: 15a0069e08b33f020069260667ba568a21c2b3bb
  * Commits must be prefixed with the package(s) they modify

 * Commit: 882cc66b4c67a8a00da63e5e7e0ce037ec8b3f68
  * Commits must be prefixed with the package(s) they modify

 * Commit: c81525c0587c59228b4215cd6fe14fa445c85cb6
  * Commits must be prefixed with the package(s) they modify

 * Commit: cf7fbeffc80de472239299fe78d7314620c54dbc
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 285b524ac3a600dc64469ec689afd4a1cc85197f
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 0f3776a816f5aaf0d185073e937cf564e4517409
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 746adc3770ce098de187f845557c0ddeb6a823f7
  * Commits must be prefixed with the package(s) they modify

 * Commit: 46f8e96dfce85ccc4e667f708a73c2cdf565ecc6
  * Commits must be prefixed with the package(s) they modify

 * Commit: ab0ffbf36918a97aaaad915acaf1a42a5d1011a4
  * Commits must be prefixed with the package(s) they modify

 * Commit: 0d08f16925823cf658ac0ffb5ff317fb8b8cceda
  * Commits must be prefixed with the package(s) they modify

 * Commit: 351b9589dde9ede339874ff86b358ab79fbe692a
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 746adc3770ce098de187f845557c0ddeb6a823f7
  * Commits must be prefixed with the package(s) they modify

 * Commit: 46f8e96dfce85ccc4e667f708a73c2cdf565ecc6
  * Commits must be prefixed with the package(s) they modify

 * Commit: ab0ffbf36918a97aaaad915acaf1a42a5d1011a4
  * Commits must be prefixed with the package(s) they modify

 * Commit: 0d08f16925823cf658ac0ffb5ff317fb8b8cceda
  * Commits must be prefixed with the package(s) they modify

 * Commit: 351b9589dde9ede339874ff86b358ab79fbe692a
  * Commits must be prefixed with the package(s) they modify

 * Commit: de1003b75c919f1dcde0cd6d465bc17536a5d8dc
  * Commits must be prefixed with the package(s) they modify

 * Commit: ca637c8dda23deea5e1570b3774207dfd8651a60
  * Commits must be prefixed with the package(s) they modify

 * Commit: b22125f5152f297621d68aeb0b412d8f23958c0b
  * Commits must be prefixed with the package(s) they modify

 * Commit: 2356ffb8aacb208f0d8d91e4242f7baac111346a
  * Commits must be prefixed with the package(s) they modify

 * Commit: ccdbdd70e02bca329f355df717b6424aaf79aabf
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 90dd5a974a5ad9c7d9103c67bcd40a93920ba043
  * Commits must be prefixed with the package(s) they modify

 * Commit: 8ec57434d12cf5adebd3932dc7f25f890ad51646
  * Commits must be prefixed with the package(s) they modify

 * Commit: bd2ada798d396b32aa50739572647f38b5833b71
  * Commits must be prefixed with the package(s) they modify

 * Commit: 87a31f664378f2add08f56e1439e7e50305a35d9
  * Commits must be prefixed with the package(s) they modify

 * Commit: 5713ddd2608d0c3610299468b074b92491d4f1b0
  * Commits must be prefixed with the package(s) they modify

 * Commit: 0787b33197656296253527ee9190ed58ca74c6a0
  * Commits must be prefixed with the package(s) they modify

 * Commit: 020f7cf9710283b4d27e5cd4552dc62c4f23587e
  * Commits must be prefixed with the package(s) they modify

 * Commit: 0d17f0f6d04a102cbaceb8020c10ea3ca0d40450
  * Commits must be prefixed with the package(s) they modify

 * Commit: 02161174d995c1f1bab65870cd1a6d4673565524
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by ligi** [comment]
W00t - nice to see this merged - can't wait for 1.7.3 - any chance for a release before DevCon3?

**Comment by karalabe** [comment]
No :) That would be far too dangerous :)

**Comment by ligi** [comment]
Yea - I think you are right - but perhaps I use a snapshot for once ;-) Would really love to see a faster light-client ..
Especially on one Device I have there currently - NXP i.MX6UL - this syncs on rinkeby for days now ..

**Pull request merged**
