### PR TITLE
graphql: remove underscore variable that has no effect.

### PR DESCRIPTION
**Pull request by dbadoy**

### CODE REVIEW

**Comment by karalabe** [comment]
Myeah, you're right, but it's not our code so I'd rather just leave it be and not open up a can of worms with fixing stuff.

**Comment by ray-themedium** [comment]
> Myeah, you're right, but it's not our code so I'd rather just leave it be and not open up a can of worms with fixing stuff.

I see, thanks.
I'll close this PR.

**Comment by dbadoy** [comment]
> Myeah, you're right, but it's not our code so I'd rather just leave it be and not open up a can of worms with fixing stuff.

I see, thanks.
I'll close this PR.

**Comment by holiman** [comment]
Actually, I think the code as it was is better anyway. Some linters complain when you ignore returnvalues, since it's an indication that errors are not being handled. The underscore serves to signal that the returnvalues are _intentionally_ ignored, not just an oversight.

**Comment by dbadoy** [comment]
> Actually, I think the code as it was is better anyway. Some linters complain when you ignore returnvalues, since it's an indication that errors are not being handled. The underscore serves to signal that the returnvalues are _intentionally_ ignored, not just an oversight.

I agree. appreciated !

**Comment by Athayde3586** [comment]
U need to quit STEALLING

**Pull request closed without merging**
