### PR TITLE
accounts/abi/bind: support generating bindings for various arrays

### PR DESCRIPTION
**Pull request by karalabe**
Previously we only supported slices for addresses. This PR fixes it up properly by supporting

 * Slices for `address`, `bool` and `string`
 * Slices for various sized byte arrays
 * Unifies the `int` and `uint` handling code
 * Supports both unbound slices and fixed sized arrays for all types

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Tue Apr 5 15:24:54 UTC 2016_

**Comment by karalabe** [comment]
@zelig @obscuren PTAL

**Comment by zelig** [comment]
This worked, LGTM but your regexps are incredibly dangerously complex wish we could use 
some official solidity type parser definition here
 :1:

**Comment by zelig** [comment]
lol I wrote :1: first but robotally insists :)

**Pull request merged**
