### PR TITLE
Geth 1.4.7

### PR DESCRIPTION
**Pull request by karalabe**

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Tue Jun 14 14:13:58 UTC 2016_

**Comment by GitCop** [comment]
Your commits seem to not adhere to the repository coding standards

 * Commit: 71b577f83953838d79cf78b77ab0d9d671bd5edf
  * Commit subjects should be kept under 80 characters

 * Commit: 39f1d909d185816bade35c7336364fe5e842c7c5
  * Commit subjects should be kept under 80 characters

 * Commit: 0405f728c632b99ad6b755ff68019c6ae7ab0cec
  * Commit subjects should be kept under 80 characters

 * Commit: f7fdfa4eace4f0ab1dd820398efa0f2f44bd1eca
  * Commit subjects should be kept under 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Your commits seem to not adhere to the repository coding standards

 * Commit: 71b577f83953838d79cf78b77ab0d9d671bd5edf
  * Commit subjects should be kept under 80 characters

 * Commit: 39f1d909d185816bade35c7336364fe5e842c7c5
  * Commit subjects should be kept under 80 characters

 * Commit: 0405f728c632b99ad6b755ff68019c6ae7ab0cec
  * Commit subjects should be kept under 80 characters

 * Commit: f7fdfa4eace4f0ab1dd820398efa0f2f44bd1eca
  * Commit subjects should be kept under 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Your commits seem to not adhere to the repository coding standards

 * Commit: 71b577f83953838d79cf78b77ab0d9d671bd5edf
  * Commit subjects should be kept under 80 characters

 * Commit: 39f1d909d185816bade35c7336364fe5e842c7c5
  * Commit subjects should be kept under 80 characters

 * Commit: 0405f728c632b99ad6b755ff68019c6ae7ab0cec
  * Commit subjects should be kept under 80 characters

 * Commit: f7fdfa4eace4f0ab1dd820398efa0f2f44bd1eca
  * Commit subjects should be kept under 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Your commits seem to not adhere to the repository coding standards

 * Commit: 71b577f83953838d79cf78b77ab0d9d671bd5edf
  * Commit subjects should be kept under 80 characters

 * Commit: 39f1d909d185816bade35c7336364fe5e842c7c5
  * Commit subjects should be kept under 80 characters

 * Commit: 0405f728c632b99ad6b755ff68019c6ae7ab0cec
  * Commit subjects should be kept under 80 characters

 * Commit: f7fdfa4eace4f0ab1dd820398efa0f2f44bd1eca
  * Commit subjects should be kept under 80 characters

 * Commit: be29e41334fd831d18fc6acdadeb2e0e31eb9c2a
  * Commit subjects should be kept under 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
