### PR TITLE
whisper, event/filter: mutexes for whisper keys and filter watchers

### PR DESCRIPTION
**Pull request by JoHense**
Using RWMutex to synchronize access to the key map in the Whisper client and to the map of watcher in event filters.

Fixing #2811

### CODE REVIEW

**Comment by obscuren** [comment]
@gluk256 PTAL.

@JoHense please rebase instead of merge. We do not accept PRs that contain merge commits. Remove the merge commit and do a `git rebase ethereum/develop`

**Comment by JoHense** [comment]
Preparing new pull request

**Comment by obscuren** [comment]
There was no need to close it you could have just removed the commit locally and `git push develop --force` :-)

**Comment by JoHense** [comment]
Damn... sorry. I am new to github :-)

**Pull request closed without merging**
