### PR TITLE
eth/catalyst: use circular queue to cache items

### PR DESCRIPTION
**Pull request by hero5512**
use circular queue to avoid copy arrays everytime

### CODE REVIEW

**Comment by jsvisa** [comment]
Could you please add some test cases?

**Comment by hero5512** [comment]
> Could you please add some test cases?

done

**Review by jwasinger — COMMENTED** [review]
This prevents the copying of 9 pointers every time a payload is added.  It's not worth the added complexity in my opinion.

**Comment by hero5512** [comment]
> This prevents the copying of 9 pointers every time a payload is added. It's not worth the added complexity in my opinion.

ooops.... I write a benchmark to test it. It seems that it's slow when the array with small capacity

**Pull request closed without merging**
