### PR TITLE
core/txpool: additional DoS defense measures

### PR DESCRIPTION
**Pull request by dwn1998**
Implemented DoS defense schemes

### CODE REVIEW

**Comment by fjl** [comment]
Please provide some additional context about these defense measures. They sure look interesting, it would be nice to hear whether these were explored in a paper or in another implementation!

**Comment by fjl** [comment]
Thanks for the info! This needs to be reviewed by @karalabe and/or @MariusVanDerWijden.

**Comment by mohammadfarari1360** [comment]
Good

**Comment by holiman** [comment]
Superseded by #26648

**Pull request closed without merging**
