### PR TITLE
core: add BlockChainConfig 

### LINKED ISSUE #20280: Make a core.BlockChainConfig to simplify NewBlockChain
The function arguments to `core.NewBlockChain` got way out of hand. We need a config structure instead.

### PR DESCRIPTION
**Pull request by gideongrinberg**
I've replaced all of the arguments to `core.NewBlockChain` with a `core.BlockChainConfig` struct. Closes #20280.

### CODE REVIEW

**Comment by gideongrinberg** [comment]
It should be ready now.

**Comment by smysmymrik1803** [comment]
core/blockchain.go

**Comment by gideongrinberg** [comment]
I'll fix those in a bit

**Comment by MariusVanDerWijden** [comment]
I don't think `database` and `consensus.Engine` should be in the configs. But we should discuss it in triage

**Comment by fjl** [comment]
go-ethereum core team doesn't have time to evaluate this PR right now. We discussed it a bit, the idea is pretty good.

**Comment by gideongrinberg** [comment]
> go-ethereum core team doesn't have time to evaluate this PR right now. We discussed it a bit, the idea is pretty good.

Ok, thanks.

**Pull request closed without merging**
