### PR TITLE
core, miner: remove PostChainEvents

### PR DESCRIPTION
**Pull request by rjl493456442**
In this PR: 
* get rid of exposing PostEvent function
* make `removed` log sorted by block number
* fire the `newChainHead` event if we inject a canonical block into the chain no matter the entire insertion is successful or not.
* guarantee correct event ordering

Question:

Should we also reemit the `ChainEvent` for reborn blocks?

A notable change is: I remove the event fire go routine in the `reorg` function.
Since our `feed` implementation doesn't support event caching. It means if the event subscriber doesn't receive the event as soon as possible, the event firing can block the entire procedure.
But from another point of view: if we blindly spawn the routines, it can cause the memory leak. 

TODO
- [x] Please merge this PR https://github.com/ethereum/go-ethereum/pull/20310 first

### CODE REVIEW

**Comment by zcheng9** [comment]
@rjl493456442 When you call the `writeBlockWithState` method in `insertChain`, you set the parameter `emitHeadEvent` as false, which means the `ChainHeadEvent` would never been send when insert a batch of blocks.  The only scenario the `ChainHeadEvent` can be sent is when mining(in the result loop). Do you intend to do this? Because in the original code, every time when you call the `insertChain` to insert a batch of blocks, it would eventually post one `ChainHeadEvent` at the end.  Here is the reference code:

```
func (w *worker) resultLoop() {
                        ...
			_, err := w.chain.WriteBlockWithState(block, receipts, logs, task.state, true)
                        ...
        }
```
```
func (bc *BlockChain) insertChain(chain types.Blocks, verifySeals bool) {
                ...
		substart = time.Now()
		status, err := bc.writeBlockWithState(block, receipts, logs, statedb, false)
               ...
	}

```

**Comment by rjl493456442** [comment]
@zcheng9 An accumulated `ChainHeadEvent` will be fired when we actually make any progress during the chain insertion. Checkout the code here https://github.com/ethereum/go-ethereum/pull/19396/files#diff-30184e52dfee0fbd0ba21f92638b2ec1R1221

**Comment by zcheng9** [comment]
I see ,sry I miss this defer func, didn't see you move it to to top.

**Comment by zcheng9** [comment]
One more quick questions: in the mining result loop,  when call `WriteBlockWithState`, it passes one single block , which means no matter `emitchainhead` is true or false ,it will emit this block as a new head. Is there any specific reason to keep this check?

**Comment by rjl493456442** [comment]
@zcheng9 In theory, miners can submit an uncle block and this block will also be included in the blockchain with paying uncle block fee to the miner.

**Comment by fjl** [comment]
rebased on master

**Pull request merged**
