### PR TITLE
cmd/geth: inspect snapshot dangling storage

### PR DESCRIPTION
**Pull request by holiman**
While investigating a failure during post-merge goerli shadowfork, I found that there was 'dangling' snap storage data. 

Our `verify-state` iterates the snapshot data by iterating the snapshot accounts, and regenerating the trie. This method was unable to discover the flaw, since the account did not exist (only the storage data did), thus reported that the verification passed. 

This PR adds an additional checker. It iterates the `o<32byte account key><32 byte storage key>` items in the db, and verifies that for each storage, there is a corresponding account. 

Example of running it 
```
$ geth --datadir ./eth1data/geth snapshot check-dangling-storage
INFO [04-05|09:28:55.764] Maximum peer count                       ETH=50 LES=0 total=50
INFO [04-05|09:28:55.765] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [04-05|09:28:55.765] Using deprecated resource file /home/user/tmp/goerlishadowfork/eth1data/geth/nodekey, please move this file to the 'geth' subdirectory of datadir. 
INFO [04-05|09:28:55.765] Set global gas cap                       cap=50,000,000
INFO [04-05|09:28:55.766] Allocated cache and file handles         database=/home/user/tmp/goerlishadowfork/eth1data/geth/chaindata cache=512.00MiB handles=262,144 readonly=true
INFO [04-05|09:28:55.877] Opened ancient database                  database=/home/user/tmp/goerlishadowfork/eth1data/geth/chaindata/ancient readonly=true
INFO [04-05|09:29:05.176] Iterating snap storage                   at=0x1c488160412c5dc4086dbc93bd94b2bdc3346a37f7152282c5cdf524a8f01f6f elapsed=9.220s
INFO [04-05|09:29:13.176] Iterating snap storage                   at=0x3bf33ad4ac0beab534e8dc18ea36ba33acd878a85500378f55490a9d065a9e56 elapsed=17.220s
INFO [04-05|09:29:21.176] Iterating snap storage                   at=0x51c7d59d773a0121fb9c5a21f560b7e6403a7c1d2568758612b4956b30471935 elapsed=25.220s
INFO [04-05|09:29:29.244] Iterating snap storage                   at=0x6e72233b022b2447b4364d0dcdba7cbcfba390c261c755fec9fd46c9b584d80d elapsed=33.289s
ERROR[04-05|09:29:32.162] Dangling storage - missing account       account=0x725beb54c9fc8debc2b0c22865cc757ff911fd56f6068e53aeb935794e6c45c7 storagekey=0x6f725beb54c9fc8debc2b0c22865cc757ff911fd56f6068e53aeb935794e6c45c7b10e2d527612073b26eecdfd717e6a320cf44b4afac2b0732d9fcbe2b7fa0cf6
INFO [04-05|09:29:37.321] Iterating snap storage                   at=0x88365ceff946a5fdc5a5eb95cd68852d259f8fcfcd6bf428d9ebb3eebd47e51e elapsed=41.365s
INFO [04-05|09:29:45.321] Iterating snap storage                   at=0xa1f9cecf5fc9f11e303628245d659e8bc3d35bcde70bfe083cd541d95a5bfe2f elapsed=49.365s
INFO [04-05|09:29:53.321] Iterating snap storage                   at=0xb15c80a7a789fb5b6b4695c7ad7f7ee7a418f8f76cf1ea13035a686195c244bd elapsed=57.365s
INFO [04-05|09:30:01.321] Iterating snap storage                   at=0xcc03d7e25ad8ee1a2267ad6757644c14269ef24bf9f664a43acd1818ea89ba11 elapsed=1m5.366s
INFO [04-05|09:30:09.446] Iterating snap storage                   at=0xe581ad9a486d6504024c0ed40087a373f7f38a1d951964e177c5ea088d81d135 elapsed=1m13.490s
INFO [04-05|09:30:16.678] Verified the snapshot storage            root=faa279..7c9376 time=1m20.723s err=nil

```

### CODE REVIEW

**Comment by holiman** [comment]
Triage discussion: look into integrating this with `verify-state`, so both checks are done simultaneously.

**Comment by karalabe** [comment]
I think the functionality is very good, but I'd integrate it with `verify-state` (?) so we get a fuller verification by default vs having to remember to run 2 passes to catch all errors.

**Comment by holiman** [comment]
I've now changed it -- but I didn't do a 'deep' integration, for two reasons. 

1. The `verify-state` takes ~15-20m on goerli, and hours on mainet, whereas verify snapshot storage takes ~1m on goerli. So it's a much smaller check, which can be nice to run individually without also doing the full verify-state. 
2. The `verify-state` is implemented pretty deep inside the snaptree, with several worker go-routines and closures. Adding support for also iterating the database via a different iterator makes it even more complex, as opposed to just adding an extra 10% work at the end.

**Review by rjl493456442 — APPROVED** [review]

**Comment by rjl493456442** [comment]
Apologize for approving. I just found a bug inside.

In `checkDangling` function, we iterate the storage out from the "disk layer" but we check the presence of the account on the "different" snapshot layer(might be some diff layers). 

So if the account is destructed between disk layer and this diff layer, we will incorrectly report dangling messages.

**Comment by holiman** [comment]
Oh, good point.Also we could/should soup up the journal (serialized difflayers) and check them separately.

**Pull request merged**
