### PR TITLE
les, light, eth/filter: implement transformed bloom bitmap based quick log search for light client

### PR DESCRIPTION
**Pull request by zsfelfoldi**
This PR optimizes log searching by creating a data structure (BloomBits) that makes it cheaper to retrieve bloom filter data relevant to a specific filter either from the database or through the LES protocol. When searching in a long section of the block history, we are checking three specific bits of each bloom filter per address/topic. In order to do that, currently we read/retrieve a cca. 500 byte block header for each block. The implemented structure optimizes this by a "bitwise 90 degree rotation" of the bloom filters. Blocks are grouped into sections (SectionSize is 4096 blocks at the moment), BloomBits[bitIdx][sectionIdx] is a 4096 bit (512 byte) long bit vector that contains a single bit of each bloom filter from the block range [sectionIdx*SectionSize ... (sectionIdx+1)*SectionSize-1]. (Since bloom filters are usually sparse, a simple data compression makes this structure even more efficient, especially for ODR retrieval.) By reading and binary AND-ing three BloomBits sections, we can filter for an address/topic in 4096 blocks at once ("1" bits in the binary AND result mean bloom matches).
A new request/reply pair is added to LES (GetBloomBits/BloomBits), which retrieve/serve Merkle proofs of BloomBits sections, which are added to the CHT trie. Headers downloaded after the CHT checkpoint are processed by the client, the recent BloomBits (along with the recent headers) are always available in the database.
This search algorithm is currently only used by the light client but it could be considered for full clients too. If the required BloomBits data is available locally, an address search in the entire 3M block history takes only a fraction of a second (around 0.1-0.2s). A second level filter (MIP mapping) could be used with this approach too, but it is not a high priority at the moment because of its high efficiency in its current single-level form. This approach also saves a lot of database writes compared to the current MIP map implementation.

Note: the PR is under heavy development at the moment, hopefully it will be functional again later this week.

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: e5ac2dc67e8419180907f0afc13dfe7c120061d9
  * Commit subjects should be kept under 100 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: e5ac2dc67e8419180907f0afc13dfe7c120061d9
  * Commit subjects should be kept under 100 characters

 * Commit: 38d000331f8f5e7f9456ab14f0952337eba24a16
  * Commits must be prefixed with the package(s) they modify

 * Commit: 990d23f2b9c30ed5f25540704d04ee8d3abd4f94
  * Commits must be prefixed with the package(s) they modify

 * Commit: d6862a71eebbd28d3cef8611fb5425677dcf9558
  * Commits must be prefixed with the package(s) they modify

 * Commit: 7a89e2174d8e0519c6def931d702c14ea0dd1d1e
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: e5ac2dc67e8419180907f0afc13dfe7c120061d9
  * Commit subjects should be kept under 100 characters

 * Commit: 38d000331f8f5e7f9456ab14f0952337eba24a16
  * Commits must be prefixed with the package(s) they modify

 * Commit: 990d23f2b9c30ed5f25540704d04ee8d3abd4f94
  * Commits must be prefixed with the package(s) they modify

 * Commit: d6862a71eebbd28d3cef8611fb5425677dcf9558
  * Commits must be prefixed with the package(s) they modify

 * Commit: 7a89e2174d8e0519c6def931d702c14ea0dd1d1e
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by Arachnid** [comment]
Could you leave a brief description of how this works in the PR description?

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: e5ac2dc67e8419180907f0afc13dfe7c120061d9
  * Commit subjects should be kept under 100 characters

 * Commit: 38d000331f8f5e7f9456ab14f0952337eba24a16
  * Commits must be prefixed with the package(s) they modify

 * Commit: 990d23f2b9c30ed5f25540704d04ee8d3abd4f94
  * Commits must be prefixed with the package(s) they modify

 * Commit: d6862a71eebbd28d3cef8611fb5425677dcf9558
  * Commits must be prefixed with the package(s) they modify

 * Commit: 7a89e2174d8e0519c6def931d702c14ea0dd1d1e
  * Commits must be prefixed with the package(s) they modify

 * Commit: 4b7aa57fed39c69cf5ae8c02d370179e54a9aa5b
  * Commits must be prefixed with the package(s) they modify

 * Commit: f1f7f65c1ac72dc0dadbbf39c81ecdff5757ed19
  * Commits must be prefixed with the package(s) they modify

 * Commit: b2340b7a7913693c4f3319a373cfb3f47e5a8b07
  * Commits must be prefixed with the package(s) they modify

 * Commit: a05377d0d509055ef1befe64c6aa4ec0255c9315
  * Commits must be prefixed with the package(s) they modify

 * Commit: 40cc19a33e0f021c0d9873a6791de7eb2797bd99
  * Commits must be prefixed with the package(s) they modify

 * Commit: 48ae0ed6a04c7e1f3fd78320526066b02531fca5
  * Commits must be prefixed with the package(s) they modify

 * Commit: 01fa0d72e1f13f9b730f1a87193bca2b1c420eb1
  * Commits must be prefixed with the package(s) they modify

 * Commit: 54571478ebfd960524329ea974c05cc233f154a1
  * Commits must be prefixed with the package(s) they modify

 * Commit: 347bfac7a4cc03a08657370e66cb16ec7139ea03
  * Commits must be prefixed with the package(s) they modify

 * Commit: 72bc5545331cd8536dbbac18b5ed1f5eee53c121
  * Commits must be prefixed with the package(s) they modify

 * Commit: 8b34a609f425ab33da7dc9efe56db50184a345bc
  * Commits must be prefixed with the package(s) they modify

 * Commit: d79502942bbc36ec42b69e24363858156456feef
  * Commits must be prefixed with the package(s) they modify

 * Commit: 82d93a28f998ff301c3f8f5d9d49df946bf76e9c
  * Commits must be prefixed with the package(s) they modify

 * Commit: 42613c80ed8f35651ee9712e6e492821958b6392
  * Commits must be prefixed with the package(s) they modify

 * Commit: f9bd9d8cb1c6a03936cec083ec36aedf2329be0e
  * Commits must be prefixed with the package(s) they modify

 * Commit: 0576be2027a4a5d84ab058558fc662053fff44a9
  * Commits must be prefixed with the package(s) they modify

 * Commit: c72d5a0438217ee9f21a147ab7c6a56ff48c9d7e
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: e5ac2dc67e8419180907f0afc13dfe7c120061d9
  * Commit subjects should be kept under 100 characters

 * Commit: 38d000331f8f5e7f9456ab14f0952337eba24a16
  * Commits must be prefixed with the package(s) they modify

 * Commit: 990d23f2b9c30ed5f25540704d04ee8d3abd4f94
  * Commits must be prefixed with the package(s) they modify

 * Commit: d6862a71eebbd28d3cef8611fb5425677dcf9558
  * Commits must be prefixed with the package(s) they modify

 * Commit: 7a89e2174d8e0519c6def931d702c14ea0dd1d1e
  * Commits must be prefixed with the package(s) they modify

 * Commit: 4b7aa57fed39c69cf5ae8c02d370179e54a9aa5b
  * Commits must be prefixed with the package(s) they modify

 * Commit: f1f7f65c1ac72dc0dadbbf39c81ecdff5757ed19
  * Commits must be prefixed with the package(s) they modify

 * Commit: b2340b7a7913693c4f3319a373cfb3f47e5a8b07
  * Commits must be prefixed with the package(s) they modify

 * Commit: a05377d0d509055ef1befe64c6aa4ec0255c9315
  * Commits must be prefixed with the package(s) they modify

 * Commit: 40cc19a33e0f021c0d9873a6791de7eb2797bd99
  * Commits must be prefixed with the package(s) they modify

 * Commit: 48ae0ed6a04c7e1f3fd78320526066b02531fca5
  * Commits must be prefixed with the package(s) they modify

 * Commit: 01fa0d72e1f13f9b730f1a87193bca2b1c420eb1
  * Commits must be prefixed with the package(s) they modify

 * Commit: 54571478ebfd960524329ea974c05cc233f154a1
  * Commits must be prefixed with the package(s) they modify

 * Commit: 347bfac7a4cc03a08657370e66cb16ec7139ea03
  * Commits must be prefixed with the package(s) they modify

 * Commit: 72bc5545331cd8536dbbac18b5ed1f5eee53c121
  * Commits must be prefixed with the package(s) they modify

 * Commit: 8b34a609f425ab33da7dc9efe56db50184a345bc
  * Commits must be prefixed with the package(s) they modify

 * Commit: d79502942bbc36ec42b69e24363858156456feef
  * Commits must be prefixed with the package(s) they modify

 * Commit: 82d93a28f998ff301c3f8f5d9d49df946bf76e9c
  * Commits must be prefixed with the package(s) they modify

 * Commit: 42613c80ed8f35651ee9712e6e492821958b6392
  * Commits must be prefixed with the package(s) they modify

 * Commit: f9bd9d8cb1c6a03936cec083ec36aedf2329be0e
  * Commits must be prefixed with the package(s) they modify

 * Commit: 0576be2027a4a5d84ab058558fc662053fff44a9
  * Commits must be prefixed with the package(s) they modify

 * Commit: 67eb0cc07ab9404ab0c097c6d9187029ac8f92e8
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: e5ac2dc67e8419180907f0afc13dfe7c120061d9
  * Commit subjects should be kept under 100 characters

 * Commit: 38d000331f8f5e7f9456ab14f0952337eba24a16
  * Commits must be prefixed with the package(s) they modify

 * Commit: 990d23f2b9c30ed5f25540704d04ee8d3abd4f94
  * Commits must be prefixed with the package(s) they modify

 * Commit: d6862a71eebbd28d3cef8611fb5425677dcf9558
  * Commits must be prefixed with the package(s) they modify

 * Commit: 7a89e2174d8e0519c6def931d702c14ea0dd1d1e
  * Commits must be prefixed with the package(s) they modify

 * Commit: 4b7aa57fed39c69cf5ae8c02d370179e54a9aa5b
  * Commits must be prefixed with the package(s) they modify

 * Commit: f1f7f65c1ac72dc0dadbbf39c81ecdff5757ed19
  * Commits must be prefixed with the package(s) they modify

 * Commit: b2340b7a7913693c4f3319a373cfb3f47e5a8b07
  * Commits must be prefixed with the package(s) they modify

 * Commit: a05377d0d509055ef1befe64c6aa4ec0255c9315
  * Commits must be prefixed with the package(s) they modify

 * Commit: 40cc19a33e0f021c0d9873a6791de7eb2797bd99
  * Commits must be prefixed with the package(s) they modify

 * Commit: 48ae0ed6a04c7e1f3fd78320526066b02531fca5
  * Commits must be prefixed with the package(s) they modify

 * Commit: 01fa0d72e1f13f9b730f1a87193bca2b1c420eb1
  * Commits must be prefixed with the package(s) they modify

 * Commit: 54571478ebfd960524329ea974c05cc233f154a1
  * Commits must be prefixed with the package(s) they modify

 * Commit: 347bfac7a4cc03a08657370e66cb16ec7139ea03
  * Commits must be prefixed with the package(s) they modify

 * Commit: 72bc5545331cd8536dbbac18b5ed1f5eee53c121
  * Commits must be prefixed with the package(s) they modify

 * Commit: 8b34a609f425ab33da7dc9efe56db50184a345bc
  * Commits must be prefixed with the package(s) they modify

 * Commit: d79502942bbc36ec42b69e24363858156456feef
  * Commits must be prefixed with the package(s) they modify

 * Commit: 82d93a28f998ff301c3f8f5d9d49df946bf76e9c
  * Commits must be prefixed with the package(s) they modify

 * Commit: 42613c80ed8f35651ee9712e6e492821958b6392
  * Commits must be prefixed with the package(s) they modify

 * Commit: f9bd9d8cb1c6a03936cec083ec36aedf2329be0e
  * Commits must be prefixed with the package(s) they modify

 * Commit: 0576be2027a4a5d84ab058558fc662053fff44a9
  * Commits must be prefixed with the package(s) they modify

 * Commit: 67eb0cc07ab9404ab0c097c6d9187029ac8f92e8
  * Commits must be prefixed with the package(s) they modify

 * Commit: 5ba4a42024789dc1f6d745244b7ca4604fa08f4c
  * Commits must be prefixed with the package(s) they modify

 * Commit: 019bb653d7edfa59ad98e7f9424408f8d6cbaadf
  * Commits must be prefixed with the package(s) they modify

 * Commit: b98033786335347e29c590125933951f71499de4
  * Commits must be prefixed with the package(s) they modify

 * Commit: 3868069c3930c72f26c96568720bdb5f4f861f00
  * Commits must be prefixed with the package(s) they modify

 * Commit: 59a6aba438835556388c03ede2892ba290a4eb75
  * Commits must be prefixed with the package(s) they modify

 * Commit: 8d6ab026f8e82dca0e8aab9feaaa8ccff4bee91d
  * Commits must be prefixed with the package(s) they modify

 * Commit: 761577a7ae8f550d86e5daa88413de2e4da0054f
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Pull request closed without merging**
