### PR TITLE
p2p: reject enode with unspecified ip address [::] or 0.0.0.0

### PR DESCRIPTION
**Pull request by YaoZengzeng**
fixes issue #17522

### CODE REVIEW

**Comment by YaoZengzeng** [comment]
@karalabe PTAL

**Comment by fjl** [comment]
My change is in now, sorry for the long wait.

**Comment by YaoZengzeng** [comment]
@fjl conflict was resolved

**Comment by fjl** [comment]
Thanks. Unfortunately this still seems to break swarm. We can just keep this PR open, I'll merge it when swarm is ready for it.

**Comment by fjl** [comment]
We have decided to drop this change after all. See https://github.com/ethereum/go-ethereum/issues/17522#issuecomment-442451228 for why.

**Pull request closed without merging**
