### PR TITLE
support for user agents

### LINKED ISSUE #1631: Timed unlock is not working. Parameters are not being passed through.
Hi.

Timed unlocks aren't working. I looked through the code & it seems it is not checking for the parameter and just passes through Duration as '-1'.

https://github.com/ethereum/go-ethereum/blob/master/rpc/api/personal_args.go

```
func (args *UnlockAccountArgs) UnmarshalJSON(b []byte) (err error) {
	var obj []interface{}
	if err := json.Unmarshal(b, &obj); err != nil {
		return shared.NewDecodeParamError(err.Error())
	}

	args.Duration = -1

	if len(obj) < 2 {
		return shared.NewInsufficientParamsError(len(obj), 2)
	}

	if addrstr, ok := obj[0].(string); ok {
		args.Address = addrstr
	} else {
		return shared.NewInvalidTypeError("address", "not a string")
	}

	if passphrasestr, ok := obj[1].(string); ok {
		args.Passphrase = passphrasestr
	} else {
		return shared.NewInvalidTypeError("passphrase", "not a string")
	}

	return nil
}
```

The fix seems simple and would've submitted a fix, but I'm not too versed in Go, to venture attempting this. :)

### PR DESCRIPTION
**Pull request by bas-vk**
This PR adds support for user agents. A user agent is a program that can interact with the user. When geth needs user input it can ask an agent to query the user and act on the response. These agents can be integrated in the environment of the user to provide the best user experience as possible. Currently the console (console and attach) acts as such an agent.

With this PR the user doesn't have to provide the password anymore for the `personal.unlockAccount` method. It will also ask the user for a password for the sendTransaction when the from account is locked. It is backwards compatible, it won't enable the user agent logic by default.

Future steps:
- implement this correct in the redesigned RPC module
- a GUI agent will be integrated into geth which can communicate with the user through windows. Or a user can write a custom agent
- transaction confirmation

It also fixes #1631.

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Mon Aug 10 12:00:16 UTC 2015_

**Comment by Gustav-Simonsson** [comment]
:+1:

**Comment by maran** [comment]
Two things:

1. The name "User agent" confused me at first because it reminds me too much of the [Browser User Agents](https://en.wikipedia.org/wiki/User_agent). Is anybody else bothered by this?

2. I am not completely sure what this PR produces. You mention "With this PR the user doesn't have to provide the password anymore for the personal.unlockAccount method." but I'm guessing the account has to be unlocked somehow? I guess what I'm asking is what steps can I take to test this PR is working as expected?

**Comment by tgerring** [comment]
Agree with @maran on both his points

**Comment by fjl** [comment]
> I am not completely sure what this PR produces.

This PR allows an attached `geth console` to unlock an account interactively.
You can test it by doing sendTransaction without unlocking the account first.

**Comment by maran** [comment]
I can confirm that using `sendTransaction` from a console now interactively asks to unlock the account. Unlocking interactively from the RPC is outside the scope of this PR?

**Comment by bas-vk** [comment]
Yes, for now that is out of scope. This allows users to unlock their accounts in a password prompt instead of heaving it to type it plain text in the console. And als fjl mentioned, you don't have to unlock the account before you send a transaction, it will now ask the user to provide it when necessary. Of if you manually want to unlock an account just do `personal.unlockAccount(your-acc)`, it will than ask for a password.

When we start redesigning the RPC layer next week to coop with all the new requirements/insights this needs to be redesigned. Part of that discussion is how user interaction should be done over the different RPC interfaces.

**Comment by maran** [comment]
Awesome, then it's working as expected. The code is a bit to hard for me to comment on so I will leave others to do that.

I do stand behind my original point that I feel "User agents" is too confusing. I rather see something like "User broker", "User delegate" or something along those lines.

**Comment by obscuren** [comment]
:+1: LGTM

**Pull request merged**
