### PR TITLE
internal/ethapi: add tests for transaction types JSON marshal/unmarshal

### PR DESCRIPTION
**Pull request by ajsutton**
Checks that Transaction.MarshalJSON and newRPCTransaction JSON output can be parsed by Transaction.UnmarshalJSON

### CODE REVIEW

**Comment by ajsutton** [comment]
The duplication of the `allTransactionTypes` helper function is rather unfortunate. If there's a good place to put a shared version of that I'm happy to move it - just point me at the right place. :)

**Review by holiman — APPROVED** [review]
LGTM

**Comment by holiman** [comment]
I refactored it a bit -- now it's only in `internal/ethapi`, where it can perform both tests. Semantically, that's a bit odd, since arguably the 'types' test should be done in 'types' and not a satellite package. I'd argue that we get the same coverage doing it like this, but less clutter and copied code.

**Comment by ajsutton** [comment]
Yeah that makes sense.  Avoiding the duplication is a good tradeoff for the tests being in the "wrong" package. Looks like the windows build failed `TestSkeletonSyncRetrievals` which I'm guessing in flaky.

**Pull request merged**
