### PR TITLE
all: use big.Sign to compare with zero

### PR DESCRIPTION
**Pull request by AaronChen0**

### CODE REVIEW

**Review by MariusVanDerWijden — APPROVED** [review]
SGTM, the only real change that might have an impact on allocations is the core/evm.go change, everything else is either called once per run or never called in production code.
The benefit is very minimal though

**Review by holiman — APPROVED** [review]
LGTM

**Comment by holiman** [comment]
This doesn't compile, some stray imports left behind

**Comment by AaronChen0** [comment]
@holiman fixed. Thank you.

**Pull request merged**
