### PR TITLE
README.md: update formatting

### PR DESCRIPTION
**Pull request by giulio92**
This PR will improve readme.md formatting by:

1. Adding syntax highlighting to all code blocks
2. Aligning the text up to 80 column guideline (before it was following different guidelines, sometime 80, sometime 90, etc.)
3. Formatting example `JSON`s

### CODE REVIEW

**Comment by giulio92** [comment]
How is it possible that AppVeyor fails if this PR only changes the `Readme.md` file?

**Comment by holiman** [comment]
Re appveyor, it's very flaky and fails most of the time

**Comment by giulio92** [comment]
Oh ok thanks! How can I run AppVeyor again? Do I need to `force-push` the changes again?

**Comment by holiman** [comment]
Nah, it's nothing to worry about

**Comment by giulio92** [comment]
Any update on this?

**Pull request merged**
