### PR TITLE
trie: add Commit-sequence tests for stacktrie commit

### PR DESCRIPTION
**Pull request by holiman**
We recently merged the stacktrie, to hash elements in a trie in a more memory friendly manner. The stacktrie has support for Commit, shoving nodes into a database, which we are currently not using. 
However, we didn't have any good tests for commit-sequences, until I added them in https://github.com/ethereum/go-ethereum/pull/21351 . This PR extends the commit-sequence tests to also cover the stacktrie.

### CODE REVIEW

**Review by gballet — COMMENTED** [review]
Couple nitpicks

**Comment by holiman** [comment]
Half of the elems are between 1 and 32 bytes already

**Comment by gballet** [comment]
> Half of the elems are between 1 and 32 bytes already

right, my bad, 32 is the max size

**Review by gballet — APPROVED** [review]
no more objections, your honor. When I've recovered from my data loss, I'll test if the `CopyBytes` is really necessary. No need to hold the merge for this, though.

**Comment by holiman** [comment]
> I'll test if the CopyBytes is really necessary

So, _two_ copybytes is definitely unnecessary, obviously, because nothing else touches the data if we copy it once and then sends the original to the second trie. I thought it would be prudent to copy it twice anyway, to signal that "hey the trie takes ownership of this", in case the test is ever extended. 
Now, if you're saying that the stacktrie internally copies the data, then you should add something like : 
```
st.TryUpdate( data, val)
crand.Read(data) // intentionally corrupt the data 
```
... I think the code above will fail, because I don't think stacktrie copies the data.

**Pull request merged**
