### PR TITLE
rpc: deprecate Client.ShhSubscribe

### PR DESCRIPTION
**Pull request by gballet**
It never worked, whisper uses polling.

### CODE REVIEW

**Comment by fjl** [comment]
We can't remove this method because it has been around for quite a while and I don't want to break the API.
However, we can mark it deprecated. To do this, add a comment like

```
// ShhSubscribe registers a subscripion under the "shh" namespace.
// Deprecated: use Subscribe(ctx, "shh", ...) instead.
```

**Comment by gballet** [comment]
@fjl it's not going to break anything, this function never worked: whisper didn't use the subscription api.

**Comment by fjl** [comment]
It turns out this method is actually used in package shhclient: https://github.com/ethereum/whisper/blob/master/shhclient/client.go#L171

**Comment by gballet** [comment]
and yet, it never worked

**Pull request merged**
