### PR TITLE
signer: remove extra data verification from message eip712 parsing

### PR DESCRIPTION
**Pull request by trevoraron**
This PR removes a verification from EIP712 parsing lib that JS libs don't perform

The reasoning for this is that Opensea's seaport protocol isn't compatible with go-ethereum's eip712 message parsing, because it includes an extra field not specified in type parsing when users attempt to list an item for sale. See the following example:

```
{
	"types": {
		"EIP712Domain": [
			{
				"name": "name",
				"type": "string"
			},
			{
				"name": "version",
				"type": "string"
			},
			{
				"name": "chainId",
				"type": "uint256"
			},
			{
				"name": "verifyingContract",
				"type": "address"
			}
		],
		"OrderComponents": [
			{
				"name": "offerer",
				"type": "address"
			},
			{
				"name": "zone",
				"type": "address"
			},
			{
				"name": "offer",
				"type": "OfferItem[]"
			},
			{
				"name": "consideration",
				"type": "ConsiderationItem[]"
			},
			{
				"name": "orderType",
				"type": "uint8"
			},
			{
				"name": "startTime",
				"type": "uint256"
			},
			{
				"name": "endTime",
				"type": "uint256"
			},
			{
				"name": "zoneHash",
				"type": "bytes32"
			},
			{
				"name": "salt",
				"type": "uint256"
			},
			{
				"name": "conduitKey",
				"type": "bytes32"
			},
			{
				"name": "counter",
				"type": "uint256"
			}
		],
		"OfferItem": [
			{
				"name": "itemType",
				"type": "uint8"
			},
			{
				"name": "token",
				"type": "address"
			},
			{
				"name": "identifierOrCriteria",
				"type": "uint256"
			},
			{
				"name": "startAmount",
				"type": "uint256"
			},
			{
				"name": "endAmount",
				"type": "uint256"
			}
		],
		"ConsiderationItem": [
			{
				"name": "itemType",
				"type": "uint8"
			},
			{
				"name": "token",
				"type": "address"
			},
			{
				"name": "identifierOrCriteria",
				"type": "uint256"
			},
			{
				"name": "startAmount",
				"type": "uint256"
			},
			{
				"name": "endAmount",
				"type": "uint256"
			},
			{
				"name": "recipient",
				"type": "address"
			}
		]
	},
	"primaryType": "OrderComponents",
	"domain": {
		"name": "Seaport",
		"version": "1.1",
		"chainId": "1",
		"verifyingContract": "0x00000000006c3852cbEf3e08E8dF289169EdE581"
	},
	"message": {
		"offerer": "0x20cBC8bccF97d216A301961bab28e05F0A1Ece28",
		"offer": [
			{
				"itemType": "2",
				"token": "0x5bdF47c6691eDF5D2E5F7A156324d88e1478FCa6",
				"identifierOrCriteria": "6585",
				"startAmount": "1",
				"endAmount": "1"
			}
		],
		"consideration": [
			{
				"itemType": "0",
				"token": "0x0000000000000000000000000000000000000000",
				"identifierOrCriteria": "0",
				"startAmount": "90600000000000000",
				"endAmount": "90600000000000000",
				"recipient": "0x20cBC8bccF97d216A301961bab28e05F0A1Ece28"
			},
			{
				"itemType": "0",
				"token": "0x0000000000000000000000000000000000000000",
				"identifierOrCriteria": "0",
				"startAmount": "2500000000000000",
				"endAmount": "2500000000000000",
				"recipient": "0x8De9C5A032463C561423387a9648c5C7BCC5BC90"
			},
			{
				"itemType": "0",
				"token": "0x0000000000000000000000000000000000000000",
				"identifierOrCriteria": "0",
				"startAmount": "6900000000000000",
				"endAmount": "6900000000000000",
				"recipient": "0xCC8aE29e05d22169e2246B609E36Cae291a45887"
			}
		],
		"startTime": "1657553054",
		"endTime": "1660231454",
		"orderType": "2",
		"zone": "0x004C00500000aD104D7DBd00e3ae0A5C00560C00",
		"zoneHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
		"salt": "64159753770275801",
		"conduitKey": "0x0000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f0000",
		"totalOriginalConsiderationItems": "3",
		"counter": "0"
	}
}
```

The field `totalOriginalConsiderationItems` is added, but it isn't specified in `OrderComponents`

The current behavior in js libraries is to just ignore extra fields. This PR should do the same

### CODE REVIEW

**Comment by holiman** [comment]
> The current behavior in js libraries is to just ignore extra fields. This PR should do the same

I'm not sure about this. IIRC, that field will be displayed to the user, when asked "Do you want to sign this?". 
In that step, I don't want to display anything which is outside the scope of what is being signed, i.e:  extra data fields. Such fields can be used for spoofing. 

So, if we ignore it, we should ignore it _totally_, meaning that it is not displayed either. What is the behaviour of this PR?

**Comment by trevoraron** [comment]
hey @holiman thanks for taking a look at this :)

The behavior of this will make it so that user see's the field included, but because it is not specified in the object definition the value will not be encoded and included in the hash that is signed. 

I see what you mean on this being confusing, all though this seems to be how Metamask's EIP712 lib operates. The purpose of this PR is to make this consistent, just because some popular dapps (Opensea) don't seem to work with the go-ethereum libs but do with js libs so it impacts functionality of go-eth based wallets

**Comment by holiman** [comment]
> I see what you mean on this being confusing, all though this seems to be how Metamask's EIP712 lib operates. 

In my opinion, this is _wrong_ and potentially dangerous behaviour. It makes things ambiguous, and goes against "You See What You Sign" (since some of the things you see are not signed).   

> don't seem to work with the go-ethereum libs but do with js libs so it impacts functionality of go-eth based wallets

This makes it complicated. On the one hand, I don't want to compromise on security. On the other hand, I don't want to force people away to a less secure solution. I'm very torn. 

cc @fjl any opinion?

**Comment by holiman** [comment]
> The behavior of this will make it so that user see's the field included, but because it is not specified in the object definition the value will not be encoded and included in the hash that is signed.

No. If we show it to the user, it must be part of the signed data. 
If you want to not have it part of the signed data, it must be stripped from the displayed data too.

**Comment by fjl** [comment]
I agree with @holiman. We need to modify the signer code to remove message fields which are not given by the type.

**Comment by fjl** [comment]
What we mean is: at the moment, your PR removes the check that no extra data is present. We want it to be modified so that the extra data is removed from the input, and thus also not displayed to the user in confirmation prompts.

**Comment by holiman** [comment]
Closing this, since it does not fix a bug, but only removes an explicit check that is there to enforce "what you see is what you sign".
Feel free to open another PR to address the problem the other way round, so that we maintain "what you see is what you sign" by hiding/removing anything that is not part of what is signed.

**Pull request closed without merging**
