### PR TITLE
xeth: fixed nil pointer of filter retrieval

### LINKED ISSUE #1665: Geth crashed on filter (creation?)
While using the wallet this just happened:

https://gist.github.com/frozeman/d5fcabe62e13da081e86

I assume the wallet wanted to create new filters, or where polling filters.

### PR DESCRIPTION
**Pull request by obscuren**
This fix addresses an issue with filters that were (possibly) not yet
added to the filter queues but were expected. I've added additional nil
checks making sure it doesn't crash and swapped the installation of the
filter around so it's installed before use.

Closes #1665

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Fri Sep 25 11:58:02 UTC 2015_

**Comment by Gustav-Simonsson** [comment]
:+1:

**Comment by bas-vk** [comment]
:+1:

**Comment by karalabe** [comment]
The Linux build bot seemed to have timed out on a test. Are we sure this is unrelated to this PR?

**Comment by obscuren** [comment]
@karalabe Has nothing to do with the changes

**Pull request merged**
