### PR TITLE
Create alphacoin

### PR DESCRIPTION
**Pull request by spinox85**
hello,i need help for my first step in to the programing with new cryptocurrency for next opening now open free lab for people...not genius :-))))))
io non conosco capisco nulla d'informatica....

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: c73f0c925f72ec26e93d5211cb0144a6dbcedd44
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by ligi** [comment]
Trolling? also https://github.com/ethereum/go-ethereum/issues/16311
please do something productive with your time!

**Comment by Ruethairat** [comment]
# TREZOR 
SUBSYSTEM == "usb" ,  ATTR { idVendor } == "534c" ,  ATTR { idProduct } == "0001" ,  MODE = "0660" ,  GROUP = "plugdev" ,  TAG + = "uaccess" ,  TAG + = "udev-acl" ,  SYMLINK + = "trezor% n" 
KERNEL == "hidraw *" ,  ATTRS { idVendor } == "534c",  ATTRS{ idProduct } == "0001" ,   MODE = "0660" ,  GROUP = "plugdev" ,  TAG + = "uaccess" ,  TAG + = "udev-acl"

# TREZOR v2 
SUBSYSTEM == "usb" ,  ATTR { idVendor } == "1209" ,  ATTR { idProduct } == "53c0" ,  MODE = "0660" ,  GROUP = "plugdev" ,  TAG + = "uaccess" ,  TAG + = "udev-acl" ,  SYMLINK + = "trezor% n" 
SUBSYSTEM == "usb" ,  ATTR { idVendor } == "1209",  ATTR{ idProduct } == "53c1" ,  MODE = "0660" ,  GROUP = "plugdev" ,  TAG + = "uaccess" ,  TAG + = "udev-acl" ,  SYMLINK + = "trezor% n" 
KERNEL == "hidraw * " ,  ATTRS { idVendo

**Comment by ligi** [comment]
?

**Pull request closed without merging**
