### PR TITLE
consensus: use the public constant MaxGasLimit to check the header.GasLimit

### PR DESCRIPTION
**Pull request by jovijovi**
Use the constant `maxGasLimit` to check the `header.GasLimit` to avoid creating new variables repeatedly.
It has been tested and passed in the development environment.

### CODE REVIEW

**Comment by holiman** [comment]
The way you did it, instead of being three 'magic' values spread out in the codebase, it's instead three constants spread out in the codebase. Not sure if that's (a lot) better, really? 
If we want it a constant, perhaps better to make it a public constant somewhere.

**Comment by jovijovi** [comment]
> The way you did it, instead of being three 'magic' values spread out in the codebase, it's instead three constants spread out in the codebase. Not sure if that's (a lot) better, really? 
> 
> If we want it a constant, perhaps better to make it a public constant somewhere. 

I thought of that. But there seems to be no place for public constants in the consensus code files. Maybe we can add a new consensus/const.go file to save public constants.

**Comment by fjl** [comment]
We usually keep such constants in package `params`.

**Comment by jovijovi** [comment]
> We usually keep such constants in package `params`.

You're right, I got it. I'll keep the constant `MaxGasLimit` in `params/protocol_params.go`.

**Review by rjl493456442 — APPROVED** [review]

**Review by holiman — APPROVED** [review]

**Pull request merged**
