### PR TITLE
accounts/keystore: non-blocking filesystem scan

### PR DESCRIPTION
**Pull request by holiman**
This PR makes the filesystem watcher not to block account operations during filesystem scan, by splitting the 'reload' into two steps, where the first step can be performed without holding the mutex. 

Potential fix for https://github.com/ethereum/go-ethereum/issues/14810 .

### CODE REVIEW

**Comment by holiman** [comment]
I noticed that modifying or creating files triggered two events via `notify`, so the fs was scanned twice every time a new account was created. The code supposedly handled this, but it wasn't, really. I made another modification, so that once the 'scanning'-phase starts, we unset `hadEvent`. 

Output (with additional logging) with the latest fix, when modifying a file and creating a file: 
```
INFO [08-14|17:45:12] Got event                                event=notify.Write
INFO [08-14|17:45:12] Got event                                event=notify.Write
INFO [08-14|17:45:13] Doing fs scan from 'watcher' 
INFO [08-14|17:45:18] Finished fs scan 
INFO [08-14|17:45:24] Got event                                event=notify.Create
INFO [08-14|17:45:24] Got event                                event=notify.Write
INFO [08-14|17:45:24] Doing fs scan from 'watcher' 
INFO [08-14|17:45:30] Finished fs scan 
```

**Comment by karalabe** [comment]
Apparently Linux and OSX tests hang now. Are you sure about that event dedup? Isn't that only happening on Windows and now you dropped the event altogether? It seems a bit dangerous to me to just discard an event without specific reasons as to why the double notify.

**Comment by holiman** [comment]
So, I've done my tests on Linux, not windows. The thing is, I haven't added any event dedup - that was already there. What I did was simply to _clear_ events just before I start the actual work of scanning the filesystem. 
Any events triggered while the scan is happening will set the flag again. However, _now_, if two events are triggered _during the debounce_ phase, they get treated as one event.

**Comment by fjl** [comment]
`go test -v -timeout=1m ./accounts/keystore` hangs for me.

**Comment by holiman** [comment]
For me, `go test -v -timeout 1m ./accounts/keystore/` takes a rather reliable 10.3 seconds every time. I can't for the life of me see what in my changes would cause a hang. Any pointers appreciated.

**Comment by holiman** [comment]
So @fjl, do you have any output from that hang, so I can see what tests are _not_ causing the hang?

**Comment by lmars** [comment]
@holiman to aid in your investigation, it hangs for me too:

https://gist.github.com/lmars/77df628406ae8d26efffd8484784b6d1

**Comment by holiman** [comment]
Thanks @lmars!

**Comment by holiman** [comment]
The output looks like it's one of the following : 

	TestWatchNewFile
	TestWatchNoDir
	TestV3_PBKDF2_1
	TestV3_Scrypt_1
	TestV1_1
	TestV1_2
	TestKeyForDirectICAP
	TestV3_31_Byte_Key
	TestV3_30_Byte_Key
	TestWalletNotifications

Could one of you try: 

```bash

#!/bin/bash

declare -a arr=("TestWatchNewFile" "TestWatchNoDir" "TestV3_PBKDF2_1" "TestV3_Scrypt_1" "TestV1_1" "TestV1_2" "TestKeyForDirectICAP" "TestV3_31_Byte_Key" "TestV3_30_Byte_Key" "TestWalletNotifications")

for i in "${arr[@]}"
do
  go test -v -timeout 40s ./accounts/keystore/ -run $i
done
```

**Comment by fjl** [comment]
The hang is due to a bug in `TestWalletNotifications`. The test doesn't always read its subscription channel, so if multiple events are sent, the updater loop locks up because it can't deliver the event. We can fix this by increasing the channel buffer size or by making sure that events are recorded in a slice.

**Comment by holiman** [comment]
Thanks, I've changed the buffer size, let's see if it solves the issue.

**Comment by fjl** [comment]
It doesn't work because the test expects exactly one event for each added/removed file.

**Comment by fjl** [comment]
There is an inherent timing issue with the current design that's really hard to fix. Accounts are added to the address cache when creating a new account. If a file system scan is running at the same time it may miss the new account, so it will be removed once the scan results are published. The mutex around the scan avoided this because the account would be added after the scan was done.

The fix will be complicated: the cache needs to track additions while a scan is running and ensure they're present.

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 23b2192c9fc257fb7654900b12eb1fbd64a8e0ad
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by holiman** [comment]
Made a new attempt, which is less 'racy' overall. This one will rescan as long as new events keep coming in. It's not perfect; 
* If an event comes in during the gap that we're waiting for the mutex, it won't be handled. 
* If events keep coming (because the scan is very large), it will be a large delay before scan results are reported. 

I was just a bit curious to see if it was possible to make a passable solution which did not require a more intelligent caching-layer.

**Comment by holiman** [comment]
I think a better solution would be to put the mutex back, but make the scan less intense: maintain a `set` of files seen last time (possibly with mtime if we want to be obnoxiously thorough), and not bother reading the full file contents of all files again. 

We also need a mapping `address->path` . Then upon notification, we scan and update the cache with `added_accounts, deleted_accounts`.

**Pull request closed without merging**
