### PR TITLE
eth/downloader/downloader.go : potential panic

### PR DESCRIPTION
**Pull request by ucwong**

### CODE REVIEW

**Comment by karalabe** [comment]
Potential explanation needed.

**Comment by ucwong** [comment]
> Potential explanation needed.
Sometimes failed, but only in unit test
image

**Comment by holiman** [comment]
@ucwong 

https://github.com/CortexFoundation/CortexTheseus/blob/master/ctxc/downloader/downloader.go#L1 

https://github.com/CortexFoundation/CortexTheseus/commit/a7503464205ad1bba1f7e7c926a303dec25b2cdf

Not cool man

**Comment by ucwong** [comment]
> @ucwong
> 
> https://github.com/CortexFoundation/CortexTheseus/blob/master/ctxc/downloader/downloader.go#L1
> 
> [CortexFoundation/CortexTheseus@a750346](https://github.com/CortexFoundation/CortexTheseus/commit/a7503464205ad1bba1f7e7c926a303dec25b2cdf) [CortexFoundation/CortexTheseus@7ab7a5b](https://github.com/CortexFoundation/CortexTheseus/commit/7ab7a5b7dfa6f55cb7386ab047664252478b2f32)
> 
> Not cool man

Thank you for notification and sorry to reply this so late, revert has been done here. https://github.com/CortexFoundation/CortexTheseus/issues/1825

Best Regards

**Pull request closed without merging**
