### PR TITLE
Fix preimage race (results in the wrong and missing preimages in the database)

### PR DESCRIPTION
**Pull request by AlexeyAkhunov**
I have noticed this problem when doing "differential" testing between go-ethereum and turbo-geth RPC apis. On one machine, I was syncing geth 1.9.12 with `--sync mode full --gcmode archive`, on another - turbo-geth with "similar" settings. The RPC methods I had troubles with (when go-ethereum returned wrong results) were:
1. `debug_getModifiedAccountsByHash`
2. `debug_getStorangeRangeAt`

In the case of the `debug_getModifiedAccountsByHash`, go-ethereum's results contained accounts that were not supposed to be in the ranges at all, and also some accounts that were supposed to be there were missing.
In the case of the `debug_getStorageRangeAt`, I got correct set of key hashes, but often incorrect or missing preimages.
Other RPC requests I used were not affected.

After a while I realised that perhaps go-ethereum's database is corrupted and contains wrong preimages. That would explain that other RPC requests I used, which do not employ preimages, were correct. So I looked into the source code and noticed the race. The one in the `trie/database.go` is definitely the one that causes the races (because after fixing it and re-doing the sync, all request results were fine). I am not yet certain whether the fix in `trie/secure_trie.go` is required.

Hope it helps

### CODE REVIEW

**Comment by holiman** [comment]
Thanks! Looked briefly - I don't understand the change to database.go, how that is related to races... Sure you committed everything?

**Comment by AlexeyAkhunov** [comment]
The fix in `database.go` changes `seckeybuf` field's capacity from 11+32 (which fits `secure-key-` prefix and the hash) to 0, which does not fit anything. This affects the way the first line in the `secureKey` function works:
````
buf := append(db.seckeybuf[:0], secureKeyPrefix...)
````
previously, append would re-use `seckeybuf` so effectively it would be shared between multiple threads (one thread trying to do `Commit`, and another one - trying to work on RPC). I changed it to not be shared.
It is not the best fix, but the shortest for me to simply try if the problem would go away. And it dit

**Comment by holiman** [comment]
Yeah, that's a big "woopsie". I suspect that it's cheaper to not reuse the memory than having to mutex it (but should perhaps be removed entirely, instead of making it a 0-sized buf). 
I'll look into whether the mutexes in secure_trie are needed

**Comment by AlexeyAkhunov** [comment]
> I'll look into whether the mutexes in secure_trie are needed

I think they are not needed, because each invocation of an RPC method creates a new instance of `SecureTrie`, so that cache is not shared across.

**Comment by AlexeyAkhunov** [comment]
Closing this in favour of the proper implementation

**Pull request closed without merging**
