### PR TITLE
node, p2p: make sure the p2p server is stopped in node API

### PR DESCRIPTION
**Pull request by dbadoy**
Even if p2p.Server exists, I think it need to make sure it's actually running.

### CODE REVIEW

**Review by JurbinM — APPROVED** [review]

**Comment by MariusVanDerWijden** [comment]
I'm not 100% sure that this is even needed, but if so, a better change imo would be:
```diff
diff --git a/node/node.go b/node/node.go
index b60e32f22..7c54b053e 100644
--- a/node/node.go
+++ b/node/node.go
@@ -625,6 +625,9 @@ func (n *Node) Server() *p2p.Server {
        n.lock.Lock()
        defer n.lock.Unlock()
 
+       if !n.server.IsRunning() {
+               return nil
+       }
        return n.server
 }
 
diff --git a/p2p/server.go b/p2p/server.go
index 19f7935ff..51c32ef53 100644
--- a/p2p/server.go
+++ b/p2p/server.go
@@ -409,6 +409,13 @@ func (srv *Server) Stop() {
        srv.loopWG.Wait()
 }
 
+func (srv *Server) IsRunning() bool {
+       srv.lock.Lock()
+       defer srv.lock.Unlock()
+
+       return srv.running
+}
+
```

**Comment by fjl** [comment]
I don't think this is needed. If the node is stopped, the API server will also be stopped, and it is therefore very unlikely that an API will execute at a time where the p2p server is not running.

**Comment by dbadoy** [comment]
Thanks the review!

> Even if such a call could happen theoretically, there is no point in trying to be pendantic in this situation.

Actually, I tried find that `node.server is nil` case, but I couldn't find it.
But if it can happen, there is point that need fixing.

web3_ClientVersion
```
func (s *web3API) ClientVersion() string {
	return s.stack.Server().Name
}
```
If node.server is nil, it may occur panic.
@fjl

**Comment by fjl** [comment]
I think this `server == nil` condition is a holdover from previous times. As I said, this condition cannot really occur: the RPC server is terminated before the p2p server, and shutting down RPC waits for all calls to end.

**Comment by dbadoy** [comment]
I understood. Thank a lot!

**Pull request closed without merging**
