### PR TITLE
eth/tracers: avoid panic if nil-receipt passed to OnTxEnd

### PR DESCRIPTION
**Pull request by holiman**
Make tracers more robust by handling `nil` as input. Closes https://github.com/ethereum/go-ethereum/issues/30117

### CODE REVIEW

**Review by MariusVanDerWijden — APPROVED** [review]
SGTM

**Comment by s1na** [comment]
I would like to try an alternative to pass in the receipt instead. Please hold off merging.

**Comment by holiman** [comment]
> I would like to try an alternative to pass in the receipt instead. Please hold off merging.

If it's defined to take a pointer input, I think they should be robust enough to handle `nil`. 

But sure, we can _also_ try to avoid passing nil, that doesn't hurt.

**Comment by holiman** [comment]
Actually, I think this is already fine. Afaict, we only ever pass `nil` recept if `err != nil`, and the tracers already handle that fine. (?)

**Comment by holiman** [comment]
Ah, so the remaining error-prone callsite is in `state_test_util.go`
```golang
	if tracer := vmconfig.Tracer; tracer != nil && tracer.OnTxStart != nil {
		tracer.OnTxStart(evm.GetVMContext(), nil, msg.From)
		if evm.Config.Tracer.OnTxEnd != nil {
			defer func() {
				evm.Config.Tracer.OnTxEnd(nil, err)
			}()
		}
	}
```

**Comment by s1na** [comment]
I took liberty to push a commit on your branch: https://github.com/ethereum/go-ethereum/pull/30332/commits/8d245bf85e48062824c3bb364218870a69890c26

I think just setting GasUsed is fine. Our internal tracers use only that field and the state tests will not be relying on any external.

**Comment by holiman** [comment]
SGTM!

**Review by s1na — APPROVED** [review]
LGTM

**Pull request merged**
