### PR TITLE
accounts/abi: add function to unpack dynamic data in slice or array

### PR DESCRIPTION
**Pull request by weimumu**
I change some code to make the abi package can unpack dynamic data in slice or array rightly

### CODE REVIEW

**Comment by weimumu** [comment]
If I want to be a collaborator of this repository, how can I do. I am very interested in this repository, and I think I can do more thing in this repository. Besides, I have one question. I have contributed a little code to the community, but why i am not the top 100 in contributions.

**Comment by weimumu** [comment]
accounts/abi: fix bug to unpack dynamic data in slice or array

**Comment by gballet** [comment]
Closing this PR as it is superseded by https://github.com/ethereum/go-ethereum/pull/18406. The tests were interesting so I have created a PR for them at https://github.com/ethereum/go-ethereum/pull/18424 and specified you as a co-author.

**Comment by gballet** [comment]
Oh, and in response to your questions, I don't think you have made enough contributions to show up in the insights (at least according to the commit logs). Let's see a couple PRs from now if you still don't show up, we'll investigate then

**Pull request closed without merging**
