### PR TITLE
eth/api: fixed GetCompilers when there is no error creating Solc

### LINKED ISSUE #2598: No Solidity compiler available in fresh geth installation from source
#### System information

Geth version: 1.4.4-stable-8ea3c88e
OS & Version: Linux (tested on Ubuntu and Fedora)

#### Expected behaviour

In the geth console, ```eth.getCompilers()``` returns ```['Solidity' ]``` as described at https://www.ethereum.org/greeter .

#### Actual behaviour

```eth.getCompilers()``` returns ```[ ]```

#### Steps to reproduce the behaviour

Build ```geth``` from source, run the executable in ```build/bin```, attach to it and execute the ```eth.getCompilers()``` command.

Note that I've also tried installing Solidity globally using ```npn -g solc``` as described at http://solidity.readthedocs.io/en/latest/installing-solidity.html . Checked that ```NODE_PATH``` was defined. Killed and re-started ```geth```. There was no change. It has to be noted that the ```node``` repl can import the library, so it must be visible to ```geth```, too.

### PR DESCRIPTION
**Pull request by remyroy**
Fixes #2598.

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Tue May 24 20:45:47 UTC 2016_

**Comment by fjl** [comment]
👍

**Comment by anfedorov** [comment]
Still nothing :(

    root@ubuntu-1gb-sfo1-01:~/code/go-ethereum# /usr/bin/solc | head -n1
    solc, the Solidity commandline compiler.
    root@ubuntu-1gb-sfo1-01:~/code/go-ethereum# build/bin/geth --solc "/usr/bin/solc" attach http://127.0.0.1:8545
    instance: Parity//v1.1.0-beta/x86_64-linux-gnu/rustc1.8.0
    coinbase: 0x8b826939563d985b14f1e421d8753f0bfbf30ace
    at block: 1596676 (Fri, 27 May 2016 18:50:47 EDT)
    > web3.eth.getCompilers()
    []

**Comment by remyroy** [comment]
@anfedorov Which version of geth are you running?

**Pull request merged**
