### PR TITLE
accounts/abi: Better Array/Slice Handling

### PR DESCRIPTION
**Pull request by VoR0220**
* Eliminates entire switch case that was not only ugly as sin, but inefficient to boot.
* Adds a new test function that should be exclusively for handling slices and arrays.
* changes the name of ubig_t (and type) to something a bit more useful (derefbig_t...open to suggestions on a name change).

* todo: Add more tests for every type (might be here, might be in a later PR, depends). As it stands, it currently passes. 

REQUIRES #14610

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 3f7b7ff289894e345fb78b3ed845edb52aa857a8
  * Commit subjects should be kept under 100 characters

 * Commit: 50ee5a2eb4e25b30651146140f472be94c05ff94
  * Commit subjects should be kept under 100 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 3f7b7ff289894e345fb78b3ed845edb52aa857a8
  * Commit subjects should be kept under 100 characters

 * Commit: 50ee5a2eb4e25b30651146140f472be94c05ff94
  * Commit subjects should be kept under 100 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 3f7b7ff289894e345fb78b3ed845edb52aa857a8
  * Commit subjects should be kept under 100 characters

 * Commit: 50ee5a2eb4e25b30651146140f472be94c05ff94
  * Commit subjects should be kept under 100 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 3f7b7ff289894e345fb78b3ed845edb52aa857a8
  * Commit subjects should be kept under 100 characters

 * Commit: 50ee5a2eb4e25b30651146140f472be94c05ff94
  * Commit subjects should be kept under 100 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 824373ae73a06a2274e0bac1be1954d42f336ed8
  * Commit subjects should be kept under 100 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by fjl** [comment]
This is contained in #14743

**Pull request closed without merging**
