### PR TITLE
Polling miner activation

### PR DESCRIPTION
**Pull request by shmookey**

### CODE REVIEW

**Comment by robotally** [comment]
:exclamation: Pull request against `master` :exclamation:

| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Tue Jun 28 05:23:44 UTC 2016_

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 45a259f1053f41457aa62b59b2a4666e5fae6072
  * Commits must be prefixed with the package(s) they modify

 * Commit: 7d3f06b9820b40eda53cf81434c97b2d9942a3a7
  * Commits must be prefixed with the package(s) they modify

 * Commit: 26d69d69c5e44626254b1e920fb57659be1bad5c
  * Commits must be prefixed with the package(s) they modify

 * Commit: 1a6fbacb648589875493ef596b16fd60b9bd1828
  * Commits must be prefixed with the package(s) they modify

 * Commit: b2d29f9e9af6b1076059a12b5974042fa6e10409
  * Commits must be prefixed with the package(s) they modify

 * Commit: 5b0255f05d9df20d3f68f173758b616c471a2d7a
  * Commits must be prefixed with the package(s) they modify

 * Commit: c399152a07049c51b4dbb06211eaa84a3c79016d
  * Commits must be prefixed with the package(s) they modify

 * Commit: c6782a42844c17a917884a152d99860496a055fd
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 45a259f1053f41457aa62b59b2a4666e5fae6072
  * Commits must be prefixed with the package(s) they modify

 * Commit: 7d3f06b9820b40eda53cf81434c97b2d9942a3a7
  * Commits must be prefixed with the package(s) they modify

 * Commit: 26d69d69c5e44626254b1e920fb57659be1bad5c
  * Commits must be prefixed with the package(s) they modify

 * Commit: 1a6fbacb648589875493ef596b16fd60b9bd1828
  * Commits must be prefixed with the package(s) they modify

 * Commit: b2d29f9e9af6b1076059a12b5974042fa6e10409
  * Commits must be prefixed with the package(s) they modify

 * Commit: 5b0255f05d9df20d3f68f173758b616c471a2d7a
  * Commits must be prefixed with the package(s) they modify

 * Commit: c399152a07049c51b4dbb06211eaa84a3c79016d
  * Commits must be prefixed with the package(s) they modify

 * Commit: c6782a42844c17a917884a152d99860496a055fd
  * Commits must be prefixed with the package(s) they modify

 * Commit: 919fd902c547ec6b25a8527f1b3d8db7d40af8df
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by shmookey** [comment]
This PR was meant for our fork, sorry!

**Pull request closed without merging**
