### PR TITLE
Godeps: update all dependencies

### PR DESCRIPTION
**Pull request by karalabe**

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Thu Feb 11 14:48:04 UTC 2016_

**Comment by fjl** [comment]
Please don't update everything at once. I will submit a PR to update otto tonight because upgrading it breaks the pretty-printer.

**Comment by fjl** [comment]
Please don't update everything at once. I will submit a PR to update otto tonight because upgrading it breaks the pretty-printer.

**Comment by fjl** [comment]
Please don't update everything at once. I will submit a PR to update otto tonight because upgrading it breaks the pretty-printer.

**Comment by karalabe** [comment]
@fjl Can't you push those changes on top of this PR? :D

**Comment by fjl** [comment]
That's certainly possible, but anyone who pulls an update in between will get a version of geth where the console doesn't work.

**Comment by karalabe** [comment]
I meant to pull in this PR into your own repo, push your stuff on top of it and open a new PR. We could close this one then and have the changes included in your pr.

**Comment by fjl** [comment]
Yeah can do that in a few hours.

**Comment by karalabe** [comment]
@fjl I'm also thinking it might be a good idea to switch over to the official Go vendoring. That would make our repo fully self contained (i.e. go get, no need for godep to build it); and it would also allow hierarchical vendored packages (i.e. I can vendor go-ethereum itself, without needing to maintain all its dependencies, which godeps currently requires as it only uses a flat namespace). But it's definitely something we should discuss a bit more, just thought I'd mention it so you could think about it too.

**Comment by fjl** [comment]
We can do it when go 1.6 is out and we require go 1.5. The build scripts can set GOVENDOREXPERIMENT on 1.5.

**Comment by karalabe** [comment]
Yeah, that was my idea too :)

**Comment by fjl** [comment]
See #2206

**Pull request closed without merging**
