### PR TITLE
core/state: remove unnecessary preallocation in StateDB.Copy

### PR DESCRIPTION
**Pull request by AaronChen0**
Both stateObjectsDestruct and preimages fields are assigned by the value returned by maps.Clone. The preallocation is a waste.

```
state.stateObjects[addr] = object.deepCopy(state)
```
The `deepCopy` methods only copy a pointer of `state`, so I assume this pr is legitimate.

### CODE REVIEW

**Review by holiman — APPROVED** [review]
LGTM

**Comment by AaronChen0** [comment]
Just notice
```
	state.accountsOrigin = copySet(state.accountsOrigin)
	state.storagesOrigin = copy2DSet(state.storagesOrigin)
```
The origin lines copied itself. Is that a mistake?

**Comment by holiman** [comment]
Yes, introduced here: https://github.com/ethereum/go-ethereum/pull/27349/files#diff-c3757dc9e9d868f63bc84a0cc67159c1d5c22cc5d8c9468757098f0492e0658cR817

**Review by rjl493456442 — APPROVED** [review]
SGTM

**Pull request merged**
