### PR TITLE
Fix mixHash/nonce for parity compatible network

### PR DESCRIPTION
**Pull request by jdkanani**

### CODE REVIEW

**Comment by holiman** [comment]
Could you elaborate, in what situation would this change make a difference?

**Comment by jdkanani** [comment]
@holiman Following code will fail without this PR.

```golang
client, _ := ethclient.Dial("https://kovan.infura.io")
header, err := client.HeaderByNumber(ctx, nil)
if err != nil {
    log.Fatal(err)
} else {
    fmt.Println(header)
}
```

**Comment by karalabe** [comment]
Isn't this a Parity error that needs to be fixed on their side?

**Comment by holiman** [comment]
I don't think it's an 'error' pre se, afaik kovan has a different structure for block headers. It's not `rlp` compatible, it's not `json` compatible. If this fix makes it 'work', then I'm ok with it.

**Comment by karalabe** [comment]
Ah, it's Kovan. That explains it. Can we just kill kovan in favor of Görli? :D

**Comment by jdkanani** [comment]
So this will get merged, right? :) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by naikmyeong** [comment]
@karalabe Or should we kill rinkeby also so we can merge multiple POA testnets into one? 😂

**Comment by rmulhol** [comment]
Playing around with this, it seems the data you get back when pointing at Kovan is not correct. Specifically, the block hash doesn't match. For example, if I query for `BlockByNumber` at block 6,000,000 and call `block.Hash()`, it's outputting `0x5d97eef9b38f68ba351d83117fd9fe910b1a4fcb8e3aa22408e04376d8088753` - but [Etherscan](https://kovan.etherscan.io/block/6000000) shows that block hash as `0xec501946b182d39e4311d79e8168d224f17c4f1469cd9301b5f5d5ccd118a94a`.

I believe that has to do with a mismatch on the `Nonce` field. With the above changes, Geth registers a nonce of `0x0000000000000000`, but Etherscan shows a nonce of `0xb8418a61b7c658282c897e7f26248734a2733f8623e08671973a207c272f3b797a3802dfe7f6026baa9de54708d24424b76bc21b0e780ce1173a0ffdb0e7a999b7bc00`

Here's a little script to reproduce (note you must insert your own Infura token):
```
package main

import (
	"context"
	"log"
	"math/big"

	"github.com/ethereum/go-ethereum/ethclient"
	"github.com/ethereum/go-ethereum/rpc"
)

func main() {
	myRPC, err := rpc.Dial("https://kovan.infura.io/INSERT-YOUR-TOKEN-HERE")
	if err != nil {
		log.Fatal("error connecting to rpc: ", err)
	}
	myEthClient := ethclient.NewClient(myRPC)
	block, err := myEthClient.BlockByNumber(context.Background(), big.NewInt(6000000))
	if err != nil {
		log.Fatal("error fetching block: ", err)
	}
	log.Println("Block found with hash: ", block.Hash().String())
}
```

Let me know if this is worth creating a separate issue.

**Comment by holiman** [comment]
Well, to quote myself:

> I don't think it's an 'error' pre se, afaik kovan has a different structure for block headers. It's not rlp compatible, it's not json compatible. 

Since the hash is the hash of the rlp-encoded blob, with certain quirks (such as not actually including the sealhash in the hash to seal/sign), geth cannot meaningfully produce a block hash of a kovan block. 

> If this fix makes it 'work', then I'm ok with it.

So what I mean above when I wrote 'work' in quotes, is that this change will kind of look and feel like it works, but there will be deeper problems later on.

**Pull request merged**
