### PR TITLE
RPC migration

### PR DESCRIPTION
**Pull request by bas-vk**
This PR will:
- [x] migrate the RPC-HTTP interface to the new RPC implementation
- [x] remove the xeth package
- [x] remove the old RPC packages and moves rpc/v2 to rpc
- [x] improved auto completion in the console
- [x] add RPC websocket interface

Disables natspec (https://github.com/ethereum/go-ethereum/pull/2083)

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Mon Jan 11 12:53:05 UTC 2016_

**Comment by zsfelfoldi** [comment]
Just a note, not urgent, can be changed later after the light client is working: registryAPIBackend of PrivateRegistarAPI uses core.BlockChain and core.TxPool directly, which is full client dependent. I think these kind of functions that could work the same way with full and light nodes might use further RPC calls to access the appropriate API implementations (PublicBlockChainAPI and PublicTransactionPoolAPI for full nodes, PublicLightChainAPI and PublicLightTxPoolAPI for light nodes).

**Comment by zsfelfoldi** [comment]
Otherwise, is seems fine to me :) :+1: 
(just nitpicking: a few exported functions in cmd/utils/client.go are not documented, although I'm not sure they need to be, they're quite trivial)

**Comment by bas-vk** [comment]
@zsfelfoldi, added docs to client.go.

The current registry does not seems to be production ready yet. The current registry is documented in the console but not in the API section of the wiki and I think the offered RPC methods should be polished before they are production ready.

**Comment by obscuren** [comment]
Took ownership in https://github.com/ethereum/go-ethereum/pull/2140

**Pull request closed without merging**
