### PR TITLE
Adds support for extended headers in CORS requests.

### LINKED ISSUE #3762: CORS headers not applied to preflight requests with extended headers.
#### Expected behaviour

HTTP response from geth to contain `Access-Control-Allow-Origin` header.

#### Actual behaviour

Http response does not contain `Access-Control-Allow-Origin` header.

#### Steps to reproduce the behaviour

Run geth with `--rpccorsdomain "*"`.  Send a preflight request like:
```
OPTIONS / HTTP/1.1
Host: 127.0.0.1:8546
Connection: keep-alive
Access-Control-Request-Method: POST
Origin: http://localhost:8080
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Access-Control-Request-Headers: content-type, x-requested-with
Accept: */*
Referer: http://localhost:8080/?page=transactions
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8
```

---

When configuring https://github.com/rs/cors (the library being used to deal with CORS in geth), you can provide a list of `AllowedHeaders`.  If the preflight request asks for headers that are not in this list then the preflight request is not responded to with the appropriate CORS headers (like `Access-Control-Allow-Origin`).  The easiest solution to this problem is to allow for any headers by setting `AllowedHeaders = ["*"]` (or whatever the Go syntax for that is).  Alternatively, geth could allow the user to supply a list of allowed headers.

You can see the comment here about the magic `*` header: https://github.com/rs/cors/blob/master/cors.go#L50-L54

The motivation for this is that I am using a JavaScript library that adds an `x-requested-with` header to outbound requests.  This is a common practice in the browser world (jquery, for example, does it).  At the moment, my requests made through this library are being rejected because geth isn't responding with the appropriate CORS headers.

### PR DESCRIPTION
**Pull request by MicahZoltu**
Fixes #3762.  Details about parameter: https://github.com/rs/cors/blob/a62a804a8a009876ca59105f7899938a1349f4b3/cors.go#L50-L54

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: a0967135792d7f8d98f0104afee2252515455959
  * Your commit message body contains a line that is longer than 80 characters
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by obscuren** [comment]
If I understand correctly this will *always* add the `*` options regardless of chosen `--rpccorsdomain`?

**Comment by MicahZoltu** [comment]
This will _always_ add `*` to `AllowedHeaders`, regardless of any `--rpccorsdomain` settings.  However, the CORS domain logic will still be in effect so the user will still need to use `--rpccorsdomain` to get the necessary response headers from Geth.  If the user doesn't set `--rpccorsdomain`, the behavior will remain the same and the request will not get the appropriate CORS headers in the response.

CORS handling is an `&&` operation, everything must line up to get the CORS headers in a response.  If one thing doesn't match, the entire request is considered not CORS elligible.  This is what is causing pain in browser apps now, one extra header is sent on the request so all of CORS fails (even though the domain matches).

**Comment by MicahZoltu** [comment]
If it is decided to merge this PR, I'll address the comments from the bot.  I just don't want to put in the effort until the PR is otherwise approved.  :)

**Comment by bas-vk** [comment]
Thank you for looking into this. The cors library only allows by default the `[Origin", "Accept", "Content-Type"]` headers. I don't see any danger in allowing all headers, after all the whole cors thing is something that browsers enforce. Unless if someone have a good point in making this configurable we can use `*`. 

This also needs to be changed in `rpc/http.go` (bottom of the file).

**Pull request closed without merging**
