### PR TITLE
Custom rpc.Client handling

### PR DESCRIPTION
**Pull request by LucasALLOIN**
### Pull Request Description

Issue: #30630 

**Purpose:**
This PR implements an enhancement to the `ethclient.Client` struct, allowing developers to utilize a custom `rpc.Client`. 

**Changes Made:**
- Introduced an interface named `rpc.ClientInterface` to define the behavior of the `rpc.Client`.
- Updated the `ethclient.Client` struct to incorporate this new interface, allowing for greater flexibility and customization.
- Ensured backward compatibility with existing functionality.

**Rationale:**
The need for this enhancement arose from the requirement to add custom features that interact with the RPC calls made by the client. By enabling the use of a custom `rpc.Client`, developers can streamline their implementations and avoid duplicating logic across multiple methods.

**Implementation Details:**
- The `rpc.ClientInterface` will be defined in a way that covers all necessary functionalities currently present in `ethclient.Client`.
- The implementation will be straightforward, ensuring that existing users of `ethclient.Client` can continue to use the library without any modifications to their existing code.

**Next Steps:**
- Please review the changes and provide feedback.
- I am open to any suggestions or additional requirements that may enhance this feature.

Thank you for considering this enhancement!

### CODE REVIEW

**Review by Jenniferab5 — COMMENTED** [review]
Review

**Review by Jenniferab5 — COMMENTED** [review]
Review

**Comment by karalabe** [comment]
You'll need to rationalize this with specific use cases, otherwise it's getting very meta here.

**Comment by LucasALLOIN** [comment]
Hey @karalabe, thanks for taking a look at this. Let me clarify the use case further:

This interface will allow developers to track and intercept all calls made through `ethclient`, including those invoked by bound contracts. For example, I work with services that need to submit a large volume of on-chain transactions across various EVM chains.

**Some real-world scenarios where this is helpful:**

1. **Transaction Publishing Errors:**
   I’ve encountered cases where the node experiences a connection reset while submitting a transaction. The submission results in an error, but the transaction is actually successfully published. By implementing this custom interface, I can save the transaction details in the database before submitting it, then check whether the error is legitimate or if the transaction was published despite the error.

2. **Fee Calculation Issues:**
   In some instances, fee calculations may be incorrect, and I need to intercept and handle the node’s responses. The interface would make it easy to inspect the result and apply custom logic to handle such errors.

3. **Custom Error Conversion:**
   This interface will also allow for custom error handling and conversion at the RPC call level, simplifying error management for complex interactions.

Without this interface, I’d need to wrap each contract transaction or every method I want to intercept, which is quite painful and leads to a lot of boilerplate code.

Here’s an example showing how I would intercept all RPC calls using this interface:

```go
package main

import (
	"context"
	"fmt"
	"github.com/anima-protocol/anima/pkg/animaerr"
	"github.com/anima-protocol/anima/services/dapp-api/pkg/contracts"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/rpc"
	"log"
)

type ClientInterface interface {
	Call(result interface{}, method string, args ...interface{}) error
	CallContext(ctx context.Context, result interface{}, method string, args ...interface{}) error
	BatchCall(b []rpc.BatchElem) error
	BatchCallContext(ctx context.Context, b []rpc.BatchElem) error
	Notify(ctx context.Context, method string, args ...interface{}) error
	EthSubscribe(ctx context.Context, channel interface{}, args ...interface{}) (*rpc.ClientSubscription, error)
	SupportsSubscriptions() bool
	Close()
}

type CustomRPCClient struct {
	ClientInterface
}

func NewCustomRPCClient(ctx context.Context, url string) (*CustomRPCClient, error) {
	i, err := rpc.DialContext(ctx, url)
	if err != nil {
		return nil, animaerr.ReportAndInternal(ctx, err, "failed to connect to Ethereum client")
	}
	client := &CustomRPCClient{ClientInterface: i}
	return client, nil
}

func (c *CustomRPCClient) CallContext(
	ctx context.Context,
	result interface{},
	method string,
	args ...interface{},
) error {
	fmt.Printf("Intercepting CallContext: method %s with args %v\n", method, args)
	return c.ClientInterface.CallContext(ctx, result, method, args...)
}

func main() {
	ctx := context.Background()
	rpcClient, err := NewCustomRPCClient(ctx, "https://rpc.url")
	if err != nil {
		panic(err)
	}

	// Interact with ethclient using the custom RPC client
	c1 := NewClient(rpcClient)

	chainID, err := c1.ChainID(ctx)
	if err != nil {
		panic(err)
	}
	fmt.Printf("ChainID: %v\n", chainID)

	// Interact with a contract
	contractInstance, err := contracts.NewContract(
		common.HexToAddress("0x000000"),
		c1,
	)
	if err != nil {
		log.Fatal(err)
	}

	// Example contract method call
	defaultAdmin, err := contractInstance.DEFAULTADMINROLE(nil)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("DefaultAdminRole: %v\n", defaultAdmin)
}
```

**Example Output:**
```
Intercepting CallContext: method eth_chainId with args []
ChainID: 11155111
Intercepting CallContext: method eth_call with args [map[from:0x0000000000000000000000000000000000000000 input:0xa217fddf to:0x000000] latest]
DefaultAdminRole: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
```

As you can see, all calls are automatically intercepted through the custom `rpc.ClientInterface` implementation. This approach will make it much easier to extend `ethclient` for various use cases.

Let me know if this makes things clearer or if you have further questions. I’m happy to discuss this in more detail.

**Comment by lightclient** [comment]
@LucasALLOIN you should use `DialHTTPWithClient` and pass a custom `http.Client` with the logging you desire.

**Review by Jenniferab5 — COMMENTED** [review]
[]() review

**Pull request closed without merging**
