### PR TITLE
Makefile: enable 64-bit ARM builds on Linux

### PR DESCRIPTION
**Pull request by karalabe**

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Wed Dec 2 14:58:15 UTC 2015_

**Comment by karalabe** [comment]
@fjl or @obscuren, merge before the nightly builds at 5am? :)

**Comment by obscuren** [comment]
:boom:

**Comment by karalabe** [comment]
Muahahahahaaaaa

**Comment by obscuren** [comment]
all your base

**Pull request merged**
