### PR TITLE
RPC v2 rebase, node updates pending, work branch

### PR DESCRIPTION
**Pull request by karalabe**
This is a rebase of @bas-vk 's RPC PR on top of the split nodes. It does not yet contain the agreed `rpc.Api` constructs, but implementing that without the new RPC package turned out to be extremely unwieldy (would have required splitting APIs into separate structs, which was already done by Bas), whereas rebasing Bas' changes needed relatively minor patches at just a handful of places. I'll add the `node` extensions on top of this PR, and then I'll kindly ask Bas to take ownership and finish up the new RPC implementation.

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Tue Dec 1 15:39:43 UTC 2015_

**Comment by karalabe** [comment]
This PR contains a commit combining a lot of features we discussed and not yet added in the current code base. Please don't close until the added commit at the end is ported to develop in a new pr.

**Comment by fjl** [comment]
Sorry for closing prematurely, I should've asked first.

**Comment by karalabe** [comment]
Superseded.

**Pull request closed without merging**
