### PR TITLE
README: expand with "Running Geth" section

### PR DESCRIPTION
**Pull request by karalabe**
Our readme sucks. This is a stab at making it suck a bit less :)

PS: It's needed for post-dao-hard-fork to describe `geth init`, which we never got around to previously. I figured that if we're expanding on this, might as well do it properly.

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Tue Jul 12 09:53:26 UTC 2016_

**Comment by fjl** [comment]
:+1:

**Comment by fjl** [comment]
fyi `geth init` is documented [here](https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options#init)

**Comment by karalabe** [comment]
Ah nice, didn't know about that.

**Pull request merged**
