### PR TITLE
internal/ethapi/api, accounts/abi/bind: Cap highest gas limit by account balance for 1559 fee parameters

### PR DESCRIPTION
**Pull request by lightclient**
Currently, you can call `eth_estimateGas` with EIP-1559 fee parameters and it won't cap the gas limits it tries based on the account balance. This can cause an `ErrInsufficientFunds` to be propagated back to the users if they can't afford the initial `hi * maxFeeCapPerGas + value`.

Before:
```console
$ curl http://localhost:8645 -H 'Content-Type: application/json' -d '{"method":"eth_estimateGas","id":1,"jsonrpc":"2.0", "params":[{"type":"0x2","maxFeePerGas":"0xb2d05e00","maxPriorityFeePerGas":"0xb2d05e00","value":"0x2386f26fc10000","from":"0xe77162b7d2ceb3625a4993bab557403a7b706f18","to":"0xe77162b7d2ceb3625a4993bab557403a7b706f18","data":"0x"}]}' | jq .
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32000,
    "message": "err: insufficient funds for gas * price + value: address 0xe77162b7D2CEb3625a4993Bab557403a7B706F18 have 50000000000000000 want 54943570000000000 (supplied gas 14981190)"
  }
}
```

After:
```console
$ curl http://localhost:8645 -H 'Content-Type: application/json' -d '{"method":"eth_estimateGas","i
d":1,"jsonrpc":"2.0", "params":[{"type":"0x2","maxFeePerGas":"0xb2d05e00","maxPriorityFeePerGas":"0xb2d05e00","value":"0x2386f26fc10
000","from":"0xe77162b7d2ceb3625a4993bab557403a7b706f18","to":"0xe77162b7d2ceb3625a4993bab557403a7b706f18","data":"0x"}]}' | jq .
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": "0x5208"
}
```

*Note that these request are against a Gorli node.*

### CODE REVIEW

**Review by rjl493456442 — APPROVED** [review]
Thanks for catching it, lgtm.

**Comment by karalabe** [comment]
Do we need to duplicate this for the simulated backend too?

**Comment by rjl493456442** [comment]
Right, I think we need to port the change to the accounts/abi/bind/backends.

**Comment by lightclient** [comment]
@rjl493456442 @karalabe I ported this to the simulated backend and added a test for it, but because the simulated backend grants the account a balance of `2**256-1` it doesn't fail the same way as the it does in the `ethapi`.

https://github.com/ethereum/go-ethereum/blob/3b26cd1847fe52f09fc876dbff856cbe1e42edde/accounts/abi/bind/backends/simulated.go#L622-L623

It will, however, return a gas value even if the account can't afford it. This is different than how legacy fee estimates are evaluated -- if the account can't afford the estimated gas, the call returns an error `gas required exceeds allowance (X)`.

Feel free to drop the last two commits as you see fit.

**Comment by GregTheGreek** [comment]
I don't think this is a great call, if I'm not mistaken users may want to call `eth_estimateGas` before submitting a metaTx in which case they may be paying for the transaction in a token other than ETH. I don't know if that example is 100% accurate, but its the first thing that came to my mind.

**Comment by GregTheGreek** [comment]
Is this going to get in before London? Do we know what ranges might look like for small wallet balances? This could block a lot of wallets from submitting transactions if they have something like:

```
try {
  const gas = web3.eth.estimateGas(...)
  const tx = ... // maybe modify the tx;
  web3.sendTransaction(tx);
} catch (e) {
  // skips sending transaction
}
```

**Comment by GregTheGreek** [comment]
For example, I know Argent wallet [does this](https://twitter.com/itamarl/status/1422606699052023815)

**Review by holiman — APPROVED** [review]
LGTM

**Review by rjl493456442 — APPROVED** [review]

**Comment by karalabe** [comment]
Pushed a minor naming nitpick so internal variables are using the Go API style and the error message used the RPC API style. Otherwise LGTM

**Pull request merged**
