### PR TITLE
cmd/swarm: tools to update/manipulate manifests

### PR DESCRIPTION
**Pull request by jmozah**
#3498

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 18bf7ba0238f069162b62e945065e9e6e7ef2fad
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 18bf7ba0238f069162b62e945065e9e6e7ef2fad
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by jmozah** [comment]
adding a left out file, manifest.go

**Comment by zelig** [comment]
oh so why was this closed? is it now #3572 ?

**Pull request closed without merging**
