### PR TITLE
internal/api: Removed the binary search method and adopted a more efficient and accurate estimation approach.

### PR DESCRIPTION
**Pull request by joohhnnn**
@s1na 
https://github.com/ethereum/go-ethereum/pull/27154#issuecomment-1520215797
First of all, I apologize for submitting a new PR, as I couldn't find the button to reopen a PR. Secondly, I agree with what you said, so I added a double check and reintroduced the binary search method on this basis (to handle the special cases you mentioned).

### CODE REVIEW

**Comment by karalabe** [comment]
I don't really understand what the purpose of this PR is.

You say it's more accurate, but I don't see how it can be more accurate than the binary search. That is "perfect".

As to having a lot of special case logic, it seems very dangerous to me that you miss some strange aspect, some cornercase, or simply some future change that will break the code. Why is it an issue that estimation takes a few iterations?

**Comment by joohhnnn** [comment]
> I don't really understand what the purpose of this PR is.
> 
> You say it's more accurate, but I don't see how it can be more accurate than the binary search. That is "perfect".
> 
> As to having a lot of special case logic, it seems very dangerous to me that you miss some strange aspect, some cornercase, or simply some future change that will break the code. Why is it an issue that estimation takes a few iterations?

I apologize for any confusion caused by my ambiguous title. I can explain the changes made. Firstly, the idea for this issue came from https://github.com/ethereum/go-ethereum/pull/27132. I personally believe that the reason for using binary search is that the unpredictable gas refund and the dynamic changes in gas refund limitations can lead to dynamic gas consumption. More specifically, it's because it's impossible to predict the exact amount of gas refund generated. If the gas refund was predetermined at the beginning of the design, or if there was no gas refund at all, I think the binary search method wouldn't be used here. With this major premise in mind, I discovered that the value of gasRefund can be implemented, meaning that the amount of gas potentially needed can be narrowed down to a very small range from the start.

This is the logic for determining the actual amount of gas used before the gas refund.

Given:

`postRefundGasUsed`: The actual consumed gas after the transaction execution (including gasRefund).
`refund`: The refund value obtained from state.GetRefund().
To calculate preRefundGasUsed, you can use the following formula:

If the refund is at most half （Before eip-3529）of the preRefundGasUsed, you can use the following formula to calculate:

`preRefundGasUsed = postRefundGasUsed + min(refund, postRefundGasUsed)`

If the refund is at most one-fifth（after eip-3529） of the preRefundGasUsed, you can use the following formula to calculate:

`preRefundGasUsed = postRefundGasUsed + min(refund, postRefundGasUsed * 1/4)`

**Comment by karalabe** [comment]
Refunds aren't the only weird quirks. When you do a CALL, only 63/64th of the gas gets forwarded. Meaning that even without refunds, a CALL will need more gas to call than what it needs to execute. These are the very weird quirks that are forever a source of bug if teh code tries to be smart.

**Comment by joohhnnn** [comment]
> Refunds aren't the only weird quirks. When you do a CALL, only 63/64th of the gas gets forwarded. Meaning that even without refunds, a CALL will need more gas to call than what it needs to execute. These are the very weird quirks that are forever a source of bug if teh code tries to be smart.

lol, It's another day of learning new knowledge. Although I really want to continue to follow up on this issue, I understand your point. Unless necessary, it's better not to make changes to things that can easily cause bugs.

**Comment by karalabe** [comment]
I'll close this PR as it's something we've tried to do smart for a long time and ended up with the binary search which worked flawlessly for the past 6 years. Perhaps not the most optimal, but transaction creation is less of a bottleneck than execution, so I think it should be fine, correctness is more important here.

**Pull request closed without merging**
