### PR TITLE
refactor NewBlockChain

### PR DESCRIPTION
**Pull request by ducquangkstn**
resolve https://github.com/ethereum/go-ethereum/issues/20280

### CODE REVIEW

**Comment by karalabe** [comment]
This is a really elegant solution. Need to debate it with the team to potentially move over all inits to this style. Will keep this PR hanging a bit until we decide.

**Comment by holiman** [comment]
For the record, I like this style

**Comment by djbehnke** [comment]
So this issue (https://github.com/ethereum/go-ethereum/issues/20280) is still open and tagged as a good first issue. Do you guys have any feedback for people who want to try and tackle this issue? Why has this PR not been merged?

**Comment by fredbuluku** [comment]
> validate the new blockchain

**Comment by d00medman** [comment]
bumping @djbehnke comment. Why was this PR discarded?

**Comment by jjlittlezz** [comment]
sorry never Git before

**Pull request closed without merging**
