### PR TITLE
accounts/abi/bin/backends: add market gas price to simulate duplicate nonce behavior in stuck tx

### PR DESCRIPTION
**Pull request by susannapaxos**
currently in simulated backend we cannot keep txes in the same nonce to simulate the fee bump scenario

this is introducing stuck tx and method to set market gas price so that txes are being kept in mem pool when its below the threshold.

added test in simulated_test.go

### CODE REVIEW

**Review by dench201 — APPROVED** [review]

**Comment by rjl493456442** [comment]
> currently in simulated backend we cannot keep txes in the same nonce to simulate the fee bump scenario

I am not sure it's expected in simulated backend. It's originally designed for testing, not like a fake blockchain.

**Comment by susannapaxos** [comment]
> > currently in simulated backend we cannot keep txes in the same nonce to simulate the fee bump scenario
> 
> I am not sure it's expected in simulated backend. It's originally designed for testing, not like a fake blockchain.

yeah exactly, with this change then it helps with testing fee bump situation, instead of currently we'll need to increase tx nonce in order for the sim chain to accept that tx. goal here is not to create a fake blockchain, but improve the sim chain so that it is easy to test.

**Review by popeda97 — COMMENTED** [review]
.github/CONTRIBUTING.md

**Review by Mitumaru — APPROVED** [review]

**Comment by susannapaxos** [comment]
update on this?

**Comment by holiman** [comment]
My feeling is that this adds (quite a lot of) complexity for a somewhat niche goal that not a lot of users will use. I vote to close this PR.

**Comment by karalabe** [comment]
Also this seems to be possible to add this on top as a wrapper around the simulated backend, so there's no particular need to add it inside.

**Pull request closed without merging**
