### PR TITLE
core/vm: enable istanbul EIPs in the jump table

### PR DESCRIPTION
**Pull request by karalabe**

### CODE REVIEW

**Comment by holiman** [comment]
PR LGTM so far, but I think there's some remaining work to be done... Ok if I push some on top?

**Comment by karalabe** [comment]
Sure, though what did I miss?

**Comment by holiman** [comment]
retesteth support

**Comment by holiman** [comment]
And support in state tests

**Comment by holiman** [comment]
LGTM
```
[user@work go-ethereum]$ build/bin/evm --code "6001464700" --json --prestate istanbul_genesis.json run 
{"pc":0,"op":96,"gas":"0x8000000","gasCost":"0x3","memory":"0x","memSize":0,"stack":[],"depth":1,"refund":0,"opName":"PUSH1","error":""}
{"pc":2,"op":70,"gas":"0x7fffffd","gasCost":"0x2","memory":"0x","memSize":0,"stack":["0x1"],"depth":1,"refund":0,"opName":"CHAINID","error":""}
{"pc":3,"op":71,"gas":"0x7fffffb","gasCost":"0x5","memory":"0x","memSize":0,"stack":["0x1","0x21"],"depth":1,"refund":0,"opName":"SELFBALANCE","error":""}
{"pc":4,"op":0,"gas":"0x7fffff6","gasCost":"0x0","memory":"0x","memSize":0,"stack":["0x1","0x21","0x0"],"depth":1,"refund":0,"opName":"STOP","error":""}
{"output":"","gasUsed":"0xa","time":120632}
```
With the following genesis
```json
{
  "config": {
    "chainId": 33,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0
  },
  "nonce": "0x0000000000000033",
  "timestamp": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0x8000000",
  "difficulty": "0x100",
  "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x3333333333333333333333333333333333333333",
  "alloc": {}
}
```

**Pull request merged**
