### PR TITLE
types: add field 'from' to Receipt

### PR DESCRIPTION
**Pull request by Haupc**
Add field `from` to transaction receipt.

### CODE REVIEW

**Comment by karalabe** [comment]
I'm not entirely sure what you're trying to do here. This is a consensus type, you can't just modify it.

**Comment by karalabe** [comment]
Ah, seems this srtuct also accepts non consensus fields. Either way, any changes needs a very good motivation.

**Comment by Haupc** [comment]
I just want to add field `from` for client to know the sender from receipt because that field already included in the response from server. This is no need to do anything from server side but much more convince for client to get that info

**Comment by Haupc** [comment]
> Ah, seems this srtuct also accepts non consensus fields. Either way, any changes needs a very good motivation.


I just want to add field from for client to know the sender from receipt because that field already included in the response from server. This is no need to do anything from server side but much more convince for client to get that info

**Comment by Haupc** [comment]
@karalabe using the `(ec *Client) TransactionSender` we need to know block and index of tx and there is no short way to get the sender when we already know the tx hash although it is returned in field `from` of request `eth_getTransactionReceipt`

**Pull request closed without merging**
