### PR TITLE
Go 1.12.8 breaks TestParseNode and TestClientNotificationStorm tests #19959

### PR DESCRIPTION
**Pull request by thomasmodeneis**
see #19959 for info about the bug.

### CODE REVIEW

**Comment by thomasmodeneis** [comment]
It seems like its also affecting the RPC package, the test TestClientNotificationStorm is now throwing context.deadlineExceededError instead of ErrSubscriptionQueueOverflow error.

```
--- FAIL: TestClientNotificationStorm (2.31s)
    client_test.go:378: didn't get expected error
FAIL
```

I'm not yet sure why, any ideas ?

**Comment by fjl** [comment]
I have a simpler fix in #19963. The failure in package rpc is not related to Go 1.12.8 AFAIK.

**Comment by thomasmodeneis** [comment]
Right, that also fixes it...what do you want to do then ? merge the new one and leave this the way it is ? 
You could have told me to use strings.contains instead of opening a new pr, but ok....

**Comment by fjl** [comment]
Sorry, it was easier for me to make the change myself than to modify your PR.

**Pull request closed without merging**
