### PR TITLE
crypto/crypto, cmd/geth: added ChecksumAddress

### PR DESCRIPTION
**Pull request by 8go**
I added 2 functions: **ChecksumAddress**(address) and **ChecksumAddressHex**(string)
Both functions convert a public (20-byte, 40-hex) address into a **checksummed address**. 
The algorithm follows design outlined in https://github.com/ethereum/EIPs/issues/55
The implementation follows the Javascript implementation. 
Test functions with 25+ test cases have been provided for both functions. 
````geth account new```` prints now a checksummed address such as: 
````
Address: 0x50074DFbB298B0f4Aa351B35B24629200C93AE29
````
Note the lower and uppercase letters in the address. The functions will also work on longer addresses.  ChecksumAddressHex() will work with or without the 0x prefix on input. 
As discussed on https://github.com/ethereum/EIPs/issues/55, the output always has a "0x" prefix.

This is my first contribution to Ethereum, so please be tolerant and let me know if I did it correctly or point out any mistakes I made in creating the git Pull Request. Thank you.

### CODE REVIEW

**Comment by 8go** [comment]
Sorry, I am a newbie. About the "rebase and format and squash your commit messages". I figure that means a ````git rebase -i HEAD~2```` to merge the 2 commits into one. I've done it, and now git tells me ````Your branch and 'origin/master' have diverged````. Not knowing too much about git, I am afraid I will screw something up. How shall I continue?

You made a lot of good comments and suggestions (use ````a[:]```` instead of ````a.Bytes()````, etc.). What is the std process now? I implement your suggestions and do another commit? 

Please advise. Thank you.

**Comment by 8go** [comment]
I implemented all your improvement suggestions. I committed changes locally and did a push. These changes should automatically be appended to the original pull request. What is the next step for me to assist?

**Comment by 8go** [comment]
The issue is a broader than implemented in this pull request so far. 

In ```cmd/geth/main.go``` there are these occurrences where addresses are displayed **without** CheckSum: 
In ```unlockAccount()```:
```	   msg := fmt.Sprintf("Unlocking account %s | Attempt %d/%d", addr, tries+1, attempts)
	   fmt.Printf("Account '%s' (%v) unlocked.\n", addr, addrHex)```
In ```accountList()```:
```	   fmt.Printf("Account #%d: %x\n", i, acct)```
In ```importWallet()```:
```	   fmt.Printf("Address: %x\n", acct)```
In ```accountImport()```:
```	   fmt.Printf("Address: %x\n", acct)```

Here the addresses are always printed without the ```0x``` prefix, and all lowercase. 
In https://github.com/ethereum/EIPs/issues/55 it was pointed out that we should be consistent and standardize. Shouldn't we put a ```0x``` in front of the address and checksum the address whenever we display an address to the user?

How about the filename in the ```.ethereum/keystore```? Should ```UTC--2016-03-15T07-30-20.396377029Z--ba3a2b751b0931e2560114df11b060ef05559a4a``` become ```UTC--2016-03-15T07-30-20.396377029Z--ba3A2b751B0931e2560114df11B060EF05559A4a```??? If we were to go with checksummed addresses in the keystore file names we have to be very careful to stay backwards compatible with the existing lowercase file names.

What do you think? Should I add the ```0x``` prefix and checksumming to all print stmt in ```geth/main.go```? Shall I leave the file names as is, all lower case?

**Comment by karalabe** [comment]
Hmm, ok so this PR is kind of messy right now as you based it on top of master and then there are tons of conflicts and weird commits. Cleaning it up will take a few iterations, so for the first go, pleace get rid of all commits that aren't yours and only have those in the PR.

Since this branch is probably a tad too messy to fix up, I recommend doing the following:

 * Create a fresh new branch from develop
 * Go over all your own commits from this PR and cherry pick them into your new branch `git cherry-pick <commit hash>`
 * Open a new PR with that code, we can take it forward from there.

Currently this PR is almost impossible to review since it contains soo many other stuff that it shouldn't.

**Comment by 8go** [comment]
I tried to follow you suggestion. I hope I did it correctly. The new PR is in https://github.com/ethereum/go-ethereum/pull/2347.

**Comment by karalabe** [comment]
Closing this in favor of the above mentioned new PR.

**Pull request closed without merging**
