### PR TITLE
p2p/enode: store local port number as uint16

### PR DESCRIPTION
**Pull request by jfcg**
Fix integer conversions discovered by CodeQL

### CODE REVIEW

**Comment by fjl** [comment]
We have decided against enabling CodeQL scanning in the past, for various reasons.

**Comment by fjl** [comment]
That said, would be interested to explain the reasoning behind the integer conversion change in package p2p/enode?

**Comment by jfcg** [comment]
Port of an internet address has a well-defined range (hence type), and we need to utilize that when parsing a port string. For example "71000" should be treated equally invalid as "xyzw" when parsing a port field. This can yield to unpredictable problems, including security ones and CodeQL warns about these.

**Comment by fjl** [comment]
I don't think it is a security issue in this specific case because netutil.IPTracker will always return one of the strings added to it via AddStatement, and the statement strings are created via net.UDPAddr.String. However I do agree it is cleaner to use uint16.

Could you remove the CodeQL addition and leave only the integer type change in this PR? I would merge it then.

**Review by fjl — APPROVED** [review]

**Pull request merged**
