### PR TITLE
Make sure to return 400 when errors are present in the response

### PR DESCRIPTION
**Pull request by atoulme**

### CODE REVIEW

**Review by renaynay — APPROVED** [review]
Running this through hive now, but LGTM.

**Comment by renaynay** [comment]
Looking at the results from hive, this PR fixed a couple of issues geth had with invalid graphQL requests.

**Review by renaynay — APPROVED** [review]
LGTM -- sorry had to double check results from hive. It seems like this solves quite a number of issues geth had serving invalid queries accurately. Thanks!

**Comment by holiman** [comment]
This errors on appveyor, due to it using default chainconfig, which allocates a
large bloom filter.
```
fatal error: out of memory
runtime stack:
runtime.throw(0x1330824, 0xd)
	C:/go/src/runtime/panic.go:1116 +0x64
runtime.largeAlloc(0x20000000, 0x13f60101, 0xcd2cae)
	C:/go/src/runtime/malloc.go:1179 +0x15d
runtime.mallocgc.func1()
	C:/go/src/runtime/malloc.go:1071 +0x39
runtime.systemstack(0x5b6ac8)
	C:/go/src/runtime/asm_386.s:391 +0x53
runtime.mstart()
	C:/go/src/runtime/proc.go:1116
goroutine 152 [running]:
runtime.systemstack_switch()
	C:/go/src/runtime/asm_386.s:352 fp=0x140a1298 sp=0x140a1294 pc=0x872530
runtime.mallocgc(0x20000000, 0x12270a0, 0x1, 0x20)
	C:/go/src/runtime/malloc.go:1070 +0x698 fp=0x140a12e8 sp=0x140a1298 pc=0x81ca48
runtime.makeslice(0x12270a0, 0x4000000, 0x4000000, 0x10)
	C:/go/src/runtime/slice.go:98 +0x4f fp=0x140a12fc sp=0x140a12e8 pc=0x85859f
runtime.makeslice64(0x12270a0, 0x4000000, 0x0, 0x4000000, 0x0, 0x14d9dc0)
	C:/go/src/runtime/slice.go:112 +0x4b fp=0x140a1310 sp=0x140a12fc pc=0x85864b
github.com/steakknife/bloomfilter.newBits(...)
	C:/gopath/pkg/mod/github.com/steakknife/bloomfilter@v0.0.0-20180922174646-6819c0d2a570/new.go:102
github.com/steakknife/bloomfilter.NewWithKeys(0x0, 0x1, 0x1b10a9e0, 0x3, 0x3, 0x819a57, 0x13c0fd2c, 0x34f55178)
	C:/gopath/pkg/mod/github.com/steakknife/bloomfilter@v0.0.0-20180922174646-6819c0d2a570/new.go:82 +0x1f7 fp=0x140a1354 sp=0x140a1310 pc=0xbdd157
github.com/steakknife/bloomfilter.New(0x0, 0x1, 0x3, 0x0, 0x124dcc0, 0x12ff960, 0x34f55178)
	C:/gopath/pkg/mod/github.com/steakknife/bloomfilter@v0.0.0-20180922174646-6819c0d2a570/new.go:34 +0x3d fp=0x140a1378 sp=0x140a1354 pc=0xbdcced
github.com/ethereum/go-ethereum/trie.NewSyncBloom(0x200, 0x0, 0x34f55178, 0x17903670, 0x17903670)
	C:/gopath/src/github.com/ethereum/go-ethereum/trie/sync_bloom.go:72 +0x4a fp=0x140a13bc sp=0x140a1378 pc=0xbf0b0a
github.com/ethereum/go-ethereum/eth.NewProtocolManager(0x1166020, 0x1081b80, 0x1, 0x1, 0x0, 0x14419960, 0x14d6980, 0x1a716b40, 0x14dcaa0, 0x13cc7700, ...)
	C:/gopath/src/github.com/ethereum/go-ethereum/eth/handler.go:154 +0x7de fp=0x140a1430 sp=0x140a13bc pc=0xfcbaee
github.com/ethereum/go-ethereum/eth.New(0x17952a10, 0x1167a40, 0x5, 0x132618d, 0x3)
	C:/gopath/src/github.com/ethereum/go-ethereum/eth/backend.go:198 +0xadc fp=0x140a1ec4 sp=0x140a1430 pc=0xfc6e9c
github.com/ethereum/go-ethereum/graphql.createGQLService(0x13ce4e00, 0x17952a10, 0x1330b95, 0xe)
	C:/gopath/src/github.com/ethereum/go-ethereum/graphql/graphql_test.go:141 +0x2f fp=0x140a1f04 sp=0x140a1ec4 pc=0xff185f
```

Confirming it locally:
```
[user@work graphql]$ go test . -run BadReq  -memprofile=mem.out
ok      github.com/ethereum/go-ethereum/graphql 0.913s
[user@work graphql]$ go tool pprof mem.out
File: graphql.test
Build ID: b624f2b6c57f63c0b77a4b0c21fb297207aaad0d
Type: alloc_space
Time: Nov 25, 2020 at 9:06am (CET)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 562.11MB, 92.11% of 610.28MB total
Dropped 125 nodes (cum <= 3.05MB)
Showing top 10 nodes out of 65
      flat  flat%   sum%        cum   cum%
     512MB 83.90% 83.90%      512MB 83.90%  github.com/steakknife/bloomfilter.newBits
      11MB  1.80% 85.70%       11MB  1.80%  github.com/ethereum/go-ethereum/trie.(*fullNode).copy (inline)
    8.92MB  1.46% 87.16%     8.92MB  1.46%  github.com/ethereum/go-ethereum/ethdb/memorydb.(*batch).Write
    7.34MB  1.20% 88.36%     7.34MB  1.20%  github.com/ethereum/go-ethereum/ethdb/memorydb.(*batch).Put
       5MB  0.82% 89.18%        5MB  0.82%  golang.org/x/crypto/sha3.NewLegacyKeccak256 (inline)
```

I pushed a change to use a differnet config. With the last change:
```
[user@work graphql]$ go test . -run BadReq  -memprofile=mem2.out
ok      github.com/ethereum/go-ethereum/graphql 0.597s
[user@work graphql]$ go tool pprof mem2.out
File: graphql.test
Build ID: f7e554b31e02120246f43bdca6dd675fda5c13f2
Type: alloc_space
Time: Nov 25, 2020 at 9:08am (CET)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 2983.03kB, 100% of 2983.03kB total
Showing top 10 nodes out of 29
      flat  flat%   sum%        cum   cum%
 1056.33kB 35.41% 35.41%  1056.33kB 35.41%  strings.genSplit
  902.59kB 30.26% 65.67%   902.59kB 30.26%  compress/flate.NewWriter
  512.08kB 17.17% 82.84%   512.08kB 17.17%  regexp.compile
  512.03kB 17.16%   100%   512.03kB 17.16%  github.com/ethereum/go-ethereum/core/vm.newFrontierInstructionSet
```

**Review by holiman — APPROVED** [review]
LGTM, will merge on green

**Pull request merged**
