### PR TITLE
les, eth: fix typo in comment

### PR DESCRIPTION
**Pull request by ucwong**

### CODE REVIEW

**Comment by bionics-maestro** [comment]
Hi! Who will approve your pull request? Ethereum is decentralized. Please tell me and don't ignore me. I am a beginner developer learning new things.

**Comment by bionics-maestro** [comment]
Hi! Who will approve your pull request? Ethereum is decentralized. Please tell me and don't ignore me. I am beginner developer learning new things.

**Comment by Shaft-3796** [comment]
> Hi! Who will approve your pull request? Ethereum is decentralized. Please tell me and don't ignore me. I am beginner developer learning new things.

Hi, even if Ethereum is decentralized, the approval system for pull requests works the same than for any github repository, collaborators can approve it. However, the nodes running on Geth decides if they update their node or if they stay with an older version, this is how blockchain forks happen, some nodes update, some don't. This repository provide an official implementation of the Ethereum protocol, but every node is free to run any correct implementation of the protocol.

Hope I was clear : )

**Comment by bionics-maestro** [comment]
> > Hi! Who will approve your pull request? Ethereum is decentralized. Please tell me and don't ignore me. I am beginner developer learning new things.
> 
> Hi, even if Ethereum is decentralized, the approval system for pull requests works the same than for any github repository, collaborators can approve it. However, the nodes running on Geth decides if they update their node or if they stay with an older version, this is how blockchain forks happen, some nodes update, some don't. This repository provide an official implementation of the Ethereum protocol, but every node is free to run any correct implementation of the protocol.
> 
> Hope I was clear : )

Can anyone become collaborator to approve pull request in this repository?

**Comment by panicalways** [comment]
Contact the Ethereum Foundation. @bionics-maestro

**Review by holiman — CHANGES_REQUESTED** [review]
Thanks, but this is a copy of `eth/api.go`, where these same typos are also present. Wanna fix those too while you're at it ?

**Review by rjl493456442 — APPROVED** [review]

**Pull request merged**
