### PR TITLE
swarm/network: rewrite 

### PR DESCRIPTION
**Pull request by zelig**
This PR is in progress. Builds on top of #3102 and reimplements the base bzz protocol using p2p/protocols, hive and kademlia connectivity management.
Includes unit tests and connectivity tests using p2p/simulations

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 186849d81d4c78c18d1fc6e602acf2489cd2d6e7
  * Your commit message body contains a line that is longer than 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 15b8c39f9603dd8c4f2bd37960273c9acf4d7089
  * Your commit message body contains a line that is longer than 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 15b8c39f9603dd8c4f2bd37960273c9acf4d7089
  * Your commit message body contains a line that is longer than 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 15b8c39f9603dd8c4f2bd37960273c9acf4d7089
  * Your commit message body contains a line that is longer than 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by fjl** [comment]
@zelig please resubmit when you're done

**Pull request closed without merging**
