### PR TITLE
cmd/geth: enhance account output

### PR DESCRIPTION
**Pull request by MaximilianMeister**
* enhance the format of the account list output to specify the fields
  (index, address, file)
* also output the same format when creating a new account

### CODE REVIEW

**Comment by karalabe** [comment]
What is the rational behind changing `Account #0: {0x...}` to `Index: 0, Account: {0x...}`?

I don't have anything in particular against either format, but the former seems much more condensed to me, so I'm curious what would prompt someone to want the second form.

**Comment by MaximilianMeister** [comment]
> What is the rational behind changing Account #0: {0x...} to Index: 0, Account: {0x...}?

I probably could have added it to the commit message... I think it enhances readability a bit, for both human and machine, as it may also be easier consumable from scripts that don't talk to the api directly, and just use `geth` to get to some index, file or account address

> I don't have anything in particular against either format, but the former seems much more condensed to me, so I'm curious what would prompt someone to want the second form.

sure it is more condensed, but IMO output from a cli can be descriptive and doesn't really need to be condensed.

**Comment by fjl** [comment]
I'm unsure about this change. geth account output is already pretty long because it contains the full path to the file. This just makes it longer. IMHO it's pretty clear that `#0`, `#1`, ... are the index numbers of the accounts.

**Comment by fjl** [comment]
Sorry, I'm closing this because we have doubts about the merits of this change. geth account output has been stable for a long time (the last change added the file name), so who knows what might break
if we change it. Thanks for your effort nonetheless!

**Pull request closed without merging**
