### PR TITLE
miner: gas limit strategy, target 3141592 & def gas price 50 Shannon

### PR DESCRIPTION
**Pull request by Gustav-Simonsson**

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Mon Aug 3 11:05:33 UTC 2015_

**Comment by obscuren** [comment]
:+1:

**Comment by Gustav-Simonsson** [comment]
@fjl @karalabe saw you guys discussed accounts test timeout before - know anything about the failing test?

**Comment by obscuren** [comment]
@Gustav-Simonsson could you try to rebase and try again? I merged in a test that should get rid of one pesky failed test

**Comment by obscuren** [comment]
Squash please

**Comment by zsfelfoldi** [comment]
Default gpomax is 100 shannon here, I still think that should be raised. At least to 500 shannon imho.

**Comment by alexvandesande** [comment]
:shipit:

**Comment by fjl** [comment]
:+1:

**Comment by obscuren** [comment]
:trollface:

**Pull request merged**
