### PR TITLE
cmd/devp2p: update eth/snap protocol test suites for PoS

### PR DESCRIPTION
**Pull request by lightclient**
It looks like the eth-test suite has been kinda broken for a while now. This PR tries to do a minimal fixup to extend the life of the suite so we can add some tests for blob propagation. Main additions

* updated the genesis and `chain.rlp` to be post-merge
* added `dialEngine(..)` which creates an RPC client into the specified engine url
* replaced `sendNextBlock(..)` with `sendForkchoiceUpdated(..)` in the tx propagation tests to kick the target client out of sync and to start accepting txs
* some misc. changes to the global nonce to get things passing again (this part is wonky)

The current design is kind finicky. A ton of assumptions are baked into the code based on the `chain.rlp`. It would be much better if we could read the chain and generate the tests based on that instead. ~~I understand Felix is working on something sort of like this with `hivechain`, so I will wait until that is ready to do a more comprehensive update to this testing suite.~~

--

update 2023-10-30: integrated the new hivechain chain into these tests and added some tests checking protocol violations w.r.t. blobs.

### CODE REVIEW

**Comment by fjl** [comment]
I'm adding hive support in https://github.com/ethereum/hive/pull/942 but have a hard time making other clients accept the test chain.

**Review by fjl — APPROVED** [review]

**Comment by fjl** [comment]
@lightclient this is basically ready now

**Comment by fjl** [comment]
Hmm, so when I run the snap tests on hive against Geth, I get this failure:

```
 -- Test 4
 In this test, we request the genesis block state root node. The server should respond with the node.
   request:
     root: 17fa928a94db88a7959927626d9bb0c82d28710e59aa91c0eaa12b33e303fd52
     paths: [[00] [01 00]]
     responseBytes: 5000
   failed: wrong trienode count, got 0, want 1
 ```

**Comment by holiman** [comment]
> In this test, we request the genesis block state root node. The server should respond with the node.

I believe that this is more of an assumption that an important pillar of snap-sync. Retaining the genesis-state for snap-serving is not mandatory.

**Pull request merged**
