### PR TITLE
[website] Overflow with scroll on the table of index

### PR DESCRIPTION
**Pull request by wackerow**
[PR migrated from now-deprecated `geth-website` repo](https://github.com/ethereum/geth-website/pull/187)

Fixes: #26426

### CODE REVIEW

**Comment by holiman** [comment]
Marked as draft still... Want it merged or time to close it?

**Comment by holiman** [comment]
Ping @wackerow please undraft or close

**Comment by wackerow** [comment]
Thanks for the ping @holiman.. @corwintines, this was ported over from `geth-website`, previously under your name. Do you know if there is any progress on this? If not, agree we should just close and can address when ready.

**Comment by holiman** [comment]
Poked and prodded, seems ded to me :)

**Pull request closed without merging**
