### PR TITLE
Change go-uuid to use the current supported repository.

### PR DESCRIPTION
**Pull request by jeffallen**

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Thu Sep 10 17:39:52 UTC 2015_

**Comment by fjl** [comment]
:+1:

**Comment by karalabe** [comment]
Please remove the old files from Godeps if moving to a new repository.

**Comment by karalabe** [comment]
Just to make sure it's not merged leaving in the old junk, :-1: to mark the issue until fixed :)

**Comment by karalabe** [comment]
LGTM :+1:

**Pull request merged**
