### PR TITLE
allow empty string passwords for unlocking account

### PR DESCRIPTION
**Pull request by almindor**
Fixes issue #1699

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Wed Aug 26 00:27:05 UTC 2015_

**Comment by karalabe** [comment]
:-1: I don't think this complexity (adding a new field) is warranted. If no password was provided, then it should be caught by the `not enough arguments` check (https://github.com/ethereum/go-ethereum/pull/1719/files#diff-75a66eb98fca46aea749aa6fc99c6316R93). IMHO that should be bumped to check for 2 args (account + password). Then we can assume that the `Passphrase` is always valid, but maybe empty (which is valid), thus we can remove completely the check for `len(Passphrase)`.

What do you think @bas-vk ?

**Comment by maran** [comment]
What would happen if we decide to try unlocking with an empty password first and only ask for the password if that fails? If you decide to not have a password you probably aren't too concerned about security anyway so doing unattended unlocks might be useful there.

**Comment by Gustav-Simonsson** [comment]
We'll go with https://github.com/ethereum/go-ethereum/pull/1739

**Pull request closed without merging**
