### PR TITLE
go.mod : go-nat-pmp v1.0.2

### PR DESCRIPTION
**Pull request by ucwong**
including timeout customized added
https://github.com/jackpal/go-nat-pmp/commit/5d7eea0e53b70d7c2d7320ccf7aa275ec318be71

### CODE REVIEW

**Review by misamoo — APPROVED** [review]
e

**Review by misamoo — APPROVED** [review]
e

**Review by karalabe — APPROVED** [review]
SGTM, thanks!

**Review by arslan-raza-143 — COMMENTED** [review]
@karalabe

**Comment by arslan-raza-143** [comment]
> including timeout customized added
> 
> https://github.com/jackpal/go-nat-pmp/commit/5d7eea0e53b70d7c2d7320ccf7aa275ec318be71

**Pull request merged**
