### PR TITLE
Add function to find event by log topic (aka. id)

### PR DESCRIPTION
**Pull request by tranvictor**
One of the use case for `abi package` is to parse transaction receipt that leads to parsing the tx data to see all of the parameters and event logs to see all of the relevant information in a readable way.

A method can be found using `MethodById` yet there is no equivalent function to find an event according to its id or the topic extracted from the event logs.

In this PR, I propose that method.

### CODE REVIEW

**Comment by gballet** [comment]
Please add some unit tests like in `TestABI_MethodById`

**Comment by tranvictor** [comment]
@gballet Sure, I will add the tests in next few days.

**Comment by tranvictor** [comment]
@gballet so I added the test, however, I mistakenly upgraded the vendors and it made the PR so messy. Should I close this one and make another PR?

**Comment by gballet** [comment]
@tranvictor no worries, as it turns out someone else has made a similar PR (#19359) so I have added your work on top of theirs. You both get attribution for your work, of course.

**Pull request closed without merging**
