### PR TITLE
graphql: fixes missing tx logs

### LINKED ISSUE #25583: GraphQL/JSON-RPC logs regression between 1.10.21 & 1.10.22
#### System information

Geth
Version: 1.10.22-stable
Git Commit: 2de49b04e56cf07f011d6d91f9d5c08847aabe8e
Architecture: amd64
Go Version: go1.18.5
Operating System: linux
GOPATH=
GOROOT=go

Archive node

#### Expected behaviour

Doing a complex GraphQL query returns correct data from a block, like in 1.10.21

#### Actual behaviour

Too much data (logs unrelated to current block)

#### Steps to reproduce the behaviour

Going to GraphQL UI : http://xxxxx:8545/graphql/ui

Type the following query :

```
{
  block(number: 15401505) {
    number
    transactions {
      logs {
        account {
          address
        }
      }
    }
  }
}

```

#### More details

That block on etherscan : https://etherscan.io/block/15401505

On a 1.10.22 node, this query returns 257386 lines, which is a bit too much (could depend on when you run the request)
On a 1.10.21 node, this query returns 2209 lines, which seems more in the norm

### PR DESCRIPTION
**Pull request by s1na**
Fixes #25583 (for a second time, hopefully last time 😄)

### CODE REVIEW

**Review by fjl — APPROVED** [review]
LGTM

**Review by MariusVanDerWijden — APPROVED** [review]
Ssssgtm

**Comment by SLoeuillet** [comment]
Thanks
Testing it now

**Comment by donatocayurin** [comment]
Thank you ❤️🙏

**Comment by donatocayurin** [comment]
❤️🙏

**Pull request merged**
