### PR TITLE
Fix sync crash for nil pointer about fast sync td

### PR DESCRIPTION
**Pull request by ucwong**

### CODE REVIEW

**Comment by karalabe** [comment]
I don't understand these changes you are making. These cannot happen. You can't be missing a TD from the database for your head block. Are you seeing an issue where this genuinely triggers? Can you reproduce it? Can you show us some logs?

**Comment by ucwong** [comment]
After running removedb delete the chaindata except the ancient data, then start the node again
image
the fast td is nil

**Comment by ucwong** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xaf5386]

goroutine 40506 [running]:
math/big.(*Int).Cmp(0x0, 0xc0413897e0, 0x6d00de887c688716)
	/usr/local/go/src/math/big/int.go:326 +0x26
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).synchronise(0xc00016c1e0, 0xc037e4a3c0)
	/root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:185 +0x28a
created by github.com/ethereum/go-ethereum/eth.(*ProtocolManager).syncer
	/root/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:151 +0x269

**Comment by rjl493456442** [comment]
I just try to case you described, remove chaindata via `geth removedb` but keep the ancient dir and restart.
But nothing special happens.

**Comment by ucwong** [comment]
@rjl493456442 what is the fast block td when u start the node again after removedb, the td is nil in my action

**Comment by ucwong** [comment]
merge the latest code of blockchain.go it never happend.
Thank you very much for your reply, @karalabe @rjl493456442 , I will close the pr

**Pull request closed without merging**
