### PR TITLE
Mutexfree chain stats

### PR DESCRIPTION
**Pull request by holiman**
Work in progress, todo

- [x] Documentation
- [x] Proper testing
- [x] Possibly refactor

### CODE REVIEW

**Comment by holiman** [comment]
TODO: Make the ones returning `uint64`not use bigints internally.

**Comment by holiman** [comment]
@karalabe PTAL. I've merged the setters, however, there are a couple of places where they are not all called simultaneously. 

In `FastSyncCommitHead`, we only set `currentBlock` but not `currentFastBlock` : https://github.com/ethereum/go-ethereum/pull/15980/files#diff-30184e52dfee0fbd0ba21f92638b2ec1R309

In `InsertReceiptChain` we only set `currentFastBlock`, but not `currentBlock`; https://github.com/ethereum/go-ethereum/pull/15980/files#diff-30184e52dfee0fbd0ba21f92638b2ec1R803

**Comment by holiman** [comment]
Rebased on master

**Comment by karalabe** [comment]
@holiman Downloader tests fail to compile.

**Comment by holiman** [comment]
Hoping appveyor turns 💚 now

**Comment by holiman** [comment]
Rebased on master. I'd rather get 1.8.0 out than get this squeezed in

**Comment by fjl** [comment]
I don't get why we need a separate package for this struct.

**Comment by holiman** [comment]
> I don't get why we need a separate package for this struct.

We don't _need_ it, but I thought it was cleaner to do it that way. One thing I dislike is when packages grow too big, and there are various mutexes all over the place and various private methods being called. I think it's better to encapsulate packages that _can_ be packaged, and expose only those things which should be exposed.

**Comment by holiman** [comment]
Primarily, I didn't want anyone to start reaching directly in to the numbers and fiddle with them. As it is now, you cannot possibly read or write them the 'wrong' way, they can only be accessed 'correctly' via `atomic`

**Comment by karalabe** [comment]
Ah, hmm. Creating an entire package does feel weird. Especially a non-internal one. I would also just drop into into `core`, but I do agree with @holiman that `core` grew into a little monster already.

**Comment by holiman** [comment]
Well, I'm not as familiar with The Go Way as you guys are... I see it as a good thing to modularize things to keep interfaces clean. Is there some other way of achieving the same effect other than a "package"? Why do you call it "an entire package" -- it's just a folder, right? I don't understand why there would be any gains in not separating stuff.

**Comment by holiman** [comment]
Could you guys @karalabe @fjl LMK how you want it to be? I'd like to merge this

**Comment by karalabe** [comment]
So, my suggestion are:

 * Don't put this in a separate package. It's a tiny internal implementation detail of `core.BlockChain`.
 * I don't see a value to make the type public, nor to return it. It messes up interfaces when the same thing can be retrieved multiple ways (that's why I removed the redundancy in the first place).
 * Since we can already retrieve the latest block / latest header, I think it might be more reasonable to save those into this new struct via `atomic.Value`, and return those. Then all current interfaces work. Otherwise calling code still needs to know that `chain.CurrentBlock().Number()` will block, but `chain.Status().CurrentBlock()` will not. It's just a ambiguous API (and in general any API that lets you do the same thing multiple ways).

**Comment by holiman** [comment]
Hm. So just use `atomic.Value` around the actual `currentBlock` / `currentFastBlock` instead? Yeah that'll work.

**Comment by holiman** [comment]
Closed in favour of https://github.com/ethereum/go-ethereum/pull/16171

**Pull request closed without merging**
