### PR TITLE
signer/core/apitypes: deep convert types in slice

### PR DESCRIPTION
**Pull request by 6xiaowu9**
Hey, @holiman 

Golang version: v1.19
go-ethereum version: v1.10.25

I have a problem doing EIP712 signature with parameter type `uint256[]`

It's like this issue: 
https://github.com/ethereum/go-ethereum/issues/23335#issue-961626333

When the input type is a slice of the internal required type, for example: 
`[]string`,`[]*math.HexOrDecimal256`...

The following line of code will not pass the type when performing type assertion, unless the user encapsulates it in `[]interface{}` before calling
```go
arrayValue, ok:=encValue.([]interface{})
```

Reference documentation: https://github.com/golang/go/wiki/InterfaceSlice

So I processed this code, using reflection to assert whether the value is a slice, process and return the required slice

### CODE REVIEW

**Comment by holiman** [comment]
@fjl ptal?

**Comment by MariusVanDerWijden** [comment]
@6xiaowu9 The idea looks good to me, using reflect is always a bit iffy. Could you add a test for it please?

**Comment by 6xiaowu9** [comment]
@MariusVanDerWijden Hi, I've added a couple of tests for the commonly used (`[]uint256`, `[]address`, `[]string`) types to it.

**Comment by 6xiaowu9** [comment]
@holiman @fjl  PTAL?

**Review by holiman — APPROVED** [review]
LGTM

**Pull request merged**
