### PR TITLE
Use MySQL as external db for geth

### PR DESCRIPTION
**Pull request by markya0616**
In current design, we use level db to store state data in local disk. The state db can not be shared among geths. Some geths are synced to latest block, but some geths are not. It may cause you get different results from different geth. If we have a central state db such as MySQL, all geth can share the same state. Also, for a new geth, it can join the network quickly because it don't need to sync data again.

### CODE REVIEW

**Comment by karalabe** [comment]
Hmm, could you detail why this is useful a bit? Do you see any performance improvements? Any infos would really help figure this out properly :)

**Comment by markya0616** [comment]
OK. In current design, we use level db to store state data in local disk. The state db can not be shared among geths. Some geths are synced to latest block, but some geths are not. It may cause you get different results from different geth. If we have a central state db such as MySQL, all geth can share the same state. Also, for a new geth, it can join the network quickly because it don't need to sync data again.

**Comment by ligi** [comment]
@markya0616 can you elaborate on your use-case a bit more? Are you talking about multiple geth's on the same machine? Somehow this solution feels wrong - but it would be good to know what exactly your problem is.

**Comment by markya0616** [comment]
@ligi No, we will hope to run a multiple geth on different machine and want them to share the same state db. In our side, we need to run a geth cluster to ensure the system liveness, but we encounter that their state db is not consistent. Some are synced, but some are not. If there is a central db for all geth, it will solve this problem. After that, we can also analysis these data for further applications.

**Comment by ligi** [comment]
What are your nodes used for? Have you looked into solutions like https://github.com/MyCryptoHQ/shepherd?

**Comment by siong1987** [comment]
i am doing some work on comparing the performance of leveldb and badger here: #15717.

wonder it makes sense to have a plugin-like system to support different DB instead of putting the code as part of the main repo.

@markya0616 how does it make sure that different geth instances won't compete to write to the DB? transaction?

**Comment by karalabe** [comment]
And what happens during a database upgrade and/or eventual pruning when stuff starts to get deleted from the database? Or fast sync, which operates based on the existing content of the database. Geth internally always had the invariant that noone else pokes in its database at the same time. I'm not sure things won't go belly up if all of a sudden many processed modify the data.

**Comment by ekryski** [comment]
I'm with @karalabe here. You likely shouldn't have more than one Geth process writing to the same DB. If that's the case they'll have to support ACID transactions so that you don't end up with conflicting writes. Having read/write locks may end up being even slower to sync than the current setup.

A blockchain really is just a fancy database so we should be taking similar approach to other DBs, where there is a master that writes and slaves that can operate on the same DB in read-only mode, or you take a sharded replication approach more like MongoDB, RethinkDB, etc. This will allow you to run a high availability setup (ie. multiple Geth nodes). Currently the only way this is possible is if you run multiple distinct Geth nodes and load balance across them and hope they are all at the same sync state.

So all that to say, I don't think it's quite as simple as making MySQL the database instead of LevelDB. I think we could stick with LevelDB (or some faster database) but Geth needs to be able to run in a read-only mode.

**Comment by siong1987** [comment]
> Geth needs to be able to run in a read-only mode.

@ekryski is this possible today?

**Comment by ekryski** [comment]
> @ekryski is this possible today?

@siong1987 Not as far as I'm aware. If it is possible and someone knows pass on that sweet knowledge. Happy to help document it.

> The sync speed may be different according to your node, network, and so on. If there is only "one" master, the sync state may be slower than others. That's why we want to have multiple geth to write.

@markya0616 Totally. I think I had mentioned that in my same comment. 😄

The issue with having multiple nodes write is that you will likely make the problem of nodes being out of sync worse. How do you decide which node is "correct"? Which update should be respected? That whole problem is the reason each node has its own DB right now. You don't have to worry about write consistency and order because that's already handled at the node level between all it's peers. Otherwise you'll be replicating everything the blockchain nodes already do with the public blockchain, but for a private group of nodes for DB writes (ie. broadcasting transactions, coming to consensus, etc.).

It's probably better to either have each node have it's own DB and have some proxy/load balancing layer outside of Geth that determines who is the most up to date and ready to handle requests **or** have a master node that has the best connection, lowest latency, most memory, etc. to make it the fastest possible. Then your read-only nodes don't need to have so many resources.

In reality, you need both of those things.

**Comment by duanbing** [comment]
Who will maintain the Mysql cluster do you think  if we publish a public blockchain?

**Comment by karalabe** [comment]
My 2c on this PR is that at least with the current code, Geth will not be able to use a distributed database, since it invalidates internal invariants about the order of events and the content of the database. Also Geth assumes that it has sole access to the db, so if it checks a data entry and it doesn't write anything out, it assumes the same state holds. This breaks in the distributed database model.

Just for the sake of enabling distributed databases, I don't think this PR is in its current form reliable enough to warrant inclusion. That said, I'd be curious of the single node performance compared to leveldb. My hunch is that it's slower, but we could use performance metrics to make a case for the PR.

So, anyone willing to do some performance benchmarks of leveldb vs. mysql? And perhaps some sanity runs of syncing maybe 5 nodes backed by the same distributed db (my hunch is that it will break hard)? That would be a better starting point than arguing theoretics :)

**Comment by deckarep** [comment]
Wow, this seems like a really bad idea...Geth requires exclusive access to its own database. Additionally relational dbs and lsm dbs are two entirely different beasts...I’m quite sure trying to sync the full db would choke MySQL...even before mutations on it occur.

**Comment by AFDudley** [comment]
You probably want to have a different architecture to support your use case. We are working on addressing these state issues with https://github.com/vulcanize/vulcanizedb

You're welcome to chat with us about it here: https://gitter.im/vulcanizeio/VulcanizeDB

**Comment by hermanjunge** [comment]
Hey. I have a use case where I need to have all the state and storage trie nodes in a clusterizable DB (as to support 200MM of keys being queried by multiple parties, and then make the data available over different networks, such as *libp2p*.

Haven't code a single line on that particular yet, but I think it reduces to two elements:

a) Have a hook on `Put()` in `ethdb`, and forward a call to the clusterizable DB (or an agent running next the client).

b) Coding a function to return you a subset of the trie (i.e. a walk from an *arbitrary hash* down *n* levels. And being able to expose this function to return the values in Hex using the RPC. (This is to recolect past data)

@karalabe Do you have any thoughts on that? I know it escapes a bit of the purview of the core team, but I would like to pick your brain on the most economical (and kosher) way to export data from the go-ethereum client, without needing to destroy its natural flow.

**Comment by holiman** [comment]
There is work ongoing (openrelay) to set up geth in a master-slave relationship with other geth instances, which should cover this usecae.

**Comment by karalabe** [comment]
We can possibly revisit extending with different databases if Geth has read only mode eventually implemented, until then however MySQL support doesn't bring anything useful to the table, neither performance nor distribution wise.

**Pull request closed without merging**
