### PR TITLE
core, core/vm, core/state: remove unused functions

### PR DESCRIPTION
**Pull request by Gustav-Simonsson**

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Thu Sep 10 14:29:21 UTC 2015_

**Comment by fjl** [comment]
Commit message should be `core, core/vm, core/state: ...`.

**Comment by Gustav-Simonsson** [comment]
@fjl Fixed

**Comment by fjl** [comment]
:+1:

**Comment by obscuren** [comment]
:+1:

**Pull request merged**
