### PR TITLE
params: set goerli TTD to 10_790_000

### PR DESCRIPTION
**Pull request by MariusVanDerWijden**
Sets the TTD for the goerli/prater merge to 10,790,000 as specified in https://github.com/ethereum/execution-specs/pull/563

### CODE REVIEW

**Review by holiman — APPROVED** [review]
LGTM. 
Does this need an accompanying change in the forkid tests or nah?

**Comment by MariusVanDerWijden** [comment]
Nah, no forkid changes

**Comment by chrishobcroft** [comment]
What is blocking the merge?

Some test is failing: https://ci.appveyor.com/project/ethereum/go-ethereum/builds/44203058

Also funny how it says merging is blocked:

image

**Comment by MariusVanDerWijden** [comment]
Nothing blocking it, I just need someone from the team to push the merge button. The failing test is just a flakey test and has nothing to do with this change. You are not authorized to merge it, only the team can do it (I can't because of the flakey test, need someone with higher privileges to push the button)

**Comment by chrishobcroft** [comment]
What is a "flakey" test?

**Review by Tetita — APPROVED** [review]

**Pull request merged**
