### PR TITLE
p2p, p2p/discover: small fixes 

### LINKED ISSUE #1579: Low peers: UDP use of closed network connection
Not sure if this is a separate issue from other low peer problems but here it is. I can't get more than ~3 peers now. Deleting nodekey, the nodes dir, or trying various flags hasn't helped. I was often maintaining 20-50 nodes during olympic.

Here is a log with lots of "use of closed network connection" alerts:

https://gist.github.com/TalkingAntColony/eade156c0bd0b84f6823

Here is my current startup flags:

geth --genesis genesis_block.json --rpc --rpcaddr localhost --rpcport "8545" --nat extip:71.225.210.78 --maxpeers "100" console 2>C:\Ethereum\geth_log.txt

Platform is Windows 8.1, high performance machine, high speed internet.

### PR DESCRIPTION
**Pull request by fjl**
This PR should resolve #1579 and other minor errors.

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Wed Aug 19 12:55:21 UTC 2015_

**Comment by karalabe** [comment]
What can cause temporary read/accept errors?

**Comment by fjl** [comment]
I don't know for sure, but cannot find any other explanation for the linked issue.

**Comment by obscuren** [comment]
:+1:

**Comment by tgerring** [comment]
:+1:

**Pull request merged**
