### PR TITLE
contracts/ens: Replace setOwner with setSubnodeOwner per EIP137

### PR DESCRIPTION
**Pull request by Arachnid**

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Wed Aug 31 16:33:56 UTC 2016_

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 8fe3d376c6e24ac356da48b5803a2f6961776871
  * Commit subjects should be kept under 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by fjl** [comment]
Please use solc v0.3.6 and abigen from develop branch to regenerate

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 3505848a73fba4198dd68424e816170827c406f3
  * Commit subjects should be kept under 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by Arachnid** [comment]
> Please use solc v0.3.6

I did!

> and abigen from develop branch

I've rebuilt my abigen and pushed again.

**Comment by fjl** [comment]
Hmm, weird. I cannot reproduce the bytecode.

```text
~ >> solc --version
solc, the solidity compiler commandline interface
Version: 0.3.6-988fe5e5/.-Darwin/appleclang
```

**Comment by Arachnid** [comment]
It appears I was using head:

> Version: 0.3.6-develop.2016.08.31+commit.3ccd1986.Darwin.appleclang

I'll regenerated off a release.

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: a386b4c9837cd6c21b9581cbd94a076665961c67
  * Commit subjects should be kept under 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by fjl** [comment]
Thanks. Verified.

**Pull request merged**
