### PR TITLE
Update Prysm's link -> point to the Quickstart that includes Geth config instructions

### PR DESCRIPTION
**Pull request by mick-prysm**
A proposed link update that gets users one click closer to the steps they need to take to configure Prysm with Geth :)

### CODE REVIEW

**Review by MariusVanDerWijden — APPROVED** [review]
LGTM

**Review by s1na — APPROVED** [review]
Thanks

**Comment by mick-prysm** [comment]
Thanks @MariusVanDerWijden @s1na - PS I'd be more than happy to support you on the docs front if you ever need a content pressure release / second set of eyes! I'm mick#6078 on Discord :)

cc @kasey to close the loop on your linkfix suggestion 🙏

**Comment by mohammadfarari1360** [comment]
Good

**Comment by s1na** [comment]
@mick-prysm our docs could always use more support, your offer is appreciated. Please see https://github.com/ethereum/go-ethereum/issues/20260 for some ideas if you ever had some time to spare.

**Pull request merged**
