### PR TITLE
SECURITY.md: link to release page

### PR DESCRIPTION
**Pull request by suriyaa**
Add links to go-ethereum's GitHub release page.

### CODE REVIEW

**Review by holiman — COMMENTED** [review]
We should also add links to the security vulnerability disclosure page ( https://github.com/ethereum/go-ethereum/security/advisories?state=published ) , and mention the `geth version-check` feature

**Comment by suriyaa** [comment]
@holiman Done. ✅

**Review by DGKSK8LIFE — COMMENTED** [review]
well done

**Review by suriyaa — COMMENTED** [review]
@fjl Thank you for correcting it. :+1:

**Pull request merged**
