### PR TITLE
RPC HTTPS

### PR DESCRIPTION
**Pull request by iFA88**
Geth should accept secure connection on RPC socket.
While using Đapp from a secured website the browser deny the connection until i allow it in the website details.

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Wed Jun 15 09:03:25 UTC 2016_

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 6826b2040f0d5eaebad8b68eb46bd2b738eef3fc
  * Commit subjects should be kept under 80 characters

 * Commit: 2e6b9c141bf2b7e0c555dfeaad2147cf96b08974
  * Commit subjects should be kept under 80 characters

 * Commit: 594328c1121f997748cc5fe87f493db94827e1ec
  * Commit subjects should be kept under 80 characters

 * Commit: efcfa2209babc5b23dde75592048194238c1e1d5
  * Commit subjects should be kept under 80 characters

 * Commit: 8ea3c88e444d774bc5921b51e30715494c52f713
  * Commits must be prefixed with the package(s) they modify

 * Commit: b950a2977c6d74c9150fd37b7cf7fb20c762baf7
  * Commit subjects should be kept under 80 characters

 * Commit: 7a7a5acc9ffee60ea838c8374741dad8e79e59ef
  * Commit subjects should be kept under 80 characters

 * Commit: 1776c717bfb540f95e1b2233f35ea6f4cc8f57d5
  * Commit subjects should be kept under 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by karalabe** [comment]
Please do code modifications based on the `develop` branch. Otherwise you're pulling in all the cherry picked hotfixes from the stable releases (i.e. the above huge commit log).

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 6826b2040f0d5eaebad8b68eb46bd2b738eef3fc
  * Commit subjects should be kept under 80 characters

 * Commit: 2e6b9c141bf2b7e0c555dfeaad2147cf96b08974
  * Commit subjects should be kept under 80 characters

 * Commit: 594328c1121f997748cc5fe87f493db94827e1ec
  * Commit subjects should be kept under 80 characters

 * Commit: efcfa2209babc5b23dde75592048194238c1e1d5
  * Commit subjects should be kept under 80 characters

 * Commit: 8ea3c88e444d774bc5921b51e30715494c52f713
  * Commits must be prefixed with the package(s) they modify

 * Commit: b950a2977c6d74c9150fd37b7cf7fb20c762baf7
  * Commit subjects should be kept under 80 characters

 * Commit: 7a7a5acc9ffee60ea838c8374741dad8e79e59ef
  * Commit subjects should be kept under 80 characters

 * Commit: 1776c717bfb540f95e1b2233f35ea6f4cc8f57d5
  * Commit subjects should be kept under 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Pull request closed without merging**
