### PR TITLE
cmd/geth, eth/downloader: collect and report import progress too

### PR DESCRIPTION
**Pull request by karalabe**
Currently it's difficult to track how the import is progressing because even though `admin.progress()` surfaces the download progress, it does not have any information about the import progress. I have no means to check how much out of those potentially 1024 blocks the importer crunched through.

This PR aims to fix that by surfacing an additional number, the still in-progress block imports. This is done by the downloader maintaining a list of recently taken blocks, and checking how many of those have not yet been imported (i.e. not found in the chain) whenever `Stats()` are requested.

So now we have something more useful to watch:

```javascript
> admin.progress()
{
  cached: 1024,
  importing: 155,
  pending: 17000
}
> admin.progress()
{
  cached: 1024,
  importing: 55,
  pending: 17000
}
I0610 01:16:02.493558   17673 chain_manager.go:686] imported 251 block(s) (0 queued 0 ignored) in 7.980843992s. #536696 [b126eea6 / 066ead6d]
> admin.progress()
{
  cached: 965,
  importing: 897,
  pending: 16035
}
I0610 01:16:10.394021   17673 chain_manager.go:686] imported 256 block(s) (0 queued 0 ignored) in 7.703510153s. #536952 [cc7d28d1 / 806269fd]
> admin.progress()
{
  cached: 1024,
  importing: 725,
  pending: 15976
}
```

There may still be some corner cases.

### CODE REVIEW

**Comment by karalabe** [comment]
Added ETA too:

```javascript
> admin.progress()
{
  cached: 406,
  estimate: '3m59.319902793s',
  importing: 313,
  pending: 0
}
> I0610 18:01:03.473822    8754 chain_manager.go:686] imported 256 block(s) (0 queued 0 ignored) in 1m51.73506812s. #560781 [e267e8c0 / db93fd03]
> admin.progress()
{
  cached: 406,
  estimate: '3m1.41722212s',
  importing: 99,
  pending: 0
}
```

**Comment by karalabe** [comment]
Round the ETA to seconds, the rest is just unneeded data.

```javascript
> admin.progress()
{
  cached: 488,
  estimate: '12m31s',
  importing: 973,
  pending: 0
}
```

**Comment by obscuren** [comment]
Isn't this a bit overkill for just getting an approximate time? Especially the `TakeBlocks` method.

**Comment by karalabe** [comment]
Actually, come to think of it you're right that we don't need to flesh out the hashes individually. I can just save a copy of the retrieved blocks array too.

The reason I don't think this is an overkill is because a lot of people were whining that sync is stopped, downloader doesn't work, it hangs... then it turns out that no... you're just importing. Along the same lines, when importing 256 blocks takes 7+ minutes on my machine, it's really annoying to not be able to see any status at all and just *hope* it will finish soon. This was my rational behind this PR. If you feel it's useless I can abandon it, but I think it doesn't complicate things much and it's a useful detail to surface.

**Comment by karalabe** [comment]
That however would lead to a data race since block.Hash() is not thread safe, so I cannot freely call it after it's returned by TakeBlocks. So I still think this is the cleanest solution for this problem. The question is whether there **is** a problem to solve or not?

**Comment by fjl** [comment]
block.Hash is safe for concurrent use if you don't modify the block.

**Comment by karalabe** [comment]
Hmmm... I thought that blocks cache their hashes. Wouldn't that be a useful addition? Because we are calling Hash() on a block probably multiple times over its lifetime.

**Comment by fjl** [comment]
I am working on a change that enables caching right now.

**Comment by fjl** [comment]
It will still be safe to call Hash concurrently. I am mentioning this only because it should not be the limiting factor here.

**Comment by karalabe** [comment]
Yeah, I understood :) Btw, I've updated the PR to do exactly that.

**Pull request merged**
