### PR TITLE
internal/debug: add switch to format logs with json

### LINKED ISSUE #21926: Logging in JSON format
# Rationale

There should be more options on logging format for Geth.
At the moment, the only option available is the verbosity level.
For example, logging parsing is a great tool for managing highly available nodes.
I am suggesting two flags, one that would change the formatted log to JSON and a second flag to specify the output log file, rather than dump onto `stdout`.

These two flags combined would allow a variety of tools to monitor the health of a Geth node.
# Implementation

The [`log/` folder](https://github.com/ethereum/go-ethereum/tree/master/log), containing the `log15` package already parses the log messages in JSON format, but it converts to syslog before dumping. The first mentioned flag would skip the conversation.

Also, it's (to my knowledge) trivial to create a flag that receives one argument (file) and writes the log into it rather than `stdout`.

### PR DESCRIPTION
**Pull request by s1na**
This PR adds a switch `--logjson` which if enabled makes the client format logs with JSON.

Something I'm not clear about is if setting `glogger` needs to be done in `init`. I had to move it to `Setup` to have access to the flags. Could this have an unintended consequence?

Fixes #21926

### CODE REVIEW

**Comment by holiman** [comment]
> Something I'm not clear about is if setting glogger needs to be done in init. I had to move it to Setup to have access to the flags. Could this have an unintended consequence?

It doesn't _need_ to be done in `init`, it's just that `init` is called very very early. And we want to configure the logger very early, since someting may need to log something in a very early phase. 

On a normal run, this seems to work fine (as in, nothing in the _normal_ case tries to log anything before we have performed Setup):

```
 ./build/bin/geth --logjson --nodiscover --maxpeers 0  
{"lvl":"info","msg":"Starting Geth on Ethereum mainnet...","t":"2021-01-25T14:32:25.359673574+01:00"}
{"lvl":"info","msg":"Bumping default cache on mainnet","provided":1024,"t":"2021-01-25T14:32:25.359768424+01:00","updated":4096}
{"lvl":"warn","msg":"Sanitizing cache to Go's GC limits","provided":4096,"t":"2021-01-25T14:32:25.35985691+01:00","updated":2589}
```

I'll test it a bit more to see if I can find any place where geth tries to log before we've called `Setup`

**Comment by holiman** [comment]
> I had to move it to Setup to have access to the flags. Could this have an unintended consequence?

Oh, yeah there's one more thing aswell: there's this `glogger` global variable, which is `nil`. I don't see it as a problem, however, because it's only accessed via `debug.Verbosity` and `debug.VModule` RPC calls, and the RPC stack isn't spun up until much later.

**Comment by holiman** [comment]
I think you can combine the two, and make it even better than it is on `master`. On `master`, if something logs before we've called Setup, it won't actually be printed. 
```
[user@work go-ethereum]$ git diff
```
```diff
diff --git a/internal/debug/flags.go b/internal/debug/flags.go
index a39a4a3194..92a46d3e8e 100644
--- a/internal/debug/flags.go
+++ b/internal/debug/flags.go
@@ -130,9 +130,16 @@ var DeprecatedFlags = []cli.Flag{
 
 var glogger *log.GlogHandler
 
+func init() {
+       glogger = log.NewGlogHandler(log.StreamHandler(os.Stderr, log.TerminalFormat(false)))
+       glogger.Verbosity(log.LvlInfo)
+       log.Root().SetHandler(glogger)
+}
+
 // Setup initializes profiling and logging based on the CLI flags.
 // It should be called as early as possible in the program.
 func Setup(ctx *cli.Context) error {
+       log.Info("setting up logging")
        var ostream log.Handler
        output := io.Writer(os.Stderr)
        if ctx.GlobalBool(logjsonFlag.Name) {
@@ -144,8 +151,7 @@ func Setup(ctx *cli.Context) error {
                }
                ostream = log.StreamHandler(output, log.TerminalFormat(usecolor))
        }
-       glogger := log.NewGlogHandler(ostream)
-
+       glogger.SetHandler(ostream)
        // logging
        log.PrintOrigins(ctx.GlobalBool(debugFlag.Name))
        glogger.Verbosity(log.Lvl(ctx.GlobalInt(verbosityFlag.Name)))
```
Running this, which contains an extra logging before we've actually set up the desired logging, yields: 
```
[user@work go-ethereum]$ ./build/bin/geth --logjson --nodiscover --maxpeers 0 --config=/bax/noz
INFO [01-25|14:49:57.978] setting up logging 
{"lvl":"info","msg":"Starting Geth on Ethereum mainnet...","t":"2021-01-25T14:49:57.978621371+01:00"}
{"lvl":"info","msg":"Bumping default cache on mainnet","provided":1024,"t":"2021-01-25T14:49:57.978673911+01:00","updated":4096}
{"lvl":"warn","msg":"Sanitizing cache to Go's GC limits","provided":4096,"t":"2021-01-25T14:49:57.978784402+01:00","updated":2589}
Fatal: open /bax/noz: no such file or directory

```

So I think this diff minus the extra log line will make it both 'safe' and functional

**Comment by s1na** [comment]
Aha this way `glogger` has a default value until it is more exactly configured based on flags. Updated with this patch and squashed the commits.

**Review by holiman — APPROVED** [review]
LGTM. I think this is a really nice feature, and on the upside, it doesn't actually add a lot of complexity or new code. 

The only thing I'm a bit unsure about is whether `logjson` flag is the best name for it.

**Comment by s1na** [comment]
Another option I was thinking about would be `--log.format json/human`. But since there are only 2 options it seems a bit too much. Do you have any ideas Martin?

**Comment by holiman** [comment]
I think maybe I'd prefer just `--log.json`

**Comment by holiman** [comment]
@s1na as a follow-up, can you move other flags into the `logs.` namespace, namely: `log.verbosity`, `log.vmodule`, `log.backtrace` ? And while doing so, make the old ones deprecated, causing them to still work, but also show a mesage about the new flags.

**Comment by willianpaixao** [comment]
Thanks @s1na and @holiman! ❤️

**Pull request merged**
