### PR TITLE
all: remove terminalTotalDifficultyPassed

### PR DESCRIPTION
**Pull request by stevemilk**
The PR gets rid of the flag terminalTotalDifficultyPassed which is mentioned in #29555.

### CODE REVIEW

**Comment by fjl** [comment]
The linked issue is more like an internal memo for us to delete this flag later. We don't want to remove it yet.

**Comment by karalabe** [comment]
It's probably time to get this in.

**Comment by karalabe** [comment]
It's probably time to get this in.

**Comment by jwasinger** [comment]
The downstream branch and associated commit are missing from @stevemilk 's fork (deleted I guess).

**Pull request closed without merging**
