### PR TITLE
ETH API - Estimate gas return data

### PR DESCRIPTION
**Pull request by julesGoullee**
This PR intends to return transaction data for `eth_estimateGas` method. When transaction required state modification, (not a Solidity view or pure, it can't be execute without a transaction), the estimate endpoint returns the amount of gas needed but omit the returned value.
Sadly this modification required a breaking change in the API in the response format.
In place of: `{ "result": 123456 }`
Returns: `{"result": { "gasUsed": 123456, "returnData": "0x" } }`
ReturnData is typing `Bytes`, the client has to parse it regarding the type of returned value.
I'm not very familiar with the go-ethereum base code, I'm not confident about the way I have done this modification, I run it on live, seems to be ok. Probably I'm not the only one who is annoyed to be able to estimate the transaction but to ignore the returned value.
EIP link: [https://github.com/ethereum/EIPs/pull/2724](https://github.com/ethereum/EIPs/pull/2724)

### CODE REVIEW

**Comment by karalabe** [comment]
Why not just do an `eth_call` to get the result? That's what it's meant to do. I don't think changing gas estimation to return a result something else is meant to provide makes sense.

**Comment by karalabe** [comment]
FYI, you can use `eth_call` just fine with state modifying ops, just it will not be persisted after the call returns.

**Comment by julesGoullee** [comment]
Yeah, it's to avoid two calls one for the returned data one for the gas, without "extra" cost in terms of computing, avoiding one call that runs more less the same logic with two incomplete response in one call

**Comment by karalabe** [comment]
I am not really sure what the exact use case is though? If you want the amount of gas needed for a transaction, call `eth_estimateGas`. In that case the result is not that relevant, because the final result will depend on execution by a miner whenever it gets included. If you want the result itself, then you can call `eth_call` and don't care about the gas.

What is your use case that requires both gas estimation and execution result at the same time? We could return a result from estimation, but that will not be the same as executed by the chain eventually, so I'm not really sure the value is there.

Changing the RPC API on the other hand is not possible because it would break every single code out there.  The only viable option is to add a new endpoint, but that requires a pretty good rationalization as to why it's useful.

**Comment by fjl** [comment]
I also think this change is not correct and would cause problems in applications if you used it.
eth_estimateGas is for estimating the gas limit of a transaction. It executes the transaction to estimate
it, but the execution is not canonical. The only true execution result is the one that is generated when the
TX is included in a block.

**Pull request closed without merging**
