### PR TITLE
Renamed Coinbase to Etherbase, fixes #1420

### LINKED ISSUE #1420: cmd/geth: rename etherbase to coinbase
If "etherbase" is really preferred over "coinbase", let's make it consistent everywhere.

The output of `geth attach` uses `coinbase`

Geth
Version: 0.9.35
Git Commit: aa4502060b50733a3a82a0ab575eac0731cdb7ca
Protocol Versions: [61 60]
Network Id: 0
Go Version: go1.4.2

### PR DESCRIPTION
**Pull request by dherbst**
Renamed Coinbase to Etherbase, fixes #1420

Leaves the values in the json named "coinbase" for backwards compatibility.

Touches cmd/geth, consensus, console, core/vm, eth, les, internal/ethapi,
internal/jsre, light, miner, mobile.

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 67a464b8c1b4fb0cea0587ce58b92e8f95f5e419
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: ffe257e5c14255c3ad3be46784b161659688f8e2
  * Commits must be prefixed with the package(s) they modify
  * Commit subjects should be kept under 100 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: c3158a31f71faf0c8c9b56a9366c620e8de580ef
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by dherbst** [comment]
I'm going to close this PR because I need to learn more about the web3.js integration.

**Pull request closed without merging**
