### PR TITLE
core/vm: remove unnecessary memset for Memory.Set32

### PR DESCRIPTION
**Pull request by qianbin**

### CODE REVIEW

**Comment by holiman** [comment]
Ah. Now I see. The `uint256.WriteToSlice` always writes 32 bytes, which wasn't the case when it was based on `big.Int`s. So this change is not breaking anything. 

However, it does rely on the behaviour of `uint256.Int` not changing. And the behaviour isn't likely to change, but perhaps we should comment on the uint256 method that it is guaranteed to write the full `32` bytes (and have a test for it)

**Comment by qianbin** [comment]
> This looks super dangerous, and wrong, to me. Do you have any reasons for why you think this is a safe change?

unlike big.Int, uint256.Int.WriteToSlice fully fills 32 bytes of dst if len(dst)>=32. so zero mem is not needed.

**Comment by Kantitad** [comment]
👋

ในวันที่ พ. 11 พ.ค. 2022 00:47 น. Martin Holst Swende <
***@***.***> เขียนว่า:

**Comment by qianbin** [comment]
@holiman I found something interesting. Here's a piece of benchmark code:
```go
func BenchmarkMemorySet32(b *testing.B) {
	mem := make([]byte, 32)
	val, _ := uint256.FromHex("0x123456789012345678901234567890")
	b.Run("WriteToSlice", func(b *testing.B) {
		mem := make([]byte, 32)
		for i := 0; i < b.N; i++ {
			val.WriteToSlice(mem)
		}
	})

	b.Run("Copy bytes32", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			b32 := val.Bytes32()
			copy(mem, b32[:])
		}
	})
}
```
It gives the result: 
```
$  go test -benchmem -run=^$ -bench ^BenchmarkMemorySet32$ ./core/vm -benchtime=2s
goos: linux
goarch: amd64
pkg: github.com/ethereum/go-ethereum/core/vm
cpu: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
BenchmarkXxx/WriteToSlice-8         	41986675	        55.17 ns/op	       0 B/op	       0 allocs/op
BenchmarkXxx/Copy_bytes32-8         	322073786	         7.451 ns/op	       0 B/op	       0 allocs/op
PASS
```
I don't know why, perhaps  `binary.BigEndian.PutUintxxx` is highly optimized somehow (except inlining). 

So I think copy-bytes32 is the right way.

**Comment by holiman** [comment]
The `WriteToSlice` loops and shifts, and possibly the compiler cannot omit the out-of-bounds checks. If the compiler isn't sure that it cannot go out of bounds, then it's possible that it can `panic`, thus it cannot be inlined either. 

So I agree that `b32 := val.Bytes32()` might be a better option. There's no GC overhead either since it'll just be a stack allocated item, afaict.

**Comment by holiman** [comment]
We actually have a benchmark for this. With the first change, removing the initializer: 
```
$ benchstat master.txt pr_v1.txt 
name        old time/op  new time/op  delta
OpMstore-6   106ns ±22%    94ns ± 1%  -11.92%  (p=0.016 n=5+4)
```
And the `master` versus the latest variant: 
```
$ benchstat master.txt after.txt 
name        old time/op  new time/op  delta
OpMstore-6   106ns ±22%    26ns ± 1%  -75.14%  (p=0.008 n=5+5)
```

**Comment by qianbin** [comment]
> We actually have a benchmark for this. With the first change, removing the initializer:
> 
> ```
> $ benchstat master.txt pr_v1.txt 
> name        old time/op  new time/op  delta
> OpMstore-6   106ns ±22%    94ns ± 1%  -11.92%  (p=0.016 n=5+4)
> ```
> 
> And the `master` versus the latest variant:
> 
> ```
> $ benchstat master.txt after.txt 
> name        old time/op  new time/op  delta
> OpMstore-6   106ns ±22%    26ns ± 1%  -75.14%  (p=0.008 n=5+5)
> ```

OK. Should I remove the newly added test file?

**Comment by holiman** [comment]
> OK. Should I remove the newly added test file?

Yes please, was just about to ask that :)

**Review by holiman — APPROVED** [review]
Good find, thanks!

**Pull request merged**
