### PR TITLE
miner: track uncles more aggressively

### PR DESCRIPTION
**Pull request by karalabe**
Currently we maintain a set of possible uncles, and cross out headers that turn out to be inappropriate for uncle inclusion. A reorg however could convert the inappropriate uncles back into possible ones, so this PR ensures that the headers from the potential uncle list are only removed if the chain progresses beyond the 7 uncle depth.

---

Hmm, this PR may not be needed. A reorg in theory reports all reorged blocks as a side chain event. So those would en up in the pending blocks anyway.

### CODE REVIEW

**Comment by holiman** [comment]
Looked through it a bit, have one question. 
So we have these fields in `worker`: 
```
// family set (used for checking uncle invalidity)
Family: contains all ancestor hashes, and their uncle-hashes

 // ancestor set (used for checking uncle parent validity)
ancestors: contains all ancestor hashes

// uncle set
uncles: initially empty, then uncle hashes are added on commitUncle
```
So on `commitUncle`, the uncle is added to the `uncles` set. But during the processing loop, we end up by calling `commit(uncles...`, where another `uncles` set is used: not `w.uncles`. So there are basically two `uncles` mappings, one on the `w` object, and another list on the heap. 

https://github.com/ethereum/go-ethereum/blob/de8607c6dc7af60d03560cb9e77b072797036fde/miner/worker.go#L924

What's the point of this? Is it correct?

**Comment by rjl493456442** [comment]
@holiman `w.uncles` is a `set`. While the `commit` function needs an uncle array. So basically we just make a conversion

**Comment by rjl493456442** [comment]
@karalabe Sorry for the error typing, sibling is not allowed to be an uncle. 
Current the `commitUncle` function could add siblings to the uncle set. So i mean we should add some extra checking.

**Comment by holiman** [comment]
But it's not a conversion. If, an uncle is already in the `set` before the loop starts, then it will exit with `error` on `commit`, and not become part of the list.

**Comment by karalabe** [comment]
@holiman If it's already tracked as an uncle in the block, why add it a second time?

**Pull request merged**
