### PR TITLE
build: add -buildid='' to make the binary reproducible

### PR DESCRIPTION
**Pull request by attila-lendvai**
i checked it only briefly by copying the source to another directory, and `make clean` followed by `make`, both with and without this commit.

what's missing: something in the CI to test this.

### CODE REVIEW

**Comment by fjl** [comment]
Not sure if this is a good idea. AFAIK Go buildid is deterministic, and the toolchain also uses it for something.

**Comment by fjl** [comment]
Can you give some additional information about the observed changes in the binary with this commit?

**Comment by attila-lendvai** [comment]
oh, sorry, i didn't run **that** test...

so, `buildid` is indeed deterministic on the same host. my goal is to be deterministic across building hosts, but i can't find a quick answer to whether `buildid` is also stable across hosts. there's all kind of chatter on golang issues that it needs to be set to an empty string.

if it is deterministic across hosts, then this PR is unnecessary.

**Review by ligi — APPROVED** [review]

**Comment by attila-lendvai** [comment]
there's this: https://github.com/golang/go/issues/33772 but it's been fixed.

so, i'm marking it as draft until i can find definitive answer whether the `buildid` is stable across hosts.

meanwhile, anyone with a better understanding of the go build process, if you know the answer, then feel free to merge it nevertheless.

**Review by ligi — COMMENTED** [review]
thanks for caring for reproducible builds!

**Comment by attila-lendvai** [comment]
does anyone know whether the `buildid` has any value or use on an end-user executable? if none, then maybe we can just zero it out and forget about it?

i have built it in a debian chroot, and the `buildid` is completely different, even its way of annotation?! i have put a newline for readability:

```
$ file /tmp/go-ethereum2/build/bin/geth /tmp/geth 

/tmp/go-ethereum2/build/bin/geth: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /gnu/store/fa6wj5bxkj5ll1d7292a70knmyl7a0cr-glibc-2.31/lib/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, 
Go BuildID=UAg-AqU6CZG8sFO6FWKs/TVun71wAK_139gbQH95P/2pm34P8ORuBIXSFED1fZ/nhynqARG9yvX-rTbU_Um, not stripped

/tmp/geth:                        ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, 
BuildID[sha1]=a9a1486f590ae686487386244b622f948b98c24b, for GNU/Linux 3.2.0, not stripped
```

even though both go version print the exact same:
```
$ go version
go version go1.15.15 linux/amd64
```

this requires further investigation.

**Comment by attila-lendvai** [comment]
how are `geth` releases built? is it public information? if so, then i'd appreciate any pointers.

for now i'm failing badly at reproducing the released binary locally.

**Comment by holiman** [comment]
> how are geth releases built? is it public information? if so, then i'd appreciate any pointers.

Sorry for late answer. Yes, it's public, it's even in this repo. See https://github.com/ethereum/go-ethereum/tree/master/build , and in partcular https://github.com/ethereum/go-ethereum/blob/master/build/ci.go

**Comment by attila-lendvai** [comment]
thank you!

meanwhile, i'm having a lot of fun on guix. i'm working on the packaging of geth for guix, and i'll see how the result compares using `diffoscope`. due to architectural reasons, bit-by-bit reproducibility on guix proper is pretty hopeless without some form of virtualization, but a reasonably clean diffoscope may be feasible. and i may try to put together a guix package that builds geth in a container.

if you want to track the issue of reproducible builds somewhere else, then feel free to close this PR for now, and link to the place where we should continue this.

**Comment by fjl** [comment]
Just to give a more detailed answer, the release binary is built by the command

```
go run build/ci.go install -dlgo
```

I think removing the Go buildid is not a good idea. The buildid is deterministic, but may include some file system paths.
Two builds in the same file system location, with the same C toolchain should generate an identical binary.

**Pull request closed without merging**
