### PR TITLE
event: secondary send method

### PR DESCRIPTION
**Pull request by Exca-DK**
This pr adds a secondary method for notifying subscribers. This method allows notifications to be sent within a deadline and optionally allows for slow consumers to be dropped.

### CODE REVIEW

**Comment by Hektoreth** [comment]
How adres lido send my eth ??

pon., 17 kwi 2023, 15:30 użytkownik Exca-DK ***@***.***>
napisał:

**Comment by fjl** [comment]
Can you please provide more information about your use case? I designed `Feed` to not drop subscribers, because it is intended as a a reliable mechanism for internal event dissemination.

**Comment by Exca-DK** [comment]
The premise behind that is to have ability to drop or ignore slow subscribers in places where consistent view is not fully required. One of the places I think could make use of that would be event system. From what I understand it subscribes to systems such as txpool through feed and redistributes the txs to its own consumers. Although each consumer runs in its own goroutine with buffered channel, it can still be filled since remote writes are wasting a lot of time by doing 1 item at a time instead of the whole batch.  I also sometimes use the feed in my own apps to redistribute the data and there are cases where I am okay with seeing only the newest data even though I might lose some along the way. 
This pr only changes the newer version of feed, FeedOf so maybe when the base starts moving to the newer version of feed, there might be a more apparent case for that. This also makes me confused why the build failed, FeedOf is not used anywhere across the repo yet?

**Comment by holiman** [comment]
I might be missing something.. but you want to make certain subscribers be "best-effort" via using a different method of registering the subscription? 
And it adds quite some complexity to the subscription mechanism. 

Why not just make them call-sites where those subscribers are set up use something like the code below, so the consumer turns itself into a best-effort consumer that doesn't block? 
```golang

	go func(src, dest chan int) {
		for item := range src {
			select {
			case dest <- item:
			default:
			}
		}
	}
```

**Comment by Exca-DK** [comment]
It's okay. I just thought that it might be useful not only for my use case as inexpensive secondary option, especially considering the original remains unchanged.

**Comment by fjl** [comment]
Hey, no need to close the PR immediately, we are just exploring your solution!

**Pull request closed without merging**
