### PR TITLE
rpc: accept gzip encoded responses

### PR DESCRIPTION
**Pull request by prestonvanloon**
- Allow HTTP RPC to specify that it accepts gzip encoded responses
- Decode gzip encoded responses

### CODE REVIEW

**Comment by fjl** [comment]
Please add a test for this.

**Comment by prestonvanloon** [comment]
Unfortunately, there are no tests for the `DialHTTPWithClient` method. 
I do not have time to write tests for this and it isn't very complicated logic, just adding a header.

**Comment by fjl** [comment]
I'm adding a test now, and this change is puzzling me. net/http adds "accept-encoding" gzip by default, and does uncompress transparently. This change only becomes active in cases where someone uses `http.Transport` with `DisableCompression` turned on, and forces compression to be on in this case.

Wouldn't it be better to leave the choice regarding compression to the transport?

**Comment by fjl** [comment]
I have now verified that the client uses gzip by default even without this change unless `DisableCompression` is set by the transport.

**Comment by karalabe** [comment]
@fjl So is this PR a noop?

**Comment by fjl** [comment]
The PR is not no-op, it enables compression when automatic compression in http.Transport is disabled. I'm not sure if we want that.

We could remove the line that sets `accept-encoding`. With that, the PR would be a fix for misconfigured transports or servers that send gzip even though we didn't ask for it.

**Comment by karalabe** [comment]
Hmm. If I explicitly disable compression, it seems weird to me to force enable it anyway. I'm fine with not-choking on a bad server.

**Comment by prestonvanloon** [comment]
Without the accept encoding header, I wasn’t observing compressed responses. Maybe there is a better way to handle the decompression if transport can do it automatically.

**Comment by fjl** [comment]
@prestonvanloon how did you check for compressed responses? are you using a custom `http.Client`?

**Comment by prestonvanloon** [comment]
I was using [rpc.Dial](https://godoc.org/github.com/ethereum/go-ethereum/rpc#Dial) and logging if the response returned was compressed with gzip encoding. 

Is there a flag or something to specify transport encoding? Without the accept-encoding header, server was not encoding the responses which is to be expected. Additionally, without some handling of compressed responses, the json payload could not be unmarshalled.

**Comment by karalabe** [comment]
So. @fjl says it works. @prestonvanloon says it doesn't. At this point IMHO it falls on Preston to actually demonstrate that it doesn't, which the PR should have done anyway via a test to verify the fix.

So, either lets add the repro/fix, or let's close this PR.

**Comment by prestonvanloon** [comment]
I think @fjl is correct and i am incorrect. Part of my confusion was that when providing the accept-encoding header, it is not automatically decompressed. After reading a bit more in the godocs for HTTP Transport, I see this "However, if the user explicitly requested gzip it is not automatically uncompressed." 

I really appreciate you all looking into this and I'm sorry for wasting cycles on it.

**Comment by fjl** [comment]
Hey, no problem! I actually didn't know about automatic gzip support before checking out this PR :)

**Pull request closed without merging**
