### PR TITLE
cmd/puppeth: remove puppeth

### PR DESCRIPTION
**Pull request by holiman**
This PR removes `puppeth` from the codebase. 

:vulcan_salute: :bow: :smiling_face_with_tear: :funeral_urn:

### CODE REVIEW

**Comment by lightclient** [comment]
🫡

**Review by fjl — APPROVED** [review]
<key>F</key>

**Review by MariusVanDerWijden — APPROVED** [review]
:vulcan_salute:

**Review by karalabe — APPROVED** [review]
F

**Comment by Alessandro-Cavaliere** [comment]
Why was it removed? Is it deprecated?

**Comment by toshitehdev** [comment]
kek

**Comment by JainitBITW** [comment]
why puppeth was removed

**Comment by karalabe** [comment]
Puppeth became obsolete after the merge since it could not deploy consensus clients nor configure beacon chains. Implementing all that logic into Puppeth would have been too much of an effort and there was nobody to do it. As such, we've decided to remove the non-functional functionality.

**Comment by choesy** [comment]
What are some alternatives to puppeth?

**Comment by holiman** [comment]
well, `ansible` is a more common alternative, i'm sure you can find setups to orchestrate both geth and beacon-client and validator(s), whereas puppeth was always just a geth-first tool with very limited non-geth support

**Pull request merged**
