### PR TITLE
eth: fix shutdown errors

### PR DESCRIPTION
**Pull request by zsfelfoldi**
- implemented common.ShutdownManager, a sync mechanism for proper shutdown
- PM shutdown waits for all handlers to stop, drops all peers
- event.TypeMux.Stop() waits for all event loops to exit, see LoopStarted() and LoopStopped()

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Sat Mar 26 17:30:45 UTC 2016_

**Comment by fjl** [comment]
I do not agree with any of these changes. 

sync.WaitGroup must be used in a controlled fashion. Any use must ensure that all calls to Add have **completed** when Wait is called.

Exposing the WaitGroup in package event makes it very hard to maintain this guarantee in all cases.

Tracking peer sessions with a WaitGroup is possible, but requires synchronisation with Stop to ensure that no call to Add will happen.

The use of time.Sleep looks odd. If shutdown synchronisation is done correctly, no sleeping should be required.

**Comment by zsfelfoldi** [comment]
@fjl thanks for the comments, I created a simple sync object that ensures the proper use of sync.WaitGroup. You're also right about Sleep, I just forgot to remove it after experimenting. Removed now and it works properly without sleeping.

**Comment by fjl** [comment]
I think the addition of ShutdownManager (essentially a locked WaitGroup) is band-aid
around the real issue. The shutdown errors are caused by the fact that the Stop method of 
some components (eth.ProtocolManager, miner.Miner, core.TxPool) is asynchronous.
In the presence of `go mux.Post` calls, this means that event processing will continue after Stop
even though the database has already been closed.

I would prefer it if we just used WaitGroup correctly to fix those Stop methods.
Would be nice to hear other people's opinions, though.

The suggestions below are in commit form because it seemed to be the easiest way to
explain what I mean. You can build off those commits if you want, but I haven't checked whether
they introduce any regressions or pass the tests.

**Shutting down eth.ProtocolManager**

In order to make use of WaitGroup safe, we need a way to stop new peer sessions from
being added before wg.Wait can be called. Your diff already hints at a solution:
in the protocol Run function, use select to add to the WaitGroup if we're not shutting down.

https://github.com/fjl/go-ethereum/commit/ed0389a563eb5025b4122d633c2309fa075112f3

**Shutting down the other loops**

For miner.worker and TxPool the number of goroutines is static, so WaitGroup can be used
without additional synchronisation.

TxPool: https://github.com/fjl/go-ethereum/commit/36b6e9f1faeb9e272ef48a3635f873c5c28bc40b
Miner: https://github.com/fjl/go-ethereum/commit/f0b1f2635d0496b82d7c3632603b917dd04dd227

**Comment by zsfelfoldi** [comment]
Closed because of https://github.com/ethereum/go-ethereum/pull/2523

**Pull request closed without merging**
