### PR TITLE
whisper: version 6 initial commit (clone of v5)

### PR DESCRIPTION
**Pull request by gluk256**

### CODE REVIEW

**Comment by karalabe** [comment]
Is there a reason to retain v5? Can't we just move it to v6? And drop v2 while we're at it?

**Comment by gballet** [comment]
@karalabe Some of the people in the whisper chat still use v2. We will ask the question in Cancun to find out if v2 can be dropped, but from what I see it's too early. Same reason with v5, people are barely switching to it and v6 isn't going to be ready for a while, it would be a bit early to drop it altogether, especially since the situation with Parity's v6 is not currently clear.

**Comment by 5chdn** [comment]
If there is some kind of whisper working group, please make me part of it. I want to get back to the point where Parity and Geth can talk to each other again, _literally_.

**Comment by karalabe** [comment]
Lets make one!

**Comment by jarradh** [comment]
+1 to be involved in Whisper working group

**Comment by tiabc** [comment]
+1 to be included in the working group.

**Comment by b00ris** [comment]
+1 to be involved in Whisper working group

**Comment by JekaMas** [comment]
+1 me too.

**Comment by karysto** [comment]
+1 to be included in the Whisper working group.

**Pull request merged**
