### PR TITLE
internal/ethapi: fix eth_call nonce bug

### PR DESCRIPTION
**Pull request by zsfelfoldi**
fixes https://github.com/ethereum/go-ethereum/issues/2796
alternative solution: https://github.com/ethereum/go-ethereum/pull/2799

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Sun Jul 10 12:12:43 UTC 2016_

**Comment by karalabe** [comment]
Were nonces always required to execute plain CALLs? Could you link to the old code before your PR that did this same thing?

**Comment by zsfelfoldi** [comment]
https://github.com/ethereum/go-ethereum/blob/22ef7370e7932b085cc0bd7d1a07d58b0ef596a7/eth/api.go#L751
The entire state object was retrieved. Btw you're right, this is unnecessary and in a light client it even costs an extra ODR request. We should probably just disable nonce checking instead. But this is how it worked until now.

**Comment by zsfelfoldi** [comment]
I'm creating another PR that disables nonce check, then we can decide which one to merge.

**Comment by zsfelfoldi** [comment]
done

**Comment by fjl** [comment]
:-1: I'm in favour of the alternative solution in #2799

**Comment by karalabe** [comment]
Closed in favor of the alternative.

**Pull request closed without merging**
