### PR TITLE
core/vm: implement EIP-2681: Limit account nonce to 2^64-1

### PR DESCRIPTION
**Pull request by gumb0**
This retroactively implements requirements or [EIP-2681](https://eips.ethereum.org/EIPS/eip-2681) for the account nonce upper limit.
Consensus tests (covering only CREATE/CREATE2 case): https://github.com/ethereum/tests/pull/934

Opening PR as requested in https://github.com/ethereum/tests/pull/934#issuecomment-959815137

### CODE REVIEW

**Comment by holiman** [comment]
What about the case where the EOA goes above the same limit, shouldn't the tx be rejected in that case? Do we already have that in place?

**Comment by gumb0** [comment]
> What about the case where the EOA goes above the same limit, shouldn't the tx be rejected in that case? Do we already have that in place?

Yes it should, tx_pool doesn't have such check, but nonces are already uint64 there. Digging deeper to find where it's decoded...

**Comment by gumb0** [comment]
Here I found another place where the check is missing when external transaction updates the sender's nonce.
https://github.com/ethereum/go-ethereum/blob/03bc8b7858e0b019132de5fd5df6e8ec414d1dfd/core/state_transition.go#L321
EIP is not very clear for this case, (it only mentions tx nonce being above 64 bit, which is already rejected by geth as invalid tx encoding) I think it would make sense for a transaction to be valid and fail.

cc @axic

**Comment by gumb0** [comment]
And creation transaction BTW goes through the same code path as CREATE/CREATE2 and with this PR should already result in failed execution https://github.com/ethereum/go-ethereum/blob/03bc8b7858e0b019132de5fd5df6e8ec414d1dfd/core/state_transition.go#L318

**Comment by holiman** [comment]
Txpool is unrelated - the important part is the consensus engine. Check state-transition.go

**Comment by axic** [comment]
> EIP is not very clear for this case, (it only mentions tx nonce being above 64 bit, which is already rejected by geth as invalid tx encoding) I think it would make sense for a transaction to be valid and fail.

The mempool is not part of the EIP as clients are free to decide how they select transactions.

**Comment by gumb0** [comment]
> > EIP is not very clear for this case, (it only mentions tx nonce being above 64 bit, which is already rejected by geth as invalid tx encoding) I think it would make sense for a transaction to be valid and fail.
> 
> The mempool is not part of the EIP as clients are free to decide how they select transactions.

"is not very clear" did not refer to the mempool, but to external transaction updating sender's nonce when included.

**Comment by axic** [comment]
> > > EIP is not very clear for this case, (it only mentions tx nonce being above 64 bit, which is already rejected by geth as invalid tx encoding) I think it would make sense for a transaction to be valid and fail.
> >
> > The mempool is not part of the EIP as clients are free to decide how they select transactions.
>
> "is not very clear" did not refer to the mempool, but to external transaction updating sender's nonce when included.

Such transactions should not be accepted, i.e. they are invalid.

**Comment by gumb0** [comment]
> > "is not very clear" did not refer to the mempool, but to external transaction updating sender's nonce when included.
> 
> Such transactions should not be accepted, i.e. they are invalid.

This would make transactions with `nonce == 0xffffffffffffffff` invalid (and not only `where the nonce exceeds 2^64-1` as EIP states)

**Comment by axic** [comment]
> This would make transactions with nonce == 0xffffffffffffffff invalid (and not only where the nonce exceeds 2^64-1 as EIP states)

I mean those which exceed are invalid.

**Comment by holiman** [comment]
> This would make transactions with nonce == 0xffffffffffffffff invalid (and not only where the nonce exceeds 2^64-1 as EIP states)

I'd agree with that: by themselves they are valid, but since nonce increase is a consequence of including them, they lead to breaking the rule. Hence they must be rejected and cannot be included in a block. (not in the txpool though, this is a consensus rule)

**Comment by axic** [comment]
Hmm, that's an interesting point, that the increase is part of the inclusion, so transaction nonce `2^64-1` can't be included.

**Comment by holiman** [comment]
Triage discussion: we should fix both nonce-out-of-bounds cases in the same PR

**Comment by gumb0** [comment]
I think a change to `evm transaction` tool is also needed.

**Comment by holiman** [comment]
Hmpf... 
```
ERROR: Permission to ewasm/go-ethereum.git denied to holiman.
```
Please cherry-pick from https://github.com/holiman/go-ethereum/commits/deletelater

**Review by holiman — APPROVED** [review]
LGTM, if you also add the testcase from my branch

**Pull request merged**
