### PR TITLE
trie: try out ristretto cache

### PR DESCRIPTION
**Pull request by holiman**
This PR is a test of Ristretto: 
- Blog: https://blog.dgraph.io/post/introducing-ristretto-high-perf-go-cache/ 
- Code: https://github.com/dgraph-io/ristretto

This PR wraps ristretto, to produce an API that is more reminiscent of what we already have. 

In Ristretto, all cache items are `interface{}`. So if we tell it to cache a slice, then it will cache that slice, and not copy it "for us". So the caller needs to take care of that himself. In this PR, I make each `value` into a `string`. 

Bigcache was good since it didn't incur a lot of  the garbage collector overhead, using a big byte buffer as backend. Not sure how ristretto behaves from that aspect, I guess we'll see. 

There's a potential hiccup in ristretto - it has a channel where 32K items can sit queued, from `Set`. So aside from the actual cache, there may be 32K things hogging memory for a brief period before it's processed and something is evicted. This obviously improves `Set` performance in a multithreaded environment, but may also cause unnecessary cache-misses, which should be evident if we run a benchmark.

### CODE REVIEW

**Comment by holiman** [comment]
I found this open issue:

- https://github.com/dgraph-io/ristretto/issues/30

> Given that the KeyToHash (1) function supports string (and []byte), and it returns uint64, it is possible that there are hash collisions.
> 
> However the cache.Get (2) method doesn't check if the found entry (if any) actually has the given key. (In fact the store doesn't even support storing the key.)

Since the actual `key` is not stored, `Get` cannot verify that it actually found the correct `value`. There is a chance that we get a false positive and the cache returns the wrong element. So if we use ristretto, we might at some point get bitten by this, which could have very bad consequences. 

Nevertheless, we could still do a benchmark to see what the performance is like.

**Comment by karlmcguire** [comment]
Hey Martin, glad to see you're considering using Ristretto here. About your concerns:

1. You're correct that the Set buffer could hold 32K items. That number is arbitrary and could probably be smaller, and configurable if you'd like. If the Set buffer is under contention, *new* items that are Set would be dropped and never enter the Set buffer (updates go a different route). I can't imagine a scenario where the Set buffer could be a memory problem for you, but of course test it and let us know. As far as hit ratios, we haven't seen much loss in our testing as long as you wait for the items in the Set buffer to pass through (taking a few milliseconds).

2. The hash collision probability is being fixed right now. We understand that some people can't accept the current probability of 64-bit hash collisions. Our solution is using the current 64-bit hash as keys and adding a 64-bit field that is verified in Set/Get/Del operations. Assuming someone were to call 30M Set operations per second for 30 days, the probability of a collision would be 0.00000000001%.

**Comment by holiman** [comment]
Benchmark started. It's only been a couple of minutes so far, but some initial stats: 
Screenshot_2019-09-27 Dual Geth - Grafana
yellow: ristretto, green: bigcache

Initally, we've written _more_ to ristretto, but have a lot more misses and fewer hits.

**Comment by holiman** [comment]
After a couple of hours, this behaviour hit even harder: 
Screenshot_2019-09-27 Dual Geth - Grafana(1)


Initially, it surprised me that `writes` were so much more on ristretto - but then I realized that since we get a cache miss, we re-read the data from disk, and then once again write it into ristretto. Meanwhile, this PR is starting to lag behind `master`.

**Comment by holiman** [comment]
Turns out I totally borked this. The `HardMaxCacheSize` in `bigCache` is in `MB`, whereas I use it as `MaxCost` as is -- thereby giving ristretto an allowance one million times lower :)

**Comment by karlmcguire** [comment]
Yea, we ran into similar issues when benchmarking all of these different implementations.

**Comment by holiman** [comment]
Same graph as above, after about two hours runtime:

Screenshot_2019-09-27 Dual Geth - Grafana(2)

`bigCache` has a minor lead in performance, but it'll be a few more hours before the real churn begins.

**Comment by holiman** [comment]
After about 1,5 days, here's the mem profile

Screenshot_2019-09-28 Dual Geth - Grafana

This PR (`mon081) uses about 2G more memory, consistently (`11G` vs `9G`). 
They are roughly equal in cache performance
Screenshot_2019-09-28 Dual Geth - Grafana(1)

And almost equal in block processing  (`mon08` slightly behind, around 3 hours)

**Pull request closed without merging**
