### PR TITLE
accounts: inintroduce derivationPathBase to represents 0x80000000

### PR DESCRIPTION
**Pull request by jsvisa**

### CODE REVIEW

**Comment by karalabe** [comment]
I don't think this is a good change. There's no real value in separating this out into its own constant. This is not something that can ever change.

**Comment by jsvisa** [comment]
@karalabe IMO, the multi `0` under 0x80000000 is error prone, one may missing one or  one more `0` as 0x80000000's suffix

**Comment by karalabe** [comment]
There are only 3 variables that need to be correct, the derivation constants. The rest are tests, and any error would be caught immediately. The code also doesn't change ever, so again there's not much reason to be afraid of potential breakages.

**Comment by jsvisa** [comment]
@karalabe Thanks, and I'll close it right now.

**Pull request closed without merging**
