### PR TITLE
metrics : use time.Timer instead of time.Sleep in metrics

### PR DESCRIPTION
**Pull request by ucwong**

### CODE REVIEW

**Comment by holiman** [comment]
Code-wise, this is IMO less elegant than the current code. Is there some benefit of this PR? Like, is it more correct? I didn't see anything in particular in the official [docs](https://golang.org/pkg/time/#Timer) about why this solution is to be preferred?

**Comment by ucwong** [comment]
> Code-wise, this is IMO less elegant than the current code. Is there some benefit of this PR? Like, is it more correct? I didn't see anything in particular in the official [docs](https://golang.org/pkg/time/#Timer) about why this solution is to be preferred?

```
// timeSleep puts the current goroutine to sleep for at least ns nanoseconds.
//go:linkname timeSleep time.Sleep
func timeSleep(ns int64) {
	if ns <= 0 {
		return
	}
	t := new(timer)
	t.when = nanotime() + ns
	t.f = goroutineReady
	t.arg = getg()
	lock(&timers.lock)
	addtimerLocked(t)
	goparkunlock(&timers.lock, "sleep", traceEvGoSleep, 2)
}
```
I think it seems to be a little better of using a single timer than creating a new timer every time when to sleep.

**Comment by holiman** [comment]
> I think it seems to be a little better of using a single timer than creating a new timer every time when to sleep.

Right ... from a pure technical perspective I can agree, however, if we alloc one timer every `3 seconds` (which seems to be the case), I personally prefer the simpler code, since it's less cognitive load for future (and current) developers

**Comment by ucwong** [comment]
> > I think it seems to be a little better of using a single timer than creating a new timer every time when to sleep.
> 
> Right ... from a pure technical perspective I can agree, however, if we alloc one timer every `3 seconds` (which seems to be the case), I personally prefer the simpler code, since it's less cognitive load for future (and current) developers

Yes, ```time.Sleep(...)```'s advantage is simpler for coding.

**Comment by holiman** [comment]
I'll leave this PR for @fjl or @karalabe to decide, :+1:  or :-1:

**Comment by fjl** [comment]
I think it doesn't make sense to use a `time.Timer` when `time.Sleep` is OK. There
are situations where `time.Sleep` is not OK, but it is fine for this loop.

**Pull request closed without merging**
