### PR TITLE
eth: fixed homestead tx check

### PR DESCRIPTION
**Pull request by obscuren**
When a block is queried for retrieval we should add a check whether the
block falls within the frontier rules. If we'd always use `From`
retrieving transaction might fail.

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Sat Feb 20 11:03:22 UTC 2016_

**Comment by fjl** [comment]
:+1:

**Comment by obscuren** [comment]
@fjl could you have a look again. I've changed all `From` to `FromFrontier`. Previous fix didn't catch all possible `From()` fields which would have failed. Due to the places where `From` is used we can not check for the block number. This isn't a problem because the transactions retrieved are always valid anyway.

**Comment by fjl** [comment]
:+1: (I looked again)

**Comment by obscuren** [comment]
This needs to be back ported to `1.3.4`

**Comment by bas-vk** [comment]
:+1:

**Pull request merged**
