### PR TITLE
crypto/secp256k1: add checking z sign in affineFromJacobian

### PR DESCRIPTION
**Pull request by hbakhtiyor**

### CODE REVIEW

**Comment by karalabe** [comment]
What is the purpose of this PR? I don't think we're willing to accept modifications to our crypto libraries without very strong arguments.

**Comment by hbakhtiyor** [comment]
checking for infinity 
`zinv := new(big.Int).ModInverse(z, BitCurve.P)` we got nil of `zinv`
and `zinvsq := new(big.Int).Mul(zinv, zinv)` throws error on `Mul` func

**Comment by hbakhtiyor** [comment]
https://github.com/hbakhtiyor/schnorr, here's my usecase

**Comment by fjl** [comment]
I will figure out if this change can be included as soon as I have a free afternoon. It's been a while since I've looked into EC math. Please be patient :).

**Comment by MariusVanDerWijden** [comment]
The same fix was proposed in https://github.com/ethereum/go-ethereum/pull/19934 again. In order to keep our backlog clean I closed the other PR. 

The other PR received the following comment from @CoreyLin 

The purpose of adding `if z.Sign() == 0` here is to prevent that `z` and `BitCurve.P` are not relatively prime which would lead to `zinv == nil` , right? If so, besides z.Sign() == 0 , there are other conditions/situations which may cause `z` and `BitCurve.P` to be not relatively prime. In other words, `z.Sign() == 0` is not the only reason to cause `z` and `BitCurve.P` to be not relatively prime.

Maybe you can furthur check source code of GCD method of big.Int as following:

```
// GCD sets z to the greatest common divisor of a and b, which both must
// be > 0, and returns z.
// If x or y are not nil, GCD sets their value such that z = a*x + b*y.
// If either a or b is <= 0, GCD sets z = x = y = 0.
func (z *Int) GCD(x, y, a, b *Int) *Int {
	if a.Sign() <= 0 || b.Sign() <= 0 {
		z.SetInt64(0)
		if x != nil {
			x.SetInt64(0)
		}
		if y != nil {
			y.SetInt64(0)
		}
		return z
	}

	return z.lehmerGCD(x, y, a, b)
}
```

Here `z` is passed in as `a` , and `BitCurve.P` is passed in as `b`. As long as `a` and `b` are not relatively prime, the return value would not be equal to 1.

**Comment by MariusVanDerWijden** [comment]
Okay so the `z == 0` is hit whenever we `Add` two points with the same `x1/x2` coordinate.
In this case `h` in line 149 becomes 0, therefore `z3` in line 195 becomes zero thus hitting the bug in affineFromJacobian.

**Pull request merged**
