### PR TITLE
Remove common/rlp*.go, which is implemented in package rlp now.

### PR DESCRIPTION
**Pull request by jeffallen**
I was trying to do this cleanup, but it seems like maybe common/rlp.go and rlp/encode.go are not compatible? Because when I made this cleanup, I ended up with these failures in package trie:

=== RUN   TestInsert
--- FAIL: TestInsert (0.00s)
	trie_test.go:72: exp 8aad789dff2f538bca5d8ea56e8abe10f4c7ba3a5dea95fea4cd6e7c3a1168d3 got c6fafca18cdfc651310c8b5f3d9d6fb737b1dcfd3cf39085db9d72141a91ea71
=== RUN   TestGet
--- PASS: TestGet (0.00s)
=== RUN   TestDelete
--- FAIL: TestDelete (0.00s)
	trie_test.go:127: expected 5991bb8c6514148a29db676a14ac506cd2cd5775ace63c30a4fe457715e9ac84 got bb50ddeadbabd5f63b2aabd919ab48847170debcd9ebcebcb8207103b32afb25
=== RUN   TestEmptyValues
--- FAIL: TestEmptyValues (0.00s)
	trie_test.go:151: expected 5991bb8c6514148a29db676a14ac506cd2cd5775ace63c30a4fe457715e9ac84 got bb50ddeadbabd5f63b2aabd919ab48847170debcd9ebcebcb8207103b32afb25
=== RUN   TestReplication
--- FAIL: TestReplication (0.00s)
	trie_test.go:175: expected to have horse => stallion
	trie_test.go:181: root failure. expected 15881a400d0ae2d110f06ff50e3fdb95d5655657d8a61e952e43411155af89d5 got 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421

What's going on here? Is this a known backwards compatibly hack?

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Mon Sep 14 19:24:27 UTC 2015_

**Comment by fjl** [comment]
trie and core/state are the last two places still using the old RLP functions in package common. 
#1405 moves trie to package rlp (among other changes). I'll update core/state and remove the old RLP
functions when the trie changes are on develop.

**Comment by fjl** [comment]
I know you are putting a lot of effort into these PRs. Please get in touch on Gitter before making larger changes like this so we can discuss their impact beforehand.

**Comment by fjl** [comment]
The failure in this PR is probably because trie nodes can't be encoded directly.

**Comment by jeffallen** [comment]
No problem. This wasn't a lot of effort. More just something I stumbled upon while browsing trying to see how it all fits together. I don't have a lot of time, so I can't really check in, sign up for something, and have you expect to receive it.

**Pull request closed without merging**
