### PR TITLE
Godeps: update all dependencies

### PR DESCRIPTION
**Pull request by fjl**
Stealing #2202 from @karalabe (as discussed) to include some fixes for the console.
Please try it out.

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Fri Feb 12 01:45:16 UTC 2016_

**Comment by bas-vk** [comment]
The new otto VM returns different types. This will cause the autocompletion to fail. You will need to replace `[]interface{}` with `[]string` here: https://github.com/ethereum/go-ethereum/blob/develop/cmd/geth/js.go#L100

**Comment by fjl** [comment]
@bas-vk PTAL

**Comment by bas-vk** [comment]
@fjl The autocompletion returns now an incomplete list. For example, `web3.<tab><tab>` wont give the `fromWei` method back while the old implementation does.

**Comment by fjl** [comment]
@bas-vk PTAL again

**Comment by bas-vk** [comment]
:+1:

**Comment by karalabe** [comment]
I'd vote for getting this is as soon as possible. Things shouldn't break unexpectedly and if they do, there's not much we can do to catch it with a review. If it's in the codebase then everyone's using it and we can find errors (i.e similar to the RPC merge). So from my part :+1:

**Pull request merged**
