### PR TITLE
cmd/geth: remove copydb command

### PR DESCRIPTION
**Pull request by holiman**
Removes the `geth copydb` command. It's pretty broken, 

> There were two errors that had borked it:
>
>1.    The pruning makes it likely to fail, since it serves the head block, but the client tries to sync at head-64. However, we usually do have head-127, so as long as we pretend that head-127+64 is the latest block, things works smoothly.
>2.    The fast-sync-server implementation in fakePeer hadn't been rewritten to handle separation of code and state.

- see https://github.com/ethereum/go-ethereum/pull/22203#issuecomment-764990869
- see https://github.com/ethereum/go-ethereum/issues/19266 

Also, with the new offline pruner, there's not much point in fixing up copydb.

### CODE REVIEW

**Comment by holiman** [comment]
Closes https://github.com/ethereum/go-ethereum/issues/19266

**Comment by karalabe** [comment]
Can you also nuke downloader.FakePeer?

**Comment by holiman** [comment]
Aye, done!

**Review by karalabe — APPROVED** [review]
SGTM

**Pull request merged**
