### PR TITLE
p2p/rlpx: add more rlpx throughput benchmarks for different sizes

### PR DESCRIPTION
**Pull request by ferranbt**
This PR extends the current BenchmarkThroughput in the rlpx package to include more cases for different send/receive sizes.

### CODE REVIEW

**Comment by fjl** [comment]
What's the point of these additional benchmarks?

**Comment by ferranbt** [comment]
A single benchmark is not useful to know how the optimizations in the p2p layer behave along the span of all the available transfer sizes.

**Comment by fjl** [comment]
I think additional benchmarks are not needed. If you have ideas for additional optimizations in p2p/rlpx, I'm happy to review them.

**Comment by ferranbt** [comment]
Ok, thank you. I will close the PR.

**Comment by fjl** [comment]
Let me try to explain in more detail. I added the throughput benchmark when developing some optimizations. The idea behind this benchmark was measuring the per-frame constant overhead. We managed to reduce the overhead significantly.

I think that the benchmark frame size is not so important to measure because processing of frame data cannot be sped up more: we perform AES encryption on the entire frame, and hash the entire frame for MAC. If you make the frame larger, this will take longer. IMHO we cannot learn more from benchmarks than that.

**Pull request closed without merging**
