### PR TITLE
go.mod : chainhash indirect lb version upgrade

### PR DESCRIPTION
**Pull request by ucwong**

### CODE REVIEW

**Comment by fjl** [comment]
Is it important to upgrade this version?

**Comment by ucwong** [comment]
> Is it important to upgrade this version?

Not necessary,  it fixed issue when I used latest golang1.18 in go.mod

**Comment by chappjc** [comment]
`go mod tidy` with go 1.18 is not adding these lines for me.
I'm curious what issue was fixed by this.  Seems like something the consumer app would address with it's own require statement to hoist the version?  If it turns out to be necessary, the btcec require could be bumped to v2.1.3 (which requires chainhash 1.0.1).

**Comment by holiman** [comment]
I'm using go `1.18` too, and `go mod tidy` did not do these changes for me either. I'll close this now, please reopen if you figure out more about why this happens, and why this is correct.

**Comment by Dmdv** [comment]
> Looks like explicitly adding this indirect require can smooth out an import ambiguity for certain consumers. [btcsuite/btcd#1839 (comment)](https://github.com/btcsuite/btcd/issues/1839#issuecomment-1090417191) The consumers can add the require in their own go.mod but apparently there is an ambiguity since that chainhash package now exists in two different modules? Not clear what go versions stumble on this. In any case, it's resolvable by the consumers.

Not working anyway
https://github.com/btcsuite/btcd/issues/1839#issuecomment-1099874265

**Comment by chappjc** [comment]
Try again with "btcsuite" in the url.

**Comment by fjl** [comment]
Merged https://github.com/ethereum/go-ethereum/pull/24700 instead. Everyone affected, please retry `go get github.com/ethereum/go-ethereum` in your modules.

**Comment by chappjc** [comment]
Heads up that the resolution for the "ambiguous import" issue that consumers of both go-go-ethereum and btcd hit is to use the newly-pushed [`v0.22.1` btcd tag](https://github.com/btcsuite/btcd/releases/tag/v0.22.1).  @ucwong

**Pull request closed without merging**
