### PR TITLE
cmd/geth: change ctrl-c behaviour

### LINKED ISSUE #1573: When in the console, Ctrl+C should clear the current line, not exit the program
In Bash Ctrl+C clears the current line, so I am familiar with that, but in Geth when I do this it exits the console and I loose my JS state.

Ideally it would work the same as Bash.

Ctrl+D should exit Geth console

### PR DESCRIPTION
**Pull request by obscuren**
ctrl-c clears the line, ctrl-d will quit the program.

Closes #1573

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Tue Aug 11 16:54:00 UTC 2015_

**Comment by obscuren** [comment]
One issue with this PR is that the indenting is not cleared. Looking in to this

**Comment by bas-vk** [comment]
Geth attach initializes the jsre slightly different in `newLightweighJSRE`. Remove the `lr.SetCtrlCAborts(true)` statement in that function also.

**Comment by obscuren** [comment]
Please pick this up @bas-vk I'll close this PR.

**Pull request closed without merging**
