### PR TITLE
params: add verkle witness costs

### PR DESCRIPTION
**Pull request by gballet**
Continuing on a series of small, easily reviewable PRs that make reviewing the final verkle PR easier: this PR simply adds the costs associated to Witness management to the list of gas costs.

### CODE REVIEW

**Review by MariusVanDerWijden — APPROVED** [review]
SGTM

**Comment by fjl** [comment]
I think it's a bit weird to add these now, without any context. 

I understand you are trying to simplify the verkle change, but this is not the way. We should definitely separate out refactoring changes which are necessary for verkle, as you have already done. If you need any new functionality in existing subsystems, we could also add it before the main change comes to review.

However, these constants are very much tied to the code that uses them, and so it won't make it much easier to review. Nobody will be mad at you for including 7 more lines in your PR.

**Comment by gballet** [comment]
the problem isn't that it's 7 lines as much as there is a lot of contention for these 7 lines, and so every time I rebase this clashes with something.

**Comment by fjl** [comment]
You can just define these in their own file then, to avoid the conflict. Like `params/verkle.go`.

**Comment by karalabe** [comment]
Myeah, I kind of agree with Felix here. With the BlobTx stuff, we're also only adding params at the rate of actually using them, even though we could have added all 12 or so from the get go.

**Pull request closed without merging**
