### PR TITLE
core/vm: set tracer-observable `value` of a delegatecall to match parent `value`

### PR DESCRIPTION
**Pull request by ziogaschr**
This PR has been created after request at https://github.com/ethereum/go-ethereum/pull/26377#issuecomment-1420912600

### Backwards compatibility

This is a breaking change in the tracing hooks API as well as semantics of the `callTracer`:

- `CaptureEnter` hook provided a nil `value` argument in case of DELEGATECALL. However to stay consistent with how delegate calls behave in EVM this hook is changed to pass in the value of the parent call.
- `callTracer` will return parent call's value for DELEGATECALL frames.

### CODE REVIEW

**Comment by s1na** [comment]
I'm considering setting the value directly to the hook in EVM. I.e. changing this:

https://github.com/ethereum/go-ethereum/blob/2f73f4f028e4bce5e804583d8ccd0cf5ecaf27be/core/vm/evm.go#L318
 
To:

```go
evm.Config.Tracer.CaptureEnter(DELEGATECALL, caller.Address(), addr, input, gas, caller.(*Contract).value)
```

Then all tracers would inherit this value. IMO this is right behavior, but this potentially affects people's scripts

**Comment by s1na** [comment]
I think we should make this change, since the whole `CaptureEnter` hook is a relatively new API.

**Comment by ziogaschr** [comment]
It's indeed fairly new, and it will return what's true.
Lucky shot is that nobody will have a check like `value == nil`, as it doesn't make sense in this context.

Give me the green light and I will change this, or feel free to commit the change :)

**Comment by holiman** [comment]
```
Start: from 000000000000000000000000000073656e646572 to 000000000000000000000000000000000000ff0a, value: 0x1337
  pc 0, op PUSH1, stack []
  pc 2, op PUSH1, stack [0x0]
  pc 4, op PUSH1, stack [0x0,0x0]
  pc 6, op PUSH1, stack [0x0,0x0,0x0]
  pc 8, op PUSH2, stack [0x0,0x0,0x0,0x0]
  pc 11, op GAS, stack [0x0,0x0,0x0,0x0,0xff0b]
  pc 12, op DELEGATECALL, stack [0x0,0x0,0x0,0x0,0xff0b,0x98966f]
   pc 0, op CALLVALUE, stack []
   pc 1, op ISZERO, stack [0x1337]
   pc 2, op STOP, stack [0x0]
  pc 13, op STOP, stack [0x1]

```
I wanted to verify that indeed, that's how the EVM works, it uses the parent callvalue for the `CALLVALUE1 op.

**Comment by s1na** [comment]
From goerli [tx](https://goerli.etherscan.io/tx/0xb6d12278b873d7ca888afbe3273cb76fa113c8058021775f5c9924103e2c6307):

```json
{
    calls: [{
        from: "0x5b9ae6234cf1e447680c245200e066091e631bf3",
        gas: "0x649",
        gasUsed: "0x30b",
        input: "0x",
        to: "0x54ded98a6720eceaa54eb0f858c81737cde9ff9e",
        type: "DELEGATECALL",
        value: "0x650e1ca0690e"
    }],
    from: "0x26b17999f109b3ee24ef26a60495d5c583f3ee6f",
    gas: "0x8fc",
    gasUsed: "0x5cb",
    input: "0x",
    to: "0x5b9ae6234cf1e447680c245200e066091e631bf3",
    type: "CALL",
    value: "0x650e1ca0690e"
}
```

**Review by holiman — APPROVED** [review]
LGTM

**Review by s1na — APPROVED** [review]
LGTM! tests passed, only an unrelated flaky one failed. I restarted CI and will merge on green. Then merge this into #26377  and that will be ready to go too.

**Pull request merged**
