### PR TITLE
trie: merkle proofs

### PR DESCRIPTION
**Pull request by ebuchman**
Here's a first take at merkle proofs for the trie.

The basic idea is to fetch and store all the ShortNodes and FullNodes along the path to a given value. We don't store the ShortNode's value or the relevant branch of the FullNode, as they will be overwritten during verification. Both nodes are represented by a common ProofNode type, which holds a key and a slice of byte-slices. If the slice is nil, it's a ShortNode. RLP handles the rest. 

I also added lots of comments. 

I included a test for bad proofs, whereby I just mutate a byte in the rlp encoded proof before decoding back to a proof struct. Note I had to be careful with mutating bytes `128` and `32` because of apparent indeterminacy in rlp (ie. you can mutate those bytes and everything will still be fine)

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Sat Aug 8 19:28:10 UTC 2015_

**Comment by ebuchman** [comment]
Apologies on failure to communicate that I was going to do this, if someone is already working on it. I started late last night for the fun and figured I'd see it through regardless.

**Comment by obscuren** [comment]
Awesome effort. Minor thing, please see https://github.com/ethereum/go-ethereum/pull/1405 it's the new trie. Would be awesome if you could base it on that! :)

**Comment by ebuchman** [comment]
Yup I reviewed that and tried to make sure to avoid conflicts. What's the status on that PR? presumably it needs to be rebased itself? Shall I take lead on it and we'll just merge it all through this PR?

**Comment by fjl** [comment]
I'll pick up #1405 tomorrow. Will merge your stuff into it.

**Comment by ebuchman** [comment]
Thanks!

**Comment by fjl** [comment]
Sorry, didn't get to it yet. But I promise that today and tomorrow will be spent on getting the trie PR ready.

**Comment by fjl** [comment]
This is now part of #1405.

**Pull request closed without merging**
