### PR TITLE
console: allow optional password on the command line

### PR DESCRIPTION
**Pull request by bas-vk**
This PR will allow users to supply a password as argument when creating a new account with `personal.newAccount`. This is useful for scripts.

It also addresses a problem with single quotes in the password which where not escaped.

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Tue Mar 8 13:55:46 UTC 2016_

**Comment by karalabe** [comment]
@LefterisJP Could you take a stab at your problem with this?

**Comment by karalabe** [comment]
LGTM :+1:

**Comment by obscuren** [comment]
:+1:

**Comment by LefterisJP** [comment]
:+1: this is exactly what I needed. Thanks for addressing this so quick.

**Pull request merged**
