### PR TITLE
tests/solidity: add contract to test every opcode

### PR DESCRIPTION
**Pull request by lhendre**
This is creating a byte code for quickly testing all of the op codes.  This is a work in progress.  It is likely to look very different when complete, the main request is for the byte code.  I have included the smart contract itself and the tests to get feedback and to help answer questions I have.  #18210

### CODE REVIEW

**Comment by lhendre** [comment]
The purpose of this was to grab the byte code of a smart contract that can be used to test all of the opcodes.  I have the byte codes, but I am not positive on how to wrap this up.  I have made this available as a string in a js file, but I can make it available elsewhere.  Additionally, how do we want to document it?  For now, I have made the smart contract testable through truffle but my guess is that will change @adamschmideg

**Comment by lhendre** [comment]
@adamschmideg Let me know your thoughts, Im somewhat blocked at the moment till I can get some feedback or more details in the issue.  If your busy could you help get someone else to review?

**Comment by lhendre** [comment]
@fjl could you help me get a review.  This is related to issue #18210 and I could use some help finalizing it

**Comment by lhendre** [comment]
Hi @fjl  let me know how you would like this wrapped up.  I have the byte code but I am not sure where to put it and how we want this document.  I have included the tests and smart contract itself to provide information on what the contract actually does, I am planning on removing that.

**Comment by lhendre** [comment]
Any update @fjl ?

**Comment by fjl** [comment]
Hi, sorry for the slow review. It's absolutely great you put in the work to make the contract. We'll figure out how to integrate it but it might take a while.

**Comment by lhendre** [comment]
No problem @fjl , is there a time period I should check back in then?

**Comment by fjl** [comment]
It's fine the way it is now. This PR won't go away and we'll pick it up eventually.

**Comment by holiman** [comment]
Thanks @lhendre, and sorry it took so long. We still need to figure out how and where to use it in our build and test-pipeline, but we can figure that out later

**Comment by lhendre** [comment]
@holiman  and @fjl  no problem just glad it got done!

**Pull request merged**
