### PR TITLE
xeth: call fix when doing 'create'-like calls

### PR DESCRIPTION
**Pull request by obscuren**
When doing a call use the `2**256` as a mix for `eth_call`. This should also give the correct estimate regardless of the current gas limit

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Thu Aug 13 14:37:52 UTC 2015_

**Comment by tgerring** [comment]
:+1:

**Comment by frozeman** [comment]
doesn't  work yet

**Comment by frozeman** [comment]
Sending data like `0xf` returns a 3mio gas estimate. I will try now contracts etc.

**Comment by frozeman** [comment]
Ok i tested contract creation:

Original wallet:
estimate: 1 172 182
used: 1 187 182

Stub Wallet contract
estimate: 141 294
used: 141 294

When i send dummy random data i get 3 000 000 estimate, does that mean it would eat up 3mio, if i send dummy data as well?

I still seems like some small things are not counted in, there fore the difference in the original contract. Maybe thats the storage cost to store the data itself?

**Comment by frozeman** [comment]
Normal transaction with some money: :+1: 
Estimate: 29,228
used: 29,228

Wallet contract execution below daily limit: :+1: 
Estimate: 54280
actual: 54280

Wallet contract over daily limit: :+1: 
Estimate: 171032
used: 171032

**Comment by obscuren** [comment]
Dummy random data will be run in the VM and will fail due to an error (either unknown opcode or out of gas or some other illegal op execution) resulting in all ether being used

**Comment by obscuren** [comment]
> Original wallet: :-1: 
> estimate: 1 172 182
> used: 1 187 182

Are you sure this is correct? The others seem alright

**Comment by frozeman** [comment]
I will test again, but i'm pretty sure

**Comment by frozeman** [comment]
When providing incorrect or dummy data i recommend returning the minimum of 21000 gas not the maximum of 3mio

**Comment by obscuren** [comment]
@frozeman PTAL the default gas for all `eth_call`s is now set to max `2^256`

**Comment by frozeman** [comment]
ok, please let me try on monday and we can merge.

**Comment by frozeman** [comment]
Ok made a quick test and i now get `Error: insufficient ETH for gas`, so it seems like simply setting the default gas very high, is not enough :(

**Comment by obscuren** [comment]
@frozeman PTAL. I've decreased the default gas to `50.000.000`

**Comment by frozeman** [comment]
So you need at least `2.5` ether at a gas price of `50` shannon, on your account, so that the gas estimate works. hmmm. maybe works for the time being, but we should have a better solution for the future

**Comment by frozeman** [comment]
Ideally the estimate and call functions don't take the eth balance into account.

**Comment by obscuren** [comment]
Not possible

**Comment by obscuren** [comment]
The account is also front loaded with `2**256` ether during call and estimateGas

**Pull request merged**
