### PR TITLE
accounts/keystore: add ImportRawKey method

### PR DESCRIPTION
**Pull request by iyume**
Provide golang way to import raw key from other wallets.

Related to #24469.

### CODE REVIEW

**Review by fjl — COMMENTED** [review]
I think this method is redundant and not worth adding. You'd only be saving three lines of code with this.

**Comment by karalabe** [comment]
It's not that the proposed functionality isn't useful, but it's not enabling anything new at the expense of introducing more code to support. Yes, it's a tiny thing, but these tend to grown in time.

**Comment by iyume** [comment]
> I tend to agree with @fjl here. File handling should ideally not be done by library packages since they always get messy, or at least absolutely minimize it. Reading the file from the outside and calling the already existing method is cleaner and also generally having only one was of doing things keeps the API surface smaller.

I replace the `crypto.FromECDSA` to `crypto.HexToECDSA`. The implementation has no file handling now.

```go
// ImportRawKey loads the given raw hex key and stores it into the key directory, encrypting it with the passphrase.
func (ks *KeyStore) ImportRawKey(hexkey, passphrase string) (accounts.Account, error) {
	priv, err := crypto.HexToECDSA(hexkey)
	if err != nil {
		return accounts.Account{}, err
	}
	return ks.ImportECDSA(priv, passphrase)
}
```

Can you consider reopen the PR?

**Comment by fjl** [comment]
But what's the point of this method, when you can just parse the key yourself before adding it? 

The way we see it, there are many ways to parse the key into the canonical representation (which is `*ecdsa.PrivateKey` in go-ethereum), and we think having a single method that imports a key that is in the canonical representation is enough.

**Comment by iyume** [comment]
> there are many ways to parse the key into the canonical representation

Metamask exports `secp256k1` key and it is supported by kind of libraries (like https://github.com/starkbank/ecdsa-python).

> we think having a single method that imports a key that is in the canonical representation is enough

That is very OK! I just open this PR for user convenience.

**Pull request closed without merging**
