### PR TITLE
console: cleanup old autocompletations relics

### PR DESCRIPTION
**Pull request by bas-vk**
The current console determines at runtime which are valid auto completions. The old hard coded definitions can be removed as well as some of the RPC calls which where not migrated into the new RPC layer. This PR removes them.

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Tue Mar 1 17:29:40 UTC 2016_

**Comment by fjl** [comment]
:+1:

**Comment by winsvega** [comment]
looks good

**Comment by karalabe** [comment]
LGTM :+1:

**Pull request merged**
