### PR TITLE
eth/filters: send rpctransactions in pending-subscription

### PR DESCRIPTION
**Pull request by holiman**
This PR is an alternative to https://github.com/ethereum/go-ethereum/pull/26034. This PR keeps the internal objects as `*types.Transaction`, and mutates it into rpc.Transaction right before it's sent on the wire. 

At least I think it does, I haven't fully verified it (yet).

### CODE REVIEW

**Comment by s1na** [comment]
Example response:

```js
{
  blockHash: null,
  blockNumber: null,
  from: '0x21a31ee1afc51d94c2efccaa2092ad1028285549',
  gas: '0x32918',
  gasPrice: '0x202170e400',
  maxFeePerGas: '0x202170e400',
  maxPriorityFeePerGas: '0x77359400',
  hash: '0xde8f7e26fd9dc0157c8dfb8d6742a50ee1d13077f7eb675a8b9de42374ad4e6d',
  input: '0xa9059cbb000000000000000000000000a055bdc23d5f8fa59214b18a4c892d2be87d2cc200000000000000000000000000000000000000000000000
0000000001b774000',
  nonce: '0x487572',
  to: '0xdac17f958d2ee523a2206206994597c13d831ec7',
  transactionIndex: null,
  value: '0x0',
  type: '0x2',
  accessList: [],
  chainId: '0x1',
  v: '0x1',
  r: '0x93a2c41a452a8ad03c7e31e12608650205f7b2ab8f73bef174fdb28a046ccaa8',
  s: '0x74c0b4b811807c1cb066e7082dcc9341acbeff68fcd2653c9e21e82c45e1720c'
}
```

Only thing is `blockHash`, `blockNumber` and `transactionIndex` will always be null for pending txes. But adding `omitempty` rules to `RPCTransaction` type will also change the result of `getTransactionByHash` for pending txes, so I guess it's best to keep as is.

**Review by s1na — APPROVED** [review]
LGTM

**Comment by s1na** [comment]
Ah gethclient's method might need to change

**Comment by holiman** [comment]
> Update: seems to work. I think because the JSON encoding of a rpc transaction is unmarshalable to types.Transaction. 

Could you clarify this a bit? I don't understand if there's anything we need to address here

**Comment by s1na** [comment]
To clarify, IMO no change needed for gethclient. PR looks good to me!

**Pull request merged**
