### PR TITLE
rpc: client bug fixes

### PR DESCRIPTION
**Pull request by fjl**
I found these issues while working on ethclient.

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Fri Aug 5 18:11:39 UTC 2016_

**Comment by bas-vk** [comment]
LGTM 👍 (did not tried it).

**Comment by fjl** [comment]
@karalabe PTAL

**Comment by awishformore** [comment]
Reviewed it and it looks good, but I don't quite understand the advantage of using a circular buffer over using a buffered channel. Couldn't you accomplish the same thing by simple attempting a send on a channel buffered to 8000 and dropping the client when it fails in the default case?

**Comment by fjl** [comment]
Yes but channel buffers are static, so the memory would be consumed even for subscriptions that are read all the time.

**Comment by awishformore** [comment]
OK, makes sense, thanks.

**Comment by karalabe** [comment]
LGTM :+1:

**Pull request merged**
