### PR TITLE
eth: return the statedb after ApplyMessage inside api_tracer

### PR DESCRIPTION
**Pull request by jsvisa**
The `statedb` is parent's, so it should be ApplyMessage,
then with `statedb.Finalise` to get a new one.

### CODE REVIEW

**Comment by jsvisa** [comment]
@karalabe PTAL

**Comment by holiman** [comment]
This change makes it so that if you want to trace a transaction, you will actually trace it on a state where it already has been applied, doesn't it?

**Comment by jsvisa** [comment]
@holiman Sorry, I modify the wrong code. I'm using the `StorageRangeAt` API, seems is a bug there, [go-ethereum/api.go at master · ethereum/go-ethereum](https://github.com/ethereum/go-ethereum/blob/master/eth/api.go#L353-L386) directly return the storage back, but which is the preview storage of the tx is executed. Please let me know what I've missed.

**Comment by jsvisa** [comment]
@holiman fixed, please take another look.

**Comment by holiman** [comment]
Again, 

> This change makes it so that if you want to trace a transaction, you will actually trace it on a state where it already has been applied, doesn't it?

That comment is still relevant, right? And if so, this change changes the semantics of the api call. Not sure we want to do that, people might already rely on the semantics of that call. 

Is there also some other actual error this PR fixes?

**Comment by holiman** [comment]
In essence, can't you solve your problem/usecase by just adding `1` to the txindex?

**Comment by adamschmideg** [comment]
This PR seems abandoned, no response to the last comments for a long time.

**Comment by karalabe** [comment]
If there's an issue with StorageRangeAt, please open an issue with a repro and we can take a look.

**Pull request closed without merging**
