### PR TITLE
Fix tests on windows

### PR DESCRIPTION
**Pull request by fjl**
The tests were panicking on windows due to a memory issue (first commit).
Most other failures were related to use of package filepath or hard-coded `/tmp`.
They work now: https://build.ethdev.com/builders/Windows%20Go%20pull%20requests/builds/1190/steps/go-test/

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Thu Aug 6 14:34:27 UTC 2015_

**Comment by fjl** [comment]
https://build.ethdev.com/builders/Windows%20Go%20pull%20requests/builds/1188/steps/go-test

**Comment by obscuren** [comment]
:+1: altho I have no idea what was broken, the code seems legit

**Comment by Gustav-Simonsson** [comment]
I also have no idea what this really fixes, but looks OK :D :+1:

**Comment by fjl** [comment]
https://build.ethdev.com/builders/Windows%20Go%20pull%20requests/builds/1184/steps/go-test/logs/stdio is what this fixes. Nobody notices these regressions because the windows builder doesn't consider test failures when showing the green mark.

**Comment by tgerring** [comment]
@fjl Now that this is merged, should we turn fail Windows builds on test errors?

**Comment by fjl** [comment]
Sure, would be nice.

**Comment by tgerring** [comment]
Pinging @caktux to update Windows configuration

**Pull request merged**
