### PR TITLE
vendor/gopkg.in/olebedev/go-duktape.v3: Fix overflown callstack trace bug

### PR DESCRIPTION
**Pull request by linuxion**
During the development of the Ethereum block explorer, we came across the problem described in [this issue](https://github.com/ethereum/go-ethereum/issues/16426).

The problem was in the [config](https://github.com/olebedev/go-duktape/blob/v3/duk_config.h) of [go-duktape library](https://github.com/olebedev/go-duktape). When call [call_tracer](https://github.com/ethereum/go-ethereum/blob/master/eth/tracers/internal/tracers/call_tracer.js) + `debug.traceTransaction` on a transaction with a large nesting of CALLs, Geth calls the `JsonEncode` function from the go-duktape library but reaches the [DUK_USE_JSON_ENC_RECLIMIT = 1000](https://github.com/ethereum/go-ethereum/blob/master/vendor/gopkg.in/olebedev/go-duktape.v3/duk_config.h#L2928) and fails. The increase of `DUK_USE_JSON_ENC_RESCLIMES`, `DUK_USE_JSON_DEC_RECLIMIT`, and `DUK_USE_NATIVE_CALL_RECLIMIT` to 16384 (I do not know why the smaller values did not work, max depth was only 1026), solved the problem.

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 73e5cf9e4ef7718496ec5a37f31e0b19b9924dc3
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by holiman** [comment]
The fix itself looks good to me, but I don't know how well it will work to manually patch a 'vendored' dependency. We use `govendor` for dep management, which becomes affixed to a certain commit-hash. If we want to manually modify an import, we somehow need to keep track of that, and probably not use `govendor` on that import. @karalabe ideas?

**Comment by karalabe** [comment]
Ah, this is definitely a problem. We can't change vendored code as a next fetch will just overwrite it.

Could we perhaps open an issue on the upstream duktape lib and ask them why the decision was made for 1000?

**Comment by karalabe** [comment]
Ah, I also figured out why we can't accept it into the vendored library. Because if you build on top of go-ethereum from Go, the vendored packages aren't retained, rather they are revendored in your own project based on the specified versions, so your package will not have the fix.

Our solution currently is:

 * Have this fixed upstream
 * Fork the repo and fix it in that
 * Inline the dependency and use that

The latter two loses us the updates, so it's not really a good idea. Either way, I'll close this PR as it's not really possible to get it merged safely.

**Pull request closed without merging**
