### PR TITLE
ErrInvalidPubKey; machine-readable account list output

### PR DESCRIPTION
**Pull request by ebuchman**
Just a few very simple things:

1) `geth account list <N>` for machine readable output of account `<N>`

2) use an ErrInvalidPubKey variable in pubkey recovery

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Sat Jan 30 00:12:35 UTC 2016_

**Comment by karalabe** [comment]
I'm really split on this. Although I see the value of machine readable output, I'm not sure the best course of action is to rig the CLI subcommand to output in a different format for an arbitrary parameter input. Wouldn't it be simpler to either use an RPC endpoint or to query the information from the javascript API?

`geth --exec 'eth.accounts' console 2>/dev/null`

**Comment by ebuchman** [comment]
Fair point. My use case was to get the address so I can make a genesis.json file automatically, so I don't even have a running or configured geth yet. Having to boot into console to get that seemed overkill.

**Comment by obscuren** [comment]
I agree with @karalabe (we've actually had a discussion about this)

I don't think that `geth` should be turned in to some Swiss Army knife. Geth is a way to interact with the network and is meant as entry point in to the network and is certainly not your average utility; however it does provide you with the tools to build and develop anything that is apperant missing for your particular use case (up to a certain point of course).

Geth's JavaScript enabled REPL is a powerful tool, I suggest you make use of it :-)

> Having to boot the into the console to get that seems overkill

Your PR vs the one-liner provided by Peter seems hardly overkill to me.

**Comment by karalabe** [comment]
OP has a point that booting Geth does require a fair amount of overhead, which shouldn't be needed for only accessing and managing the accounts. However as long term the ideal would be to have apps manage their own accounts and not use geth-central accounts, I still think that an occasional workaround is better than an extra CLI API maintenance point.

**Comment by obscuren** [comment]
> OP has a point that booting Geth does require a fair amount of overhead, which shouldn't be needed for only accessing and managing the accounts

Which probably means there should be an extraction tool and I don't think it would be that hard to write if you rip out some of the code.

**Comment by obscuren** [comment]
And that's exactly what I mean with swiss army knife. It isn't required for normal operation, and even so you can write it in alternative ways. It's the like saying "lets add features to ethereum because contracts are an overhead".

**Comment by karalabe** [comment]
I'll close this PR as deemed not going in. Btw, if you parse json output, then the accounts can be retrieved even without logging to the console, simply with `geth --exec "eth.accounts" console`.

There was a second modification in your code that separated out the ErrInvalidPubKey. If you need that for anything, I think it should be fine to do that in another PR.

**Comment by ebuchman** [comment]
Yes fair points. Thanks for the responses. The exec command works fine. I will open a new PR with the ErrInvalidPubKey since I started using that.

One thing that has always bothered me with ethereum design is the fact that it's so monolithic, and especially the fact that key management is baked into the network daemon. I think something like what btcd did would be much preferable, in terms of separation between the core daemon process and the wallet process, and the user talks to the wallet RPC. 

Is there a strategy to bust up the monolith moving forward, and make the thing more modular? In particular, I'm interested in seeing the geth application state run above alternative consensus mechanisms - I have implemented a prototype of geth 1.3.3 running above tendermint here: https://github.com/eris-ltd/geth-tmsp.  Would be happy to discuss this further if there is interest.

**Comment by obscuren** [comment]
We're discussing (though mainly internally) to remove key management entirely from geth, we agree this was bad design.

**Pull request closed without merging**
