### PR TITLE
Enable WASM compilation when importing `github.com/go-ethereum/signer/core`

### PR DESCRIPTION
**Pull request by fabioberger**
At 0x we are building a P2P node that compiles to WASM and can run in the browser. While trying to import `github.com/go-ethereum/signer/core` as a project dependency, we noticed that it caused our WASM tests to fail, since its `github.com/go-ethereum/internal/ethapi` dependency was attempting to pull in `leveldb`. 

This PR addresses the issue by moving `PrivateDebugAPI` (the only part of `ethapi` requiring `leveldb`) into it's own file, and adding the `// +build !js` build flag to it, so that it does not get compiled when targeting WASM.

Is WASM support something the Geth team is interested in supporting?

### CODE REVIEW

**Comment by karalabe** [comment]
Hmmm, I think I've made these functionality into an interface so there's no need to cast to leveldb any more. Lemme check.

Yup, all databases implement the `Stater` and `Compacter` interfaces https://github.com/ethereum/go-ethereum/blob/master/ethdb/database.go#L40, so you should be able to directly call those methods without a cast.

**Comment by fabioberger** [comment]
Thanks for the reply @karalabe. I was able to remove the cast to the `leveldb` type, but I still was unable to compile to WASM. It turns out `leveldb` is still being pulled in by:

- `github.com/ethereum/go-ethereum/eth/downloader`
- `github.com/ethereum/go-ethereum/core`
- `github.com/ethereum/go-ethereum/ethdb`

In `backend.go` and:

- `github.com/ethereum/go-ethereum/core/rawdb`

in `api.go`.

Additionally, `golang.org/x/crypto/ssh/terminal` in `cliui.go` also caused the WASM compilation to fail. 

I added additional `// +build !js` flags in the above files and was able to get WASM to compile. Are there better places for me to put this excludes?

**Comment by gballet** [comment]
@karalabe any thought's on Fabio's response?

**Comment by albrow** [comment]
@gballet @karalabe It's been a while. Any updates for us?

**Comment by gballet** [comment]
@fabioberger @albrow could you please fix the build errors and rebase, if you want us to have another look at it?

**Comment by fabioberger** [comment]
@gballet we working on fixing the conflicts and will have something for you to review soon.

**Comment by fabioberger** [comment]
@gballet this PR has been rebased and fixed given the most recent changes to `master`. The CI failure seems to be an unrelated race-condition error. Please let me know if you need anything else from us.

**Comment by holiman** [comment]
I'm not too fond of this. It 'randomly' ( yes, I know, it 's not random) moves certain things into a huge dump of "things we don't want to build" and moves certain other things into the file "things we want to build". But there's no real red thread that correlates what goes where, other than what can be built on js.

**Comment by karalabe** [comment]
We should try to solve the dependencies instead of moving code around and excluding them from builds. E.g. `ethdb` is a generic database interface package. If we use that, we completely remove `leveldb` depndency and solve this, without disabling code.

**Comment by karalabe** [comment]
This PR moves way tooo much code around. We're not convinced it's a good solution really. Probably there is 1 or 2 types or imports that cause the cascading imports, so those should be identified and worked around, not this much code in itself.

E.g. The signer imports external which pulls in some type from intneral. If we solved this single reference from `external` to `internal`, I think most of the issues should be solved. More info at https://github.com/ethereum/go-ethereum/issues/20535

**Pull request closed without merging**
