### PR TITLE
Access list state test format

### PR DESCRIPTION
**Pull request by MariusVanDerWijden**
Updates marshalling and execution for the new access list format in the state tests

depends on https://github.com/ethereum/go-ethereum/pull/21502

### CODE REVIEW

**Comment by holiman** [comment]
On this PR, are you able to execute the tests in https://github.com/ethereum/tests/pull/774 ?

**Comment by holiman** [comment]
Rebased

**Comment by holiman** [comment]
```
[user@work evm]$ ./evm statetest ../../tests/testdata/GeneralStateTests/stEIP2930/addressOpcodes.json 
json: cannot unmarshal string into Go struct field stJSON.transaction of type tests.stData
```

**Comment by MariusVanDerWijden** [comment]
It passes the newest version (https://github.com/ethereum/tests/pull/774/commits/0966f56536511200326e5ca939385da462730240) of the ethereum/tests flawlessly!

**Comment by holiman** [comment]
Obviously this will need a rebase, and it's a bit hard to see the changes -- but did you add the new tests? If not, please add the updated tests (or maybe wait until they've been merged to master)

**Comment by MariusVanDerWijden** [comment]
Didn't add the tests yet, will do once they merge

**Pull request merged**
