### PR TITLE
eth: fixed incorrect storage from prestate_tracer

### PR DESCRIPTION
**Pull request by mafrasi2**
`prestate_tracer` didn't handle this storage access scenario correctly:

1. before the transaction the storage at a specific key is 0
2. SLOAD results in a 0, but the tracer doesn't record it because this was special cased
3. a SSTORE modifies the storage and again the tracer doesn't record the previous value, because it's 0
4. when another SSTORE occurs, the tracer records the value set by the SSTORE in 3 as prestate entry, even though the SLOAD before loaded the real prestate entry (which is 0).

Simply removing the special case in 2. fixed this problem.

**Edit:**
I created a small example contract to demonstrate this behavior [here](https://rinkeby.etherscan.io/address/0x8e84228107a341de47ecf4e165e7ff6cc2ec4ca8). The `prestate_tracer` generates an incorrect prestate storage entry for the [corresponding transaction](https://rinkeby.etherscan.io/tx/0x8fad6ee6c345120bbaa715202e4d338aa370db8fa9f574872e3441d852037eea):
<details>
<summary>Current prestate_tracer result</summary>
<pre>{
  "0x8e84228107a341de47ecf4e165e7ff6cc2ec4ca8": {
    "balance": "0x0",
    "nonce": 1,
    "code": "0x6001546002600155600260015500",
    "storage": {
      <b>"0x0000000000000000000000000000000000000000000000000000000000000001": "0x0000000000000000000000000000000000000000000000000000000000000002"</b>
    }
  },
  "0xb6ae8c9e3e1dd4c3c13a467c2d09466b3ae08b12": {
    "balance": "0x29a4381bd9816000",
    "nonce": 5,
    "code": "0x",
    "storage": {}
  }
}</pre></details>
<details>
<summary>Correct prestate_tracer result</summary>
<pre>{
  "0x8e84228107a341de47ecf4e165e7ff6cc2ec4ca8": {
    "balance": "0x0",
    "nonce": 1,
    "code": "0x6001546002600155600260015500",
    "storage": {
      <b>"0x0000000000000000000000000000000000000000000000000000000000000001": "0x0000000000000000000000000000000000000000000000000000000000000000"</b>
    }
  },
  "0xb6ae8c9e3e1dd4c3c13a467c2d09466b3ae08b12": {
    "balance": "0x29a4381bd9816000",
    "nonce": 5,
    "code": "0x",
    "storage": {}
  }
}</pre></details>
<details>
<summary>Contract source code</summary>
<pre>PUSH 0x01
SLOAD
PUSH 0x02
PUSH 0x01
SSTORE
PUSH 0x02
PUSH 0x01
SSTORE
STOP</pre>
</details>

### CODE REVIEW

**Comment by holiman** [comment]
Lgtm! Needs regenerating the asset files, though.

**Comment by karalabe** [comment]
The bindata changes are fine. They are caused by a limitation we actually hit and reported upstream, causing the massive changes :)

**Comment by karalabe** [comment]
@mafrasi2 Ah, no. You possibly used the wrong go-bindata. We use https://github.com/kevinburke/go-bindata . You can get a correct up-to-date version by running `make devtools`.

**Comment by mafrasi2** [comment]
@karalabe Thanks, that makes sense and the diff is much smaller now :)

**Pull request merged**
