### PR TITLE
cmd, eth: switch the dev synctarget to hash from block

### PR DESCRIPTION
**Pull request by karalabe**
This PR switched the `--synctarget` flag from requiring a block RLP in a file (which is annoyingly hard to obtain) to just using a hash and retrieving everything else from the network.

`geth --synctarget 0x91c90676cab257a59cd956d7cb0bceb9b1a71d79755c23c7277a0697ccfaf8c4`

### CODE REVIEW

**Comment by holiman** [comment]
Cool
```
[user@work ~]$ geth --datadir ./tmp/deleteme --synctarget=0x165f73c83ca0393c988c8b4bbc2c62db6052ddd97697dbeb49c61c979a38a7e4 
INFO [09-28|10:58:26.835] Starting Geth on Ethereum mainnet... 
INFO [09-28|10:58:26.836] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [09-28|10:58:26.841] Maximum peer count                       ETH=50 LES=0 total=50

...
INFO [09-28|10:58:28.325] Waiting for peers to retrieve sync target 
INFO [09-28|10:58:28.440] Generated state snapshot                 accounts=8893 slots=0 storage=409.64KiB dangling=0 elapsed=225.272ms
INFO [09-28|10:58:30.966] New local node record                    seq=1,695,891,508,322 id=256353e9dc5ee98c ip=84.55.65.82 udp=30303 tcp=30303
INFO [09-28|10:58:38.356] Looking for peers                        peercount=0 tried=22 static=0
INFO [09-28|10:58:48.359] Looking for peers                        peercount=0 tried=29 static=0
INFO [09-28|10:58:52.339] Attempting to retrieve sync target       peer=6f0bf62ee28c9ad07a50b297bfad5af90879da6c7c57263ec08ff458d82d64a6
INFO [09-28|10:58:52.665] Syncing beacon headers                   downloaded=499 left=0 eta=0s
INFO [09-28|10:58:52.667] Block synchronisation started 
INFO [09-28|10:58:52.710] Imported new chain segment               number=2 hash=b495a1..4698c9 blocks=2 txs=0 mgas=0.000 elapsed=33.304ms  mgasps=0.000 age=8y3mo1w  snapdiffs=90.00B triedirty=4.74KiB
INFO [09-28|10:58:52.739] Imported new chain segment               number=3 hash=3d6122..8cf741 blocks=1 txs=0 mgas=0.000 elapsed=17.402ms  mgasps=0.000 age=8y3mo1w  snapdiffs=180.00B triedirty=9.09KiB
INFO [09-28|10:58:55.812] Imported new chain segment               number=201 hash=b840bb..374c8c blocks=198 txs=0 mgas=0.000 elapsed=3.014s    mgasps=0.000 age=8y3mo1w  snapdiffs=10.81KiB triedirty=388.81KiB
INFO [09-28|10:58:58.687] Looking for peers                        peercount=2 tried=32 static=0
INFO [09-28|10:58:59.640] Imported new chain segment               number=500 hash=165f73..38a7e4 blocks=299 txs=0 mgas=0.000 elapsed=3.827s    mgasps=0.000 age=8y3mo1w  snapdiffs=28.01KiB triedirty=425.07KiB
INFO [09-28|10:58:59.640] Snap sync complete, auto disabling 
WARN [09-28|10:59:00.890] Peer delivering stale transactions       peer=6f0bf62ee28c9ad07a50b297bfad5af90879da6c7c57263ec08ff458d82d64a6 rejected=104
WARN [09-28|10:59:01.936] Peer delivering stale transactions       peer=6c61a3069f4f71be0ad732b43bb00813cda0f6ecbe1d9bc54e095e9a0bb45bc1 rejected=128
WARN [09-28|10:59:02.137] Peer delivering stale transactions       peer=6c61a3069f4f71be0ad732b43bb00813cda0f6ecbe1d9bc54e095e9a0bb45bc1 rejected=116
```

**Comment by karalabe** [comment]
Erm, what's with snap sync in there? cc @rjl493456442

**Comment by karalabe** [comment]
Ah ok, it's unrelated to any changes. The original synctarget code **required** --syncmode=full. I just dropped that requirement and defaulted to it, but the node *thinks* it's snap syncing until done. Lemme see if I can hard swap the sync-flag out to full.

**Comment by karalabe** [comment]
@holiman PTAL

**Pull request merged**
