### PR TITLE
core: fixed various typos

### PR DESCRIPTION
**Pull request by leijurv**
Recreating pull request, accidentally based previous off master. "failed" was misspelled as "filed".

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Mon Mar 14 21:48:46 UTC 2016_

**Comment by karalabe** [comment]
Thanks for helping out in making our code better :)

A few tips:

 * We usually prefix our commit messages with the packages they touch. This allows quickly skimming the commit logs and finding stuff. So your commit (a bit more context) would become `core: fixed error log typo`.
 * To prevent filling the repository with half ready commits or accidental commits and fixes to them (e.g. just like you make and then corrected yourself), we require most PRs to be squashed into a single commit.

So to fix your PR, please:

 * Squash the two commits into one: `git rebase -i HEAD~2` (set the second to `fixup`)
 * Amend the commit message via `git commit --amend`
 * Update the PR with the fixed version: `git push -f <remote> <branch>`

Otherwise te PR is fine :)

**Comment by leijurv** [comment]
Okay, I squashed the commits and renamed to "core: fixed error log typo"

**Comment by karalabe** [comment]
LGTM :+1:

**Comment by leijurv** [comment]
I added some more, also squashed into the same commit

**Comment by obscuren** [comment]
Awesome, thanks! :+1:

**Pull request merged**
