### PR TITLE
accounts/abi: Provide DoNotSend flag in TransactOpts

### PR DESCRIPTION
**Pull request by mcdee**
At current there is no way to create but not send a transaction whose code has been generated with `abigen`.  This patch adds a `DoNotSend` flag to `TransactOpts` to provide this feature.

Adding this feature allows for such transactions to be created offline (e.g. on an airgapped PC) and broadcast to the network at a later date and/or from a separate computer.

### CODE REVIEW

**Comment by fjl** [comment]
IMHO it'd be better to modify abigen so all methods that send a transaction return an unsigned one instead. I've been bugging @karalabe about this since forever.

**Comment by VoR0220** [comment]
I would agree with @fjl that that would be the better approach.

**Comment by mcdee** [comment]
Although that might be a better long-term approach that sounds like a breaking change, or at least a fairly major alteration to abigen's template.  This has the benefit of being simple and causes no changes to existing behaviour.

**Comment by mcdee** [comment]
I'm going to close this PR and create a new one with changes to abigen to meet the above requests.

**Pull request closed without merging**
