### PR TITLE
eth/downloader: fix for Issue #16539

### PR DESCRIPTION
**Pull request by reductionista**
This fixes the deadlock introduced in [commit de2a7bb764c82dbaa80d37939c5862358174bc6e](https://github.com/ethereum/go-ethereum/commit/de2a7bb764c82dbaa80d37939c5862358174bc6e).

This was reported by several people in [Issue #16539](https://github.com/ethereum/go-ethereum/issues/16539), and by someone else in duplicate [Issue #16545](https://github.com/ethereum/go-ethereum/issues/16545).

This should probably be a hot fix to 1.8.4 "stable" as this bug is bad enough that it makes geth very unstable.  In particular, it causes geth to deadlock any time the master peer has an issue that causes it to get dropped by a fetcher.  These freezes happen most often during initial sync, but can also happen even after initial sync is done, as I've encountered myself.  Each time it freezes, killing and manual restart is required--often a regular SIGTERM or SIGINT is not enough to shut geth down after the deadlock happens.

I don't know for sure whether this is the best long-term solution, but I think it's at least better than either keeping the current commit or rolling it back.  If there is some desired functionality intended by the commit (such as having removePeer() block when called on the master peer externally) that's missing here, it would require a larger rewrite to include that while avoiding the deadlock.

### CODE REVIEW

**Comment by tianyun6655** [comment]
Hi,Karalabe
When I am debuging with Geth, I found that the total difficulty can decided the longest chain. What if I start one private chain, then change the total difficulty to larger than the main network TD. Final I sync with the main change. What will happened ?

**Comment by karalabe** [comment]
Well, you could for a moment fool a node to start syncing with you, but you actually need to deliver blocks that support your promised TD. At the first sign of you not being able to supply the required blocks, you're dropped.

**Comment by tianyun6655** [comment]
I have tried 2 private chain. The first chain get 58 blocks and the second chain get 5 blocks (which TD has been changed to very huge.) Then I use admin.addPeer() function to connection 2 chains. I found The 5 block can be received, but it can not write to local database. Can you tell me why?

**Comment by yangwao** [comment]
@reductionista kudos! 
I occurred this bug in production and I could not figure out and my two nodes downloaded over 100M blocks and getting stuck a lot during sync.

**Pull request merged**
