### PR TITLE
pebble: Update pebble to fix mips incompatibility

### PR DESCRIPTION
**Pull request by ajsutton**
Updates pebble to include https://github.com/cockroachdb/pebble/pull/3005 which fixes compilation for 32-bit mips architectures. The dependency meant geth can't currently be built for mips and updating pebble fix that.

From what I can see pebble isn't tagging releases and the previous version used was just an arbitrary hash. Not sure if there's a process you're using to vet which version to pick.  The diff between the previous version and this new one is https://github.com/cockroachdb/pebble/compare/aa077af62593...f6cde3fc2fa4

### CODE REVIEW

**Comment by ajsutton** [comment]
`TestAuthEndpoints` is failing in CI but passing for me locally (and on the Windows amd build) so I think it's flaky.

The windows 386 build is failing with a compile error in blake2b but its also doing that on other PR builds so I think it may be broken on master.

**Comment by holiman** [comment]
They don't explicitly tag releases, but they do have release-branches which we try to pick from (or stay close to). See e.g https://github.com/cockroachdb/pebble/tree/crl-release-23.2 

That said, would be good to fix the incompatibility...

**Comment by ajsutton** [comment]
Ah, ok that makes sense.  My guess is that MIPs isn't a particularly popular platform for geth - I only found this because we use a MIPs VM as part of our fault proofs system and it pulls in op-geth for the EVM and block processing code.  For Optimism, we could just override the version of pebble used there to have this fix - it doesn't actually use pebble, we just need it to compile. Then we can just pull in the next pebbledb release once it's out.

**Comment by ajsutton** [comment]
I saw the pebble branch `crl-release-23.2` was updated so pulled that in here, but it's actually just cherry-picked a few updates and not the mips fix.  So still no actual release with the mips fix.

So pointed back to the commit on master with the pebble fix and will have to keep waiting for a pebble release with the fix.  I'm happy to make this draft or close it until that release comes out if it helps you keep things tidy.

**Pull request closed without merging**
