### PR TITLE
vendor: added vendor packages necessary for the swarm-network-rewrite merge

### PR DESCRIPTION
**Pull request by justelad**
this pull request addresses the changes needed in the vendor directory for merging `ethersphere/swarm-network-rewrite` branch into `ethereum/master`

addresses https://github.com/ethersphere/go-ethereum/issues/419

### CODE REVIEW

**Comment by nonsense** [comment]
LGTM - I tried merge `swarm-network-rewrite` on top of this, and it looks like we have all necessary libraries vendored here.

**Comment by justelad** [comment]
@gbalint what's the status on this?

**Comment by fjl** [comment]
Can multihash be removed?

**Comment by gbalint** [comment]
@fjl Yes, we are working on it: https://github.com/ethersphere/go-ethereum/pull/633

**Comment by justelad** [comment]
@gbalint, i just went through this PR again - `multihash` isn't even here since it wasn't vendored in the classical sense through the `vendor` folder (it was placed under `swarm/multihash` and not under `vendor`).
hence i think this PR is mergeable as is.

**Comment by nonsense** [comment]
@justelad however dependencies were included because of `multihash`
- golang.org/x/crypto/blake2s
- golang.org/x/crypto/blake2b
- golang.org/x/crypto/sha3
- leb.io/hashland/keccakpg
- github.com/jbenet/go-base58
- github.com/spaolacci/murmur3
etc.

I believe we have to remove these and any other dependencies included by `multihash` as they are no longer necessary.

**Comment by justelad** [comment]
removed the multihash dependencies and the json entries in `vendor.json`, i guess that now its good to go.

**Pull request merged**
