### PR TITLE
accounts/abi: handle events and redo unpack

### PR DESCRIPTION
**Pull request by VoR0220**
- Enables unpacking of events using a common interface to methods
- Redoes unpack into modular pieces and functions
- Merge this after #14735

### CODE REVIEW

**Comment by VoR0220** [comment]
Seems like there's a big chunk missing on the bind side to make this work. What would be needed to get this merged @fjl ?

**Comment by edevil** [comment]
Any news on this?

**Comment by bas-vk** [comment]
@fjl I the last change allows for unpacking events/methods output into slices/arrays.

**Comment by VoR0220** [comment]
what's holding up merging this besides the one bind test?

**Comment by bas-vk** [comment]
Now rebased against latest master.

@VoR0220 all tests should pass.

**Comment by VoR0220** [comment]
My understanding was that the ability to pull values out of an interface was being deprecated in favor of a move to structs, is that not the case anymore?

**Pull request merged**
