### PR TITLE
core/vm: implement opcode REVERT - eip#140

### PR DESCRIPTION
**Pull request by obscuren**
https://github.com/ethereum/EIPs/issues/140

### CODE REVIEW

**Comment by holiman** [comment]
You've implemented the first suggestion, which afaict has been superseeded by https://github.com/axic/EIPs/blob/20fdb8ccd069f5a70ebe8566c81d6f35086a6493/EIPS/eip-draft_revert_opcode.md . The big difference is that `REVERT` is more like `RETURN`, in that it returns an actual memory segment.

**Comment by obscuren** [comment]
@holiman it hasn't been accepted yet. It was another proposal that was discussed.

**Comment by obscuren** [comment]
PR has been updated according to the new specification

**Comment by holiman** [comment]
Just to be clear, which specification is being followed?

**Comment by obscuren** [comment]
@holiman the one you linked.

**Pull request closed without merging**
