### PR TITLE
balancer: implemented generic load balancer

### PR DESCRIPTION
**Pull request by obscuren**
Balancer is a generic approach to load balancing given any type of
tasks. Tasks are packages that do 1. perform an expensive tasks and
2. yield a good/bad result (i.e. an error).

When tasks are given to the balancer the balancer will selects one of the
least loaded workers and passes on the work and adds it to its work
queue.

The load balancer can be used in all sorts of places and should
generally help with optimisations in places where parallel processing is
useful. The following tasks could be paralellised:
- The transaction pool's validation process whenever it's given a bunch
  of transactions.
- Block & uncle pow verification
- Transaction sender public key derivation

---

**WILL SQUASH WHEN FINISHED**

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Mon Feb 22 16:01:57 UTC 2016_

**Comment by obscuren** [comment]
Some preliminary benchmarks:

```
$ go test -run=- -bench . -benchtime 3s

PASS
BenchmarkTxsRaw-4         	      20	 229383743 ns/op
BenchmarkTxsLoadBalancer-4	     100	  51153227 ns/op
ok  	github.com/ethereum/go-ethereum/balancer	25.340s
```

**Comment by obscuren** [comment]
I've tried several approaches when making a generic worker.

1. I started out with the balancer approach and noticed it was slightly slower than the initial implementation done by @fjl (which was specifically created for handling **only** block pow verification). This implementation used a load balancer and several workers that were *given* work based on their work load. The work distributed evenly and work packages were created in batches. The batches were the size of `len(work)/workers` and separate tasks were created for both blocks and transactions.

2. The second approach I tried turned the balancer in to a queue. Shove work in to it and the worker would pick of work from that same channel leaving the "balancing" in the hands of the Go runtime. This turned out to be even slower than 1. This approach uses a one-to-many type channel where many workers read of the same channel and I think results in a lot of internal (Go runtime internal) locking of the channel's mutex/lock. It also used the same size in work packages with the same distribution over the tasks.

3. Similar to 2. however with a different work package size; each nonce and each transaction was shoved in to a new task. This turned out to be slightly faster than 2. yet still slower than 1.

4. Similar to 1. but with the combination of 3's work packages ... :boom: ... faster than 1. and the initial implementation done by @fjl. With a higher nonce and transaction throughput I moved the nonce and transaction in to the same worker loop.

The drawback both 1. and 2. have is that it may lock up because there's no such thing as infinite channel size. This is solved by checking channel `cap` and `size` and creating new *temporary* workers on the fly if the other workers are busy.

**Comment by fjl** [comment]
@obscuren please reopen this later when you get to it

**Pull request closed without merging**
