### PR TITLE
accounts/abi/backends/simulated: add more API methods (#5)

### PR DESCRIPTION
**Pull request by gitteri**
Isolated automated integration tests were hard for us with the current backend simulator. In order to have a robust test suite I added methods to the backend simulator that have been extremely helpful for testing. Additionally, I added unit tests for almost all the methods of the backend simulator (but not the ones for the filter backend).

New methods added to the simulated backend:
BlockByHash
BlockByNumber
HeaderByHash
HeaderByNumber
TransactionCount
TransactionInBlock
SubscribeNewHead

The Simulated backend now implements the following interfaces:
ChainReader, ChainStateReader, ContractBackend, ContractCaller, ContractFilterer, ContractTransactor, DeployBackend, GasEstimator, GasPricer, LogFilterer, PendingContractCaller, TransactionReader, and TransactionSender

### CODE REVIEW

**Comment by gitteri** [comment]
@fjl Please let me know if I can provide any further details for this PR to make reviewing it easier

**Comment by gitteri** [comment]
@fjl @gballet @adamschmideg Is there's anything I can provide to help push this PR forward? Thanks!

**Comment by gballet** [comment]
@gitteri one thing you could do would be to fix the linter issue, please

**Comment by gitteri** [comment]
@gballet just fixed it. Looks like the failure in ci is unrelated to this pr: 
`lookup proxy.golang.org on 8.8.8.8:53: read udp 192.168.0.8:57902->8.8.8.8:53: i/o timeout`

**Comment by gitteri** [comment]
@gballet just a friendly bump for this. Let me know if there's anyone else who can also help review this pr that I should reach out to

**Pull request merged**
