### PR TITLE
add optional 'codeFilePath' field for accounts predefined in the genesis

### PR DESCRIPTION
**Pull request by jwasinger**
For Ξwasm, we are defining genesis files containing a lot of accounts with code.  If we were to put these directly in the genesis, it would make the file very large.  This PR adds an option to specify a genesis account's code with a relative/absolute path to a file containing the code (binary).

### CODE REVIEW

**Comment by karalabe** [comment]
This seems a very bad idea. It would mean that all of a sudden the genesis block is not self contained, rather depends on many external files. That would make it super unportable.

**Comment by jwasinger** [comment]
CC @axic @gballet

**Comment by jwasinger** [comment]
Is there a size limit for the genesis file?  If not, this change should be unnecessary.

**Comment by karalabe** [comment]
Nope.

**Comment by karalabe** [comment]
Perhaps a better alternative would be to support loading a compressed json as the genesis block. That would ensure that your final file size is small, but would retain the portability.

**Comment by karalabe** [comment]
We already do that internally in Geth btw, all genesis blocks for predefined networks are compressed within the binary.

**Comment by fjl** [comment]
There is no size limit on genesis files. I will close this PR now to clear it from the backlog.

**Pull request closed without merging**
