### PR TITLE
 gh-pages: match geth --help in v1.10.3

### PR DESCRIPTION
**Pull request by adrienlacombe**
https://geth.ethereum.org/docs/interface/command-line-options is currently out of date

### CODE REVIEW

**Review by karalabe — APPROVED** [review]
Thanks

**Comment by adrienlacombe** [comment]
sorry, should I change the commit comment to add gh-pages in front?

**Comment by karalabe** [comment]
It's fine, I squashed your commit with a slightly updated message. But the gh-pages messages aren't that relevant.

**Comment by adrienlacombe** [comment]
Understood, thank you!

**Pull request merged**
