### PR TITLE
swarm: Add favicon for Swarm templates served by browser

### PR DESCRIPTION
**Pull request by cooganb**
This PR adds a base64 data blob in the `head` of the generic HTML templates used by the HTTP Swarm client.

This PR has been approved by 2 members of the Swarm development team in [ethersphere#208](https://github.com/ethersphere/go-ethereum/pull/208).

It is a contribution to the goal of improving the http interface for Swarm users. Please let me know if you have any questions.

### CODE REVIEW

**Comment by cooganb** [comment]
@karalabe Thanks so much! I so appreciate it.

I also have another PR waiting for review also related to http interface of Swarm, [ethereum#15926](https://github.com/ethereum/go-ethereum/pull/15926)...would you mind taking a look at that?

Thanks again!

**Comment by cooganb** [comment]
@karalabe will do! on it now

**Comment by karalabe** [comment]
Ping?

**Comment by cooganb** [comment]
hey @karalabe ! Thanks for following up. Swarm Dev incorrectly stated it was an error of whisper protocol (which is true for one test shown below) but another test fails in server_test.go, which I just realized while typing this to you. Working on it now!

`FAIL
coverage: 59.3% of statements
FAIL	github.com/ethereum/go-ethereum/whisper/whisperv6	23.232s
util.go:45: exit status 1
exit status 1`

**Comment by karalabe** [comment]
Tests are still failing.

**Comment by cooganb** [comment]
working on it now. apologies for the delay but i'm a community contributor,
not part of ethereum foundation

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 4af6c8c1ab14527bc6a27c7c933b8cc2c12b1e14
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by cooganb** [comment]
@karalabe main tests are fixed, rebasing from master right now to correct one more.

**Comment by cooganb** [comment]
@karalabe all the swarm tests are passing -- the fail test is coming from 

```
go build _/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/gomobile-work-757186050/src/gomobile_bind: invalid flag in #cgo CFLAGS: -fmodules
/Users/travis/gopath/src/github.com/ethereum/go-ethereum/build/bin/gomobile: darwin-armv7: go build -pkgdir=/Users/travis/gopath/pkg/gomobile/pkg_darwin_arm -tags ios ios -v -buildmode=c-archive -o /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/gomobile-work-757186050/geth-arm.a /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/gomobile-work-757186050/src/iosbin/main.go failed: exit status 1
util.go:45: exit status 1
exit status 1
The command "go run build/ci.go xcode -signer IOS_SIGNING_KEY -deploy trunk -upload gethstore/builds" exited with 1.
```

**Comment by cooganb** [comment]
@karalabe thank you!!

**Pull request merged**
