### PR TITLE
core/rawdb, node: use standalone flock dependency

### PR DESCRIPTION
**Pull request by holiman**
This PR uses https://github.com/gofrs/flock instead of github.com/prometheus/tsdb/fileutil, as the latter is archived.

### CODE REVIEW

**Review by rjl493456442 — APPROVED** [review]
LGTM. 

I have checked the implementation of new library. It has a bit more functionalities which might not be used in our case, but the core logic is still very clear and basically identical.

**Comment by holiman** [comment]
Added a fix to unconditionally create the directory where the flock is placed. I basically do it just like the previous one did: https://github.com/prometheus-junkyard/tsdb/blob/master/fileutil/flock.go#L32 . 

Re `MkDirAll`:
```
// If path is already a directory, MkdirAll does nothing
// and returns nil.
```

**Comment by karalabe** [comment]
Seems to choke a lot on various tests:

```
console_test.go:111: failed to register Ethereum protocol: open /tmp/TestPrettyError3976087765/001/console-tester/chaindata/ancient/chain/FLOCK: no such file or directory
```

```
--- FAIL: TestFreezerCleanup (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x61d944]
goroutine 47 [running]:
testing.tRunner.func1.2({0x690060, 0xa99d10})
	/home/appveyor/.gvm/gos/go1.19.5/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
	/home/appveyor/.gvm/gos/go1.19.5/src/testing/testing.go:1399 +0x39f
panic({0x690060, 0xa99d10})
	/home/appveyor/.gvm/gos/go1.19.5/src/runtime/panic.go:884 +0x212
github.com/ethereum/go-ethereum/core/rawdb.(*ResettableFreezer).Close(0xc00047e630?)
	/home/appveyor/projects/go-ethereum/core/rawdb/freezer_resettable.go:96 +0x44
github.com/ethereum/go-ethereum/core/rawdb.TestFreezerCleanup(0xc000085040)
	/home/appveyor/projects/go-ethereum/core/rawdb/freezer_resettable_test.go:102 +0x37a
testing.tRunner(0xc000085040, 0x6fc8c0)
	/home/appveyor/.gvm/gos/go1.19.5/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/home/appveyor/.gvm/gos/go1.19.5/src/testing/testing.go:1493 +0x35f
```

**Comment by holiman** [comment]
> Seems to choke a lot on various tests:

Yeah I had done the mkdir on one level too low

**Comment by karalabe** [comment]
Pls rebase

**Comment by holiman** [comment]
rebased again

**Comment by holiman** [comment]
no rush, perhaps better hold it until 1.11.1, to give it some time

**Pull request merged**
