### PR TITLE
eth/api: rename signAndSendTransaction to sendTransaction

### PR DESCRIPTION
**Pull request by bas-vk**
See https://github.com/ethereum/EIPs/issues/113. Will update web3 when it released a new version with this method included.

@frozeman

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Fri Jun 17 10:14:53 UTC 2016_

**Comment by karalabe** [comment]
Mostly discussion/opinion:

I'm a bit reluctant from this change because we're starting to litter our `personal` namespace with various methods that perhaps should have been part of `eth` in the first place. There could be a potential confusion in what the difference is between `eth.sendTransaction` and `personal.sendTransaction`.

Couldn't we simply drop `eth.sendTransaction` altogether and have only the personal version remaining with the password being optional? This could potentially solve a lot of issues in the long run (both confusion as well as security wise).

**Comment by bas-vk** [comment]
Removing `eth_sendTransaction` would break a lot of current applications and I don't expect this to happen anytime soon. There is a valid use case for it in a trusted environment.

Currently there is a clear separation between method that accept sensitive input and the one's that are not. I would like to keep this separation. If we let `eth_sendTransaction` accept an optional password this might give a false signal that it is safe to use on a http/ws interface.

**Comment by karalabe** [comment]
I meant to keep both versions inside personal and completely drop from eth.
It's not safe anyway.

**Comment by bas-vk** [comment]
I understand what you mean, but dropping it from the `eth` namespace will break a lot of things.
This PR is only a rename of the old method as discussed in the EIP.

**Comment by frozeman** [comment]
dropping this from eth is not an options, its the main way people use the node currently.

In the future when we move accounts out of the node we can discuss that. Currently the `personal` namespace is also not official part of the RPC spec, so changes are still fine, while in eth, we have to be backwards compatible.

Conquering the name change, we had an ERC discussing the name with the community: https://github.com/ethereum/EIPs/issues/113

So please merge

**Comment by obscuren** [comment]
Rebase please.

**Comment by bas-vk** [comment]
rebased again

**Comment by frozeman** [comment]
Please merge

**Comment by karalabe** [comment]
LGTM :+1:

**Pull request merged**
