### PR TITLE
miner: Prevent attempts to close nil quit channel in agent (fixes #2948)

### LINKED ISSUE #2948: panic: close of nil channel in miner.(*worker).stop
G'day.
#### System information

Geth version: 

```
Version: 1.4.11-stable-fed692f6
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7
OS: darwin
GOPATH=/Users/elliot/.go
GOROOT=/usr/local/opt/go/libexec
```

OS & Version: Windows/Linux/OSX

```
OSX 10.11.5
```
#### Expected behaviour

Not panic
#### Actual behaviour

Panic
#### Steps to reproduce the behaviour

I'm starting geth with 

```
geth --datadir="data" init genesis.json
```

then

```
geth --datadir="data" --keystore="keystore" --password="./password"  --port 30303 --rpc --rpcport 8101 --rpcaddr localhost --networkid 21423 --rpccorsdomain="*" --minerthreads=1 --mine --rpcapi "eth,web3,personal" --maxpeers 4 --unlock=$(cat genesis.json | jq '.alloc | with_entries(select(.value.unlock != false)) | keys | join(",")' -r) js mine.js
```

mine.js is from embark  (https://github.com/iurimatias/embark-framework/blob/develop/js/mine.js)

Can't seem to make it die without mine.js, and looks like it has something to do with stopping mining.
## What I'm doing

Connecting via HTTP from node.js, calling a contract 50 times, fetching the 50 transactions that result, filtering for 50 events coming back. No batching.

Doesn't happen every time.
#### Backtrace

```
== Pending transactions! Looking for next block...
== Pending transactions! Looking for next block...
== Pending transactions! Looking for next block...
== Pending transactions! Looking for next block...
I0825 10:42:10.419129 miner/worker.go:573] commit new work on block 189 with 50 txs & 0 uncles. Took 514.889961ms
I0825 10:42:10.419393 miner/miner.go:119] Starting mining operation (CPU=4 TOT=17)
I0825 10:42:11.252229 miner/worker.go:573] commit new work on block 189 with 50 txs & 0 uncles. Took 832.800055ms
I0825 10:42:11.252379 miner/miner.go:119] Starting mining operation (CPU=4 TOT=21)
I0825 10:42:11.516675 miner/worker.go:339] 🔨  Mined block (#189 / 35b43fbb). Wait 5 blocks for confirmation
I0825 10:42:11.861606 miner/worker.go:573] commit new work on block 189 with 50 txs & 0 uncles. Took 609.182259ms
I0825 10:42:11.861696 miner/miner.go:119] Starting mining operation (CPU=4 TOT=25)
I0825 10:42:12.089754 miner/worker.go:573] commit new work on block 190 with 0 txs & 0 uncles. Took 261.719µs
I0825 10:42:12.263832 miner/miner.go:119] Starting mining operation (CPU=4 TOT=29)
I0825 10:42:12.265277 miner/worker.go:573] commit new work on block 190 with 0 txs & 0 uncles. Took 1.221938ms
I0825 10:42:12.508372 miner/miner.go:119] Starting mining operation (CPU=4 TOT=33)
I0825 10:42:12.508929 miner/worker.go:573] commit new work on block 190 with 0 txs & 0 uncles. Took 499.909µs
I0825 10:42:12.734714 miner/miner.go:119] Starting mining operation (CPU=4 TOT=37)
I0825 10:42:12.735308 miner/worker.go:573] commit new work on block 190 with 0 txs & 0 uncles. Took 375.778µs
I0825 10:42:14.051396 miner/miner.go:119] Starting mining operation (CPU=4 TOT=46)
I0825 10:42:15.218144 miner/worker.go:573] commit new work on block 190 with 0 txs & 0 uncles. Took 298.943µs
I0825 10:42:15.361249 miner/miner.go:119] Starting mining operation (CPU=4 TOT=50)
I0825 10:42:16.717218 miner/worker.go:573] commit new work on block 190 with 0 txs & 0 uncles. Took 1.355905235s
I0825 10:42:17.500571 miner/miner.go:119] Starting mining operation (CPU=4 TOT=54)
I0825 10:42:17.500923 miner/worker.go:573] commit new work on block 190 with 0 txs & 0 uncles. Took 279.117µs
I0825 10:42:17.780828 miner/miner.go:119] Starting mining operation (CPU=4 TOT=58)
I0825 10:42:17.781361 miner/worker.go:573] commit new work on block 190 with 0 txs & 0 uncles. Took 262.624µs
== No transactions left. Stopping miner...
I0825 10:42:20.739047 miner/miner.go:119] Starting mining operation (CPU=4 TOT=5)
I0825 10:42:20.739459 miner/worker.go:573] commit new work on block 190 with 0 txs & 0 uncles. Took 357.111µs
I0825 10:42:21.601187 miner/worker.go:573] commit new work on block 190 with 0 txs & 0 uncles. Took 7.380731ms
I0825 10:42:21.602076 miner/miner.go:119] Starting mining operation (CPU=4 TOT=39)
== No transactions left. Stopping miner...
I0825 10:42:21.624625 miner/worker.go:339] 🔨  Mined block (#190 / da12f53f). Wait 5 blocks for confirmation
I0825 10:42:21.717035 miner/worker.go:573] commit new work on block 191 with 0 txs & 0 uncles. Took 307.93µs
panic: close of nil channel

goroutine 2836 [running]:
panic(0x47fb700, 0xc4205e4090)
        /usr/local/opt/go/libexec/src/runtime/panic.go:500 +0x1a1
github.com/ethereum/go-ethereum/miner.(*CpuAgent).Stop(0xc4459a38b0)
        /private/tmp/ethereum-20160824-96982-s9fitz/build/_workspace/src/github.com/ethereum/go-ethereum/miner/agent.go:61 +0x65
github.com/ethereum/go-ethereum/miner.(*worker).stop(0xc4203997a0)
        /private/tmp/ethereum-20160824-96982-s9fitz/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:199 +0x127
github.com/ethereum/go-ethereum/miner.(*Miner).Stop(0xc420409200)
        /private/tmp/ethereum-20160824-96982-s9fitz/build/_workspace/src/github.com/ethereum/go-ethereum/miner/miner.go:127 +0x2f
github.com/ethereum/go-ethereum/eth.(*Ethereum).StopMining(0xc420399680)
        /private/tmp/ethereum-20160824-96982-s9fitz/build/_workspace/src/github.com/ethereum/go-ethereum/eth/backend.go:385 +0x32
github.com/ethereum/go-ethereum/eth.(*PrivateMinerAPI).Stop(0xc4201d61f8, 0x0)
        /private/tmp/ethereum-20160824-96982-s9fitz/build/_workspace/src/github.com/ethereum/go-ethereum/eth/api.go:261 +0x2e
reflect.Value.call(0xc4214cbbc0, 0xc4201d6918, 0x13, 0x48d893d, 0x4, 0xc4217a3e80, 0x1, 0x1, 0x743752a7f3fd1792, 0x14, ...)
        /usr/local/opt/go/libexec/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0xc4214cbbc0, 0xc4201d6918, 0x13, 0xc4217a3e80, 0x1, 0x1, 0x2, 0x2, 0xc420465618)
        /usr/local/opt/go/libexec/src/reflect/value.go:302 +0xa4
github.com/ethereum/go-ethereum/rpc.(*Server).handle(0xc420091ef0, 0x4e469a0, 0xc4201d8a50, 0x4e49d40, 0xc4200c7c70, 0xc448ad8fc0, 0xc4204657a0, 0xc420465720, 0xc444dff440)
        /private/tmp/ethereum-20160824-96982-s9fitz/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:323 +0x903
github.com/ethereum/go-ethereum/rpc.(*Server).exec(0xc420091ef0, 0x4e469a0, 0xc4201d8a50, 0x4e49d40, 0xc4200c7c70, 0xc448ad8fc0)
        /private/tmp/ethereum-20160824-96982-s9fitz/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:345 +0x1e4
created by github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest
        /private/tmp/ethereum-20160824-96982-s9fitz/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:216 +0x34d
```

and another time

```
I0825 11:04:27.847320 miner/worker.go:339] 🔨  Mined block (#199 / 6d2aac6c). Wait 5 blocks for confirmation
I0825 11:04:27.847640 miner/worker.go:573] commit new work on block 200 with 0 txs & 1 uncles. Took 283.353µs
I0825 11:04:31.028575 miner/miner.go:119] Starting mining operation (CPU=4 TOT=70)
I0825 11:04:31.028555 miner/miner.go:119] Starting mining operation (CPU=4 TOT=67)
I0825 11:04:33.001447 miner/worker.go:339] 🔨  Mined block (#199 / e8d18fa7). Wait 5 blocks for confirmation
I0825 11:04:33.823435 miner/worker.go:573] commit new work on block 200 with 0 txs & 1 uncles. Took 1.688746936s
I0825 11:04:33.823771 miner/miner.go:119] Starting mining operation (CPU=4 TOT=73)
I0825 11:04:33.824176 miner/worker.go:573] commit new work on block 200 with 0 txs & 1 uncles. Took 357.273µs
I0825 11:04:38.107613 miner/worker.go:573] commit new work on block 200 with 0 txs & 1 uncles. Took 760.942976ms
I0825 11:04:40.066858 miner/worker.go:573] commit new work on block 200 with 0 txs & 1 uncles. Took 1.408152ms
I0825 11:04:40.067499 miner/worker.go:573] commit new work on block 200 with 0 txs & 2 uncles. Took 328.937µs
I0825 11:04:41.956777 miner/worker.go:573] commit new work on block 200 with 0 txs & 2 uncles. Took 392.285µs
I0825 11:04:41.957268 miner/worker.go:573] commit new work on block 200 with 0 txs & 2 uncles. Took 382.171µs
I0825 11:04:48.731872 miner/worker.go:573] commit new work on block 200 with 0 txs & 2 uncles. Took 3.709715838s
I0825 11:04:48.732346 miner/worker.go:573] commit new work on block 200 with 0 txs & 2 uncles. Took 354.505µs
I0825 11:04:51.665796 miner/worker.go:573] commit new work on block 200 with 0 txs & 2 uncles. Took 694.453µs
I0825 11:04:52.119866 miner/worker.go:573] commit new work on block 200 with 0 txs & 2 uncles. Took 1.066103ms
I0825 11:04:52.120374 miner/worker.go:573] commit new work on block 200 with 0 txs & 2 uncles. Took 418.248µs
I0825 11:04:55.830796 miner/worker.go:573] commit new work on block 200 with 0 txs & 2 uncles. Took 359.535µs
I0825 11:04:55.831110 miner/worker.go:573] commit new work on block 200 with 0 txs & 2 uncles. Took 243.539µs
I0825 11:05:00.916900 miner/worker.go:573] commit new work on block 200 with 0 txs & 2 uncles. Took 1.22005ms
I0825 11:05:00.917346 miner/worker.go:573] commit new work on block 200 with 0 txs & 2 uncles. Took 360.515µs
I0825 11:05:03.650018 miner/worker.go:573] commit new work on block 200 with 0 txs & 2 uncles. Took 372.837µs
I0825 11:05:03.650331 miner/worker.go:573] commit new work on block 200 with 0 txs & 2 uncles. Took 235.644µs
I0825 11:05:07.514641 miner/worker.go:573] commit new work on block 200 with 0 txs & 2 uncles. Took 386.16µs
I0825 11:05:07.514958 miner/worker.go:573] commit new work on block 200 with 0 txs & 2 uncles. Took 253.433µs
I0825 11:05:09.836426 miner/worker.go:573] commit new work on block 200 with 0 txs & 2 uncles. Took 491.46µs
I0825 11:05:09.869512 miner/worker.go:573] commit new work on block 200 with 0 txs & 2 uncles. Took 525.265µs
I0825 11:05:10.216684 miner/worker.go:573] commit new work on block 200 with 0 txs & 2 uncles. Took 332.964µs
I0825 11:05:11.251834 miner/worker.go:573] commit new work on block 200 with 0 txs & 2 uncles. Took 346.189µs
I0825 11:05:11.252218 miner/worker.go:573] commit new work on block 200 with 0 txs & 2 uncles. Took 319.868µs
I0825 11:05:18.495318 miner/miner.go:119] Starting mining operation (CPU=4 TOT=89)
I0825 11:05:18.495840 miner/worker.go:573] commit new work on block 200 with 0 txs & 2 uncles. Took 424.515µs
I0825 11:05:18.496685 miner/miner.go:119] Starting mining operation (CPU=4 TOT=93)
I0825 11:05:18.497184 miner/worker.go:573] commit new work on block 200 with 0 txs & 2 uncles. Took 392.348µs
I0825 11:05:21.069182 miner/miner.go:119] Starting mining operation (CPU=4 TOT=97)
I0825 11:05:21.069670 miner/worker.go:573] commit new work on block 200 with 0 txs & 2 uncles. Took 415.291µs
panic: close of nil channel

goroutine 5315 [running]:
panic(0x47fb700, 0xc439346a20)
        /usr/local/opt/go/libexec/src/runtime/panic.go:500 +0x1a1
github.com/ethereum/go-ethereum/miner.(*CpuAgent).Stop(0xc43b5e0a50)
        /private/tmp/ethereum-20160824-96982-s9fitz/build/_workspace/src/github.com/ethereum/go-ethereum/miner/agent.go:61 +0x65
github.com/ethereum/go-ethereum/miner.(*worker).stop(0xc4202c45a0)
        /private/tmp/ethereum-20160824-96982-s9fitz/build/_workspace/src/github.com/ethereum/go-ethereum/miner/worker.go:199 +0x127
github.com/ethereum/go-ethereum/miner.(*Miner).Stop(0xc4203f8f60)
        /private/tmp/ethereum-20160824-96982-s9fitz/build/_workspace/src/github.com/ethereum/go-ethereum/miner/miner.go:127 +0x2f
github.com/ethereum/go-ethereum/eth.(*Ethereum).StopMining(0xc4202c4360)
        /private/tmp/ethereum-20160824-96982-s9fitz/build/_workspace/src/github.com/ethereum/go-ethereum/eth/backend.go:385 +0x32
github.com/ethereum/go-ethereum/eth.(*PrivateMinerAPI).Stop(0xc4204287f8, 0x0)
        /private/tmp/ethereum-20160824-96982-s9fitz/build/_workspace/src/github.com/ethereum/go-ethereum/eth/api.go:261 +0x2e
reflect.Value.call(0xc4214450e0, 0xc420428f18, 0x13, 0x48d893d, 0x4, 0xc43bcf5e80, 0x1, 0x1, 0x0, 0x0, ...)
        /usr/local/opt/go/libexec/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0xc4214450e0, 0xc420428f18, 0x13, 0xc43bcf5e80, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/opt/go/libexec/src/reflect/value.go:302 +0xa4
github.com/ethereum/go-ethereum/rpc.(*Server).handle(0xc420421ef0, 0x4e469a0, 0xc420253170, 0x4e49d40, 0xc42009e230, 0xc43bb86850, 0x0, 0x0, 0x0)
        /private/tmp/ethereum-20160824-96982-s9fitz/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:323 +0x903
github.com/ethereum/go-ethereum/rpc.(*Server).exec(0xc420421ef0, 0x4e469a0, 0xc420253170, 0x4e49d40, 0xc42009e230, 0xc43bb86850)
        /private/tmp/ethereum-20160824-96982-s9fitz/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:345 +0x1e4
created by github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest
        /private/tmp/ethereum-20160824-96982-s9fitz/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:216 +0x34d
```

### PR DESCRIPTION
**Pull request by elliots**

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Thu Aug 25 01:48:31 UTC 2016_

**Comment by karalabe** [comment]
Nice catch, though I think this will still be racey.

As far as I see the underlying issue is that if I call [`miner.Start`](https://github.com/ethereum/go-ethereum/blob/develop/miner/miner.go#L119) and [`miner.Stop`](https://github.com/ethereum/go-ethereum/blob/develop/miner/miner.go#L143) in quick succession, it might happen that the start method [adds the CPU miners](https://github.com/ethereum/go-ethereum/blob/develop/miner/miner.go#L133), but [doesn't yet start them](https://github.com/ethereum/go-ethereum/blob/develop/miner/miner.go#L138) when the stop method already [tries to abort them](https://github.com/ethereum/go-ethereum/blob/develop/miner/miner.go#L144). Since the CPU agents' `quit` channel is only initialized when starting, you hit the error you reported.

The problem with your solution is that Start and Stop still race with each other, the first creating the `quit` channel and the second reading it. Although the race is probably much less frequent with your code, it can still result in a panic. My suggestion would be that instead of checking for `nil`-ness of the `quit` channel, move the channel's creation [from start](https://github.com/ethereum/go-ethereum/blob/develop/miner/agent.go#L72) to the [agent initialization](https://github.com/ethereum/go-ethereum/blob/develop/miner/agent.go#L45).

Another question is whether we need the mutex locking in [start](https://github.com/ethereum/go-ethereum/blob/develop/miner/agent.go#L65) and [stop](https://github.com/ethereum/go-ethereum/blob/develop/miner/agent.go#L58) at all of if that could be removed. AFAIK the channels are only ever created once and discarded once, so I don't see any benefit behind the mutex protecting them (this would entail [moving the work channel](https://github.com/ethereum/go-ethereum/blob/develop/miner/agent.go#L75) too  the initialization).

@obscuren @fjl @bas-vk Could some of you check this logic?

**Comment by fjl** [comment]
Moving the channels sounds better. Please do that.

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: ac0f8b81ae40f18a70413916e5ef1cbc503e4743
  * Commit subjects should be kept under 80 characters

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by karalabe** [comment]
Yup, exactly like this! :) Could you check whether your embark tester works properly with this code?

**Comment by elliots** [comment]
Apart from the too-long commit message, my test case is no longer working after this commit. That could be a change between my stable (brew) geth->develop, but it's midnight so I'll check in the morning.

**Comment by karalabe** [comment]
> my test case is no longer working after this commit

Does this mean that the issue was solved, or that the issue reappeared again? :D

**Comment by elliots** [comment]
My original issue is fixed by this commit, when applied to 1.4.

My test case however doesn't work at all (even without miner.js) in the develop branch (due to #2950 and is fixed by this dodgy PR #2951)

**Comment by karalabe** [comment]
Hmmm, that is very strange because I remember @bas-vk explicitly fixing this issue a while back.

**Comment by karalabe** [comment]
LGTM :+1:

**Comment by obscuren** [comment]
👍

**Pull request merged**
