### PR TITLE
accounts/scwallet: fix keycard data signing error

### PR DESCRIPTION
**Pull request by gballet**
Fixes the error condition in #25222

### CODE REVIEW

**Comment by willianpaixao** [comment]
Hi @gballet,

I've checkout your branch, built locally and would like to share that your patch works, at least with the Keycard! Follow the logs confirming:

``` js
> personal.listWallets
[{
    accounts: [{
        address: "0xb5269a99a7022ae0010fb2d1121fd8c7278161a1",
        url: "keycard://f98f/m/44'/60'/0'/0/0"
    }],
    status: "Online",
    url: "keycard://f98f82ca"
}]

> personal.listAccounts
["0xb5269a99a7022ae0010fb2d1121fd8c7278161a1"]

> personal.sign("0xdeadbeaf", "0xb5269a99a7022ae0010fb2d1121fd8c7278161a1", "112199")
"0x5ca8ff0628d6682918fd902fdfba70be802ed812c4f2b1f70ccea78da83077a86b6a94a1d7ee18481db8dffd7054d5b0f6ebc0b6e8e72a347e5286d008724e8b1c"

> eth.sign("0xb5269a99a7022ae0010fb2d1121fd8c7278161a1","0xdeadbeaf")
"0xcf38d41ae42b1d2949aedc31823d970f15f7f76f6bf50c93b0e4b8ea8ac8930e28e2009d9a9c72c7a5c74165377ccfcae8f25a2946dac263c0254b1318895f731c"

> eth.signTransaction({from: "0xb5269a99a7022ae0010fb2d1121fd8c7278161a1", to:"0x3b15ba77fd4f389dafbbf3d8ecb241f781eec943", gasPrice: 1, gas: 200, nonce:1})
{
  raw: "0xf862010181c8943b15ba77fd4f389dafbbf3d8ecb241f781eec94380808401546d71a0603a8b37dfbac62204d4fe087ec84a956c9c56be1ee462f127d2e65fa2e58fcca0244763fd575f80a93ec3bd89c75f9aa460e01b9a7da3924bc0de14e0994470b0",
  tx: {
    gas: "0xc8",
    gasPrice: "0x1",
    hash: "0x167ce2331c8c73455661bbafdc55a6821f6de08fde53131d0466383cf9d13e60",
    input: "0x",
    maxFeePerGas: null,
    maxPriorityFeePerGas: null,
    nonce: "0x1",
    r: "0x603a8b37dfbac62204d4fe087ec84a956c9c56be1ee462f127d2e65fa2e58fcc",
    s: "0x244763fd575f80a93ec3bd89c75f9aa460e01b9a7da3924bc0de14e0994470b0",
    to: "0x3b15ba77fd4f389dafbbf3d8ecb241f781eec943",
    type: "0x0",
    v: "0x1546d71",
    value: "0x0"
  }
}
```

Thanks a lot for fixing!

**Comment by willianpaixao** [comment]
@ligi could you paste the link of the upstream issue?

**Comment by holiman** [comment]
@gballet why not just we merge this -- seems to fix an error, as @willianpaixao has shown.

**Review by holiman — APPROVED** [review]

**Comment by holiman** [comment]
> @gballet why not just we merge this -- seems to fix an error, as @willianpaixao has shown. The upstream "bug" is not truly a bug -- geth also didn't always produce deterministic signatures on transactions.

@gballet PTAL ^^

**Pull request merged**
