### PR TITLE
core/txpool: remove redundant check for floatingRatio == 0

### PR DESCRIPTION
**Pull request by hero5512**

### CODE REVIEW

**Comment by fjl** [comment]
Care to explain?

**Comment by hero5512** [comment]
> Care to explain?
floatingRatio is a constant value and always is non-zero. so there is no need to check this value

**Comment by fjl** [comment]
Thanks! Please, if possible, explain your PRs in the description. It is expected and makes the review easier for us.

**Review by fjl — APPROVED** [review]

**Comment by hero5512** [comment]
> Thanks! Please, if possible, explain your PRs in the description. It is expected and makes the review easier for us.

ok

**Review by rjl493456442 — APPROVED** [review]

**Comment by karalabe** [comment]
Please don't merge until https://github.com/ethereum/go-ethereum/pull/27463 is in

**Comment by karalabe** [comment]
Pls rebase, the txpool package was moved to `core/txpool/legacypool`.

**Comment by hero5512** [comment]
> Pls rebase, the txpool package was moved to `core/txpool/legacypool`.

done

**Pull request merged**
