### PR TITLE
mobile: don't retain transient []byte in CallMsg.SetData

### LINKED ISSUE #14675: mobile: incorrect assignment of CallMsg data from byte array
#### System information

Geth version: `1.6.6`
OS & Version: Android 5.1.1/arm64-v8a with geth.aar(make android)
Commit hash : 431cf2a1e453346bcc627ac1fb9df3950a6c3499

#### Expected behaviour
the msg.Data of `func (ec *Client) CallContract(ctx context.Context, msg ethereum.CallMsg, blockNumber *big.Int) ([]byte, error)` of ethclient/ethclient.go should be `[32 150 82 85]`

#### Actual behaviour
msg.Data is not `[32 150 82 85]`. Instead, it's a changeable byte array，such as `[48 122 59 151]`, `[73 78 70 79]`, etc. Sometimes it will be the right value `[32 150 82 85]`

#### Steps to reproduce the behaviour
Constructa an CallMsg on Android:
 ```
 CallMsg callMsg= Geth.newCallMsg();
 byte data = okio.ByteString.decodeHex("20965255").toByteArray();//[32 150 82 85]
 callMsg.setData(data);
 callMsg.set...
```
call it by EthereumClient#callContract(ctx, callMsg, -1)

BTW, on Android 7.1/armeabi-v7a device, it has no such issue. The msg.Data is exactly that passed from Android.

Does anybody happen to know this issue? Tks.

### PR DESCRIPTION
**Pull request by eliasnaur**
Go mobile doesn't copy []byte parameters, for performance and to allow
writes to the byte array be reflected in the native byte array.
Unfortunately, that means []byte arguments are only valid during the
call it is being passed into.

CallMsg.SetData retains such a byte array. Copy it instead.

Fixes #14675

### CODE REVIEW

**Comment by karalabe** [comment]
Oh wow, I didn't know about this limitation. Could you skim the `mobile` package to see if we used something like this and fix it? 

I know of three cases:

 * mobile.NewTransaction, this is ok as is because internally it copies the `data`.
 * https://github.com/ethereum/go-ethereum/blob/master/mobile/interface.go#L49 and , which I guess should be fixed now too.
 * https://github.com/ethereum/go-ethereum/blob/master/mobile/interface.go#L50, same, should be fixed.

Btw, does gomobile only do this optimization for byte slices, or for other types of slices too?

**Comment by karalabe** [comment]
We already have a method to copy a byte slice [`common.CopyBytes`](https://godoc.org/github.com/ethereum/go-ethereum/common#CopyBytes), perhaps use that to avoid having duplicate code.

**Comment by eliasnaur** [comment]
Done.

**Comment by karalabe** [comment]
Sweet, I've rebased it to fix a merge error, hope you don't mind :)

**Pull request merged**
