### PR TITLE
core, eth: unship EIP 2315

### PR DESCRIPTION
**Pull request by karalabe**
*Posted without comments.*

### CODE REVIEW

**Comment by karalabe** [comment]
Decision was against removing this EIP.

**Comment by winsvega** [comment]
merge?

**Comment by karalabe** [comment]
When there's a test suite to verify the merge.

**Comment by winsvega** [comment]
@qbzzt  Ori did a test on this PR

**Review by holiman — APPROVED** [review]
Lgtm

**Comment by meowsbits** [comment]
> Decision was against removing this EIP.

Where was this decision made? Can someone provide a link?

**Comment by karalabe** [comment]
There was a decision against the decision of removing this EIP XD. Final Berlin spec removed it.

**Comment by meowsbits** [comment]
I found the AllCoreDevs call `Ethereum Core Devs Meeting #107​ [2021-03-05]` (via https://github.com/ethereum/eth1.0-specs/commit/7d3d203a883b6ab90f2dc9bc6bffbc2aa24c1a6d) where this is discussed and apparently the decision is ultimately reached: https://youtu.be/xWfR-WxjmYg?t=223.

**Comment by benbaley** [comment]
How can we guarantee the correct execution of historical transactions during full sync?

**Pull request merged**
