### PR TITLE
logger/glog: improve vmodule

### PR DESCRIPTION
**Pull request by fjl**
This change allows setting the verbosity for directory prefixes using the syntax

    --vmodule=eth/*=6

If you want to restrict messages to a particular directory (e.g. p2p), but exclude subdirectories, use

    --vmodule=p2p=6

If you want to see log messages from a particular source file, use

    --vmodule=server.go=6

You can compose these basic patterns. If you want to see all output from peer.go in a package below
eth (eth/peer.go, eth/downloader/peer.go), use

    --vmodule=eth/*/peer.go=6

The output format also changes to display part of the import path and removes the process id.

```text
I0120 14:10:59.731647 ethdb/database.go:71] Alloted 16MB cache to /Users/fjl/Library/Ethereum/chaindata
I0120 14:10:59.763596 ethdb/database.go:71] Alloted 16MB cache to /Users/fjl/Library/Ethereum/dapp
I0120 14:10:59.769989 eth/backend.go:161] Protocol Versions: [63 62 61], Network Id: 1
I0120 14:10:59.770127 eth/backend.go:189] Blockchain DB Version: 3
I0120 14:10:59.770985 core/blockchain.go:210] Last header: #848682 [96865ccd…] TD=5538940244436146641
...
```

Additionally the vmodule patterns can now be set through the debug API without
restarting the node.

```text
$ geth attach
...
> debug.vmodule("p2p=6")
```

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Wed Jan 20 13:24:22 UTC 2016_

**Comment by karalabe** [comment]
Wouldn't the following pattern be more reasonable?

 * `eth` -> do the eth package, no subpackages
 * `eth/*` -> eth + everything underneath
 * `eth.go` -> ... 

Your use of the asterisk as an exclusive wildcard is imho very non intuitive.

**Comment by fjl** [comment]
The original code supported glob patterns and I didn't want to break that.

**Comment by karalabe** [comment]
Fair enough, but can we swap the meaning of the asterisk then? I.e. no asterisk = single package, with asterisk = subpackages too?

**Comment by fjl** [comment]
>  If you don't include a slash, it will still match against basename.

In case this isn't clear, it means that `--vmodule=server=6` will still match `p2p/server.go` just like before.
Similarly, `*=3` will still match every file.

**Comment by karalabe** [comment]
Yeah, I got that, I was referring to 

`eth/` vs `eth/*` imho the first should exclude subpackages and the latter include. Your PR description states in the other way around, `*` *excluding* stuff.

**Comment by fjl** [comment]
@karalabe PTAL

**Comment by fjl** [comment]
Now ready for review. Note, I have removed `admin_verbosity` in the old RPC implementation because we're retiring it anyway. Both `verbosity` and `vmodule` now live in the debug API.

**Comment by karalabe** [comment]
I think you only updated the old RPC with the new methods. The new RPC that should also feature these changes are in https://github.com/ethereum/go-ethereum/blob/develop/node/api.go I believe.

**Comment by fjl** [comment]
See https://github.com/ethereum/go-ethereum/pull/2136/files#diff-9333767b602263d799081cc2b59fa874R141

**Comment by karalabe** [comment]
Sorry, didn't see that.

**Comment by obscuren** [comment]
:+1:

**Comment by nagydani** [comment]
(y)

**Comment by nagydani** [comment]
+1

**Comment by nagydani** [comment]
:+1:

**Pull request merged**
