### PR TITLE
core: handle engine VerifyHeader error in NewBlockChain

### PR DESCRIPTION
**Pull request by meowsbits**
Signed-off-by: meows <b5c6@protonmail.com>

### CODE REVIEW

**Comment by karalabe** [comment]
This is just a pre-caching step. It cannot fail as it operates on data already in our chain.

**Comment by meowsbits** [comment]
Is there any harm in handling an almost-definitely `nil` error?  There are also a few other validations on existing chaindata immediately below...

**Comment by karalabe** [comment]
It's more like an added mental load. This code is a precaching optimization. Even if it fails, we don't care at all.

If we started caring, then all of a sudden it's not just "warming up the cache", but it starts to look like it's important for some code below, which would be untrue.

**Comment by meowsbits** [comment]
Got it. I was about to suggest `VerifySeal` as perhaps more to the point, but see now that clique's implementation wouldn't hit snapshot caching.

**Pull request closed without merging**
