### PR TITLE
support state override for debug_traceTransaction ("offchain events")

### PR DESCRIPTION
**Pull request by hananbeer**
the debug_traceCall function supports state overrides, but debug_traceTransaction does not - it only accepts a transaction hash.

I wrote this originally as the backbone for generating "offchain events" (as developed by shadow / ghost logs)

to prevent confusion with nodes that don't implement this feature I created a distinct function debug_traceTransactionOverrides.
by overriding contracts bytecode it is possible to reexecute onchain transactions in different context, specifically to emit so called "offchain events" but not limited to this.

see equivalent implementations:

reth: https://github.com/paradigmxyz/reth/pull/7410
erigon: https://github.com/ledgerwatch/erigon/pull/9847

### CODE REVIEW

**Comment by s1na** [comment]
Why is this not possible by using `debug_traceCall` and passing in all the tx args? `traceCall` has the option to produce the state of a (block, tx_id).

**Comment by hananbeer** [comment]
> Why is this not possible by using `debug_traceCall` and passing in all the tx args? `traceCall` has the option to produce the state of a (block, tx_id).

I haven't seen this in docs.
https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug

do you have reference?

**Comment by s1na** [comment]
> I haven't seen this in docs.

Sorry about that. It seems we forgot to update the docs after adding it. This is the PR https://github.com/ethereum/go-ethereum/pull/28460 in question. So it's added to the last object which has the state and block overrides and tracing config.`

@jsvisa care to update the docs?

**Comment by jsvisa** [comment]
> > I haven't seen this in docs.
> 
> 
> 
> Sorry about that. It seems we forgot to update the docs after adding it. This is the PR https://github.com/ethereum/go-ethereum/pull/28460 in question. So it's added to the last object which has the state and block overrides and tracing config.`
> 
> 
> 
> @jsvisa care to update the docs?

Sure, I'll add it in the docs later today or tomorrow

**Comment by jsvisa** [comment]
@s1na how about let's also add `TxIndex` for the `eth_call` RPC, seems that is also a useful feature, wdyt.

**Comment by s1na** [comment]
> @s1na how about let's also add TxIndex for the eth_call RPC, seems that is also a useful feature, wdyt.

Yep I think it makes sense. But with multicall around the corner I'd say it's a short term benefit anyway.

@hananbeer let me know if you tried the alternative I suggested and it works for you, then I'd go ahead and close this PR. We can keep the `debug_traceTransaction` a pure re-execution while adding allowing all override possibilities in `traceCall`.

**Comment by hananbeer** [comment]
that solution is fine I just want it to be standardized across nodes :)
I guess we can close this pr.

**Comment by ArtificialPB** [comment]
IMO, it still makes sense to support state overrides on both `TraceTransaction` and `TraceBlock` calls. This will allow tracing a whole block with injected events, with a single call, instead of doing a `TraceCall` for each tx in the block.

It would be a two-line code change: just move `StateOverrides *ethapi.StateOverride` from `TraceCallConfig` to `TraceConfig`.

**Pull request closed without merging**
