### PR TITLE
core/vm: use pointer to avoid unnecessary copy in validate function

### PR DESCRIPTION
**Pull request by libotony**

### CODE REVIEW

**Comment by holiman** [comment]
Please supply some motivation. If this is for performance reasons, for example a benchmark would be good.

**Comment by libotony** [comment]
> Please supply some motivation. If this is for performance reasons, for example a benchmark would be good.

This PR proposes chaning `validate(jt JumpTable) JumpTable` to `validate(jt *JumpTable) *JumpTable` since it's called in every `newXxxInstructionSet` func.

**Comment by libotony** [comment]
Furthermore, I think `validate` func does not need to return the input jumptable, just 
``` golang
...
    instructionSet := newShanghaiInstructionSet()
    // enablexxx...
    validate(instructionSet)
    return instructionSet
}
```
would be better.

**Comment by MariusVanDerWijden** [comment]
The `newXXXInstructionSet` functions are only called once when the client is started, so even if there is some improvement in the validate function, it does not improve the overall speed of the client only maybe the startup marginally. I don't really see the need for this change

**Comment by holiman** [comment]
> > Please supply some motivation. If this is for performance reasons, for example a benchmark would be good.
> 
> This PR proposes chaning `validate(jt JumpTable) JumpTable` to `validate(jt *JumpTable) *JumpTable` since it's called in every `newXxxInstructionSet` func.

Yes, that's what it does. But why?

**Comment by libotony** [comment]
> The `newXXXInstructionSet` functions are only called once when the client is started, so even if there is some improvement in the validate function, it does not improve the overall speed of the client only maybe the startup marginally. I don't really see the need for this change

You're right, this change doesn't enhance performance but rather a coding style refinement. The decision is yours.

**Comment by holiman** [comment]
I prefer keeping it as is

**Pull request closed without merging**
