### PR TITLE
cmd/geth: codegansta/cli package renamed to urfave/cli

### PR DESCRIPTION
**Pull request by bas-vk**
According to their [github](https://github.com/urfave/cli#pinning-to-the-v1-branch) page v2 will become master in the future which can cause compatibility issues. Therefore the version is pinned to v1 which makes the upgrade to v2 explicit.

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Thu Jun 9 09:49:12 UTC 2016_

**Comment by karalabe** [comment]
Seems this revision is from a month ago. Any particular reason for not pulling the latest code?

**Comment by bas-vk** [comment]
v1.17.0 is the latest officially released version that is guaranteed v1 compatible. Its what you currently get if you use the gopkg redirect service.

**Comment by karalabe** [comment]
Hmm, strange. I didn't know gopkg has both branch and tag versioning supported. Cool then :) 

Another question: do we use `github.com/rs/xhandler` for anything?

**Comment by bas-vk** [comment]
I *thought* it was a dependency for `github.com/rs/cors` once. But that doesn't uses it currently and I could not find any references to it in our own code base nor in the dependencies. Since godep removed it from the godep.json file I figured we can delete it entirely.

**Comment by fjl** [comment]
👍

**Comment by karalabe** [comment]
@bas-vk But in this PR godeps just added it back, that's why I'm asking :)

**Pull request merged**
