### PR TITLE
update tests for istanbul

### PR DESCRIPTION
**Pull request by holiman**
This PR updates the tests, let's see what Travis says about it

### CODE REVIEW

**Comment by karalabe** [comment]
Travis gave you the finger.

**Comment by holiman** [comment]
The structure of the tests has changed a bit, and some tests have been moved into `LegacyTests`. I suspect we may have to do some changes to our test runners to ensure that we do still execute them.

**Comment by holiman** [comment]
Travis keeps hating on this PR. Trying now with running tests with `--short` flag, to disable long-running tests.

**Comment by holiman** [comment]
Finally travis :green_heart: me

**Pull request merged**
