### PR TITLE
graphql: add error code and message

### PR DESCRIPTION
**Pull request by jsvisa**
I'm introduing https://github.com/graph-gophers/graphql-go#custom-errors to add `errorCode` and `errorMessage` for the incorrect GraphQL requests. 

It will return something like this, eg:

```graphql
{blocks(from: 2 to: 0) { number }}
```

```json
{
  "errors": [
    {
      "message": "error [-32602]: invalid from and to block combination: from > to",
      "path": [
        "blocks"
      ],
      "extensions": {
        "errorCode": -32602,
        "errorMessage": "invalid from and to block combination: from > to"
      }
    }
  ],
  "data": null
}
```
Two error codes were defined in this PR:

- `-32602`: for any invalid request parameters
- `-32600`: for any other unknown errors

But the `graphql.ResolverError` can only be used for errors returned by graphql implementation body functions, for these errors that have not yet entered the function cannot be applied. 

eg:

```graphql
{ block(number: "") { number } }
```

> geth's response(after this PR)

```json
{"errors":[{"message":"strconv.ParseInt: parsing \"\": invalid syntax"}],"data":{}}
```

> besu's response

```json
{
  "errors" : [ {
    "message" : "Validation error (WrongType@[block]) : argument 'number' with value 'StringValue{value=''}' is not a valid 'Long' - Value is not any Long : 'StringValue{value=''}'",
    "locations" : [ {
      "line" : 1,
      "column" : 9
    } ],
    "extensions" : {
      "classification" : "ValidationError"
    }
  } ]
}
```

Or another case

```graphql
{ block(hash: "0x1001") { number } }
```

> geth's response(after this PR)

```json
{"errors":[{"message":"hex string has length 4, want 64 for Hash"}],"data":{}}
```

> besu's response

```json
{
  "errors" : [ {
    "message" : "Exception while fetching data (/block) : Block hash 0x0000000000000000000000000000000000000000000000000000000000001001 was not found",
    "locations" : [ {
      "line" : 1,
      "column" : 3
    } ],
    "path" : [ "block" ],
    "extensions" : {
      "classification" : "DataFetchingException"
    }
  } ],
  "data" : {
    "block" : null
  }
}
```

@s1na please take a look, and give some advice. thanks.

### CODE REVIEW

**Comment by fjl** [comment]
There is no need to match the errors of besu. I know we are checking these on hive, but the place to fix that is hive. What's most important is that implementations should agree on whether a query results in an error at all. The code and message do not need to match.

**Comment by holiman** [comment]
If I interpret the comment from @fjl correctly, we can just close this PR. Thanks for the effort!

**Comment by s1na** [comment]
Sorry I haven't responded here. But I insist on adding error codes across the board in the APIs. I will re-open this and bring it up for discussion on a triage.

**Comment by s1na** [comment]
> But I insist on adding error codes across the board in the APIs.

I will eat those words. The efforts to standardize graphql have fizzled out and I don't want to champion them anymore. Closing this PR. If someone else would like to champion that feel free to re-open.

Thanks for the effort regardless @jsvisa.

**Pull request closed without merging**
