### PR TITLE
refactor Dockerfile

### PR DESCRIPTION
**Pull request by caktux**
Following discussion in #747, reduces size to ~350 MB, saving 811 MB over the original size. Also using supervisord for a more manageable container. Logs are sent to `/var/log/geth.log` and `/var/log/geth.err` within the container.

### CODE REVIEW

**Comment by fjl** [comment]
I like the small image, but dislike the addition of unattended-upgrades and ‎supervisord. Users need direct control of the command line arguments to geth. In fact, the system-testing project depends on this in their scripts. This is not negotiable. Please change‎ these two things, then we can merge.

**Comment by caktux** [comment]
System-testing shouldn't depend on the end-user docker image. I just checked how the image was being used, and the `ENTRYPOINT` is already being overridden, so using supervisor has no incidence. What does is that there is no longer a `GOPATH`, nor a git checkout, so it needs its own image anyway. Not only that, but I'll be assisting on that project shortly to clean things up, and probably move to using Docker Machine. So take back your *not negotiable*; it has to be fixed properly another way.

**Comment by caktux** [comment]
Updated the system-testing repo to account for this change, but will most probably create a different build for it later on.
The unattended-upgrades package is necessary for long-running containers, supervisor allows to debug a process that failed, and users always have the option the override the entrypoint and cmd as they see fit.

**Comment by fjl** [comment]
I was about to write that we care about users being able to use the interactive console as well. And ask about why on earth system-testing (or anyone) would need a git checkout and a set GOPATH in the container.

**Comment by fjl** [comment]
I have reverted your PR because we need to agree on things before anything can be merged.

**Comment by fjl** [comment]
system-testing uses the container to call various `geth` subcommands, see [here](https://github.com/ethereum/system-testing/blob/acfb6b62d87c83187c904e445de642d014532d58/ansible/roles/clients/tasks/ethash.yml#L11) for an example.

**Comment by fjl** [comment]
The `Dockerfile` that you updated in system-testing is for `cmd/bootnode`. We should either create another one for it or put the old `Dockerfile` which compiles go-ethereum into system-testing.

**Comment by caktux** [comment]
The command line argument just need to be updated to override the entrypoint and cmd, that's it.

**Comment by fjl** [comment]
That would fix system testing. But the main question I'd like to resolve is who the Dockerfile in our repo is for.

**Comment by fjl** [comment]
Adding `supervisord` and the other changes to make it more `manageable` assume that this container is supposed to run on a server for a long time.

**Comment by caktux** [comment]
We agreed earlier it was for end-users, hence using supervisor by default.

**Comment by fjl** [comment]
But who are those end users you think of?

**Comment by caktux** [comment]
Whoever wants to quickly try ethereum, either locally or running it for long periods of time on a server, this caters to both.

**Comment by caktux** [comment]
It also doesn't prevent its use in system-testing, at all, besides a few adjustments. And as I said earlier, and you seem to agree on that too, a different Dockerfile would be better suited.

**Comment by caktux** [comment]
Now can you please revert your revert? It didn't fix anything for one, and I'm making the necessary adjustments to system-testing.

**Comment by fjl** [comment]
OK, at this point, the only thing I'm worried about is people not being able to use `geth console` and `geth js` easily. From reading about it more, it seems as if your container still allows that using

```
$ docker run -t -i -entrypoint="/usr/bin/geth console" ethereum/client-go
```

With the old container, that one was:

```
$ docker run -t -i ethereum/client-go console
```

**Comment by fjl** [comment]
Can you confirm that this still works? It doesn't really matter how long the command is.

**Comment by caktux** [comment]
That'd be `docker run -it --entrypoint="/usr/bin/geth" ethereum/client-go console`

**Comment by fjl** [comment]
cool

**Comment by fjl** [comment]
Now we can merge it.

**Comment by caktux** [comment]
Thank you

**Comment by t128** [comment]
Im getting now the error msg: `System error: exec: "\"geth\"": executable file not found in $PATH`

my docker-compose.yaml file:
```yaml
main:
  image: ethereum/client-go
  restart: on-failure
  volumes:
    - ./data:/root/.ethereum
  command: --nat "extip:$myPublicIp" --rpc --rpcaddr="0.0.0.0" --rpccorsdomain="*" --maxpeers 100 --natspec
  ports:
    - "30303:30303"
    - "8545:8545"
  entrypoint: geth
```

ps: i also dislike the "nice" supervisord idea.

**Pull request merged**
