### PR TITLE
crypto/secp256k1: remove dependency on libgmp

### PR DESCRIPTION
**Pull request by fjl**
Turns out we actually don't need it, USE_NUM_NONE works
because we also set USE_FIELD_INV_BUILTIN.

libgmp is our only external runtime dependency. Removing the dependency
makes it possible to compile standalone geth binaries that can be redistributed
by simply copying the executable file (e.g. with Mist or the Wallet app).

### CODE REVIEW

**Comment by robotally** [comment]
| Vote | Count | Reviewers |
| :---: | :---: | :---: |
| :+1: | 0 |  |
| :-1: | 0 |  |

_Updated: Thu Dec 3 19:07:20 UTC 2015_

**Comment by tgerring** [comment]
:+1: as long as Mac builds are verified. Might also want to hear from @karalabe on how this might impact xgo cross-comilation

**Comment by karalabe** [comment]
Cool :D Few things though, could you pull in my ios/arm pr below yours, and also drop depsflags from the ios targets?

**Comment by karalabe** [comment]
*depsargs, the disable assembly part. That was for gmplib

**Comment by fjl** [comment]
@karalabe done

**Comment by karalabe** [comment]
Does this impact performance, if we don't use gmp optimized code?

**Comment by fjl** [comment]
It was not actually using any of the num.h functions because of USE_FIELD_INV_BUILTIN.

**Comment by obscuren** [comment]
@karalabe let me know if you run in to any issues with `xgo`

**Comment by karalabe** [comment]
Don't see why removing would cause issues, but can only test it in the
morning. Will report as soon as O know for sure :)

**Comment by karalabe** [comment]
Turned on my laptop, running the builds now, will report back in 10 mins.

**Comment by karalabe** [comment]
:+1: 

```
Full cross compilation done:
-rwxr-xr-x 1 root root 20962040 Dec  4 00:42 build/bin/geth-android-16-arm
-rwxr-xr-x 1 root root 14822424 Dec  4 00:40 build/bin/geth-darwin-10.6-386
-rwxr-xr-x 1 root root 17895796 Dec  4 00:40 build/bin/geth-darwin-10.6-amd64
-rwxr-xr-x 1 root root 14952816 Dec  4 00:43 build/bin/geth-ios-5.0-arm-7
-rwxr-xr-x 1 root root 18111232 Dec  4 00:43 build/bin/geth-ios-7.0-arm64
-rwxr-xr-x 1 root root 21691932 Dec  4 00:37 build/bin/geth-linux-386
-rwxr-xr-x 1 root root 25726272 Dec  4 00:37 build/bin/geth-linux-amd64
-rwxr-xr-x 1 root root 20972600 Dec  4 00:38 build/bin/geth-linux-arm-5
-rwxr-xr-x 1 root root 20907872 Dec  4 00:38 build/bin/geth-linux-arm-6
-rwxr-xr-x 1 root root 25202992 Dec  4 00:39 build/bin/geth-linux-arm64
-rwxr-xr-x 1 root root 20895912 Dec  4 00:39 build/bin/geth-linux-arm-7
-rwxr-xr-x 1 root root 16291411 Dec  4 00:41 build/bin/geth-windows-4.0-386.exe
-rwxr-xr-x 1 root root 19409663 Dec  4 00:41 build/bin/geth-windows-4.0-amd64.exe
```

**Comment by karalabe** [comment]
Btw, getting rid of gmplib has the secondary advantage that we can include out stuff in the App Store. Read it yesterday that there are some licensing issues which make gmplib incompatible with the AppStore.

**Pull request merged**
