### PR TITLE
build: bundle the bootnode too into alltools

### PR DESCRIPTION
**Pull request by karalabe**

### CODE REVIEW

**Comment by karalabe** [comment]
Given the massively overloaded CI, I'm just going to merge this now. I don't see anything possibly breaking :P

**Comment by msolima** [comment]
Hi @karalabe 
I just downloaded Geth & Tools 1.5.9 from https://geth.ethereum.org/downloads/ and I can't find the bootnode executable. Although the published date was 02/13/2017. 
I'm I missing something ?
I used this one:
Geth & Tools 1.5.9	a07539fb…	Archive	64-bit	23.46 MB	02/13/2017	Signature	c16a6c116a364aa5a06a1706e507fdde

**Comment by karalabe** [comment]
Well, since 1.5.9 was published in February, and this PR was merged in March... ;) It will be available in the Geth 1.6.0 release.

**Comment by msolima** [comment]
@karalabe thanks for the quick reply!

**Comment by msolima** [comment]
@karalabe this is going to sound like a noob question.
but I'm trying to do the following to get bootnode
```
git clone https://github.com/ethereum/go-ethereum.git
cd go-ethereum
make geth
```

after I execute those commands, I only get "geth" executable under build/bin

is there a way (command) to build bootnode executable as well there ?

Thanks

**Comment by karalabe** [comment]
`make all` :)

**Comment by rakeshkumar33** [comment]
bootnode :command not found 

need sme help

**Pull request merged**
