### PR TITLE
les: pass server pool to protocol manager

### PR DESCRIPTION
**Pull request by zsfelfoldi**
This PR fixes a regression that rendered the LES server pool practically useless.

### CODE REVIEW

**Comment by holiman** [comment]
Lgtm

**Comment by karalabe** [comment]
Please `gofmt -s`.

**Comment by zsfelfoldi** [comment]
@karalabe ran it on the entire les package and it made no changes. Maybe its behavior depends on the go version? (I use 1.9.2)

**Comment by karalabe** [comment]
Oh wow

```
metrics/metrics.go:1::warning: file is not goimported (goimports)
metrics/metrics.go:1::warning: file is not gofmted with -s (gofmt)
```

**Comment by karalabe** [comment]
Apparently master is borked on linters, will open a new PR to fix these.

**Pull request merged**
