### PR TITLE
core/rawdb: use go ticker instead of timer

### PR DESCRIPTION
**Pull request by htiennv**

### CODE REVIEW

**Review by MariusVanDerWijden — APPROVED** [review]
SGTM

**Comment by lilasxie** [comment]
Sorry for bothering you, but what's the benefit of the replacement?

**Review by lightclient — COMMENTED** [review]
I don't think ticker is correct here. We don't want to fire events at regularly scheduled intervals. In the backoff, the goal is to wait `freezerRecheckInterval` time before resuming execution. To do this, should prefer a timer.

The code there actually seems incorrect, I believe the `timer.Reset` should be above the `select` in the `backoff` if statement.

**Comment by htiennv** [comment]
> I don't think ticker is correct here. We don't want to fire events a regularly scheduled intervals. In the backoff, the goal is to wait `freezerRecheckInterval` time before resuming execution. To do this, should prefer a timer.
> 
> 
> 
> The code there actually seems incorrect, I believe the `timer.Reset` should be above the `select` in the `backoff` if statement.

Yeah, Thanks @lightclient for your review.

**Pull request closed without merging**
