### PR TITLE
metrics: fix flaky Example metrics test

### PR DESCRIPTION
**Pull request by nonsense**
1. `Example` test is failing on AppVeyor, as the timing of the empty function updates the timer sample with value 0 due to Windows' time resolution. Adding a short sleep should predictably fix the output with 1 being the lowest value in the sample.

2. `TestTimerFunc` constraints are relaxed, because of a failure I saw on Travis:
```
--- FAIL: TestTimerFunc (0.08s)

	timer_test.go:51: tm.Max(): 45e6 > 82254038 || 82254038 > 55e6

FAIL
```

### CODE REVIEW

**Comment by karalabe** [comment]
Thank you! I'll merge on green.

**Comment by nonsense** [comment]
@karalabe I read that by default the Windows resolution is 15.6ms, so in theory this might fail even with this 10ms time.Sleep. In case it happens, I will increase it, but it looks like it might be fine as is.

**Comment by nonsense** [comment]
Looks like the `les` tests deadlock on occasion. I've seen this while fixing the flaky tests on Swarm, but haven't had time to look into this at all yet.

**Comment by nonsense** [comment]
And we are back to OOM errors on the `tests` package. I think this is expected, at least I have seen it very often on AppVeyor. We have to see how to fix this, but out-of-scope for this PR.

**Pull request merged**
