### PR TITLE
ethtest improvements

### PR DESCRIPTION
**Pull request by tgerring**
Refactor/cleanup of `cmd/ethtest` utility and `tests` package to support #1157 

TODO:
* [x] Allow running all test types
* [x] Allow running all tests in specified directory (instead of single file)
* [x] Fix geth rpc blocktest command
* [x] Re-enable Stdin option

Maybe:
* [ ] Move geth blockest command to ethtest
* [x] Set "skip" tests via CLI instead of hardcoded

### CODE REVIEW

**Comment by tgerring** [comment]
@Gustav-Simonsson Please review core test logic to makes sure I haven't trampled on anything important

TODO: Extend ethtest options to allow running all tests and/or a whole directory

**Comment by tgerring** [comment]
Please test with the new flags:
```
   --test "all"		Test type (string): VMTests, TransactionTests, StateTests, BlockTests
   --file "."		Test file or directory. Directories are searched for .json files 1 level deep [$ETHEREUM_TEST_PATH]
   --continue		Continue running tests on error (true) or exit immediately (false)
```

**Comment by tgerring** [comment]
Updated flags with `--stdin` option:

```
GLOBAL OPTIONS:
   --test "all"		Test type (string): VMTests, TransactionTests, StateTests, BlockTests
   --file "."		Test file or directory. Directories are searched for .json files 1 level deep [$ETHEREUM_TEST_PATH]
   --continue		Continue running tests on error (true) or [default] exit immediately (false)
   --stdin		Accept input from stdin instead of reading from file
```

For example, `ethtest --test BlockTests --stdin < ../../tests/files/BlockTests/bcUncleTest.json`

**Comment by fjl** [comment]
I would prefer to keep the test files included. Why are you removing them?

**Comment by tgerring** [comment]
What is the benefit of clouding commit history (and ballooning repo) by manually reflecting changes in the parent repo versus a `git submodule update --init`?

If the concern is that changes to the tests might start breaking CI unnecessarily (for example, this PR that fails due to new tests), we can update the builds to checkout a specific commit before building. It would be good to anticipate the future use of submodules, which will allow for more flexible integration testing.

**Comment by fjl** [comment]
We initially used subtree merging to keep the tests up to date, which I consider the superior strategy.
It wasn't always used though (cough, @Gustav-Simonsson). I prefer having the files in the repo itself
because the tests are supposed to run as part of go test (like they do now). Moving to a submodule means that people would need to clone them as well in order to be able to run the tests. The only way
around this would be to skip the tests if the files don't exist (can be done in the tests themselves).

**Comment by obscuren** [comment]
I despise the use of git submodule. Please do not remove the tests from the repository.

**Comment by tgerring** [comment]
This PR is being used by the testing team now and I believe is ready for merge.

**Comment by obscuren** [comment]
I think something got merged and screwed up this PR

**Comment by winsvega** [comment]
I've tested it. Seems to work. I am ready to start simulation with this tool

**Comment by obscuren** [comment]
```
diff --git a/tests/state_test_util.go b/tests/state_test_util.go
index 835ba44..577935d 100644
--- a/tests/state_test_util.go
+++ b/tests/state_test_util.go
@@ -172,7 +172,7 @@ func RunState(statedb *state.StateDB, env, tx map[string]string) ([]byte, state.
        vmenv := NewEnvFromMap(statedb, env, tx)
        vmenv.origin = common.BytesToAddress(keyPair.Address())
        ret, _, err := core.ApplyMessage(vmenv, message, coinbase)
-       if core.IsNonceErr(err) || core.IsInvalidTxErr(err) {
+       if core.IsNonceErr(err) || core.IsInvalidTxErr(err) || state.IsGasLimitErr(err) {
                statedb.Set(snapshot)
        }
        statedb.Update()
```

**Comment by winsvega** [comment]
could you add testsuite "BlockChainTests"  it is same as the block tests  just another syntax

**Pull request merged**
