### PR TITLE
abi/bind: workaround for OpenEthereum missing eth_maxPriorityFeePerGas for Kovan

### LINKED ISSUE #23479: transact() attempts to use unsupported eth_maxPriorityFeePerGas via JSON RPC on Kovan
With go-ethereum v1.10.8 connected to an Infura or Alcchemy Kovan node, it is unable to transact if `gasPrice` is nil. `HeaderByNumber("latest")` returns a non-nil `head.BaseFee` (implying EIP-1559 support), but then returns `Method not found` for `eth_maxPriorityFeePerGas` when `ethclient.SuggestGasTipCap()` is called.

The issue is on this line of code:
https://github.com/ethereum/go-ethereum/blob/62ad17fb0046243255048fbf8cb0882f48d8d850/accounts/abi/bind/base.go#L263

go-ethereum client version: v1.10.8
node version (Infura and Alchemy Kovan): OpenEthereum//v3.3.0-rc.6-stable-5d9ff63-20210804/x86_64-linux-gnu/rustc1.52.1

Error in action - note the non-nil `head.BaseFee` and the `Method not found` error returned from `ethclient.SuggestGasTipCap()`:

image

Have reported this to Infura support as well.

Easy workaround is to manually specify a `gasPrice` of `2000000000` (2 GWei).

### PR DESCRIPTION
**Pull request by shoenseiwaso**
Resolves #23479

go-ethereum as a JSON RPC client may be used to connect to Kovan via OpenEthereum nodes, which do not currently support `eth_maxPriorityFeePerGas`, used by `ethclient.SuggestGasTipCap()`. This is called in `bind.transact()` and we receive a `"Method not found"` error from OpenEthereum.

In this case, we fall back to the logic [suggested in this comment](https://github.com/ethereum/pm/issues/328#issuecomment-853234014) and compute `tip = eth_gasPrice - baseFee`.

One question is whether we should try to match the error string or just try for it on any error.

Tested on Kovan on both Infura and Alchemy.

Side note that I recently learned [OpenEthereum has been deprecated](https://medium.com/openethereum/gnosis-joins-erigon-formerly-turbo-geth-to-release-next-gen-ethereum-client-c6708dd06dd), although I'm sure Kovan will be around for a while. There are probably other nodes that will not implement `eth_maxPriorityFeePerGas` that would benefit from this. A longer term fix might be to consider something involving [`eth_feeHistory`](https://notes.ethereum.org/@timbeiko/london-json-rpc#3-eth_maxPriorityFeePerGas-vs-eth_feeHistory), although I had a hard time following the various threads around EIP-1559 and what the best approach for this would be. Certainly open to suggestions in this PR.

### CODE REVIEW

**Review by macotouenaca — APPROVED** [review]

**Comment by rjl493456442** [comment]
Originally `eth_maxPriorityFeePerGas ` was a part of standard JSONPRC spec but was abandoned later. We should use feeHistory instead since it's expected to be implemented by all clients.

**Comment by shoenseiwaso** [comment]
> Originally `eth_maxPriorityFeePerGas ` was a part of standard JSONPRC spec but was abandoned later. We should use feeHistory instead since it's expected to be implemented by all clients.

Ok great! I can update the PR to use this.

Do you have a link to how we might use `eth_feeHistory` instead? I looked around online but it was hard to figure out what the "right" way to do this was.

**Comment by ligi** [comment]
@zsfelfoldi did this: https://github.com/zsfelfoldi/feehistory - maybe this can be used here?

**Comment by shoenseiwaso** [comment]
> @zsfelfoldi did this: https://github.com/zsfelfoldi/feehistory - maybe this can be used here?

@zsfelfoldi would you consider relicensing this under the LGPL so we can look at it for go-ethereum?

**Pull request closed without merging**
