### PR TITLE
vendor: Fix overflown callstack trace bug

### PR DESCRIPTION
**Pull request by linuxion**
The problem and the fix are described [here](https://github.com/ethereum/go-ethereum/pull/16458).

If @olebedev merges my [PR](https://github.com/olebedev/go-duktape/pull/58), you can undo the changes using
```
govendor update gopkg.in/olebedev/go-duktape.v3::gopkg.in/olebedev/go-duktape.v3
govendor update gopkg.in/olebedev/go-duktape.v3
```
if necessary.

### CODE REVIEW

**Comment by linuxion** [comment]
@karalabe, just a reminder. You have done a lot of cool geth improvements last 2 months, but it is a little inconvenient to recompile geth each update. :(

**Comment by holiman** [comment]
I'm not a fan of this. It changes the vendoring into `gopkg.in/linuxion/go-duktape.v3`. I'd much prefer it if the original maintainer merged that PR instead of us vendoring a fork.

**Comment by holiman** [comment]
Just pinged upstream

**Comment by holiman** [comment]
Closing this, as we'd rather use an upstream fix

**Pull request closed without merging**
