### PR TITLE
eth/tracers/js: make fault() optional

### PR DESCRIPTION
**Pull request by s1na**
`fault()` is very rarely implemented. No reason to have it mandatory.

### CODE REVIEW

**Comment by holiman** [comment]
> fault() is very rarely implemented. No reason to have it mandatory.

Myeah, makes sense, I guess. OTOH, if we remove it from mandatory-ness, and remove it from the tracers, it's going to be pretty difficult for users to figure out that `fault()` is part of the API, no?  Like, their tracer isn't working, and they spend N hours tearing their hair before discovering that they can add a `fault` function and handle the error.

Thoughts?

**Comment by hendeyk** [comment]
Y

**Comment by s1na** [comment]
> it's going to be pretty difficult for users to figure out that fault() is part of the API, no?

My thoughts were that handling `fault()` is more for the advanced use-cases and by highlighting this in the docs we can make sure a power user can figure it out. That's based on my observation that among all our tracers only the `callTracerLegacy` implements the method, and that because its doing this weird thing of callframe tracking via steps.

As a compromise what if we make it optional for callframe tracers? I.e. similar to how `enter` and `exit` must be present together, `step` and `fault` must be present together but otherwise both optional. The error happening during opcode exec will be eventually caught by `exit` (or `end`).

**Comment by holiman** [comment]
The code LGTM. If we want this feature, I'm fine with this getting merged. 

However, this is one of those types of changes that we cannot go back on. We are currently strict, enforcing `fault`, and if we become less strict we can not change it back later. I'd prefer keeping the status quo, but no strong feelings really.

**Pull request closed without merging**
