### PR TITLE
core, trie: speed up some tests with quadratic processing flaw

### PR DESCRIPTION
**Pull request by holiman**
This PR fixes what I _think_ is a flaw in two testcases, and brings down the exec-time from ~40s on my laptop, to ~8s for `trie/TestIncompleteSync`. 

The `checkConsistency` was performed over and over again on the _complete_ set of nodes, not just the recently added. So it had a quadratic runtime, basically. 

@rjl493456442 please correct me if it looks like I misinterpreted the test

### CODE REVIEW

**Review by rjl493456442 — APPROVED** [review]
LGTM. But I think we can improve it a bit further.
https://github.com/ethereum/go-ethereum/pull/21987/files#diff-7e4495028d0f8ed80bc9b25ce17f563cb2c9f17c4d97e4c2a0d1af935e604f4dR406

Here we re-calculate the hash all the time. Would be nice to save the hash somewhere.

**Comment by holiman** [comment]
@rjl493456442 yes, I can fix that, however, the `state/TestIncompleteStateSync` is already sub-second (it uses a smaller test-trie than `trie/TestIncompleteSync`). It just happened to contain the same flaw, so I fixed it in both places

**Comment by holiman** [comment]
Appveyor time went down from `128s` to `63s` for the trie package (https://ci.appveyor.com/project/ethereum/go-ethereum/builds/36748584/job/xg1q5eoop6lyj2lt#L809).

**Comment by karalabe** [comment]
The original code was deliberate FYI. It was meant to do a full check over and over to make sure nothing funky happens. That said, since we're only ever adding new stuff to the db, never deleting, the optimization should be fine.

**Pull request merged**
