### PR TITLE
Added links to dependencies

### PR DESCRIPTION
**Pull request by amissine**
Afterwards, was able to **make geth**. Thanks for the fun, folks! Keep pushing!

As for me, now is the time to learn go...

Thanks again,
:)

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: 726da108f314c680d225de9cb0b7f6dfc97ff324
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by lmars** [comment]
@amissine why was this change necessary? Were you getting an error? It doesn't look to me like a necessary change.

**Comment by amissine** [comment]
Yes, right off the box I was getting errors. IMHO, this is a typical situation with established and new environments (mine was new). If you try to "make geth" right after cloning to a new env (new computer), you'll get those errors too. Anyways, just my 2 cents.
:)

**Comment by lmars** [comment]
Can you paste the errors that you got? What version of Go are you using (run `go version`).

**Comment by amissine** [comment]
go version go1.7.3 linux/amd64

**Comment by amissine** [comment]
Found! Here:

alec@alec-MS-7596 ~/product/go-ethereum (master) $ make geth
build/env.sh go run build/ci.go install ./cmd/geth
build/_workspace/src/github.com/ethereum/go-ethereum/internal/build/azure.go:23:2: cannot find package "github.com/Azure/azure-storage-go" in any of:
	/usr/lib/go/src/pkg/github.com/Azure/azure-storage-go (from $GOROOT)
	/home/alec/product/go-ethereum/build/_workspace/src/github.com/Azure/azure-storage-go (from $GOPATH)
build/_workspace/src/github.com/ethereum/go-ethereum/internal/build/pgp.go:27:2: cannot find package "golang.org/x/crypto/openpgp" in any of:
	/usr/lib/go/src/pkg/golang.org/x/crypto/openpgp (from $GOROOT)
	/home/alec/product/go-ethereum/build/_workspace/src/golang.org/x/crypto/openpgp (from $GOPATH)
make: *** [geth] Error 1

**Comment by karalabe** [comment]
This change should definitely not be needed. I'll try to look into our dependencies if we're missing something by any chance, but our deps workflow pretty much worked for everyone for 2 years straight, so I don't think the issue lies on our setup.

**Comment by karalabe** [comment]
And we're building all our stuff on CI and stripped down alpine docker images too, which are the cleanest environments you'll be able to get.

**Comment by fjl** [comment]
This error happens when `go` is too old to recognize vendored dependencies used by build/ci.go.

**Comment by amissine** [comment]
I use go1.7.3 linux/amd64, as instructed by the docs. The docs also mention version 1.8, but do not provide access to it. Which version are you guys using and how can I get it? And thanks!
:)

**Comment by fjl** [comment]
See #14929

**Pull request closed without merging**
