### PR TITLE
cmd/evm: statet8n output folder + tx hashes on trace filenames

### LINKED ISSUE #21373: evm t8n  execution log files
the command I use to execute `evm t8n`:

```
/home/wins/.retesteth/t8ntool/start.sh --input.alloc /tmp/3d57a356-15f4-4ac4-9ed5-394c574debc3/alloc.json --input.txs /tmp/3d57a356-15f4-4ac4-9ed5-394c574debc3/txs.json --input.env /tmp/3d57a356-15f4-4ac4-9ed5-394c574debc3/env.json --state.fork Istanbul --output.result /tmp/3d57a356-15f4-4ac4-9ed5-394c574debc3/out.json --output.alloc /tmp/3d57a356-15f4-4ac4-9ed5-394c574debc3/outAlloc.json
```

need to get the execution log from it running:
```
--trace   /tmp/3d57a356-15f4-4ac4-9ed5-394c574debc3/trace.json
--trace.nomemory    /tmp/3d57a356-15f4-4ac4-9ed5-394c574debc3/trace.json
--trace.nostack   /tmp/3d57a356-15f4-4ac4-9ed5-394c574debc3/trace.json
```

where trace.json contains tx execution log like
```
TXHASH: 
LOG

TXHASH: 
LOG
```

most cases we log only one transaction. so might need a selector argument:

```
--tracetxhash     (for already generated tests)
--tracetxindex    (when generating tests. tx hash is unknown)
```

### PR DESCRIPTION
**Pull request by holiman**
This PR adds two features requested in https://github.com/ethereum/go-ethereum/issues/21373 

- output basedir, 
- txhash into the name of the tracefile

Closes #21373

### CODE REVIEW

**Comment by holiman** [comment]
@winsvega please check if it works the way you expected

**Comment by winsvega** [comment]
backward compatibility? 
```
Error: The command '/home/wins/.retesteth/t8ntool/start.sh --input.alloc /tmp/3b618bc2-bf95-4761-af39-cc58d7295d52/alloc.json --input.txs /tmp/3b618bc2-bf95-4761-af39-cc58d7295d52/txs.json --input.env /tmp/3b618bc2-bf95-4761-af39-cc58d7295d52/env.json --state.fork YOLOv1 --output.result /tmp/3b618bc2-bf95-4761-af39-cc58d7295d52/out.json --output.alloc /tmp/3b618bc2-bf95-4761-af39-cc58d7295d52/outAlloc.json' exited with 2816 code. (stExample/add11, step: GeneralStateTest)
```
```
ERROR(11): failed writing output: open tmp/3b618bc2-bf95-4761-af39-cc58d7295d52/outAlloc.json: no such file or directory
```

**Comment by holiman** [comment]
@winsvega pushed a fix, please try again

**Comment by winsvega** [comment]
works

**Review by MariusVanDerWijden — APPROVED** [review]
LGTM

**Pull request merged**
