### PR TITLE
core/txpool, eth/catalyst:  ensure gas tip retains current value upon rollback

### PR DESCRIPTION
**Pull request by jwasinger**

### CODE REVIEW

**Review by holiman — APPROVED** [review]
LGTM. 

But looking at what's happening here, it's that the Rollback-code is using `SetGasTip` as a hack to flush transactions from the pools. 
This PR further entrenches that hack, by making the API more accomodating: returning the previous value. 

A more "proper" fix might have been instead to introduce a method, `Flush` or `DropAll` or whatever, which just makes the pool(s) discard transactions ? 

I'm really mostly thinking aloud, haven't looked at it in any depth.

**Comment by jwasinger** [comment]
Yeah, this is a good point.  It's worth looking into instead of modifying the API to accommodate a hack.  I will take a look into it.

**Comment by jwasinger** [comment]
Diff is now larger, but it's less of a hack and a somewhat-trivial change.

**Review by fjl — APPROVED** [review]

**Comment by holiman** [comment]
This was reverted. 

The way of moving this threshold-juggling into the pool is not The Way, but rather to write a  `Flush` or `Clear` or `DropAll` makes the pool(s) discard transactions. Such a method is semantically sound, easy to reason about and is arguably a "basic" method for any API to contain. 

So, please make second attempt.

**Comment by jwasinger** [comment]
working on it 👍

**Pull request merged**
